// Unit test of the internal pak units: PakFile (open file, stamp, exact reads)
// and PakIndexRead (the rules of the pak format, one detail text each). Every
// pak is generated by PakTestSupport.hpp.

#include "PakTestSupport.hpp"
#include "TestPaths.hpp"

#include "internal/PakAccess.hpp"
#include "internal/PakFile.hpp"
#include "internal/PakIndex.hpp"

#include <chrono>
#include <cstdint>
#include <exception>
#include <filesystem>
#include <fstream>
#include <limits>
#include <string>
#include <vector>

using namespace seed::internal;

namespace
{
    std::vector<std::uint8_t> Filled(std::size_t count, std::uint8_t first)
    {
        std::vector<std::uint8_t> bytes(count);
        for(std::size_t i = 0; i < count; ++i)
        {
            bytes[i] = static_cast<std::uint8_t>(first + i);
        }
        return bytes;
    }

    // Data bytes never hold a newline, so the first newline of a pak is the
    // end of its description.
    seedtest::PakSpec SampleSpec()
    {
        seedtest::PakSpec spec;
        spec.name = "org/sample";
        spec.resources.push_back({"alpha", Filled(100, 0x41), ""});
        spec.resources.push_back({"empty", {}, ""});
        spec.resources.push_back({"beta", Filled(37, 0x61), "{\"kind\":\"sound\"}"});
        return spec;
    }

    std::size_t DescriptionLength(const std::vector<std::uint8_t> &bytes)
    {
        for(std::size_t i = 0; i < bytes.size(); ++i)
        {
            if(bytes[i] == '\n')
            {
                return i + 1;
            }
        }
        return 0;
    }

    bool Contains(const std::string &text, const std::string &part)
    {
        return text.find(part) != std::string::npos;
    }

    // Writes the bytes as a pak file, reads its index and returns the detail
    // text of the PakDamaged it must throw. Any other outcome fails the test.
    std::string DamageDetail(const std::vector<std::uint8_t> &bytes)
    {
        seedtest::ScratchDir scratch;
        const std::filesystem::path path = scratch.Path() / "damaged.pak";
        seedtest::WriteBytes(path, bytes);

        PakFile file = PakFile::Open(path);
        try
        {
            PakIndexRead(file);
        }
        catch(const PakDamaged &damaged)
        {
            return damaged.what();
        }
        catch(const std::exception &other)
        {
            FAIL("expected PakDamaged, got another exception: " << other.what());
        }
        catch(...)
        {
            FAIL("expected PakDamaged, got an exception of another type");
        }
        FAIL("expected PakDamaged, the pak was accepted");
        return "";
    }

    std::shared_ptr<const PakIndex> IndexOf(const std::vector<std::uint8_t> &bytes)
    {
        seedtest::ScratchDir scratch;
        const std::filesystem::path path = scratch.Path() / "sound.pak";
        seedtest::WriteBytes(path, bytes);
        PakFile file = PakFile::Open(path);
        return PakIndexRead(file);
    }

    const std::string unmarked = "{\"headerSize\":\"@@@@@@@@@@\",\"resources\":";
}

TEST_CASE("PakFile opens a pak and reads exact bytes", "[PakIndex]")
{
    seedtest::ScratchDir scratch;
    const std::vector<std::uint8_t> bytes = seedtest::PakBytes(SampleSpec());
    const std::filesystem::path path = seedtest::WritePakFile(scratch.Path(), "sample.pak", SampleSpec());

    PakFile file = PakFile::Open(path);

    SECTION("ReadAt returns the bytes at the offset")
    {
        std::vector<std::uint8_t> got(25);
        file.ReadAt(10, got.data(), got.size());
        REQUIRE(got == std::vector<std::uint8_t>(bytes.begin() + 10, bytes.begin() + 35));
    }

    SECTION("ReadAt reads the very last bytes")
    {
        std::vector<std::uint8_t> got(5);
        file.ReadAt(bytes.size() - 5, got.data(), got.size());
        REQUIRE(got == std::vector<std::uint8_t>(bytes.end() - 5, bytes.end()));
    }

    SECTION("ReadAt of the whole file returns every byte")
    {
        std::vector<std::uint8_t> got(bytes.size());
        file.ReadAt(0, got.data(), got.size());
        REQUIRE(got == bytes);
    }

    SECTION("A read past the end throws with the short-read text")
    {
        std::vector<std::uint8_t> got(10);
        try
        {
            file.ReadAt(bytes.size() - 4, got.data(), got.size());
            FAIL("a read past the end did not throw");
        }
        catch(const std::exception &error)
        {
            REQUIRE(Contains(error.what(), "shorter than its description"));
        }
    }

    SECTION("A read starting past the end throws")
    {
        std::vector<std::uint8_t> got(1);
        REQUIRE_THROWS(file.ReadAt(bytes.size() + 100, got.data(), got.size()));
    }

    SECTION("PakBytesReadCount grows by exactly the bytes read")
    {
        ResetPakBytesReadCount();
        REQUIRE(PakBytesReadCount() == 0);

        std::vector<std::uint8_t> got(100);
        file.ReadAt(0, got.data(), 40);
        REQUIRE(PakBytesReadCount() == 40);
        file.ReadAt(50, got.data(), 60);
        REQUIRE(PakBytesReadCount() == 100);

        ResetPakBytesReadCount();
        REQUIRE(PakBytesReadCount() == 0);
    }
}

TEST_CASE("PakFile open failures carry the system text", "[PakIndex]")
{
    seedtest::ScratchDir scratch;

    try
    {
        PakFile::Open(scratch.Path() / "absent.pak");
        FAIL("opening a missing file did not throw");
    }
    catch(const std::exception &error)
    {
        REQUIRE_FALSE(std::string(error.what()).empty());
#ifndef _WIN32
        REQUIRE(Contains(error.what(), "No such file or directory"));
#endif
    }
}

TEST_CASE("PakFile stamp identifies one version of a file", "[PakIndex]")
{
    seedtest::ScratchDir scratch;
    const std::filesystem::path path = seedtest::WritePakFile(scratch.Path(), "sample.pak", SampleSpec());

    PakFile first = PakFile::Open(path);
    const PakStamp before = first.Stamp();

    SECTION("Two opens of the same file are equal")
    {
        PakFile second = PakFile::Open(path);
        REQUIRE(second.Stamp() == before);
        REQUIRE(first.Stamp() == before);
    }

    SECTION("Replacing the file by rename differs")
    {
        // The first handle stays open, so the old file keeps its identity and
        // the new one cannot reuse it.
        seedtest::PakSpec other = SampleSpec();
        other.resources[0].bytes = Filled(100, 0x71);
        const std::filesystem::path staged = seedtest::WritePakFile(scratch.Path(), "staged.pak", other);
        std::filesystem::rename(staged, path);

        PakFile second = PakFile::Open(path);
        REQUIRE_FALSE(second.Stamp() == before);
        REQUIRE(first.Stamp() == before);
    }

    SECTION("A change of size differs")
    {
        {
            std::ofstream out(path, std::ios::binary | std::ios::app);
            out << "more";
        }
        PakFile second = PakFile::Open(path);
        REQUIRE_FALSE(second.Stamp() == before);
        REQUIRE(second.Stamp().size == before.size + 4);
    }

    SECTION("A change of modification time differs")
    {
        const auto time = std::filesystem::last_write_time(path);
        std::filesystem::last_write_time(path, time + std::chrono::seconds(30));

        PakFile second = PakFile::Open(path);
        REQUIRE_FALSE(second.Stamp() == before);
        REQUIRE(second.Stamp().size == before.size);
    }

    SECTION("The size field is the size of the file")
    {
        REQUIRE(before.size == seedtest::PakBytes(SampleSpec()).size());
    }
}

TEST_CASE("PakIndexRead lists a sound pak in description order", "[PakIndex]")
{
    seedtest::ScratchDir scratch;
    const seedtest::PakSpec spec = SampleSpec();
    const std::vector<std::uint8_t> bytes = seedtest::PakBytes(spec);
    const std::filesystem::path path = seedtest::WritePakFile(scratch.Path(), "sample.pak", spec);

    PakFile file = PakFile::Open(path);
    ResetPakDescriptionParseCount();
    const std::shared_ptr<const PakIndex> index = PakIndexRead(file);

    REQUIRE(PakDescriptionParseCount() == 1);
    REQUIRE(index != nullptr);
    REQUIRE(index->stamp == file.Stamp());

    const std::uint64_t length = DescriptionLength(bytes);
    REQUIRE(index->description_size == length);
    REQUIRE(index->entries.size() == 3);

    REQUIRE(index->entries[0].name == "alpha");
    REQUIRE(index->entries[0].offset == length);
    REQUIRE(index->entries[0].size == 100);
    REQUIRE(index->entries[1].name == "empty");
    REQUIRE(index->entries[1].offset == length + 100);
    REQUIRE(index->entries[1].size == 0);
    REQUIRE(index->entries[2].name == "beta");
    REQUIRE(index->entries[2].offset == length + 100);
    REQUIRE(index->entries[2].size == 37);

    REQUIRE(index->by_name.size() == 3);
    REQUIRE(index->by_name.at("alpha") == 0);
    REQUIRE(index->by_name.at("empty") == 1);
    REQUIRE(index->by_name.at("beta") == 2);

    SECTION("The offsets point at the resource bytes")
    {
        for(std::size_t i = 0; i < index->entries.size(); ++i)
        {
            std::vector<std::uint8_t> got(index->entries[i].size);
            file.ReadAt(index->entries[i].offset, got.data(), got.size());
            REQUIRE(got == spec.resources[i].bytes);
        }
    }

    SECTION("Each read of a description counts once")
    {
        PakIndexRead(file);
        REQUIRE(PakDescriptionParseCount() == 2);
        ResetPakDescriptionParseCount();
        REQUIRE(PakDescriptionParseCount() == 0);
    }
}

TEST_CASE("PakIndexRead accepts the edge cases the format allows", "[PakIndex]")
{
    SECTION("An empty pak")
    {
        seedtest::PakSpec spec;
        spec.name = "org/empty";
        const std::vector<std::uint8_t> bytes = seedtest::PakBytes(spec);
        const std::shared_ptr<const PakIndex> index = IndexOf(bytes);

        REQUIRE(index->entries.empty());
        REQUIRE(index->by_name.empty());
        REQUIRE(index->description_size == bytes.size());
    }

    SECTION("A zero-size resource, alone")
    {
        seedtest::PakSpec spec;
        spec.name = "org/zero";
        spec.resources.push_back({"nothing", {}, ""});
        const std::shared_ptr<const PakIndex> index = IndexOf(seedtest::PakBytes(spec));

        REQUIRE(index->entries.size() == 1);
        REQUIRE(index->entries[0].size == 0);
    }

    SECTION("The top-level name is not checked")
    {
        const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());
        const std::vector<std::uint8_t> bytes = seedtest::PakDescriptionReplace(
            sound,
            "{\"name\":5,\"headerSize\":\"@@@@@@@@@@\",\"resources\":[{\"name\":\"alpha\",\"size\":100},"
            "{\"name\":\"empty\",\"size\":0},{\"name\":\"beta\",\"size\":37}]}",
            true);
        REQUIRE(IndexOf(bytes)->entries.size() == 3);
    }

    SECTION("Attributes of any kind and unknown keys are ignored")
    {
        const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());
        const std::vector<std::uint8_t> bytes = seedtest::PakDescriptionReplace(
            sound,
            "{\"extra\":[1,{\"a\":null}],\"headerSize\":\"@@@@@@@@@@\",\"resources\":[{\"size\":100,"
            "\"name\":\"alpha\",\"attributes\":7,\"more\":true},{\"name\":\"empty\",\"size\":0,\"attributes\":"
            "[1,2]},{\"name\":\"beta\",\"size\":37,\"attributes\":\"text\"}]}",
            true);
        const std::shared_ptr<const PakIndex> index = IndexOf(bytes);

        REQUIRE(index->entries.size() == 3);
        REQUIRE(index->entries[0].size == 100);
    }

    SECTION("Nesting just inside the limit")
    {
        const std::vector<std::uint8_t> bytes = seedtest::PakDescriptionNest(seedtest::PakBytes(SampleSpec()), 62);
        REQUIRE(IndexOf(bytes)->entries.size() == 3);
    }

    SECTION("Names with escapes are kept as the characters they stand for")
    {
        seedtest::PakSpec spec;
        spec.name = "org/escapes";
        spec.resources.push_back({"quo\"te", Filled(3, 1), ""});
        spec.resources.push_back({"back\\slash", Filled(3, 1), ""});
        spec.resources.push_back({"tab\tcontrol\x01", Filled(3, 1), ""});
        const std::shared_ptr<const PakIndex> index = IndexOf(seedtest::PakBytes(spec));

        REQUIRE(index->entries.size() == 3);
        REQUIRE(index->entries[0].name == "quo\"te");
        REQUIRE(index->entries[1].name == "back\\slash");
        REQUIRE(index->entries[2].name == "tab\tcontrol\x01");
    }
}

TEST_CASE("PakIndexRead: the description line must end within 64 MiB", "[PakIndex]")
{
    SECTION("No newline in a small file")
    {
        const std::vector<std::uint8_t> bytes = seedtest::PakNewlineRemove(seedtest::PakBytes(SampleSpec()));
        REQUIRE(DamageDetail(bytes) ==
                "no description line (no newline in the first " + std::to_string(bytes.size()) + " bytes)");
    }

    SECTION("An empty file")
    {
        REQUIRE(DamageDetail({}) == "no description line (no newline in the first 0 bytes)");
    }

    SECTION("No newline in more than 64 MiB")
    {
        const std::vector<std::uint8_t> bytes(67108864u + 16u, static_cast<std::uint8_t>('x'));
        REQUIRE(DamageDetail(bytes) == "description line is longer than 67108864 bytes");
    }
}

TEST_CASE("PakIndexRead: the description must be JSON, nested at most 64 levels", "[PakIndex]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    SECTION("Not JSON")
    {
        const std::string detail =
            DamageDetail(seedtest::PakDescriptionReplace(sound, "this is not json", false));
        REQUIRE(detail.rfind("description is not valid JSON: ", 0) == 0);
        REQUIRE(detail.size() > std::string("description is not valid JSON: ").size());
    }

    SECTION("Cut short")
    {
        const std::string detail =
            DamageDetail(seedtest::PakDescriptionReplace(sound, "{\"headerSize\":\"0000000030\",\"resou", false));
        REQUIRE(detail.rfind("description is not valid JSON: ", 0) == 0);
    }

    SECTION("An empty line")
    {
        const std::string detail = DamageDetail(seedtest::PakDescriptionReplace(sound, "", false));
        REQUIRE(detail.rfind("description is not valid JSON: ", 0) == 0);
    }

    SECTION("Text after the value")
    {
        const std::string detail = DamageDetail(seedtest::PakDescriptionReplace(sound, "{} trailing", false));
        REQUIRE(detail.rfind("description is not valid JSON: ", 0) == 0);
    }

    SECTION("Nested too deeply")
    {
        REQUIRE(DamageDetail(seedtest::PakDescriptionNest(sound, 66)) ==
                "description is nested deeper than 64 levels");
    }

    SECTION("Nested very deeply does not exhaust the stack")
    {
        REQUIRE(DamageDetail(seedtest::PakDescriptionNest(sound, 200000)) ==
                "description is nested deeper than 64 levels");
    }
}

TEST_CASE("PakIndexRead: the top level must be an object", "[PakIndex]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    for(const char *text : {"[1,2]", "7", "\"text\"", "null", "true"})
    {
        CAPTURE(text);
        REQUIRE(DamageDetail(seedtest::PakDescriptionReplace(sound, text, false)) ==
                "description is not a JSON object");
    }
}

TEST_CASE("PakIndexRead: headerSize must be a string of digits that fits 64 bits", "[PakIndex]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    SECTION("Missing")
    {
        REQUIRE(DamageDetail(seedtest::PakDescriptionReplace(sound, "{\"resources\":[]}", false)) ==
                "\"headerSize\" is missing");
    }

    SECTION("Not a string of decimal digits")
    {
        for(const char *value : {"123", "1.5", "true", "null", "[]", "\"12ab\"", "\"abc\"", "\"\"", "\"-5\"",
                                 "\" 12\"", "\"+12\"", "\"0x10\""})
        {
            CAPTURE(value);
            REQUIRE(DamageDetail(seedtest::PakHeaderSizeSet(sound, value)) ==
                    "\"headerSize\" is not a string of decimal digits");
        }
    }

    SECTION("Does not fit 64 bits")
    {
        REQUIRE(DamageDetail(seedtest::PakHeaderSizeSet(sound, "\"99999999999999999999\"")) ==
                "\"headerSize\" is out of range");
        REQUIRE(DamageDetail(seedtest::PakHeaderSizeSet(sound, "\"18446744073709551616\"")) ==
                "\"headerSize\" is out of range");
    }
}

TEST_CASE("PakIndexRead: headerSize must match the end of the description", "[PakIndex]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());
    const std::string end = std::to_string(DescriptionLength(sound));

    SECTION("Too small")
    {
        REQUIRE(DamageDetail(seedtest::PakHeaderSizeSet(sound, "\"0000000001\"")) ==
                "stated description length 1 does not match the description's end at byte " + end);
    }

    SECTION("Too large")
    {
        REQUIRE(DamageDetail(seedtest::PakHeaderSizeSet(sound, "\"0000099999\"")) ==
                "stated description length 99999 does not match the description's end at byte " + end);
    }

    SECTION("A name that is longer in bytes than in UTF-16 units, as the writer counts it")
    {
        seedtest::PakSpec spec;
        spec.name = "org/accents";
        spec.resources.push_back({"caf\xC3\xA9", Filled(10, 1), ""});
        const std::vector<std::uint8_t> bytes = seedtest::PakBytes(spec);
        const std::size_t offset = DescriptionLength(bytes);

        REQUIRE(DamageDetail(bytes) == "stated description length " + std::to_string(offset - 1) +
                                           " does not match the description's end at byte " +
                                           std::to_string(offset));
    }
}

TEST_CASE("PakIndexRead: resources must be an array", "[PakIndex]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    SECTION("Missing")
    {
        REQUIRE(DamageDetail(seedtest::PakDescriptionReplace(
                    sound, "{\"name\":\"x\",\"headerSize\":\"@@@@@@@@@@\"}", true)) ==
                "\"resources\" is missing");
    }

    SECTION("Not an array")
    {
        for(const char *value : {"{}", "7", "\"text\"", "null"})
        {
            CAPTURE(value);
            REQUIRE(DamageDetail(seedtest::PakDescriptionReplace(sound, unmarked + value + "}", true)) ==
                    "\"resources\" is not an array");
        }
    }
}

TEST_CASE("PakIndexRead: each resource is an object with a string name", "[PakIndex]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    SECTION("Not an object")
    {
        REQUIRE(DamageDetail(seedtest::PakDescriptionReplace(
                    sound, unmarked + "[{\"name\":\"a\",\"size\":0},5]}", true)) == "resource 1 is not an object");
        REQUIRE(DamageDetail(seedtest::PakDescriptionReplace(sound, unmarked + "[\"a\"]}", true)) ==
                "resource 0 is not an object");
    }

    SECTION("No name")
    {
        REQUIRE(DamageDetail(seedtest::PakDescriptionReplace(sound, unmarked + "[{\"size\":0}]}", true)) ==
                "resource 0 has no \"name\"");
    }

    SECTION("Name not a string")
    {
        REQUIRE(DamageDetail(seedtest::PakDescriptionReplace(
                    sound, unmarked + "[{\"name\":\"a\",\"size\":0},{\"name\":7,\"size\":0}]}", true)) ==
                "resource 1 \"name\" is not a string");
    }
}

TEST_CASE("PakIndexRead: each size is a non-negative integer that fits 64 bits", "[PakIndex]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    SECTION("No size")
    {
        REQUIRE(DamageDetail(seedtest::PakDescriptionReplace(sound, unmarked + "[{\"name\":\"x\"}]}", true)) ==
                "resource \"x\" has no \"size\"");
    }

    SECTION("Not a non-negative integer")
    {
        for(const char *value : {"-1", "1.5", "\"3\"", "null", "true", "[3]", "18446744073709551616",
                                 "99999999999999999999999"})
        {
            CAPTURE(value);
            REQUIRE(DamageDetail(seedtest::PakDescriptionReplace(
                        sound, unmarked + "[{\"name\":\"x\",\"size\":" + value + "}]}", true)) ==
                    "resource \"x\" \"size\" is not a non-negative integer");
        }
    }
}

TEST_CASE("PakIndexRead: names are unique", "[PakIndex]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    REQUIRE(DamageDetail(seedtest::PakEntryDuplicate(sound, 0)) == "resource \"alpha\" appears more than once");
    REQUIRE(DamageDetail(seedtest::PakEntryDuplicate(sound, 1)) == "resource \"empty\" appears more than once");
}

TEST_CASE("PakIndexRead: running offsets do not overflow", "[PakIndex]")
{
    seedtest::PakSpec one;
    one.name = "org/one";
    one.resources.push_back({"a", Filled(4, 1), ""});

    SECTION("A size near 2^64")
    {
        REQUIRE(DamageDetail(seedtest::PakSizeSet(seedtest::PakBytes(one), 0,
                                                  std::numeric_limits<std::uint64_t>::max())) ==
                "size of resource \"a\" is out of range");
        REQUIRE(DamageDetail(seedtest::PakSizeSet(seedtest::PakBytes(one), 0,
                                                  std::numeric_limits<std::uint64_t>::max() - 3)) ==
                "size of resource \"a\" is out of range");
    }

    SECTION("Sizes that overflow only together")
    {
        seedtest::PakSpec two = one;
        two.resources.push_back({"b", Filled(4, 1), ""});
        const std::uint64_t half = std::uint64_t{1} << 63;
        const std::vector<std::uint8_t> bytes =
            seedtest::PakSizeSet(seedtest::PakSizeSet(seedtest::PakBytes(two), 0, half), 1, half);

        REQUIRE(DamageDetail(bytes) == "size of resource \"b\" is out of range");
    }
}

TEST_CASE("PakIndexRead: the sizes explain the whole file", "[PakIndex]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());
    const std::size_t total = sound.size();

    SECTION("The file is shorter")
    {
        REQUIRE(DamageDetail(seedtest::PakTruncate(sound, 1)) ==
                "the description claims " + std::to_string(total) + " bytes but the file holds " +
                    std::to_string(total - 1));
        REQUIRE(DamageDetail(seedtest::PakTruncate(sound, 100)) ==
                "the description claims " + std::to_string(total) + " bytes but the file holds " +
                    std::to_string(total - 100));
    }

    SECTION("A size larger than the data")
    {
        const std::vector<std::uint8_t> bytes = seedtest::PakSizeSet(sound, 0, 5000);
        const std::uint64_t claimed = DescriptionLength(bytes) + 5000 + 0 + 37;
        REQUIRE(DamageDetail(bytes) == "the description claims " + std::to_string(claimed) +
                                           " bytes but the file holds " + std::to_string(bytes.size()));
    }

    SECTION("The file is longer")
    {
        REQUIRE(DamageDetail(seedtest::PakAppend(sound, 1)) ==
                "1 bytes of unexplained data after the last resource");
        REQUIRE(DamageDetail(seedtest::PakAppend(sound, 4096)) ==
                "4096 bytes of unexplained data after the last resource");
    }

    SECTION("A pak with no resources and trailing data")
    {
        seedtest::PakSpec empty;
        empty.name = "org/empty";
        REQUIRE(DamageDetail(seedtest::PakAppend(seedtest::PakBytes(empty), 3)) ==
                "3 bytes of unexplained data after the last resource");
    }
}

TEST_CASE("PakIndexRead reports the first rule broken, then the first resource", "[PakIndex]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    SECTION("A wrong description length before a wrong file length")
    {
        const std::vector<std::uint8_t> bytes =
            seedtest::PakTruncate(seedtest::PakHeaderSizeSet(sound, "\"0000000001\""), 5);
        REQUIRE(Contains(DamageDetail(bytes), "stated description length 1 "));
    }

    SECTION("A bad size before a wrong file length")
    {
        REQUIRE(DamageDetail(seedtest::PakAppend(
                    seedtest::PakDescriptionReplace(sound, unmarked + "[{\"name\":\"x\",\"size\":-1}]}", true), 4)) ==
                "resource \"x\" \"size\" is not a non-negative integer");
    }

    SECTION("The first bad resource, in description order")
    {
        REQUIRE(DamageDetail(seedtest::PakDescriptionReplace(
                    sound, unmarked + "[{\"name\":\"a\",\"size\":0},{\"name\":\"b\"},{\"name\":\"c\"}]}", true)) ==
                "resource \"b\" has no \"size\"");
    }
}

TEST_CASE("PakEntryRead reports a file that shrank after it was checked as damaged", "[PakIndex]")
{
    seedtest::ScratchDir scratch;
    const std::filesystem::path path = seedtest::WritePakFile(scratch.Path(), "sample.pak", SampleSpec());

    PakFile file = PakFile::Open(path);
    const auto index = PakIndexRead(file);
    const PakEntry &beta = index->entries[index->by_name.at("beta")];

    std::filesystem::resize_file(path, beta.offset + 10);

    ecs::Resource resource;
    try
    {
        PakEntryRead(file, beta, resource);
        FAIL("a read past the end did not throw");
    }
    catch(const PakDamaged &error)
    {
        REQUIRE(std::string(error.what()) ==
                "file is shorter than its description: expected 37 bytes of resource \"beta\" at offset " +
                    std::to_string(beta.offset) + ", got 10 (was it changed while being read?)");
    }
}
