// Every kind of damage a resource pak can have is reported as a LoadError
// (NotLoadable) whose detail starts with "damaged: " and names the rule that
// is broken, through PakLoader and through ResourcePak, and no other exception
// type escapes. Every pak is generated by PakTestSupport.hpp.

#include "PakTestSupport.hpp"
#include "TestPaths.hpp"

#include <libthe-seed/LoadError.hpp>
#include <libthe-seed/PakLoader.hpp>
#include <libthe-seed/ResourcePak.hpp>

#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <limits>
#include <string>
#include <vector>

namespace
{
    std::vector<std::uint8_t> Filled(std::size_t count, std::uint8_t first)
    {
        std::vector<std::uint8_t> bytes(count);
        for(std::size_t i = 0; i < count; ++i)
        {
            bytes[i] = static_cast<std::uint8_t>(first + i);
        }
        return bytes;
    }

    // Data bytes never hold a newline, so the first newline of a pak is the
    // end of its description.
    seedtest::PakSpec SampleSpec()
    {
        seedtest::PakSpec spec;
        spec.name = "org/sample";
        spec.resources.push_back({"alpha", Filled(100, 0x41), ""});
        spec.resources.push_back({"empty", {}, ""});
        spec.resources.push_back({"beta", Filled(37, 0x61), "{\"kind\":\"sound\"}"});
        return spec;
    }

    std::size_t DescriptionLength(const std::vector<std::uint8_t> &bytes)
    {
        for(std::size_t i = 0; i < bytes.size(); ++i)
        {
            if(bytes[i] == '\n')
            {
                return i + 1;
            }
        }
        return 0;
    }

    const std::string unmarked = "{\"headerSize\":\"@@@@@@@@@@\",\"resources\":";

    // What the detail of the error has to be after "damaged: ": all of it, or
    // (when `prefix` is set) its start, for texts that carry a parser message.
    struct Expected
    {
        std::string text;
        bool prefix = false;
    };

    void DetailCheck(const LoadError &error, const Expected &expected)
    {
        const std::string &detail = error.DetailGet();
        REQUIRE(detail.rfind("damaged: ", 0) == 0);
        const std::string rest = detail.substr(std::string("damaged: ").size());
        if(expected.prefix)
        {
            REQUIRE(rest.rfind(expected.text, 0) == 0);
            REQUIRE(rest.size() > expected.text.size());
        }
        else
        {
            REQUIRE(rest == expected.text);
        }
    }

    // Loads the pak through PakLoader and checks the error. Any other kind of
    // outcome fails the test.
    void LoaderCheck(const std::filesystem::path &dir, const std::string &file, const Expected &expected)
    {
        PakLoader loader;
        loader.PathAdd(dir.string());
        const std::string pak_name = std::filesystem::path(file).stem().string();
        const std::string absolute = (dir / file).string();

        for(int pass = 0; pass < 2; ++pass)
        {
            try
            {
                loader.Load(pak_name);
                FAIL("PakLoader accepted a damaged pak");
            }
            catch(const LoadError &error)
            {
                REQUIRE(error.ReasonGet() == LoadError::Reason::NotLoadable);
                REQUIRE(error.NameGet() == pak_name);
                REQUIRE(error.FileGet() == absolute);
                DetailCheck(error, expected);
                bool found = false;
                for(const LoadError::Location &location : error.LocationsGet())
                {
                    found = found || (location.state == LoadError::LocationState::Found &&
                                      location.path == dir.string());
                }
                REQUIRE(found);
            }
            catch(...)
            {
                FAIL("PakLoader let an exception other than LoadError escape");
            }
        }
    }

    // Opens the pak with ResourcePak and checks the error.
    void PakCheck(const std::filesystem::path &dir, const std::string &file, const Expected &expected)
    {
        const std::string absolute = (dir / file).string();
        try
        {
            ResourcePak pak(absolute);
            FAIL("ResourcePak accepted a damaged pak");
        }
        catch(const LoadError &error)
        {
            REQUIRE(error.ReasonGet() == LoadError::Reason::NotLoadable);
            REQUIRE(error.FileGet() == absolute);
            DetailCheck(error, expected);
        }
        catch(...)
        {
            FAIL("ResourcePak let an exception other than LoadError escape");
        }
    }

    // Writes the bytes as damaged.pak and checks both classes.
    void DamageCheck(const std::vector<std::uint8_t> &bytes, const Expected &expected)
    {
        seedtest::ScratchDir scratch;
        seedtest::WriteBytes(scratch.Path() / "damaged.pak", bytes);
        LoaderCheck(scratch.Path(), "damaged.pak", expected);
        PakCheck(scratch.Path(), "damaged.pak", expected);
    }

    void DamageCheck(const std::vector<std::uint8_t> &bytes, const std::string &detail)
    {
        DamageCheck(bytes, Expected{detail, false});
    }

    void DamageCheckPrefix(const std::vector<std::uint8_t> &bytes, const std::string &detail)
    {
        DamageCheck(bytes, Expected{detail, true});
    }
}

TEST_CASE("Damage R1: the description line must end within 64 MiB", "[PakDamage]")
{
    SECTION("A zero-length file")
    {
        DamageCheck({}, "no description line (no newline in the first 0 bytes)");
    }

    SECTION("No newline")
    {
        const std::vector<std::uint8_t> bytes = seedtest::PakNewlineRemove(seedtest::PakBytes(SampleSpec()));
        DamageCheck(bytes, "no description line (no newline in the first " + std::to_string(bytes.size()) +
                               " bytes)");
    }

    SECTION("A description longer than 64 MiB")
    {
        seedtest::ScratchDir scratch;
        const std::filesystem::path path = scratch.Path() / "damaged.pak";
        seedtest::WriteBytes(path, std::vector<std::uint8_t>(16, static_cast<std::uint8_t>('x')));
        // Extends the file with zero bytes, as a sparse file where the file
        // system allows it.
        std::filesystem::resize_file(path, 67108864u + 16u);

        const Expected expected{"description line is longer than 67108864 bytes", false};
        LoaderCheck(scratch.Path(), "damaged.pak", expected);
        PakCheck(scratch.Path(), "damaged.pak", expected);
    }
}

TEST_CASE("Damage R2: the description must be JSON nested at most 64 levels", "[PakDamage]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());
    const std::string invalid = "description is not valid JSON: ";

    SECTION("Not JSON")
    {
        DamageCheckPrefix(seedtest::PakDescriptionReplace(sound, "this is not json", false), invalid);
    }

    SECTION("Cut short")
    {
        DamageCheckPrefix(
            seedtest::PakDescriptionReplace(sound, "{\"headerSize\":\"0000000030\",\"resou", false), invalid);
    }

    SECTION("An empty line")
    {
        DamageCheckPrefix(seedtest::PakDescriptionReplace(sound, "", false), invalid);
    }

    SECTION("Text after the value")
    {
        DamageCheckPrefix(seedtest::PakDescriptionReplace(sound, "{} trailing", false), invalid);
    }

    SECTION("Nested too deeply")
    {
        DamageCheck(seedtest::PakDescriptionNest(sound, 66), "description is nested deeper than 64 levels");
    }

    SECTION("Nested very deeply")
    {
        DamageCheck(seedtest::PakDescriptionNest(sound, 200000),
                    "description is nested deeper than 64 levels");
    }
}

TEST_CASE("Damage R3: the top level must be an object", "[PakDamage]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    for(const char *text : {"[1,2]", "7", "\"text\"", "null", "true"})
    {
        CAPTURE(text);
        DamageCheck(seedtest::PakDescriptionReplace(sound, text, false), "description is not a JSON object");
    }
}

TEST_CASE("Damage R4: headerSize must be a string of digits that fits 64 bits", "[PakDamage]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    SECTION("Missing")
    {
        DamageCheck(seedtest::PakDescriptionReplace(sound, "{\"resources\":[]}", false),
                    "\"headerSize\" is missing");
    }

    SECTION("Numeric")
    {
        DamageCheck(seedtest::PakHeaderSizeSet(sound, "123"), "\"headerSize\" is not a string of decimal digits");
    }

    SECTION("Not digits")
    {
        for(const char *value : {"\"12ab\"", "\"abc\"", "\"\"", "\"-5\"", "\" 12\"", "\"0x10\"", "null"})
        {
            CAPTURE(value);
            DamageCheck(seedtest::PakHeaderSizeSet(sound, value),
                        "\"headerSize\" is not a string of decimal digits");
        }
    }

    SECTION("Out of range")
    {
        DamageCheck(seedtest::PakHeaderSizeSet(sound, "\"99999999999999999999\""),
                    "\"headerSize\" is out of range");
        DamageCheck(seedtest::PakHeaderSizeSet(sound, "\"18446744073709551616\""),
                    "\"headerSize\" is out of range");
    }
}

TEST_CASE("Damage R5: headerSize must match the end of the description", "[PakDamage]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());
    const std::string end = std::to_string(DescriptionLength(sound));

    SECTION("Too small")
    {
        DamageCheck(seedtest::PakHeaderSizeSet(sound, "\"0000000001\""),
                    "stated description length 1 does not match the description's end at byte " + end);
    }

    SECTION("Too large")
    {
        DamageCheck(seedtest::PakHeaderSizeSet(sound, "\"0000099999\""),
                    "stated description length 99999 does not match the description's end at byte " + end);
    }

    SECTION("A non-ASCII name, counted the writer's way")
    {
        seedtest::PakSpec spec;
        spec.name = "org/accents";
        spec.resources.push_back({"caf\xC3\xA9", Filled(10, 1), ""});
        const std::vector<std::uint8_t> bytes = seedtest::PakBytes(spec);
        const std::size_t offset = DescriptionLength(bytes);

        DamageCheck(bytes, "stated description length " + std::to_string(offset - 1) +
                               " does not match the description's end at byte " + std::to_string(offset));
    }
}

TEST_CASE("Damage R6: resources must be an array", "[PakDamage]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    SECTION("Missing")
    {
        DamageCheck(seedtest::PakDescriptionReplace(sound, "{\"name\":\"x\",\"headerSize\":\"@@@@@@@@@@\"}", true),
                    "\"resources\" is missing");
    }

    SECTION("Not an array")
    {
        for(const char *value : {"{}", "7", "\"text\"", "null"})
        {
            CAPTURE(value);
            DamageCheck(seedtest::PakDescriptionReplace(sound, unmarked + value + "}", true),
                        "\"resources\" is not an array");
        }
    }
}

TEST_CASE("Damage R7: each resource is an object with a string name", "[PakDamage]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    SECTION("An element that is not an object")
    {
        DamageCheck(seedtest::PakDescriptionReplace(sound, unmarked + "[{\"name\":\"a\",\"size\":0},5]}", true),
                    "resource 1 is not an object");
    }

    SECTION("No name")
    {
        DamageCheck(seedtest::PakDescriptionReplace(sound, unmarked + "[{\"size\":0}]}", true),
                    "resource 0 has no \"name\"");
    }

    SECTION("A name that is not a string")
    {
        DamageCheck(seedtest::PakDescriptionReplace(
                        sound, unmarked + "[{\"name\":\"a\",\"size\":0},{\"name\":7,\"size\":0}]}", true),
                    "resource 1 \"name\" is not a string");
    }
}

TEST_CASE("Damage R8: each size is a non-negative integer that fits 64 bits", "[PakDamage]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    SECTION("No size")
    {
        DamageCheck(seedtest::PakDescriptionReplace(sound, unmarked + "[{\"name\":\"x\"}]}", true),
                    "resource \"x\" has no \"size\"");
    }

    SECTION("A size that is not a non-negative integer")
    {
        for(const char *value : {"-1", "1.5", "\"3\"", "null", "18446744073709551616"})
        {
            CAPTURE(value);
            DamageCheck(seedtest::PakDescriptionReplace(
                            sound, unmarked + "[{\"name\":\"x\",\"size\":" + value + "}]}", true),
                        "resource \"x\" \"size\" is not a non-negative integer");
        }
    }
}

TEST_CASE("Damage R9: names are unique", "[PakDamage]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    DamageCheck(seedtest::PakEntryDuplicate(sound, 0), "resource \"alpha\" appears more than once");
}

TEST_CASE("Damage R10: running offsets do not overflow", "[PakDamage]")
{
    seedtest::PakSpec one;
    one.name = "org/one";
    one.resources.push_back({"a", Filled(4, 1), ""});

    SECTION("A size near 2^64")
    {
        DamageCheck(seedtest::PakSizeSet(seedtest::PakBytes(one), 0, std::numeric_limits<std::uint64_t>::max()),
                    "size of resource \"a\" is out of range");
        DamageCheck(
            seedtest::PakSizeSet(seedtest::PakBytes(one), 0, std::numeric_limits<std::uint64_t>::max() - 3),
            "size of resource \"a\" is out of range");
    }

    SECTION("Sizes that overflow only together")
    {
        seedtest::PakSpec two = one;
        two.resources.push_back({"b", Filled(4, 1), ""});
        const std::uint64_t half = std::uint64_t{1} << 63;
        DamageCheck(seedtest::PakSizeSet(seedtest::PakSizeSet(seedtest::PakBytes(two), 0, half), 1, half),
                    "size of resource \"b\" is out of range");
    }
}

TEST_CASE("Damage R11: the sizes explain the whole file", "[PakDamage]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());
    const std::size_t total = sound.size();

    SECTION("The file holds less than the description claims")
    {
        DamageCheck(seedtest::PakTruncate(sound, 1), "the description claims " + std::to_string(total) +
                                                         " bytes but the file holds " + std::to_string(total - 1));
        DamageCheck(seedtest::PakTruncate(sound, 100), "the description claims " + std::to_string(total) +
                                                           " bytes but the file holds " +
                                                           std::to_string(total - 100));
    }

    SECTION("A size larger than the data")
    {
        const std::vector<std::uint8_t> bytes = seedtest::PakSizeSet(sound, 0, 5000);
        const std::uint64_t claimed = DescriptionLength(bytes) + 5000 + 0 + 37;
        DamageCheck(bytes, "the description claims " + std::to_string(claimed) + " bytes but the file holds " +
                               std::to_string(bytes.size()));
    }

    SECTION("Trailing data, with the count")
    {
        DamageCheck(seedtest::PakAppend(sound, 1), "1 bytes of unexplained data after the last resource");
        DamageCheck(seedtest::PakAppend(sound, 4096), "4096 bytes of unexplained data after the last resource");
    }

    SECTION("A pak with no resources and trailing data")
    {
        seedtest::PakSpec empty;
        empty.name = "org/empty";
        DamageCheck(seedtest::PakAppend(seedtest::PakBytes(empty), 3),
                    "3 bytes of unexplained data after the last resource");
    }
}

TEST_CASE("Damage: the first rule broken is the one reported", "[PakDamage]")
{
    const std::vector<std::uint8_t> sound = seedtest::PakBytes(SampleSpec());

    SECTION("The first bad resource, in description order")
    {
        DamageCheck(seedtest::PakDescriptionReplace(
                        sound, unmarked + "[{\"name\":\"a\",\"size\":0},{\"name\":\"b\"},{\"name\":\"c\"}]}", true),
                    "resource \"b\" has no \"size\"");
    }

    SECTION("A broken size before trailing data")
    {
        DamageCheck(seedtest::PakAppend(
                        seedtest::PakDescriptionReplace(sound, unmarked + "[{\"name\":\"x\",\"size\":-1}]}", true),
                        4),
                    "resource \"x\" \"size\" is not a non-negative integer");
    }
}

TEST_CASE("A damaged pak is never reported as not found", "[PakDamage]")
{
    seedtest::ScratchDir scratch;
    seedtest::WriteBytes(scratch.Path() / "damaged.pak", {});

    PakLoader loader;
    loader.PathAdd(scratch.Path().string());

    SECTION("A filtered request")
    {
        try
        {
            loader.Load("damaged", {"anything"});
            FAIL("PakLoader accepted a damaged pak");
        }
        catch(const LoadError &error)
        {
            REQUIRE(error.ReasonGet() == LoadError::Reason::NotLoadable);
        }
        catch(...)
        {
            FAIL("an exception other than LoadError escaped");
        }
    }

    SECTION("An empty request")
    {
        try
        {
            loader.Load("damaged", {});
            FAIL("PakLoader accepted a damaged pak");
        }
        catch(const LoadError &error)
        {
            REQUIRE(error.ReasonGet() == LoadError::Reason::NotLoadable);
        }
        catch(...)
        {
            FAIL("an exception other than LoadError escaped");
        }
    }
}

TEST_CASE("A pak in no location is still not found", "[PakDamage]")
{
    seedtest::ScratchDir scratch;
    seedtest::ScratchDir other;
    PakLoader loader;
    loader.PathAdd(scratch.Path().string());
    loader.PathAdd(other.Path().string());

    try
    {
        loader.Load("absent");
        FAIL("PakLoader found a pak that is not there");
    }
    catch(const LoadError &error)
    {
        REQUIRE(error.ReasonGet() == LoadError::Reason::NotFound);
        REQUIRE(error.NameGet() == "absent");
        REQUIRE(error.LocationsGet().size() >= 2);
    }
    catch(...)
    {
        FAIL("an exception other than LoadError escaped");
    }
}
