libthe-seed: external/Catch2/examples/311-Gen-CustomCapture.cpp File Reference
311-Gen-CustomCapture.cpp File Reference
#include <catch2/catch_test_macros.hpp>
#include <catch2/generators/catch_generators_adapters.hpp>
#include <catch2/generators/catch_generators_random.hpp>
Functions
TEST_CASE ("Generate random doubles across different ranges", "[generator][example][advanced]")
Function Documentation
TEST_CASE()
TEST_CASE ("Generate random doubles across different ranges" , "" [generator][example][advanced])
Definition at line 24 of file 311-Gen-CustomCapture.cpp.
References CATCH_INTERNAL_LINEINFO, GENERATE, Catch::Generators::generate(), Catch::Generators::makeGenerators(), Catch::Generators::random(), REQUIRE, and Catch::Generators::take().