libthe-seed: Catch::Clara::Detail::ResultValueBase< T > Class Template Reference
Catch::Clara::Detail::ResultValueBase< T > Class Template Reference
#include <catch_amalgamated.hpp>
Public Member Functions
auto value () const -> T const &
auto value () const -> T const &
Protected Member Functions
ResultValueBase (ResultType type)
ResultValueBase (ResultValueBase const &other)
ResultValueBase (ResultType, T const &value)
auto operator= (ResultValueBase const &other) -> ResultValueBase &
~ResultValueBase () override
ResultValueBase (ResultType type)
ResultValueBase (ResultValueBase const &other)
ResultValueBase (ResultType, T const &value)
auto operator= (ResultValueBase const &other) -> ResultValueBase &
~ResultValueBase () override
Protected Member Functions inherited from Catch::Clara::Detail::ResultBase
ResultBase (ResultType type)
virtual ~ResultBase ()
ResultBase (ResultBase const &)=default
ResultBase & operator= (ResultBase const &)=default
ResultBase (ResultBase &&)=default
ResultBase & operator= (ResultBase &&)=default
virtual void enforceOk () const =0
ResultBase (ResultType type)
virtual ~ResultBase ()
ResultBase (ResultBase const &)=default
ResultBase & operator= (ResultBase const &)=default
ResultBase (ResultBase &&)=default
ResultBase & operator= (ResultBase &&)=default
virtual void enforceOk () const =0
Protected Attributes
union {
T m_value
};
union {
T m_value
};
Protected Attributes inherited from Catch::Clara::Detail::ResultBase
ResultType m_type
Detailed Description
template<typename T>
class Catch::Clara::Detail::ResultValueBase< T >
Definition at line 4594 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ResultValueBase() [1/6]
template<typename T> Catch::Clara::Detail::ResultValueBase< T >::ResultValueBase (ResultType type) inline protected
Definition at line 4602 of file catch_amalgamated.hpp.
References Catch::Clara::Detail::ResultBase::ResultBase().
Referenced by operator=(), and ResultValueBase().
ResultValueBase() [2/6]
template<typename T> Catch::Clara::Detail::ResultValueBase< T >::ResultValueBase (ResultValueBase< T > const & other) inline protected
Definition at line 4604 of file catch_amalgamated.hpp.
References Catch::Clara::Detail::ResultBase::m_type, m_value, Catch::Clara::Detail::Ok, Catch::Clara::Detail::ResultBase::ResultBase(), and ResultValueBase().
ResultValueBase() [3/6]
template<typename T> Catch::Clara::Detail::ResultValueBase< T >::ResultValueBase (ResultType , T const & value) inline protected
Definition at line 4610 of file catch_amalgamated.hpp.
References m_value, Catch::Clara::Detail::Ok, Catch::Clara::Detail::ResultBase::ResultBase(), and value().
~ResultValueBase() [1/2]
template<typename T> Catch::Clara::Detail::ResultValueBase< T >::~ResultValueBase () inline override protected
Definition at line 4624 of file catch_amalgamated.hpp.
References Catch::Clara::Detail::ResultBase::m_type, m_value, and Catch::Clara::Detail::Ok.
ResultValueBase() [4/6]
template<typename T> Catch::Clara::Detail::ResultValueBase< T >::ResultValueBase (ResultType type) inline protected
Definition at line 174 of file catch_clara.hpp.
References Catch::Clara::Detail::ResultBase::ResultBase().
ResultValueBase() [5/6]
template<typename T> Catch::Clara::Detail::ResultValueBase< T >::ResultValueBase (ResultValueBase< T > const & other) inline protected
Definition at line 176 of file catch_clara.hpp.
References Catch::Clara::Detail::ResultBase::m_type, m_value, Catch::Clara::Detail::Ok, Catch::Clara::Detail::ResultBase::ResultBase(), and ResultValueBase().
ResultValueBase() [6/6]
template<typename T> Catch::Clara::Detail::ResultValueBase< T >::ResultValueBase (ResultType , T const & value) inline protected
Definition at line 182 of file catch_clara.hpp.
References m_value, Catch::Clara::Detail::ResultBase::ResultBase(), and value().
~ResultValueBase() [2/2]
template<typename T> Catch::Clara::Detail::ResultValueBase< T >::~ResultValueBase () inline override protected
Definition at line 196 of file catch_clara.hpp.
References Catch::Clara::Detail::ResultBase::m_type, m_value, and Catch::Clara::Detail::Ok.
Member Function Documentation
operator=() [1/2]
template<typename T> auto Catch::Clara::Detail::ResultValueBase< T >::operator= (ResultValueBase< T > const & other) ->ResultValueBase & inline protected
Definition at line 4614 of file catch_amalgamated.hpp.
References Catch::Clara::Detail::ResultBase::m_type, m_value, Catch::Clara::Detail::Ok, Catch::Clara::Detail::ResultBase::operator=(), and ResultValueBase().
operator=() [2/2]
template<typename T> auto Catch::Clara::Detail::ResultValueBase< T >::operator= (ResultValueBase< T > const & other) ->ResultValueBase & inline protected
Definition at line 186 of file catch_clara.hpp.
References Catch::Clara::Detail::ResultBase::m_type, m_value, Catch::Clara::Detail::Ok, Catch::Clara::Detail::ResultBase::operator=(), and ResultValueBase().
value() [1/2]
template<typename T> auto Catch::Clara::Detail::ResultValueBase< T >::value () const->Tconst & inline
Definition at line 4596 of file catch_amalgamated.hpp.
References Catch::Clara::Detail::ResultBase::enforceOk(), and m_value.
Referenced by ResultValueBase().
value() [2/2]
template<typename T> auto Catch::Clara::Detail::ResultValueBase< T >::value () const->Tconst & inline
Definition at line 168 of file catch_clara.hpp.
References Catch::Clara::Detail::ResultBase::enforceOk(), and m_value.
Member Data Documentation
[union]
union { ... } Catch::Clara::Detail::ResultValueBase< T >
[union]
union { ... } Catch::Clara::Detail::ResultValueBase< T >
m_value
template<typename T> T Catch::Clara::Detail::ResultValueBase< T >::m_value
Definition at line 4630 of file catch_amalgamated.hpp.
Referenced by operator=(), ResultValueBase(), ResultValueBase(), value(), and ~ResultValueBase().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp