libthe-seed: Catch::AssertionResult Class Reference
Catch::AssertionResult Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
AssertionResult ()=delete
AssertionResult (AssertionInfo const &info, AssertionResultData &&data)
bool isOk () const
bool succeeded () const
ResultWas::OfType getResultType () const
bool hasExpression () const
bool hasMessage () const
std::string getExpression () const
std::string getExpressionInMacro () const
bool hasExpandedExpression () const
std::string getExpandedExpression () const
StringRef getMessage () const
SourceLineInfo getSourceInfo () const
StringRef getTestMacroName () const
AssertionResult ()=delete
AssertionResult (AssertionInfo const &info, AssertionResultData &&data)
bool isOk () const
bool succeeded () const
ResultWas::OfType getResultType () const
bool hasExpression () const
bool hasMessage () const
std::string getExpression () const
std::string getExpressionInMacro () const
bool hasExpandedExpression () const
std::string getExpandedExpression () const
StringRef getMessage () const
SourceLineInfo getSourceInfo () const
StringRef getTestMacroName () const
Public Attributes
AssertionInfo m_info
AssertionResultData m_resultData
Detailed Description
Definition at line 3482 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
AssertionResult() [1/4]
Catch::AssertionResult::AssertionResult () delete
References AssertionResult(), getExpandedExpression(), getExpression(), getExpressionInMacro(), getMessage(), getResultType(), getSourceInfo(), getTestMacroName(), hasExpandedExpression(), hasExpression(), hasMessage(), isOk(), and succeeded().
Referenced by AssertionResult().
AssertionResult() [2/4]
Catch::AssertionResult::AssertionResult (AssertionInfo const & info, AssertionResultData && data)
Definition at line 505 of file catch_amalgamated.cpp.
References CATCH_MOVE, m_info, and m_resultData.
AssertionResult() [3/4]
Catch::AssertionResult::AssertionResult () delete
AssertionResult() [4/4]
Catch::AssertionResult::AssertionResult (AssertionInfo const & info, AssertionResultData && data)
Member Function Documentation
getExpandedExpression() [1/2]
std::string Catch::AssertionResult::getExpandedExpression () const
Definition at line 562 of file catch_amalgamated.cpp.
References getExpression(), and m_resultData.
Referenced by Catch::CumulativeReporterBase::assertionEnded(), Catch::TeamCityReporter::assertionEnded(), Catch::XmlReporter::assertionEnded(), AssertionResult(), hasExpandedExpression(), and Catch::SonarQubeReporter::writeAssertion().
getExpandedExpression() [2/2]
std::string Catch::AssertionResult::getExpandedExpression () const
getExpression() [1/2]
std::string Catch::AssertionResult::getExpression () const
Definition at line 532 of file catch_amalgamated.cpp.
References Catch::isFalseTest(), and m_info.
Referenced by Catch::XmlReporter::assertionEnded(), AssertionResult(), getExpandedExpression(), hasExpandedExpression(), and Catch::SonarQubeReporter::writeAssertion().
getExpression() [2/2]
std::string Catch::AssertionResult::getExpression () const
getExpressionInMacro() [1/2]
std::string Catch::AssertionResult::getExpressionInMacro () const
Definition at line 545 of file catch_amalgamated.cpp.
References m_info.
Referenced by Catch::TeamCityReporter::assertionEnded(), AssertionResult(), and Catch::SonarQubeReporter::writeAssertion().
getExpressionInMacro() [2/2]
std::string Catch::AssertionResult::getExpressionInMacro () const
getMessage() [1/2]
StringRef Catch::AssertionResult::getMessage () const
Definition at line 569 of file catch_amalgamated.cpp.
References m_resultData.
Referenced by Catch::XmlReporter::assertionEnded(), AssertionResult(), and Catch::SonarQubeReporter::writeAssertion().
getMessage() [2/2]
StringRef Catch::AssertionResult::getMessage () const
getResultType() [1/2]
ResultWas::OfType Catch::AssertionResult::getResultType () const
Definition at line 520 of file catch_amalgamated.cpp.
References m_resultData.
Referenced by Catch::CompactReporter::assertionEnded(), Catch::ConsoleReporter::assertionEnded(), Catch::JunitReporter::assertionEnded(), Catch::MultiReporter::assertionEnded(), Catch::TeamCityReporter::assertionEnded(), Catch::XmlReporter::assertionEnded(), AssertionResult(), and Catch::SonarQubeReporter::writeAssertion().
getResultType() [2/2]
ResultWas::OfType Catch::AssertionResult::getResultType () const
getSourceInfo() [1/2]
SourceLineInfo Catch::AssertionResult::getSourceInfo () const
Definition at line 572 of file catch_amalgamated.cpp.
References m_info.
Referenced by Catch::TeamCityReporter::assertionEnded(), Catch::XmlReporter::assertionEnded(), AssertionResult(), and Catch::SonarQubeReporter::writeAssertion().
getSourceInfo() [2/2]
SourceLineInfo Catch::AssertionResult::getSourceInfo () const
getTestMacroName() [1/2]
StringRef Catch::AssertionResult::getTestMacroName () const
Definition at line 576 of file catch_amalgamated.cpp.
References m_info.
Referenced by Catch::XmlReporter::assertionEnded(), AssertionResult(), and Catch::SonarQubeReporter::writeAssertion().
getTestMacroName() [2/2]
StringRef Catch::AssertionResult::getTestMacroName () const
References m_info, and m_resultData.
hasExpandedExpression() [1/2]
bool Catch::AssertionResult::hasExpandedExpression () const
Definition at line 558 of file catch_amalgamated.cpp.
References getExpandedExpression(), getExpression(), and hasExpression().
Referenced by AssertionResult(), and Catch::SonarQubeReporter::writeAssertion().
hasExpandedExpression() [2/2]
bool Catch::AssertionResult::hasExpandedExpression () const
hasExpression() [1/2]
bool Catch::AssertionResult::hasExpression () const
Definition at line 524 of file catch_amalgamated.cpp.
References m_info.
Referenced by Catch::TeamCityReporter::assertionEnded(), Catch::XmlReporter::assertionEnded(), AssertionResult(), hasExpandedExpression(), and Catch::SonarQubeReporter::writeAssertion().
hasExpression() [2/2]
bool Catch::AssertionResult::hasExpression () const
hasMessage() [1/2]
bool Catch::AssertionResult::hasMessage () const
Definition at line 528 of file catch_amalgamated.cpp.
References m_resultData.
Referenced by AssertionResult(), and Catch::SonarQubeReporter::writeAssertion().
hasMessage() [2/2]
bool Catch::AssertionResult::hasMessage () const
isOk() [1/2]
bool Catch::AssertionResult::isOk () const
Definition at line 516 of file catch_amalgamated.cpp.
References Catch::isOk(), m_info, m_resultData, and Catch::shouldSuppressFailure().
Referenced by Catch::CompactReporter::assertionEnded(), Catch::ConsoleReporter::assertionEnded(), Catch::CumulativeReporterBase::assertionEnded(), Catch::TeamCityReporter::assertionEnded(), Catch::XmlReporter::assertionEnded(), AssertionResult(), Catch::RunContext::handleMessage(), Catch::RunContext::handleNonExpr(), and Catch::SonarQubeReporter::writeAssertion().
isOk() [2/2]
bool Catch::AssertionResult::isOk () const
succeeded() [1/2]
bool Catch::AssertionResult::succeeded () const
Definition at line 511 of file catch_amalgamated.cpp.
References Catch::isOk(), and m_resultData.
Referenced by Catch::XmlReporter::assertionEnded(), and AssertionResult().
succeeded() [2/2]
bool Catch::AssertionResult::succeeded () const
Member Data Documentation
m_info
AssertionInfo Catch::AssertionResult::m_info
Definition at line 3501 of file catch_amalgamated.hpp.
Referenced by AssertionResult(), getExpression(), getExpressionInMacro(), getSourceInfo(), getTestMacroName(), hasExpression(), and isOk().
m_resultData
AssertionResultData Catch::AssertionResult::m_resultData
Definition at line 3502 of file catch_amalgamated.hpp.
Referenced by AssertionResult(), getExpandedExpression(), getMessage(), getResultType(), getTestMacroName(), hasMessage(), isOk(), and succeeded().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/catch_assertion_result.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/catch_assertion_result.cpp