libthe-seed: Catch::XmlEncode Class Reference
Catch::XmlEncode Class Reference
#include <catch_amalgamated.hpp>
Public Types
enum ForWhat { ForTextNodes , ForAttributes , ForTextNodes , ForAttributes }
enum ForWhat { ForTextNodes , ForAttributes , ForTextNodes , ForAttributes }
Public Member Functions
XmlEncode (StringRef str, ForWhat forWhat=ForTextNodes)
void encodeTo (std::ostream &os) const
XmlEncode (StringRef str, ForWhat forWhat=ForTextNodes)
void encodeTo (std::ostream &os) const
Friends
std::ostream & operator<< (std::ostream &os, XmlEncode const &xmlEncode)
std::ostream & operator<< (std::ostream &os, XmlEncode const &xmlEncode)
Detailed Description
Helper for XML-encoding text (escaping angle brackets, quotes, etc)
Note: doesn't take ownership of passed strings, and thus the encoded string must outlive the encoding instance.
Definition at line 10469 of file catch_amalgamated.hpp.
Member Enumeration Documentation
ForWhat [1/2]
enum Catch::XmlEncode::ForWhat
Enumerator
ForTextNodes
ForAttributes
ForTextNodes
ForAttributes
Definition at line 10471 of file catch_amalgamated.hpp.
ForWhat [2/2]
enum Catch::XmlEncode::ForWhat
Enumerator
ForTextNodes
ForAttributes
ForTextNodes
ForAttributes
Definition at line 35 of file catch_xmlwriter.hpp.
Constructor & Destructor Documentation
XmlEncode() [1/2]
Catch::XmlEncode::XmlEncode (StringRef str, ForWhat forWhat = ForTextNodes)
Definition at line 7204 of file catch_amalgamated.cpp.
Referenced by encodeTo(), and operator<<.
XmlEncode() [2/2]
Catch::XmlEncode::XmlEncode (StringRef str, ForWhat forWhat = ForTextNodes)
References ForTextNodes.
Member Function Documentation
encodeTo() [1/2]
void Catch::XmlEncode::encodeTo (std::ostream & os) const
Definition at line 7209 of file catch_amalgamated.cpp.
References ForAttributes.
Referenced by operator<<.
encodeTo() [2/2]
void Catch::XmlEncode::encodeTo (std::ostream & os) const
References XmlEncode().
Friends And Related Symbol Documentation
operator<< [1/2]
std::ostream & operator<< (std::ostream & os, XmlEncode const & xmlEncode) friend
Definition at line 7303 of file catch_amalgamated.cpp.
References encodeTo(), and XmlEncode().
operator<< [2/2]
std::ostream & operator<< (std::ostream & os, XmlEncode const & xmlEncode) friend
Definition at line 7303 of file catch_amalgamated.cpp.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_xmlwriter.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_xmlwriter.cpp