libthe-seed: Catch::Detail::unique_ptr< T > Class Template Reference
Catch::Detail::unique_ptr< T > Class Template Reference
#include <catch_amalgamated.hpp>
Public Member Functions
constexpr unique_ptr (std::nullptr_t=nullptr)
constexpr unique_ptr (T *ptr)
template<typename U, typename = std::enable_if_t<std::is_base_of<T, U>::value>>
unique_ptr (unique_ptr< U > &&from)
template<typename U, typename = std::enable_if_t<std::is_base_of<T, U>::value>>
unique_ptr & operator= (unique_ptr< U > &&from)
unique_ptr (unique_ptr const &)=delete
unique_ptr & operator= (unique_ptr const &)=delete
unique_ptr (unique_ptr &&rhs) noexcept
unique_ptr & operator= (unique_ptr &&rhs) noexcept
~unique_ptr ()
T & operator* ()
T const & operator* () const
T * operator-> () noexcept
T const * operator-> () const noexcept
T * get ()
T const * get () const
void reset (T *ptr=nullptr)
T * release ()
operator bool () const
constexpr unique_ptr (std::nullptr_t=nullptr)
constexpr unique_ptr (T *ptr)
template<typename U, typename = std::enable_if_t<std::is_base_of<T, U>::value>>
unique_ptr (unique_ptr< U > &&from)
template<typename U, typename = std::enable_if_t<std::is_base_of<T, U>::value>>
unique_ptr & operator= (unique_ptr< U > &&from)
unique_ptr (unique_ptr const &)=delete
unique_ptr & operator= (unique_ptr const &)=delete
unique_ptr (unique_ptr &&rhs) noexcept
unique_ptr & operator= (unique_ptr &&rhs) noexcept
~unique_ptr ()
T & operator* ()
T const & operator* () const
T * operator-> () noexcept
T const * operator-> () const noexcept
T * get ()
T const * get () const
void reset (T *ptr=nullptr)
T * release ()
operator bool () const
Friends
void swap (unique_ptr &lhs, unique_ptr &rhs)
void swap (unique_ptr &lhs, unique_ptr &rhs)
Detailed Description
template<typename T>
class Catch::Detail::unique_ptr< T >
A reimplementation of std::unique_ptr for improved compilation performance
Does not support arrays nor custom deleters.
Definition at line 853 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
unique_ptr() [1/10]
template<typename T> Catch::Detail::unique_ptr< T >::unique_ptr (std::nullptr_t = nullptr) inline constexpr
Definition at line 856 of file catch_amalgamated.hpp.
unique_ptr() [2/10]
template<typename T> Catch::Detail::unique_ptr< T >::unique_ptr (T * ptr) inline explicit constexpr
Definition at line 859 of file catch_amalgamated.hpp.
unique_ptr() [3/10]
template<typename T> template<typename U, typename = std::enable_if_t<std::is_base_of<T, U>::value>> Catch::Detail::unique_ptr< T >::unique_ptr (unique_ptr< U > && from) inline
Definition at line 864 of file catch_amalgamated.hpp.
unique_ptr() [4/10]
template<typename T> Catch::Detail::unique_ptr< T >::unique_ptr (unique_ptr< T > const &) delete
unique_ptr() [5/10]
template<typename T> Catch::Detail::unique_ptr< T >::unique_ptr (unique_ptr< T > && rhs) inline noexcept
Definition at line 878 of file catch_amalgamated.hpp.
~unique_ptr() [1/2]
template<typename T> Catch::Detail::unique_ptr< T >::~unique_ptr () inline
Definition at line 888 of file catch_amalgamated.hpp.
unique_ptr() [6/10]
template<typename T> Catch::Detail::unique_ptr< T >::unique_ptr (std::nullptr_t = nullptr) inline constexpr
Definition at line 27 of file catch_unique_ptr.hpp.
unique_ptr() [7/10]
template<typename T> Catch::Detail::unique_ptr< T >::unique_ptr (T * ptr) inline explicit constexpr
Definition at line 30 of file catch_unique_ptr.hpp.
unique_ptr() [8/10]
template<typename T> template<typename U, typename = std::enable_if_t<std::is_base_of<T, U>::value>> Catch::Detail::unique_ptr< T >::unique_ptr (unique_ptr< U > && from) inline
Definition at line 35 of file catch_unique_ptr.hpp.
unique_ptr() [9/10]
template<typename T> Catch::Detail::unique_ptr< T >::unique_ptr (unique_ptr< T > const &) delete
unique_ptr() [10/10]
template<typename T> Catch::Detail::unique_ptr< T >::unique_ptr (unique_ptr< T > && rhs) inline noexcept
Definition at line 49 of file catch_unique_ptr.hpp.
~unique_ptr() [2/2]
template<typename T> Catch::Detail::unique_ptr< T >::~unique_ptr () inline
Definition at line 59 of file catch_unique_ptr.hpp.
Member Function Documentation
get() [1/4]
template<typename T> T * Catch::Detail::unique_ptr< T >::get () inline
Definition at line 909 of file catch_amalgamated.hpp.
Referenced by Catch::TestRegistry::registerTest().
get() [2/4]
template<typename T> T * Catch::Detail::unique_ptr< T >::get () inline
Definition at line 80 of file catch_unique_ptr.hpp.
get() [3/4]
template<typename T> T const * Catch::Detail::unique_ptr< T >::get () const inline
Definition at line 910 of file catch_amalgamated.hpp.
get() [4/4]
template<typename T> T const * Catch::Detail::unique_ptr< T >::get () const inline
Definition at line 81 of file catch_unique_ptr.hpp.
operator bool() [1/2]
template<typename T> Catch::Detail::unique_ptr< T >::operator bool () const inline explicit
Definition at line 923 of file catch_amalgamated.hpp.
operator bool() [2/2]
template<typename T> Catch::Detail::unique_ptr< T >::operator bool () const inline explicit
Definition at line 94 of file catch_unique_ptr.hpp.
operator*() [1/4]
template<typename T> T & Catch::Detail::unique_ptr< T >::operator* () inline
Definition at line 892 of file catch_amalgamated.hpp.
operator*() [2/4]
template<typename T> T & Catch::Detail::unique_ptr< T >::operator* () inline
Definition at line 63 of file catch_unique_ptr.hpp.
operator*() [3/4]
template<typename T> T const & Catch::Detail::unique_ptr< T >::operator* () const inline
Definition at line 896 of file catch_amalgamated.hpp.
operator*() [4/4]
template<typename T> T const & Catch::Detail::unique_ptr< T >::operator* () const inline
Definition at line 67 of file catch_unique_ptr.hpp.
operator->() [1/4]
template<typename T> T const * Catch::Detail::unique_ptr< T >::operator-> () const inline noexcept
Definition at line 904 of file catch_amalgamated.hpp.
operator->() [2/4]
template<typename T> T const * Catch::Detail::unique_ptr< T >::operator-> () const inline noexcept
Definition at line 75 of file catch_unique_ptr.hpp.
operator->() [3/4]
template<typename T> T * Catch::Detail::unique_ptr< T >::operator-> () inline noexcept
Definition at line 900 of file catch_amalgamated.hpp.
operator->() [4/4]
template<typename T> T * Catch::Detail::unique_ptr< T >::operator-> () inline noexcept
Definition at line 71 of file catch_unique_ptr.hpp.
operator=() [1/6]
template<typename T> unique_ptr & Catch::Detail::unique_ptr< T >::operator= (unique_ptr< T > && rhs) inline noexcept
Definition at line 882 of file catch_amalgamated.hpp.
operator=() [2/6]
template<typename T> unique_ptr & Catch::Detail::unique_ptr< T >::operator= (unique_ptr< T > && rhs) inline noexcept
Definition at line 53 of file catch_unique_ptr.hpp.
operator=() [3/6]
template<typename T> unique_ptr & Catch::Detail::unique_ptr< T >::operator= (unique_ptr< T > const &) delete
operator=() [4/6]
template<typename T> unique_ptr & Catch::Detail::unique_ptr< T >::operator= (unique_ptr< T > const &) delete
operator=() [5/6]
template<typename T> template<typename U, typename = std::enable_if_t<std::is_base_of<T, U>::value>> unique_ptr & Catch::Detail::unique_ptr< T >::operator= (unique_ptr< U > && from) inline
Definition at line 869 of file catch_amalgamated.hpp.
operator=() [6/6]
template<typename T> template<typename U, typename = std::enable_if_t<std::is_base_of<T, U>::value>> unique_ptr & Catch::Detail::unique_ptr< T >::operator= (unique_ptr< U > && from) inline
Definition at line 40 of file catch_unique_ptr.hpp.
release() [1/2]
template<typename T> T * Catch::Detail::unique_ptr< T >::release () inline
Definition at line 917 of file catch_amalgamated.hpp.
release() [2/2]
template<typename T> T * Catch::Detail::unique_ptr< T >::release () inline
Definition at line 88 of file catch_unique_ptr.hpp.
reset() [1/2]
template<typename T> void Catch::Detail::unique_ptr< T >::reset (T * ptr = nullptr) inline
Definition at line 912 of file catch_amalgamated.hpp.
Referenced by Catch::Detail::unique_ptr< GeneratorUntypedBase >::operator=(), and Catch::Detail::unique_ptr< GeneratorUntypedBase >::operator=().
reset() [2/2]
template<typename T> void Catch::Detail::unique_ptr< T >::reset (T * ptr = nullptr) inline
Definition at line 83 of file catch_unique_ptr.hpp.
Friends And Related Symbol Documentation
swap [1/2]
template<typename T> void swap (unique_ptr< T > & lhs, unique_ptr< T > & rhs) friend
Definition at line 927 of file catch_amalgamated.hpp.
swap [2/2]
template<typename T> void swap (unique_ptr< T > & lhs, unique_ptr< T > & rhs) friend
Definition at line 98 of file catch_unique_ptr.hpp.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_unique_ptr.hpp