libthe-seed: Catch::XmlReporter Class Reference
Catch::XmlReporter Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
XmlReporter (ReporterConfig &&_config)
~XmlReporter () override
virtual std::string getStylesheetRef () const
void writeSourceInfo (SourceLineInfo const &sourceInfo)
void testRunStarting (TestRunInfo const &testInfo) override
void testCaseStarting (TestCaseInfo const &testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void sectionStarting (SectionInfo const &sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &assertionStats) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &sectionStats) override
Called after a SECTION has finished running.
void testCaseEnded (TestCaseStats const &testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &testRunStats) override
void benchmarkPreparing (StringRef name) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef error) override
Called if running the benchmarks fails for any reason.
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
XmlReporter (ReporterConfig &&_config)
~XmlReporter () override
virtual std::string getStylesheetRef () const
void writeSourceInfo (SourceLineInfo const &sourceInfo)
void testRunStarting (TestRunInfo const &testInfo) override
void testCaseStarting (TestCaseInfo const &testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void sectionStarting (SectionInfo const &sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &assertionStats) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &sectionStats) override
Called after a SECTION has finished running.
void testCaseEnded (TestCaseStats const &testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &testRunStats) override
void benchmarkPreparing (StringRef name) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef error) override
Called if running the benchmarks fails for any reason.
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
Public Member Functions inherited from Catch::StreamingReporterBase
StreamingReporterBase (ReporterConfig &&_config)
~StreamingReporterBase () override
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void skipTest (TestCaseInfo const &) override
StreamingReporterBase (ReporterConfig &&_config)
~StreamingReporterBase () override
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void skipTest (TestCaseInfo const &) override
Public Member Functions inherited from Catch::ReporterBase
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
Public Member Functions inherited from Catch::IEventListener
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
Static Public Member Functions
static std::string getDescription ()
static std::string getDescription ()
Additional Inherited Members
Protected Attributes inherited from Catch::StreamingReporterBase
TestRunInfo currentTestRunInfo { "test run has not started yet"_sr }
TestCaseInfo const * currentTestCaseInfo = nullptr
std::vector< SectionInfo > m_sectionStack
Stack of all active sections in the current test case.
Protected Attributes inherited from Catch::ReporterBase
Detail::unique_ptr< IStream > m_wrapped_stream
The stream wrapper as passed to us by outside code.
std::ostream & m_stream
Cached output stream from m_wrapped_stream to reduce number of indirect calls needed to write output.
Detail::unique_ptr< ColourImpl > m_colour
Colour implementation this reporter was configured for.
std::map< std::string, std::string > m_customOptions
The custom reporter options user passed down to the reporter.
Protected Attributes inherited from Catch::IEventListener
ReporterPreferences m_preferences
Derived classes can set up their preferences here.
IConfig const * m_config
The test run's config as filled in from CLI and defaults.
Detailed Description
Definition at line 13090 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
XmlReporter() [1/2]
Catch::XmlReporter::XmlReporter (ReporterConfig && _config)
Definition at line 10486 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::IEventListener::m_preferences, Catch::ReporterBase::m_stream, and Catch::StreamingReporterBase::StreamingReporterBase().
~XmlReporter() [1/2]
Catch::XmlReporter::~XmlReporter () override default
References assertionEnded(), assertionStarting(), benchmarkEnded(), benchmarkFailed(), benchmarkPreparing(), benchmarkStarting(), getDescription(), getStylesheetRef(), listListeners(), listReporters(), listTags(), listTests(), sectionEnded(), sectionStarting(), testCaseEnded(), testCaseStarting(), testRunEnded(), testRunStarting(), and writeSourceInfo().
XmlReporter() [2/2]
Catch::XmlReporter::XmlReporter (ReporterConfig && _config)
~XmlReporter() [2/2]
Catch::XmlReporter::~XmlReporter () override
Member Function Documentation
assertionEnded() [1/2]
void Catch::XmlReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10550 of file catch_amalgamated.cpp.
References Catch::AssertionStats::assertionResult, Catch::ResultWas::ExplicitFailure, Catch::ResultWas::ExplicitSkip, Catch::ResultWas::FatalErrorCondition, Catch::AssertionResult::getExpandedExpression(), Catch::AssertionResult::getExpression(), Catch::AssertionResult::getMessage(), Catch::AssertionResult::getResultType(), Catch::AssertionResult::getSourceInfo(), Catch::AssertionResult::getTestMacroName(), Catch::AssertionResult::hasExpression(), Catch::ResultWas::Info, Catch::AssertionStats::infoMessages, Catch::AssertionResult::isOk(), Catch::IEventListener::m_config, Catch::AssertionResult::succeeded(), Catch::ResultWas::ThrewException, Catch::ResultWas::Warning, and writeSourceInfo().
Referenced by ~XmlReporter().
assertionEnded() [2/2]
void Catch::XmlReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Reimplemented from Catch::StreamingReporterBase.
assertionStarting() [1/2]
void Catch::XmlReporter::assertionStarting (AssertionInfo const & assertionInfo) override virtual
Called before assertion success/failure is evaluated.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10548 of file catch_amalgamated.cpp.
Referenced by ~XmlReporter().
assertionStarting() [2/2]
void Catch::XmlReporter::assertionStarting (AssertionInfo const & assertionInfo) override virtual
Called before assertion success/failure is evaluated.
Reimplemented from Catch::StreamingReporterBase.
benchmarkEnded() [1/2]
void Catch::XmlReporter::benchmarkEnded (BenchmarkStats<> const & benchmarkStats) override virtual
Called with the benchmark results if benchmark successfully finishes.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10695 of file catch_amalgamated.cpp.
References Catch::Benchmark::OutlierClassification::high_mild, Catch::Benchmark::OutlierClassification::high_severe, Catch::Benchmark::OutlierClassification::low_mild, Catch::Benchmark::OutlierClassification::low_severe, Catch::BenchmarkStats< Dummy >::mean, Catch::BenchmarkStats< Dummy >::outliers, Catch::BenchmarkStats< Dummy >::outlierVariance, and Catch::BenchmarkStats< Dummy >::standardDeviation.
Referenced by ~XmlReporter().
benchmarkEnded() [2/2]
void Catch::XmlReporter::benchmarkEnded (BenchmarkStats<> const & benchmarkStats) override virtual
Called with the benchmark results if benchmark successfully finishes.
Reimplemented from Catch::StreamingReporterBase.
benchmarkFailed() [1/2]
void Catch::XmlReporter::benchmarkFailed (StringRef benchmarkName) override virtual
Called if running the benchmarks fails for any reason.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10718 of file catch_amalgamated.cpp.
Referenced by ~XmlReporter().
benchmarkFailed() [2/2]
void Catch::XmlReporter::benchmarkFailed (StringRef benchmarkName) override virtual
Called if running the benchmarks fails for any reason.
Reimplemented from Catch::StreamingReporterBase.
benchmarkPreparing() [1/2]
void Catch::XmlReporter::benchmarkPreparing (StringRef benchmarkName) override virtual
Called when user-code is being probed before the actual benchmark runs.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10681 of file catch_amalgamated.cpp.
Referenced by ~XmlReporter().
benchmarkPreparing() [2/2]
void Catch::XmlReporter::benchmarkPreparing (StringRef benchmarkName) override virtual
Called when user-code is being probed before the actual benchmark runs.
Reimplemented from Catch::StreamingReporterBase.
benchmarkStarting() [1/2]
void Catch::XmlReporter::benchmarkStarting (BenchmarkInfo const & benchmarkInfo) override virtual
Called after probe but before the user-code is being benchmarked.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10686 of file catch_amalgamated.cpp.
References Catch::BenchmarkInfo::clockResolution, Catch::BenchmarkInfo::estimatedDuration, Catch::BenchmarkInfo::iterations, Catch::BenchmarkInfo::resamples, and Catch::BenchmarkInfo::samples.
Referenced by ~XmlReporter().
benchmarkStarting() [2/2]
void Catch::XmlReporter::benchmarkStarting (BenchmarkInfo const & benchmarkInfo) override virtual
Called after probe but before the user-code is being benchmarked.
Reimplemented from Catch::StreamingReporterBase.
getDescription() [1/2]
std::string Catch::XmlReporter::getDescription () static
Definition at line 10496 of file catch_amalgamated.cpp.
Referenced by ~XmlReporter().
getDescription() [2/2]
std::string Catch::XmlReporter::getDescription () static
getStylesheetRef() [1/2]
std::string Catch::XmlReporter::getStylesheetRef () const virtual
Definition at line 10500 of file catch_amalgamated.cpp.
Referenced by testRunStarting(), and ~XmlReporter().
getStylesheetRef() [2/2]
virtual std::string Catch::XmlReporter::getStylesheetRef () const virtual
listListeners() [1/2]
void Catch::XmlReporter::listListeners (std::vector< ListenerDescription > const & descriptions) override virtual
Provides a simple default listing of listeners
Looks similarly to listing of reporters, but with listener type instead of reporter name.
Reimplemented from Catch::ReporterBase.
Definition at line 10737 of file catch_amalgamated.cpp.
References Catch::Indent, Catch::Newline, and Catch::None.
Referenced by ~XmlReporter().
listListeners() [2/2]
void Catch::XmlReporter::listListeners (std::vector< ListenerDescription > const & descriptions) override virtual
Provides a simple default listing of listeners
Looks similarly to listing of reporters, but with listener type instead of reporter name.
Reimplemented from Catch::ReporterBase.
listReporters() [1/2]
void Catch::XmlReporter::listReporters (std::vector< ReporterDescription > const & descriptions) override virtual
Provides a simple default listing of reporters.
Should look roughly like the reporter listing in v2 and earlier versions of Catch2.
Reimplemented from Catch::ReporterBase.
Definition at line 10724 of file catch_amalgamated.cpp.
References Catch::Indent, Catch::Newline, and Catch::None.
Referenced by ~XmlReporter().
listReporters() [2/2]
void Catch::XmlReporter::listReporters (std::vector< ReporterDescription > const & descriptions) override virtual
Provides a simple default listing of reporters.
Should look roughly like the reporter listing in v2 and earlier versions of Catch2.
Reimplemented from Catch::ReporterBase.
listTags() [1/2]
void Catch::XmlReporter::listTags (std::vector< TagInfo > const & tags) override virtual
Provides a simple default listing of tags.
Should look roughly like the tag listing in v2 and earlier versions of Catch2.
Reimplemented from Catch::ReporterBase.
Definition at line 10775 of file catch_amalgamated.cpp.
References Catch::Indent, Catch::Newline, and Catch::None.
Referenced by ~XmlReporter().
listTags() [2/2]
void Catch::XmlReporter::listTags (std::vector< TagInfo > const & tags) override virtual
Provides a simple default listing of tags.
Should look roughly like the tag listing in v2 and earlier versions of Catch2.
Reimplemented from Catch::ReporterBase.
listTests() [1/2]
void Catch::XmlReporter::listTests (std::vector< TestCaseHandle > const & tests) override virtual
Provides a simple default listing of tests.
Should look roughly like the test listing in v2 and earlier versions of Catch2. Especially supports low-verbosity listing that mimics the old --list-test-names-only output.
Reimplemented from Catch::ReporterBase.
Definition at line 10750 of file catch_amalgamated.cpp.
References Catch::Indent, Catch::Newline, and Catch::None.
Referenced by ~XmlReporter().
listTests() [2/2]
void Catch::XmlReporter::listTests (std::vector< TestCaseHandle > const & tests) override virtual
Provides a simple default listing of tests.
Should look roughly like the test listing in v2 and earlier versions of Catch2. Especially supports low-verbosity listing that mimics the old --list-test-names-only output.
Reimplemented from Catch::ReporterBase.
sectionEnded() [1/2]
void Catch::XmlReporter::sectionEnded (SectionStats const & sectionStats) override virtual
Called after a SECTION has finished running.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10632 of file catch_amalgamated.cpp.
References Catch::Always, Catch::SectionStats::assertions, Catch::SectionStats::durationInSeconds, Catch::Counts::failed, Catch::Counts::failedButOk, Catch::IEventListener::m_config, Catch::Counts::passed, Catch::StreamingReporterBase::sectionEnded(), Catch::Counts::skipped, and Catch::XmlWriter::ScopedElement::writeAttribute().
Referenced by ~XmlReporter().
sectionEnded() [2/2]
void Catch::XmlReporter::sectionEnded (SectionStats const & sectionStats) override virtual
Called after a SECTION has finished running.
Reimplemented from Catch::StreamingReporterBase.
sectionStarting() [1/2]
void Catch::XmlReporter::sectionStarting (SectionInfo const & sectionInfo) override virtual
Called when a SECTION is being entered. Not called for skipped sections.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10538 of file catch_amalgamated.cpp.
References Catch::SectionInfo::lineInfo, Catch::SectionInfo::name, Catch::StreamingReporterBase::sectionStarting(), Catch::trim(), and writeSourceInfo().
Referenced by ~XmlReporter().
sectionStarting() [2/2]
void Catch::XmlReporter::sectionStarting (SectionInfo const & sectionInfo) override virtual
Called when a SECTION is being entered. Not called for skipped sections.
Reimplemented from Catch::StreamingReporterBase.
testCaseEnded() [1/2]
void Catch::XmlReporter::testCaseEnded (TestCaseStats const & testCaseStats) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10650 of file catch_amalgamated.cpp.
References Catch::Counts::allOk(), Catch::Always, Catch::Totals::assertions, Catch::IEventListener::m_config, Catch::Newline, Catch::Counts::skipped, Catch::TestCaseStats::stdErr, Catch::TestCaseStats::stdOut, Catch::StreamingReporterBase::testCaseEnded(), Catch::TestCaseStats::totals, Catch::trim(), Catch::XmlWriter::ScopedElement::writeAttribute(), and Catch::XmlWriter::ScopedElement::writeText().
Referenced by ~XmlReporter().
testCaseEnded() [2/2]
void Catch::XmlReporter::testCaseEnded (TestCaseStats const & testCaseStats) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Reimplemented from Catch::StreamingReporterBase.
testCaseStarting() [1/2]
void Catch::XmlReporter::testCaseStarting (TestCaseInfo const & testInfo) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10525 of file catch_amalgamated.cpp.
References Catch::Always, Catch::TestCaseInfo::lineInfo, Catch::IEventListener::m_config, Catch::TestCaseInfo::name, Catch::TestCaseInfo::tagsAsString(), Catch::StreamingReporterBase::testCaseStarting(), Catch::trim(), and writeSourceInfo().
Referenced by ~XmlReporter().
testCaseStarting() [2/2]
void Catch::XmlReporter::testCaseStarting (TestCaseInfo const & testInfo) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Reimplemented from Catch::StreamingReporterBase.
testRunEnded() [1/2]
void Catch::XmlReporter::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10666 of file catch_amalgamated.cpp.
References Catch::Totals::assertions, Catch::Counts::failed, Catch::Counts::failedButOk, Catch::Counts::passed, Catch::Counts::skipped, Catch::Totals::testCases, Catch::StreamingReporterBase::testRunEnded(), and Catch::TestRunStats::totals.
Referenced by ~XmlReporter().
testRunEnded() [2/2]
void Catch::XmlReporter::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Reimplemented from Catch::StreamingReporterBase.
testRunStarting() [1/2]
void Catch::XmlReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10510 of file catch_amalgamated.cpp.
References getStylesheetRef(), Catch::libraryVersion(), Catch::IEventListener::m_config, and Catch::StreamingReporterBase::testRunStarting().
Referenced by ~XmlReporter().
testRunStarting() [2/2]
void Catch::XmlReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Reimplemented from Catch::StreamingReporterBase.
writeSourceInfo() [1/2]
void Catch::XmlReporter::writeSourceInfo (SourceLineInfo const & sourceInfo)
Definition at line 10504 of file catch_amalgamated.cpp.
References Catch::SourceLineInfo::file, and Catch::SourceLineInfo::line.
Referenced by assertionEnded(), sectionStarting(), testCaseStarting(), and ~XmlReporter().
writeSourceInfo() [2/2]
void Catch::XmlReporter::writeSourceInfo (SourceLineInfo const & sourceInfo)
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/reporters/catch_reporter_xml.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/reporters/catch_reporter_xml.cpp