libthe-seed: Catch::ExceptionTranslatorRegistrar Class Reference
Catch::ExceptionTranslatorRegistrar Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
template<typename T>
ExceptionTranslatorRegistrar (std::string(*translateFunction)(T const &))
template<typename T>
ExceptionTranslatorRegistrar (std::string(*translateFunction)(T const &))
Detailed Description
Definition at line 7271 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ExceptionTranslatorRegistrar() [1/2]
template<typename T> Catch::ExceptionTranslatorRegistrar::ExceptionTranslatorRegistrar (std::string(* translateFunction)(T const &)) inline
Definition at line 7302 of file catch_amalgamated.hpp.
References Catch::Detail::make_unique(), and Catch::Detail::registerTranslatorImpl().
ExceptionTranslatorRegistrar() [2/2]
template<typename T> Catch::ExceptionTranslatorRegistrar::ExceptionTranslatorRegistrar (std::string(* translateFunction)(T const &)) inline
Definition at line 54 of file catch_translate_exception.hpp.
References Catch::Detail::make_unique(), and Catch::Detail::registerTranslatorImpl().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/catch_translate_exception.hpp