libthe-seed: Catch::Generators::SingleValueGenerator< T > Class Template Reference
Catch::Generators::SingleValueGenerator< T > Class Template Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
SingleValueGenerator (T const &value)
SingleValueGenerator (T &&value)
T const & get () const override
bool next () override
SingleValueGenerator (T const &value)
SingleValueGenerator (T &&value)
T const & get () const override
bool next () override
Public Member Functions inherited from Catch::Generators::IGenerator< T >
~IGenerator () override=default
IGenerator ()=default
IGenerator (IGenerator const &)=default
IGenerator & operator= (IGenerator const &)=default
~IGenerator () override=default
IGenerator ()=default
IGenerator (IGenerator const &)=default
IGenerator & operator= (IGenerator const &)=default
Public Member Functions inherited from Catch::Generators::GeneratorUntypedBase
GeneratorUntypedBase ()=default
GeneratorUntypedBase (GeneratorUntypedBase const &)=default
GeneratorUntypedBase & operator= (GeneratorUntypedBase const &)=default
virtual ~GeneratorUntypedBase ()
bool countedNext ()
std::size_t currentElementIndex () const
StringRef currentElementAsString () const
GeneratorUntypedBase ()=default
GeneratorUntypedBase (GeneratorUntypedBase const &)=default
GeneratorUntypedBase & operator= (GeneratorUntypedBase const &)=default
virtual ~GeneratorUntypedBase ()
bool countedNext ()
std::size_t currentElementIndex () const
StringRef currentElementAsString () const
Additional Inherited Members
Public Types inherited from Catch::Generators::IGenerator< T >
using type = T
using type = T
Detailed Description
template<typename T>
class Catch::Generators::SingleValueGenerator< T >
Definition at line 7573 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
SingleValueGenerator() [1/4]
template<typename T> Catch::Generators::SingleValueGenerator< T >::SingleValueGenerator (T const & value) inline
Definition at line 7576 of file catch_amalgamated.hpp.
References Catch::Generators::value().
SingleValueGenerator() [2/4]
template<typename T> Catch::Generators::SingleValueGenerator< T >::SingleValueGenerator (T && value) inline
Definition at line 7579 of file catch_amalgamated.hpp.
References CATCH_MOVE, and Catch::Generators::value().
SingleValueGenerator() [3/4]
template<typename T> Catch::Generators::SingleValueGenerator< T >::SingleValueGenerator (T const & value) inline
Definition at line 80 of file catch_generators.hpp.
References Catch::Generators::value().
SingleValueGenerator() [4/4]
template<typename T> Catch::Generators::SingleValueGenerator< T >::SingleValueGenerator (T && value) inline
Definition at line 83 of file catch_generators.hpp.
References CATCH_MOVE, and Catch::Generators::value().
Member Function Documentation
get() [1/2]
template<typename T> T const & Catch::Generators::SingleValueGenerator< T >::get () const inline override virtual
Implements Catch::Generators::IGenerator< T >.
Definition at line 7583 of file catch_amalgamated.hpp.
get() [2/2]
template<typename T> T const & Catch::Generators::SingleValueGenerator< T >::get () const inline override virtual
Implements Catch::Generators::IGenerator< T >.
Definition at line 87 of file catch_generators.hpp.
next() [1/2]
template<typename T> bool Catch::Generators::SingleValueGenerator< T >::next () inline override virtual
Attempts to move the generator to the next element
Returns true iff the move succeeded (and a valid element can be retrieved).
Implements Catch::Generators::GeneratorUntypedBase.
Definition at line 7586 of file catch_amalgamated.hpp.
next() [2/2]
template<typename T> bool Catch::Generators::SingleValueGenerator< T >::next () inline override virtual
Attempts to move the generator to the next element
Returns true iff the move succeeded (and a valid element can be retrieved).
Implements Catch::Generators::GeneratorUntypedBase.
Definition at line 90 of file catch_generators.hpp.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/generators/catch_generators.hpp