libthe-seed: Catch::SimplePcg32 Class Reference
Catch::SimplePcg32 Class Reference
#include <catch_amalgamated.hpp>
Public Types
using result_type = std::uint32_t
using result_type = std::uint32_t
Public Member Functions
SimplePcg32 ()
SimplePcg32 (result_type seed_)
void seed (result_type seed_)
void discard (uint64_t skip)
result_type operator() ()
SimplePcg32 ()
SimplePcg32 (result_type seed_)
void seed (result_type seed_)
void discard (uint64_t skip)
result_type operator() ()
Static Public Member Functions
static constexpr result_type min ()
static constexpr result_type max ()
static constexpr result_type min ()
static constexpr result_type max ()
Friends
bool operator== (SimplePcg32 const &lhs, SimplePcg32 const &rhs)
bool operator!= (SimplePcg32 const &lhs, SimplePcg32 const &rhs)
bool operator== (SimplePcg32 const &lhs, SimplePcg32 const &rhs)
bool operator!= (SimplePcg32 const &lhs, SimplePcg32 const &rhs)
Detailed Description
Definition at line 7999 of file catch_amalgamated.hpp.
Member Typedef Documentation
result_type [1/2]
using Catch::SimplePcg32::result_type = std::uint32_t
Definition at line 8002 of file catch_amalgamated.hpp.
result_type [2/2]
using Catch::SimplePcg32::result_type = std::uint32_t
Definition at line 23 of file catch_random_number_generator.hpp.
Constructor & Destructor Documentation
SimplePcg32() [1/4]
Catch::SimplePcg32::SimplePcg32 () inline
Definition at line 8011 of file catch_amalgamated.hpp.
References SimplePcg32().
Referenced by operator!=, operator()(), operator==, and SimplePcg32().
SimplePcg32() [2/4]
Catch::SimplePcg32::SimplePcg32 (result_type seed_) explicit
Definition at line 4706 of file catch_amalgamated.cpp.
References seed().
SimplePcg32() [3/4]
Catch::SimplePcg32::SimplePcg32 () inline
Definition at line 32 of file catch_random_number_generator.hpp.
References SimplePcg32().
SimplePcg32() [4/4]
Catch::SimplePcg32::SimplePcg32 (result_type seed_) explicit
Member Function Documentation
discard() [1/2]
void Catch::SimplePcg32::discard (uint64_t skip)
Definition at line 4718 of file catch_amalgamated.cpp.
discard() [2/2]
void Catch::SimplePcg32::discard (uint64_t skip)
max() [1/2]
constexpr result_type Catch::SimplePcg32::max () inline static constexpr
Definition at line 8006 of file catch_amalgamated.hpp.
References max().
Referenced by max().
max() [2/2]
constexpr result_type Catch::SimplePcg32::max () inline static constexpr
Definition at line 27 of file catch_random_number_generator.hpp.
References max().
min() [1/2]
constexpr result_type Catch::SimplePcg32::min () inline static constexpr
Definition at line 8003 of file catch_amalgamated.hpp.
References min().
Referenced by min().
min() [2/2]
constexpr result_type Catch::SimplePcg32::min () inline static constexpr
Definition at line 24 of file catch_random_number_generator.hpp.
References min().
operator()() [1/2]
SimplePcg32::result_type Catch::SimplePcg32::operator() ()
Definition at line 4726 of file catch_amalgamated.cpp.
operator()() [2/2]
result_type Catch::SimplePcg32::operator() ()
References SimplePcg32().
seed() [1/2]
void Catch::SimplePcg32::seed (result_type seed_)
Definition at line 4711 of file catch_amalgamated.cpp.
Referenced by Catch::seedRng(), SimplePcg32(), and TEST_CASE().
seed() [2/2]
void Catch::SimplePcg32::seed (result_type seed_)
Friends And Related Symbol Documentation
operator!= [1/2]
bool operator!= (SimplePcg32 const & lhs, SimplePcg32 const & rhs) friend
Definition at line 4741 of file catch_amalgamated.cpp.
References SimplePcg32().
operator!= [2/2]
bool operator!= (SimplePcg32 const & lhs, SimplePcg32 const & rhs) friend
Definition at line 4741 of file catch_amalgamated.cpp.
operator== [1/2]
bool operator== (SimplePcg32 const & lhs, SimplePcg32 const & rhs) friend
Definition at line 4737 of file catch_amalgamated.cpp.
References SimplePcg32().
operator== [2/2]
bool operator== (SimplePcg32 const & lhs, SimplePcg32 const & rhs) friend
Definition at line 4737 of file catch_amalgamated.cpp.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_random_number_generator.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_random_number_generator.cpp