libthe-seed: Catch::TeamCityReporter Class Reference
Catch::TeamCityReporter Class Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
TeamCityReporter (ReporterConfig &&_config)
~TeamCityReporter () override
void testRunStarting (TestRunInfo const &groupInfo) override
void testRunEnded (TestRunStats const &testGroupStats) override
void assertionEnded (AssertionStats const &assertionStats) override
Called after assertion was fully evaluated.
void sectionStarting (SectionInfo const &sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void testCaseStarting (TestCaseInfo const &testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCaseEnded (TestCaseStats const &testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
TeamCityReporter (ReporterConfig &&_config)
~TeamCityReporter () override
void testRunStarting (TestRunInfo const &groupInfo) override
void testRunEnded (TestRunStats const &testGroupStats) override
void assertionEnded (AssertionStats const &assertionStats) override
Called after assertion was fully evaluated.
void sectionStarting (SectionInfo const &sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void testCaseStarting (TestCaseInfo const &testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCaseEnded (TestCaseStats const &testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
Public Member Functions inherited from Catch::StreamingReporterBase
StreamingReporterBase (ReporterConfig &&_config)
~StreamingReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void sectionEnded (SectionStats const &) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void skipTest (TestCaseInfo const &) override
StreamingReporterBase (ReporterConfig &&_config)
~StreamingReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void sectionEnded (SectionStats const &) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void skipTest (TestCaseInfo const &) override
Public Member Functions inherited from Catch::ReporterBase
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
Public Member Functions inherited from Catch::IEventListener
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
Static Public Member Functions
static std::string getDescription ()
static std::string getDescription ()
Additional Inherited Members
Protected Attributes inherited from Catch::StreamingReporterBase
TestRunInfo currentTestRunInfo { "test run has not started yet"_sr }
TestCaseInfo const * currentTestCaseInfo = nullptr
std::vector< SectionInfo > m_sectionStack
Stack of all active sections in the current test case.
Protected Attributes inherited from Catch::ReporterBase
Detail::unique_ptr< IStream > m_wrapped_stream
The stream wrapper as passed to us by outside code.
std::ostream & m_stream
Cached output stream from m_wrapped_stream to reduce number of indirect calls needed to write output.
Detail::unique_ptr< ColourImpl > m_colour
Colour implementation this reporter was configured for.
std::map< std::string, std::string > m_customOptions
The custom reporter options user passed down to the reporter.
Protected Attributes inherited from Catch::IEventListener
ReporterPreferences m_preferences
Derived classes can set up their preferences here.
IConfig const * m_config
The test run's config as filled in from CLI and defaults.
Detailed Description
Definition at line 13037 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
TeamCityReporter() [1/2]
Catch::TeamCityReporter::TeamCityReporter (ReporterConfig && _config) inline
Definition at line 13039 of file catch_amalgamated.hpp.
References CATCH_MOVE, Catch::IEventListener::m_preferences, and Catch::StreamingReporterBase::StreamingReporterBase().
~TeamCityReporter() [1/2]
Catch::TeamCityReporter::~TeamCityReporter () override default
Definition at line 10344 of file catch_amalgamated.cpp.
TeamCityReporter() [2/2]
Catch::TeamCityReporter::TeamCityReporter (ReporterConfig && _config) inline
Definition at line 25 of file catch_reporter_teamcity.hpp.
References CATCH_MOVE, Catch::IEventListener::m_preferences, and Catch::StreamingReporterBase::StreamingReporterBase().
~TeamCityReporter() [2/2]
Catch::TeamCityReporter::~TeamCityReporter () override
Member Function Documentation
assertionEnded() [1/2]
void Catch::TeamCityReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10356 of file catch_amalgamated.cpp.
References Catch::AssertionStats::assertionResult, CATCH_ERROR, Catch::StreamingReporterBase::currentTestCaseInfo, Catch::ResultWas::DidntThrowException, Catch::ResultWas::Exception, Catch::ResultWas::ExplicitFailure, Catch::ResultWas::ExplicitSkip, Catch::ResultWas::ExpressionFailed, Catch::ResultWas::FailureBit, Catch::ResultWas::FatalErrorCondition, Catch::ReusableStringStream::get(), Catch::AssertionResult::getExpandedExpression(), Catch::AssertionResult::getExpressionInMacro(), Catch::AssertionResult::getResultType(), Catch::AssertionResult::getSourceInfo(), Catch::AssertionResult::hasExpression(), Catch::ResultWas::Info, Catch::AssertionStats::infoMessages, Catch::AssertionResult::isOk(), Catch::ReporterBase::m_stream, Catch::ResultWas::Ok, Catch::ReusableStringStream::str(), Catch::ResultWas::ThrewException, Catch::ResultWas::Unknown, and Catch::ResultWas::Warning.
assertionEnded() [2/2]
void Catch::TeamCityReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Reimplemented from Catch::StreamingReporterBase.
getDescription() [1/2]
std::string Catch::TeamCityReporter::getDescription () inline static
Definition at line 13047 of file catch_amalgamated.hpp.
getDescription() [2/2]
std::string Catch::TeamCityReporter::getDescription () inline static
Definition at line 33 of file catch_reporter_teamcity.hpp.
sectionStarting() [1/2]
void Catch::TeamCityReporter::sectionStarting (SectionInfo const & sectionInfo) inline override virtual
Called when a SECTION is being entered. Not called for skipped sections.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 13058 of file catch_amalgamated.hpp.
References Catch::StreamingReporterBase::sectionStarting().
sectionStarting() [2/2]
void Catch::TeamCityReporter::sectionStarting (SectionInfo const & sectionInfo) inline override virtual
Called when a SECTION is being entered. Not called for skipped sections.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 44 of file catch_reporter_teamcity.hpp.
References Catch::StreamingReporterBase::sectionStarting().
testCaseEnded() [1/2]
void Catch::TeamCityReporter::testCaseEnded (TestCaseStats const & testCaseStats) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10436 of file catch_amalgamated.cpp.
References Catch::ReporterBase::m_stream, Catch::TestCaseStats::stdErr, Catch::TestCaseStats::stdOut, Catch::StreamingReporterBase::testCaseEnded(), and Catch::TestCaseStats::testInfo.
testCaseEnded() [2/2]
void Catch::TeamCityReporter::testCaseEnded (TestCaseStats const & testCaseStats) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Reimplemented from Catch::StreamingReporterBase.
testCaseStarting() [1/2]
void Catch::TeamCityReporter::testCaseStarting (TestCaseInfo const & testInfo) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10428 of file catch_amalgamated.cpp.
References Catch::ReporterBase::m_stream, Catch::TestCaseInfo::name, and Catch::StreamingReporterBase::testCaseStarting().
testCaseStarting() [2/2]
void Catch::TeamCityReporter::testCaseStarting (TestCaseInfo const & testInfo) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Reimplemented from Catch::StreamingReporterBase.
testRunEnded() [1/2]
void Catch::TeamCityReporter::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10351 of file catch_amalgamated.cpp.
References Catch::ReporterBase::m_stream, Catch::TestRunInfo::name, and Catch::TestRunStats::runInfo.
testRunEnded() [2/2]
void Catch::TeamCityReporter::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Reimplemented from Catch::StreamingReporterBase.
testRunStarting() [1/2]
void Catch::TeamCityReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10346 of file catch_amalgamated.cpp.
References Catch::ReporterBase::m_stream, and Catch::TestRunInfo::name.
testRunStarting() [2/2]
void Catch::TeamCityReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Reimplemented from Catch::StreamingReporterBase.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/reporters/catch_reporter_teamcity.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/reporters/catch_reporter_teamcity.cpp