libthe-seed: Catch::Matchers::MatcherGenericBase Class Reference
Catch::Matchers::MatcherGenericBase Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
MatcherGenericBase ()=default
~MatcherGenericBase () override
MatcherGenericBase (MatcherGenericBase const &)=default
MatcherGenericBase (MatcherGenericBase &&)=default
MatcherGenericBase & operator= (MatcherGenericBase const &)=delete
MatcherGenericBase & operator= (MatcherGenericBase &&)=delete
MatcherGenericBase ()=default
~MatcherGenericBase () override
MatcherGenericBase (MatcherGenericBase const &)=default
MatcherGenericBase (MatcherGenericBase &&)=default
MatcherGenericBase & operator= (MatcherGenericBase const &)=delete
MatcherGenericBase & operator= (MatcherGenericBase &&)=delete
Public Member Functions inherited from Catch::Matchers::MatcherUntypedBase
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
Additional Inherited Members
Protected Member Functions inherited from Catch::Matchers::MatcherUntypedBase
virtual ~MatcherUntypedBase ()
virtual std::string describe () const =0
virtual ~MatcherUntypedBase ()
virtual std::string describe () const =0
Protected Attributes inherited from Catch::Matchers::MatcherUntypedBase
std::string m_cachedToString
Detailed Description
Definition at line 10932 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
MatcherGenericBase() [1/6]
Catch::Matchers::MatcherGenericBase::MatcherGenericBase () default
Referenced by MatcherGenericBase(), MatcherGenericBase(), operator=(), and operator=().
~MatcherGenericBase() [1/2]
Catch::Matchers::MatcherGenericBase::~MatcherGenericBase () override default
MatcherGenericBase() [2/6]
Catch::Matchers::MatcherGenericBase::MatcherGenericBase (MatcherGenericBase const &) default
References MatcherGenericBase().
MatcherGenericBase() [3/6]
Catch::Matchers::MatcherGenericBase::MatcherGenericBase (MatcherGenericBase &&) default
References MatcherGenericBase().
MatcherGenericBase() [4/6]
Catch::Matchers::MatcherGenericBase::MatcherGenericBase () default
~MatcherGenericBase() [2/2]
Catch::Matchers::MatcherGenericBase::~MatcherGenericBase () override
MatcherGenericBase() [5/6]
Catch::Matchers::MatcherGenericBase::MatcherGenericBase (MatcherGenericBase const &) default
References MatcherGenericBase().
MatcherGenericBase() [6/6]
Catch::Matchers::MatcherGenericBase::MatcherGenericBase (MatcherGenericBase &&) default
References MatcherGenericBase().
Member Function Documentation
operator=() [1/4]
MatcherGenericBase & Catch::Matchers::MatcherGenericBase::operator= (MatcherGenericBase &&) delete
References MatcherGenericBase().
operator=() [2/4]
MatcherGenericBase & Catch::Matchers::MatcherGenericBase::operator= (MatcherGenericBase &&) delete
References MatcherGenericBase().
operator=() [3/4]
MatcherGenericBase & Catch::Matchers::MatcherGenericBase::operator= (MatcherGenericBase const &) delete
References MatcherGenericBase().
operator=() [4/4]
MatcherGenericBase & Catch::Matchers::MatcherGenericBase::operator= (MatcherGenericBase const &) delete
References MatcherGenericBase().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/matchers/catch_matchers_templated.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/matchers/catch_matchers_templated.cpp