libthe-seed: LibraryLoader Class Reference
LibraryLoader Class Reference
#include <LibraryLoader.hpp>
Public Member Functions
LibraryLoader (std::string library)
~LibraryLoader ()
void * FunctionGet (std::string FuncName)
void PathAdd (std::string path)
Public Attributes
std::string name
Private Member Functions
void Load ()
std::vector< std::string > PathsGet ()
Private Attributes
void * dl_handle = nullptr
std::vector< std::string > paths
Detailed Description
Definition at line 6 of file LibraryLoader.hpp.
Constructor & Destructor Documentation
LibraryLoader()
LibraryLoader::LibraryLoader (std::string library)
Definition at line 12 of file LibraryLoader.cpp.
 {
     this->name = library;
 }
References name.
~LibraryLoader()
LibraryLoader::~LibraryLoader ()
Definition at line 95 of file LibraryLoader.cpp.
 {
 #ifdef _WIN32
     FreeLibrary((HMODULE)this->dl_handle);
 #else
     dlclose(this->dl_handle);
 #endif
 }
References dl_handle.
Member Function Documentation
FunctionGet()
void * LibraryLoader::FunctionGet (std::string FuncName)
Definition at line 104 of file LibraryLoader.cpp.
 {
     this->Load();
     void *ptr = nullptr;
     std::string error;
 #ifdef _WIN32
     ptr = (void *)GetProcAddress((HMODULE)this->dl_handle, FuncName.c_str());
     if(!ptr)
     {
         DWORD result = GetLastError();
         LPSTR messageBuffer = nullptr;
         size_t size = FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
                                  NULL, result, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), (LPSTR)&messageBuffer, 0, NULL);
         error = std::string(messageBuffer);
         LocalFree(messageBuffer);
     }
 #else
     ptr = dlsym(this->dl_handle, FuncName.c_str());
     if(!ptr) error = std::string(dlerror());
 #endif
     if(!ptr)
     {
         std::cerr << error << std::endl;
         throw std::string(error);
     }
     return ptr;
 }
References dl_handle, and Load().
Referenced by ComponentLoader::Loader::ComponentCreate(), ComponentLoader::Loader::ComponentGet(), SystemLoader::Loader::SystemCreate(), and SystemLoader::Loader::SystemGet().
Load()
void LibraryLoader::Load () private
Definition at line 56 of file LibraryLoader.cpp.
 {
     if(this->dl_handle != nullptr) return;
     std::string error;
     std::vector<std::string> search_paths = this->PathsGet();
     for(auto &path : search_paths)
     {
 #ifdef _WIN32
         this->dl_handle = LoadLibrary(path.c_str());
         if(this->dl_handle == nullptr)
         {
             DWORD result = GetLastError();
             LPSTR messageBuffer = nullptr;
             size_t size = FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
                                      NULL, result, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), (LPSTR)&messageBuffer, 0, NULL);
             error = std::string(messageBuffer);
             LocalFree(messageBuffer);
         }
         else break;
 #else
         dlerror();
         this->dl_handle = dlopen(path.c_str(), RTLD_LAZY);
         if(this->dl_handle == nullptr)
         {
             error = std::string(dlerror());
         }
         else break;
 #endif
     }
     if(this->dl_handle == nullptr)
     {
         std::cout << "Couldn't open shared object." << std::endl;
         std::cout << error << std::endl;
         throw error;
     }
 }
References dl_handle, and PathsGet().
Referenced by FunctionGet().
PathAdd()
void LibraryLoader::PathAdd (std::string path)
Definition at line 17 of file LibraryLoader.cpp.
 {
     this->paths.push_back(path);
 }
References paths.
PathsGet()
std::vector< std::string > LibraryLoader::PathsGet () private
Definition at line 22 of file LibraryLoader.cpp.
 {
     std::vector<std::string> valid_paths;
     for(auto &p : this->paths)
     {
 #ifdef _WIN32
         std::string full_path = p + "\\lib" + this->name + "-0.dll";
 #elif __APPLE__
         std::string full_path = p + "/lib" + this->name + ".dylib";
 #else
         std::string full_path = p + "/lib" + this->name + ".so";
 #endif
         std::ifstream test_path(full_path);
         if(test_path.is_open())
         {
             valid_paths.push_back(full_path);
             test_path.close();
         }
     }
     if(valid_paths.size() == 0)
     {
         std::cout << "Could not find " + this->name + " shared object in the following paths:" << std::endl;
         for(auto &p : this->paths)
         {
             std::cout << p << std::endl;
         }
     }
     return valid_paths;
 }
References name, and paths.
Referenced by Load().
Member Data Documentation
dl_handle
void* LibraryLoader::dl_handle = nullptr private
Definition at line 15 of file LibraryLoader.hpp.
Referenced by FunctionGet(), Load(), and ~LibraryLoader().
name
std::string LibraryLoader::name
Definition at line 13 of file LibraryLoader.hpp.
Referenced by ComponentLoader::Loader::ComponentCreate(), LibraryLoader(), PathsGet(), and SystemLoader::Loader::SystemCreate().
paths
std::vector<std::string> LibraryLoader::paths private
Definition at line 18 of file LibraryLoader.hpp.
Referenced by PathAdd(), and PathsGet().
The documentation for this class was generated from the following files:
include/libthe-seed/LibraryLoader.hpp
src/LibraryLoader.cpp