libthe-seed: Catch::TestCaseTracking::TrackerContext Class Reference
Catch::TestCaseTracking::TrackerContext Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
ITracker & startRun ()
void startCycle ()
void completeCycle ()
bool completedCycle () const
ITracker & currentTracker ()
void setCurrentTracker (ITracker *tracker)
ITracker & startRun ()
void startCycle ()
void completeCycle ()
bool completedCycle () const
ITracker & currentTracker ()
void setCurrentTracker (ITracker *tracker)
Detailed Description
Definition at line 9680 of file catch_amalgamated.hpp.
Member Function Documentation
completeCycle() [1/2]
void Catch::TestCaseTracking::TrackerContext::completeCycle ()
Definition at line 6347 of file catch_amalgamated.cpp.
completeCycle() [2/2]
void Catch::TestCaseTracking::TrackerContext::completeCycle ()
completedCycle() [1/2]
bool Catch::TestCaseTracking::TrackerContext::completedCycle () const
Definition at line 6351 of file catch_amalgamated.cpp.
Referenced by Catch::TestCaseTracking::SectionTracker::acquire(), and TEST_CASE().
completedCycle() [2/2]
bool Catch::TestCaseTracking::TrackerContext::completedCycle () const
currentTracker() [1/2]
ITracker & Catch::TestCaseTracking::TrackerContext::currentTracker () inline
Definition at line 9703 of file catch_amalgamated.hpp.
Referenced by Catch::TestCaseTracking::SectionTracker::acquire().
currentTracker() [2/2]
ITracker & Catch::TestCaseTracking::TrackerContext::currentTracker () inline
Definition at line 186 of file catch_test_case_tracker.hpp.
setCurrentTracker() [1/2]
void Catch::TestCaseTracking::TrackerContext::setCurrentTracker (ITracker * tracker)
Definition at line 6354 of file catch_amalgamated.cpp.
setCurrentTracker() [2/2]
void Catch::TestCaseTracking::TrackerContext::setCurrentTracker (ITracker * tracker)
startCycle() [1/2]
void Catch::TestCaseTracking::TrackerContext::startCycle () inline
Definition at line 9696 of file catch_amalgamated.hpp.
Referenced by TEST_CASE().
startCycle() [2/2]
void Catch::TestCaseTracking::TrackerContext::startCycle () inline
Definition at line 179 of file catch_test_case_tracker.hpp.
startRun() [1/2]
ITracker & Catch::TestCaseTracking::TrackerContext::startRun ()
Definition at line 6336 of file catch_amalgamated.cpp.
References CATCH_INTERNAL_LINEINFO, and Catch::Detail::make_unique().
Referenced by TEST_CASE().
startRun() [2/2]
ITracker & Catch::TestCaseTracking::TrackerContext::startRun ()
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_test_case_tracker.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_test_case_tracker.cpp