libthe-seed: Catch::TestSpec Class Reference
Catch::TestSpec Class Reference
#include <catch_amalgamated.hpp>
Classes
struct FilterMatch
Public Types
using Matches = std::vector<FilterMatch>
using vectorStrings = std::vector<std::string>
using Matches = std::vector<FilterMatch>
using vectorStrings = std::vector<std::string>
Public Member Functions
bool hasFilters () const
bool matches (TestCaseInfo const &testCase) const
Matches matchesByFilter (std::vector< TestCaseHandle > const &testCases, IConfig const &config) const
const vectorStrings & getInvalidSpecs () const
bool hasFilters () const
bool matches (TestCaseInfo const &testCase) const
Matches matchesByFilter (std::vector< TestCaseHandle > const &testCases, IConfig const &config) const
const vectorStrings & getInvalidSpecs () const
Friends
class TestSpecParser
std::ostream & operator<< (std::ostream &out, TestSpec const &spec)
std::ostream & operator<< (std::ostream &out, TestSpec const &spec)
Detailed Description
Definition at line 3578 of file catch_amalgamated.hpp.
Member Typedef Documentation
Matches [1/2]
using Catch::TestSpec::Matches = std::vector<FilterMatch>
Definition at line 3640 of file catch_amalgamated.hpp.
Matches [2/2]
using Catch::TestSpec::Matches = std::vector<FilterMatch>
Definition at line 91 of file catch_test_spec.hpp.
vectorStrings [1/2]
using Catch::TestSpec::vectorStrings = std::vector<std::string>
Definition at line 3641 of file catch_amalgamated.hpp.
vectorStrings [2/2]
using Catch::TestSpec::vectorStrings = std::vector<std::string>
Definition at line 92 of file catch_test_spec.hpp.
Member Function Documentation
getInvalidSpecs() [1/2]
const TestSpec::vectorStrings & Catch::TestSpec::getInvalidSpecs () const
Definition at line 1740 of file catch_amalgamated.cpp.
getInvalidSpecs() [2/2]
const vectorStrings & Catch::TestSpec::getInvalidSpecs () const
References TestSpecParser.
hasFilters() [1/2]
bool Catch::TestSpec::hasFilters () const
Definition at line 1717 of file catch_amalgamated.cpp.
Referenced by Catch::filterTests().
hasFilters() [2/2]
bool Catch::TestSpec::hasFilters () const
matches() [1/2]
bool Catch::TestSpec::matches (TestCaseInfo const & testCase) const
Definition at line 1721 of file catch_amalgamated.cpp.
Referenced by matchesByFilter().
matches() [2/2]
bool Catch::TestSpec::matches (TestCaseInfo const & testCase) const
matchesByFilter() [1/2]
TestSpec::Matches Catch::TestSpec::matchesByFilter (std::vector< TestCaseHandle > const & testCases, IConfig const & config) const
Definition at line 1725 of file catch_amalgamated.cpp.
References Catch::isThrowSafe(), and matches().
matchesByFilter() [2/2]
Matches Catch::TestSpec::matchesByFilter (std::vector< TestCaseHandle > const & testCases, IConfig const & config) const
Friends And Related Symbol Documentation
operator<< [1/2]
std::ostream & operator<< (std::ostream & out, TestSpec const & spec) friend
Definition at line 3656 of file catch_amalgamated.hpp.
operator<< [2/2]
std::ostream & operator<< (std::ostream & out, TestSpec const & spec) friend
Definition at line 107 of file catch_test_spec.hpp.
TestSpecParser
TestSpecParser friend
Definition at line 3652 of file catch_amalgamated.hpp.
References TestSpecParser.
Referenced by getInvalidSpecs(), and TestSpecParser.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/catch_test_spec.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/catch_test_spec.cpp