libthe-seed: Catch::StringRef Class Reference
Catch::StringRef Class Reference
A non-owning string class (similar to the forthcoming std::string_view) Note that, because a StringRef may be a substring of another string, it may not be null terminated.
#include <catch_amalgamated.hpp>
Public Types
using size_type = std::size_t
using const_iterator = const char*
using size_type = std::size_t
using const_iterator = const char*
Public Member Functions
constexpr StringRef () noexcept=default
StringRef (char const *rawChars) noexcept
constexpr StringRef (char const *rawChars, size_type size) noexcept
StringRef (std::string const &stdString) noexcept
operator std::string () const
auto operator== (StringRef other) const noexcept -> bool
auto operator!= (StringRef other) const noexcept -> bool
constexpr auto operator[] (size_type index) const noexcept -> char
bool operator< (StringRef rhs) const noexcept
constexpr auto empty () const noexcept -> bool
constexpr auto size () const noexcept -> size_type
constexpr StringRef substr (size_type start, size_type length) const noexcept
constexpr char const * data () const noexcept
constexpr const_iterator begin () const
constexpr const_iterator end () const
int compare (StringRef rhs) const
constexpr StringRef () noexcept=default
StringRef (char const *rawChars) noexcept
constexpr StringRef (char const *rawChars, size_type size) noexcept
StringRef (std::string const &stdString) noexcept
operator std::string () const
auto operator== (StringRef other) const noexcept -> bool
auto operator!= (StringRef other) const noexcept -> bool
constexpr auto operator[] (size_type index) const noexcept -> char
bool operator< (StringRef rhs) const noexcept
constexpr auto empty () const noexcept -> bool
constexpr auto size () const noexcept -> size_type
constexpr StringRef substr (size_type start, size_type length) const noexcept
constexpr char const * data () const noexcept
constexpr const_iterator begin () const
constexpr const_iterator end () const
int compare (StringRef rhs) const
Friends
std::string & operator+= (std::string &lhs, StringRef sr)
std::ostream & operator<< (std::ostream &os, StringRef sr)
std::string operator+ (StringRef lhs, StringRef rhs)
std::string & operator+= (std::string &lhs, StringRef sr)
std::ostream & operator<< (std::ostream &os, StringRef sr)
std::string operator+ (StringRef lhs, StringRef rhs)
Detailed Description
A non-owning string class (similar to the forthcoming std::string_view) Note that, because a StringRef may be a substring of another string, it may not be null terminated.
Definition at line 685 of file catch_amalgamated.hpp.
Member Typedef Documentation
const_iterator [1/2]
using Catch::StringRef::const_iterator = const char*
Definition at line 688 of file catch_amalgamated.hpp.
const_iterator [2/2]
using Catch::StringRef::const_iterator = const char*
Definition at line 26 of file catch_stringref.hpp.
size_type [1/2]
using Catch::StringRef::size_type = std::size_t
Definition at line 687 of file catch_amalgamated.hpp.
size_type [2/2]
using Catch::StringRef::size_type = std::size_t
Definition at line 25 of file catch_stringref.hpp.
Constructor & Destructor Documentation
StringRef() [1/8]
Catch::StringRef::StringRef () constexpr default noexcept
References StringRef().
Referenced by compare(), operator!=(), operator+, operator+=, operator<(), operator<<, operator==(), StringRef(), StringRef(), StringRef(), and substr().
StringRef() [2/8]
Catch::StringRef::StringRef (char const * rawChars) noexcept
Definition at line 6006 of file catch_amalgamated.cpp.
References StringRef().
StringRef() [3/8]
Catch::StringRef::StringRef (char const * rawChars, size_type size) inline constexpr noexcept
Definition at line 701 of file catch_amalgamated.hpp.
References size(), and StringRef().
StringRef() [4/8]
Catch::StringRef::StringRef (std::string const & stdString) inline noexcept
Definition at line 706 of file catch_amalgamated.hpp.
StringRef() [5/8]
Catch::StringRef::StringRef () constexpr default noexcept
StringRef() [6/8]
Catch::StringRef::StringRef (char const * rawChars) noexcept
References StringRef().
StringRef() [7/8]
Catch::StringRef::StringRef (char const * rawChars, size_type size) inline constexpr noexcept
Definition at line 39 of file catch_stringref.hpp.
References size(), and StringRef().
StringRef() [8/8]
Catch::StringRef::StringRef (std::string const & stdString) inline noexcept
Definition at line 44 of file catch_stringref.hpp.
Member Function Documentation
begin() [1/2]
const_iterator Catch::StringRef::begin () const inline constexpr
Definition at line 756 of file catch_amalgamated.hpp.
Referenced by Catch::Detail::CaseInsensitiveEqualTo::operator()(), and Catch::Detail::CaseInsensitiveLess::operator()().
begin() [2/2]
const_iterator Catch::StringRef::begin () const inline constexpr
Definition at line 94 of file catch_stringref.hpp.
compare() [1/2]
int Catch::StringRef::compare (StringRef rhs) const
Provides a three-way comparison with rhs
Returns negative number if lhs < rhs, 0 if lhs == rhs, and a positive number if lhs > rhs
Definition at line 6018 of file catch_amalgamated.cpp.
References StringRef().
Referenced by Catch::TestCaseInfo::operator<.
compare() [2/2]
int Catch::StringRef::compare (StringRef rhs) const
Provides a three-way comparison with rhs
Returns negative number if lhs < rhs, 0 if lhs == rhs, and a positive number if lhs > rhs
References StringRef().
data() [1/2]
char const * Catch::StringRef::data () const inline constexpr noexcept
Definition at line 752 of file catch_amalgamated.hpp.
Referenced by Catch::Matchers::Detail::describe_multi_matcher().
data() [2/2]
char const * Catch::StringRef::data () const inline constexpr noexcept
Definition at line 90 of file catch_stringref.hpp.
empty() [1/2]
auto Catch::StringRef::empty () const->bool inline constexpr noexcept
Definition at line 732 of file catch_amalgamated.hpp.
Referenced by Catch::startsWith(), Catch::TestCaseInfo::TestCaseInfo(), Catch::XmlWriter::writeAttribute(), and Catch::XmlWriter::writeText().
empty() [2/2]
auto Catch::StringRef::empty () const->bool inline constexpr noexcept
Definition at line 70 of file catch_stringref.hpp.
end() [1/2]
const_iterator Catch::StringRef::end () const inline constexpr
Definition at line 757 of file catch_amalgamated.hpp.
Referenced by Catch::Detail::CaseInsensitiveEqualTo::operator()(), and Catch::Detail::CaseInsensitiveLess::operator()().
end() [2/2]
const_iterator Catch::StringRef::end () const inline constexpr
Definition at line 95 of file catch_stringref.hpp.
operator std::string() [1/2]
Catch::StringRef::operator std::string () const inline explicit
Definition at line 711 of file catch_amalgamated.hpp.
operator std::string() [2/2]
Catch::StringRef::operator std::string () const inline explicit
Definition at line 49 of file catch_stringref.hpp.
operator!=() [1/2]
auto Catch::StringRef::operator!= (StringRef other) const->bool inline noexcept
Definition at line 720 of file catch_amalgamated.hpp.
References StringRef().
operator!=() [2/2]
auto Catch::StringRef::operator!= (StringRef other) const->bool inline noexcept
Definition at line 58 of file catch_stringref.hpp.
References StringRef().
operator<() [1/2]
bool Catch::StringRef::operator< (StringRef rhs) const noexcept
Definition at line 6011 of file catch_amalgamated.cpp.
References StringRef().
operator<() [2/2]
bool Catch::StringRef::operator< (StringRef rhs) const noexcept
References StringRef().
operator==() [1/2]
auto Catch::StringRef::operator== (StringRef other) const->bool inline noexcept
Definition at line 716 of file catch_amalgamated.hpp.
References StringRef().
operator==() [2/2]
auto Catch::StringRef::operator== (StringRef other) const->bool inline noexcept
Definition at line 54 of file catch_stringref.hpp.
References StringRef().
operator[]() [1/2]
auto Catch::StringRef::operator[] (size_type index) const->char inline constexpr noexcept
Definition at line 724 of file catch_amalgamated.hpp.
operator[]() [2/2]
auto Catch::StringRef::operator[] (size_type index) const->char inline constexpr noexcept
Definition at line 62 of file catch_stringref.hpp.
size() [1/2]
auto Catch::StringRef::size () const->size_type inline constexpr noexcept
Definition at line 735 of file catch_amalgamated.hpp.
Referenced by Catch::Capturer::Capturer(), Catch::Matchers::Detail::describe_multi_matcher(), Catch::endsWith(), operator+, Catch::Detail::splitReporterSpec(), Catch::splitStringRef(), StringRef(), Catch::TestCaseInfo::TestCaseInfo(), and Catch::trim().
size() [2/2]
auto Catch::StringRef::size () const->size_type inline constexpr noexcept
Definition at line 73 of file catch_stringref.hpp.
substr() [1/2]
StringRef Catch::StringRef::substr (size_type start, size_type length) const inline constexpr noexcept
Definition at line 742 of file catch_amalgamated.hpp.
References StringRef().
Referenced by Catch::Capturer::Capturer(), Catch::Detail::splitReporterSpec(), Catch::splitStringRef(), Catch::TestCaseInfo::TestCaseInfo(), and Catch::trim().
substr() [2/2]
StringRef Catch::StringRef::substr (size_type start, size_type length) const inline constexpr noexcept
Definition at line 80 of file catch_stringref.hpp.
References StringRef().
Friends And Related Symbol Documentation
operator+ [1/2]
std::string operator+ (StringRef lhs, StringRef rhs) friend
Definition at line 6043 of file catch_amalgamated.cpp.
References size(), and StringRef().
operator+ [2/2]
std::string operator+ (StringRef lhs, StringRef rhs) friend
Definition at line 6043 of file catch_amalgamated.cpp.
operator+= [1/2]
std::string & operator+= (std::string & lhs, StringRef sr) friend
References StringRef().
operator+= [2/2]
std::string & operator+= (std::string & lhs, StringRef sr) friend
References StringRef().
operator<< [1/2]
std::ostream & operator<< (std::ostream & os, StringRef sr) friend
References StringRef().
operator<< [2/2]
std::ostream & operator<< (std::ostream & os, StringRef sr) friend
References StringRef().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_stringref.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_stringref.cpp