libthe-seed: Catch::TestCaseTracking::TrackerBase Class Reference
Catch::TestCaseTracking::TrackerBase Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
TrackerBase (NameAndLocation &&nameAndLocation, TrackerContext &ctx, ITracker *parent)
bool isComplete () const override
Returns true if tracker run to completion (successfully or not).
void open ()
void close () override
void fail () override
TrackerBase (NameAndLocation &&nameAndLocation, TrackerContext &ctx, ITracker *parent)
bool isComplete () const override
Returns true if tracker run to completion (successfully or not).
void open ()
void close () override
void fail () override
Public Member Functions inherited from Catch::TestCaseTracking::ITracker
ITracker (NameAndLocation &&nameAndLoc, ITracker *parent)
NameAndLocation const & nameAndLocation () const
ITracker * parent () const
virtual ~ITracker ()
bool isSuccessfullyCompleted () const
Returns true if tracker run to completion successfully.
bool isOpen () const
Returns true if tracker has started but hasn't been completed.
bool hasStarted () const
Returns true iff tracker has started.
void markAsNeedingAnotherRun ()
void addChild (ITrackerPtr &&child)
Register a nested ITracker.
ITracker * findChild (NameAndLocationRef const &nameAndLocation)
bool hasChildren () const
Have any children been added?
void openChild ()
Marks tracker as executing a child, doing se recursively up the tree.
virtual bool isSectionTracker () const
virtual bool isGeneratorTracker () const
ITracker (NameAndLocation &&nameAndLoc, ITracker *parent)
NameAndLocation const & nameAndLocation () const
ITracker * parent () const
virtual ~ITracker ()
bool isSuccessfullyCompleted () const
Returns true if tracker run to completion successfully.
bool isOpen () const
Returns true if tracker has started but hasn't been completed.
bool hasStarted () const
Returns true iff tracker has started.
void markAsNeedingAnotherRun ()
void addChild (ITrackerPtr &&child)
Register a nested ITracker.
ITracker * findChild (NameAndLocationRef const &nameAndLocation)
bool hasChildren () const
Have any children been added?
void openChild ()
Marks tracker as executing a child, doing se recursively up the tree.
virtual bool isSectionTracker () const
virtual bool isGeneratorTracker () const
Protected Attributes
TrackerContext & m_ctx
Protected Attributes inherited from Catch::TestCaseTracking::ITracker
ITracker * m_parent = nullptr
Children m_children
CycleState m_runState = NotStarted
Additional Inherited Members
Protected Types inherited from Catch::TestCaseTracking::ITracker
enum CycleState {
NotStarted , Executing , ExecutingChildren , NeedsAnotherRun ,
CompletedSuccessfully , Failed , NotStarted , Executing ,
ExecutingChildren , NeedsAnotherRun , CompletedSuccessfully , Failed
}
enum CycleState {
NotStarted , Executing , ExecutingChildren , NeedsAnotherRun ,
CompletedSuccessfully , Failed , NotStarted , Executing ,
ExecutingChildren , NeedsAnotherRun , CompletedSuccessfully , Failed
}
Detailed Description
Definition at line 9707 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
TrackerBase() [1/2]
Catch::TestCaseTracking::TrackerBase::TrackerBase (NameAndLocation && nameAndLocation, TrackerContext & ctx, ITracker * parent)
Definition at line 6359 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::TestCaseTracking::ITracker::ITracker(), m_ctx, Catch::TestCaseTracking::ITracker::nameAndLocation(), and Catch::TestCaseTracking::ITracker::parent().
Referenced by Catch::TestCaseTracking::SectionTracker::SectionTracker().
TrackerBase() [2/2]
Catch::TestCaseTracking::TrackerBase::TrackerBase (NameAndLocation && nameAndLocation, TrackerContext & ctx, ITracker * parent)
References Catch::TestCaseTracking::ITracker::ITracker(), Catch::TestCaseTracking::ITracker::nameAndLocation(), and Catch::TestCaseTracking::ITracker::parent().
Member Function Documentation
close() [1/2]
void Catch::TestCaseTracking::TrackerBase::close () override virtual
Implements Catch::TestCaseTracking::ITracker.
Definition at line 6375 of file catch_amalgamated.cpp.
References CATCH_INTERNAL_ERROR, Catch::TestCaseTracking::ITracker::CompletedSuccessfully, Catch::TestCaseTracking::ITracker::Executing, Catch::TestCaseTracking::ITracker::ExecutingChildren, Catch::TestCaseTracking::ITracker::Failed, Catch::TestCaseTracking::ITracker::m_children, m_ctx, Catch::TestCaseTracking::ITracker::m_runState, Catch::TestCaseTracking::ITracker::NeedsAnotherRun, and Catch::TestCaseTracking::ITracker::NotStarted.
close() [2/2]
void Catch::TestCaseTracking::TrackerBase::close () override virtual
Implements Catch::TestCaseTracking::ITracker.
fail() [1/2]
void Catch::TestCaseTracking::TrackerBase::fail () override virtual
Implements Catch::TestCaseTracking::ITracker.
Definition at line 6404 of file catch_amalgamated.cpp.
References Catch::TestCaseTracking::ITracker::Failed, m_ctx, Catch::TestCaseTracking::ITracker::m_parent, and Catch::TestCaseTracking::ITracker::m_runState.
fail() [2/2]
void Catch::TestCaseTracking::TrackerBase::fail () override virtual
Implements Catch::TestCaseTracking::ITracker.
isComplete() [1/2]
bool Catch::TestCaseTracking::TrackerBase::isComplete () const override virtual
Returns true if tracker run to completion (successfully or not).
Implements Catch::TestCaseTracking::ITracker.
Definition at line 6364 of file catch_amalgamated.cpp.
References Catch::TestCaseTracking::ITracker::CompletedSuccessfully, Catch::TestCaseTracking::ITracker::Failed, and Catch::TestCaseTracking::ITracker::m_runState.
Referenced by Catch::TestCaseTracking::SectionTracker::isComplete().
isComplete() [2/2]
bool Catch::TestCaseTracking::TrackerBase::isComplete () const override virtual
Returns true if tracker run to completion (successfully or not).
Implements Catch::TestCaseTracking::ITracker.
open() [1/2]
void Catch::TestCaseTracking::TrackerBase::open ()
Definition at line 6368 of file catch_amalgamated.cpp.
References Catch::TestCaseTracking::ITracker::Executing, Catch::TestCaseTracking::ITracker::m_parent, and Catch::TestCaseTracking::ITracker::m_runState.
Referenced by Catch::TestCaseTracking::SectionTracker::tryOpen().
open() [2/2]
void Catch::TestCaseTracking::TrackerBase::open ()
Member Data Documentation
m_ctx
TrackerContext & Catch::TestCaseTracking::TrackerBase::m_ctx protected
Definition at line 9710 of file catch_amalgamated.hpp.
Referenced by close(), fail(), and TrackerBase().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_test_case_tracker.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_test_case_tracker.cpp