libthe-seed: Catch::CumulativeReporterBase Class Reference
Catch::CumulativeReporterBase Class Reference abstract
#include <catch_amalgamated.hpp>
Classes
struct Node
struct SectionNode
Public Types
using TestCaseNode = Node<TestCaseStats, SectionNode>
using TestRunNode = Node<TestRunStats, TestCaseNode>
using TestCaseNode = Node<TestCaseStats, SectionNode>
using TestRunNode = Node<TestRunStats, TestCaseNode>
Public Member Functions
CumulativeReporterBase (ReporterConfig &&_config)
~CumulativeReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &benchmarkStats) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void testRunStarting (TestRunInfo const &) override
void testCaseStarting (TestCaseInfo const &) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &assertionStats) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &sectionStats) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &testRunStats) override
virtual void testRunEndedCumulative ()=0
Customization point: called after last test finishes (testRunEnded has been handled).
void skipTest (TestCaseInfo const &) override
CumulativeReporterBase (ReporterConfig &&_config)
~CumulativeReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &benchmarkStats) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void testRunStarting (TestRunInfo const &) override
void testCaseStarting (TestCaseInfo const &) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &assertionStats) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &sectionStats) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &testRunStats) override
virtual void testRunEndedCumulative ()=0
Customization point: called after last test finishes (testRunEnded has been handled).
void skipTest (TestCaseInfo const &) override
Public Member Functions inherited from Catch::ReporterBase
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
Public Member Functions inherited from Catch::IEventListener
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
Protected Attributes
bool m_shouldStoreSuccesfulAssertions = true
Should the cumulative base store the assertion expansion for successful assertions?
bool m_shouldStoreFailedAssertions = true
Should the cumulative base store the assertion expansion for failed assertions?
Detail::unique_ptr< TestRunNode > m_testRun
The root node of the test run tree.
Protected Attributes inherited from Catch::ReporterBase
Detail::unique_ptr< IStream > m_wrapped_stream
The stream wrapper as passed to us by outside code.
std::ostream & m_stream
Cached output stream from m_wrapped_stream to reduce number of indirect calls needed to write output.
Detail::unique_ptr< ColourImpl > m_colour
Colour implementation this reporter was configured for.
std::map< std::string, std::string > m_customOptions
The custom reporter options user passed down to the reporter.
Protected Attributes inherited from Catch::IEventListener
ReporterPreferences m_preferences
Derived classes can set up their preferences here.
IConfig const * m_config
The test run's config as filled in from CLI and defaults.
Detailed Description
Utility base for reporters that need to handle all results at once
It stores tree of all test cases, sections and assertions, and after the test run is finished, calls into testRunEndedCumulative to pass the control to the deriving class.
If you are deriving from this class and override any testing related member functions, you should first call into the base's implementation to avoid breaking the tree construction.
Due to the way this base functions, it has to expand assertions up-front, even if they are later unused (e.g. because the deriving reporter does not report successful assertions, or because the deriving reporter does not use assertion expansion at all). Derived classes can use two customization points, m_shouldStoreSuccesfulAssertions and m_shouldStoreFailedAssertions, to disable the expansion and gain extra performance. Accessing the assertion expansions if it wasn't stored is UB.
Definition at line 12466 of file catch_amalgamated.hpp.
Member Typedef Documentation
TestCaseNode [1/2]
using Catch::CumulativeReporterBase::TestCaseNode = Node<TestCaseStats, SectionNode>
Definition at line 12493 of file catch_amalgamated.hpp.
TestCaseNode [2/2]
using Catch::CumulativeReporterBase::TestCaseNode = Node<TestCaseStats, SectionNode>
Definition at line 89 of file catch_reporter_cumulative_base.hpp.
TestRunNode [1/2]
using Catch::CumulativeReporterBase::TestRunNode = Node<TestRunStats, TestCaseNode>
Definition at line 12494 of file catch_amalgamated.hpp.
TestRunNode [2/2]
using Catch::CumulativeReporterBase::TestRunNode = Node<TestRunStats, TestCaseNode>
Definition at line 90 of file catch_reporter_cumulative_base.hpp.
Constructor & Destructor Documentation
CumulativeReporterBase() [1/2]
Catch::CumulativeReporterBase::CumulativeReporterBase (ReporterConfig && _config) inline
Definition at line 12498 of file catch_amalgamated.hpp.
References CATCH_MOVE, and Catch::ReporterBase::ReporterBase().
Referenced by Catch::JunitReporter::JunitReporter(), and Catch::SonarQubeReporter::SonarQubeReporter().
~CumulativeReporterBase() [1/2]
Catch::CumulativeReporterBase::~CumulativeReporterBase () override default
CumulativeReporterBase() [2/2]
Catch::CumulativeReporterBase::CumulativeReporterBase (ReporterConfig && _config) inline
Definition at line 94 of file catch_reporter_cumulative_base.hpp.
References CATCH_MOVE, and Catch::ReporterBase::ReporterBase().
~CumulativeReporterBase() [2/2]
Catch::CumulativeReporterBase::~CumulativeReporterBase () override
Member Function Documentation
assertionEnded() [1/2]
void Catch::CumulativeReporterBase::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Implements Catch::IEventListener.
Reimplemented in Catch::JunitReporter, and Catch::JunitReporter.
Definition at line 8993 of file catch_amalgamated.cpp.
References Catch::AssertionStats::assertionResult, Catch::CumulativeReporterBase::SectionNode::assertionsAndBenchmarks, Catch::AssertionResult::getExpandedExpression(), Catch::AssertionResult::isOk(), m_shouldStoreFailedAssertions, and m_shouldStoreSuccesfulAssertions.
Referenced by Catch::JunitReporter::assertionEnded().
assertionEnded() [2/2]
void Catch::CumulativeReporterBase::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Implements Catch::IEventListener.
Reimplemented in Catch::JunitReporter, and Catch::JunitReporter.
assertionStarting() [1/2]
void Catch::CumulativeReporterBase::assertionStarting (AssertionInfo const & assertionInfo) inline override virtual
Called before assertion success/failure is evaluated.
Implements Catch::IEventListener.
Definition at line 12518 of file catch_amalgamated.hpp.
assertionStarting() [2/2]
void Catch::CumulativeReporterBase::assertionStarting (AssertionInfo const & assertionInfo) inline override virtual
Called before assertion success/failure is evaluated.
Implements Catch::IEventListener.
Definition at line 114 of file catch_reporter_cumulative_base.hpp.
benchmarkEnded() [1/2]
void Catch::CumulativeReporterBase::benchmarkEnded (BenchmarkStats<> const & benchmarkStats) override virtual
Called with the benchmark results if benchmark successfully finishes.
Implements Catch::IEventListener.
Definition at line 8959 of file catch_amalgamated.cpp.
benchmarkEnded() [2/2]
void Catch::CumulativeReporterBase::benchmarkEnded (BenchmarkStats<> const & benchmarkStats) override virtual
Called with the benchmark results if benchmark successfully finishes.
Implements Catch::IEventListener.
benchmarkFailed() [1/2]
void Catch::CumulativeReporterBase::benchmarkFailed (StringRef benchmarkName) inline override virtual
Called if running the benchmarks fails for any reason.
Implements Catch::IEventListener.
Definition at line 12506 of file catch_amalgamated.hpp.
benchmarkFailed() [2/2]
void Catch::CumulativeReporterBase::benchmarkFailed (StringRef benchmarkName) inline override virtual
Called if running the benchmarks fails for any reason.
Implements Catch::IEventListener.
Definition at line 102 of file catch_reporter_cumulative_base.hpp.
benchmarkPreparing() [1/2]
void Catch::CumulativeReporterBase::benchmarkPreparing (StringRef benchmarkName) inline override virtual
Called when user-code is being probed before the actual benchmark runs.
Implements Catch::IEventListener.
Definition at line 12503 of file catch_amalgamated.hpp.
benchmarkPreparing() [2/2]
void Catch::CumulativeReporterBase::benchmarkPreparing (StringRef benchmarkName) inline override virtual
Called when user-code is being probed before the actual benchmark runs.
Implements Catch::IEventListener.
Definition at line 99 of file catch_reporter_cumulative_base.hpp.
benchmarkStarting() [1/2]
void Catch::CumulativeReporterBase::benchmarkStarting (BenchmarkInfo const & benchmarkInfo) inline override virtual
Called after probe but before the user-code is being benchmarked.
Implements Catch::IEventListener.
Definition at line 12504 of file catch_amalgamated.hpp.
benchmarkStarting() [2/2]
void Catch::CumulativeReporterBase::benchmarkStarting (BenchmarkInfo const & benchmarkInfo) inline override virtual
Called after probe but before the user-code is being benchmarked.
Implements Catch::IEventListener.
Definition at line 100 of file catch_reporter_cumulative_base.hpp.
fatalErrorEncountered() [1/2]
void Catch::CumulativeReporterBase::fatalErrorEncountered (StringRef error) inline override virtual
Called if a fatal error (signal/structured exception) occurred.
Implements Catch::IEventListener.
Definition at line 12510 of file catch_amalgamated.hpp.
fatalErrorEncountered() [2/2]
void Catch::CumulativeReporterBase::fatalErrorEncountered (StringRef error) inline override virtual
Called if a fatal error (signal/structured exception) occurred.
Implements Catch::IEventListener.
Definition at line 106 of file catch_reporter_cumulative_base.hpp.
noMatchingTestCases() [1/2]
void Catch::CumulativeReporterBase::noMatchingTestCases (StringRef unmatchedSpec) inline override virtual
Called when no test cases match provided test spec.
Implements Catch::IEventListener.
Definition at line 12508 of file catch_amalgamated.hpp.
noMatchingTestCases() [2/2]
void Catch::CumulativeReporterBase::noMatchingTestCases (StringRef unmatchedSpec) inline override virtual
Called when no test cases match provided test spec.
Implements Catch::IEventListener.
Definition at line 104 of file catch_reporter_cumulative_base.hpp.
reportInvalidTestSpec() [1/2]
void Catch::CumulativeReporterBase::reportInvalidTestSpec (StringRef invalidArgument) inline override virtual
Called for all invalid test specs from the cli.
Implements Catch::IEventListener.
Definition at line 12509 of file catch_amalgamated.hpp.
reportInvalidTestSpec() [2/2]
void Catch::CumulativeReporterBase::reportInvalidTestSpec (StringRef invalidArgument) inline override virtual
Called for all invalid test specs from the cli.
Implements Catch::IEventListener.
Definition at line 105 of file catch_reporter_cumulative_base.hpp.
sectionEnded() [1/2]
void Catch::CumulativeReporterBase::sectionEnded (SectionStats const & sectionStats) override virtual
Called after a SECTION has finished running.
Implements Catch::IEventListener.
Definition at line 9015 of file catch_amalgamated.cpp.
References Catch::CumulativeReporterBase::SectionNode::stats.
sectionEnded() [2/2]
void Catch::CumulativeReporterBase::sectionEnded (SectionStats const & sectionStats) override virtual
Called after a SECTION has finished running.
Implements Catch::IEventListener.
sectionStarting() [1/2]
void Catch::CumulativeReporterBase::sectionStarting (SectionInfo const & sectionInfo) override virtual
Called when a SECTION is being entered. Not called for skipped sections.
Implements Catch::IEventListener.
Definition at line 8964 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::CumulativeReporterBase::SectionNode::childSections, and Catch::Detail::make_unique().
sectionStarting() [2/2]
void Catch::CumulativeReporterBase::sectionStarting (SectionInfo const & sectionInfo) override virtual
Called when a SECTION is being entered. Not called for skipped sections.
Implements Catch::IEventListener.
skipTest() [1/2]
void Catch::CumulativeReporterBase::skipTest (TestCaseInfo const & testInfo) inline override virtual
Called with test cases that are skipped due to the test run aborting. NOT called for test cases that are explicitly skipped using the SKIP macro.
Deprecated - will be removed in the next major release.
Implements Catch::IEventListener.
Definition at line 12528 of file catch_amalgamated.hpp.
skipTest() [2/2]
void Catch::CumulativeReporterBase::skipTest (TestCaseInfo const & testInfo) inline override virtual
Called with test cases that are skipped due to the test run aborting. NOT called for test cases that are explicitly skipped using the SKIP macro.
Deprecated - will be removed in the next major release.
Implements Catch::IEventListener.
Definition at line 124 of file catch_reporter_cumulative_base.hpp.
testCaseEnded() [1/2]
void Catch::CumulativeReporterBase::testCaseEnded (TestCaseStats const & testCaseStats) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
Reimplemented in Catch::JunitReporter, and Catch::JunitReporter.
Definition at line 9022 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::Detail::make_unique(), Catch::TestCaseStats::stdErr, and Catch::TestCaseStats::stdOut.
Referenced by Catch::JunitReporter::testCaseEnded().
testCaseEnded() [2/2]
void Catch::CumulativeReporterBase::testCaseEnded (TestCaseStats const & testCaseStats) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
Reimplemented in Catch::JunitReporter, and Catch::JunitReporter.
testCasePartialEnded() [1/2]
void Catch::CumulativeReporterBase::testCasePartialEnded (TestCaseStats const & testCaseStats, uint64_t partNumber) inline override virtual
Called every time a TEST_CASE is entered, including repeats (due to sections).
Implements Catch::IEventListener.
Definition at line 12522 of file catch_amalgamated.hpp.
testCasePartialEnded() [2/2]
void Catch::CumulativeReporterBase::testCasePartialEnded (TestCaseStats const & testCaseStats, uint64_t partNumber) inline override virtual
Called every time a TEST_CASE is entered, including repeats (due to sections).
Implements Catch::IEventListener.
Definition at line 118 of file catch_reporter_cumulative_base.hpp.
testCasePartialStarting() [1/2]
void Catch::CumulativeReporterBase::testCasePartialStarting (TestCaseInfo const & testInfo, uint64_t partNumber) inline override virtual
Called every time a TEST_CASE is entered, including repeats (due to sections).
Implements Catch::IEventListener.
Definition at line 12515 of file catch_amalgamated.hpp.
testCasePartialStarting() [2/2]
void Catch::CumulativeReporterBase::testCasePartialStarting (TestCaseInfo const & testInfo, uint64_t partNumber) inline override virtual
Called every time a TEST_CASE is entered, including repeats (due to sections).
Implements Catch::IEventListener.
Definition at line 111 of file catch_reporter_cumulative_base.hpp.
testCaseStarting() [1/2]
void Catch::CumulativeReporterBase::testCaseStarting (TestCaseInfo const & testInfo) inline override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
Reimplemented in Catch::JunitReporter, and Catch::JunitReporter.
Definition at line 12514 of file catch_amalgamated.hpp.
testCaseStarting() [2/2]
void Catch::CumulativeReporterBase::testCaseStarting (TestCaseInfo const & testInfo) inline override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
Reimplemented in Catch::JunitReporter, and Catch::JunitReporter.
Definition at line 110 of file catch_reporter_cumulative_base.hpp.
testRunEnded() [1/2]
void Catch::CumulativeReporterBase::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Implements Catch::IEventListener.
Definition at line 9035 of file catch_amalgamated.cpp.
References m_testRun, Catch::Detail::make_unique(), and testRunEndedCumulative().
testRunEnded() [2/2]
void Catch::CumulativeReporterBase::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Implements Catch::IEventListener.
testRunEndedCumulative() [1/2]
virtual void Catch::CumulativeReporterBase::testRunEndedCumulative () pure virtual
Customization point: called after last test finishes (testRunEnded has been handled).
Implemented in Catch::JunitReporter, Catch::JunitReporter, Catch::SonarQubeReporter, and Catch::SonarQubeReporter.
Referenced by testRunEnded().
testRunEndedCumulative() [2/2]
virtual void Catch::CumulativeReporterBase::testRunEndedCumulative () pure virtual
Customization point: called after last test finishes (testRunEnded has been handled).
Implemented in Catch::JunitReporter, Catch::JunitReporter, Catch::SonarQubeReporter, and Catch::SonarQubeReporter.
testRunStarting() [1/2]
void Catch::CumulativeReporterBase::testRunStarting (TestRunInfo const & testRunInfo) inline override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Implements Catch::IEventListener.
Reimplemented in Catch::JunitReporter, Catch::JunitReporter, Catch::SonarQubeReporter, and Catch::SonarQubeReporter.
Definition at line 12512 of file catch_amalgamated.hpp.
Referenced by Catch::JunitReporter::testRunStarting(), and Catch::SonarQubeReporter::testRunStarting().
testRunStarting() [2/2]
void Catch::CumulativeReporterBase::testRunStarting (TestRunInfo const & testRunInfo) inline override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Implements Catch::IEventListener.
Reimplemented in Catch::JunitReporter, Catch::JunitReporter, Catch::SonarQubeReporter, and Catch::SonarQubeReporter.
Definition at line 108 of file catch_reporter_cumulative_base.hpp.
Member Data Documentation
m_shouldStoreFailedAssertions
bool Catch::CumulativeReporterBase::m_shouldStoreFailedAssertions = true protected
Should the cumulative base store the assertion expansion for failed assertions?
Definition at line 12534 of file catch_amalgamated.hpp.
Referenced by assertionEnded().
m_shouldStoreSuccesfulAssertions
bool Catch::CumulativeReporterBase::m_shouldStoreSuccesfulAssertions = true protected
Should the cumulative base store the assertion expansion for successful assertions?
Definition at line 12532 of file catch_amalgamated.hpp.
Referenced by assertionEnded(), Catch::JunitReporter::JunitReporter(), and Catch::SonarQubeReporter::SonarQubeReporter().
m_testRun
Detail::unique_ptr< TestRunNode > Catch::CumulativeReporterBase::m_testRun protected
The root node of the test run tree.
Definition at line 12539 of file catch_amalgamated.hpp.
Referenced by testRunEnded(), Catch::JunitReporter::testRunEndedCumulative(), and Catch::SonarQubeReporter::testRunEndedCumulative().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/reporters/catch_reporter_cumulative_base.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/reporters/catch_reporter_cumulative_base.cpp