libthe-seed: ComponentLoader::Loader Class Reference
ComponentLoader::Loader Class Reference
#include <ComponentLoader.hpp>
Public Member Functions
Loader (std::string library)
~Loader ()
ecs::Component * ComponentCreate ()
ecs::Component * ComponentCreate (void *data)
ComponentCreator ComponentGet ()
Private Attributes
LibraryLoader * library
Detailed Description
Definition at line 11 of file ComponentLoader.hpp.
Constructor & Destructor Documentation
Loader()
ComponentLoader::Loader::Loader (std::string library)
Definition at line 9 of file ComponentLoader.cpp.
     {
         auto name = NameParser(library);
         try
         {
             this->library = new LibraryLoader(name.library);
             this->library->PathAdd(".");
             this->library->PathAdd("../../" + name.library + "/src/.libs/");
             if(name.org.size())
             {
                 auto path = "../node_modules/" + name.org + "/" + name.library + "/src/.libs";
                 this->library->PathAdd(path);
             }
             for(auto path : component_paths) this->library->PathAdd(path);
         }
         catch(std::string e)
         {
             std::cout << "Exception in ComponentLoader::Loader::Loader()" << e << std::endl;
             throw e;
         }
     }
References ComponentLoader::component_paths, and library.
~Loader()
ComponentLoader::Loader::~Loader ()
Member Function Documentation
ComponentCreate() [1/2]
ecs::Component * ComponentLoader::Loader::ComponentCreate ()
Definition at line 40 of file ComponentLoader.cpp.
     {
         void *ptr = this->library->FunctionGet("create_component");
         ComponentCreator creator = reinterpret_cast<ComponentCreator>(ptr);
         return creator(nullptr);
     }
References LibraryLoader::FunctionGet(), and library.
ComponentCreate() [2/2]
ecs::Component * ComponentLoader::Loader::ComponentCreate (void * data)
Definition at line 47 of file ComponentLoader.cpp.
     {
         void *ptr;
         try
         {
             ptr = this->library->FunctionGet("create_component");
         }
         catch(std::string e)
         {
             std::cout << "ComponentLoader::Loader(\"" + this->library->name + "\")::ComponentCreate(&data): Couldn't find create_component in library.";
             std::cout << e << std::endl;
             throw e;
         }
         ComponentCreator creator = reinterpret_cast<ComponentCreator>(ptr);
         return creator(data);
     }
References LibraryLoader::FunctionGet(), library, and LibraryLoader::name.
ComponentGet()
ComponentCreator ComponentLoader::Loader::ComponentGet ()
Definition at line 33 of file ComponentLoader.cpp.
     {
         void *ptr = this->library->FunctionGet("create_component");
         ComponentCreator creator = reinterpret_cast<ComponentCreator>(ptr);
         return creator;
     }
References LibraryLoader::FunctionGet(), and library.
Member Data Documentation
library
LibraryLoader* ComponentLoader::Loader::library private
Definition at line 20 of file ComponentLoader.hpp.
Referenced by ComponentCreate(), ComponentGet(), and Loader().
The documentation for this class was generated from the following files:
include/libthe-seed/ComponentLoader.hpp
src/ComponentLoader.cpp