libthe-seed: Catch::Clara::Detail::ParserBase Class Reference
Catch::Clara::Detail::ParserBase Class Reference abstract
#include <catch_amalgamated.hpp>
Public Member Functions
virtual ~ParserBase ()=default
virtual auto validate () const -> Result
virtual auto parse (std::string const &exeName, TokenStream const &tokens) const -> InternalParseResult=0
virtual size_t cardinality () const
InternalParseResult parse (Args const &args) const
virtual ~ParserBase ()=default
virtual auto validate () const -> Result
virtual auto parse (std::string const &exeName, TokenStream const &tokens) const -> InternalParseResult=0
virtual size_t cardinality () const
InternalParseResult parse (Args const &args) const
Detailed Description
Definition at line 4871 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
~ParserBase() [1/2]
virtual Catch::Clara::Detail::ParserBase::~ParserBase () virtual default
~ParserBase() [2/2]
virtual Catch::Clara::Detail::ParserBase::~ParserBase () virtual default
Member Function Documentation
cardinality() [1/2]
size_t Catch::Clara::Detail::ParserBase::cardinality () const virtual
Definition at line 2559 of file catch_amalgamated.cpp.
Referenced by parse().
cardinality() [2/2]
virtual size_t Catch::Clara::Detail::ParserBase::cardinality () const virtual
parse() [1/4]
InternalParseResult Catch::Clara::Detail::ParserBase::parse (Args const & args) const
Definition at line 2561 of file catch_amalgamated.cpp.
References Catch::Clara::Args::exeName(), and parse().
parse() [2/4]
InternalParseResult Catch::Clara::Detail::ParserBase::parse (Args const & args) const
parse() [3/4]
virtual auto Catch::Clara::Detail::ParserBase::parse (std::string const & exeName, TokenStream const & tokens) const->InternalParseResult pure virtual
References cardinality(), and parse().
Referenced by parse(), and parse().
parse() [4/4]
virtual auto Catch::Clara::Detail::ParserBase::parse (std::string const & exeName, TokenStream const & tokens) const->InternalParseResult pure virtual
validate() [1/2]
virtual auto Catch::Clara::Detail::ParserBase::validate () const->Result inline virtual
Definition at line 4874 of file catch_amalgamated.hpp.
References Catch::Clara::Detail::BasicResult< void >::ok().
Referenced by Catch::Clara::Arg::parse().
validate() [2/2]
virtual auto Catch::Clara::Detail::ParserBase::validate () const->Result inline virtual
Definition at line 446 of file catch_clara.hpp.
References Catch::Clara::Detail::BasicResult< void >::ok().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_clara.cpp