libthe-seed: DependencyLister Class Reference
DependencyLister Class Reference
Analyzes binaries to build a reverse dependency map of shared libraries.
#include <DependencyLister.hpp>
Public Member Functions
DependencyResult ListDependencies (const std::vector< std::string > &binary_paths, const std::vector< std::string > &search_paths)
Build a complete reverse dependency map for the given binaries.
DependencyResult ListDependencies (const std::vector< std::string > &binary_paths, const std::vector< std::string > &search_paths)
Build a complete reverse dependency map for the given binaries.
Detailed Description
Analyzes binaries to build a reverse dependency map of shared libraries.
Parses ELF and PE binary formats directly (no external library dependencies). Supports cross-platform analysis: ELF binaries can be parsed on Windows and PE binaries can be parsed on Linux.
Usage:
DependencyLister lister;
auto result = lister.ListDependencies(
    {"./build/myapp", "./build/libfoo.so"},
    {"/usr/lib", "/usr/local/lib", "./build/libs"}
);
// result.dependencies: library path -> [project files that need it]
// result.errors: file path -> error description
Definition at line 53 of file DependencyLister.hpp.
Member Function Documentation
ListDependencies() [1/2]
DependencyResult DependencyLister::ListDependencies (const std::vector< std::string > & binary_paths, const std::vector< std::string > & search_paths)
Build a complete reverse dependency map for the given binaries.
Accepts a list of binary file paths and a list of search directories. For each binary, extracts shared library dependencies (DT_NEEDED for ELF, import table for PE) and recursively resolves transitive dependencies using the provided search paths.
The result maps each discovered library's resolved absolute path (or recorded name if unresolvable) to the list of input binaries that depend on it.
Errors for individual binaries are collected in the error map without aborting processing of remaining binaries.
Parameters
binary_paths List of file paths to compiled binaries (ELF or PE).
search_paths Ordered list of directories to search when resolving library names to filesystem paths. No platform defaults are used.
Returns
DependencyResult containing the dependency map and error map.
Definition at line 134 of file DependencyLister.cpp.
References DependencyResult::dependencies, and DependencyResult::errors.
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
ListDependencies() [2/2]
DependencyResult DependencyLister::ListDependencies (const std::vector< std::string > & binary_paths, const std::vector< std::string > & search_paths)
Build a complete reverse dependency map for the given binaries.
Accepts a list of binary file paths and a list of search directories. For each binary, extracts shared library dependencies (DT_NEEDED for ELF, import table for PE) and recursively resolves transitive dependencies using the provided search paths.
The result maps each discovered library's resolved absolute path (or recorded name if unresolvable) to the list of input binaries that depend on it.
Errors for individual binaries are collected in the error map without aborting processing of remaining binaries.
Parameters
binary_paths List of file paths to compiled binaries (ELF or PE).
search_paths Ordered list of directories to search when resolving library names to filesystem paths. No platform defaults are used.
Returns
DependencyResult containing the dependency map and error map.
The documentation for this class was generated from the following files:
include/libthe-seed/DependencyLister.hpp
specs/001-dependency-lister/contracts/DependencyLister.hpp
src/DependencyLister.cpp