libthe-seed: ResourcePak Class Reference
ResourcePak Class Reference
Loads resources (images, sounds, etc.) from .pak files.
#include <ResourcePak.hpp>
Public Member Functions
ResourcePak (std::string filename)
Construct a new ResourcePak object.
void Load (ecs::Container *container, std::string name)
Load resource by name.
ecs::Resource Load (std::string name)
Load resource by name.
void LoadAll (ecs::Container *container)
Load all resources in Resource Pak.
Detailed Description
Loads resources (images, sounds, etc.) from .pak files.
Definition at line 12 of file ResourcePak.hpp.
Constructor & Destructor Documentation
ResourcePak()
ResourcePak::ResourcePak (std::string filename)
Construct a new ResourcePak object.
Parameters
filename Path to resource pak to load.
Definition at line 4 of file ResourcePak.cpp.
Member Function Documentation
Load() [1/2]
void ResourcePak::Load (ecs::Container * container, std::string name)
Load resource by name.
Parameters
container Container to load resource into.
name Name of resource to load.
Definition at line 38 of file ResourcePak.cpp.
References Load().
Referenced by Load(), and LoadAll().
Load() [2/2]
ecs::Resource ResourcePak::Load (std::string name)
Load resource by name.
Parameters
name Name of resource to load.
Returns
Handle to Resource
Definition at line 43 of file ResourcePak.cpp.
LoadAll()
void ResourcePak::LoadAll (ecs::Container * container)
Load all resources in Resource Pak.
Parameters
container Container to load resource into.
Definition at line 63 of file ResourcePak.cpp.
References Load().
The documentation for this class was generated from the following files:
include/libthe-seed/ResourcePak.hpp
src/ResourcePak.cpp