libthe-seed: Catch::Context Class Reference
Catch::Context Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
IResultCapture * getResultCapture () const
IConfig const * getConfig () const
void setResultCapture (IResultCapture *resultCapture)
void setConfig (IConfig const *config)
IResultCapture * getResultCapture () const
IConfig const * getConfig () const
void setResultCapture (IResultCapture *resultCapture)
void setConfig (IConfig const *config)
Friends
Context & getCurrentMutableContext ()
Context const & getCurrentContext ()
void cleanUpContext ()
Context & getCurrentMutableContext ()
Context const & getCurrentContext ()
void cleanUpContext ()
Detailed Description
Definition at line 541 of file catch_amalgamated.hpp.
Member Function Documentation
getConfig() [1/2]
IConfig const * Catch::Context::getConfig () const inline
Definition at line 553 of file catch_amalgamated.hpp.
Referenced by Catch::AssertionHandler::allowThrows(), Catch::getSeed(), Catch::Benchmark::Benchmark::operator=(), Catch::rngSeed(), and Catch::Benchmark::Benchmark::run().
getConfig() [2/2]
IConfig const * Catch::Context::getConfig () const inline
Definition at line 30 of file catch_context.hpp.
getResultCapture() [1/2]
IResultCapture * Catch::Context::getResultCapture () const inline
Definition at line 552 of file catch_amalgamated.hpp.
getResultCapture() [2/2]
IResultCapture * Catch::Context::getResultCapture () const inline
Definition at line 29 of file catch_context.hpp.
setConfig() [1/2]
void Catch::Context::setConfig (IConfig const * config)
Definition at line 3475 of file catch_amalgamated.cpp.
Referenced by Catch::Session::applyCommandLine(), and Catch::Session::Session().
setConfig() [2/2]
void Catch::Context::setConfig (IConfig const * config)
setResultCapture() [1/2]
void Catch::Context::setResultCapture (IResultCapture * resultCapture)
Definition at line 3471 of file catch_amalgamated.cpp.
Referenced by Catch::RunContext::RunContext().
setResultCapture() [2/2]
void Catch::Context::setResultCapture (IResultCapture * resultCapture)
Friends And Related Symbol Documentation
cleanUpContext [1/2]
void cleanUpContext () friend
Definition at line 3457 of file catch_amalgamated.cpp.
cleanUpContext [2/2]
void cleanUpContext () friend
Definition at line 3457 of file catch_amalgamated.cpp.
getCurrentContext [1/2]
Context const & getCurrentContext () friend
Definition at line 560 of file catch_amalgamated.hpp.
getCurrentContext [2/2]
Context const & getCurrentContext () friend
Definition at line 560 of file catch_amalgamated.hpp.
getCurrentMutableContext [1/2]
Context & getCurrentMutableContext () friend
Definition at line 3465 of file catch_amalgamated.cpp.
getCurrentMutableContext [2/2]
Context & getCurrentMutableContext () friend
Definition at line 3465 of file catch_amalgamated.cpp.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_context.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_context.cpp