libthe-seed: unrelated::needs_ADL_begin< T > Class Template Reference
unrelated::needs_ADL_begin< T > Class Template Reference
#include <range_test_helpers.hpp>
Public Types
using iterator = typename std::vector<T>::iterator
using const_iterator = typename std::vector<T>::const_iterator
Public Member Functions
needs_ADL_begin (std::initializer_list< T > init)
const_iterator Begin () const
const_iterator End () const
Friends
const_iterator begin (needs_ADL_begin const &lhs)
const_iterator end (needs_ADL_begin const &rhs)
Detailed Description
template<typename T>
class unrelated::needs_ADL_begin< T >
Definition at line 21 of file range_test_helpers.hpp.
Member Typedef Documentation
const_iterator
template<typename T> using unrelated::needs_ADL_begin< T >::const_iterator = typename std::vector<T>::const_iterator
Definition at line 26 of file range_test_helpers.hpp.
iterator
template<typename T> using unrelated::needs_ADL_begin< T >::iterator = typename std::vector<T>::iterator
Definition at line 25 of file range_test_helpers.hpp.
Constructor & Destructor Documentation
needs_ADL_begin()
template<typename T> unrelated::needs_ADL_begin< T >::needs_ADL_begin (std::initializer_list< T > init) inline
Definition at line 28 of file range_test_helpers.hpp.
Referenced by begin, and end.
Member Function Documentation
Begin()
template<typename T> const_iterator unrelated::needs_ADL_begin< T >::Begin () const inline
Definition at line 30 of file range_test_helpers.hpp.
Referenced by begin.
End()
template<typename T> const_iterator unrelated::needs_ADL_begin< T >::End () const inline
Definition at line 31 of file range_test_helpers.hpp.
Referenced by end.
Friends And Related Symbol Documentation
begin
template<typename T> const_iterator begin (needs_ADL_begin< T > const & lhs) friend
Definition at line 33 of file range_test_helpers.hpp.
References Begin(), and needs_ADL_begin().
end
template<typename T> const_iterator end (needs_ADL_begin< T > const & rhs) friend
Definition at line 36 of file range_test_helpers.hpp.
References End(), and needs_ADL_begin().
The documentation for this class was generated from the following file:
external/Catch2/tests/SelfTest/helpers/range_test_helpers.hpp