libthe-seed: Catch::Generators::IGenerator< T > Class Template Reference
Catch::Generators::IGenerator< T > Class Template Reference abstract
#include <catch_amalgamated.hpp>
Public Types
using type = T
using type = T
Public Member Functions
~IGenerator () override=default
IGenerator ()=default
IGenerator (IGenerator const &)=default
IGenerator & operator= (IGenerator const &)=default
virtual T const & get () const =0
~IGenerator () override=default
IGenerator ()=default
IGenerator (IGenerator const &)=default
IGenerator & operator= (IGenerator const &)=default
virtual T const & get () const =0
Public Member Functions inherited from Catch::Generators::GeneratorUntypedBase
GeneratorUntypedBase ()=default
GeneratorUntypedBase (GeneratorUntypedBase const &)=default
GeneratorUntypedBase & operator= (GeneratorUntypedBase const &)=default
virtual ~GeneratorUntypedBase ()
bool countedNext ()
std::size_t currentElementIndex () const
StringRef currentElementAsString () const
GeneratorUntypedBase ()=default
GeneratorUntypedBase (GeneratorUntypedBase const &)=default
GeneratorUntypedBase & operator= (GeneratorUntypedBase const &)=default
virtual ~GeneratorUntypedBase ()
bool countedNext ()
std::size_t currentElementIndex () const
StringRef currentElementAsString () const
Detailed Description
template<typename T>
class Catch::Generators::IGenerator< T >
Definition at line 7530 of file catch_amalgamated.hpp.
Member Typedef Documentation
type [1/2]
template<typename T> using Catch::Generators::IGenerator< T >::type = T
Definition at line 7547 of file catch_amalgamated.hpp.
type [2/2]
template<typename T> using Catch::Generators::IGenerator< T >::type = T
Definition at line 51 of file catch_generators.hpp.
Constructor & Destructor Documentation
~IGenerator() [1/2]
template<typename T> Catch::Generators::IGenerator< T >::~IGenerator () override default
IGenerator() [1/4]
template<typename T> Catch::Generators::IGenerator< T >::IGenerator () default
Referenced by IGenerator(), and operator=().
IGenerator() [2/4]
template<typename T> Catch::Generators::IGenerator< T >::IGenerator (IGenerator< T > const &) default
References IGenerator().
~IGenerator() [2/2]
template<typename T> Catch::Generators::IGenerator< T >::~IGenerator () override default
IGenerator() [3/4]
template<typename T> Catch::Generators::IGenerator< T >::IGenerator () default
IGenerator() [4/4]
template<typename T> Catch::Generators::IGenerator< T >::IGenerator (IGenerator< T > const &) default
References IGenerator().
Member Function Documentation
get() [1/2]
template<typename T> virtual T const & Catch::Generators::IGenerator< T >::get () const pure virtual
Implemented in Catch::Generators::ChunkGenerator< T >, Catch::Generators::ChunkGenerator< T >, Catch::Generators::FilterGenerator< T, Predicate >, Catch::Generators::FilterGenerator< T, Predicate >, Catch::Generators::FixedValuesGenerator< T >, Catch::Generators::FixedValuesGenerator< T >, Catch::Generators::Generators< T >, Catch::Generators::Generators< T >, Catch::Generators::IteratorGenerator< T >, Catch::Generators::IteratorGenerator< T >, Catch::Generators::MapGenerator< T, U, Func >, Catch::Generators::MapGenerator< T, U, Func >, Catch::Generators::RandomFloatingGenerator< Float >, Catch::Generators::RandomFloatingGenerator< Float >, Catch::Generators::RandomIntegerGenerator< Integer >, Catch::Generators::RandomIntegerGenerator< Integer >, Catch::Generators::RangeGenerator< T >, Catch::Generators::RangeGenerator< T >, Catch::Generators::RepeatGenerator< T >, Catch::Generators::RepeatGenerator< T >, Catch::Generators::SingleValueGenerator< T >, Catch::Generators::SingleValueGenerator< T >, Catch::Generators::TakeGenerator< T >, and Catch::Generators::TakeGenerator< T >.
get() [2/2]
template<typename T> virtual T const & Catch::Generators::IGenerator< T >::get () const pure virtual
Implemented in Catch::Generators::FilterGenerator< T, Predicate >, Catch::Generators::FilterGenerator< T, Predicate >, Catch::Generators::FixedValuesGenerator< T >, Catch::Generators::FixedValuesGenerator< T >, Catch::Generators::Generators< T >, Catch::Generators::Generators< T >, Catch::Generators::IteratorGenerator< T >, Catch::Generators::IteratorGenerator< T >, Catch::Generators::MapGenerator< T, U, Func >, Catch::Generators::MapGenerator< T, U, Func >, Catch::Generators::RangeGenerator< T >, Catch::Generators::RangeGenerator< T >, Catch::Generators::RepeatGenerator< T >, Catch::Generators::RepeatGenerator< T >, Catch::Generators::SingleValueGenerator< T >, Catch::Generators::SingleValueGenerator< T >, Catch::Generators::TakeGenerator< T >, and Catch::Generators::TakeGenerator< T >.
operator=() [1/2]
template<typename T> IGenerator & Catch::Generators::IGenerator< T >::operator= (IGenerator< T > const &) default
References IGenerator().
operator=() [2/2]
template<typename T> IGenerator & Catch::Generators::IGenerator< T >::operator= (IGenerator< T > const &) default
References IGenerator().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/generators/catch_generators.hpp