libthe-seed: Catch::Clara::Detail::ResultValueBase< void > Class Reference
Catch::Clara::Detail::ResultValueBase< void > Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
auto value () const -> void const &
Public Attributes
void m_value
Protected Member Functions
ResultBase (ResultType type)
ResultBase (ResultBase const &)=default
ResultBase (ResultBase &&)=default
ResultValueBase (ResultType type)
auto operator= (ResultValueBase const &other) -> ResultValueBase &
~ResultValueBase () override
Protected Member Functions inherited from Catch::Clara::Detail::ResultBase
ResultBase (ResultType type)
virtual ~ResultBase ()
ResultBase (ResultBase const &)=default
ResultBase & operator= (ResultBase const &)=default
ResultBase (ResultBase &&)=default
ResultBase & operator= (ResultBase &&)=default
virtual void enforceOk () const =0
ResultBase (ResultType type)
virtual ~ResultBase ()
ResultBase (ResultBase const &)=default
ResultBase & operator= (ResultBase const &)=default
ResultBase (ResultBase &&)=default
ResultBase & operator= (ResultBase &&)=default
virtual void enforceOk () const =0
Protected Attributes
union {
T m_value
};
union {
T m_value
};
Protected Attributes inherited from Catch::Clara::Detail::ResultBase
ResultType m_type
Detailed Description
Definition at line 4634 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ResultValueBase()
Catch::Clara::Detail::ResultValueBase< void >::ResultValueBase (ResultType type) inline protected
Definition at line 4602 of file catch_amalgamated.hpp.
Referenced by Catch::Clara::Detail::BasicResult< void >::BasicResult(), and Catch::Clara::Detail::BasicResult< void >::BasicResult().
~ResultValueBase()
Catch::Clara::Detail::ResultValueBase< void >::~ResultValueBase () inline override protected
Definition at line 4624 of file catch_amalgamated.hpp.
Member Function Documentation
operator=()
auto Catch::Clara::Detail::ResultValueBase< void >::operator= (ResultValueBase< void > const & other) ->ResultValueBase & inline protected
Definition at line 4614 of file catch_amalgamated.hpp.
ResultBase() [1/3]
Catch::Clara::Detail::ResultBase::ResultBase (ResultBase &&) protected default
ResultBase() [2/3]
Catch::Clara::Detail::ResultBase::ResultBase (ResultBase const &) protected default
ResultBase() [3/3]
Catch::Clara::Detail::ResultBase::ResultBase (ResultType type) inline protected
Definition at line 4580 of file catch_amalgamated.hpp.
value()
auto Catch::Clara::Detail::ResultValueBase< void >::value () const->Tconst & inline
Definition at line 4596 of file catch_amalgamated.hpp.
Referenced by Catch::Clara::Detail::BasicResult< void >::ok().
Member Data Documentation
[union]
union { ... } Catch::Clara::Detail::ResultValueBase< void >
[union]
union { ... } Catch::Clara::Detail::ResultValueBase< void >
m_value
void Catch::Clara::Detail::ResultValueBase< void >::m_value
Definition at line 4630 of file catch_amalgamated.hpp.
The documentation for this class was generated from the following file:
external/Catch2/extras/catch_amalgamated.hpp