libthe-seed: JSONLoader Class Reference
JSONLoader Class Reference
Loads Entities, Components, and Systems from JSON data.
#include <JSONLoader.hpp>
Public Member Functions
JSONLoader (ecs::Container *container)
Construct a new JSONLoader object.
~JSONLoader ()
void StringParse (std::string data)
Parses ECS data from string.
void FileParse (std::string filename)
Parses ECS data from a file.
Detailed Description
Definition at line 10 of file JSONLoader.hpp.
Constructor & Destructor Documentation
JSONLoader()
JSONLoader::JSONLoader (ecs::Container * container)
Parameters
container A pointer to the ECS container that will house the Entities, Components, and Systems imported from JSON data.
Definition at line 5 of file JSONLoader.cpp.
                                              : container(container)
 {
 }
~JSONLoader()
JSONLoader::~JSONLoader ()
Definition at line 49 of file JSONLoader.cpp.
 {
 }
Member Function Documentation
FileParse()
void JSONLoader::FileParse (std::string filename)
Parameters
filename JSON formatted file containing ECS data.
Definition at line 31 of file JSONLoader.cpp.
 {
     std::string data;
     std::ifstream file;
     std::streampos fsize, fstart = 0;
     file.open(filename);
     fstart = file.tellg();
     file.seekg(0, std::ios::end);
     fsize = file.tellg() - fstart;
     file.seekg(0, std::ios::beg);
     data.resize(fsize);
     file.read(&data[0], fsize);
     file.close();
     this->StringParse(data);
 }
References StringParse().
StringParse()
void JSONLoader::StringParse (std::string data)
Parameters
data JSON formatted ECS data.
Definition at line 9 of file JSONLoader.cpp.
 {
     Json::Reader reader;
     if(!reader.parse(data.c_str(), this->scene))
     {
         std::string err = "Couldn't parse scene: " + data;
         throw std::runtime_error(err);
     }
     for(auto entity : this->scene["entities"])
     {
         auto e = this->container->Entity(entity["Handle"].asString());
         for(auto type : entity["Components"].getMemberNames())
         {
             for(auto component : entity["Components"][type])
             {
                 e->Component(ComponentLoader::Create(type, &component));
             }
         }
     }
 }
References ComponentLoader::Create().
Referenced by FileParse().
The documentation for this class was generated from the following files:
include/libthe-seed/JSONLoader.hpp
src/JSONLoader.cpp