libthe-seed: Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs > Class Template Reference
Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs > Class Template Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
MatchAllOfGeneric (MatchAllOfGeneric const &)=delete
MatchAllOfGeneric & operator= (MatchAllOfGeneric const &)=delete
MatchAllOfGeneric (MatchAllOfGeneric &&)=default
MatchAllOfGeneric & operator= (MatchAllOfGeneric &&)=default
MatchAllOfGeneric (MatcherTs const &... matchers)
MatchAllOfGeneric (std::array< void const *, sizeof...(MatcherTs)> matchers)
template<typename Arg>
bool match (Arg &&arg) const
std::string describe () const override
MatchAllOfGeneric (MatchAllOfGeneric const &)=delete
MatchAllOfGeneric & operator= (MatchAllOfGeneric const &)=delete
MatchAllOfGeneric (MatchAllOfGeneric &&)=default
MatchAllOfGeneric & operator= (MatchAllOfGeneric &&)=default
MatchAllOfGeneric (MatcherTs const &... matchers)
MatchAllOfGeneric (std::array< void const *, sizeof...(MatcherTs)> matchers)
template<typename Arg>
bool match (Arg &&arg) const
std::string describe () const override
Public Member Functions inherited from Catch::Matchers::MatcherGenericBase
MatcherGenericBase ()=default
~MatcherGenericBase () override
MatcherGenericBase (MatcherGenericBase const &)=default
MatcherGenericBase (MatcherGenericBase &&)=default
MatcherGenericBase & operator= (MatcherGenericBase const &)=delete
MatcherGenericBase & operator= (MatcherGenericBase &&)=delete
MatcherGenericBase ()=default
~MatcherGenericBase () override
MatcherGenericBase (MatcherGenericBase const &)=default
MatcherGenericBase (MatcherGenericBase &&)=default
MatcherGenericBase & operator= (MatcherGenericBase const &)=delete
MatcherGenericBase & operator= (MatcherGenericBase &&)=delete
Public Member Functions inherited from Catch::Matchers::MatcherUntypedBase
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
Public Attributes
std::array< void const *, sizeof...(MatcherTs)> m_matchers
Friends
template<typename... MatchersRHS>
MatchAllOfGeneric< MatcherTs..., MatchersRHS... > operator&& (MatchAllOfGeneric< MatcherTs... > &&lhs, MatchAllOfGeneric< MatchersRHS... > &&rhs)
Avoids type nesting for GenericAllOf && GenericAllOf case.
template<typename MatcherRHS>
std::enable_if_t< is_matcher< MatcherRHS >::value, MatchAllOfGeneric< MatcherTs..., MatcherRHS > > operator&& (MatchAllOfGeneric< MatcherTs... > &&lhs, MatcherRHS const &rhs)
Avoids type nesting for GenericAllOf && some matcher case.
template<typename MatcherLHS>
std::enable_if_t< is_matcher< MatcherLHS >::value, MatchAllOfGeneric< MatcherLHS, MatcherTs... > > operator&& (MatcherLHS const &lhs, MatchAllOfGeneric< MatcherTs... > &&rhs)
Avoids type nesting for some matcher && GenericAllOf case.
template<typename... MatchersRHS>
MatchAllOfGeneric< MatcherTs..., MatchersRHS... > operator&& (MatchAllOfGeneric< MatcherTs... > &&lhs, MatchAllOfGeneric< MatchersRHS... > &&rhs)
Avoids type nesting for GenericAllOf && GenericAllOf case.
template<typename MatcherRHS>
std::enable_if_t< is_matcher< MatcherRHS >::value, MatchAllOfGeneric< MatcherTs..., MatcherRHS > > operator&& (MatchAllOfGeneric< MatcherTs... > &&lhs, MatcherRHS const &rhs)
Avoids type nesting for GenericAllOf && some matcher case.
template<typename MatcherLHS>
std::enable_if_t< is_matcher< MatcherLHS >::value, MatchAllOfGeneric< MatcherLHS, MatcherTs... > > operator&& (MatcherLHS const &lhs, MatchAllOfGeneric< MatcherTs... > &&rhs)
Avoids type nesting for some matcher && GenericAllOf case.
Additional Inherited Members
Protected Member Functions inherited from Catch::Matchers::MatcherUntypedBase
virtual ~MatcherUntypedBase ()
virtual ~MatcherUntypedBase ()
Protected Attributes inherited from Catch::Matchers::MatcherUntypedBase
std::string m_cachedToString
Detailed Description
template<typename... MatcherTs>
class Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >
Definition at line 11019 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
MatchAllOfGeneric() [1/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::MatchAllOfGeneric (MatchAllOfGeneric< MatcherTs > const &) delete
References MatchAllOfGeneric().
Referenced by MatchAllOfGeneric(), MatchAllOfGeneric(), operator&&, operator&&, operator&&, operator=(), and operator=().
MatchAllOfGeneric() [2/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::MatchAllOfGeneric (MatchAllOfGeneric< MatcherTs > &&) default
References MatchAllOfGeneric().
MatchAllOfGeneric() [3/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::MatchAllOfGeneric (MatcherTs const &... matchers) inline
Definition at line 11026 of file catch_amalgamated.hpp.
References m_matchers.
MatchAllOfGeneric() [4/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::MatchAllOfGeneric (std::array< void const *, sizeof...(MatcherTs)> matchers) inline explicit
Definition at line 11027 of file catch_amalgamated.hpp.
References m_matchers.
MatchAllOfGeneric() [5/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::MatchAllOfGeneric (MatchAllOfGeneric< MatcherTs > const &) delete
References MatchAllOfGeneric().
MatchAllOfGeneric() [6/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::MatchAllOfGeneric (MatchAllOfGeneric< MatcherTs > &&) default
References MatchAllOfGeneric().
MatchAllOfGeneric() [7/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::MatchAllOfGeneric (MatcherTs const &... matchers) inline
Definition at line 117 of file catch_matchers_templated.hpp.
References m_matchers.
MatchAllOfGeneric() [8/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::MatchAllOfGeneric (std::array< void const *, sizeof...(MatcherTs)> matchers) inline explicit
Definition at line 118 of file catch_matchers_templated.hpp.
References m_matchers.
Member Function Documentation
describe() [1/2]
template<typename... MatcherTs> std::string Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 11034 of file catch_amalgamated.hpp.
References Catch::Matchers::Detail::describe_multi_matcher(), and m_matchers.
describe() [2/2]
template<typename... MatcherTs> std::string Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 125 of file catch_matchers_templated.hpp.
References Catch::Matchers::Detail::describe_multi_matcher(), and m_matchers.
match() [1/2]
template<typename... MatcherTs> template<typename Arg> bool Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::match (Arg && arg) const inline
Definition at line 11030 of file catch_amalgamated.hpp.
References m_matchers, and Catch::Matchers::Detail::match_all_of().
match() [2/2]
template<typename... MatcherTs> template<typename Arg> bool Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::match (Arg && arg) const inline
Definition at line 121 of file catch_matchers_templated.hpp.
References m_matchers, and Catch::Matchers::Detail::match_all_of().
operator=() [1/4]
template<typename... MatcherTs> MatchAllOfGeneric & Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::operator= (MatchAllOfGeneric< MatcherTs > &&) default
References MatchAllOfGeneric().
operator=() [2/4]
template<typename... MatcherTs> MatchAllOfGeneric & Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::operator= (MatchAllOfGeneric< MatcherTs > &&) default
References MatchAllOfGeneric().
operator=() [3/4]
template<typename... MatcherTs> MatchAllOfGeneric & Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::operator= (MatchAllOfGeneric< MatcherTs > const &) delete
References MatchAllOfGeneric().
operator=() [4/4]
template<typename... MatcherTs> MatchAllOfGeneric & Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::operator= (MatchAllOfGeneric< MatcherTs > const &) delete
References MatchAllOfGeneric().
Friends And Related Symbol Documentation
operator&& [1/6]
template<typename... MatcherTs> template<typename... MatchersRHS> MatchAllOfGeneric< MatcherTs..., MatchersRHS... > operator&& (MatchAllOfGeneric< MatcherTs... > && lhs, MatchAllOfGeneric< MatchersRHS... > && rhs) friend
Avoids type nesting for GenericAllOf && GenericAllOf case.
Definition at line 11047 of file catch_amalgamated.hpp.
References Catch::Matchers::Detail::array_cat(), CATCH_MOVE, and MatchAllOfGeneric().
operator&& [2/6]
template<typename... MatcherTs> template<typename... MatchersRHS> MatchAllOfGeneric< MatcherTs..., MatchersRHS... > operator&& (MatchAllOfGeneric< MatcherTs... > && lhs, MatchAllOfGeneric< MatchersRHS... > && rhs) friend
Avoids type nesting for GenericAllOf && GenericAllOf case.
Definition at line 138 of file catch_matchers_templated.hpp.
References Catch::Matchers::Detail::array_cat(), CATCH_MOVE, and MatchAllOfGeneric().
operator&& [3/6]
template<typename... MatcherTs> template<typename MatcherRHS> std::enable_if_t< is_matcher< MatcherRHS >::value, MatchAllOfGeneric< MatcherTs..., MatcherRHS > > operator&& (MatchAllOfGeneric< MatcherTs... > && lhs, MatcherRHS const & rhs) friend
Avoids type nesting for GenericAllOf && some matcher case.
Definition at line 11056 of file catch_amalgamated.hpp.
References Catch::Matchers::Detail::array_cat(), CATCH_MOVE, and MatchAllOfGeneric().
operator&& [4/6]
template<typename... MatcherTs> template<typename MatcherRHS> std::enable_if_t< is_matcher< MatcherRHS >::value, MatchAllOfGeneric< MatcherTs..., MatcherRHS > > operator&& (MatchAllOfGeneric< MatcherTs... > && lhs, MatcherRHS const & rhs) friend
Avoids type nesting for GenericAllOf && some matcher case.
Definition at line 147 of file catch_matchers_templated.hpp.
References Catch::Matchers::Detail::array_cat(), CATCH_MOVE, and MatchAllOfGeneric().
operator&& [5/6]
template<typename... MatcherTs> template<typename MatcherLHS> std::enable_if_t< is_matcher< MatcherLHS >::value, MatchAllOfGeneric< MatcherLHS, MatcherTs... > > operator&& (MatcherLHS const & lhs, MatchAllOfGeneric< MatcherTs... > && rhs) friend
Avoids type nesting for some matcher && GenericAllOf case.
Definition at line 11065 of file catch_amalgamated.hpp.
References Catch::Matchers::Detail::array_cat(), CATCH_MOVE, and MatchAllOfGeneric().
operator&& [6/6]
template<typename... MatcherTs> template<typename MatcherLHS> std::enable_if_t< is_matcher< MatcherLHS >::value, MatchAllOfGeneric< MatcherLHS, MatcherTs... > > operator&& (MatcherLHS const & lhs, MatchAllOfGeneric< MatcherTs... > && rhs) friend
Avoids type nesting for some matcher && GenericAllOf case.
Definition at line 156 of file catch_matchers_templated.hpp.
References Catch::Matchers::Detail::array_cat(), CATCH_MOVE, and MatchAllOfGeneric().
Member Data Documentation
m_matchers
template<typename... MatcherTs> std::array< void const *, sizeof...(MatcherTs)> Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::m_matchers
Definition at line 11041 of file catch_amalgamated.hpp.
Referenced by describe(), match(), MatchAllOfGeneric(), and MatchAllOfGeneric().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/matchers/catch_matchers_templated.hpp