libthe-seed: Catch::Matchers::Detail::MatchAllOf< ArgT > Class Template Reference
Catch::Matchers::Detail::MatchAllOf< ArgT > Class Template Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
MatchAllOf ()=default
MatchAllOf (MatchAllOf const &)=delete
MatchAllOf & operator= (MatchAllOf const &)=delete
MatchAllOf (MatchAllOf &&)=default
MatchAllOf & operator= (MatchAllOf &&)=default
bool match (ArgT const &arg) const override
std::string describe () const override
MatchAllOf ()=default
MatchAllOf (MatchAllOf const &)=delete
MatchAllOf & operator= (MatchAllOf const &)=delete
MatchAllOf (MatchAllOf &&)=default
MatchAllOf & operator= (MatchAllOf &&)=default
bool match (ArgT const &arg) const override
std::string describe () const override
Public Member Functions inherited from Catch::Matchers::MatcherUntypedBase
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
Friends
MatchAllOf operator&& (MatchAllOf &&lhs, MatcherBase< ArgT > const &rhs)
MatchAllOf operator&& (MatcherBase< ArgT > const &lhs, MatchAllOf &&rhs)
MatchAllOf operator&& (MatchAllOf &&lhs, MatcherBase< ArgT > const &rhs)
MatchAllOf operator&& (MatcherBase< ArgT > const &lhs, MatchAllOf &&rhs)
Additional Inherited Members
Protected Member Functions inherited from Catch::Matchers::MatcherUntypedBase
virtual ~MatcherUntypedBase ()
virtual ~MatcherUntypedBase ()
Protected Attributes inherited from Catch::Matchers::MatcherUntypedBase
std::string m_cachedToString
Detailed Description
template<typename ArgT>
class Catch::Matchers::Detail::MatchAllOf< ArgT >
Definition at line 10724 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
MatchAllOf() [1/6]
template<typename ArgT> Catch::Matchers::Detail::MatchAllOf< ArgT >::MatchAllOf () default
Referenced by MatchAllOf(), MatchAllOf(), operator&&, operator&&, operator=(), and operator=().
MatchAllOf() [2/6]
template<typename ArgT> Catch::Matchers::Detail::MatchAllOf< ArgT >::MatchAllOf (MatchAllOf< ArgT > const &) delete
References MatchAllOf().
MatchAllOf() [3/6]
template<typename ArgT> Catch::Matchers::Detail::MatchAllOf< ArgT >::MatchAllOf (MatchAllOf< ArgT > &&) default
References MatchAllOf().
MatchAllOf() [4/6]
template<typename ArgT> Catch::Matchers::Detail::MatchAllOf< ArgT >::MatchAllOf () default
MatchAllOf() [5/6]
template<typename ArgT> Catch::Matchers::Detail::MatchAllOf< ArgT >::MatchAllOf (MatchAllOf< ArgT > const &) delete
References MatchAllOf().
MatchAllOf() [6/6]
template<typename ArgT> Catch::Matchers::Detail::MatchAllOf< ArgT >::MatchAllOf (MatchAllOf< ArgT > &&) default
References MatchAllOf().
Member Function Documentation
describe() [1/2]
template<typename ArgT> std::string Catch::Matchers::Detail::MatchAllOf< ArgT >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 10742 of file catch_amalgamated.hpp.
describe() [2/2]
template<typename ArgT> std::string Catch::Matchers::Detail::MatchAllOf< ArgT >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 66 of file catch_matchers.hpp.
match() [1/2]
template<typename ArgT> bool Catch::Matchers::Detail::MatchAllOf< ArgT >::match (ArgT const & arg) const inline override virtual
Implements Catch::Matchers::MatcherBase< ArgT >.
Definition at line 10735 of file catch_amalgamated.hpp.
Referenced by TEST_CASE().
match() [2/2]
template<typename ArgT> bool Catch::Matchers::Detail::MatchAllOf< ArgT >::match (ArgT const & arg) const inline override virtual
Implements Catch::Matchers::MatcherBase< ArgT >.
Definition at line 59 of file catch_matchers.hpp.
operator=() [1/4]
template<typename ArgT> MatchAllOf & Catch::Matchers::Detail::MatchAllOf< ArgT >::operator= (MatchAllOf< ArgT > &&) default
References MatchAllOf().
operator=() [2/4]
template<typename ArgT> MatchAllOf & Catch::Matchers::Detail::MatchAllOf< ArgT >::operator= (MatchAllOf< ArgT > &&) default
References MatchAllOf().
operator=() [3/4]
template<typename ArgT> MatchAllOf & Catch::Matchers::Detail::MatchAllOf< ArgT >::operator= (MatchAllOf< ArgT > const &) delete
References MatchAllOf().
operator=() [4/4]
template<typename ArgT> MatchAllOf & Catch::Matchers::Detail::MatchAllOf< ArgT >::operator= (MatchAllOf< ArgT > const &) delete
References MatchAllOf().
Friends And Related Symbol Documentation
operator&& [1/4]
template<typename ArgT> MatchAllOf operator&& (MatchAllOf< ArgT > && lhs, MatcherBase< ArgT > const & rhs) friend
Definition at line 10758 of file catch_amalgamated.hpp.
References CATCH_MOVE, and MatchAllOf().
operator&& [2/4]
template<typename ArgT> MatchAllOf operator&& (MatchAllOf< ArgT > && lhs, MatcherBase< ArgT > const & rhs) friend
Definition at line 82 of file catch_matchers.hpp.
References CATCH_MOVE, and MatchAllOf().
operator&& [3/4]
template<typename ArgT> MatchAllOf operator&& (MatcherBase< ArgT > const & lhs, MatchAllOf< ArgT > && rhs) friend
Definition at line 10762 of file catch_amalgamated.hpp.
References CATCH_MOVE, and MatchAllOf().
operator&& [4/4]
template<typename ArgT> MatchAllOf operator&& (MatcherBase< ArgT > const & lhs, MatchAllOf< ArgT > && rhs) friend
Definition at line 86 of file catch_matchers.hpp.
References CATCH_MOVE, and MatchAllOf().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/matchers/catch_matchers.hpp