libthe-seed: clara::detail::ParseState Class Reference
clara::detail::ParseState Class Reference
#include <clara.hpp>
Public Member Functions
ParseState (ParseResultType type, TokenStream const &remainingTokens)
auto type () const -> ParseResultType
auto remainingTokens () const -> TokenStream
Detailed Description
Definition at line 629 of file clara.hpp.
Constructor & Destructor Documentation
ParseState()
clara::detail::ParseState::ParseState (ParseResultType type, TokenStream const & remainingTokens) inline
Definition at line 632 of file clara.hpp.
References remainingTokens(), and type().
Member Function Documentation
remainingTokens()
auto clara::detail::ParseState::remainingTokens () const->TokenStream inline
Definition at line 638 of file clara.hpp.
Referenced by ParseState().
type()
auto clara::detail::ParseState::type () const->ParseResultType inline
Definition at line 637 of file clara.hpp.
Referenced by ParseState().
The documentation for this class was generated from the following file:
external/Catch2/third_party/clara.hpp