libthe-seed: clara::TextFlow::Column::iterator Class Reference
clara::TextFlow::Column::iterator Class Reference
#include <clara.hpp>
Public Types
using difference_type = std::ptrdiff_t
using value_type = std::string
using pointer = value_type*
using reference = value_type&
using iterator_category = std::forward_iterator_tag
Public Member Functions
iterator (Column const &column)
auto operator* () const -> std::string
auto operator++ () -> iterator &
auto operator++ (int) -> iterator
auto operator== (iterator const &other) const -> bool
auto operator!= (iterator const &other) const -> bool
Detailed Description
Definition at line 79 of file clara.hpp.
Member Typedef Documentation
difference_type
using clara::TextFlow::Column::iterator::difference_type = std::ptrdiff_t
Definition at line 148 of file clara.hpp.
iterator_category
using clara::TextFlow::Column::iterator::iterator_category = std::forward_iterator_tag
Definition at line 152 of file clara.hpp.
pointer
using clara::TextFlow::Column::iterator::pointer = value_type*
Definition at line 150 of file clara.hpp.
reference
using clara::TextFlow::Column::iterator::reference = value_type&
Definition at line 151 of file clara.hpp.
value_type
using clara::TextFlow::Column::iterator::value_type = std::string
Definition at line 149 of file clara.hpp.
Constructor & Destructor Documentation
iterator()
clara::TextFlow::Column::iterator::iterator (Column const & column) inline explicit
Definition at line 154 of file clara.hpp.
Member Function Documentation
operator!=()
auto clara::TextFlow::Column::iterator::operator!= (iterator const & other) const->bool inline
Definition at line 196 of file clara.hpp.
References operator==().
operator*()
auto clara::TextFlow::Column::iterator::operator* () const->std::string inline
Definition at line 162 of file clara.hpp.
operator++() [1/2]
auto clara::TextFlow::Column::iterator::operator++ () ->iterator & inline
Definition at line 168 of file clara.hpp.
References clara::TextFlow::isWhitespace().
Referenced by operator++().
operator++() [2/2]
auto clara::TextFlow::Column::iterator::operator++ (int) ->iterator inline
Definition at line 184 of file clara.hpp.
References operator++().
operator==()
auto clara::TextFlow::Column::iterator::operator== (iterator const & other) const->bool inline
Definition at line 190 of file clara.hpp.
Referenced by operator!=().
The documentation for this class was generated from the following file:
external/Catch2/third_party/clara.hpp