libthe-seed: Catch::ColourImpl::ColourGuard Class Reference
Catch::ColourImpl::ColourGuard Class Reference
RAII wrapper around writing specific colour of text using specific colour impl into a stream.
#include <catch_amalgamated.hpp>
Public Member Functions
ColourGuard (Colour::Code code, ColourImpl const *colour)
Does not engage the guard/start the colour.
ColourGuard (ColourGuard const &rhs)=delete
ColourGuard & operator= (ColourGuard const &rhs)=delete
ColourGuard (ColourGuard &&rhs) noexcept
ColourGuard & operator= (ColourGuard &&rhs) noexcept
~ColourGuard ()
Removes colour if the guard was engaged.
ColourGuard & engage (std::ostream &stream) &
ColourGuard && engage (std::ostream &stream) &&
ColourGuard (Colour::Code code, ColourImpl const *colour)
Does not engage the guard/start the colour.
ColourGuard (ColourGuard const &rhs)=delete
ColourGuard & operator= (ColourGuard const &rhs)=delete
ColourGuard (ColourGuard &&rhs) noexcept
ColourGuard & operator= (ColourGuard &&rhs) noexcept
~ColourGuard ()
Removes colour if the guard was engaged.
ColourGuard & engage (std::ostream &stream) &
ColourGuard && engage (std::ostream &stream) &&
Friends
std::ostream & operator<< (std::ostream &lhs, ColourGuard &guard)
Engages the guard and starts using colour.
std::ostream & operator<< (std::ostream &lhs, ColourGuard &&guard)
Engages the guard and starts using colour.
std::ostream & operator<< (std::ostream &lhs, ColourGuard &guard)
Engages the guard and starts using colour.
std::ostream & operator<< (std::ostream &lhs, ColourGuard &&guard)
Engages the guard and starts using colour.
Detailed Description
RAII wrapper around writing specific colour of text using specific colour impl into a stream.
Definition at line 3868 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ColourGuard() [1/6]
Catch::ColourImpl::ColourGuard::ColourGuard (Colour::Code code, ColourImpl const * colour)
Does not engage the guard/start the colour.
Definition at line 3215 of file catch_amalgamated.cpp.
References Catch::ColourImpl::ColourImpl().
Referenced by ColourGuard(), ColourGuard(), engage(), engage(), operator<<, operator<<, operator=(), and operator=().
ColourGuard() [2/6]
Catch::ColourImpl::ColourGuard::ColourGuard (ColourGuard const & rhs) delete
References ColourGuard().
ColourGuard() [3/6]
Catch::ColourImpl::ColourGuard::ColourGuard (ColourGuard && rhs) noexcept
Definition at line 3219 of file catch_amalgamated.cpp.
References ColourGuard().
~ColourGuard() [1/2]
Catch::ColourImpl::ColourGuard::~ColourGuard ()
Removes colour if the guard was engaged.
Definition at line 3234 of file catch_amalgamated.cpp.
References Catch::Colour::None.
ColourGuard() [4/6]
Catch::ColourImpl::ColourGuard::ColourGuard (Colour::Code code, ColourImpl const * colour)
Does not engage the guard/start the colour.
References Catch::ColourImpl::ColourImpl().
ColourGuard() [5/6]
Catch::ColourImpl::ColourGuard::ColourGuard (ColourGuard const & rhs) delete
References ColourGuard().
ColourGuard() [6/6]
Catch::ColourImpl::ColourGuard::ColourGuard (ColourGuard && rhs) noexcept
References ColourGuard().
~ColourGuard() [2/2]
Catch::ColourImpl::ColourGuard::~ColourGuard ()
Removes colour if the guard was engaged.
Member Function Documentation
engage() [1/4]
ColourImpl::ColourGuard & Catch::ColourImpl::ColourGuard::engage (std::ostream & stream) &
Explicitly engages colour for given stream.
The API based on operator<< should be preferred.
Definition at line 3241 of file catch_amalgamated.cpp.
Referenced by Catch::defaultListTests(), and operator=().
engage() [2/4]
ColourGuard & Catch::ColourImpl::ColourGuard::engage (std::ostream & stream) &
Explicitly engages colour for given stream.
The API based on operator<< should be preferred.
References ColourGuard().
engage() [3/4]
ColourImpl::ColourGuard && Catch::ColourImpl::ColourGuard::engage (std::ostream & stream) &&
Explicitly engages colour for given stream.
The API based on operator<< should be preferred.
Definition at line 3247 of file catch_amalgamated.cpp.
References CATCH_MOVE.
engage() [4/4]
ColourGuard && Catch::ColourImpl::ColourGuard::engage (std::ostream & stream) &&
Explicitly engages colour for given stream.
The API based on operator<< should be preferred.
References ColourGuard().
operator=() [1/4]
ColourImpl::ColourGuard & Catch::ColourImpl::ColourGuard::operator= (ColourGuard && rhs) noexcept
Definition at line 3226 of file catch_amalgamated.cpp.
References ColourGuard().
operator=() [2/4]
ColourGuard & Catch::ColourImpl::ColourGuard::operator= (ColourGuard && rhs) noexcept
References ColourGuard().
operator=() [3/4]
ColourGuard & Catch::ColourImpl::ColourGuard::operator= (ColourGuard const & rhs) delete
References ColourGuard(), engage(), and operator=().
Referenced by operator=().
operator=() [4/4]
ColourGuard & Catch::ColourImpl::ColourGuard::operator= (ColourGuard const & rhs) delete
References ColourGuard().
Friends And Related Symbol Documentation
operator<< [1/4]
std::ostream & operator<< (std::ostream & lhs, ColourGuard && guard) friend
Engages the guard and starts using colour.
Definition at line 3908 of file catch_amalgamated.hpp.
References ColourGuard().
operator<< [2/4]
std::ostream & operator<< (std::ostream & lhs, ColourGuard && guard) friend
Engages the guard and starts using colour.
Definition at line 109 of file catch_console_colour.hpp.
References ColourGuard().
operator<< [3/4]
std::ostream & operator<< (std::ostream & lhs, ColourGuard & guard) friend
Engages the guard and starts using colour.
Definition at line 3902 of file catch_amalgamated.hpp.
References ColourGuard().
operator<< [4/4]
std::ostream & operator<< (std::ostream & lhs, ColourGuard & guard) friend
Engages the guard and starts using colour.
Definition at line 103 of file catch_console_colour.hpp.
References ColourGuard().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_console_colour.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_console_colour.cpp