libthe-seed: Catch::ScopedMessage Class Reference
Catch::ScopedMessage Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
ScopedMessage (MessageBuilder &&builder)
ScopedMessage (ScopedMessage &duplicate)=delete
ScopedMessage (ScopedMessage &&old) noexcept
~ScopedMessage ()
ScopedMessage (MessageBuilder &&builder)
ScopedMessage (ScopedMessage &duplicate)=delete
ScopedMessage (ScopedMessage &&old) noexcept
~ScopedMessage ()
Public Attributes
MessageInfo m_info
bool m_moved = false
Detailed Description
Definition at line 4260 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ScopedMessage() [1/6]
Catch::ScopedMessage::ScopedMessage (MessageBuilder && builder) explicit
Definition at line 834 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::getResultCapture(), m_info, and Catch::IResultCapture::pushScopedMessage().
Referenced by ScopedMessage(), and ScopedMessage().
ScopedMessage() [2/6]
Catch::ScopedMessage::ScopedMessage (ScopedMessage & duplicate) delete
References ScopedMessage().
ScopedMessage() [3/6]
Catch::ScopedMessage::ScopedMessage (ScopedMessage && old) noexcept
Definition at line 840 of file catch_amalgamated.cpp.
References m_info, and ScopedMessage().
~ScopedMessage() [1/2]
Catch::ScopedMessage::~ScopedMessage ()
Definition at line 845 of file catch_amalgamated.cpp.
References Catch::getResultCapture(), m_info, m_moved, Catch::IResultCapture::popScopedMessage(), and Catch::uncaught_exceptions().
ScopedMessage() [4/6]
Catch::ScopedMessage::ScopedMessage (MessageBuilder && builder) explicit
ScopedMessage() [5/6]
Catch::ScopedMessage::ScopedMessage (ScopedMessage & duplicate) delete
References ScopedMessage().
ScopedMessage() [6/6]
Catch::ScopedMessage::ScopedMessage (ScopedMessage && old) noexcept
References ScopedMessage().
~ScopedMessage() [2/2]
Catch::ScopedMessage::~ScopedMessage ()
References m_info, and m_moved.
Member Data Documentation
m_info
MessageInfo Catch::ScopedMessage::m_info
Definition at line 4267 of file catch_amalgamated.hpp.
Referenced by ScopedMessage(), ScopedMessage(), and ~ScopedMessage().
m_moved
bool Catch::ScopedMessage::m_moved = false
Definition at line 4268 of file catch_amalgamated.hpp.
Referenced by ~ScopedMessage().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/catch_message.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/catch_message.cpp