libthe-seed: Catch::IConfig Class Reference
Catch::IConfig Class Reference abstract
#include <catch_amalgamated.hpp>
Public Member Functions
virtual ~IConfig ()
virtual bool allowThrows () const =0
virtual StringRef name () const =0
virtual bool includeSuccessfulResults () const =0
virtual bool shouldDebugBreak () const =0
virtual bool warnAboutMissingAssertions () const =0
virtual bool warnAboutUnmatchedTestSpecs () const =0
virtual bool zeroTestsCountAsSuccess () const =0
virtual int abortAfter () const =0
virtual bool showInvisibles () const =0
virtual ShowDurations showDurations () const =0
virtual double minDuration () const =0
virtual TestSpec const & testSpec () const =0
virtual bool hasTestFilters () const =0
virtual std::vector< std::string > const & getTestsOrTags () const =0
virtual TestRunOrder runOrder () const =0
virtual uint32_t rngSeed () const =0
virtual unsigned int shardCount () const =0
virtual unsigned int shardIndex () const =0
virtual ColourMode defaultColourMode () const =0
virtual std::vector< std::string > const & getSectionsToRun () const =0
virtual Verbosity verbosity () const =0
virtual bool skipBenchmarks () const =0
virtual bool benchmarkNoAnalysis () const =0
virtual unsigned int benchmarkSamples () const =0
virtual double benchmarkConfidenceInterval () const =0
virtual unsigned int benchmarkResamples () const =0
virtual std::chrono::milliseconds benchmarkWarmupTime () const =0
virtual ~IConfig ()
virtual bool allowThrows () const =0
virtual StringRef name () const =0
virtual bool includeSuccessfulResults () const =0
virtual bool shouldDebugBreak () const =0
virtual bool warnAboutMissingAssertions () const =0
virtual bool warnAboutUnmatchedTestSpecs () const =0
virtual bool zeroTestsCountAsSuccess () const =0
virtual int abortAfter () const =0
virtual bool showInvisibles () const =0
virtual ShowDurations showDurations () const =0
virtual double minDuration () const =0
virtual TestSpec const & testSpec () const =0
virtual bool hasTestFilters () const =0
virtual std::vector< std::string > const & getTestsOrTags () const =0
virtual TestRunOrder runOrder () const =0
virtual uint32_t rngSeed () const =0
virtual unsigned int shardCount () const =0
virtual unsigned int shardIndex () const =0
virtual ColourMode defaultColourMode () const =0
virtual std::vector< std::string > const & getSectionsToRun () const =0
virtual Verbosity verbosity () const =0
virtual bool skipBenchmarks () const =0
virtual bool benchmarkNoAnalysis () const =0
virtual unsigned int benchmarkSamples () const =0
virtual double benchmarkConfidenceInterval () const =0
virtual unsigned int benchmarkResamples () const =0
virtual std::chrono::milliseconds benchmarkWarmupTime () const =0
Additional Inherited Members
Protected Member Functions inherited from Catch::Detail::NonCopyable
NonCopyable () noexcept=default
NonCopyable () noexcept=default
Detailed Description
Definition at line 1139 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
~IConfig() [1/2]
Catch::IConfig::~IConfig () virtual default
~IConfig() [2/2]
virtual Catch::IConfig::~IConfig () virtual
Member Function Documentation
abortAfter() [1/2]
virtual int Catch::IConfig::abortAfter () const pure virtual
Implemented in Catch::Config, and Catch::Config.
abortAfter() [2/2]
virtual int Catch::IConfig::abortAfter () const pure virtual
Implemented in Catch::Config, and Catch::Config.
allowThrows() [1/2]
virtual bool Catch::IConfig::allowThrows () const pure virtual
Implemented in Catch::Config, and Catch::Config.
Referenced by Catch::AssertionHandler::allowThrows(), and Catch::isThrowSafe().
allowThrows() [2/2]
virtual bool Catch::IConfig::allowThrows () const pure virtual
Implemented in Catch::Config, and Catch::Config.
benchmarkConfidenceInterval() [1/2]
virtual double Catch::IConfig::benchmarkConfidenceInterval () const pure virtual
Implemented in Catch::Config, and Catch::Config.
Referenced by Catch::Benchmark::Detail::analyse(), and Catch::Benchmark::Detail::analyse().
benchmarkConfidenceInterval() [2/2]
virtual double Catch::IConfig::benchmarkConfidenceInterval () const pure virtual
Implemented in Catch::Config, and Catch::Config.
benchmarkNoAnalysis() [1/2]
virtual bool Catch::IConfig::benchmarkNoAnalysis () const pure virtual
Implemented in Catch::Config, and Catch::Config.
Referenced by Catch::Benchmark::Detail::analyse(), and Catch::Benchmark::Detail::analyse().
benchmarkNoAnalysis() [2/2]
virtual bool Catch::IConfig::benchmarkNoAnalysis () const pure virtual
Implemented in Catch::Config, and Catch::Config.
benchmarkResamples() [1/2]
virtual unsigned int Catch::IConfig::benchmarkResamples () const pure virtual
Implemented in Catch::Config, and Catch::Config.
Referenced by Catch::Benchmark::Detail::analyse(), and Catch::Benchmark::Detail::analyse().
benchmarkResamples() [2/2]
virtual unsigned int Catch::IConfig::benchmarkResamples () const pure virtual
Implemented in Catch::Config, and Catch::Config.
benchmarkSamples() [1/2]
virtual unsigned int Catch::IConfig::benchmarkSamples () const pure virtual
Implemented in Catch::Config, and Catch::Config.
Referenced by Catch::Benchmark::Benchmark::prepare(), Catch::Benchmark::Benchmark::prepare(), Catch::Benchmark::ExecutionPlan< Duration >::run(), and Catch::Benchmark::ExecutionPlan< Duration >::run().
benchmarkSamples() [2/2]
virtual unsigned int Catch::IConfig::benchmarkSamples () const pure virtual
Implemented in Catch::Config, and Catch::Config.
benchmarkWarmupTime() [1/2]
virtual std::chrono::milliseconds Catch::IConfig::benchmarkWarmupTime () const pure virtual
Implemented in Catch::Config, and Catch::Config.
Referenced by Catch::Benchmark::Benchmark::prepare(), and Catch::Benchmark::Benchmark::prepare().
benchmarkWarmupTime() [2/2]
virtual std::chrono::milliseconds Catch::IConfig::benchmarkWarmupTime () const pure virtual
Implemented in Catch::Config, and Catch::Config.
defaultColourMode() [1/2]
virtual ColourMode Catch::IConfig::defaultColourMode () const pure virtual
Implemented in Catch::Config, and Catch::Config.
defaultColourMode() [2/2]
virtual ColourMode Catch::IConfig::defaultColourMode () const pure virtual
Implemented in Catch::Config, and Catch::Config.
getSectionsToRun() [1/2]
virtual std::vector< std::string > const & Catch::IConfig::getSectionsToRun () const pure virtual
Implemented in Catch::Config, and Catch::Config.
getSectionsToRun() [2/2]
virtual std::vector< std::string > const & Catch::IConfig::getSectionsToRun () const pure virtual
Implemented in Catch::Config, and Catch::Config.
getTestsOrTags() [1/2]
virtual std::vector< std::string > const & Catch::IConfig::getTestsOrTags () const pure virtual
Implemented in Catch::Config, and Catch::Config.
getTestsOrTags() [2/2]
virtual std::vector< std::string > const & Catch::IConfig::getTestsOrTags () const pure virtual
Implemented in Catch::Config, and Catch::Config.
hasTestFilters() [1/2]
virtual bool Catch::IConfig::hasTestFilters () const pure virtual
Implemented in Catch::Config, and Catch::Config.
hasTestFilters() [2/2]
virtual bool Catch::IConfig::hasTestFilters () const pure virtual
Implemented in Catch::Config, and Catch::Config.
includeSuccessfulResults() [1/2]
virtual bool Catch::IConfig::includeSuccessfulResults () const pure virtual
Implemented in Catch::Config, and Catch::Config.
includeSuccessfulResults() [2/2]
virtual bool Catch::IConfig::includeSuccessfulResults () const pure virtual
Implemented in Catch::Config, and Catch::Config.
minDuration() [1/2]
virtual double Catch::IConfig::minDuration () const pure virtual
Implemented in Catch::Config, and Catch::Config.
Referenced by Catch::shouldShowDuration().
minDuration() [2/2]
virtual double Catch::IConfig::minDuration () const pure virtual
Implemented in Catch::Config, and Catch::Config.
name() [1/2]
virtual StringRef Catch::IConfig::name () const pure virtual
Implemented in Catch::Config, and Catch::Config.
name() [2/2]
virtual StringRef Catch::IConfig::name () const pure virtual
Implemented in Catch::Config, and Catch::Config.
rngSeed() [1/2]
virtual uint32_t Catch::IConfig::rngSeed () const pure virtual
Implemented in Catch::Config, and Catch::Config.
Referenced by Catch::getSeed(), Catch::rngSeed(), Catch::seedRng(), and Catch::sortTests().
rngSeed() [2/2]
virtual uint32_t Catch::IConfig::rngSeed () const pure virtual
Implemented in Catch::Config, and Catch::Config.
runOrder() [1/2]
virtual TestRunOrder Catch::IConfig::runOrder () const pure virtual
Implemented in Catch::Config, and Catch::Config.
Referenced by Catch::TestRegistry::getAllTestsSorted(), and Catch::sortTests().
runOrder() [2/2]
virtual TestRunOrder Catch::IConfig::runOrder () const pure virtual
Implemented in Catch::Config, and Catch::Config.
shardCount() [1/2]
virtual unsigned int Catch::IConfig::shardCount () const pure virtual
Implemented in Catch::Config, and Catch::Config.
Referenced by Catch::filterTests().
shardCount() [2/2]
virtual unsigned int Catch::IConfig::shardCount () const pure virtual
Implemented in Catch::Config, and Catch::Config.
shardIndex() [1/2]
virtual unsigned int Catch::IConfig::shardIndex () const pure virtual
Implemented in Catch::Config, and Catch::Config.
Referenced by Catch::filterTests().
shardIndex() [2/2]
virtual unsigned int Catch::IConfig::shardIndex () const pure virtual
Implemented in Catch::Config, and Catch::Config.
shouldDebugBreak() [1/2]
virtual bool Catch::IConfig::shouldDebugBreak () const pure virtual
Implemented in Catch::Config, and Catch::Config.
shouldDebugBreak() [2/2]
virtual bool Catch::IConfig::shouldDebugBreak () const pure virtual
Implemented in Catch::Config, and Catch::Config.
showDurations() [1/2]
virtual ShowDurations Catch::IConfig::showDurations () const pure virtual
Implemented in Catch::Config, and Catch::Config.
Referenced by Catch::shouldShowDuration().
showDurations() [2/2]
virtual ShowDurations Catch::IConfig::showDurations () const pure virtual
Implemented in Catch::Config, and Catch::Config.
showInvisibles() [1/2]
virtual bool Catch::IConfig::showInvisibles () const pure virtual
Implemented in Catch::Config, and Catch::Config.
showInvisibles() [2/2]
virtual bool Catch::IConfig::showInvisibles () const pure virtual
Implemented in Catch::Config, and Catch::Config.
skipBenchmarks() [1/2]
virtual bool Catch::IConfig::skipBenchmarks () const pure virtual
Implemented in Catch::Config, and Catch::Config.
skipBenchmarks() [2/2]
virtual bool Catch::IConfig::skipBenchmarks () const pure virtual
Implemented in Catch::Config, and Catch::Config.
testSpec() [1/2]
virtual TestSpec const & Catch::IConfig::testSpec () const pure virtual
Implemented in Catch::Config, and Catch::Config.
testSpec() [2/2]
virtual TestSpec const & Catch::IConfig::testSpec () const pure virtual
Implemented in Catch::Config, and Catch::Config.
verbosity() [1/2]
virtual Verbosity Catch::IConfig::verbosity () const pure virtual
Implemented in Catch::Config, and Catch::Config.
verbosity() [2/2]
virtual Verbosity Catch::IConfig::verbosity () const pure virtual
Implemented in Catch::Config, and Catch::Config.
warnAboutMissingAssertions() [1/2]
virtual bool Catch::IConfig::warnAboutMissingAssertions () const pure virtual
Implemented in Catch::Config, and Catch::Config.
warnAboutMissingAssertions() [2/2]
virtual bool Catch::IConfig::warnAboutMissingAssertions () const pure virtual
Implemented in Catch::Config, and Catch::Config.
warnAboutUnmatchedTestSpecs() [1/2]
virtual bool Catch::IConfig::warnAboutUnmatchedTestSpecs () const pure virtual
Implemented in Catch::Config, and Catch::Config.
warnAboutUnmatchedTestSpecs() [2/2]
virtual bool Catch::IConfig::warnAboutUnmatchedTestSpecs () const pure virtual
Implemented in Catch::Config, and Catch::Config.
zeroTestsCountAsSuccess() [1/2]
virtual bool Catch::IConfig::zeroTestsCountAsSuccess () const pure virtual
Implemented in Catch::Config, and Catch::Config.
zeroTestsCountAsSuccess() [2/2]
virtual bool Catch::IConfig::zeroTestsCountAsSuccess () const pure virtual
Implemented in Catch::Config, and Catch::Config.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/interfaces/catch_interfaces_config.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/interfaces/catch_interfaces_config.cpp