libthe-seed: Catch::JunitReporter Class Reference
Catch::JunitReporter Class Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
JunitReporter (ReporterConfig &&_config)
~JunitReporter () override=default
void testRunStarting (TestRunInfo const &runInfo) override
void testCaseStarting (TestCaseInfo const &testCaseInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void assertionEnded (AssertionStats const &assertionStats) override
Called after assertion was fully evaluated.
void testCaseEnded (TestCaseStats const &testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEndedCumulative () override
Customization point: called after last test finishes (testRunEnded has been handled).
JunitReporter (ReporterConfig &&_config)
~JunitReporter () override=default
void testRunStarting (TestRunInfo const &runInfo) override
void testCaseStarting (TestCaseInfo const &testCaseInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void assertionEnded (AssertionStats const &assertionStats) override
Called after assertion was fully evaluated.
void testCaseEnded (TestCaseStats const &testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEndedCumulative () override
Customization point: called after last test finishes (testRunEnded has been handled).
Public Member Functions inherited from Catch::CumulativeReporterBase
CumulativeReporterBase (ReporterConfig &&_config)
~CumulativeReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &benchmarkStats) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void sectionEnded (SectionStats const &sectionStats) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testRunEnded (TestRunStats const &testRunStats) override
void skipTest (TestCaseInfo const &) override
CumulativeReporterBase (ReporterConfig &&_config)
~CumulativeReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &benchmarkStats) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void sectionEnded (SectionStats const &sectionStats) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testRunEnded (TestRunStats const &testRunStats) override
void skipTest (TestCaseInfo const &) override
Public Member Functions inherited from Catch::ReporterBase
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
Public Member Functions inherited from Catch::IEventListener
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
Static Public Member Functions
static std::string getDescription ()
static std::string getDescription ()
Additional Inherited Members
Public Types inherited from Catch::CumulativeReporterBase
using TestCaseNode = Node<TestCaseStats, SectionNode>
using TestRunNode = Node<TestRunStats, TestCaseNode>
using TestCaseNode = Node<TestCaseStats, SectionNode>
using TestRunNode = Node<TestRunStats, TestCaseNode>
Protected Attributes inherited from Catch::CumulativeReporterBase
bool m_shouldStoreSuccesfulAssertions = true
Should the cumulative base store the assertion expansion for successful assertions?
bool m_shouldStoreFailedAssertions = true
Should the cumulative base store the assertion expansion for failed assertions?
Detail::unique_ptr< TestRunNode > m_testRun
The root node of the test run tree.
Protected Attributes inherited from Catch::ReporterBase
Detail::unique_ptr< IStream > m_wrapped_stream
The stream wrapper as passed to us by outside code.
std::ostream & m_stream
Cached output stream from m_wrapped_stream to reduce number of indirect calls needed to write output.
Detail::unique_ptr< ColourImpl > m_colour
Colour implementation this reporter was configured for.
std::map< std::string, std::string > m_customOptions
The custom reporter options user passed down to the reporter.
Protected Attributes inherited from Catch::IEventListener
ReporterPreferences m_preferences
Derived classes can set up their preferences here.
IConfig const * m_config
The test run's config as filled in from CLI and defaults.
Detailed Description
Definition at line 12706 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
JunitReporter() [1/2]
Catch::JunitReporter::JunitReporter (ReporterConfig && _config)
Definition at line 9485 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::CumulativeReporterBase::CumulativeReporterBase(), Catch::IEventListener::m_preferences, Catch::CumulativeReporterBase::m_shouldStoreSuccesfulAssertions, and Catch::ReporterBase::m_stream.
~JunitReporter() [1/2]
Catch::JunitReporter::~JunitReporter () override default
References assertionEnded(), getDescription(), testCaseEnded(), testCaseStarting(), testRunEndedCumulative(), and testRunStarting().
JunitReporter() [2/2]
Catch::JunitReporter::JunitReporter (ReporterConfig && _config)
~JunitReporter() [2/2]
Catch::JunitReporter::~JunitReporter () override default
Member Function Documentation
assertionEnded() [1/2]
void Catch::JunitReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Reimplemented from Catch::CumulativeReporterBase.
Definition at line 9511 of file catch_amalgamated.cpp.
References Catch::CumulativeReporterBase::assertionEnded(), Catch::AssertionStats::assertionResult, Catch::AssertionResult::getResultType(), and Catch::ResultWas::ThrewException.
Referenced by ~JunitReporter().
assertionEnded() [2/2]
void Catch::JunitReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Reimplemented from Catch::CumulativeReporterBase.
getDescription() [1/2]
std::string Catch::JunitReporter::getDescription () static
Definition at line 9494 of file catch_amalgamated.cpp.
Referenced by ~JunitReporter().
getDescription() [2/2]
std::string Catch::JunitReporter::getDescription () static
testCaseEnded() [1/2]
void Catch::JunitReporter::testCaseEnded (TestCaseStats const & testCaseStats) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Reimplemented from Catch::CumulativeReporterBase.
Definition at line 9517 of file catch_amalgamated.cpp.
References Catch::TestCaseStats::stdErr, Catch::TestCaseStats::stdOut, and Catch::CumulativeReporterBase::testCaseEnded().
Referenced by ~JunitReporter().
testCaseEnded() [2/2]
void Catch::JunitReporter::testCaseEnded (TestCaseStats const & testCaseStats) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Reimplemented from Catch::CumulativeReporterBase.
testCaseStarting() [1/2]
void Catch::JunitReporter::testCaseStarting (TestCaseInfo const & testInfo) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Reimplemented from Catch::CumulativeReporterBase.
Definition at line 9507 of file catch_amalgamated.cpp.
References Catch::TestCaseInfo::okToFail().
Referenced by ~JunitReporter().
testCaseStarting() [2/2]
void Catch::JunitReporter::testCaseStarting (TestCaseInfo const & testInfo) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Reimplemented from Catch::CumulativeReporterBase.
testRunEndedCumulative() [1/2]
void Catch::JunitReporter::testRunEndedCumulative () override virtual
Customization point: called after last test finishes (testRunEnded has been handled).
Implements Catch::CumulativeReporterBase.
Definition at line 9523 of file catch_amalgamated.cpp.
References Catch::CumulativeReporterBase::m_testRun.
Referenced by ~JunitReporter().
testRunEndedCumulative() [2/2]
void Catch::JunitReporter::testRunEndedCumulative () override virtual
Customization point: called after last test finishes (testRunEnded has been handled).
Implements Catch::CumulativeReporterBase.
testRunStarting() [1/2]
void Catch::JunitReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Reimplemented from Catch::CumulativeReporterBase.
Definition at line 9498 of file catch_amalgamated.cpp.
References Catch::CumulativeReporterBase::testRunStarting().
Referenced by ~JunitReporter().
testRunStarting() [2/2]
void Catch::JunitReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Reimplemented from Catch::CumulativeReporterBase.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/reporters/catch_reporter_junit.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/reporters/catch_reporter_junit.cpp