libthe-seed: clara::detail::ResultValueBase< T > Class Template Reference
clara::detail::ResultValueBase< T > Class Template Reference
#include <clara.hpp>
Public Member Functions
auto value () const -> T const &
Protected Member Functions
ResultValueBase (Type type)
ResultValueBase (ResultValueBase const &other)
ResultValueBase (Type, T const &value)
auto operator= (ResultValueBase const &other) -> ResultValueBase &
~ResultValueBase () override
Protected Member Functions inherited from clara::detail::ResultBase
ResultBase (Type type)
virtual ~ResultBase ()=default
virtual void enforceOk () const =0
Protected Attributes
union {
T m_value
};
Protected Attributes inherited from clara::detail::ResultBase
Type m_type
Additional Inherited Members
Public Types inherited from clara::detail::ResultBase
enum Type { Ok , LogicError , RuntimeError }
Detailed Description
template<typename T>
class clara::detail::ResultValueBase< T >
Definition at line 536 of file clara.hpp.
Constructor & Destructor Documentation
ResultValueBase() [1/3]
template<typename T> clara::detail::ResultValueBase< T >::ResultValueBase (Type type) inline protected
Definition at line 544 of file clara.hpp.
References clara::detail::ResultBase::ResultBase().
Referenced by operator=(), and ResultValueBase().
ResultValueBase() [2/3]
template<typename T> clara::detail::ResultValueBase< T >::ResultValueBase (ResultValueBase< T > const & other) inline protected
Definition at line 546 of file clara.hpp.
References clara::detail::ResultBase::m_type, m_value, clara::detail::ResultBase::Ok, clara::detail::ResultBase::ResultBase(), and ResultValueBase().
ResultValueBase() [3/3]
template<typename T> clara::detail::ResultValueBase< T >::ResultValueBase (Type , T const & value) inline protected
Definition at line 551 of file clara.hpp.
References m_value, clara::detail::ResultBase::Ok, clara::detail::ResultBase::ResultBase(), and value().
~ResultValueBase()
template<typename T> clara::detail::ResultValueBase< T >::~ResultValueBase () inline override protected
Definition at line 564 of file clara.hpp.
References clara::detail::ResultBase::m_type, m_value, and clara::detail::ResultBase::Ok.
Member Function Documentation
operator=()
template<typename T> auto clara::detail::ResultValueBase< T >::operator= (ResultValueBase< T > const & other) ->ResultValueBase & inline protected
Definition at line 555 of file clara.hpp.
References clara::detail::ResultBase::m_type, m_value, clara::detail::ResultBase::Ok, and ResultValueBase().
value()
template<typename T> auto clara::detail::ResultValueBase< T >::value () const->Tconst & inline
Definition at line 538 of file clara.hpp.
References clara::detail::ResultBase::enforceOk(), and m_value.
Referenced by ResultValueBase().
Member Data Documentation
[union]
union { ... } clara::detail::ResultValueBase< T >
m_value
template<typename T> T clara::detail::ResultValueBase< T >::m_value
Definition at line 570 of file clara.hpp.
Referenced by operator=(), ResultValueBase(), ResultValueBase(), value(), and ~ResultValueBase().
The documentation for this class was generated from the following file:
external/Catch2/third_party/clara.hpp