libthe-seed: Catch::TestRegistry Class Reference
Catch::TestRegistry Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
~TestRegistry () override=default
void registerTest (Detail::unique_ptr< TestCaseInfo > testInfo, Detail::unique_ptr< ITestInvoker > testInvoker)
std::vector< TestCaseInfo * > const & getAllInfos () const override
std::vector< TestCaseHandle > const & getAllTests () const override
std::vector< TestCaseHandle > const & getAllTestsSorted (IConfig const &config) const override
~TestRegistry () override=default
void registerTest (Detail::unique_ptr< TestCaseInfo > testInfo, Detail::unique_ptr< ITestInvoker > testInvoker)
std::vector< TestCaseInfo * > const & getAllInfos () const override
std::vector< TestCaseHandle > const & getAllTests () const override
std::vector< TestCaseHandle > const & getAllTestsSorted (IConfig const &config) const override
Public Member Functions inherited from Catch::ITestCaseRegistry
virtual ~ITestCaseRegistry ()
virtual ~ITestCaseRegistry ()
Detailed Description
Definition at line 10145 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
~TestRegistry() [1/2]
Catch::TestRegistry::~TestRegistry () override default
References Catch::Declared, getAllInfos(), getAllTests(), getAllTestsSorted(), and registerTest().
~TestRegistry() [2/2]
Catch::TestRegistry::~TestRegistry () override default
Member Function Documentation
getAllInfos() [1/2]
std::vector< TestCaseInfo * > const & Catch::TestRegistry::getAllInfos () const override virtual
Implements Catch::ITestCaseRegistry.
Definition at line 6253 of file catch_amalgamated.cpp.
References getAllInfos().
Referenced by getAllInfos(), and ~TestRegistry().
getAllInfos() [2/2]
std::vector< TestCaseInfo * > const & Catch::TestRegistry::getAllInfos () const override virtual
Implements Catch::ITestCaseRegistry.
getAllTests() [1/2]
std::vector< TestCaseHandle > const & Catch::TestRegistry::getAllTests () const override virtual
Implements Catch::ITestCaseRegistry.
Definition at line 6257 of file catch_amalgamated.cpp.
References getAllTests().
Referenced by getAllTests(), and ~TestRegistry().
getAllTests() [2/2]
std::vector< TestCaseHandle > const & Catch::TestRegistry::getAllTests () const override virtual
Implements Catch::ITestCaseRegistry.
getAllTestsSorted() [1/2]
std::vector< TestCaseHandle > const & Catch::TestRegistry::getAllTestsSorted (IConfig const & config) const override virtual
Implements Catch::ITestCaseRegistry.
Definition at line 6260 of file catch_amalgamated.cpp.
References getAllTestsSorted(), Catch::IConfig::runOrder(), and Catch::sortTests().
Referenced by getAllTestsSorted(), and ~TestRegistry().
getAllTestsSorted() [2/2]
std::vector< TestCaseHandle > const & Catch::TestRegistry::getAllTestsSorted (IConfig const & config) const override virtual
Implements Catch::ITestCaseRegistry.
References Catch::Declared.
registerTest() [1/2]
void Catch::TestRegistry::registerTest (Detail::unique_ptr< TestCaseInfo > testInfo, Detail::unique_ptr< ITestInvoker > testInvoker)
Definition at line 6246 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::Detail::unique_ptr< T >::get(), and registerTest().
Referenced by registerTest(), and ~TestRegistry().
registerTest() [2/2]
void Catch::TestRegistry::registerTest (Detail::unique_ptr< TestCaseInfo > testInfo, Detail::unique_ptr< ITestInvoker > testInvoker)
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_test_case_registry_impl.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_test_case_registry_impl.cpp