libthe-seed: Catch::LazyExpression Class Reference
Catch::LazyExpression Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
LazyExpression (bool isNegated)
LazyExpression (LazyExpression const &other)=default
LazyExpression & operator= (LazyExpression const &)=delete
operator bool () const
LazyExpression (bool isNegated)
LazyExpression (LazyExpression const &other)=default
LazyExpression & operator= (LazyExpression const &)=delete
operator bool () const
Friends
class AssertionHandler
struct AssertionStats
class RunContext
auto operator<< (std::ostream &os, LazyExpression const &lazyExpr) ->std::ostream &
auto operator<< (std::ostream &os, LazyExpression const &lazyExpr) ->std::ostream &
Detailed Description
Definition at line 3439 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
LazyExpression() [1/4]
Catch::LazyExpression::LazyExpression (bool isNegated) inline
Definition at line 3447 of file catch_amalgamated.hpp.
Referenced by LazyExpression(), operator<<, and operator=().
LazyExpression() [2/4]
Catch::LazyExpression::LazyExpression (LazyExpression const & other) default
References LazyExpression().
LazyExpression() [3/4]
Catch::LazyExpression::LazyExpression (bool isNegated) inline
Definition at line 25 of file catch_lazy_expr.hpp.
LazyExpression() [4/4]
Catch::LazyExpression::LazyExpression (LazyExpression const & other) default
References LazyExpression().
Member Function Documentation
operator bool() [1/2]
Catch::LazyExpression::operator bool () const inline explicit
Definition at line 3453 of file catch_amalgamated.hpp.
operator bool() [2/2]
Catch::LazyExpression::operator bool () const inline explicit
Definition at line 31 of file catch_lazy_expr.hpp.
operator=() [1/2]
LazyExpression & Catch::LazyExpression::operator= (LazyExpression const &) delete
References LazyExpression().
operator=() [2/2]
LazyExpression & Catch::LazyExpression::operator= (LazyExpression const &) delete
References LazyExpression().
Friends And Related Symbol Documentation
AssertionHandler
AssertionHandler friend
Definition at line 3440 of file catch_amalgamated.hpp.
References AssertionHandler.
Referenced by AssertionHandler.
AssertionStats
AssertionStats friend
Definition at line 3441 of file catch_amalgamated.hpp.
References AssertionStats.
Referenced by AssertionStats.
operator<< [1/2]
auto operator<< (std::ostream & os, LazyExpression const & lazyExpr)->std::ostream & friend
Definition at line 4273 of file catch_amalgamated.cpp.
References LazyExpression().
operator<< [2/2]
auto operator<< (std::ostream & os, LazyExpression const & lazyExpr)->std::ostream & friend
Definition at line 4273 of file catch_amalgamated.cpp.
RunContext
RunContext friend
Definition at line 3442 of file catch_amalgamated.hpp.
References RunContext.
Referenced by RunContext.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_lazy_expr.hpp