libthe-seed: Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT > Class Template Reference
Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT > Class Template Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
MatchNotOfGeneric (MatchNotOfGeneric const &)=delete
MatchNotOfGeneric & operator= (MatchNotOfGeneric const &)=delete
MatchNotOfGeneric (MatchNotOfGeneric &&)=default
MatchNotOfGeneric & operator= (MatchNotOfGeneric &&)=default
MatchNotOfGeneric (MatcherT const &matcher)
template<typename Arg>
bool match (Arg &&arg) const
std::string describe () const override
MatchNotOfGeneric (MatchNotOfGeneric const &)=delete
MatchNotOfGeneric & operator= (MatchNotOfGeneric const &)=delete
MatchNotOfGeneric (MatchNotOfGeneric &&)=default
MatchNotOfGeneric & operator= (MatchNotOfGeneric &&)=default
MatchNotOfGeneric (MatcherT const &matcher)
template<typename Arg>
bool match (Arg &&arg) const
std::string describe () const override
Public Member Functions inherited from Catch::Matchers::MatcherGenericBase
MatcherGenericBase ()=default
~MatcherGenericBase () override
MatcherGenericBase (MatcherGenericBase const &)=default
MatcherGenericBase (MatcherGenericBase &&)=default
MatcherGenericBase & operator= (MatcherGenericBase const &)=delete
MatcherGenericBase & operator= (MatcherGenericBase &&)=delete
MatcherGenericBase ()=default
~MatcherGenericBase () override
MatcherGenericBase (MatcherGenericBase const &)=default
MatcherGenericBase (MatcherGenericBase &&)=default
MatcherGenericBase & operator= (MatcherGenericBase const &)=delete
MatcherGenericBase & operator= (MatcherGenericBase &&)=delete
Public Member Functions inherited from Catch::Matchers::MatcherUntypedBase
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
Friends
MatcherT const & operator! (MatchNotOfGeneric< MatcherT > const &matcher)
Negating negation can just unwrap and return underlying matcher.
MatcherT const & operator! (MatchNotOfGeneric< MatcherT > const &matcher)
Negating negation can just unwrap and return underlying matcher.
Additional Inherited Members
Protected Member Functions inherited from Catch::Matchers::MatcherUntypedBase
virtual ~MatcherUntypedBase ()
virtual ~MatcherUntypedBase ()
Protected Attributes inherited from Catch::Matchers::MatcherUntypedBase
std::string m_cachedToString
Detailed Description
template<typename MatcherT>
class Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >
Definition at line 11128 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
MatchNotOfGeneric() [1/6]
template<typename MatcherT> Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::MatchNotOfGeneric (MatchNotOfGeneric< MatcherT > const &) delete
References MatchNotOfGeneric().
Referenced by MatchNotOfGeneric(), MatchNotOfGeneric(), operator!, operator=(), and operator=().
MatchNotOfGeneric() [2/6]
template<typename MatcherT> Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::MatchNotOfGeneric (MatchNotOfGeneric< MatcherT > &&) default
References MatchNotOfGeneric().
MatchNotOfGeneric() [3/6]
template<typename MatcherT> Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::MatchNotOfGeneric (MatcherT const & matcher) inline explicit
Definition at line 11137 of file catch_amalgamated.hpp.
MatchNotOfGeneric() [4/6]
template<typename MatcherT> Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::MatchNotOfGeneric (MatchNotOfGeneric< MatcherT > const &) delete
References MatchNotOfGeneric().
MatchNotOfGeneric() [5/6]
template<typename MatcherT> Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::MatchNotOfGeneric (MatchNotOfGeneric< MatcherT > &&) default
References MatchNotOfGeneric().
MatchNotOfGeneric() [6/6]
template<typename MatcherT> Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::MatchNotOfGeneric (MatcherT const & matcher) inline explicit
Definition at line 228 of file catch_matchers_templated.hpp.
Member Function Documentation
describe() [1/2]
template<typename MatcherT> std::string Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 11144 of file catch_amalgamated.hpp.
describe() [2/2]
template<typename MatcherT> std::string Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 235 of file catch_matchers_templated.hpp.
match() [1/2]
template<typename MatcherT> template<typename Arg> bool Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::match (Arg && arg) const inline
Definition at line 11140 of file catch_amalgamated.hpp.
match() [2/2]
template<typename MatcherT> template<typename Arg> bool Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::match (Arg && arg) const inline
Definition at line 231 of file catch_matchers_templated.hpp.
operator=() [1/4]
template<typename MatcherT> MatchNotOfGeneric & Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::operator= (MatchNotOfGeneric< MatcherT > &&) default
References MatchNotOfGeneric().
operator=() [2/4]
template<typename MatcherT> MatchNotOfGeneric & Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::operator= (MatchNotOfGeneric< MatcherT > &&) default
References MatchNotOfGeneric().
operator=() [3/4]
template<typename MatcherT> MatchNotOfGeneric & Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::operator= (MatchNotOfGeneric< MatcherT > const &) delete
References MatchNotOfGeneric().
operator=() [4/4]
template<typename MatcherT> MatchNotOfGeneric & Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >::operator= (MatchNotOfGeneric< MatcherT > const &) delete
References MatchNotOfGeneric().
Friends And Related Symbol Documentation
operator! [1/2]
template<typename MatcherT> MatcherT const & operator! (MatchNotOfGeneric< MatcherT > const & matcher) friend
Negating negation can just unwrap and return underlying matcher.
Definition at line 11149 of file catch_amalgamated.hpp.
References MatchNotOfGeneric().
operator! [2/2]
template<typename MatcherT> MatcherT const & operator! (MatchNotOfGeneric< MatcherT > const & matcher) friend
Negating negation can just unwrap and return underlying matcher.
Definition at line 240 of file catch_matchers_templated.hpp.
References MatchNotOfGeneric().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/matchers/catch_matchers_templated.hpp