libthe-seed: Catch::ReporterSpec Class Reference
Catch::ReporterSpec Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
ReporterSpec (std::string name, Optional< std::string > outputFileName, Optional< ColourMode > colourMode, std::map< std::string, std::string > customOptions)
std::string const & name () const
Optional< std::string > const & outputFile () const
Optional< ColourMode > const & colourMode () const
std::map< std::string, std::string > const & customOptions () const
ReporterSpec (std::string name, Optional< std::string > outputFileName, Optional< ColourMode > colourMode, std::map< std::string, std::string > customOptions)
std::string const & name () const
Optional< std::string > const & outputFile () const
Optional< ColourMode > const & colourMode () const
std::map< std::string, std::string > const & customOptions () const
Friends
bool operator== (ReporterSpec const &lhs, ReporterSpec const &rhs)
bool operator!= (ReporterSpec const &lhs, ReporterSpec const &rhs)
bool operator== (ReporterSpec const &lhs, ReporterSpec const &rhs)
bool operator!= (ReporterSpec const &lhs, ReporterSpec const &rhs)
Detailed Description
Structured reporter spec that a reporter can be created from
Parsing has been validated, but semantics have not. This means e.g. that the colour mode is known to Catch2, but it might not be compiled into the binary, and the output filename might not be openable.
Definition at line 3965 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ReporterSpec() [1/2]
Catch::ReporterSpec::ReporterSpec (std::string name, Optional< std::string > outputFileName, Optional< ColourMode > colourMode, std::map< std::string, std::string > customOptions)
Definition at line 4996 of file catch_amalgamated.cpp.
References CATCH_MOVE, colourMode(), customOptions(), and name().
Referenced by operator!=, and operator==.
ReporterSpec() [2/2]
Catch::ReporterSpec::ReporterSpec (std::string name, Optional< std::string > outputFileName, Optional< ColourMode > colourMode, std::map< std::string, std::string > customOptions)
References colourMode(), customOptions(), and name().
Member Function Documentation
colourMode() [1/2]
Optional< ColourMode > const & Catch::ReporterSpec::colourMode () const inline
Definition at line 3991 of file catch_amalgamated.hpp.
Referenced by ReporterSpec().
colourMode() [2/2]
Optional< ColourMode > const & Catch::ReporterSpec::colourMode () const inline
Definition at line 64 of file catch_reporter_spec_parser.hpp.
customOptions() [1/2]
std::map< std::string, std::string > const & Catch::ReporterSpec::customOptions () const inline
Definition at line 3993 of file catch_amalgamated.hpp.
Referenced by ReporterSpec().
customOptions() [2/2]
std::map< std::string, std::string > const & Catch::ReporterSpec::customOptions () const inline
Definition at line 66 of file catch_reporter_spec_parser.hpp.
name() [1/2]
std::string const & Catch::ReporterSpec::name () const inline
Definition at line 3985 of file catch_amalgamated.hpp.
Referenced by ReporterSpec().
name() [2/2]
std::string const & Catch::ReporterSpec::name () const inline
Definition at line 58 of file catch_reporter_spec_parser.hpp.
outputFile() [1/2]
Optional< std::string > const & Catch::ReporterSpec::outputFile () const inline
Definition at line 3987 of file catch_amalgamated.hpp.
outputFile() [2/2]
Optional< std::string > const & Catch::ReporterSpec::outputFile () const inline
Definition at line 60 of file catch_reporter_spec_parser.hpp.
Friends And Related Symbol Documentation
operator!= [1/2]
bool operator!= (ReporterSpec const & lhs, ReporterSpec const & rhs) friend
Definition at line 3973 of file catch_amalgamated.hpp.
References ReporterSpec().
operator!= [2/2]
bool operator!= (ReporterSpec const & lhs, ReporterSpec const & rhs) friend
Definition at line 46 of file catch_reporter_spec_parser.hpp.
References ReporterSpec().
operator== [1/2]
bool operator== (ReporterSpec const & lhs, ReporterSpec const & rhs) friend
Definition at line 4932 of file catch_amalgamated.cpp.
References ReporterSpec().
operator== [2/2]
bool operator== (ReporterSpec const & lhs, ReporterSpec const & rhs) friend
Definition at line 4932 of file catch_amalgamated.cpp.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_reporter_spec_parser.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_reporter_spec_parser.cpp