libthe-seed: Catch::Matchers::Detail::MatchAnyOf< ArgT > Class Template Reference
Catch::Matchers::Detail::MatchAnyOf< ArgT > Class Template Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
MatchAnyOf ()=default
MatchAnyOf (MatchAnyOf const &)=delete
MatchAnyOf & operator= (MatchAnyOf const &)=delete
MatchAnyOf (MatchAnyOf &&)=default
MatchAnyOf & operator= (MatchAnyOf &&)=default
bool match (ArgT const &arg) const override
std::string describe () const override
MatchAnyOf ()=default
MatchAnyOf (MatchAnyOf const &)=delete
MatchAnyOf & operator= (MatchAnyOf const &)=delete
MatchAnyOf (MatchAnyOf &&)=default
MatchAnyOf & operator= (MatchAnyOf &&)=default
bool match (ArgT const &arg) const override
std::string describe () const override
Public Member Functions inherited from Catch::Matchers::MatcherUntypedBase
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
Friends
MatchAnyOf operator|| (MatchAnyOf &&lhs, MatcherBase< ArgT > const &rhs)
MatchAnyOf operator|| (MatcherBase< ArgT > const &lhs, MatchAnyOf &&rhs)
MatchAnyOf operator|| (MatchAnyOf &&lhs, MatcherBase< ArgT > const &rhs)
MatchAnyOf operator|| (MatcherBase< ArgT > const &lhs, MatchAnyOf &&rhs)
Additional Inherited Members
Protected Member Functions inherited from Catch::Matchers::MatcherUntypedBase
virtual ~MatcherUntypedBase ()
virtual ~MatcherUntypedBase ()
Protected Attributes inherited from Catch::Matchers::MatcherUntypedBase
std::string m_cachedToString
Detailed Description
template<typename ArgT>
class Catch::Matchers::Detail::MatchAnyOf< ArgT >
Definition at line 10778 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
MatchAnyOf() [1/6]
template<typename ArgT> Catch::Matchers::Detail::MatchAnyOf< ArgT >::MatchAnyOf () default
Referenced by MatchAnyOf(), MatchAnyOf(), operator=(), operator=(), operator||, and operator||.
MatchAnyOf() [2/6]
template<typename ArgT> Catch::Matchers::Detail::MatchAnyOf< ArgT >::MatchAnyOf (MatchAnyOf< ArgT > const &) delete
References MatchAnyOf().
MatchAnyOf() [3/6]
template<typename ArgT> Catch::Matchers::Detail::MatchAnyOf< ArgT >::MatchAnyOf (MatchAnyOf< ArgT > &&) default
References MatchAnyOf().
MatchAnyOf() [4/6]
template<typename ArgT> Catch::Matchers::Detail::MatchAnyOf< ArgT >::MatchAnyOf () default
MatchAnyOf() [5/6]
template<typename ArgT> Catch::Matchers::Detail::MatchAnyOf< ArgT >::MatchAnyOf (MatchAnyOf< ArgT > const &) delete
References MatchAnyOf().
MatchAnyOf() [6/6]
template<typename ArgT> Catch::Matchers::Detail::MatchAnyOf< ArgT >::MatchAnyOf (MatchAnyOf< ArgT > &&) default
References MatchAnyOf().
Member Function Documentation
describe() [1/2]
template<typename ArgT> std::string Catch::Matchers::Detail::MatchAnyOf< ArgT >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 10794 of file catch_amalgamated.hpp.
describe() [2/2]
template<typename ArgT> std::string Catch::Matchers::Detail::MatchAnyOf< ArgT >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 118 of file catch_matchers.hpp.
match() [1/2]
template<typename ArgT> bool Catch::Matchers::Detail::MatchAnyOf< ArgT >::match (ArgT const & arg) const inline override virtual
Implements Catch::Matchers::MatcherBase< ArgT >.
Definition at line 10787 of file catch_amalgamated.hpp.
Referenced by TEST_CASE().
match() [2/2]
template<typename ArgT> bool Catch::Matchers::Detail::MatchAnyOf< ArgT >::match (ArgT const & arg) const inline override virtual
Implements Catch::Matchers::MatcherBase< ArgT >.
Definition at line 111 of file catch_matchers.hpp.
operator=() [1/4]
template<typename ArgT> MatchAnyOf & Catch::Matchers::Detail::MatchAnyOf< ArgT >::operator= (MatchAnyOf< ArgT > &&) default
References MatchAnyOf().
operator=() [2/4]
template<typename ArgT> MatchAnyOf & Catch::Matchers::Detail::MatchAnyOf< ArgT >::operator= (MatchAnyOf< ArgT > &&) default
References MatchAnyOf().
operator=() [3/4]
template<typename ArgT> MatchAnyOf & Catch::Matchers::Detail::MatchAnyOf< ArgT >::operator= (MatchAnyOf< ArgT > const &) delete
References MatchAnyOf().
operator=() [4/4]
template<typename ArgT> MatchAnyOf & Catch::Matchers::Detail::MatchAnyOf< ArgT >::operator= (MatchAnyOf< ArgT > const &) delete
References MatchAnyOf().
Friends And Related Symbol Documentation
operator|| [1/4]
template<typename ArgT> MatchAnyOf operator|| (MatchAnyOf< ArgT > && lhs, MatcherBase< ArgT > const & rhs) friend
Definition at line 10810 of file catch_amalgamated.hpp.
References CATCH_MOVE, and MatchAnyOf().
operator|| [2/4]
template<typename ArgT> MatchAnyOf operator|| (MatchAnyOf< ArgT > && lhs, MatcherBase< ArgT > const & rhs) friend
Definition at line 134 of file catch_matchers.hpp.
References CATCH_MOVE, and MatchAnyOf().
operator|| [3/4]
template<typename ArgT> MatchAnyOf operator|| (MatcherBase< ArgT > const & lhs, MatchAnyOf< ArgT > && rhs) friend
Definition at line 10814 of file catch_amalgamated.hpp.
References CATCH_MOVE, and MatchAnyOf().
operator|| [4/4]
template<typename ArgT> MatchAnyOf operator|| (MatcherBase< ArgT > const & lhs, MatchAnyOf< ArgT > && rhs) friend
Definition at line 138 of file catch_matchers.hpp.
References CATCH_MOVE, and MatchAnyOf().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/matchers/catch_matchers.hpp