libthe-seed: Catch::TAPReporter Class Reference
Catch::TAPReporter Class Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
TAPReporter (ReporterConfig &&config)
~TAPReporter () override=default
void testRunStarting (TestRunInfo const &testInfo) override
void noMatchingTestCases (StringRef unmatchedSpec) override
Called when no test cases match provided test spec.
void assertionEnded (AssertionStats const &_assertionStats) override
Called after assertion was fully evaluated.
void testRunEnded (TestRunStats const &_testRunStats) override
TAPReporter (ReporterConfig &&config)
~TAPReporter () override=default
void testRunStarting (TestRunInfo const &testInfo) override
void noMatchingTestCases (StringRef unmatchedSpec) override
Called when no test cases match provided test spec.
void assertionEnded (AssertionStats const &_assertionStats) override
Called after assertion was fully evaluated.
void testRunEnded (TestRunStats const &_testRunStats) override
Public Member Functions inherited from Catch::StreamingReporterBase
StreamingReporterBase (ReporterConfig &&_config)
~StreamingReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void testCaseStarting (TestCaseInfo const &_testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &_sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void sectionEnded (SectionStats const &) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &) override
Called once for each TEST_CASE, no matter how many times it is entered.
void skipTest (TestCaseInfo const &) override
StreamingReporterBase (ReporterConfig &&_config)
~StreamingReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void testCaseStarting (TestCaseInfo const &_testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &_sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void sectionEnded (SectionStats const &) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &) override
Called once for each TEST_CASE, no matter how many times it is entered.
void skipTest (TestCaseInfo const &) override
Public Member Functions inherited from Catch::ReporterBase
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
Public Member Functions inherited from Catch::IEventListener
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
Static Public Member Functions
static std::string getDescription ()
static std::string getDescription ()
Additional Inherited Members
Protected Attributes inherited from Catch::StreamingReporterBase
TestRunInfo currentTestRunInfo { "test run has not started yet"_sr }
TestCaseInfo const * currentTestCaseInfo = nullptr
std::vector< SectionInfo > m_sectionStack
Stack of all active sections in the current test case.
Protected Attributes inherited from Catch::ReporterBase
Detail::unique_ptr< IStream > m_wrapped_stream
The stream wrapper as passed to us by outside code.
std::ostream & m_stream
Cached output stream from m_wrapped_stream to reduce number of indirect calls needed to write output.
Detail::unique_ptr< ColourImpl > m_colour
Colour implementation this reporter was configured for.
std::map< std::string, std::string > m_customOptions
The custom reporter options user passed down to the reporter.
Protected Attributes inherited from Catch::IEventListener
ReporterPreferences m_preferences
Derived classes can set up their preferences here.
IConfig const * m_config
The test run's config as filled in from CLI and defaults.
Detailed Description
Definition at line 12994 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
TAPReporter() [1/2]
Catch::TAPReporter::TAPReporter (ReporterConfig && config) inline
Definition at line 12996 of file catch_amalgamated.hpp.
References CATCH_MOVE, Catch::IEventListener::m_preferences, and Catch::StreamingReporterBase::StreamingReporterBase().
~TAPReporter() [1/2]
Catch::TAPReporter::~TAPReporter () override default
TAPReporter() [2/2]
Catch::TAPReporter::TAPReporter (ReporterConfig && config) inline
Definition at line 18 of file catch_reporter_tap.hpp.
References CATCH_MOVE, Catch::IEventListener::m_preferences, and Catch::StreamingReporterBase::StreamingReporterBase().
~TAPReporter() [2/2]
Catch::TAPReporter::~TAPReporter () override default
Member Function Documentation
assertionEnded() [1/2]
void Catch::TAPReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10285 of file catch_amalgamated.cpp.
References Catch::StreamingReporterBase::currentTestCaseInfo, Catch::ReporterBase::m_colour, and Catch::ReporterBase::m_stream.
assertionEnded() [2/2]
void Catch::TAPReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Reimplemented from Catch::StreamingReporterBase.
getDescription() [1/2]
std::string Catch::TAPReporter::getDescription () inline static
Definition at line 13002 of file catch_amalgamated.hpp.
getDescription() [2/2]
std::string Catch::TAPReporter::getDescription () inline static
Definition at line 24 of file catch_reporter_tap.hpp.
noMatchingTestCases() [1/2]
void Catch::TAPReporter::noMatchingTestCases (StringRef unmatchedSpec) override virtual
Called when no test cases match provided test spec.
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10281 of file catch_amalgamated.cpp.
References Catch::ReporterBase::m_stream.
noMatchingTestCases() [2/2]
void Catch::TAPReporter::noMatchingTestCases (StringRef unmatchedSpec) override virtual
Called when no test cases match provided test spec.
Reimplemented from Catch::StreamingReporterBase.
testRunEnded() [1/2]
void Catch::TAPReporter::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10295 of file catch_amalgamated.cpp.
References Catch::Totals::assertions, Catch::ReporterBase::m_stream, Catch::Totals::testCases, Catch::StreamingReporterBase::testRunEnded(), Catch::Counts::total(), and Catch::TestRunStats::totals.
testRunEnded() [2/2]
void Catch::TAPReporter::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Reimplemented from Catch::StreamingReporterBase.
testRunStarting() [1/2]
void Catch::TAPReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Reimplemented from Catch::StreamingReporterBase.
Definition at line 10274 of file catch_amalgamated.cpp.
References Catch::IEventListener::m_config, and Catch::ReporterBase::m_stream.
testRunStarting() [2/2]
void Catch::TAPReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Reimplemented from Catch::StreamingReporterBase.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/reporters/catch_reporter_tap.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/reporters/catch_reporter_tap.cpp