libthe-seed: Catch::ITransientExpression Class Reference
Catch::ITransientExpression Class Reference abstract
#include <catch_amalgamated.hpp>
Public Member Functions
auto isBinaryExpression () const -> bool
auto getResult () const -> bool
virtual void streamReconstructedExpression (std::ostream &os) const =0
ITransientExpression (bool isBinaryExpression, bool result)
ITransientExpression ()=default
ITransientExpression (ITransientExpression const &)=default
ITransientExpression & operator= (ITransientExpression const &)=default
virtual ~ITransientExpression ()
auto isBinaryExpression () const -> bool
auto getResult () const -> bool
virtual void streamReconstructedExpression (std::ostream &os) const =0
ITransientExpression (bool isBinaryExpression, bool result)
ITransientExpression ()=default
ITransientExpression (ITransientExpression const &)=default
ITransientExpression & operator= (ITransientExpression const &)=default
virtual ~ITransientExpression ()
Friends
std::ostream & operator<< (std::ostream &out, ITransientExpression const &expr)
std::ostream & operator<< (std::ostream &out, ITransientExpression const &expr)
Detailed Description
Definition at line 5400 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ITransientExpression() [1/6]
Catch::ITransientExpression::ITransientExpression (bool isBinaryExpression, bool result) inline
Definition at line 5409 of file catch_amalgamated.hpp.
References isBinaryExpression().
Referenced by Catch::BinaryExpr< LhsT, RhsT >::BinaryExpr(), ITransientExpression(), Catch::MatchExpr< ArgT, MatcherT >::MatchExpr(), operator<<, operator=(), and Catch::UnaryExpr< LhsT >::UnaryExpr().
ITransientExpression() [2/6]
Catch::ITransientExpression::ITransientExpression () default
ITransientExpression() [3/6]
Catch::ITransientExpression::ITransientExpression (ITransientExpression const &) default
References ITransientExpression().
~ITransientExpression() [1/2]
Catch::ITransientExpression::~ITransientExpression () virtual default
ITransientExpression() [4/6]
Catch::ITransientExpression::ITransientExpression (bool isBinaryExpression, bool result) inline
Definition at line 51 of file catch_decomposer.hpp.
References isBinaryExpression().
ITransientExpression() [5/6]
Catch::ITransientExpression::ITransientExpression () default
ITransientExpression() [6/6]
Catch::ITransientExpression::ITransientExpression (ITransientExpression const &) default
References ITransientExpression().
~ITransientExpression() [2/2]
virtual Catch::ITransientExpression::~ITransientExpression () virtual
Member Function Documentation
getResult() [1/2]
auto Catch::ITransientExpression::getResult () const->bool inline
Definition at line 5406 of file catch_amalgamated.hpp.
Referenced by Catch::RunContext::handleExpr().
getResult() [2/2]
auto Catch::ITransientExpression::getResult () const->bool inline
Definition at line 48 of file catch_decomposer.hpp.
isBinaryExpression() [1/2]
auto Catch::ITransientExpression::isBinaryExpression () const->bool inline
Definition at line 5405 of file catch_amalgamated.hpp.
Referenced by ITransientExpression().
isBinaryExpression() [2/2]
auto Catch::ITransientExpression::isBinaryExpression () const->bool inline
Definition at line 47 of file catch_decomposer.hpp.
operator=() [1/2]
ITransientExpression & Catch::ITransientExpression::operator= (ITransientExpression const &) default
References ITransientExpression().
operator=() [2/2]
ITransientExpression & Catch::ITransientExpression::operator= (ITransientExpression const &) default
References ITransientExpression().
streamReconstructedExpression() [1/2]
virtual void Catch::ITransientExpression::streamReconstructedExpression (std::ostream & os) const pure virtual
Implemented in Catch::MatchExpr< ArgT, MatcherT >, and Catch::MatchExpr< ArgT, MatcherT >.
Referenced by operator<<.
streamReconstructedExpression() [2/2]
virtual void Catch::ITransientExpression::streamReconstructedExpression (std::ostream & os) const pure virtual
Implemented in Catch::MatchExpr< ArgT, MatcherT >, and Catch::MatchExpr< ArgT, MatcherT >.
Friends And Related Symbol Documentation
operator<< [1/2]
std::ostream & operator<< (std::ostream & out, ITransientExpression const & expr) friend
Definition at line 5422 of file catch_amalgamated.hpp.
References ITransientExpression(), and streamReconstructedExpression().
operator<< [2/2]
std::ostream & operator<< (std::ostream & out, ITransientExpression const & expr) friend
Definition at line 64 of file catch_decomposer.hpp.
References ITransientExpression().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_decomposer.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_decomposer.cpp