libthe-seed: Catch::XmlWriter::ScopedElement Class Reference
Catch::XmlWriter::ScopedElement Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
ScopedElement (XmlWriter *writer, XmlFormatting fmt)
ScopedElement (ScopedElement &&other) noexcept
ScopedElement & operator= (ScopedElement &&other) noexcept
~ScopedElement ()
ScopedElement & writeText (StringRef text, XmlFormatting fmt=XmlFormatting::Newline|XmlFormatting::Indent)
ScopedElement & writeAttribute (StringRef name, StringRef attribute)
template<typename T, typename = typename std::enable_if_t< !std::is_convertible<T, StringRef>::value>>
ScopedElement & writeAttribute (StringRef name, T const &attribute)
ScopedElement (XmlWriter *writer, XmlFormatting fmt)
ScopedElement (ScopedElement &&other) noexcept
ScopedElement & operator= (ScopedElement &&other) noexcept
~ScopedElement ()
ScopedElement & writeText (StringRef text, XmlFormatting fmt=XmlFormatting::Newline|XmlFormatting::Indent)
ScopedElement & writeAttribute (StringRef name, StringRef attribute)
template<typename T, typename = typename std::enable_if_t< !std::is_convertible<T, StringRef>::value>>
ScopedElement & writeAttribute (StringRef name, T const &attribute)
Detailed Description
Definition at line 10487 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ScopedElement() [1/4]
Catch::XmlWriter::ScopedElement::ScopedElement (XmlWriter * writer, XmlFormatting fmt)
Definition at line 7308 of file catch_amalgamated.cpp.
References Catch::XmlWriter::XmlWriter().
Referenced by operator=(), ScopedElement(), writeAttribute(), writeAttribute(), and ~ScopedElement().
ScopedElement() [2/4]
Catch::XmlWriter::ScopedElement::ScopedElement (ScopedElement && other) noexcept
Definition at line 7313 of file catch_amalgamated.cpp.
References Catch::None, and ScopedElement().
~ScopedElement() [1/2]
Catch::XmlWriter::ScopedElement::~ScopedElement ()
Definition at line 7332 of file catch_amalgamated.cpp.
ScopedElement() [3/4]
Catch::XmlWriter::ScopedElement::ScopedElement (XmlWriter * writer, XmlFormatting fmt)
References Catch::XmlWriter::XmlWriter().
ScopedElement() [4/4]
Catch::XmlWriter::ScopedElement::ScopedElement (ScopedElement && other) noexcept
References ScopedElement().
~ScopedElement() [2/2]
Catch::XmlWriter::ScopedElement::~ScopedElement ()
References ScopedElement().
Member Function Documentation
operator=() [1/2]
XmlWriter::ScopedElement & Catch::XmlWriter::ScopedElement::operator= (ScopedElement && other) noexcept
Definition at line 7320 of file catch_amalgamated.cpp.
References Catch::None, and ScopedElement().
operator=() [2/2]
ScopedElement & Catch::XmlWriter::ScopedElement::operator= (ScopedElement && other) noexcept
References ScopedElement().
writeAttribute() [1/4]
XmlWriter::ScopedElement & Catch::XmlWriter::ScopedElement::writeAttribute (StringRef name, StringRef attribute)
Definition at line 7345 of file catch_amalgamated.cpp.
References writeAttribute().
Referenced by Catch::XmlReporter::sectionEnded(), TEST_CASE(), TEST_CASE(), Catch::XmlReporter::testCaseEnded(), writeAttribute(), writeAttribute(), Catch::SonarQubeReporter::writeSection(), and Catch::SonarQubeReporter::writeTestFile().
writeAttribute() [2/4]
ScopedElement & Catch::XmlWriter::ScopedElement::writeAttribute (StringRef name, StringRef attribute)
References ScopedElement().
writeAttribute() [3/4]
template<typename T, typename = typename std::enable_if_t< !std::is_convertible<T, StringRef>::value>> ScopedElement & Catch::XmlWriter::ScopedElement::writeAttribute (StringRef name, T const & attribute) inline
Definition at line 10510 of file catch_amalgamated.hpp.
References ScopedElement(), and writeAttribute().
writeAttribute() [4/4]
template<typename T, typename = typename std::enable_if_t< !std::is_convertible<T, StringRef>::value>> ScopedElement & Catch::XmlWriter::ScopedElement::writeAttribute (StringRef name, T const & attribute) inline
Definition at line 74 of file catch_xmlwriter.hpp.
References ScopedElement(), and writeAttribute().
writeText() [1/2]
XmlWriter::ScopedElement & Catch::XmlWriter::ScopedElement::writeText (StringRef text, XmlFormatting fmt = XmlFormatting::Newline | XmlFormatting::Indent)
Definition at line 7339 of file catch_amalgamated.cpp.
References writeText().
Referenced by TEST_CASE(), Catch::XmlReporter::testCaseEnded(), and writeText().
writeText() [2/2]
ScopedElement & Catch::XmlWriter::ScopedElement::writeText (StringRef text, XmlFormatting fmt = XmlFormatting::Newline|XmlFormatting::Indent)
References Catch::Indent, and Catch::Newline.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_xmlwriter.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_xmlwriter.cpp