libthe-seed: Catch::Optional< T > Class Template Reference
Catch::Optional< T > Class Template Reference
#include <catch_amalgamated.hpp>
Public Member Functions
Optional ()
~Optional ()
Optional (T const &_value)
Optional (T &&_value)
Optional & operator= (T const &_value)
Optional & operator= (T &&_value)
Optional (Optional const &_other)
Optional (Optional &&_other)
Optional & operator= (Optional const &_other)
Optional & operator= (Optional &&_other)
void reset ()
T & operator* ()
T const & operator* () const
T * operator-> ()
const T * operator-> () const
T valueOr (T const &defaultValue) const
bool some () const
bool none () const
bool operator! () const
operator bool () const
Optional ()
~Optional ()
Optional (T const &_value)
Optional (T &&_value)
Optional & operator= (T const &_value)
Optional & operator= (T &&_value)
Optional (Optional const &_other)
Optional (Optional &&_other)
Optional & operator= (Optional const &_other)
Optional & operator= (Optional &&_other)
void reset ()
T & operator* ()
T const & operator* () const
T * operator-> ()
const T * operator-> () const
T valueOr (T const &defaultValue) const
bool some () const
bool none () const
bool operator! () const
operator bool () const
Friends
bool operator== (Optional const &a, Optional const &b)
bool operator!= (Optional const &a, Optional const &b)
bool operator== (Optional const &a, Optional const &b)
bool operator!= (Optional const &a, Optional const &b)
Detailed Description
template<typename T>
class Catch::Optional< T >
Definition at line 3681 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
Optional() [1/10]
template<typename T> Catch::Optional< T >::Optional () inline
Definition at line 3683 of file catch_amalgamated.hpp.
Referenced by operator!=, operator=(), operator=(), operator=(), operator=(), operator==, Optional(), and Optional().
~Optional() [1/2]
template<typename T> Catch::Optional< T >::~Optional () inline
Definition at line 3684 of file catch_amalgamated.hpp.
References reset().
Optional() [2/10]
template<typename T> Catch::Optional< T >::Optional (T const & _value) inline
Definition at line 3686 of file catch_amalgamated.hpp.
Optional() [3/10]
template<typename T> Catch::Optional< T >::Optional (T && _value) inline
Definition at line 3688 of file catch_amalgamated.hpp.
References CATCH_MOVE.
Optional() [4/10]
template<typename T> Catch::Optional< T >::Optional (Optional< T > const & _other) inline
Definition at line 3702 of file catch_amalgamated.hpp.
References Optional().
Optional() [5/10]
template<typename T> Catch::Optional< T >::Optional (Optional< T > && _other) inline
Definition at line 3704 of file catch_amalgamated.hpp.
References CATCH_MOVE, and Optional().
Optional() [6/10]
template<typename T> Catch::Optional< T >::Optional () inline
Definition at line 21 of file catch_optional.hpp.
~Optional() [2/2]
template<typename T> Catch::Optional< T >::~Optional () inline
Definition at line 22 of file catch_optional.hpp.
References reset().
Optional() [7/10]
template<typename T> Catch::Optional< T >::Optional (T const & _value) inline
Definition at line 24 of file catch_optional.hpp.
Optional() [8/10]
template<typename T> Catch::Optional< T >::Optional (T && _value) inline
Definition at line 26 of file catch_optional.hpp.
References CATCH_MOVE.
Optional() [9/10]
template<typename T> Catch::Optional< T >::Optional (Optional< T > const & _other) inline
Definition at line 40 of file catch_optional.hpp.
References Optional().
Optional() [10/10]
template<typename T> Catch::Optional< T >::Optional (Optional< T > && _other) inline
Definition at line 42 of file catch_optional.hpp.
References CATCH_MOVE, and Optional().
Member Function Documentation
none() [1/2]
template<typename T> bool Catch::Optional< T >::none () const inline
Definition at line 3752 of file catch_amalgamated.hpp.
Referenced by operator==.
none() [2/2]
template<typename T> bool Catch::Optional< T >::none () const inline
Definition at line 90 of file catch_optional.hpp.
operator bool() [1/2]
template<typename T> Catch::Optional< T >::operator bool () const inline explicit
Definition at line 3755 of file catch_amalgamated.hpp.
References some().
operator bool() [2/2]
template<typename T> Catch::Optional< T >::operator bool () const inline explicit
Definition at line 93 of file catch_optional.hpp.
References some().
operator!() [1/2]
template<typename T> bool Catch::Optional< T >::operator! () const inline
Definition at line 3754 of file catch_amalgamated.hpp.
operator!() [2/2]
template<typename T> bool Catch::Optional< T >::operator! () const inline
Definition at line 92 of file catch_optional.hpp.
operator*() [1/4]
template<typename T> T & Catch::Optional< T >::operator* () inline
Definition at line 3730 of file catch_amalgamated.hpp.
operator*() [2/4]
template<typename T> T & Catch::Optional< T >::operator* () inline
Definition at line 68 of file catch_optional.hpp.
operator*() [3/4]
template<typename T> T const & Catch::Optional< T >::operator* () const inline
Definition at line 3734 of file catch_amalgamated.hpp.
operator*() [4/4]
template<typename T> T const & Catch::Optional< T >::operator* () const inline
Definition at line 72 of file catch_optional.hpp.
operator->() [1/4]
template<typename T> T * Catch::Optional< T >::operator-> () inline
Definition at line 3738 of file catch_amalgamated.hpp.
operator->() [2/4]
template<typename T> T * Catch::Optional< T >::operator-> () inline
Definition at line 76 of file catch_optional.hpp.
operator->() [3/4]
template<typename T> const T * Catch::Optional< T >::operator-> () const inline
Definition at line 3742 of file catch_amalgamated.hpp.
operator->() [4/4]
template<typename T> const T * Catch::Optional< T >::operator-> () const inline
Definition at line 80 of file catch_optional.hpp.
operator=() [1/8]
template<typename T> Optional & Catch::Optional< T >::operator= (Optional< T > && _other) inline
Definition at line 3715 of file catch_amalgamated.hpp.
References CATCH_MOVE, Optional(), and reset().
operator=() [2/8]
template<typename T> Optional & Catch::Optional< T >::operator= (Optional< T > && _other) inline
Definition at line 53 of file catch_optional.hpp.
References CATCH_MOVE, Optional(), and reset().
operator=() [3/8]
template<typename T> Optional & Catch::Optional< T >::operator= (Optional< T > const & _other) inline
Definition at line 3708 of file catch_amalgamated.hpp.
References Optional(), and reset().
operator=() [4/8]
template<typename T> Optional & Catch::Optional< T >::operator= (Optional< T > const & _other) inline
Definition at line 46 of file catch_optional.hpp.
References Optional(), and reset().
operator=() [5/8]
template<typename T> Optional & Catch::Optional< T >::operator= (T && _value) inline
Definition at line 3696 of file catch_amalgamated.hpp.
References CATCH_MOVE, Optional(), and reset().
operator=() [6/8]
template<typename T> Optional & Catch::Optional< T >::operator= (T && _value) inline
Definition at line 34 of file catch_optional.hpp.
References CATCH_MOVE, Optional(), and reset().
operator=() [7/8]
template<typename T> Optional & Catch::Optional< T >::operator= (T const & _value) inline
Definition at line 3691 of file catch_amalgamated.hpp.
References Optional(), and reset().
operator=() [8/8]
template<typename T> Optional & Catch::Optional< T >::operator= (T const & _value) inline
Definition at line 29 of file catch_optional.hpp.
References Optional(), and reset().
reset() [1/2]
template<typename T> void Catch::Optional< T >::reset () inline
Definition at line 3725 of file catch_amalgamated.hpp.
Referenced by operator=(), operator=(), operator=(), operator=(), and ~Optional().
reset() [2/2]
template<typename T> void Catch::Optional< T >::reset () inline
Definition at line 63 of file catch_optional.hpp.
some() [1/2]
template<typename T> bool Catch::Optional< T >::some () const inline
Definition at line 3751 of file catch_amalgamated.hpp.
Referenced by operator bool(), and operator==.
some() [2/2]
template<typename T> bool Catch::Optional< T >::some () const inline
Definition at line 89 of file catch_optional.hpp.
valueOr() [1/2]
template<typename T> T Catch::Optional< T >::valueOr (T const & defaultValue) const inline
Definition at line 3747 of file catch_amalgamated.hpp.
valueOr() [2/2]
template<typename T> T Catch::Optional< T >::valueOr (T const & defaultValue) const inline
Definition at line 85 of file catch_optional.hpp.
Friends And Related Symbol Documentation
operator!= [1/2]
template<typename T> bool operator!= (Optional< T > const & a, Optional< T > const & b) friend
Definition at line 3768 of file catch_amalgamated.hpp.
References Optional().
operator!= [2/2]
template<typename T> bool operator!= (Optional< T > const & a, Optional< T > const & b) friend
Definition at line 106 of file catch_optional.hpp.
References Optional().
operator== [1/2]
template<typename T> bool operator== (Optional< T > const & a, Optional< T > const & b) friend
Definition at line 3759 of file catch_amalgamated.hpp.
References none(), Optional(), and some().
operator== [2/2]
template<typename T> bool operator== (Optional< T > const & a, Optional< T > const & b) friend
Definition at line 97 of file catch_optional.hpp.
References Optional().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_optional.hpp