libthe-seed: Catch::IMutableRegistryHub Class Reference
Catch::IMutableRegistryHub Class Reference abstract
#include <catch_amalgamated.hpp>
Public Member Functions
virtual ~IMutableRegistryHub ()
virtual void registerReporter (std::string const &name, IReporterFactoryPtr factory)=0
virtual void registerListener (Detail::unique_ptr< EventListenerFactory > factory)=0
virtual void registerTest (Detail::unique_ptr< TestCaseInfo > &&testInfo, Detail::unique_ptr< ITestInvoker > &&invoker)=0
virtual void registerTranslator (Detail::unique_ptr< IExceptionTranslator > &&translator)=0
virtual void registerTagAlias (std::string const &alias, std::string const &tag, SourceLineInfo const &lineInfo)=0
virtual void registerStartupException () noexcept=0
virtual IMutableEnumValuesRegistry & getMutableEnumValuesRegistry ()=0
virtual ~IMutableRegistryHub ()
virtual void registerReporter (std::string const &name, IReporterFactoryPtr factory)=0
virtual void registerListener (Detail::unique_ptr< EventListenerFactory > factory)=0
virtual void registerTest (Detail::unique_ptr< TestCaseInfo > &&testInfo, Detail::unique_ptr< ITestInvoker > &&invoker)=0
virtual void registerTranslator (Detail::unique_ptr< IExceptionTranslator > &&translator)=0
virtual void registerTagAlias (std::string const &alias, std::string const &tag, SourceLineInfo const &lineInfo)=0
virtual void registerStartupException () noexcept=0
virtual IMutableEnumValuesRegistry & getMutableEnumValuesRegistry ()=0
Detailed Description
Definition at line 1215 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
~IMutableRegistryHub() [1/2]
Catch::IMutableRegistryHub::~IMutableRegistryHub () virtual default
~IMutableRegistryHub() [2/2]
virtual Catch::IMutableRegistryHub::~IMutableRegistryHub () virtual
Member Function Documentation
getMutableEnumValuesRegistry() [1/2]
virtual IMutableEnumValuesRegistry & Catch::IMutableRegistryHub::getMutableEnumValuesRegistry () pure virtual
References Catch::cleanUp(), getMutableEnumValuesRegistry(), Catch::getMutableRegistryHub(), Catch::getRegistryHub(), and Catch::translateActiveException().
Referenced by getMutableEnumValuesRegistry().
getMutableEnumValuesRegistry() [2/2]
virtual IMutableEnumValuesRegistry & Catch::IMutableRegistryHub::getMutableEnumValuesRegistry () pure virtual
References Catch::cleanUp(), getMutableEnumValuesRegistry(), Catch::getMutableRegistryHub(), Catch::getRegistryHub(), and Catch::translateActiveException().
registerListener() [1/2]
virtual void Catch::IMutableRegistryHub::registerListener (Detail::unique_ptr< EventListenerFactory > factory) pure virtual
Referenced by Catch::Detail::registerListenerImpl().
registerListener() [2/2]
virtual void Catch::IMutableRegistryHub::registerListener (Detail::unique_ptr< EventListenerFactory > factory) pure virtual
registerReporter() [1/2]
virtual void Catch::IMutableRegistryHub::registerReporter (std::string const & name, IReporterFactoryPtr factory) pure virtual
Referenced by Catch::Detail::registerReporterImpl().
registerReporter() [2/2]
virtual void Catch::IMutableRegistryHub::registerReporter (std::string const & name, IReporterFactoryPtr factory) pure virtual
registerStartupException() [1/2]
virtual void Catch::IMutableRegistryHub::registerStartupException () pure virtual noexcept
Referenced by Catch::AutoReg::AutoReg(), Catch::Detail::registerReporterImpl(), Catch::RegistrarForTagAliases::RegistrarForTagAliases(), and Catch::Session::Session().
registerStartupException() [2/2]
virtual void Catch::IMutableRegistryHub::registerStartupException () pure virtual noexcept
registerTagAlias() [1/2]
virtual void Catch::IMutableRegistryHub::registerTagAlias (std::string const & alias, std::string const & tag, SourceLineInfo const & lineInfo) pure virtual
Referenced by Catch::RegistrarForTagAliases::RegistrarForTagAliases().
registerTagAlias() [2/2]
virtual void Catch::IMutableRegistryHub::registerTagAlias (std::string const & alias, std::string const & tag, SourceLineInfo const & lineInfo) pure virtual
registerTest() [1/2]
virtual void Catch::IMutableRegistryHub::registerTest (Detail::unique_ptr< TestCaseInfo > && testInfo, Detail::unique_ptr< ITestInvoker > && invoker) pure virtual
Referenced by Catch::AutoReg::AutoReg().
registerTest() [2/2]
virtual void Catch::IMutableRegistryHub::registerTest (Detail::unique_ptr< TestCaseInfo > && testInfo, Detail::unique_ptr< ITestInvoker > && invoker) pure virtual
registerTranslator() [1/2]
virtual void Catch::IMutableRegistryHub::registerTranslator (Detail::unique_ptr< IExceptionTranslator > && translator) pure virtual
Referenced by Catch::Detail::registerTranslatorImpl().
registerTranslator() [2/2]
virtual void Catch::IMutableRegistryHub::registerTranslator (Detail::unique_ptr< IExceptionTranslator > && translator) pure virtual
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/interfaces/catch_interfaces_registry_hub.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/interfaces/catch_interfaces_registry_hub.cpp