libthe-seed: Catch::Generators::GeneratorUntypedBase Class Reference
Catch::Generators::GeneratorUntypedBase Class Reference abstract
#include <catch_amalgamated.hpp>
Public Member Functions
GeneratorUntypedBase ()=default
GeneratorUntypedBase (GeneratorUntypedBase const &)=default
GeneratorUntypedBase & operator= (GeneratorUntypedBase const &)=default
virtual ~GeneratorUntypedBase ()
bool countedNext ()
std::size_t currentElementIndex () const
StringRef currentElementAsString () const
GeneratorUntypedBase ()=default
GeneratorUntypedBase (GeneratorUntypedBase const &)=default
GeneratorUntypedBase & operator= (GeneratorUntypedBase const &)=default
virtual ~GeneratorUntypedBase ()
bool countedNext ()
std::size_t currentElementIndex () const
StringRef currentElementAsString () const
Detailed Description
Definition at line 7441 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
GeneratorUntypedBase() [1/4]
Catch::Generators::GeneratorUntypedBase::GeneratorUntypedBase () default
Referenced by GeneratorUntypedBase(), and operator=().
GeneratorUntypedBase() [2/4]
Catch::Generators::GeneratorUntypedBase::GeneratorUntypedBase (GeneratorUntypedBase const &) default
References GeneratorUntypedBase().
~GeneratorUntypedBase() [1/2]
Catch::Generators::GeneratorUntypedBase::~GeneratorUntypedBase () virtual default
References countedNext().
GeneratorUntypedBase() [3/4]
Catch::Generators::GeneratorUntypedBase::GeneratorUntypedBase () default
GeneratorUntypedBase() [4/4]
Catch::Generators::GeneratorUntypedBase::GeneratorUntypedBase (GeneratorUntypedBase const &) default
References GeneratorUntypedBase().
~GeneratorUntypedBase() [2/2]
virtual Catch::Generators::GeneratorUntypedBase::~GeneratorUntypedBase () virtual
Member Function Documentation
countedNext() [1/2]
bool Catch::Generators::GeneratorUntypedBase::countedNext ()
Attempts to move the generator to the next element
Serves as a non-virtual interface to next, so that the top level interface can provide sanity checking and shared features.
As with next, returns true iff the move succeeded and the generator has new valid element to provide.
Definition at line 2221 of file catch_amalgamated.cpp.
Referenced by ~GeneratorUntypedBase().
countedNext() [2/2]
bool Catch::Generators::GeneratorUntypedBase::countedNext ()
Attempts to move the generator to the next element
Serves as a non-virtual interface to next, so that the top level interface can provide sanity checking and shared features.
As with next, returns true iff the move succeeded and the generator has new valid element to provide.
currentElementAsString() [1/2]
StringRef Catch::Generators::GeneratorUntypedBase::currentElementAsString () const
Returns generator's current element as user-friendly string.
By default returns string equivalent to calling Catch::Detail::stringify on the current element, but generators can customize their implementation as needed.
Not thread-safe due to internal caching.
The returned ref is valid only until the generator instance is destructed, or it moves onto the next element, whichever comes first.
Definition at line 2230 of file catch_amalgamated.cpp.
currentElementAsString() [2/2]
StringRef Catch::Generators::GeneratorUntypedBase::currentElementAsString () const
Returns generator's current element as user-friendly string.
By default returns string equivalent to calling Catch::Detail::stringify on the current element, but generators can customize their implementation as needed.
Not thread-safe due to internal caching.
The returned ref is valid only until the generator instance is destructed, or it moves onto the next element, whichever comes first.
currentElementIndex() [1/2]
std::size_t Catch::Generators::GeneratorUntypedBase::currentElementIndex () const inline
Definition at line 7481 of file catch_amalgamated.hpp.
currentElementIndex() [2/2]
std::size_t Catch::Generators::GeneratorUntypedBase::currentElementIndex () const inline
Definition at line 59 of file catch_interfaces_generatortracker.hpp.
operator=() [1/2]
GeneratorUntypedBase & Catch::Generators::GeneratorUntypedBase::operator= (GeneratorUntypedBase const &) default
References GeneratorUntypedBase().
operator=() [2/2]
GeneratorUntypedBase & Catch::Generators::GeneratorUntypedBase::operator= (GeneratorUntypedBase const &) default
References GeneratorUntypedBase().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/interfaces/catch_interfaces_generatortracker.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/generators/catch_generators.cpp
external/Catch2/src/catch2/interfaces/catch_interfaces_generatortracker.cpp