libthe-seed: Catch::IRegistryHub Class Reference
Catch::IRegistryHub Class Reference abstract
#include <catch_amalgamated.hpp>
Public Member Functions
virtual ~IRegistryHub ()
virtual ReporterRegistry const & getReporterRegistry () const =0
virtual ITestCaseRegistry const & getTestCaseRegistry () const =0
virtual ITagAliasRegistry const & getTagAliasRegistry () const =0
virtual IExceptionTranslatorRegistry const & getExceptionTranslatorRegistry () const =0
virtual StartupExceptionRegistry const & getStartupExceptionRegistry () const =0
virtual ~IRegistryHub ()
virtual ReporterRegistry const & getReporterRegistry () const =0
virtual ITestCaseRegistry const & getTestCaseRegistry () const =0
virtual ITagAliasRegistry const & getTagAliasRegistry () const =0
virtual IExceptionTranslatorRegistry const & getExceptionTranslatorRegistry () const =0
virtual StartupExceptionRegistry const & getStartupExceptionRegistry () const =0
Detailed Description
Definition at line 1202 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
~IRegistryHub() [1/2]
Catch::IRegistryHub::~IRegistryHub () virtual default
~IRegistryHub() [2/2]
virtual Catch::IRegistryHub::~IRegistryHub () virtual
Member Function Documentation
getExceptionTranslatorRegistry() [1/2]
virtual IExceptionTranslatorRegistry const & Catch::IRegistryHub::getExceptionTranslatorRegistry () const pure virtual
Referenced by Catch::translateActiveException().
getExceptionTranslatorRegistry() [2/2]
virtual IExceptionTranslatorRegistry const & Catch::IRegistryHub::getExceptionTranslatorRegistry () const pure virtual
getReporterRegistry() [1/2]
virtual ReporterRegistry const & Catch::IRegistryHub::getReporterRegistry () const pure virtual
Referenced by Catch::makeCommandLineParser(), and TEST_CASE().
getReporterRegistry() [2/2]
virtual ReporterRegistry const & Catch::IRegistryHub::getReporterRegistry () const pure virtual
getStartupExceptionRegistry() [1/2]
virtual StartupExceptionRegistry const & Catch::IRegistryHub::getStartupExceptionRegistry () const pure virtual
Referenced by Catch::Session::Session().
getStartupExceptionRegistry() [2/2]
virtual StartupExceptionRegistry const & Catch::IRegistryHub::getStartupExceptionRegistry () const pure virtual
getTagAliasRegistry() [1/2]
virtual ITagAliasRegistry const & Catch::IRegistryHub::getTagAliasRegistry () const pure virtual
Referenced by Catch::ITagAliasRegistry::get().
getTagAliasRegistry() [2/2]
virtual ITagAliasRegistry const & Catch::IRegistryHub::getTagAliasRegistry () const pure virtual
getTestCaseRegistry() [1/2]
virtual ITestCaseRegistry const & Catch::IRegistryHub::getTestCaseRegistry () const pure virtual
getTestCaseRegistry() [2/2]
virtual ITestCaseRegistry const & Catch::IRegistryHub::getTestCaseRegistry () const pure virtual
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/interfaces/catch_interfaces_registry_hub.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/interfaces/catch_interfaces_registry_hub.cpp