libthe-seed: Catch::ReporterRegistry Class Reference
Catch::ReporterRegistry Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
ReporterRegistry ()
~ReporterRegistry ()
IEventListenerPtr create (std::string const &name, ReporterConfig &&config) const
void registerReporter (std::string const &name, IReporterFactoryPtr factory)
void registerListener (Detail::unique_ptr< EventListenerFactory > factory)
std::map< std::string, IReporterFactoryPtr, Detail::CaseInsensitiveLess > const & getFactories () const
std::vector< Detail::unique_ptr< EventListenerFactory > > const & getListeners () const
ReporterRegistry ()
~ReporterRegistry ()
IEventListenerPtr create (std::string const &name, ReporterConfig &&config) const
void registerReporter (std::string const &name, IReporterFactoryPtr factory)
void registerListener (Detail::unique_ptr< EventListenerFactory > factory)
std::map< std::string, IReporterFactoryPtr, Detail::CaseInsensitiveLess > const & getFactories () const
std::vector< Detail::unique_ptr< EventListenerFactory > > const & getListeners () const
Detailed Description
Definition at line 9492 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ReporterRegistry() [1/2]
Catch::ReporterRegistry::ReporterRegistry ()
Definition at line 4783 of file catch_amalgamated.cpp.
References Catch::Detail::make_unique().
~ReporterRegistry() [1/2]
Catch::ReporterRegistry::~ReporterRegistry () default
References create(), getFactories(), getListeners(), registerListener(), and registerReporter().
ReporterRegistry() [2/2]
Catch::ReporterRegistry::ReporterRegistry ()
~ReporterRegistry() [2/2]
Catch::ReporterRegistry::~ReporterRegistry ()
Member Function Documentation
create() [1/2]
IEventListenerPtr Catch::ReporterRegistry::create (std::string const & name, ReporterConfig && config) const
Definition at line 4808 of file catch_amalgamated.cpp.
References CATCH_MOVE.
Referenced by ~ReporterRegistry().
create() [2/2]
IEventListenerPtr Catch::ReporterRegistry::create (std::string const & name, ReporterConfig && config) const
getFactories() [1/2]
std::map< std::string, IReporterFactoryPtr, Detail::CaseInsensitiveLess > const & Catch::ReporterRegistry::getFactories () const
Definition at line 4833 of file catch_amalgamated.cpp.
Referenced by Catch::makeCommandLineParser(), TEST_CASE(), and ~ReporterRegistry().
getFactories() [2/2]
std::map< std::string, IReporterFactoryPtr, Detail::CaseInsensitiveLess > const & Catch::ReporterRegistry::getFactories () const
getListeners() [1/2]
std::vector< Detail::unique_ptr< EventListenerFactory > > const & Catch::ReporterRegistry::getListeners () const
Definition at line 4838 of file catch_amalgamated.cpp.
Referenced by ~ReporterRegistry().
getListeners() [2/2]
std::vector< Detail::unique_ptr< EventListenerFactory > > const & Catch::ReporterRegistry::getListeners () const
registerListener() [1/2]
void Catch::ReporterRegistry::registerListener (Detail::unique_ptr< EventListenerFactory > factory)
Definition at line 4825 of file catch_amalgamated.cpp.
References CATCH_MOVE.
Referenced by ~ReporterRegistry().
registerListener() [2/2]
void Catch::ReporterRegistry::registerListener (Detail::unique_ptr< EventListenerFactory > factory)
registerReporter() [1/2]
void Catch::ReporterRegistry::registerReporter (std::string const & name, IReporterFactoryPtr factory)
Definition at line 4815 of file catch_amalgamated.cpp.
References CATCH_ENFORCE, and CATCH_MOVE.
Referenced by TEST_CASE(), TEST_CASE(), and ~ReporterRegistry().
registerReporter() [2/2]
void Catch::ReporterRegistry::registerReporter (std::string const & name, IReporterFactoryPtr factory)
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_reporter_registry.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_reporter_registry.cpp