libthe-seed: Catch::Clara::Detail::ParserRefImpl< DerivedT > Class Template Reference
Catch::Clara::Detail::ParserRefImpl< DerivedT > Class Template Reference
#include <catch_amalgamated.hpp>
Public Member Functions
template<typename LambdaT>
ParserRefImpl (accept_many_t, LambdaT const &ref, std::string const &hint)
template<typename T, typename = typename std::enable_if_t< !Detail::is_unary_function<T>::value>>
ParserRefImpl (T &ref, std::string const &hint)
template<typename LambdaT, typename = typename std::enable_if_t< Detail::is_unary_function<LambdaT>::value>>
ParserRefImpl (LambdaT const &ref, std::string const &hint)
auto operator() (std::string const &description) -> DerivedT &
auto optional () -> DerivedT &
auto required () -> DerivedT &
auto isOptional () const -> bool
auto cardinality () const -> size_t override
std::string const & hint () const
template<typename LambdaT>
ParserRefImpl (accept_many_t, LambdaT const &ref, std::string const &hint)
template<typename T, typename = typename std::enable_if_t< !Detail::is_unary_function<T>::value>>
ParserRefImpl (T &ref, std::string const &hint)
template<typename LambdaT, typename = typename std::enable_if_t< Detail::is_unary_function<LambdaT>::value>>
ParserRefImpl (LambdaT const &ref, std::string const &hint)
auto operator() (std::string const &description) -> DerivedT &
auto optional () -> DerivedT &
auto required () -> DerivedT &
auto isOptional () const -> bool
auto cardinality () const -> size_t override
std::string const & hint () const
Public Member Functions inherited from Catch::Clara::Detail::ComposableParserImpl< DerivedT >
template<typename T>
auto operator| (T const &other) const -> Parser
template<typename T>
auto operator| (T const &other) const -> Parser
template<typename T>
Parser operator| (T const &other) const
Public Member Functions inherited from Catch::Clara::Detail::ParserBase
virtual ~ParserBase ()=default
virtual auto validate () const -> Result
virtual auto parse (std::string const &exeName, TokenStream const &tokens) const -> InternalParseResult=0
virtual size_t cardinality () const
InternalParseResult parse (Args const &args) const
virtual ~ParserBase ()=default
virtual auto validate () const -> Result
virtual auto parse (std::string const &exeName, TokenStream const &tokens) const -> InternalParseResult=0
virtual size_t cardinality () const
InternalParseResult parse (Args const &args) const
Protected Member Functions
ParserRefImpl (std::shared_ptr< BoundRef > const &ref)
ParserRefImpl (std::shared_ptr< BoundRef > const &ref)
Protected Attributes
Optionality m_optionality = Optionality::Optional
std::shared_ptr< BoundRef > m_ref
std::string m_hint
std::string m_description
Detailed Description
template<typename DerivedT>
class Catch::Clara::Detail::ParserRefImpl< DerivedT >
Definition at line 4892 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ParserRefImpl() [1/8]
template<typename DerivedT> Catch::Clara::Detail::ParserRefImpl< DerivedT >::ParserRefImpl (std::shared_ptr< BoundRef > const & ref) inline explicit protected
Definition at line 4899 of file catch_amalgamated.hpp.
References m_ref.
ParserRefImpl() [2/8]
template<typename DerivedT> template<typename LambdaT> Catch::Clara::Detail::ParserRefImpl< DerivedT >::ParserRefImpl (accept_many_t , LambdaT const & ref, std::string const & hint) inline
Definition at line 4904 of file catch_amalgamated.hpp.
References hint(), m_hint, and m_ref.
ParserRefImpl() [3/8]
template<typename DerivedT> template<typename T, typename = typename std::enable_if_t< !Detail::is_unary_function<T>::value>> Catch::Clara::Detail::ParserRefImpl< DerivedT >::ParserRefImpl (T & ref, std::string const & hint) inline
Definition at line 4913 of file catch_amalgamated.hpp.
References hint(), m_hint, and m_ref.
ParserRefImpl() [4/8]
template<typename DerivedT> template<typename LambdaT, typename = typename std::enable_if_t< Detail::is_unary_function<LambdaT>::value>> Catch::Clara::Detail::ParserRefImpl< DerivedT >::ParserRefImpl (LambdaT const & ref, std::string const & hint) inline
Definition at line 4920 of file catch_amalgamated.hpp.
References hint(), m_hint, and m_ref.
ParserRefImpl() [5/8]
template<typename DerivedT> Catch::Clara::Detail::ParserRefImpl< DerivedT >::ParserRefImpl (std::shared_ptr< BoundRef > const & ref) inline explicit protected
Definition at line 471 of file catch_clara.hpp.
References m_ref.
ParserRefImpl() [6/8]
template<typename DerivedT> template<typename LambdaT> Catch::Clara::Detail::ParserRefImpl< DerivedT >::ParserRefImpl (accept_many_t , LambdaT const & ref, std::string const & hint) inline
Definition at line 476 of file catch_clara.hpp.
References hint(), m_hint, and m_ref.
ParserRefImpl() [7/8]
template<typename DerivedT> template<typename T, typename = typename std::enable_if_t< !Detail::is_unary_function<T>::value>> Catch::Clara::Detail::ParserRefImpl< DerivedT >::ParserRefImpl (T & ref, std::string const & hint) inline
Definition at line 485 of file catch_clara.hpp.
References hint(), m_hint, and m_ref.
ParserRefImpl() [8/8]
template<typename DerivedT> template<typename LambdaT, typename = typename std::enable_if_t< Detail::is_unary_function<LambdaT>::value>> Catch::Clara::Detail::ParserRefImpl< DerivedT >::ParserRefImpl (LambdaT const & ref, std::string const & hint) inline
Definition at line 492 of file catch_clara.hpp.
References hint(), m_hint, and m_ref.
Member Function Documentation
cardinality() [1/2]
template<typename DerivedT> auto Catch::Clara::Detail::ParserRefImpl< DerivedT >::cardinality () const->size_t inline override
Definition at line 4943 of file catch_amalgamated.hpp.
References m_ref.
cardinality() [2/2]
template<typename DerivedT> auto Catch::Clara::Detail::ParserRefImpl< DerivedT >::cardinality () const->size_t inline override
Definition at line 515 of file catch_clara.hpp.
References m_ref.
hint() [1/2]
template<typename DerivedT> std::string const & Catch::Clara::Detail::ParserRefImpl< DerivedT >::hint () const inline
Definition at line 4950 of file catch_amalgamated.hpp.
References m_hint.
Referenced by ParserRefImpl(), ParserRefImpl(), and ParserRefImpl().
hint() [2/2]
template<typename DerivedT> std::string const & Catch::Clara::Detail::ParserRefImpl< DerivedT >::hint () const inline
Definition at line 522 of file catch_clara.hpp.
References m_hint.
isOptional() [1/2]
template<typename DerivedT> auto Catch::Clara::Detail::ParserRefImpl< DerivedT >::isOptional () const->bool inline
Definition at line 4939 of file catch_amalgamated.hpp.
References m_optionality, and Catch::Clara::Detail::Optional.
isOptional() [2/2]
template<typename DerivedT> auto Catch::Clara::Detail::ParserRefImpl< DerivedT >::isOptional () const->bool inline
Definition at line 511 of file catch_clara.hpp.
References m_optionality, and Catch::Clara::Detail::Optional.
operator()() [1/2]
template<typename DerivedT> auto Catch::Clara::Detail::ParserRefImpl< DerivedT >::operator() (std::string const & description) ->DerivedT & inline
Definition at line 4924 of file catch_amalgamated.hpp.
References m_description.
operator()() [2/2]
template<typename DerivedT> auto Catch::Clara::Detail::ParserRefImpl< DerivedT >::operator() (std::string const & description) ->DerivedT & inline
Definition at line 496 of file catch_clara.hpp.
References m_description.
optional() [1/2]
template<typename DerivedT> auto Catch::Clara::Detail::ParserRefImpl< DerivedT >::optional () ->DerivedT & inline
Definition at line 4929 of file catch_amalgamated.hpp.
References m_optionality, and Catch::Clara::Detail::Optional.
optional() [2/2]
template<typename DerivedT> auto Catch::Clara::Detail::ParserRefImpl< DerivedT >::optional () ->DerivedT & inline
Definition at line 501 of file catch_clara.hpp.
References m_optionality, and Catch::Clara::Detail::Optional.
required() [1/2]
template<typename DerivedT> auto Catch::Clara::Detail::ParserRefImpl< DerivedT >::required () ->DerivedT & inline
Definition at line 4934 of file catch_amalgamated.hpp.
References m_optionality, and Catch::Clara::Detail::Required.
required() [2/2]
template<typename DerivedT> auto Catch::Clara::Detail::ParserRefImpl< DerivedT >::required () ->DerivedT & inline
Definition at line 506 of file catch_clara.hpp.
References m_optionality, and Catch::Clara::Detail::Required.
Member Data Documentation
m_description
template<typename DerivedT> std::string Catch::Clara::Detail::ParserRefImpl< DerivedT >::m_description protected
Definition at line 4897 of file catch_amalgamated.hpp.
Referenced by operator()().
m_hint
template<typename DerivedT> std::string Catch::Clara::Detail::ParserRefImpl< DerivedT >::m_hint protected
Definition at line 4896 of file catch_amalgamated.hpp.
Referenced by hint(), ParserRefImpl(), ParserRefImpl(), and ParserRefImpl().
m_optionality
template<typename DerivedT> Optionality Catch::Clara::Detail::ParserRefImpl< DerivedT >::m_optionality = Optionality::Optional protected
Definition at line 4894 of file catch_amalgamated.hpp.
Referenced by isOptional(), optional(), and required().
m_ref
template<typename DerivedT> std::shared_ptr< BoundRef > Catch::Clara::Detail::ParserRefImpl< DerivedT >::m_ref protected
Definition at line 4895 of file catch_amalgamated.hpp.
Referenced by cardinality(), ParserRefImpl(), ParserRefImpl(), ParserRefImpl(), and ParserRefImpl().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp