libthe-seed: Catch::Timer Class Reference
Catch::Timer Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
void start ()
auto getElapsedNanoseconds () const -> uint64_t
auto getElapsedMicroseconds () const -> uint64_t
auto getElapsedMilliseconds () const -> unsigned int
auto getElapsedSeconds () const -> double
void start ()
auto getElapsedNanoseconds () const -> uint64_t
auto getElapsedMicroseconds () const -> uint64_t
auto getElapsedMilliseconds () const -> unsigned int
auto getElapsedSeconds () const -> double
Detailed Description
Definition at line 5950 of file catch_amalgamated.hpp.
Member Function Documentation
getElapsedMicroseconds() [1/2]
auto Catch::Timer::getElapsedMicroseconds () const->uint64_t
Definition at line 1775 of file catch_amalgamated.cpp.
References getElapsedNanoseconds().
Referenced by getElapsedMicroseconds(), getElapsedMilliseconds(), and getElapsedSeconds().
getElapsedMicroseconds() [2/2]
auto Catch::Timer::getElapsedMicroseconds () const->uint64_t
References getElapsedMicroseconds().
getElapsedMilliseconds() [1/2]
auto Catch::Timer::getElapsedMilliseconds () const->unsignedint
Definition at line 1778 of file catch_amalgamated.cpp.
References getElapsedMicroseconds().
Referenced by getElapsedMilliseconds().
getElapsedMilliseconds() [2/2]
auto Catch::Timer::getElapsedMilliseconds () const->unsignedint
References getElapsedMilliseconds().
getElapsedNanoseconds() [1/2]
auto Catch::Timer::getElapsedNanoseconds () const->uint64_t
Definition at line 1772 of file catch_amalgamated.cpp.
Referenced by getElapsedMicroseconds().
getElapsedNanoseconds() [2/2]
auto Catch::Timer::getElapsedNanoseconds () const->uint64_t
getElapsedSeconds() [1/2]
auto Catch::Timer::getElapsedSeconds () const->double
Definition at line 1781 of file catch_amalgamated.cpp.
References getElapsedMicroseconds().
Referenced by getElapsedSeconds().
getElapsedSeconds() [2/2]
auto Catch::Timer::getElapsedSeconds () const->double
References getElapsedSeconds().
start() [1/2]
void Catch::Timer::start ()
Definition at line 1769 of file catch_amalgamated.cpp.
start() [2/2]
void Catch::Timer::start ()
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/catch_timer.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/catch_timer.cpp