libthe-seed: Catch::Clara::Detail::ParseState Class Reference
Catch::Clara::Detail::ParseState Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
ParseState (ParseResultType type, TokenStream const &remainingTokens)
ParseResultType type () const
TokenStream const & remainingTokens () const
ParseState (ParseResultType type, TokenStream const &remainingTokens)
ParseResultType type () const
TokenStream const & remainingTokens () const
Detailed Description
Definition at line 4695 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ParseState() [1/2]
Catch::Clara::Detail::ParseState::ParseState (ParseResultType type, TokenStream const & remainingTokens)
Definition at line 2565 of file catch_amalgamated.cpp.
References remainingTokens(), and type().
ParseState() [2/2]
Catch::Clara::Detail::ParseState::ParseState (ParseResultType type, TokenStream const & remainingTokens)
References remainingTokens(), and type().
Member Function Documentation
remainingTokens() [1/2]
TokenStream const & Catch::Clara::Detail::ParseState::remainingTokens () const inline
Definition at line 4701 of file catch_amalgamated.hpp.
Referenced by ParseState().
remainingTokens() [2/2]
TokenStream const & Catch::Clara::Detail::ParseState::remainingTokens () const inline
Definition at line 273 of file catch_clara.hpp.
type() [1/2]
ParseResultType Catch::Clara::Detail::ParseState::type () const inline
Definition at line 4700 of file catch_amalgamated.hpp.
Referenced by ParseState().
type() [2/2]
ParseResultType Catch::Clara::Detail::ParseState::type () const inline
Definition at line 272 of file catch_clara.hpp.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_clara.cpp