libthe-seed: Catch::SonarQubeReporter Class Reference
Catch::SonarQubeReporter Class Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
SonarQubeReporter (ReporterConfig &&config)
~SonarQubeReporter () override=default
void testRunStarting (TestRunInfo const &testRunInfo) override
void testRunEndedCumulative () override
Customization point: called after last test finishes (testRunEnded has been handled).
void writeRun (TestRunNode const &groupNode)
void writeTestFile (StringRef filename, std::vector< TestCaseNode const * > const &testCaseNodes)
void writeTestCase (TestCaseNode const &testCaseNode)
void writeSection (std::string const &rootName, SectionNode const &sectionNode, bool okToFail)
void writeAssertions (SectionNode const &sectionNode, bool okToFail)
void writeAssertion (AssertionStats const &stats, bool okToFail)
SonarQubeReporter (ReporterConfig &&config)
~SonarQubeReporter () override=default
void testRunStarting (TestRunInfo const &testRunInfo) override
void testRunEndedCumulative () override
Customization point: called after last test finishes (testRunEnded has been handled).
void writeRun (TestRunNode const &groupNode)
void writeTestFile (StringRef filename, std::vector< TestCaseNode const * > const &testCaseNodes)
void writeTestCase (TestCaseNode const &testCaseNode)
void writeSection (std::string const &rootName, SectionNode const &sectionNode, bool okToFail)
void writeAssertions (SectionNode const &sectionNode, bool okToFail)
void writeAssertion (AssertionStats const &stats, bool okToFail)
Public Member Functions inherited from Catch::CumulativeReporterBase
CumulativeReporterBase (ReporterConfig &&_config)
~CumulativeReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &benchmarkStats) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void testCaseStarting (TestCaseInfo const &) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &assertionStats) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &sectionStats) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &testRunStats) override
void skipTest (TestCaseInfo const &) override
CumulativeReporterBase (ReporterConfig &&_config)
~CumulativeReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &benchmarkStats) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void testCaseStarting (TestCaseInfo const &) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &assertionStats) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &sectionStats) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &testRunStats) override
void skipTest (TestCaseInfo const &) override
Public Member Functions inherited from Catch::ReporterBase
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
Public Member Functions inherited from Catch::IEventListener
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
Static Public Member Functions
static std::string getDescription ()
static std::string getDescription ()
Additional Inherited Members
Public Types inherited from Catch::CumulativeReporterBase
using TestCaseNode = Node<TestCaseStats, SectionNode>
using TestRunNode = Node<TestRunStats, TestCaseNode>
using TestCaseNode = Node<TestCaseStats, SectionNode>
using TestRunNode = Node<TestRunStats, TestCaseNode>
Protected Attributes inherited from Catch::CumulativeReporterBase
bool m_shouldStoreSuccesfulAssertions = true
Should the cumulative base store the assertion expansion for successful assertions?
bool m_shouldStoreFailedAssertions = true
Should the cumulative base store the assertion expansion for failed assertions?
Detail::unique_ptr< TestRunNode > m_testRun
The root node of the test run tree.
Protected Attributes inherited from Catch::ReporterBase
Detail::unique_ptr< IStream > m_wrapped_stream
The stream wrapper as passed to us by outside code.
std::ostream & m_stream
Cached output stream from m_wrapped_stream to reduce number of indirect calls needed to write output.
Detail::unique_ptr< ColourImpl > m_colour
Colour implementation this reporter was configured for.
std::map< std::string, std::string > m_customOptions
The custom reporter options user passed down to the reporter.
Protected Attributes inherited from Catch::IEventListener
ReporterPreferences m_preferences
Derived classes can set up their preferences here.
IConfig const * m_config
The test run's config as filled in from CLI and defaults.
Detailed Description
Definition at line 12942 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
SonarQubeReporter() [1/2]
Catch::SonarQubeReporter::SonarQubeReporter (ReporterConfig && config) inline
Definition at line 12944 of file catch_amalgamated.hpp.
References CATCH_MOVE, Catch::CumulativeReporterBase::CumulativeReporterBase(), Catch::IEventListener::m_preferences, Catch::CumulativeReporterBase::m_shouldStoreSuccesfulAssertions, and Catch::ReporterBase::m_stream.
~SonarQubeReporter() [1/2]
Catch::SonarQubeReporter::~SonarQubeReporter () override default
SonarQubeReporter() [2/2]
Catch::SonarQubeReporter::SonarQubeReporter (ReporterConfig && config) inline
Definition at line 20 of file catch_reporter_sonarqube.hpp.
References CATCH_MOVE, Catch::CumulativeReporterBase::CumulativeReporterBase(), Catch::IEventListener::m_preferences, Catch::CumulativeReporterBase::m_shouldStoreSuccesfulAssertions, and Catch::ReporterBase::m_stream.
~SonarQubeReporter() [2/2]
Catch::SonarQubeReporter::~SonarQubeReporter () override default
Member Function Documentation
getDescription() [1/2]
std::string Catch::SonarQubeReporter::getDescription () inline static
Definition at line 12954 of file catch_amalgamated.hpp.
getDescription() [2/2]
std::string Catch::SonarQubeReporter::getDescription () inline static
Definition at line 30 of file catch_reporter_sonarqube.hpp.
testRunEndedCumulative() [1/2]
void Catch::SonarQubeReporter::testRunEndedCumulative () inline override virtual
Customization point: called after last test finishes (testRunEnded has been handled).
Implements Catch::CumulativeReporterBase.
Definition at line 12961 of file catch_amalgamated.hpp.
References Catch::CumulativeReporterBase::m_testRun, and writeRun().
testRunEndedCumulative() [2/2]
void Catch::SonarQubeReporter::testRunEndedCumulative () inline override virtual
Customization point: called after last test finishes (testRunEnded has been handled).
Implements Catch::CumulativeReporterBase.
Definition at line 37 of file catch_reporter_sonarqube.hpp.
References Catch::CumulativeReporterBase::m_testRun, and writeRun().
testRunStarting() [1/2]
void Catch::SonarQubeReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Reimplemented from Catch::CumulativeReporterBase.
Definition at line 9946 of file catch_amalgamated.cpp.
References Catch::IEventListener::m_config, and Catch::CumulativeReporterBase::testRunStarting().
testRunStarting() [2/2]
void Catch::SonarQubeReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Reimplemented from Catch::CumulativeReporterBase.
writeAssertion() [1/2]
void Catch::SonarQubeReporter::writeAssertion (AssertionStats const & stats, bool okToFail)
Definition at line 10010 of file catch_amalgamated.cpp.
References Catch::AssertionStats::assertionResult, Catch::ResultWas::DidntThrowException, Catch::ResultWas::Exception, Catch::ResultWas::ExplicitFailure, Catch::ResultWas::ExplicitSkip, Catch::ResultWas::ExpressionFailed, Catch::ResultWas::FailureBit, Catch::ResultWas::FatalErrorCondition, Catch::AssertionResult::getExpandedExpression(), Catch::AssertionResult::getExpression(), Catch::AssertionResult::getExpressionInMacro(), Catch::AssertionResult::getMessage(), Catch::AssertionResult::getResultType(), Catch::AssertionResult::getSourceInfo(), Catch::AssertionResult::getTestMacroName(), Catch::AssertionResult::hasExpandedExpression(), Catch::AssertionResult::hasExpression(), Catch::AssertionResult::hasMessage(), Catch::ResultWas::Info, Catch::AssertionStats::infoMessages, Catch::AssertionResult::isOk(), Catch::Newline, Catch::ResultWas::Ok, Catch::ReusableStringStream::str(), Catch::ResultWas::ThrewException, Catch::ResultWas::Unknown, and Catch::ResultWas::Warning.
Referenced by writeAssertions().
writeAssertion() [2/2]
void Catch::SonarQubeReporter::writeAssertion (AssertionStats const & stats, bool okToFail)
writeAssertions() [1/2]
void Catch::SonarQubeReporter::writeAssertions (SectionNode const & sectionNode, bool okToFail)
Definition at line 10002 of file catch_amalgamated.cpp.
References Catch::CumulativeReporterBase::SectionNode::assertionsAndBenchmarks, and writeAssertion().
Referenced by writeSection().
writeAssertions() [2/2]
void Catch::SonarQubeReporter::writeAssertions (SectionNode const & sectionNode, bool okToFail)
writeRun() [1/2]
void Catch::SonarQubeReporter::writeRun (TestRunNode const & groupNode)
Definition at line 9954 of file catch_amalgamated.cpp.
References Catch::CumulativeReporterBase::Node< T, ChildNodeT >::children, and writeTestFile().
Referenced by testRunEndedCumulative().
writeRun() [2/2]
void Catch::SonarQubeReporter::writeRun (TestRunNode const & groupNode)
writeSection() [1/2]
void Catch::SonarQubeReporter::writeSection (std::string const & rootName, SectionNode const & sectionNode, bool okToFail)
Definition at line 9983 of file catch_amalgamated.cpp.
References Catch::CumulativeReporterBase::SectionNode::childSections, Catch::SectionStats::durationInSeconds, Catch::CumulativeReporterBase::SectionNode::hasAnyAssertions(), Catch::SectionInfo::name, Catch::SectionStats::sectionInfo, Catch::CumulativeReporterBase::SectionNode::stats, Catch::CumulativeReporterBase::SectionNode::stdErr, Catch::CumulativeReporterBase::SectionNode::stdOut, Catch::trim(), writeAssertions(), Catch::XmlWriter::ScopedElement::writeAttribute(), and writeSection().
Referenced by writeSection(), and writeTestCase().
writeSection() [2/2]
void Catch::SonarQubeReporter::writeSection (std::string const & rootName, SectionNode const & sectionNode, bool okToFail)
writeTestCase() [1/2]
void Catch::SonarQubeReporter::writeTestCase (TestCaseNode const & testCaseNode)
Definition at line 9975 of file catch_amalgamated.cpp.
References Catch::CumulativeReporterBase::Node< T, ChildNodeT >::children, Catch::TestCaseInfo::okToFail(), Catch::TestCaseStats::testInfo, Catch::CumulativeReporterBase::Node< T, ChildNodeT >::value, and writeSection().
Referenced by writeTestFile().
writeTestCase() [2/2]
void Catch::SonarQubeReporter::writeTestCase (TestCaseNode const & testCaseNode)
writeTestFile() [1/2]
void Catch::SonarQubeReporter::writeTestFile (StringRef filename, std::vector< TestCaseNode const * > const & testCaseNodes)
Definition at line 9967 of file catch_amalgamated.cpp.
References Catch::XmlWriter::ScopedElement::writeAttribute(), and writeTestCase().
Referenced by writeRun().
writeTestFile() [2/2]
void Catch::SonarQubeReporter::writeTestFile (StringRef filename, std::vector< TestCaseNode const * > const & testCaseNodes)
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/reporters/catch_reporter_sonarqube.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/reporters/catch_reporter_sonarqube.cpp