libthe-seed: Catch::Clara::Detail::ResultBase Class Reference
Catch::Clara::Detail::ResultBase Class Reference abstract
#include <catch_amalgamated.hpp>
Protected Member Functions
ResultBase (ResultType type)
virtual ~ResultBase ()
ResultBase (ResultBase const &)=default
ResultBase & operator= (ResultBase const &)=default
ResultBase (ResultBase &&)=default
ResultBase & operator= (ResultBase &&)=default
virtual void enforceOk () const =0
ResultBase (ResultType type)
virtual ~ResultBase ()
ResultBase (ResultBase const &)=default
ResultBase & operator= (ResultBase const &)=default
ResultBase (ResultBase &&)=default
ResultBase & operator= (ResultBase &&)=default
virtual void enforceOk () const =0
Protected Attributes
ResultType m_type
Detailed Description
Definition at line 4578 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ResultBase() [1/6]
Catch::Clara::Detail::ResultBase::ResultBase (ResultType type) inline protected
Definition at line 4580 of file catch_amalgamated.hpp.
References m_type.
Referenced by operator=(), operator=(), ResultBase(), ResultBase(), Catch::Clara::Detail::ResultValueBase< T >::ResultValueBase(), Catch::Clara::Detail::ResultValueBase< T >::ResultValueBase(), and Catch::Clara::Detail::ResultValueBase< T >::ResultValueBase().
~ResultBase() [1/2]
Catch::Clara::Detail::ResultBase::~ResultBase () protected virtual default
ResultBase() [2/6]
Catch::Clara::Detail::ResultBase::ResultBase (ResultBase const &) protected default
References ResultBase().
ResultBase() [3/6]
Catch::Clara::Detail::ResultBase::ResultBase (ResultBase &&) protected default
References ResultBase().
ResultBase() [4/6]
Catch::Clara::Detail::ResultBase::ResultBase (ResultType type) inline protected
Definition at line 152 of file catch_clara.hpp.
References m_type.
~ResultBase() [2/2]
virtual Catch::Clara::Detail::ResultBase::~ResultBase () protected virtual
ResultBase() [5/6]
Catch::Clara::Detail::ResultBase::ResultBase (ResultBase const &) protected default
References ResultBase().
ResultBase() [6/6]
Catch::Clara::Detail::ResultBase::ResultBase (ResultBase &&) protected default
References ResultBase().
Member Function Documentation
enforceOk() [1/2]
virtual void Catch::Clara::Detail::ResultBase::enforceOk () const protected pure virtual
Implemented in Catch::Clara::Detail::BasicResult< T >, Catch::Clara::Detail::BasicResult< T >, Catch::Clara::Detail::BasicResult< ParseResultType >, Catch::Clara::Detail::BasicResult< ParseResultType >, Catch::Clara::Detail::BasicResult< ParseState >, Catch::Clara::Detail::BasicResult< ParseState >, Catch::Clara::Detail::BasicResult< void >, and Catch::Clara::Detail::BasicResult< void >.
Referenced by Catch::Clara::Detail::ResultValueBase< T >::value().
enforceOk() [2/2]
virtual void Catch::Clara::Detail::ResultBase::enforceOk () const protected pure virtual
Implemented in Catch::Clara::Detail::BasicResult< T >, Catch::Clara::Detail::BasicResult< T >, Catch::Clara::Detail::BasicResult< ParseResultType >, Catch::Clara::Detail::BasicResult< ParseResultType >, Catch::Clara::Detail::BasicResult< ParseState >, Catch::Clara::Detail::BasicResult< ParseState >, Catch::Clara::Detail::BasicResult< void >, and Catch::Clara::Detail::BasicResult< void >.
References m_type.
operator=() [1/4]
ResultBase & Catch::Clara::Detail::ResultBase::operator= (ResultBase &&) protected default
References ResultBase().
operator=() [2/4]
ResultBase & Catch::Clara::Detail::ResultBase::operator= (ResultBase &&) protected default
References ResultBase().
operator=() [3/4]
ResultBase & Catch::Clara::Detail::ResultBase::operator= (ResultBase const &) protected default
References ResultBase().
Referenced by Catch::Clara::Detail::ResultValueBase< T >::operator=().
operator=() [4/4]
ResultBase & Catch::Clara::Detail::ResultBase::operator= (ResultBase const &) protected default
References ResultBase().
Member Data Documentation
m_type
ResultType Catch::Clara::Detail::ResultBase::m_type protected
Definition at line 4591 of file catch_amalgamated.hpp.
Referenced by enforceOk(), Catch::Clara::Detail::ResultValueBase< T >::operator=(), ResultBase(), Catch::Clara::Detail::ResultValueBase< T >::ResultValueBase(), and Catch::Clara::Detail::ResultValueBase< T >::~ResultValueBase().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_clara.cpp