libthe-seed: Catch::Matchers::IsNaNMatcher Class Reference
Catch::Matchers::IsNaNMatcher Class Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
IsNaNMatcher ()=default
bool match (double const &matchee) const override
std::string describe () const override
IsNaNMatcher ()=default
bool match (double const &matchee) const override
std::string describe () const override
Public Member Functions inherited from Catch::Matchers::MatcherUntypedBase
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
Additional Inherited Members
Protected Member Functions inherited from Catch::Matchers::MatcherUntypedBase
virtual ~MatcherUntypedBase ()
virtual ~MatcherUntypedBase ()
Protected Attributes inherited from Catch::Matchers::MatcherUntypedBase
std::string m_cachedToString
Detailed Description
Definition at line 11508 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
IsNaNMatcher() [1/2]
Catch::Matchers::IsNaNMatcher::IsNaNMatcher () default
References describe(), and match().
IsNaNMatcher() [2/2]
Catch::Matchers::IsNaNMatcher::IsNaNMatcher () default
Member Function Documentation
describe() [1/2]
std::string Catch::Matchers::IsNaNMatcher::describe () const override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 7759 of file catch_amalgamated.cpp.
Referenced by IsNaNMatcher().
describe() [2/2]
std::string Catch::Matchers::IsNaNMatcher::describe () const override virtual
Implements Catch::Matchers::MatcherUntypedBase.
match() [1/2]
bool Catch::Matchers::IsNaNMatcher::match (double const & matchee) const override virtual
Implements Catch::Matchers::MatcherBase< double >.
Definition at line 7755 of file catch_amalgamated.cpp.
Referenced by IsNaNMatcher().
match() [2/2]
bool Catch::Matchers::IsNaNMatcher::match (double const & matchee) const override virtual
Implements Catch::Matchers::MatcherBase< double >.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/matchers/catch_matchers_floating_point.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/matchers/catch_matchers_floating_point.cpp