libthe-seed: Catch::Clara::ExeName Class Reference
Catch::Clara::ExeName Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
ExeName ()
ExeName (std::string &ref)
template<typename LambdaT>
ExeName (LambdaT const &lambda)
Detail::InternalParseResult parse (std::string const &, Detail::TokenStream const &tokens) const override
std::string const & name () const
Detail::ParserResult set (std::string const &newName)
ExeName ()
ExeName (std::string &ref)
template<typename LambdaT>
ExeName (LambdaT const &lambda)
Detail::InternalParseResult parse (std::string const &, Detail::TokenStream const &tokens) const override
std::string const & name () const
Detail::ParserResult set (std::string const &newName)
Public Member Functions inherited from Catch::Clara::Detail::ComposableParserImpl< ExeName >
Parser operator| (T const &other) const
Public Member Functions inherited from Catch::Clara::Detail::ParserBase
virtual ~ParserBase ()=default
virtual auto validate () const -> Result
virtual auto parse (std::string const &exeName, TokenStream const &tokens) const -> InternalParseResult=0
virtual size_t cardinality () const
InternalParseResult parse (Args const &args) const
virtual ~ParserBase ()=default
virtual auto validate () const -> Result
virtual auto parse (std::string const &exeName, TokenStream const &tokens) const -> InternalParseResult=0
virtual size_t cardinality () const
InternalParseResult parse (Args const &args) const
Detailed Description
Definition at line 5015 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ExeName() [1/6]
Catch::Clara::ExeName::ExeName ()
Definition at line 2707 of file catch_amalgamated.cpp.
Referenced by ExeName(), and ExeName().
ExeName() [2/6]
Catch::Clara::ExeName::ExeName (std::string & ref) explicit
Definition at line 2710 of file catch_amalgamated.cpp.
References ExeName().
ExeName() [3/6]
template<typename LambdaT> Catch::Clara::ExeName::ExeName (LambdaT const & lambda) inline explicit
Definition at line 5024 of file catch_amalgamated.hpp.
References ExeName().
ExeName() [4/6]
Catch::Clara::ExeName::ExeName ()
ExeName() [5/6]
Catch::Clara::ExeName::ExeName (std::string & ref) explicit
ExeName() [6/6]
template<typename LambdaT> Catch::Clara::ExeName::ExeName (LambdaT const & lambda) inline explicit
Definition at line 596 of file catch_clara.hpp.
References ExeName().
Member Function Documentation
name() [1/2]
std::string const & Catch::Clara::ExeName::name () const inline
Definition at line 5034 of file catch_amalgamated.hpp.
name() [2/2]
std::string const & Catch::Clara::ExeName::name () const inline
Definition at line 606 of file catch_clara.hpp.
parse() [1/2]
Detail::InternalParseResult Catch::Clara::ExeName::parse (std::string const & , Detail::TokenStream const & tokens) const override
Definition at line 2715 of file catch_amalgamated.cpp.
References Catch::Clara::NoMatch, and Catch::Clara::Detail::BasicResult< ParseState >::ok().
parse() [2/2]
Detail::InternalParseResult Catch::Clara::ExeName::parse (std::string const & , Detail::TokenStream const & tokens) const override
set() [1/2]
ParserResult Catch::Clara::ExeName::set (std::string const & newName)
Definition at line 2721 of file catch_amalgamated.cpp.
References Catch::Clara::Matched, and Catch::Clara::Detail::BasicResult< ParseResultType >::ok().
set() [2/2]
Detail::ParserResult Catch::Clara::ExeName::set (std::string const & newName)
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_clara.cpp