libthe-seed: Catch::CompactReporter Class Reference
Catch::CompactReporter Class Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
~CompactReporter () override
void noMatchingTestCases (StringRef unmatchedSpec) override
Called when no test cases match provided test spec.
void testRunStarting (TestRunInfo const &_testInfo) override
void assertionEnded (AssertionStats const &_assertionStats) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &_sectionStats) override
Called after a SECTION has finished running.
void testRunEnded (TestRunStats const &_testRunStats) override
~CompactReporter () override
void noMatchingTestCases (StringRef unmatchedSpec) override
Called when no test cases match provided test spec.
void testRunStarting (TestRunInfo const &_testInfo) override
void assertionEnded (AssertionStats const &_assertionStats) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &_sectionStats) override
Called after a SECTION has finished running.
void testRunEnded (TestRunStats const &_testRunStats) override
StreamingReporterBase (ReporterConfig &&_config)
Public Member Functions inherited from Catch::StreamingReporterBase
StreamingReporterBase (ReporterConfig &&_config)
~StreamingReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void testRunStarting (TestRunInfo const &_testRunInfo) override
void testCaseStarting (TestCaseInfo const &_testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &_sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &) override
void skipTest (TestCaseInfo const &) override
StreamingReporterBase (ReporterConfig &&_config)
~StreamingReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void testRunStarting (TestRunInfo const &_testRunInfo) override
void testCaseStarting (TestCaseInfo const &_testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &_sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &) override
void skipTest (TestCaseInfo const &) override
Public Member Functions inherited from Catch::ReporterBase
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
Public Member Functions inherited from Catch::IEventListener
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
Static Public Member Functions
static std::string getDescription ()
static std::string getDescription ()
Additional Inherited Members
Protected Attributes inherited from Catch::StreamingReporterBase
TestRunInfo currentTestRunInfo { "test run has not started yet"_sr }
TestCaseInfo const * currentTestCaseInfo = nullptr
std::vector< SectionInfo > m_sectionStack
Stack of all active sections in the current test case.
Protected Attributes inherited from Catch::ReporterBase
Detail::unique_ptr< IStream > m_wrapped_stream
The stream wrapper as passed to us by outside code.
std::ostream & m_stream
Cached output stream from m_wrapped_stream to reduce number of indirect calls needed to write output.
Detail::unique_ptr< ColourImpl > m_colour
Colour implementation this reporter was configured for.
std::map< std::string, std::string > m_customOptions
The custom reporter options user passed down to the reporter.
Protected Attributes inherited from Catch::IEventListener
ReporterPreferences m_preferences
Derived classes can set up their preferences here.
IConfig const * m_config
The test run's config as filled in from CLI and defaults.
Detailed Description
Definition at line 12331 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
~CompactReporter() [1/2]
Catch::CompactReporter::~CompactReporter () override default
Definition at line 8260 of file catch_amalgamated.cpp.
~CompactReporter() [2/2]
Catch::CompactReporter::~CompactReporter () override
Member Function Documentation
assertionEnded() [1/2]
void Catch::CompactReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Implements Catch::IEventListener.
Definition at line 8229 of file catch_amalgamated.cpp.
References Catch::AssertionStats::assertionResult, Catch::ResultWas::ExplicitSkip, Catch::AssertionResult::getResultType(), Catch::AssertionResult::isOk(), Catch::ReporterBase::m_colour, Catch::IEventListener::m_config, Catch::ReporterBase::m_stream, and Catch::ResultWas::Warning.
assertionEnded() [2/2]
void Catch::CompactReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Implements Catch::IEventListener.
getDescription() [1/2]
std::string Catch::CompactReporter::getDescription () static
Definition at line 8211 of file catch_amalgamated.cpp.
getDescription() [2/2]
std::string Catch::CompactReporter::getDescription () static
noMatchingTestCases() [1/2]
void Catch::CompactReporter::noMatchingTestCases (StringRef unmatchedSpec) override virtual
Called when no test cases match provided test spec.
Implements Catch::IEventListener.
Definition at line 8215 of file catch_amalgamated.cpp.
References Catch::ReporterBase::m_stream.
noMatchingTestCases() [2/2]
void Catch::CompactReporter::noMatchingTestCases (StringRef unmatchedSpec) override virtual
Called when no test cases match provided test spec.
Implements Catch::IEventListener.
sectionEnded() [1/2]
void Catch::CompactReporter::sectionEnded (SectionStats const & sectionStats) override virtual
Called after a SECTION has finished running.
Implements Catch::IEventListener.
Definition at line 8247 of file catch_amalgamated.cpp.
References Catch::SectionStats::durationInSeconds, Catch::getFormattedDuration(), Catch::IEventListener::m_config, Catch::ReporterBase::m_stream, Catch::SectionInfo::name, Catch::SectionStats::sectionInfo, and Catch::shouldShowDuration().
sectionEnded() [2/2]
void Catch::CompactReporter::sectionEnded (SectionStats const & sectionStats) override virtual
Called after a SECTION has finished running.
Implements Catch::IEventListener.
StreamingReporterBase()
Catch::StreamingReporterBase::StreamingReporterBase (ReporterConfig && _config) inline
Definition at line 12243 of file catch_amalgamated.hpp.
testRunEnded() [1/2]
void Catch::CompactReporter::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Implements Catch::IEventListener.
Definition at line 8254 of file catch_amalgamated.cpp.
References Catch::ReporterBase::m_colour, Catch::ReporterBase::m_stream, Catch::printTestRunTotals(), Catch::StreamingReporterBase::testRunEnded(), and Catch::TestRunStats::totals.
testRunEnded() [2/2]
void Catch::CompactReporter::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Implements Catch::IEventListener.
testRunStarting() [1/2]
void Catch::CompactReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Implements Catch::IEventListener.
Definition at line 8219 of file catch_amalgamated.cpp.
References Catch::Colour::BrightYellow, Catch::getSeed(), Catch::ReporterBase::m_colour, Catch::IEventListener::m_config, and Catch::ReporterBase::m_stream.
testRunStarting() [2/2]
void Catch::CompactReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Implements Catch::IEventListener.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/reporters/catch_reporter_compact.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/reporters/catch_reporter_compact.cpp