libthe-seed: SystemLoader::Loader Class Reference
SystemLoader::Loader Class Reference
#include <SystemLoader.hpp>
Public Member Functions
Loader (std::string library)
~Loader ()
ecs::System * SystemCreate ()
ecs::System * SystemCreate (void *data)
SystemCreator SystemGet ()
Private Attributes
LibraryLoader * library
Detailed Description
Definition at line 11 of file SystemLoader.hpp.
Constructor & Destructor Documentation
Loader()
SystemLoader::Loader::Loader (std::string library)
Definition at line 9 of file SystemLoader.cpp.
     {
         auto name = NameParser(library);
         try
         {
             this->library = new LibraryLoader(name.library);
             this->library->PathAdd("./");
             this->library->PathAdd("../../" + name.library + "/src/.libs/");
             if(name.org.size())
             {
                 auto path = "../node_modules/" + name.org + "/" + name.library + "/src/.libs";
                 this->library->PathAdd(path);
             }
             for(auto path : system_paths) this->library->PathAdd(path);
         }
         catch(std::runtime_error e)
         {
             throw e;
         }
     }
References library, and SystemLoader::system_paths.
~Loader()
SystemLoader::Loader::~Loader ()
Member Function Documentation
SystemCreate() [1/2]
ecs::System * SystemLoader::Loader::SystemCreate ()
Definition at line 39 of file SystemLoader.cpp.
     {
         void *ptr = this->library->FunctionGet("create_system");
         SystemCreator creator = reinterpret_cast<SystemCreator>(ptr);
         ecs::System *s;
         try
         {
             s = creator(nullptr);
         }
         catch(std::runtime_error e)
         {
             throw e;
         }
         return s;
     }
References LibraryLoader::FunctionGet(), and library.
SystemCreate() [2/2]
ecs::System * SystemLoader::Loader::SystemCreate (void * data)
Definition at line 56 of file SystemLoader.cpp.
     {
         void *ptr;
         try
         {
             ptr = this->library->FunctionGet("create_system");
         }
         catch(std::runtime_error e)
         {
             throw e;
         }
         SystemCreator creator = reinterpret_cast<SystemCreator>(ptr);
         ecs::System *s;
         try
         {
             s = creator(data);
         }
         catch(std::runtime_error e)
         {
             throw e;
         }
         return s;
     }
References LibraryLoader::FunctionGet(), and library.
SystemGet()
SystemCreator SystemLoader::Loader::SystemGet ()
Definition at line 32 of file SystemLoader.cpp.
     {
         void *ptr = this->library->FunctionGet("create_system");
         SystemCreator creator = reinterpret_cast<SystemCreator>(ptr);
         return creator;
     }
References LibraryLoader::FunctionGet(), and library.
Member Data Documentation
library
LibraryLoader* SystemLoader::Loader::library private
Definition at line 20 of file SystemLoader.hpp.
Referenced by Loader(), SystemCreate(), and SystemGet().
The documentation for this class was generated from the following files:
include/libthe-seed/SystemLoader.hpp
src/SystemLoader.cpp