libthe-seed: Catch::Clara::Arg Class Reference
Catch::Clara::Arg Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
Detail::InternalParseResult parse (std::string const &, Detail::TokenStream const &tokens) const override
Detail::InternalParseResult parse (std::string const &, Detail::TokenStream const &tokens) const override
Public Member Functions inherited from Catch::Clara::Detail::ParserRefImpl< Arg >
auto operator() (std::string const &description) -> Arg &
auto optional () -> Arg &
auto required () -> Arg &
auto isOptional () const -> bool
auto cardinality () const -> size_t override
std::string const & hint () const
Public Member Functions inherited from Catch::Clara::Detail::ComposableParserImpl< Arg >
Parser operator| (T const &other) const
Public Member Functions inherited from Catch::Clara::Detail::ParserBase
virtual ~ParserBase ()=default
virtual auto validate () const -> Result
virtual auto parse (std::string const &exeName, TokenStream const &tokens) const -> InternalParseResult=0
virtual size_t cardinality () const
InternalParseResult parse (Args const &args) const
virtual ~ParserBase ()=default
virtual auto validate () const -> Result
virtual auto parse (std::string const &exeName, TokenStream const &tokens) const -> InternalParseResult=0
virtual size_t cardinality () const
InternalParseResult parse (Args const &args) const
Additional Inherited Members
Protected Member Functions inherited from Catch::Clara::Detail::ParserRefImpl< Arg >
ParserRefImpl (std::shared_ptr< BoundRef > const &ref)
Protected Attributes inherited from Catch::Clara::Detail::ParserRefImpl< Arg >
Optionality m_optionality
std::shared_ptr< BoundRef > m_ref
std::string m_hint
std::string m_description
Detailed Description
Definition at line 4957 of file catch_amalgamated.hpp.
Member Function Documentation
parse() [1/2]
Detail::InternalParseResult Catch::Clara::Arg::parse (std::string const & , Detail::TokenStream const & tokens) const override
Definition at line 2584 of file catch_amalgamated.cpp.
References Catch::Clara::Detail::Argument, Catch::Clara::Detail::ParserRefImpl< Arg >::m_ref, Catch::Clara::Matched, Catch::Clara::NoMatch, Catch::Clara::Detail::BasicResult< ParseState >::ok(), Catch::Clara::Detail::BoundValueRefBase::setValue(), and Catch::Clara::Detail::ParserBase::validate().
parse() [2/2]
Detail::InternalParseResult Catch::Clara::Arg::parse (std::string const & , Detail::TokenStream const & tokens) const override
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_clara.cpp