libthe-seed: clara::detail::ResultValueBase< void > Class Reference
clara::detail::ResultValueBase< void > Class Reference
#include <clara.hpp>
Public Member Functions
auto value () const -> void const &
Public Attributes
void m_value
Protected Member Functions
ResultBase (Type type)
ResultValueBase (Type type)
auto operator= (ResultValueBase const &other) -> ResultValueBase &
~ResultValueBase () override
Protected Member Functions inherited from clara::detail::ResultBase
ResultBase (Type type)
virtual ~ResultBase ()=default
virtual void enforceOk () const =0
Protected Attributes
union {
T m_value
};
Protected Attributes inherited from clara::detail::ResultBase
Type m_type
Additional Inherited Members
Public Types inherited from clara::detail::ResultBase
enum Type { Ok , LogicError , RuntimeError }
Detailed Description
Definition at line 575 of file clara.hpp.
Constructor & Destructor Documentation
ResultValueBase()
clara::detail::ResultValueBase< void >::ResultValueBase (Type type) inline protected
Definition at line 544 of file clara.hpp.
Referenced by clara::detail::BasicResult< void >::BasicResult(), and clara::detail::BasicResult< void >::BasicResult().
~ResultValueBase()
clara::detail::ResultValueBase< void >::~ResultValueBase () inline override protected
Definition at line 564 of file clara.hpp.
Member Function Documentation
operator=()
auto clara::detail::ResultValueBase< void >::operator= (ResultValueBase< void > const & other) ->ResultValueBase & inline protected
Definition at line 555 of file clara.hpp.
ResultBase()
clara::detail::ResultBase::ResultBase (Type type) inline protected
Definition at line 527 of file clara.hpp.
Referenced by clara::detail::BasicResult< void >::type().
value()
auto clara::detail::ResultValueBase< void >::value () const->Tconst & inline
Definition at line 538 of file clara.hpp.
Referenced by clara::detail::BasicResult< void >::ok().
Member Data Documentation
[union]
union { ... } clara::detail::ResultValueBase< void >
m_value
void clara::detail::ResultValueBase< void >::m_value
Definition at line 570 of file clara.hpp.
The documentation for this class was generated from the following file:
external/Catch2/third_party/clara.hpp