libthe-seed: Catch::ColourImpl Class Reference
Catch::ColourImpl Class Reference abstract
#include <catch_amalgamated.hpp>
Classes
class ColourGuard
RAII wrapper around writing specific colour of text using specific colour impl into a stream.
Public Member Functions
ColourImpl (IStream *stream)
virtual ~ColourImpl ()
ColourGuard guardColour (Colour::Code colourCode)
ColourImpl (IStream *stream)
virtual ~ColourImpl ()
ColourGuard guardColour (Colour::Code colourCode)
Protected Attributes
IStream * m_stream
The associated stream of this ColourImpl instance.
Detailed Description
Definition at line 3859 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ColourImpl() [1/2]
Catch::ColourImpl::ColourImpl (IStream * stream) inline
Definition at line 3864 of file catch_amalgamated.hpp.
References m_stream.
Referenced by Catch::ColourImpl::ColourGuard::ColourGuard().
~ColourImpl() [1/2]
Catch::ColourImpl::~ColourImpl () virtual default
References guardColour().
ColourImpl() [2/2]
Catch::ColourImpl::ColourImpl (IStream * stream) inline
Definition at line 65 of file catch_console_colour.hpp.
References m_stream.
~ColourImpl() [2/2]
virtual Catch::ColourImpl::~ColourImpl () virtual
Member Function Documentation
guardColour() [1/2]
ColourImpl::ColourGuard Catch::ColourImpl::guardColour (Colour::Code colourCode)
Creates a guard object for given colour and this colour impl
Important: the guard starts disengaged, and has to be engaged explicitly.
Definition at line 3201 of file catch_amalgamated.cpp.
Referenced by Catch::defaultListTests(), Catch::printTestRunTotals(), and ~ColourImpl().
guardColour() [2/2]
ColourGuard Catch::ColourImpl::guardColour (Colour::Code colourCode)
Creates a guard object for given colour and this colour impl
Important: the guard starts disengaged, and has to be engaged explicitly.
Member Data Documentation
m_stream
IStream * Catch::ColourImpl::m_stream protected
The associated stream of this ColourImpl instance.
Definition at line 3862 of file catch_amalgamated.hpp.
Referenced by ColourImpl().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_console_colour.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_console_colour.cpp