libthe-seed: Catch::Matchers::StringMatcherBase Class Reference
Catch::Matchers::StringMatcherBase Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
StringMatcherBase (StringRef operation, CasedString const &comparator)
std::string describe () const override
StringMatcherBase (StringRef operation, CasedString const &comparator)
std::string describe () const override
Public Member Functions inherited from Catch::Matchers::MatcherBase< std::string >
virtual bool match (std::string const &arg) const=0
virtual bool match (std::string const &arg) const=0
Public Member Functions inherited from Catch::Matchers::MatcherUntypedBase
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
Protected Attributes
CasedString m_comparator
StringRef m_operation
Protected Attributes inherited from Catch::Matchers::MatcherUntypedBase
std::string m_cachedToString
Additional Inherited Members
Protected Member Functions inherited from Catch::Matchers::MatcherUntypedBase
virtual ~MatcherUntypedBase ()
virtual ~MatcherUntypedBase ()
Detailed Description
Definition at line 11887 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
StringMatcherBase() [1/2]
Catch::Matchers::StringMatcherBase::StringMatcherBase (StringRef operation, CasedString const & comparator)
Definition at line 7821 of file catch_amalgamated.cpp.
References m_comparator, and m_operation.
Referenced by Catch::Matchers::EndsWithMatcher::EndsWithMatcher(), Catch::Matchers::StartsWithMatcher::StartsWithMatcher(), Catch::Matchers::StringContainsMatcher::StringContainsMatcher(), and Catch::Matchers::StringEqualsMatcher::StringEqualsMatcher().
StringMatcherBase() [2/2]
Catch::Matchers::StringMatcherBase::StringMatcherBase (StringRef operation, CasedString const & comparator)
Member Function Documentation
describe() [1/2]
std::string Catch::Matchers::StringMatcherBase::describe () const override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 7826 of file catch_amalgamated.cpp.
References m_comparator, and m_operation.
describe() [2/2]
std::string Catch::Matchers::StringMatcherBase::describe () const override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Member Data Documentation
m_comparator
CasedString Catch::Matchers::StringMatcherBase::m_comparator protected
Definition at line 11889 of file catch_amalgamated.hpp.
Referenced by describe(), Catch::Matchers::EndsWithMatcher::match(), Catch::Matchers::StartsWithMatcher::match(), Catch::Matchers::StringContainsMatcher::match(), Catch::Matchers::StringEqualsMatcher::match(), and StringMatcherBase().
m_operation
StringRef Catch::Matchers::StringMatcherBase::m_operation protected
Definition at line 11890 of file catch_amalgamated.hpp.
Referenced by describe(), and StringMatcherBase().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/matchers/catch_matchers_string.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/matchers/catch_matchers_string.cpp