libthe-seed: Catch::Capturer Class Reference
Catch::Capturer Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
Capturer (StringRef macroName, SourceLineInfo const &lineInfo, ResultWas::OfType resultType, StringRef names)
Capturer (Capturer const &)=delete
Capturer & operator= (Capturer const &)=delete
~Capturer ()
void captureValue (size_t index, std::string const &value)
template<typename T>
void captureValues (size_t index, T const &value)
template<typename T, typename... Ts>
void captureValues (size_t index, T const &value, Ts const &... values)
Capturer (StringRef macroName, SourceLineInfo const &lineInfo, ResultWas::OfType resultType, StringRef names)
Capturer (Capturer const &)=delete
Capturer & operator= (Capturer const &)=delete
~Capturer ()
void captureValue (size_t index, std::string const &value)
template<typename T>
void captureValues (size_t index, T const &value)
template<typename T, typename... Ts>
void captureValues (size_t index, T const &value, Ts const &... values)
Detailed Description
Definition at line 4271 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
Capturer() [1/4]
Catch::Capturer::Capturer (StringRef macroName, SourceLineInfo const & lineInfo, ResultWas::OfType resultType, StringRef names)
Definition at line 852 of file catch_amalgamated.cpp.
References CATCH_INTERNAL_ERROR, Catch::getResultCapture(), Catch::StringRef::size(), and Catch::StringRef::substr().
Referenced by Capturer(), and operator=().
Capturer() [2/4]
Catch::Capturer::Capturer (Capturer const &) delete
References Capturer().
~Capturer() [1/2]
Catch::Capturer::~Capturer ()
Definition at line 913 of file catch_amalgamated.cpp.
References Catch::uncaught_exceptions().
Capturer() [3/4]
Catch::Capturer::Capturer (StringRef macroName, SourceLineInfo const & lineInfo, ResultWas::OfType resultType, StringRef names)
Capturer() [4/4]
Catch::Capturer::Capturer (Capturer const &) delete
References Capturer().
~Capturer() [2/2]
Catch::Capturer::~Capturer ()
Member Function Documentation
captureValue() [1/2]
void Catch::Capturer::captureValue (size_t index, std::string const & value)
Definition at line 921 of file catch_amalgamated.cpp.
Referenced by captureValues(), captureValues(), and operator=().
captureValue() [2/2]
void Catch::Capturer::captureValue (size_t index, std::string const & value)
captureValues() [1/4]
template<typename T> void Catch::Capturer::captureValues (size_t index, T const & value) inline
Definition at line 4286 of file catch_amalgamated.hpp.
References captureValue(), and Catch::Detail::stringify().
Referenced by captureValues().
captureValues() [2/4]
template<typename T> void Catch::Capturer::captureValues (size_t index, T const & value) inline
Definition at line 79 of file catch_message.hpp.
References captureValue(), and Catch::Detail::stringify().
captureValues() [3/4]
template<typename T, typename... Ts> void Catch::Capturer::captureValues (size_t index, T const & value, Ts const &... values) inline
Definition at line 4291 of file catch_amalgamated.hpp.
References captureValue(), captureValues(), and Catch::Detail::stringify().
captureValues() [4/4]
template<typename T, typename... Ts> void Catch::Capturer::captureValues (size_t index, T const & value, Ts const &... values) inline
Definition at line 84 of file catch_message.hpp.
References captureValue(), captureValues(), and Catch::Detail::stringify().
operator=() [1/2]
Capturer & Catch::Capturer::operator= (Capturer const &) delete
References Capturer(), and captureValue().
operator=() [2/2]
Capturer & Catch::Capturer::operator= (Capturer const &) delete
References Capturer().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/catch_message.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/catch_message.cpp