libthe-seed: Catch::Generators::RandomFloatingGenerator< Float > Class Template Reference
Catch::Generators::RandomFloatingGenerator< Float > Class Template Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
RandomFloatingGenerator (Float a, Float b, std::uint32_t seed)
Float const & get () const override
bool next () override
RandomFloatingGenerator (Float a, Float b, std::uint32_t seed)
Float const & get () const override
bool next () override
Public Member Functions inherited from Catch::Generators::IGenerator< Float >
~IGenerator () override=default
IGenerator ()=default
IGenerator & operator= (IGenerator const &)=default
Public Member Functions inherited from Catch::Generators::GeneratorUntypedBase
GeneratorUntypedBase ()=default
GeneratorUntypedBase (GeneratorUntypedBase const &)=default
GeneratorUntypedBase & operator= (GeneratorUntypedBase const &)=default
virtual ~GeneratorUntypedBase ()
bool countedNext ()
std::size_t currentElementIndex () const
StringRef currentElementAsString () const
GeneratorUntypedBase ()=default
GeneratorUntypedBase (GeneratorUntypedBase const &)=default
GeneratorUntypedBase & operator= (GeneratorUntypedBase const &)=default
virtual ~GeneratorUntypedBase ()
bool countedNext ()
std::size_t currentElementIndex () const
StringRef currentElementAsString () const
Additional Inherited Members
Public Types inherited from Catch::Generators::IGenerator< Float >
using type
Detailed Description
template<typename Float>
class Catch::Generators::RandomFloatingGenerator< Float >
Definition at line 8052 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
RandomFloatingGenerator() [1/2]
template<typename Float> Catch::Generators::RandomFloatingGenerator< Float >::RandomFloatingGenerator (Float a, Float b, std::uint32_t seed) inline
Definition at line 8057 of file catch_amalgamated.hpp.
References next().
RandomFloatingGenerator() [2/2]
template<typename Float> Catch::Generators::RandomFloatingGenerator< Float >::RandomFloatingGenerator (Float a, Float b, std::uint32_t seed) inline
Definition at line 32 of file catch_generators_random.hpp.
References next().
Member Function Documentation
get() [1/2]
template<typename Float> Float const & Catch::Generators::RandomFloatingGenerator< Float >::get () const inline override virtual
Implements Catch::Generators::IGenerator< Float >.
Definition at line 8063 of file catch_amalgamated.hpp.
Referenced by TEST_CASE().
get() [2/2]
template<typename Float> Float const & Catch::Generators::RandomFloatingGenerator< Float >::get () const inline override virtual
Implements Catch::Generators::IGenerator< Float >.
Definition at line 38 of file catch_generators_random.hpp.
next() [1/2]
template<typename Float> bool Catch::Generators::RandomFloatingGenerator< Float >::next () inline override virtual
Attempts to move the generator to the next element
Returns true iff the move succeeded (and a valid element can be retrieved).
Implements Catch::Generators::GeneratorUntypedBase.
Definition at line 8066 of file catch_amalgamated.hpp.
Referenced by RandomFloatingGenerator(), and TEST_CASE().
next() [2/2]
template<typename Float> bool Catch::Generators::RandomFloatingGenerator< Float >::next () inline override virtual
Attempts to move the generator to the next element
Returns true iff the move succeeded (and a valid element can be retrieved).
Implements Catch::Generators::GeneratorUntypedBase.
Definition at line 41 of file catch_generators_random.hpp.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/generators/catch_generators_random.hpp