libthe-seed: Catch::Session Class Reference
Catch::Session Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
Session ()
~Session ()
void showHelp () const
void libIdentify ()
int applyCommandLine (int argc, char const *const *argv)
void useConfigData (ConfigData const &configData)
template<typename CharT>
int run (int argc, CharT const *const argv[])
int run ()
Clara::Parser const & cli () const
void cli (Clara::Parser const &newParser)
ConfigData & configData ()
Config & config ()
Session ()
~Session ()
void showHelp () const
void libIdentify ()
int applyCommandLine (int argc, char const *const *argv)
void useConfigData (ConfigData const &configData)
template<typename CharT>
int run (int argc, CharT const *const argv[])
int run ()
Clara::Parser const & cli () const
void cli (Clara::Parser const &newParser)
ConfigData & configData ()
Config & config ()
Detailed Description
Definition at line 5144 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
Session() [1/2]
Catch::Session::Session ()
Definition at line 1139 of file catch_amalgamated.cpp.
References CATCH_CATCH_ALL, CATCH_INTERNAL_ERROR, CATCH_TRY, config(), Catch::getCurrentMutableContext(), Catch::StartupExceptionRegistry::getExceptions(), Catch::getMutableRegistryHub(), Catch::getRegistryHub(), Catch::IRegistryHub::getStartupExceptionRegistry(), Catch::TextFlow::Column::indent(), Catch::makeColourImpl(), Catch::makeCommandLineParser(), Catch::makeStream(), Catch::PlatformDefault, Catch::Colour::Red, Catch::IMutableRegistryHub::registerStartupException(), and Catch::Context::setConfig().
~Session() [1/2]
Catch::Session::~Session ()
Definition at line 1173 of file catch_amalgamated.cpp.
References Catch::cleanUp().
Session() [2/2]
Catch::Session::Session ()
~Session() [2/2]
Catch::Session::~Session ()
Member Function Documentation
applyCommandLine() [1/2]
int Catch::Session::applyCommandLine (int argc, char const *const * argv)
Definition at line 1191 of file catch_amalgamated.cpp.
References config(), Catch::getCurrentMutableContext(), Catch::TextFlow::Column::indent(), libIdentify(), Catch::makeColourImpl(), Catch::makeStream(), Catch::PlatformDefault, Catch::Colour::Red, Catch::Context::setConfig(), and showHelp().
Referenced by run().
applyCommandLine() [2/2]
int Catch::Session::applyCommandLine (int argc, char const *const * argv)
cli() [1/4]
Clara::Parser const & Catch::Session::cli () const
Definition at line 1263 of file catch_amalgamated.cpp.
cli() [2/4]
Clara::Parser const & Catch::Session::cli () const
cli() [3/4]
void Catch::Session::cli (Clara::Parser const & newParser)
Definition at line 1266 of file catch_amalgamated.cpp.
cli() [4/4]
void Catch::Session::cli (Clara::Parser const & newParser)
config() [1/2]
Config & Catch::Session::config ()
Definition at line 1272 of file catch_amalgamated.cpp.
References Catch::Detail::make_unique().
Referenced by applyCommandLine(), and Session().
config() [2/2]
Config & Catch::Session::config ()
configData() [1/2]
ConfigData & Catch::Session::configData ()
Definition at line 1269 of file catch_amalgamated.cpp.
Referenced by useConfigData().
configData() [2/2]
ConfigData & Catch::Session::configData ()
libIdentify() [1/2]
void Catch::Session::libIdentify ()
Definition at line 1183 of file catch_amalgamated.cpp.
References Catch::cout(), and Catch::libraryVersion().
Referenced by applyCommandLine().
libIdentify() [2/2]
void Catch::Session::libIdentify ()
run() [1/4]
int Catch::Session::run ()
Definition at line 1250 of file catch_amalgamated.cpp.
References Catch::WaitForKeypress::BeforeExit, Catch::WaitForKeypress::BeforeStart, and Catch::cout().
Referenced by run().
run() [2/4]
int Catch::Session::run ()
run() [3/4]
template<typename CharT> int Catch::Session::run (int argc, CharT const *const argv[]) inline
Definition at line 5161 of file catch_amalgamated.hpp.
References applyCommandLine(), and run().
Referenced by main(), and run().
run() [4/4]
template<typename CharT> int Catch::Session::run (int argc, CharT const *const argv[]) inline
Definition at line 36 of file catch_session.hpp.
References applyCommandLine(), and run().
showHelp() [1/2]
void Catch::Session::showHelp () const
Definition at line 1177 of file catch_amalgamated.cpp.
References Catch::cout(), and Catch::libraryVersion().
Referenced by applyCommandLine().
showHelp() [2/2]
void Catch::Session::showHelp () const
useConfigData() [1/2]
void Catch::Session::useConfigData (ConfigData const & configData)
Definition at line 1245 of file catch_amalgamated.cpp.
References configData().
useConfigData() [2/2]
void Catch::Session::useConfigData (ConfigData const & configData)
References configData().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/catch_session.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/catch_session.cpp