libthe-seed: Catch::IResultCapture Class Reference
Catch::IResultCapture Class Reference abstract
#include <catch_amalgamated.hpp>
Public Member Functions
virtual ~IResultCapture ()
virtual void notifyAssertionStarted (AssertionInfo const &info)=0
virtual bool sectionStarted (StringRef sectionName, SourceLineInfo const &sectionLineInfo, Counts &assertions)=0
virtual void sectionEnded (SectionEndInfo &&endInfo)=0
virtual void sectionEndedEarly (SectionEndInfo &&endInfo)=0
virtual IGeneratorTracker * acquireGeneratorTracker (StringRef generatorName, SourceLineInfo const &lineInfo)=0
virtual IGeneratorTracker * createGeneratorTracker (StringRef generatorName, SourceLineInfo lineInfo, Generators::GeneratorBasePtr &&generator)=0
virtual void benchmarkPreparing (StringRef name)=0
virtual void benchmarkStarting (BenchmarkInfo const &info)=0
virtual void benchmarkEnded (BenchmarkStats<> const &stats)=0
virtual void benchmarkFailed (StringRef error)=0
virtual void pushScopedMessage (MessageInfo const &message)=0
virtual void popScopedMessage (MessageInfo const &message)=0
virtual void emplaceUnscopedMessage (MessageBuilder &&builder)=0
virtual void handleFatalErrorCondition (StringRef message)=0
virtual void handleExpr (AssertionInfo const &info, ITransientExpression const &expr, AssertionReaction &reaction)=0
virtual void handleMessage (AssertionInfo const &info, ResultWas::OfType resultType, StringRef message, AssertionReaction &reaction)=0
virtual void handleUnexpectedExceptionNotThrown (AssertionInfo const &info, AssertionReaction &reaction)=0
virtual void handleUnexpectedInflightException (AssertionInfo const &info, std::string &&message, AssertionReaction &reaction)=0
virtual void handleIncomplete (AssertionInfo const &info)=0
virtual void handleNonExpr (AssertionInfo const &info, ResultWas::OfType resultType, AssertionReaction &reaction)=0
virtual bool lastAssertionPassed ()=0
virtual void assertionPassed ()=0
virtual std::string getCurrentTestName () const =0
virtual const AssertionResult * getLastResult () const =0
virtual void exceptionEarlyReported ()=0
virtual ~IResultCapture ()
virtual void notifyAssertionStarted (AssertionInfo const &info)=0
virtual bool sectionStarted (StringRef sectionName, SourceLineInfo const &sectionLineInfo, Counts &assertions)=0
virtual void sectionEnded (SectionEndInfo &&endInfo)=0
virtual void sectionEndedEarly (SectionEndInfo &&endInfo)=0
virtual IGeneratorTracker * acquireGeneratorTracker (StringRef generatorName, SourceLineInfo const &lineInfo)=0
virtual IGeneratorTracker * createGeneratorTracker (StringRef generatorName, SourceLineInfo lineInfo, Generators::GeneratorBasePtr &&generator)=0
virtual void benchmarkPreparing (StringRef name)=0
virtual void benchmarkStarting (BenchmarkInfo const &info)=0
virtual void benchmarkEnded (BenchmarkStats<> const &stats)=0
virtual void benchmarkFailed (StringRef error)=0
virtual void pushScopedMessage (MessageInfo const &message)=0
virtual void popScopedMessage (MessageInfo const &message)=0
virtual void emplaceUnscopedMessage (MessageBuilder &&builder)=0
virtual void handleFatalErrorCondition (StringRef message)=0
virtual void handleExpr (AssertionInfo const &info, ITransientExpression const &expr, AssertionReaction &reaction)=0
virtual void handleMessage (AssertionInfo const &info, ResultWas::OfType resultType, StringRef message, AssertionReaction &reaction)=0
virtual void handleUnexpectedExceptionNotThrown (AssertionInfo const &info, AssertionReaction &reaction)=0
virtual void handleUnexpectedInflightException (AssertionInfo const &info, std::string &&message, AssertionReaction &reaction)=0
virtual void handleIncomplete (AssertionInfo const &info)=0
virtual void handleNonExpr (AssertionInfo const &info, ResultWas::OfType resultType, AssertionReaction &reaction)=0
virtual bool lastAssertionPassed ()=0
virtual void assertionPassed ()=0
virtual std::string getCurrentTestName () const =0
virtual const AssertionResult * getLastResult () const =0
virtual void exceptionEarlyReported ()=0
Detailed Description
Definition at line 990 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
~IResultCapture() [1/2]
Catch::IResultCapture::~IResultCapture () virtual default
~IResultCapture() [2/2]
virtual Catch::IResultCapture::~IResultCapture () virtual
Member Function Documentation
acquireGeneratorTracker() [1/2]
virtual IGeneratorTracker * Catch::IResultCapture::acquireGeneratorTracker (StringRef generatorName, SourceLineInfo const & lineInfo) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
Referenced by Catch::Generators::acquireGeneratorTracker().
acquireGeneratorTracker() [2/2]
virtual IGeneratorTracker * Catch::IResultCapture::acquireGeneratorTracker (StringRef generatorName, SourceLineInfo const & lineInfo) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
assertionPassed() [1/2]
virtual void Catch::IResultCapture::assertionPassed () pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
assertionPassed() [2/2]
virtual void Catch::IResultCapture::assertionPassed () pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
benchmarkEnded() [1/2]
virtual void Catch::IResultCapture::benchmarkEnded (BenchmarkStats<> const & stats) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
Referenced by Catch::Benchmark::Benchmark::run().
benchmarkEnded() [2/2]
virtual void Catch::IResultCapture::benchmarkEnded (BenchmarkStats<> const & stats) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
benchmarkFailed() [1/2]
virtual void Catch::IResultCapture::benchmarkFailed (StringRef error) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
Referenced by Catch::Benchmark::Benchmark::run().
benchmarkFailed() [2/2]
virtual void Catch::IResultCapture::benchmarkFailed (StringRef error) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
benchmarkPreparing() [1/2]
virtual void Catch::IResultCapture::benchmarkPreparing (StringRef name) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
Referenced by Catch::Benchmark::Benchmark::run().
benchmarkPreparing() [2/2]
virtual void Catch::IResultCapture::benchmarkPreparing (StringRef name) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
benchmarkStarting() [1/2]
virtual void Catch::IResultCapture::benchmarkStarting (BenchmarkInfo const & info) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
Referenced by Catch::Benchmark::Benchmark::run().
benchmarkStarting() [2/2]
virtual void Catch::IResultCapture::benchmarkStarting (BenchmarkInfo const & info) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
createGeneratorTracker() [1/2]
virtual IGeneratorTracker * Catch::IResultCapture::createGeneratorTracker (StringRef generatorName, SourceLineInfo lineInfo, Generators::GeneratorBasePtr && generator) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
Referenced by Catch::Generators::createGeneratorTracker().
createGeneratorTracker() [2/2]
virtual IGeneratorTracker * Catch::IResultCapture::createGeneratorTracker (StringRef generatorName, SourceLineInfo lineInfo, Generators::GeneratorBasePtr && generator) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
emplaceUnscopedMessage() [1/2]
virtual void Catch::IResultCapture::emplaceUnscopedMessage (MessageBuilder && builder) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
emplaceUnscopedMessage() [2/2]
virtual void Catch::IResultCapture::emplaceUnscopedMessage (MessageBuilder && builder) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
exceptionEarlyReported() [1/2]
virtual void Catch::IResultCapture::exceptionEarlyReported () pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
exceptionEarlyReported() [2/2]
virtual void Catch::IResultCapture::exceptionEarlyReported () pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
getCurrentTestName() [1/2]
virtual std::string Catch::IResultCapture::getCurrentTestName () const pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
getCurrentTestName() [2/2]
virtual std::string Catch::IResultCapture::getCurrentTestName () const pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
getLastResult() [1/2]
virtual const AssertionResult * Catch::IResultCapture::getLastResult () const pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
getLastResult() [2/2]
virtual const AssertionResult * Catch::IResultCapture::getLastResult () const pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleExpr() [1/2]
virtual void Catch::IResultCapture::handleExpr (AssertionInfo const & info, ITransientExpression const & expr, AssertionReaction & reaction) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleExpr() [2/2]
virtual void Catch::IResultCapture::handleExpr (AssertionInfo const & info, ITransientExpression const & expr, AssertionReaction & reaction) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleFatalErrorCondition() [1/2]
virtual void Catch::IResultCapture::handleFatalErrorCondition (StringRef message) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleFatalErrorCondition() [2/2]
virtual void Catch::IResultCapture::handleFatalErrorCondition (StringRef message) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleIncomplete() [1/2]
virtual void Catch::IResultCapture::handleIncomplete (AssertionInfo const & info) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleIncomplete() [2/2]
virtual void Catch::IResultCapture::handleIncomplete (AssertionInfo const & info) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleMessage() [1/2]
virtual void Catch::IResultCapture::handleMessage (AssertionInfo const & info, ResultWas::OfType resultType, StringRef message, AssertionReaction & reaction) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleMessage() [2/2]
virtual void Catch::IResultCapture::handleMessage (AssertionInfo const & info, ResultWas::OfType resultType, StringRef message, AssertionReaction & reaction) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleNonExpr() [1/2]
virtual void Catch::IResultCapture::handleNonExpr (AssertionInfo const & info, ResultWas::OfType resultType, AssertionReaction & reaction) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleNonExpr() [2/2]
virtual void Catch::IResultCapture::handleNonExpr (AssertionInfo const & info, ResultWas::OfType resultType, AssertionReaction & reaction) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleUnexpectedExceptionNotThrown() [1/2]
virtual void Catch::IResultCapture::handleUnexpectedExceptionNotThrown (AssertionInfo const & info, AssertionReaction & reaction) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleUnexpectedExceptionNotThrown() [2/2]
virtual void Catch::IResultCapture::handleUnexpectedExceptionNotThrown (AssertionInfo const & info, AssertionReaction & reaction) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleUnexpectedInflightException() [1/2]
virtual void Catch::IResultCapture::handleUnexpectedInflightException (AssertionInfo const & info, std::string && message, AssertionReaction & reaction) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
handleUnexpectedInflightException() [2/2]
virtual void Catch::IResultCapture::handleUnexpectedInflightException (AssertionInfo const & info, std::string && message, AssertionReaction & reaction) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
lastAssertionPassed() [1/2]
virtual bool Catch::IResultCapture::lastAssertionPassed () pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
lastAssertionPassed() [2/2]
virtual bool Catch::IResultCapture::lastAssertionPassed () pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
notifyAssertionStarted() [1/2]
virtual void Catch::IResultCapture::notifyAssertionStarted (AssertionInfo const & info) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
notifyAssertionStarted() [2/2]
virtual void Catch::IResultCapture::notifyAssertionStarted (AssertionInfo const & info) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
popScopedMessage() [1/2]
virtual void Catch::IResultCapture::popScopedMessage (MessageInfo const & message) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
Referenced by Catch::ScopedMessage::~ScopedMessage().
popScopedMessage() [2/2]
virtual void Catch::IResultCapture::popScopedMessage (MessageInfo const & message) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
pushScopedMessage() [1/2]
virtual void Catch::IResultCapture::pushScopedMessage (MessageInfo const & message) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
Referenced by Catch::ScopedMessage::ScopedMessage().
pushScopedMessage() [2/2]
virtual void Catch::IResultCapture::pushScopedMessage (MessageInfo const & message) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
sectionEnded() [1/2]
virtual void Catch::IResultCapture::sectionEnded (SectionEndInfo && endInfo) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
Referenced by Catch::Section::~Section().
sectionEnded() [2/2]
virtual void Catch::IResultCapture::sectionEnded (SectionEndInfo && endInfo) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
sectionEndedEarly() [1/2]
virtual void Catch::IResultCapture::sectionEndedEarly (SectionEndInfo && endInfo) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
Referenced by Catch::Section::~Section().
sectionEndedEarly() [2/2]
virtual void Catch::IResultCapture::sectionEndedEarly (SectionEndInfo && endInfo) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
sectionStarted() [1/2]
virtual bool Catch::IResultCapture::sectionStarted (StringRef sectionName, SourceLineInfo const & sectionLineInfo, Counts & assertions) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
sectionStarted() [2/2]
virtual bool Catch::IResultCapture::sectionStarted (StringRef sectionName, SourceLineInfo const & sectionLineInfo, Counts & assertions) pure virtual
Implemented in Catch::RunContext, and Catch::RunContext.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/interfaces/catch_interfaces_capture.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/interfaces/catch_interfaces_capture.cpp