libthe-seed: Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch > Class Template Reference
Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch > Class Template Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
ApproxMatcher (std::vector< T, AllocComp > const &comparator)
bool match (std::vector< T, AllocMatch > const &v) const override
std::string describe () const override
template<typename = std::enable_if_t<std::is_constructible<double, T>::value>>
ApproxMatcher & epsilon (T const &newEpsilon)
template<typename = std::enable_if_t<std::is_constructible<double, T>::value>>
ApproxMatcher & margin (T const &newMargin)
template<typename = std::enable_if_t<std::is_constructible<double, T>::value>>
ApproxMatcher & scale (T const &newScale)
ApproxMatcher (std::vector< T, AllocComp > const &comparator)
bool match (std::vector< T, AllocMatch > const &v) const override
std::string describe () const override
template<typename = std::enable_if_t<std::is_constructible<double, T>::value>>
ApproxMatcher & epsilon (T const &newEpsilon)
template<typename = std::enable_if_t<std::is_constructible<double, T>::value>>
ApproxMatcher & margin (T const &newMargin)
template<typename = std::enable_if_t<std::is_constructible<double, T>::value>>
ApproxMatcher & scale (T const &newScale)
Public Member Functions inherited from Catch::Matchers::MatcherBase< std::vector< T, AllocMatch > >
virtual bool match (T const &arg) const=0
Public Member Functions inherited from Catch::Matchers::MatcherUntypedBase
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
Additional Inherited Members
Protected Member Functions inherited from Catch::Matchers::MatcherUntypedBase
virtual ~MatcherUntypedBase ()
virtual ~MatcherUntypedBase ()
Protected Attributes inherited from Catch::Matchers::MatcherUntypedBase
std::string m_cachedToString
Detailed Description
template<typename T, typename AllocComp, typename AllocMatch>
class Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >
Definition at line 12036 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ApproxMatcher() [1/2]
template<typename T, typename AllocComp, typename AllocMatch> Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::ApproxMatcher (std::vector< T, AllocComp > const & comparator) inline
Definition at line 12041 of file catch_amalgamated.hpp.
Referenced by epsilon(), margin(), and scale().
ApproxMatcher() [2/2]
template<typename T, typename AllocComp, typename AllocMatch> Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::ApproxMatcher (std::vector< T, AllocComp > const & comparator) inline
Definition at line 105 of file catch_matchers_vector.hpp.
Member Function Documentation
describe() [1/2]
template<typename T, typename AllocComp, typename AllocMatch> std::string Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 12053 of file catch_amalgamated.hpp.
References Catch::Detail::stringify().
describe() [2/2]
template<typename T, typename AllocComp, typename AllocMatch> std::string Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 117 of file catch_matchers_vector.hpp.
References Catch::Detail::stringify().
epsilon() [1/2]
template<typename T, typename AllocComp, typename AllocMatch> template<typename = std::enable_if_t<std::is_constructible<double, T>::value>> ApproxMatcher & Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::epsilon (T const & newEpsilon) inline
Definition at line 12057 of file catch_amalgamated.hpp.
References ApproxMatcher(), and epsilon().
Referenced by epsilon().
epsilon() [2/2]
template<typename T, typename AllocComp, typename AllocMatch> template<typename = std::enable_if_t<std::is_constructible<double, T>::value>> ApproxMatcher & Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::epsilon (T const & newEpsilon) inline
Definition at line 121 of file catch_matchers_vector.hpp.
References ApproxMatcher(), and epsilon().
margin() [1/2]
template<typename T, typename AllocComp, typename AllocMatch> template<typename = std::enable_if_t<std::is_constructible<double, T>::value>> ApproxMatcher & Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::margin (T const & newMargin) inline
Definition at line 12062 of file catch_amalgamated.hpp.
References ApproxMatcher(), and margin().
Referenced by margin().
margin() [2/2]
template<typename T, typename AllocComp, typename AllocMatch> template<typename = std::enable_if_t<std::is_constructible<double, T>::value>> ApproxMatcher & Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::margin (T const & newMargin) inline
Definition at line 126 of file catch_matchers_vector.hpp.
References ApproxMatcher(), and margin().
match() [1/2]
template<typename T, typename AllocComp, typename AllocMatch> bool Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::match (std::vector< T, AllocMatch > const & v) const inline override
Definition at line 12045 of file catch_amalgamated.hpp.
match() [2/2]
template<typename T, typename AllocComp, typename AllocMatch> bool Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::match (std::vector< T, AllocMatch > const & v) const inline override
Definition at line 109 of file catch_matchers_vector.hpp.
scale() [1/2]
template<typename T, typename AllocComp, typename AllocMatch> template<typename = std::enable_if_t<std::is_constructible<double, T>::value>> ApproxMatcher & Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::scale (T const & newScale) inline
Definition at line 12067 of file catch_amalgamated.hpp.
References ApproxMatcher(), and scale().
Referenced by scale().
scale() [2/2]
template<typename T, typename AllocComp, typename AllocMatch> template<typename = std::enable_if_t<std::is_constructible<double, T>::value>> ApproxMatcher & Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::scale (T const & newScale) inline
Definition at line 131 of file catch_matchers_vector.hpp.
References ApproxMatcher(), and scale().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/matchers/catch_matchers_vector.hpp