libthe-seed: Catch::TestCaseTracking::ITracker Class Reference
Catch::TestCaseTracking::ITracker Class Reference abstract
#include <catch_amalgamated.hpp>
Public Member Functions
ITracker (NameAndLocation &&nameAndLoc, ITracker *parent)
NameAndLocation const & nameAndLocation () const
ITracker * parent () const
virtual ~ITracker ()
virtual bool isComplete () const =0
Returns true if tracker run to completion (successfully or not).
bool isSuccessfullyCompleted () const
Returns true if tracker run to completion successfully.
bool isOpen () const
Returns true if tracker has started but hasn't been completed.
bool hasStarted () const
Returns true iff tracker has started.
virtual void close ()=0
virtual void fail ()=0
void markAsNeedingAnotherRun ()
void addChild (ITrackerPtr &&child)
Register a nested ITracker.
ITracker * findChild (NameAndLocationRef const &nameAndLocation)
bool hasChildren () const
Have any children been added?
void openChild ()
Marks tracker as executing a child, doing se recursively up the tree.
virtual bool isSectionTracker () const
virtual bool isGeneratorTracker () const
ITracker (NameAndLocation &&nameAndLoc, ITracker *parent)
NameAndLocation const & nameAndLocation () const
ITracker * parent () const
virtual ~ITracker ()
virtual bool isComplete () const =0
Returns true if tracker run to completion (successfully or not).
bool isSuccessfullyCompleted () const
Returns true if tracker run to completion successfully.
bool isOpen () const
Returns true if tracker has started but hasn't been completed.
bool hasStarted () const
Returns true iff tracker has started.
virtual void close ()=0
virtual void fail ()=0
void markAsNeedingAnotherRun ()
void addChild (ITrackerPtr &&child)
Register a nested ITracker.
ITracker * findChild (NameAndLocationRef const &nameAndLocation)
bool hasChildren () const
Have any children been added?
void openChild ()
Marks tracker as executing a child, doing se recursively up the tree.
virtual bool isSectionTracker () const
virtual bool isGeneratorTracker () const
Protected Types
enum CycleState {
NotStarted , Executing , ExecutingChildren , NeedsAnotherRun ,
CompletedSuccessfully , Failed , NotStarted , Executing ,
ExecutingChildren , NeedsAnotherRun , CompletedSuccessfully , Failed
}
enum CycleState {
NotStarted , Executing , ExecutingChildren , NeedsAnotherRun ,
CompletedSuccessfully , Failed , NotStarted , Executing ,
ExecutingChildren , NeedsAnotherRun , CompletedSuccessfully , Failed
}
Protected Attributes
ITracker * m_parent = nullptr
Children m_children
CycleState m_runState = NotStarted
Detailed Description
Definition at line 9592 of file catch_amalgamated.hpp.
Member Enumeration Documentation
CycleState [1/2]
enum Catch::TestCaseTracking::ITracker::CycleState protected
Enumerator
NotStarted
Executing
ExecutingChildren
NeedsAnotherRun
CompletedSuccessfully
Failed
NotStarted
Executing
ExecutingChildren
NeedsAnotherRun
CompletedSuccessfully
Failed
Definition at line 9598 of file catch_amalgamated.hpp.
CycleState [2/2]
enum Catch::TestCaseTracking::ITracker::CycleState protected
Enumerator
NotStarted
Executing
ExecutingChildren
NeedsAnotherRun
CompletedSuccessfully
Failed
NotStarted
Executing
ExecutingChildren
NeedsAnotherRun
CompletedSuccessfully
Failed
Definition at line 81 of file catch_test_case_tracker.hpp.
Constructor & Destructor Documentation
ITracker() [1/2]
Catch::TestCaseTracking::ITracker::ITracker (NameAndLocation && nameAndLoc, ITracker * parent) inline
Definition at line 9612 of file catch_amalgamated.hpp.
References CATCH_MOVE, ITracker(), m_parent, and parent().
Referenced by fail(), findChild(), ITracker(), parent(), and Catch::TestCaseTracking::TrackerBase::TrackerBase().
~ITracker() [1/2]
Catch::TestCaseTracking::ITracker::~ITracker () virtual default
ITracker() [2/2]
Catch::TestCaseTracking::ITracker::ITracker (NameAndLocation && nameAndLoc, ITracker * parent) inline
Definition at line 95 of file catch_test_case_tracker.hpp.
References CATCH_MOVE, ITracker(), m_parent, and parent().
~ITracker() [2/2]
virtual Catch::TestCaseTracking::ITracker::~ITracker () virtual
Member Function Documentation
addChild() [1/2]
void Catch::TestCaseTracking::ITracker::addChild (ITrackerPtr && child)
Register a nested ITracker.
Definition at line 6299 of file catch_amalgamated.cpp.
References CATCH_MOVE, and m_children.
Referenced by Catch::TestCaseTracking::SectionTracker::acquire(), and fail().
addChild() [2/2]
void Catch::TestCaseTracking::ITracker::addChild (ITrackerPtr && child)
Register a nested ITracker.
close() [1/2]
virtual void Catch::TestCaseTracking::ITracker::close () pure virtual
Implemented in Catch::TestCaseTracking::TrackerBase, and Catch::TestCaseTracking::TrackerBase.
Referenced by TEST_CASE().
close() [2/2]
virtual void Catch::TestCaseTracking::ITracker::close () pure virtual
Implemented in Catch::TestCaseTracking::TrackerBase, and Catch::TestCaseTracking::TrackerBase.
fail() [1/2]
virtual void Catch::TestCaseTracking::ITracker::fail () pure virtual
Implemented in Catch::TestCaseTracking::TrackerBase, and Catch::TestCaseTracking::TrackerBase.
References addChild(), findChild(), ITracker(), markAsNeedingAnotherRun(), and nameAndLocation().
Referenced by TEST_CASE().
fail() [2/2]
virtual void Catch::TestCaseTracking::ITracker::fail () pure virtual
Implemented in Catch::TestCaseTracking::TrackerBase, and Catch::TestCaseTracking::TrackerBase.
findChild() [1/2]
ITracker * Catch::TestCaseTracking::ITracker::findChild (NameAndLocationRef const & nameAndLocation)
Returns ptr to specific child if register with this tracker.
Returns nullptr if not found.
Definition at line 6303 of file catch_amalgamated.cpp.
References ITracker(), m_children, and nameAndLocation().
Referenced by Catch::TestCaseTracking::SectionTracker::acquire(), and fail().
findChild() [2/2]
ITracker * Catch::TestCaseTracking::ITracker::findChild (NameAndLocationRef const & nameAndLocation)
Returns ptr to specific child if register with this tracker.
Returns nullptr if not found.
References ITracker(), and nameAndLocation().
hasChildren() [1/2]
bool Catch::TestCaseTracking::ITracker::hasChildren () const inline
Have any children been added?
Definition at line 9656 of file catch_amalgamated.hpp.
References m_children.
hasChildren() [2/2]
bool Catch::TestCaseTracking::ITracker::hasChildren () const inline
Have any children been added?
Definition at line 139 of file catch_test_case_tracker.hpp.
References m_children.
hasStarted() [1/2]
bool Catch::TestCaseTracking::ITracker::hasStarted () const
Returns true iff tracker has started.
Definition at line 6325 of file catch_amalgamated.cpp.
References m_runState, and NotStarted.
hasStarted() [2/2]
bool Catch::TestCaseTracking::ITracker::hasStarted () const
Returns true iff tracker has started.
isComplete() [1/2]
virtual bool Catch::TestCaseTracking::ITracker::isComplete () const pure virtual
Returns true if tracker run to completion (successfully or not).
Implemented in Catch::SectionTracker, Catch::SectionTracker, Catch::TestCaseTracking::SectionTracker, Catch::TestCaseTracking::SectionTracker, Catch::TestCaseTracking::TrackerBase, and Catch::TestCaseTracking::TrackerBase.
Referenced by isOpen(), and TEST_CASE().
isComplete() [2/2]
virtual bool Catch::TestCaseTracking::ITracker::isComplete () const pure virtual
Returns true if tracker run to completion (successfully or not).
Implemented in Catch::SectionTracker, Catch::SectionTracker, Catch::TestCaseTracking::SectionTracker, Catch::TestCaseTracking::SectionTracker, Catch::TestCaseTracking::TrackerBase, and Catch::TestCaseTracking::TrackerBase.
isGeneratorTracker() [1/2]
bool Catch::TestCaseTracking::ITracker::isGeneratorTracker () const virtual
Returns true if the instance is a generator tracker
Subclasses should override to true if they are, replaces RTTI for internal debug checks.
Definition at line 6319 of file catch_amalgamated.cpp.
isGeneratorTracker() [2/2]
virtual bool Catch::TestCaseTracking::ITracker::isGeneratorTracker () const virtual
Returns true if the instance is a generator tracker
Subclasses should override to true if they are, replaces RTTI for internal debug checks.
isOpen() [1/2]
bool Catch::TestCaseTracking::ITracker::isOpen () const
Returns true if tracker has started but hasn't been completed.
Definition at line 6321 of file catch_amalgamated.cpp.
References isComplete(), m_runState, and NotStarted.
Referenced by Catch::RunContext::sectionStarted(), and TEST_CASE().
isOpen() [2/2]
bool Catch::TestCaseTracking::ITracker::isOpen () const
Returns true if tracker has started but hasn't been completed.
isSectionTracker() [1/2]
bool Catch::TestCaseTracking::ITracker::isSectionTracker () const virtual
Returns true if the instance is a section tracker
Subclasses should override to true if they are, replaces RTTI for internal debug checks.
Reimplemented in Catch::SectionTracker, Catch::SectionTracker, Catch::TestCaseTracking::SectionTracker, and Catch::TestCaseTracking::SectionTracker.
Definition at line 6318 of file catch_amalgamated.cpp.
Referenced by Catch::RunContext::runTest().
isSectionTracker() [2/2]
virtual bool Catch::TestCaseTracking::ITracker::isSectionTracker () const virtual
Returns true if the instance is a section tracker
Subclasses should override to true if they are, replaces RTTI for internal debug checks.
Reimplemented in Catch::SectionTracker, Catch::SectionTracker, Catch::TestCaseTracking::SectionTracker, and Catch::TestCaseTracking::SectionTracker.
isSuccessfullyCompleted() [1/2]
bool Catch::TestCaseTracking::ITracker::isSuccessfullyCompleted () const inline
Returns true if tracker run to completion successfully.
Definition at line 9634 of file catch_amalgamated.hpp.
References CompletedSuccessfully, and m_runState.
Referenced by TEST_CASE().
isSuccessfullyCompleted() [2/2]
bool Catch::TestCaseTracking::ITracker::isSuccessfullyCompleted () const inline
Returns true if tracker run to completion successfully.
Definition at line 117 of file catch_test_case_tracker.hpp.
References CompletedSuccessfully, and m_runState.
markAsNeedingAnotherRun() [1/2]
void Catch::TestCaseTracking::ITracker::markAsNeedingAnotherRun ()
Definition at line 6295 of file catch_amalgamated.cpp.
References m_runState, and NeedsAnotherRun.
Referenced by fail().
markAsNeedingAnotherRun() [2/2]
void Catch::TestCaseTracking::ITracker::markAsNeedingAnotherRun ()
nameAndLocation() [1/2]
NameAndLocation const & Catch::TestCaseTracking::ITracker::nameAndLocation () const inline
Definition at line 9619 of file catch_amalgamated.hpp.
Referenced by Catch::TestCaseTracking::SectionTracker::acquire(), fail(), findChild(), Catch::TestCaseTracking::SectionTracker::SectionTracker(), and Catch::TestCaseTracking::TrackerBase::TrackerBase().
nameAndLocation() [2/2]
NameAndLocation const & Catch::TestCaseTracking::ITracker::nameAndLocation () const inline
Definition at line 102 of file catch_test_case_tracker.hpp.
openChild() [1/2]
void Catch::TestCaseTracking::ITracker::openChild ()
Marks tracker as executing a child, doing se recursively up the tree.
Definition at line 6327 of file catch_amalgamated.cpp.
References ExecutingChildren, m_parent, and m_runState.
openChild() [2/2]
void Catch::TestCaseTracking::ITracker::openChild ()
Marks tracker as executing a child, doing se recursively up the tree.
parent() [1/2]
ITracker * Catch::TestCaseTracking::ITracker::parent () const inline
Definition at line 9622 of file catch_amalgamated.hpp.
References ITracker(), and m_parent.
Referenced by ITracker(), Catch::TestCaseTracking::SectionTracker::SectionTracker(), and Catch::TestCaseTracking::TrackerBase::TrackerBase().
parent() [2/2]
ITracker * Catch::TestCaseTracking::ITracker::parent () const inline
Definition at line 105 of file catch_test_case_tracker.hpp.
References ITracker(), and m_parent.
Member Data Documentation
m_children
Children Catch::TestCaseTracking::ITracker::m_children protected
Definition at line 9608 of file catch_amalgamated.hpp.
Referenced by addChild(), Catch::TestCaseTracking::TrackerBase::close(), findChild(), and hasChildren().
m_parent
ITracker * Catch::TestCaseTracking::ITracker::m_parent = nullptr protected
Definition at line 9607 of file catch_amalgamated.hpp.
Referenced by Catch::TestCaseTracking::TrackerBase::fail(), ITracker(), Catch::TestCaseTracking::TrackerBase::open(), openChild(), and parent().
m_runState
CycleState Catch::TestCaseTracking::ITracker::m_runState = NotStarted protected
Definition at line 9609 of file catch_amalgamated.hpp.
Referenced by Catch::TestCaseTracking::TrackerBase::close(), Catch::TestCaseTracking::TrackerBase::fail(), hasStarted(), Catch::TestCaseTracking::TrackerBase::isComplete(), isOpen(), isSuccessfullyCompleted(), markAsNeedingAnotherRun(), Catch::TestCaseTracking::TrackerBase::open(), and openChild().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_test_case_tracker.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_test_case_tracker.cpp