libthe-seed: Catch::ReusableStringStream Class Reference
Catch::ReusableStringStream Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
ReusableStringStream ()
~ReusableStringStream ()
std::string str () const
Returns the serialized state.
void str (std::string const &str)
Sets internal state to str.
template<typename T>
auto operator<< (T const &value) -> ReusableStringStream &
auto get () -> std::ostream &
ReusableStringStream ()
~ReusableStringStream ()
std::string str () const
Returns the serialized state.
void str (std::string const &str)
Sets internal state to str.
template<typename T>
auto operator<< (T const &value) -> ReusableStringStream &
auto get () -> std::ostream &
Detailed Description
Definition at line 2509 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ReusableStringStream() [1/2]
Catch::ReusableStringStream::ReusableStringStream ()
Definition at line 5060 of file catch_amalgamated.cpp.
References get().
Referenced by operator<<().
~ReusableStringStream() [1/2]
Catch::ReusableStringStream::~ReusableStringStream ()
Definition at line 5065 of file catch_amalgamated.cpp.
References Catch::Singleton< SingletonImplT, InterfaceT, MutableInterfaceT >::getMutable(), and str().
ReusableStringStream() [2/2]
Catch::ReusableStringStream::ReusableStringStream ()
~ReusableStringStream() [2/2]
Catch::ReusableStringStream::~ReusableStringStream ()
Member Function Documentation
get() [1/2]
auto Catch::ReusableStringStream::get () ->std::ostream & inline
Definition at line 2542 of file catch_amalgamated.hpp.
Referenced by Catch::TeamCityReporter::assertionEnded(), and ReusableStringStream().
get() [2/2]
auto Catch::ReusableStringStream::get () ->std::ostream & inline
Definition at line 53 of file catch_reusable_string_stream.hpp.
operator<<() [1/2]
template<typename T> auto Catch::ReusableStringStream::operator<< (T const & value) ->ReusableStringStream & inline
Definition at line 2534 of file catch_amalgamated.hpp.
References ReusableStringStream().
operator<<() [2/2]
template<typename T> auto Catch::ReusableStringStream::operator<< (T const & value) ->ReusableStringStream & inline
Definition at line 45 of file catch_reusable_string_stream.hpp.
References ReusableStringStream().
str() [1/4]
std::string Catch::ReusableStringStream::str () const
Returns the serialized state.
Definition at line 5071 of file catch_amalgamated.cpp.
References str().
Referenced by Catch::TeamCityReporter::assertionEnded(), Catch::StringMaker< T, typename >::convert(), Catch::StringMaker< std::chrono::duration< Value, Ratio > >::convert(), Catch::StringMaker< std::chrono::duration< Value, std::ratio< 1 > > >::convert(), Catch::StringMaker< std::chrono::duration< Value, std::ratio< 3600 > > >::convert(), Catch::StringMaker< std::chrono::duration< Value, std::ratio< 60 > > >::convert(), Catch::defaultListTags(), Catch::Matchers::HasSizeMatcher::describe(), Catch::Detail::rangeToString(), Catch::rangeToString(), Catch::Detail::rawMemoryToString(), Catch::AssertionResultData::reconstructExpression(), str(), str(), Catch::ratio_string< Ratio >::symbol(), TEST_CASE(), Catch::to_string(), Catch::Approx::toString(), Catch::SonarQubeReporter::writeAssertion(), Catch::XmlWriter::writeAttribute(), and ~ReusableStringStream().
str() [2/4]
std::string Catch::ReusableStringStream::str () const
Returns the serialized state.
str() [3/4]
void Catch::ReusableStringStream::str (std::string const & str)
Sets internal state to str.
Definition at line 5075 of file catch_amalgamated.cpp.
References str().
str() [4/4]
void Catch::ReusableStringStream::str (std::string const & str)
Sets internal state to str.
References str().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_reusable_string_stream.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_reusable_string_stream.cpp