libthe-seed: Catch::BinaryExpr< LhsT, RhsT > Class Template Reference
Catch::BinaryExpr< LhsT, RhsT > Class Template Reference
#include <catch_amalgamated.hpp>
Public Member Functions
BinaryExpr (bool comparisonResult, LhsT lhs, StringRef op, RhsT rhs)
template<typename T>
auto operator&& (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator|| (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator== (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator!= (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator> (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator< (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator>= (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator<= (T) const -> BinaryExpr< LhsT, RhsT const & > const
BinaryExpr (bool comparisonResult, LhsT lhs, StringRef op, RhsT rhs)
template<typename T>
auto operator&& (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator|| (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator== (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator!= (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator> (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator< (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator>= (T) const -> BinaryExpr< LhsT, RhsT const & > const
template<typename T>
auto operator<= (T) const -> BinaryExpr< LhsT, RhsT const & > const
Public Member Functions inherited from Catch::ITransientExpression
auto isBinaryExpression () const -> bool
auto getResult () const -> bool
ITransientExpression (bool isBinaryExpression, bool result)
ITransientExpression ()=default
ITransientExpression (ITransientExpression const &)=default
ITransientExpression & operator= (ITransientExpression const &)=default
virtual ~ITransientExpression ()
auto isBinaryExpression () const -> bool
auto getResult () const -> bool
ITransientExpression (bool isBinaryExpression, bool result)
ITransientExpression ()=default
ITransientExpression (ITransientExpression const &)=default
ITransientExpression & operator= (ITransientExpression const &)=default
virtual ~ITransientExpression ()
Detailed Description
template<typename LhsT, typename RhsT>
class Catch::BinaryExpr< LhsT, RhsT >
Definition at line 5431 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
BinaryExpr() [1/2]
template<typename LhsT, typename RhsT> Catch::BinaryExpr< LhsT, RhsT >::BinaryExpr (bool comparisonResult, LhsT lhs, StringRef op, RhsT rhs) inline
Definition at line 5442 of file catch_amalgamated.hpp.
References Catch::ITransientExpression::ITransientExpression().
Referenced by operator!=(), operator&&(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and operator||().
BinaryExpr() [2/2]
template<typename LhsT, typename RhsT> Catch::BinaryExpr< LhsT, RhsT >::BinaryExpr (bool comparisonResult, LhsT lhs, StringRef op, RhsT rhs) inline
Definition at line 84 of file catch_decomposer.hpp.
References Catch::ITransientExpression::ITransientExpression().
Member Function Documentation
operator!=() [1/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator!= (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 5471 of file catch_amalgamated.hpp.
References BinaryExpr().
operator!=() [2/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator!= (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 113 of file catch_decomposer.hpp.
References BinaryExpr().
operator&&() [1/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator&& (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 5450 of file catch_amalgamated.hpp.
References BinaryExpr().
operator&&() [2/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator&& (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 92 of file catch_decomposer.hpp.
References BinaryExpr().
operator<() [1/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator< (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 5485 of file catch_amalgamated.hpp.
References BinaryExpr().
operator<() [2/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator< (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 127 of file catch_decomposer.hpp.
References BinaryExpr().
operator<=() [1/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator<= (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 5499 of file catch_amalgamated.hpp.
References BinaryExpr().
operator<=() [2/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator<= (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 141 of file catch_decomposer.hpp.
References BinaryExpr().
operator==() [1/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator== (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 5464 of file catch_amalgamated.hpp.
References BinaryExpr().
operator==() [2/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator== (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 106 of file catch_decomposer.hpp.
References BinaryExpr().
operator>() [1/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator> (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 5478 of file catch_amalgamated.hpp.
References BinaryExpr().
operator>() [2/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator> (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 120 of file catch_decomposer.hpp.
References BinaryExpr().
operator>=() [1/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator>= (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 5492 of file catch_amalgamated.hpp.
References BinaryExpr().
operator>=() [2/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator>= (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 134 of file catch_decomposer.hpp.
References BinaryExpr().
operator||() [1/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator|| (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 5457 of file catch_amalgamated.hpp.
References BinaryExpr().
operator||() [2/2]
template<typename LhsT, typename RhsT> template<typename T> auto Catch::BinaryExpr< LhsT, RhsT >::operator|| (T) const->BinaryExpr< LhsT, RhsTconst & >const inline
Definition at line 99 of file catch_decomposer.hpp.
References BinaryExpr().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_decomposer.hpp