libthe-seed: Catch::Config Class Reference
Catch::Config Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
Config ()=default
Config (ConfigData const &data)
~Config () override
bool listTests () const
bool listTags () const
bool listReporters () const
bool listListeners () const
std::vector< ReporterSpec > const & getReporterSpecs () const
std::vector< ProcessedReporterSpec > const & getProcessedReporterSpecs () const
std::vector< std::string > const & getTestsOrTags () const override
std::vector< std::string > const & getSectionsToRun () const override
TestSpec const & testSpec () const override
bool hasTestFilters () const override
bool showHelp () const
bool allowThrows () const override
StringRef name () const override
bool includeSuccessfulResults () const override
bool warnAboutMissingAssertions () const override
bool warnAboutUnmatchedTestSpecs () const override
bool zeroTestsCountAsSuccess () const override
ShowDurations showDurations () const override
double minDuration () const override
TestRunOrder runOrder () const override
uint32_t rngSeed () const override
unsigned int shardCount () const override
unsigned int shardIndex () const override
ColourMode defaultColourMode () const override
bool shouldDebugBreak () const override
int abortAfter () const override
bool showInvisibles () const override
Verbosity verbosity () const override
bool skipBenchmarks () const override
bool benchmarkNoAnalysis () const override
unsigned int benchmarkSamples () const override
double benchmarkConfidenceInterval () const override
unsigned int benchmarkResamples () const override
std::chrono::milliseconds benchmarkWarmupTime () const override
Config ()=default
Config (ConfigData const &data)
~Config () override
bool listTests () const
bool listTags () const
bool listReporters () const
bool listListeners () const
std::vector< ReporterSpec > const & getReporterSpecs () const
std::vector< ProcessedReporterSpec > const & getProcessedReporterSpecs () const
std::vector< std::string > const & getTestsOrTags () const override
std::vector< std::string > const & getSectionsToRun () const override
TestSpec const & testSpec () const override
bool hasTestFilters () const override
bool showHelp () const
bool allowThrows () const override
StringRef name () const override
bool includeSuccessfulResults () const override
bool warnAboutMissingAssertions () const override
bool warnAboutUnmatchedTestSpecs () const override
bool zeroTestsCountAsSuccess () const override
ShowDurations showDurations () const override
double minDuration () const override
TestRunOrder runOrder () const override
uint32_t rngSeed () const override
unsigned int shardCount () const override
unsigned int shardIndex () const override
ColourMode defaultColourMode () const override
bool shouldDebugBreak () const override
int abortAfter () const override
bool showInvisibles () const override
Verbosity verbosity () const override
bool skipBenchmarks () const override
bool benchmarkNoAnalysis () const override
unsigned int benchmarkSamples () const override
double benchmarkConfidenceInterval () const override
unsigned int benchmarkResamples () const override
std::chrono::milliseconds benchmarkWarmupTime () const override
Public Member Functions inherited from Catch::IConfig
virtual ~IConfig ()
virtual ~IConfig ()
Additional Inherited Members
Protected Member Functions inherited from Catch::Detail::NonCopyable
NonCopyable () noexcept=default
NonCopyable () noexcept=default
Detailed Description
Definition at line 4088 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
Config() [1/4]
Catch::Config::Config () default
References Config().
Referenced by Config().
Config() [2/4]
Catch::Config::Config (ConfigData const & data)
Definition at line 660 of file catch_amalgamated.cpp.
~Config() [1/2]
Catch::Config::~Config () override default
References abortAfter(), allowThrows(), benchmarkConfidenceInterval(), benchmarkNoAnalysis(), benchmarkResamples(), benchmarkSamples(), benchmarkWarmupTime(), defaultColourMode(), getProcessedReporterSpecs(), getReporterSpecs(), getSectionsToRun(), getTestsOrTags(), hasTestFilters(), includeSuccessfulResults(), listListeners(), listReporters(), listTags(), listTests(), minDuration(), name(), rngSeed(), runOrder(), shardCount(), shardIndex(), shouldDebugBreak(), showDurations(), showHelp(), showInvisibles(), skipBenchmarks(), testSpec(), verbosity(), warnAboutMissingAssertions(), warnAboutUnmatchedTestSpecs(), and zeroTestsCountAsSuccess().
Config() [3/4]
Catch::Config::Config () default
Config() [4/4]
Catch::Config::Config (ConfigData const & data)
~Config() [2/2]
Catch::Config::~Config () override
Member Function Documentation
abortAfter() [1/2]
int Catch::Config::abortAfter () const override virtual
Implements Catch::IConfig.
Definition at line 768 of file catch_amalgamated.cpp.
References abortAfter().
Referenced by abortAfter(), and ~Config().
abortAfter() [2/2]
int Catch::Config::abortAfter () const override virtual
Implements Catch::IConfig.
allowThrows() [1/2]
bool Catch::Config::allowThrows () const override virtual
Implements Catch::IConfig.
Definition at line 750 of file catch_amalgamated.cpp.
References allowThrows().
Referenced by allowThrows(), and ~Config().
allowThrows() [2/2]
bool Catch::Config::allowThrows () const override virtual
Implements Catch::IConfig.
benchmarkConfidenceInterval() [1/2]
double Catch::Config::benchmarkConfidenceInterval () const override virtual
Implements Catch::IConfig.
Definition at line 775 of file catch_amalgamated.cpp.
References benchmarkConfidenceInterval().
Referenced by benchmarkConfidenceInterval(), and ~Config().
benchmarkConfidenceInterval() [2/2]
double Catch::Config::benchmarkConfidenceInterval () const override virtual
Implements Catch::IConfig.
benchmarkNoAnalysis() [1/2]
bool Catch::Config::benchmarkNoAnalysis () const override virtual
Implements Catch::IConfig.
Definition at line 773 of file catch_amalgamated.cpp.
References benchmarkNoAnalysis().
Referenced by benchmarkNoAnalysis(), and ~Config().
benchmarkNoAnalysis() [2/2]
bool Catch::Config::benchmarkNoAnalysis () const override virtual
Implements Catch::IConfig.
benchmarkResamples() [1/2]
unsigned int Catch::Config::benchmarkResamples () const override virtual
Implements Catch::IConfig.
Definition at line 776 of file catch_amalgamated.cpp.
References benchmarkResamples().
Referenced by benchmarkResamples(), and ~Config().
benchmarkResamples() [2/2]
unsigned int Catch::Config::benchmarkResamples () const override virtual
Implements Catch::IConfig.
benchmarkSamples() [1/2]
unsigned int Catch::Config::benchmarkSamples () const override virtual
Implements Catch::IConfig.
Definition at line 774 of file catch_amalgamated.cpp.
References benchmarkSamples().
Referenced by benchmarkSamples(), and ~Config().
benchmarkSamples() [2/2]
unsigned int Catch::Config::benchmarkSamples () const override virtual
Implements Catch::IConfig.
benchmarkWarmupTime() [1/2]
std::chrono::milliseconds Catch::Config::benchmarkWarmupTime () const override virtual
Implements Catch::IConfig.
Definition at line 777 of file catch_amalgamated.cpp.
References benchmarkWarmupTime().
Referenced by benchmarkWarmupTime(), and ~Config().
benchmarkWarmupTime() [2/2]
std::chrono::milliseconds Catch::Config::benchmarkWarmupTime () const override virtual
Implements Catch::IConfig.
defaultColourMode() [1/2]
ColourMode Catch::Config::defaultColourMode () const override virtual
Implements Catch::IConfig.
Definition at line 766 of file catch_amalgamated.cpp.
References defaultColourMode().
Referenced by defaultColourMode(), and ~Config().
defaultColourMode() [2/2]
ColourMode Catch::Config::defaultColourMode () const override virtual
Implements Catch::IConfig.
getProcessedReporterSpecs() [1/2]
std::vector< ProcessedReporterSpec > const & Catch::Config::getProcessedReporterSpecs () const
Definition at line 740 of file catch_amalgamated.cpp.
References getProcessedReporterSpecs().
Referenced by getProcessedReporterSpecs(), and ~Config().
getProcessedReporterSpecs() [2/2]
std::vector< ProcessedReporterSpec > const & Catch::Config::getProcessedReporterSpecs () const
getReporterSpecs() [1/2]
std::vector< ReporterSpec > const & Catch::Config::getReporterSpecs () const
Definition at line 735 of file catch_amalgamated.cpp.
References getReporterSpecs().
Referenced by getReporterSpecs(), TEST_CASE(), and ~Config().
getReporterSpecs() [2/2]
std::vector< ReporterSpec > const & Catch::Config::getReporterSpecs () const
getSectionsToRun() [1/2]
std::vector< std::string > const & Catch::Config::getSectionsToRun () const override virtual
Implements Catch::IConfig.
Definition at line 733 of file catch_amalgamated.cpp.
References getSectionsToRun().
Referenced by getSectionsToRun(), and ~Config().
getSectionsToRun() [2/2]
std::vector< std::string > const & Catch::Config::getSectionsToRun () const override virtual
Implements Catch::IConfig.
getTestsOrTags() [1/2]
std::vector< std::string > const & Catch::Config::getTestsOrTags () const override virtual
Implements Catch::IConfig.
Definition at line 732 of file catch_amalgamated.cpp.
References getTestsOrTags().
Referenced by getTestsOrTags(), and ~Config().
getTestsOrTags() [2/2]
std::vector< std::string > const & Catch::Config::getTestsOrTags () const override virtual
Implements Catch::IConfig.
hasTestFilters() [1/2]
bool Catch::Config::hasTestFilters () const override virtual
Implements Catch::IConfig.
Definition at line 745 of file catch_amalgamated.cpp.
References hasTestFilters().
Referenced by hasTestFilters(), TEST_CASE(), and ~Config().
hasTestFilters() [2/2]
bool Catch::Config::hasTestFilters () const override virtual
Implements Catch::IConfig.
includeSuccessfulResults() [1/2]
bool Catch::Config::includeSuccessfulResults () const override virtual
Implements Catch::IConfig.
Definition at line 752 of file catch_amalgamated.cpp.
References includeSuccessfulResults().
Referenced by includeSuccessfulResults(), and ~Config().
includeSuccessfulResults() [2/2]
bool Catch::Config::includeSuccessfulResults () const override virtual
Implements Catch::IConfig.
listListeners() [1/2]
bool Catch::Config::listListeners () const
Definition at line 730 of file catch_amalgamated.cpp.
References listListeners().
Referenced by Catch::list(), listListeners(), and ~Config().
listListeners() [2/2]
bool Catch::Config::listListeners () const
listReporters() [1/2]
bool Catch::Config::listReporters () const
Definition at line 729 of file catch_amalgamated.cpp.
References listReporters().
Referenced by Catch::list(), listReporters(), and ~Config().
listReporters() [2/2]
bool Catch::Config::listReporters () const
listTags() [1/2]
bool Catch::Config::listTags () const
Definition at line 728 of file catch_amalgamated.cpp.
References listTags().
Referenced by Catch::list(), listTags(), and ~Config().
listTags() [2/2]
bool Catch::Config::listTags () const
listTests() [1/2]
bool Catch::Config::listTests () const
Definition at line 727 of file catch_amalgamated.cpp.
References listTests().
Referenced by Catch::list(), listTests(), and ~Config().
listTests() [2/2]
bool Catch::Config::listTests () const
minDuration() [1/2]
double Catch::Config::minDuration () const override virtual
Implements Catch::IConfig.
Definition at line 761 of file catch_amalgamated.cpp.
References minDuration().
Referenced by minDuration(), and ~Config().
minDuration() [2/2]
double Catch::Config::minDuration () const override virtual
Implements Catch::IConfig.
name() [1/2]
StringRef Catch::Config::name () const override virtual
Implements Catch::IConfig.
Definition at line 751 of file catch_amalgamated.cpp.
References name().
Referenced by name(), and ~Config().
name() [2/2]
StringRef Catch::Config::name () const override virtual
Implements Catch::IConfig.
rngSeed() [1/2]
uint32_t Catch::Config::rngSeed () const override virtual
Implements Catch::IConfig.
Definition at line 763 of file catch_amalgamated.cpp.
References rngSeed().
Referenced by rngSeed(), and ~Config().
rngSeed() [2/2]
uint32_t Catch::Config::rngSeed () const override virtual
Implements Catch::IConfig.
runOrder() [1/2]
TestRunOrder Catch::Config::runOrder () const override virtual
Implements Catch::IConfig.
Definition at line 762 of file catch_amalgamated.cpp.
References runOrder().
Referenced by runOrder(), and ~Config().
runOrder() [2/2]
TestRunOrder Catch::Config::runOrder () const override virtual
Implements Catch::IConfig.
shardCount() [1/2]
unsigned int Catch::Config::shardCount () const override virtual
Implements Catch::IConfig.
Definition at line 764 of file catch_amalgamated.cpp.
References shardCount().
Referenced by shardCount(), and ~Config().
shardCount() [2/2]
unsigned int Catch::Config::shardCount () const override virtual
Implements Catch::IConfig.
shardIndex() [1/2]
unsigned int Catch::Config::shardIndex () const override virtual
Implements Catch::IConfig.
Definition at line 765 of file catch_amalgamated.cpp.
References shardIndex().
Referenced by shardIndex(), and ~Config().
shardIndex() [2/2]
unsigned int Catch::Config::shardIndex () const override virtual
Implements Catch::IConfig.
shouldDebugBreak() [1/2]
bool Catch::Config::shouldDebugBreak () const override virtual
Implements Catch::IConfig.
Definition at line 767 of file catch_amalgamated.cpp.
References shouldDebugBreak().
Referenced by shouldDebugBreak(), and ~Config().
shouldDebugBreak() [2/2]
bool Catch::Config::shouldDebugBreak () const override virtual
Implements Catch::IConfig.
showDurations() [1/2]
ShowDurations Catch::Config::showDurations () const override virtual
Implements Catch::IConfig.
Definition at line 760 of file catch_amalgamated.cpp.
References showDurations().
Referenced by showDurations(), and ~Config().
showDurations() [2/2]
ShowDurations Catch::Config::showDurations () const override virtual
Implements Catch::IConfig.
showHelp() [1/2]
bool Catch::Config::showHelp () const
Definition at line 747 of file catch_amalgamated.cpp.
References showHelp().
Referenced by showHelp(), and ~Config().
showHelp() [2/2]
bool Catch::Config::showHelp () const
showInvisibles() [1/2]
bool Catch::Config::showInvisibles () const override virtual
Implements Catch::IConfig.
Definition at line 769 of file catch_amalgamated.cpp.
References showInvisibles().
Referenced by showInvisibles(), and ~Config().
showInvisibles() [2/2]
bool Catch::Config::showInvisibles () const override virtual
Implements Catch::IConfig.
skipBenchmarks() [1/2]
bool Catch::Config::skipBenchmarks () const override virtual
Implements Catch::IConfig.
Definition at line 772 of file catch_amalgamated.cpp.
References skipBenchmarks().
Referenced by skipBenchmarks(), and ~Config().
skipBenchmarks() [2/2]
bool Catch::Config::skipBenchmarks () const override virtual
Implements Catch::IConfig.
testSpec() [1/2]
TestSpec const & Catch::Config::testSpec () const override virtual
Implements Catch::IConfig.
Definition at line 744 of file catch_amalgamated.cpp.
References testSpec().
Referenced by testSpec(), and ~Config().
testSpec() [2/2]
TestSpec const & Catch::Config::testSpec () const override virtual
Implements Catch::IConfig.
verbosity() [1/2]
Verbosity Catch::Config::verbosity () const override virtual
Implements Catch::IConfig.
Definition at line 770 of file catch_amalgamated.cpp.
References verbosity().
Referenced by verbosity(), and ~Config().
verbosity() [2/2]
Verbosity Catch::Config::verbosity () const override virtual
Implements Catch::IConfig.
warnAboutMissingAssertions() [1/2]
bool Catch::Config::warnAboutMissingAssertions () const override virtual
Implements Catch::IConfig.
Definition at line 753 of file catch_amalgamated.cpp.
References Catch::WarnAbout::NoAssertions, and warnAboutMissingAssertions().
Referenced by warnAboutMissingAssertions(), and ~Config().
warnAboutMissingAssertions() [2/2]
bool Catch::Config::warnAboutMissingAssertions () const override virtual
Implements Catch::IConfig.
warnAboutUnmatchedTestSpecs() [1/2]
bool Catch::Config::warnAboutUnmatchedTestSpecs () const override virtual
Implements Catch::IConfig.
Definition at line 756 of file catch_amalgamated.cpp.
References Catch::WarnAbout::UnmatchedTestSpec, and warnAboutUnmatchedTestSpecs().
Referenced by warnAboutUnmatchedTestSpecs(), and ~Config().
warnAboutUnmatchedTestSpecs() [2/2]
bool Catch::Config::warnAboutUnmatchedTestSpecs () const override virtual
Implements Catch::IConfig.
zeroTestsCountAsSuccess() [1/2]
bool Catch::Config::zeroTestsCountAsSuccess () const override virtual
Implements Catch::IConfig.
Definition at line 759 of file catch_amalgamated.cpp.
References zeroTestsCountAsSuccess().
Referenced by zeroTestsCountAsSuccess(), and ~Config().
zeroTestsCountAsSuccess() [2/2]
bool Catch::Config::zeroTestsCountAsSuccess () const override virtual
Implements Catch::IConfig.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/catch_config.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/catch_config.cpp