libthe-seed: Catch::TestSpecParser Class Reference
Catch::TestSpecParser Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
TestSpecParser (ITagAliasRegistry const &tagAliases)
TestSpecParser & parse (std::string const &arg)
TestSpec testSpec ()
TestSpecParser (ITagAliasRegistry const &tagAliases)
TestSpecParser & parse (std::string const &arg)
TestSpec testSpec ()
Detailed Description
Definition at line 10192 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
TestSpecParser() [1/2]
Catch::TestSpecParser::TestSpecParser (ITagAliasRegistry const & tagAliases)
Definition at line 6603 of file catch_amalgamated.cpp.
Referenced by parse().
TestSpecParser() [2/2]
Catch::TestSpecParser::TestSpecParser (ITagAliasRegistry const & tagAliases)
Member Function Documentation
parse() [1/2]
TestSpecParser & Catch::TestSpecParser::parse (std::string const & arg)
Definition at line 6605 of file catch_amalgamated.cpp.
References TestSpecParser().
Referenced by LLVMFuzzerTestOneInput(), and Catch::parseTestSpec().
parse() [2/2]
TestSpecParser & Catch::TestSpecParser::parse (std::string const & arg)
References TestSpecParser().
testSpec() [1/2]
TestSpec Catch::TestSpecParser::testSpec ()
Definition at line 6623 of file catch_amalgamated.cpp.
References CATCH_MOVE.
Referenced by Catch::parseTestSpec().
testSpec() [2/2]
TestSpec Catch::TestSpecParser::testSpec ()
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_test_spec_parser.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_test_spec_parser.cpp