libthe-seed: clara::detail::ExeName Class Reference
clara::detail::ExeName Class Reference
#include <clara.hpp>
Public Member Functions
ExeName ()
ExeName (std::string &ref)
template<typename LambdaT>
ExeName (LambdaT const &lambda)
auto parse (std::string const &, TokenStream const &tokens) const -> InternalParseResult override
auto name () const -> std::string
auto set (std::string const &newName) -> ParserResult
Public Member Functions inherited from clara::detail::ComposableParserImpl< ExeName >
auto operator| (T const &other) const -> Parser
auto operator+ (T const &other) const -> Parser
Public Member Functions inherited from clara::detail::ParserBase
virtual ~ParserBase ()=default
virtual auto validate () const -> Result
virtual auto cardinality () const -> size_t
auto parse (Args const &args) const -> InternalParseResult
Detailed Description
Definition at line 884 of file clara.hpp.
Constructor & Destructor Documentation
ExeName() [1/3]
clara::detail::ExeName::ExeName () inline
Definition at line 894 of file clara.hpp.
Referenced by ExeName(), and ExeName().
ExeName() [2/3]
clara::detail::ExeName::ExeName (std::string & ref) inline explicit
Definition at line 896 of file clara.hpp.
References ExeName().
ExeName() [3/3]
template<typename LambdaT> clara::detail::ExeName::ExeName (LambdaT const & lambda) inline explicit
Definition at line 901 of file clara.hpp.
References ExeName().
Member Function Documentation
name()
auto clara::detail::ExeName::name () const->std::string inline
Definition at line 910 of file clara.hpp.
parse()
auto clara::detail::ExeName::parse (std::string const & , TokenStream const & tokens) const->InternalParseResult inline override virtual
Implements clara::detail::ParserBase.
Definition at line 906 of file clara.hpp.
References clara::detail::NoMatch, and clara::detail::BasicResult< ParseState >::ok().
set()
auto clara::detail::ExeName::set (std::string const & newName) ->ParserResult inline
Definition at line 911 of file clara.hpp.
References clara::detail::Matched, and clara::detail::BasicResult< ParseResultType >::ok().
The documentation for this class was generated from the following file:
external/Catch2/third_party/clara.hpp