libthe-seed: clara::detail::TokenStream Class Reference
clara::detail::TokenStream Class Reference
#include <clara.hpp>
Public Member Functions
TokenStream (Args const &args)
TokenStream (Iterator it, Iterator itEnd)
operator bool () const
auto count () const -> size_t
auto operator* () const -> Token
auto operator-> () const -> Token const *
auto operator++ () -> TokenStream &
Detailed Description
Definition at line 447 of file clara.hpp.
Constructor & Destructor Documentation
TokenStream() [1/2]
clara::detail::TokenStream::TokenStream (Args const & args) inline explicit
Definition at line 485 of file clara.hpp.
References TokenStream().
Referenced by operator++(), and TokenStream().
TokenStream() [2/2]
clara::detail::TokenStream::TokenStream (Iterator it, Iterator itEnd) inline
Definition at line 487 of file clara.hpp.
Member Function Documentation
count()
auto clara::detail::TokenStream::count () const->size_t inline
Definition at line 495 of file clara.hpp.
operator bool()
clara::detail::TokenStream::operator bool () const inline explicit
Definition at line 491 of file clara.hpp.
operator*()
auto clara::detail::TokenStream::operator* () const->Token inline
Definition at line 497 of file clara.hpp.
operator++()
auto clara::detail::TokenStream::operator++ () ->TokenStream & inline
Definition at line 507 of file clara.hpp.
References TokenStream().
operator->()
auto clara::detail::TokenStream::operator-> () const->Tokenconst * inline
Definition at line 502 of file clara.hpp.
The documentation for this class was generated from the following file:
external/Catch2/third_party/clara.hpp