libthe-seed: Catch::TextFlow::Columns::iterator Class Reference
Catch::TextFlow::Columns::iterator Class Reference
#include <catch_amalgamated.hpp>
Public Types
using difference_type = std::ptrdiff_t
using value_type = std::string
using pointer = value_type*
using reference = value_type&
using iterator_category = std::forward_iterator_tag
using difference_type = std::ptrdiff_t
using value_type = std::string
using pointer = value_type*
using reference = value_type&
using iterator_category = std::forward_iterator_tag
Public Member Functions
iterator (Columns const &columns)
auto operator== (iterator const &other) const -> bool
auto operator!= (iterator const &other) const -> bool
std::string operator* () const
iterator & operator++ ()
iterator operator++ (int)
iterator (Columns const &columns)
auto operator== (iterator const &other) const -> bool
auto operator!= (iterator const &other) const -> bool
std::string operator* () const
iterator & operator++ ()
iterator operator++ (int)
Detailed Description
Definition at line 10368 of file catch_amalgamated.hpp.
Member Typedef Documentation
difference_type [1/2]
using Catch::TextFlow::Columns::iterator::difference_type = std::ptrdiff_t
Definition at line 10379 of file catch_amalgamated.hpp.
difference_type [2/2]
using Catch::TextFlow::Columns::iterator::difference_type = std::ptrdiff_t
Definition at line 137 of file catch_textflow.hpp.
iterator_category [1/2]
using Catch::TextFlow::Columns::iterator::iterator_category = std::forward_iterator_tag
Definition at line 10383 of file catch_amalgamated.hpp.
iterator_category [2/2]
using Catch::TextFlow::Columns::iterator::iterator_category = std::forward_iterator_tag
Definition at line 141 of file catch_textflow.hpp.
pointer [1/2]
using Catch::TextFlow::Columns::iterator::pointer = value_type*
Definition at line 10381 of file catch_amalgamated.hpp.
pointer [2/2]
using Catch::TextFlow::Columns::iterator::pointer = value_type*
Definition at line 139 of file catch_textflow.hpp.
reference [1/2]
using Catch::TextFlow::Columns::iterator::reference = value_type&
Definition at line 10382 of file catch_amalgamated.hpp.
reference [2/2]
using Catch::TextFlow::Columns::iterator::reference = value_type&
Definition at line 140 of file catch_textflow.hpp.
value_type [1/2]
using Catch::TextFlow::Columns::iterator::value_type = std::string
Definition at line 10380 of file catch_amalgamated.hpp.
value_type [2/2]
using Catch::TextFlow::Columns::iterator::value_type = std::string
Definition at line 138 of file catch_textflow.hpp.
Constructor & Destructor Documentation
iterator() [1/2]
Catch::TextFlow::Columns::iterator::iterator (Columns const & columns) explicit
Definition at line 6996 of file catch_amalgamated.cpp.
iterator() [2/2]
Catch::TextFlow::Columns::iterator::iterator (Columns const & columns) explicit
Member Function Documentation
operator!=() [1/2]
auto Catch::TextFlow::Columns::iterator::operator!= (iterator const & other) const->bool inline
Definition at line 10390 of file catch_amalgamated.hpp.
operator!=() [2/2]
auto Catch::TextFlow::Columns::iterator::operator!= (iterator const & other) const->bool inline
Definition at line 148 of file catch_textflow.hpp.
operator*() [1/2]
std::string Catch::TextFlow::Columns::iterator::operator* () const
Definition at line 7006 of file catch_amalgamated.cpp.
References Catch::TextFlow::Columns::end().
operator*() [2/2]
std::string Catch::TextFlow::Columns::iterator::operator* () const
operator++() [1/4]
Columns::iterator & Catch::TextFlow::Columns::iterator::operator++ ()
Definition at line 7027 of file catch_amalgamated.cpp.
References Catch::TextFlow::Columns::end().
Referenced by operator++().
operator++() [2/4]
iterator & Catch::TextFlow::Columns::iterator::operator++ ()
operator++() [3/4]
Columns::iterator Catch::TextFlow::Columns::iterator::operator++ (int)
Definition at line 7036 of file catch_amalgamated.cpp.
References operator++().
operator++() [4/4]
iterator Catch::TextFlow::Columns::iterator::operator++ (int)
operator==() [1/2]
auto Catch::TextFlow::Columns::iterator::operator== (iterator const & other) const->bool inline
Definition at line 10387 of file catch_amalgamated.hpp.
operator==() [2/2]
auto Catch::TextFlow::Columns::iterator::operator== (iterator const & other) const->bool inline
Definition at line 145 of file catch_textflow.hpp.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_textflow.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_textflow.cpp