libthe-seed: Catch::RunContext Class Reference
Catch::RunContext Class Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
RunContext (RunContext const &)=delete
RunContext & operator= (RunContext const &)=delete
RunContext (IConfig const *_config, IEventListenerPtr &&reporter)
~RunContext () override
Totals runTest (TestCaseHandle const &testCase)
void handleExpr (AssertionInfo const &info, ITransientExpression const &expr, AssertionReaction &reaction) override
void handleMessage (AssertionInfo const &info, ResultWas::OfType resultType, StringRef message, AssertionReaction &reaction) override
void handleUnexpectedExceptionNotThrown (AssertionInfo const &info, AssertionReaction &reaction) override
void handleUnexpectedInflightException (AssertionInfo const &info, std::string &&message, AssertionReaction &reaction) override
void handleIncomplete (AssertionInfo const &info) override
void handleNonExpr (AssertionInfo const &info, ResultWas::OfType resultType, AssertionReaction &reaction) override
void notifyAssertionStarted (AssertionInfo const &info) override
bool sectionStarted (StringRef sectionName, SourceLineInfo const &sectionLineInfo, Counts &assertions) override
void sectionEnded (SectionEndInfo &&endInfo) override
void sectionEndedEarly (SectionEndInfo &&endInfo) override
IGeneratorTracker * acquireGeneratorTracker (StringRef generatorName, SourceLineInfo const &lineInfo) override
IGeneratorTracker * createGeneratorTracker (StringRef generatorName, SourceLineInfo lineInfo, Generators::GeneratorBasePtr &&generator) override
void benchmarkPreparing (StringRef name) override
void benchmarkStarting (BenchmarkInfo const &info) override
void benchmarkEnded (BenchmarkStats<> const &stats) override
void benchmarkFailed (StringRef error) override
void pushScopedMessage (MessageInfo const &message) override
void popScopedMessage (MessageInfo const &message) override
void emplaceUnscopedMessage (MessageBuilder &&builder) override
std::string getCurrentTestName () const override
const AssertionResult * getLastResult () const override
void exceptionEarlyReported () override
void handleFatalErrorCondition (StringRef message) override
bool lastAssertionPassed () override
void assertionPassed () override
bool aborting () const
RunContext (RunContext const &)=delete
RunContext & operator= (RunContext const &)=delete
RunContext (IConfig const *_config, IEventListenerPtr &&reporter)
~RunContext () override
Totals runTest (TestCaseHandle const &testCase)
void handleExpr (AssertionInfo const &info, ITransientExpression const &expr, AssertionReaction &reaction) override
void handleMessage (AssertionInfo const &info, ResultWas::OfType resultType, StringRef message, AssertionReaction &reaction) override
void handleUnexpectedExceptionNotThrown (AssertionInfo const &info, AssertionReaction &reaction) override
void handleUnexpectedInflightException (AssertionInfo const &info, std::string &&message, AssertionReaction &reaction) override
void handleIncomplete (AssertionInfo const &info) override
void handleNonExpr (AssertionInfo const &info, ResultWas::OfType resultType, AssertionReaction &reaction) override
void notifyAssertionStarted (AssertionInfo const &info) override
bool sectionStarted (StringRef sectionName, SourceLineInfo const &sectionLineInfo, Counts &assertions) override
void sectionEnded (SectionEndInfo &&endInfo) override
void sectionEndedEarly (SectionEndInfo &&endInfo) override
IGeneratorTracker * acquireGeneratorTracker (StringRef generatorName, SourceLineInfo const &lineInfo) override
IGeneratorTracker * createGeneratorTracker (StringRef generatorName, SourceLineInfo lineInfo, Generators::GeneratorBasePtr &&generator) override
void benchmarkPreparing (StringRef name) override
void benchmarkStarting (BenchmarkInfo const &info) override
void benchmarkEnded (BenchmarkStats<> const &stats) override
void benchmarkFailed (StringRef error) override
void pushScopedMessage (MessageInfo const &message) override
void popScopedMessage (MessageInfo const &message) override
void emplaceUnscopedMessage (MessageBuilder &&builder) override
std::string getCurrentTestName () const override
const AssertionResult * getLastResult () const override
void exceptionEarlyReported () override
void handleFatalErrorCondition (StringRef message) override
bool lastAssertionPassed () override
void assertionPassed () override
bool aborting () const
Public Member Functions inherited from Catch::IResultCapture
virtual ~IResultCapture ()
virtual ~IResultCapture ()
Detailed Description
Definition at line 9774 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
RunContext() [1/4]
Catch::RunContext::RunContext (RunContext const &) delete
References RunContext().
Referenced by operator=(), and RunContext().
RunContext() [2/4]
Catch::RunContext::RunContext (IConfig const * _config, IEventListenerPtr && reporter) explicit
Definition at line 5229 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::getCurrentMutableContext(), and Catch::Context::setResultCapture().
~RunContext() [1/2]
Catch::RunContext::~RunContext () override
Definition at line 5240 of file catch_amalgamated.cpp.
References aborting().
RunContext() [3/4]
Catch::RunContext::RunContext (RunContext const &) delete
References RunContext().
RunContext() [4/4]
Catch::RunContext::RunContext (IConfig const * _config, IEventListenerPtr && reporter) explicit
~RunContext() [2/2]
Catch::RunContext::~RunContext () override
Member Function Documentation
aborting() [1/2]
bool Catch::RunContext::aborting () const
Definition at line 5548 of file catch_amalgamated.cpp.
Referenced by operator=(), runTest(), and ~RunContext().
aborting() [2/2]
bool Catch::RunContext::aborting () const
acquireGeneratorTracker() [1/2]
IGeneratorTracker * Catch::RunContext::acquireGeneratorTracker (StringRef generatorName, SourceLineInfo const & lineInfo) override virtual
Implements Catch::IResultCapture.
Definition at line 5392 of file catch_amalgamated.cpp.
Referenced by operator=().
acquireGeneratorTracker() [2/2]
IGeneratorTracker * Catch::RunContext::acquireGeneratorTracker (StringRef generatorName, SourceLineInfo const & lineInfo) override virtual
Implements Catch::IResultCapture.
assertionPassed() [1/2]
void Catch::RunContext::assertionPassed () override virtual
Implements Catch::IResultCapture.
Definition at line 5541 of file catch_amalgamated.cpp.
Referenced by handleExpr(), and operator=().
assertionPassed() [2/2]
void Catch::RunContext::assertionPassed () override virtual
Implements Catch::IResultCapture.
benchmarkEnded() [1/2]
void Catch::RunContext::benchmarkEnded (BenchmarkStats<> const & stats) override virtual
Implements Catch::IResultCapture.
Definition at line 5467 of file catch_amalgamated.cpp.
Referenced by operator=().
benchmarkEnded() [2/2]
void Catch::RunContext::benchmarkEnded (BenchmarkStats<> const & stats) override virtual
Implements Catch::IResultCapture.
benchmarkFailed() [1/2]
void Catch::RunContext::benchmarkFailed (StringRef error) override virtual
Implements Catch::IResultCapture.
Definition at line 5470 of file catch_amalgamated.cpp.
Referenced by operator=().
benchmarkFailed() [2/2]
void Catch::RunContext::benchmarkFailed (StringRef error) override virtual
Implements Catch::IResultCapture.
benchmarkPreparing() [1/2]
void Catch::RunContext::benchmarkPreparing (StringRef name) override virtual
Implements Catch::IResultCapture.
Definition at line 5461 of file catch_amalgamated.cpp.
Referenced by operator=().
benchmarkPreparing() [2/2]
void Catch::RunContext::benchmarkPreparing (StringRef name) override virtual
Implements Catch::IResultCapture.
benchmarkStarting() [1/2]
void Catch::RunContext::benchmarkStarting (BenchmarkInfo const & info) override virtual
Implements Catch::IResultCapture.
Definition at line 5464 of file catch_amalgamated.cpp.
Referenced by operator=().
benchmarkStarting() [2/2]
void Catch::RunContext::benchmarkStarting (BenchmarkInfo const & info) override virtual
Implements Catch::IResultCapture.
createGeneratorTracker() [1/2]
IGeneratorTracker * Catch::RunContext::createGeneratorTracker (StringRef generatorName, SourceLineInfo lineInfo, Generators::GeneratorBasePtr && generator) override virtual
Implements Catch::IResultCapture.
Definition at line 5403 of file catch_amalgamated.cpp.
References CATCH_MOVE, and Catch::Detail::make_unique().
Referenced by operator=().
createGeneratorTracker() [2/2]
IGeneratorTracker * Catch::RunContext::createGeneratorTracker (StringRef generatorName, SourceLineInfo lineInfo, Generators::GeneratorBasePtr && generator) override virtual
Implements Catch::IResultCapture.
emplaceUnscopedMessage() [1/2]
void Catch::RunContext::emplaceUnscopedMessage (MessageBuilder && builder) override virtual
Implements Catch::IResultCapture.
Definition at line 5482 of file catch_amalgamated.cpp.
References CATCH_MOVE.
Referenced by operator=().
emplaceUnscopedMessage() [2/2]
void Catch::RunContext::emplaceUnscopedMessage (MessageBuilder && builder) override virtual
Implements Catch::IResultCapture.
exceptionEarlyReported() [1/2]
void Catch::RunContext::exceptionEarlyReported () override virtual
Implements Catch::IResultCapture.
Definition at line 5496 of file catch_amalgamated.cpp.
Referenced by operator=().
exceptionEarlyReported() [2/2]
void Catch::RunContext::exceptionEarlyReported () override virtual
Implements Catch::IResultCapture.
getCurrentTestName() [1/2]
std::string Catch::RunContext::getCurrentTestName () const override virtual
Implements Catch::IResultCapture.
Definition at line 5486 of file catch_amalgamated.cpp.
Referenced by operator=().
getCurrentTestName() [2/2]
std::string Catch::RunContext::getCurrentTestName () const override virtual
Implements Catch::IResultCapture.
getLastResult() [1/2]
const AssertionResult * Catch::RunContext::getLastResult () const override virtual
Implements Catch::IResultCapture.
Definition at line 5492 of file catch_amalgamated.cpp.
Referenced by operator=().
getLastResult() [2/2]
const AssertionResult * Catch::RunContext::getLastResult () const override virtual
Implements Catch::IResultCapture.
handleExpr() [1/2]
void Catch::RunContext::handleExpr (AssertionInfo const & info, ITransientExpression const & expr, AssertionReaction & reaction) override virtual
Implements Catch::IResultCapture.
Definition at line 5627 of file catch_amalgamated.cpp.
References assertionPassed(), Catch::ResultWas::ExpressionFailed, Catch::ITransientExpression::getResult(), Catch::isFalseTest(), Catch::ResultWas::Ok, and Catch::AssertionInfo::resultDisposition.
Referenced by operator=().
handleExpr() [2/2]
void Catch::RunContext::handleExpr (AssertionInfo const & info, ITransientExpression const & expr, AssertionReaction & reaction) override virtual
Implements Catch::IResultCapture.
handleFatalErrorCondition() [1/2]
void Catch::RunContext::handleFatalErrorCondition (StringRef message) override virtual
Implements Catch::IResultCapture.
Definition at line 5500 of file catch_amalgamated.cpp.
References Catch::Totals::assertions, CATCH_MOVE, Catch::Counts::failed, Catch::ResultWas::FatalErrorCondition, Catch::AssertionResultData::message, and Catch::Totals::testCases.
Referenced by operator=().
handleFatalErrorCondition() [2/2]
void Catch::RunContext::handleFatalErrorCondition (StringRef message) override virtual
Implements Catch::IResultCapture.
handleIncomplete() [1/2]
void Catch::RunContext::handleIncomplete (AssertionInfo const & info) override virtual
Implements Catch::IResultCapture.
Definition at line 5712 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::AssertionResultData::message, and Catch::ResultWas::ThrewException.
Referenced by operator=().
handleIncomplete() [2/2]
void Catch::RunContext::handleIncomplete (AssertionInfo const & info) override virtual
Implements Catch::IResultCapture.
handleMessage() [1/2]
void Catch::RunContext::handleMessage (AssertionInfo const & info, ResultWas::OfType resultType, StringRef message, AssertionReaction & reaction) override virtual
Implements Catch::IResultCapture.
Definition at line 5663 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::ResultWas::ExplicitSkip, Catch::AssertionResult::isOk(), Catch::isOk(), Catch::AssertionResultData::message, and Catch::AssertionReaction::shouldSkip.
Referenced by operator=().
handleMessage() [2/2]
void Catch::RunContext::handleMessage (AssertionInfo const & info, ResultWas::OfType resultType, StringRef message, AssertionReaction & reaction) override virtual
Implements Catch::IResultCapture.
handleNonExpr() [1/2]
void Catch::RunContext::handleNonExpr (AssertionInfo const & info, ResultWas::OfType resultType, AssertionReaction & reaction) override virtual
Implements Catch::IResultCapture.
Definition at line 5723 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::AssertionResult::isOk(), and Catch::isOk().
Referenced by handleUnexpectedExceptionNotThrown(), and operator=().
handleNonExpr() [2/2]
void Catch::RunContext::handleNonExpr (AssertionInfo const & info, ResultWas::OfType resultType, AssertionReaction & reaction) override virtual
Implements Catch::IResultCapture.
handleUnexpectedExceptionNotThrown() [1/2]
void Catch::RunContext::handleUnexpectedExceptionNotThrown (AssertionInfo const & info, AssertionReaction & reaction) override virtual
Implements Catch::IResultCapture.
Definition at line 5686 of file catch_amalgamated.cpp.
References Catch::ResultWas::DidntThrowException, and handleNonExpr().
Referenced by operator=().
handleUnexpectedExceptionNotThrown() [2/2]
void Catch::RunContext::handleUnexpectedExceptionNotThrown (AssertionInfo const & info, AssertionReaction & reaction) override virtual
Implements Catch::IResultCapture.
handleUnexpectedInflightException() [1/2]
void Catch::RunContext::handleUnexpectedInflightException (AssertionInfo const & info, std::string && message, AssertionReaction & reaction) override virtual
Implements Catch::IResultCapture.
Definition at line 5693 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::AssertionResultData::message, and Catch::ResultWas::ThrewException.
Referenced by operator=().
handleUnexpectedInflightException() [2/2]
void Catch::RunContext::handleUnexpectedInflightException (AssertionInfo const & info, std::string && message, AssertionReaction & reaction) override virtual
Implements Catch::IResultCapture.
lastAssertionPassed() [1/2]
bool Catch::RunContext::lastAssertionPassed () override virtual
Implements Catch::IResultCapture.
Definition at line 5537 of file catch_amalgamated.cpp.
Referenced by operator=().
lastAssertionPassed() [2/2]
bool Catch::RunContext::lastAssertionPassed () override virtual
Implements Catch::IResultCapture.
notifyAssertionStarted() [1/2]
void Catch::RunContext::notifyAssertionStarted (AssertionInfo const & info) override virtual
Implements Catch::IResultCapture.
Definition at line 5366 of file catch_amalgamated.cpp.
Referenced by operator=().
notifyAssertionStarted() [2/2]
void Catch::RunContext::notifyAssertionStarted (AssertionInfo const & info) override virtual
Implements Catch::IResultCapture.
operator=() [1/2]
RunContext & Catch::RunContext::operator= (RunContext const &) delete
References aborting(), acquireGeneratorTracker(), assertionPassed(), benchmarkEnded(), benchmarkFailed(), benchmarkPreparing(), benchmarkStarting(), createGeneratorTracker(), emplaceUnscopedMessage(), exceptionEarlyReported(), getCurrentTestName(), getLastResult(), handleExpr(), handleFatalErrorCondition(), handleIncomplete(), handleMessage(), handleNonExpr(), handleUnexpectedExceptionNotThrown(), handleUnexpectedInflightException(), lastAssertionPassed(), notifyAssertionStarted(), popScopedMessage(), pushScopedMessage(), RunContext(), runTest(), sectionEnded(), sectionEndedEarly(), and sectionStarted().
operator=() [2/2]
RunContext & Catch::RunContext::operator= (RunContext const &) delete
References RunContext().
popScopedMessage() [1/2]
void Catch::RunContext::popScopedMessage (MessageInfo const & message) override virtual
Implements Catch::IResultCapture.
Definition at line 5478 of file catch_amalgamated.cpp.
Referenced by operator=().
popScopedMessage() [2/2]
void Catch::RunContext::popScopedMessage (MessageInfo const & message) override virtual
Implements Catch::IResultCapture.
pushScopedMessage() [1/2]
void Catch::RunContext::pushScopedMessage (MessageInfo const & message) override virtual
Implements Catch::IResultCapture.
Definition at line 5474 of file catch_amalgamated.cpp.
Referenced by operator=().
pushScopedMessage() [2/2]
void Catch::RunContext::pushScopedMessage (MessageInfo const & message) override virtual
Implements Catch::IResultCapture.
runTest() [1/2]
Totals Catch::RunContext::runTest (TestCaseHandle const & testCase)
Definition at line 5244 of file catch_amalgamated.cpp.
References aborting(), Catch::SectionTracker::acquire(), Catch::Totals::assertions, CATCH_MOVE, Catch::Totals::delta(), Catch::Counts::failed, Catch::TestCaseHandle::getTestCaseInfo(), Catch::TestCaseTracking::ITracker::isSectionTracker(), Catch::Counts::passed, Catch::seedRng(), and Catch::Totals::testCases.
Referenced by operator=().
runTest() [2/2]
Totals Catch::RunContext::runTest (TestCaseHandle const & testCase)
sectionEnded() [1/2]
void Catch::RunContext::sectionEnded (SectionEndInfo && endInfo) override virtual
Implements Catch::IResultCapture.
Definition at line 5436 of file catch_amalgamated.cpp.
References CATCH_MOVE.
Referenced by operator=().
sectionEnded() [2/2]
void Catch::RunContext::sectionEnded (SectionEndInfo && endInfo) override virtual
Implements Catch::IResultCapture.
sectionEndedEarly() [1/2]
void Catch::RunContext::sectionEndedEarly (SectionEndInfo && endInfo) override virtual
Implements Catch::IResultCapture.
Definition at line 5450 of file catch_amalgamated.cpp.
References CATCH_MOVE.
Referenced by operator=().
sectionEndedEarly() [2/2]
void Catch::RunContext::sectionEndedEarly (SectionEndInfo && endInfo) override virtual
Implements Catch::IResultCapture.
sectionStarted() [1/2]
bool Catch::RunContext::sectionStarted (StringRef sectionName, SourceLineInfo const & sectionLineInfo, Counts & assertions) override virtual
Implements Catch::IResultCapture.
Definition at line 5370 of file catch_amalgamated.cpp.
References Catch::SectionTracker::acquire(), Catch::TestCaseTracking::ITracker::isOpen(), and Catch::SectionInfo::lineInfo.
Referenced by operator=().
sectionStarted() [2/2]
bool Catch::RunContext::sectionStarted (StringRef sectionName, SourceLineInfo const & sectionLineInfo, Counts & assertions) override virtual
Implements Catch::IResultCapture.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_run_context.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_run_context.cpp