libthe-seed: clara::detail::ParserBase Class Reference
clara::detail::ParserBase Class Reference abstract
#include <clara.hpp>
Public Member Functions
virtual ~ParserBase ()=default
virtual auto validate () const -> Result
virtual auto parse (std::string const &exeName, TokenStream const &tokens) const -> InternalParseResult=0
virtual auto cardinality () const -> size_t
auto parse (Args const &args) const -> InternalParseResult
Detailed Description
Definition at line 809 of file clara.hpp.
Constructor & Destructor Documentation
~ParserBase()
virtual clara::detail::ParserBase::~ParserBase () virtual default
Member Function Documentation
cardinality()
virtual auto clara::detail::ParserBase::cardinality () const->size_t inline virtual
Reimplemented in clara::detail::ParserRefImpl< DerivedT >, clara::detail::ParserRefImpl< Arg >, and clara::detail::ParserRefImpl< Opt >.
Definition at line 814 of file clara.hpp.
parse() [1/2]
auto clara::detail::ParserBase::parse (Args const & args) const->InternalParseResult inline
Definition at line 816 of file clara.hpp.
References parse().
parse() [2/2]
virtual auto clara::detail::ParserBase::parse (std::string const & exeName, TokenStream const & tokens) const->InternalParseResult pure virtual
Implemented in clara::detail::Arg, clara::detail::ExeName, clara::detail::Opt, clara::detail::Parser, clara::Opt, and clara::Parser.
Referenced by parse().
validate()
virtual auto clara::detail::ParserBase::validate () const->Result inline virtual
Reimplemented in clara::detail::Opt, clara::detail::Parser, clara::Opt, and clara::Parser.
Definition at line 812 of file clara.hpp.
References clara::detail::BasicResult< void >::ok().
Referenced by clara::detail::Arg::parse(), and clara::detail::Opt::validate().
The documentation for this class was generated from the following file:
external/Catch2/third_party/clara.hpp