libthe-seed: Catch::ExprLhs< LhsT > Class Template Reference
Catch::ExprLhs< LhsT > Class Template Reference
#include <catch_amalgamated.hpp>
Public Member Functions
ExprLhs (LhsT lhs)
auto makeUnaryExpr () const -> UnaryExpr< LhsT >
ExprLhs (LhsT lhs)
auto makeUnaryExpr () const -> UnaryExpr< LhsT >
Friends
template<typename RhsT>
auto operator&& (ExprLhs &&, RhsT &&) -> BinaryExpr< LhsT, RhsT const & >
template<typename RhsT>
auto operator|| (ExprLhs &&, RhsT &&) -> BinaryExpr< LhsT, RhsT const & >
template<typename RhsT>
auto operator&& (ExprLhs &&, RhsT &&) -> BinaryExpr< LhsT, RhsT const & >
template<typename RhsT>
auto operator|| (ExprLhs &&, RhsT &&) -> BinaryExpr< LhsT, RhsT const & >
Detailed Description
template<typename LhsT>
class Catch::ExprLhs< LhsT >
Definition at line 5523 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ExprLhs() [1/2]
template<typename LhsT> Catch::ExprLhs< LhsT >::ExprLhs (LhsT lhs) inline explicit
Definition at line 5526 of file catch_amalgamated.hpp.
Referenced by operator&&, and operator||.
ExprLhs() [2/2]
template<typename LhsT> Catch::ExprLhs< LhsT >::ExprLhs (LhsT lhs) inline explicit
Definition at line 168 of file catch_decomposer.hpp.
Member Function Documentation
makeUnaryExpr() [1/2]
template<typename LhsT> auto Catch::ExprLhs< LhsT >::makeUnaryExpr () const->UnaryExpr< LhsT > inline
Definition at line 5670 of file catch_amalgamated.hpp.
Referenced by Catch::AssertionHandler::handleExpr().
makeUnaryExpr() [2/2]
template<typename LhsT> auto Catch::ExprLhs< LhsT >::makeUnaryExpr () const->UnaryExpr< LhsT > inline
Definition at line 312 of file catch_decomposer.hpp.
Friends And Related Symbol Documentation
operator&& [1/2]
template<typename LhsT> template<typename RhsT> auto operator&& (ExprLhs< LhsT > && , RhsT &&)->BinaryExpr< LhsT, RhsTconst & > friend
Definition at line 5657 of file catch_amalgamated.hpp.
References ExprLhs().
operator&& [2/2]
template<typename LhsT> template<typename RhsT> auto operator&& (ExprLhs< LhsT > && , RhsT &&)->BinaryExpr< LhsT, RhsTconst & > friend
Definition at line 299 of file catch_decomposer.hpp.
References ExprLhs().
operator|| [1/2]
template<typename LhsT> template<typename RhsT> auto operator|| (ExprLhs< LhsT > && , RhsT &&)->BinaryExpr< LhsT, RhsTconst & > friend
Definition at line 5664 of file catch_amalgamated.hpp.
References ExprLhs().
operator|| [2/2]
template<typename LhsT> template<typename RhsT> auto operator|| (ExprLhs< LhsT > && , RhsT &&)->BinaryExpr< LhsT, RhsTconst & > friend
Definition at line 306 of file catch_decomposer.hpp.
References ExprLhs().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_decomposer.hpp