libthe-seed: Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs > Class Template Reference
Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs > Class Template Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
MatchAnyOfGeneric (MatchAnyOfGeneric const &)=delete
MatchAnyOfGeneric & operator= (MatchAnyOfGeneric const &)=delete
MatchAnyOfGeneric (MatchAnyOfGeneric &&)=default
MatchAnyOfGeneric & operator= (MatchAnyOfGeneric &&)=default
MatchAnyOfGeneric (MatcherTs const &... matchers)
MatchAnyOfGeneric (std::array< void const *, sizeof...(MatcherTs)> matchers)
template<typename Arg>
bool match (Arg &&arg) const
std::string describe () const override
MatchAnyOfGeneric (MatchAnyOfGeneric const &)=delete
MatchAnyOfGeneric & operator= (MatchAnyOfGeneric const &)=delete
MatchAnyOfGeneric (MatchAnyOfGeneric &&)=default
MatchAnyOfGeneric & operator= (MatchAnyOfGeneric &&)=default
MatchAnyOfGeneric (MatcherTs const &... matchers)
MatchAnyOfGeneric (std::array< void const *, sizeof...(MatcherTs)> matchers)
template<typename Arg>
bool match (Arg &&arg) const
std::string describe () const override
Public Member Functions inherited from Catch::Matchers::MatcherGenericBase
MatcherGenericBase ()=default
~MatcherGenericBase () override
MatcherGenericBase (MatcherGenericBase const &)=default
MatcherGenericBase (MatcherGenericBase &&)=default
MatcherGenericBase & operator= (MatcherGenericBase const &)=delete
MatcherGenericBase & operator= (MatcherGenericBase &&)=delete
MatcherGenericBase ()=default
~MatcherGenericBase () override
MatcherGenericBase (MatcherGenericBase const &)=default
MatcherGenericBase (MatcherGenericBase &&)=default
MatcherGenericBase & operator= (MatcherGenericBase const &)=delete
MatcherGenericBase & operator= (MatcherGenericBase &&)=delete
Public Member Functions inherited from Catch::Matchers::MatcherUntypedBase
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
Public Attributes
std::array< void const *, sizeof...(MatcherTs)> m_matchers
Friends
template<typename... MatchersRHS>
MatchAnyOfGeneric< MatcherTs..., MatchersRHS... > operator|| (MatchAnyOfGeneric< MatcherTs... > &&lhs, MatchAnyOfGeneric< MatchersRHS... > &&rhs)
Avoids type nesting for GenericAnyOf || GenericAnyOf case.
template<typename MatcherRHS>
std::enable_if_t< is_matcher< MatcherRHS >::value, MatchAnyOfGeneric< MatcherTs..., MatcherRHS > > operator|| (MatchAnyOfGeneric< MatcherTs... > &&lhs, MatcherRHS const &rhs)
Avoids type nesting for GenericAnyOf || some matcher case.
template<typename MatcherLHS>
std::enable_if_t< is_matcher< MatcherLHS >::value, MatchAnyOfGeneric< MatcherLHS, MatcherTs... > > operator|| (MatcherLHS const &lhs, MatchAnyOfGeneric< MatcherTs... > &&rhs)
Avoids type nesting for some matcher || GenericAnyOf case.
template<typename... MatchersRHS>
MatchAnyOfGeneric< MatcherTs..., MatchersRHS... > operator|| (MatchAnyOfGeneric< MatcherTs... > &&lhs, MatchAnyOfGeneric< MatchersRHS... > &&rhs)
Avoids type nesting for GenericAnyOf || GenericAnyOf case.
template<typename MatcherRHS>
std::enable_if_t< is_matcher< MatcherRHS >::value, MatchAnyOfGeneric< MatcherTs..., MatcherRHS > > operator|| (MatchAnyOfGeneric< MatcherTs... > &&lhs, MatcherRHS const &rhs)
Avoids type nesting for GenericAnyOf || some matcher case.
template<typename MatcherLHS>
std::enable_if_t< is_matcher< MatcherLHS >::value, MatchAnyOfGeneric< MatcherLHS, MatcherTs... > > operator|| (MatcherLHS const &lhs, MatchAnyOfGeneric< MatcherTs... > &&rhs)
Avoids type nesting for some matcher || GenericAnyOf case.
Additional Inherited Members
Protected Member Functions inherited from Catch::Matchers::MatcherUntypedBase
virtual ~MatcherUntypedBase ()
virtual ~MatcherUntypedBase ()
Protected Attributes inherited from Catch::Matchers::MatcherUntypedBase
std::string m_cachedToString
Detailed Description
template<typename... MatcherTs>
class Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >
Definition at line 11074 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
MatchAnyOfGeneric() [1/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::MatchAnyOfGeneric (MatchAnyOfGeneric< MatcherTs > const &) delete
References MatchAnyOfGeneric().
Referenced by MatchAnyOfGeneric(), MatchAnyOfGeneric(), operator=(), operator=(), operator||, operator||, and operator||.
MatchAnyOfGeneric() [2/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::MatchAnyOfGeneric (MatchAnyOfGeneric< MatcherTs > &&) default
References MatchAnyOfGeneric().
MatchAnyOfGeneric() [3/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::MatchAnyOfGeneric (MatcherTs const &... matchers) inline
Definition at line 11081 of file catch_amalgamated.hpp.
References m_matchers.
MatchAnyOfGeneric() [4/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::MatchAnyOfGeneric (std::array< void const *, sizeof...(MatcherTs)> matchers) inline explicit
Definition at line 11082 of file catch_amalgamated.hpp.
References m_matchers.
MatchAnyOfGeneric() [5/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::MatchAnyOfGeneric (MatchAnyOfGeneric< MatcherTs > const &) delete
References MatchAnyOfGeneric().
MatchAnyOfGeneric() [6/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::MatchAnyOfGeneric (MatchAnyOfGeneric< MatcherTs > &&) default
References MatchAnyOfGeneric().
MatchAnyOfGeneric() [7/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::MatchAnyOfGeneric (MatcherTs const &... matchers) inline
Definition at line 172 of file catch_matchers_templated.hpp.
References m_matchers.
MatchAnyOfGeneric() [8/8]
template<typename... MatcherTs> Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::MatchAnyOfGeneric (std::array< void const *, sizeof...(MatcherTs)> matchers) inline explicit
Definition at line 173 of file catch_matchers_templated.hpp.
References m_matchers.
Member Function Documentation
describe() [1/2]
template<typename... MatcherTs> std::string Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 11089 of file catch_amalgamated.hpp.
References Catch::Matchers::Detail::describe_multi_matcher(), and m_matchers.
describe() [2/2]
template<typename... MatcherTs> std::string Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 180 of file catch_matchers_templated.hpp.
References Catch::Matchers::Detail::describe_multi_matcher(), and m_matchers.
match() [1/2]
template<typename... MatcherTs> template<typename Arg> bool Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::match (Arg && arg) const inline
Definition at line 11085 of file catch_amalgamated.hpp.
References m_matchers, and Catch::Matchers::Detail::match_any_of().
match() [2/2]
template<typename... MatcherTs> template<typename Arg> bool Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::match (Arg && arg) const inline
Definition at line 176 of file catch_matchers_templated.hpp.
References m_matchers, and Catch::Matchers::Detail::match_any_of().
operator=() [1/4]
template<typename... MatcherTs> MatchAnyOfGeneric & Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::operator= (MatchAnyOfGeneric< MatcherTs > &&) default
References MatchAnyOfGeneric().
operator=() [2/4]
template<typename... MatcherTs> MatchAnyOfGeneric & Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::operator= (MatchAnyOfGeneric< MatcherTs > &&) default
References MatchAnyOfGeneric().
operator=() [3/4]
template<typename... MatcherTs> MatchAnyOfGeneric & Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::operator= (MatchAnyOfGeneric< MatcherTs > const &) delete
References MatchAnyOfGeneric().
operator=() [4/4]
template<typename... MatcherTs> MatchAnyOfGeneric & Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::operator= (MatchAnyOfGeneric< MatcherTs > const &) delete
References MatchAnyOfGeneric().
Friends And Related Symbol Documentation
operator|| [1/6]
template<typename... MatcherTs> template<typename... MatchersRHS> MatchAnyOfGeneric< MatcherTs..., MatchersRHS... > operator|| (MatchAnyOfGeneric< MatcherTs... > && lhs, MatchAnyOfGeneric< MatchersRHS... > && rhs) friend
Avoids type nesting for GenericAnyOf || GenericAnyOf case.
Definition at line 11101 of file catch_amalgamated.hpp.
References Catch::Matchers::Detail::array_cat(), CATCH_MOVE, and MatchAnyOfGeneric().
operator|| [2/6]
template<typename... MatcherTs> template<typename... MatchersRHS> MatchAnyOfGeneric< MatcherTs..., MatchersRHS... > operator|| (MatchAnyOfGeneric< MatcherTs... > && lhs, MatchAnyOfGeneric< MatchersRHS... > && rhs) friend
Avoids type nesting for GenericAnyOf || GenericAnyOf case.
Definition at line 192 of file catch_matchers_templated.hpp.
References Catch::Matchers::Detail::array_cat(), CATCH_MOVE, and MatchAnyOfGeneric().
operator|| [3/6]
template<typename... MatcherTs> template<typename MatcherRHS> std::enable_if_t< is_matcher< MatcherRHS >::value, MatchAnyOfGeneric< MatcherTs..., MatcherRHS > > operator|| (MatchAnyOfGeneric< MatcherTs... > && lhs, MatcherRHS const & rhs) friend
Avoids type nesting for GenericAnyOf || some matcher case.
Definition at line 11110 of file catch_amalgamated.hpp.
References Catch::Matchers::Detail::array_cat(), CATCH_MOVE, and MatchAnyOfGeneric().
operator|| [4/6]
template<typename... MatcherTs> template<typename MatcherRHS> std::enable_if_t< is_matcher< MatcherRHS >::value, MatchAnyOfGeneric< MatcherTs..., MatcherRHS > > operator|| (MatchAnyOfGeneric< MatcherTs... > && lhs, MatcherRHS const & rhs) friend
Avoids type nesting for GenericAnyOf || some matcher case.
Definition at line 201 of file catch_matchers_templated.hpp.
References Catch::Matchers::Detail::array_cat(), CATCH_MOVE, and MatchAnyOfGeneric().
operator|| [5/6]
template<typename... MatcherTs> template<typename MatcherLHS> std::enable_if_t< is_matcher< MatcherLHS >::value, MatchAnyOfGeneric< MatcherLHS, MatcherTs... > > operator|| (MatcherLHS const & lhs, MatchAnyOfGeneric< MatcherTs... > && rhs) friend
Avoids type nesting for some matcher || GenericAnyOf case.
Definition at line 11119 of file catch_amalgamated.hpp.
References Catch::Matchers::Detail::array_cat(), CATCH_MOVE, and MatchAnyOfGeneric().
operator|| [6/6]
template<typename... MatcherTs> template<typename MatcherLHS> std::enable_if_t< is_matcher< MatcherLHS >::value, MatchAnyOfGeneric< MatcherLHS, MatcherTs... > > operator|| (MatcherLHS const & lhs, MatchAnyOfGeneric< MatcherTs... > && rhs) friend
Avoids type nesting for some matcher || GenericAnyOf case.
Definition at line 210 of file catch_matchers_templated.hpp.
References Catch::Matchers::Detail::array_cat(), CATCH_MOVE, and MatchAnyOfGeneric().
Member Data Documentation
m_matchers
template<typename... MatcherTs> std::array< void const *, sizeof...(MatcherTs)> Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::m_matchers
Definition at line 11097 of file catch_amalgamated.hpp.
Referenced by describe(), match(), MatchAnyOfGeneric(), and MatchAnyOfGeneric().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/matchers/catch_matchers_templated.hpp