libthe-seed: Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality > Class Template Reference
Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality > Class Template Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
template<typename TargetRangeLike2, typename Equality2>
UnorderedRangeEqualsMatcher (TargetRangeLike2 &&range, Equality2 &&predicate)
template<typename RangeLike>
bool match (RangeLike &&rng) const
std::string describe () const override
template<typename TargetRangeLike2, typename Equality2>
UnorderedRangeEqualsMatcher (TargetRangeLike2 &&range, Equality2 &&predicate)
template<typename RangeLike>
bool match (RangeLike &&rng) const
std::string describe () const override
Public Member Functions inherited from Catch::Matchers::MatcherGenericBase
MatcherGenericBase ()=default
~MatcherGenericBase () override
MatcherGenericBase (MatcherGenericBase const &)=default
MatcherGenericBase (MatcherGenericBase &&)=default
MatcherGenericBase & operator= (MatcherGenericBase const &)=delete
MatcherGenericBase & operator= (MatcherGenericBase &&)=delete
MatcherGenericBase ()=default
~MatcherGenericBase () override
MatcherGenericBase (MatcherGenericBase const &)=default
MatcherGenericBase (MatcherGenericBase &&)=default
MatcherGenericBase & operator= (MatcherGenericBase const &)=delete
MatcherGenericBase & operator= (MatcherGenericBase &&)=delete
Public Member Functions inherited from Catch::Matchers::MatcherUntypedBase
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
Additional Inherited Members
Protected Member Functions inherited from Catch::Matchers::MatcherUntypedBase
virtual ~MatcherUntypedBase ()
virtual ~MatcherUntypedBase ()
Protected Attributes inherited from Catch::Matchers::MatcherUntypedBase
std::string m_cachedToString
Detailed Description
template<typename TargetRangeLike, typename Equality>
class Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >
Matcher for checking that an element contains the same elements (but not necessarily in the same order)
Definition at line 11785 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
UnorderedRangeEqualsMatcher() [1/2]
template<typename TargetRangeLike, typename Equality> template<typename TargetRangeLike2, typename Equality2> Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >::UnorderedRangeEqualsMatcher (TargetRangeLike2 && range, Equality2 && predicate) inline
Definition at line 11791 of file catch_amalgamated.hpp.
References CATCH_FORWARD.
UnorderedRangeEqualsMatcher() [2/2]
template<typename TargetRangeLike, typename Equality> template<typename TargetRangeLike2, typename Equality2> Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >::UnorderedRangeEqualsMatcher (TargetRangeLike2 && range, Equality2 && predicate) inline
Definition at line 69 of file catch_matchers_range_equals.hpp.
References CATCH_FORWARD.
Member Function Documentation
describe() [1/2]
template<typename TargetRangeLike, typename Equality> std::string Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 11807 of file catch_amalgamated.hpp.
References Catch::Detail::stringify().
describe() [2/2]
template<typename TargetRangeLike, typename Equality> std::string Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >::describe () const inline override virtual
Implements Catch::Matchers::MatcherUntypedBase.
Definition at line 85 of file catch_matchers_range_equals.hpp.
References Catch::Detail::stringify().
match() [1/2]
template<typename TargetRangeLike, typename Equality> template<typename RangeLike> bool Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >::match (RangeLike && rng) const inline
Definition at line 11797 of file catch_amalgamated.hpp.
References Catch::Detail::is_permutation().
match() [2/2]
template<typename TargetRangeLike, typename Equality> template<typename RangeLike> bool Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >::match (RangeLike && rng) const inline
Definition at line 75 of file catch_matchers_range_equals.hpp.
References Catch::Detail::is_permutation().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/matchers/catch_matchers_range_equals.hpp