libthe-seed: Catch::FatalConditionHandler Class Reference
Catch::FatalConditionHandler Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
FatalConditionHandler ()
~FatalConditionHandler ()
void engage ()
void disengage () noexcept
FatalConditionHandler ()
~FatalConditionHandler ()
void engage ()
void disengage () noexcept
Detailed Description
Wrapper for platform-specific fatal error (signals/SEH) handlers
Tries to be cooperative with other handlers, and not step over other handlers. This means that unknown structured exceptions are passed on, previous signal handlers are called, and so on.
Can only be instantiated once, and assumes that once a signal is caught, the binary will end up terminating. Thus, there
Definition at line 8947 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
FatalConditionHandler() [1/2]
Catch::FatalConditionHandler::FatalConditionHandler () default
Definition at line 4021 of file catch_amalgamated.cpp.
Referenced by FatalConditionHandler(), and ~FatalConditionHandler().
~FatalConditionHandler() [1/2]
Catch::FatalConditionHandler::~FatalConditionHandler () default
Definition at line 4029 of file catch_amalgamated.cpp.
FatalConditionHandler() [2/2]
Catch::FatalConditionHandler::FatalConditionHandler ()
References FatalConditionHandler().
~FatalConditionHandler() [2/2]
Catch::FatalConditionHandler::~FatalConditionHandler ()
References FatalConditionHandler().
Member Function Documentation
disengage() [1/2]
void Catch::FatalConditionHandler::disengage () inline noexcept
Definition at line 8966 of file catch_amalgamated.hpp.
disengage() [2/2]
void Catch::FatalConditionHandler::disengage () inline noexcept
Definition at line 47 of file catch_fatal_condition_handler.hpp.
engage() [1/2]
void Catch::FatalConditionHandler::engage () inline
Definition at line 8960 of file catch_amalgamated.hpp.
Referenced by engage().
engage() [2/2]
void Catch::FatalConditionHandler::engage () inline
Definition at line 41 of file catch_fatal_condition_handler.hpp.
References engage().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_fatal_condition_handler.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_fatal_condition_handler.cpp