libthe-seed: Catch::TagAliasRegistry Class Reference
Catch::TagAliasRegistry Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
~TagAliasRegistry () override
TagAlias const * find (std::string const &alias) const override
std::string expandAliases (std::string const &unexpandedTestSpec) const override
void add (std::string const &alias, std::string const &tag, SourceLineInfo const &lineInfo)
~TagAliasRegistry () override
TagAlias const * find (std::string const &alias) const override
std::string expandAliases (std::string const &unexpandedTestSpec) const override
void add (std::string const &alias, std::string const &tag, SourceLineInfo const &lineInfo)
Public Member Functions inherited from Catch::ITagAliasRegistry
virtual ~ITagAliasRegistry ()
virtual ~ITagAliasRegistry ()
Additional Inherited Members
Static Public Member Functions inherited from Catch::ITagAliasRegistry
static ITagAliasRegistry const & get ()
static ITagAliasRegistry const & get ()
Detailed Description
Definition at line 10085 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
~TagAliasRegistry() [1/2]
Catch::TagAliasRegistry::~TagAliasRegistry () override default
Definition at line 6062 of file catch_amalgamated.cpp.
~TagAliasRegistry() [2/2]
Catch::TagAliasRegistry::~TagAliasRegistry () override
Member Function Documentation
add() [1/2]
void Catch::TagAliasRegistry::add (std::string const & alias, std::string const & tag, SourceLineInfo const & lineInfo)
Definition at line 6085 of file catch_amalgamated.cpp.
References CATCH_ENFORCE, Catch::endsWith(), find(), and Catch::startsWith().
Referenced by TEST_CASE().
add() [2/2]
void Catch::TagAliasRegistry::add (std::string const & alias, std::string const & tag, SourceLineInfo const & lineInfo)
expandAliases() [1/2]
std::string Catch::TagAliasRegistry::expandAliases (std::string const & unexpandedTestSpec) const override virtual
Implements Catch::ITagAliasRegistry.
Definition at line 6072 of file catch_amalgamated.cpp.
expandAliases() [2/2]
std::string Catch::TagAliasRegistry::expandAliases (std::string const & unexpandedTestSpec) const override virtual
Implements Catch::ITagAliasRegistry.
find() [1/2]
TagAlias const * Catch::TagAliasRegistry::find (std::string const & alias) const override virtual
Implements Catch::ITagAliasRegistry.
Definition at line 6064 of file catch_amalgamated.cpp.
Referenced by add().
find() [2/2]
TagAlias const * Catch::TagAliasRegistry::find (std::string const & alias) const override virtual
Implements Catch::ITagAliasRegistry.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_tag_alias_registry.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_tag_alias_registry.cpp