libthe-seed: Catch::Clara::Parser Class Reference
Catch::Clara::Parser Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
auto operator|= (ExeName const &exeName) -> Parser &
auto operator|= (Arg const &arg) -> Parser &
auto operator|= (Opt const &opt) -> Parser &
Parser & operator|= (Parser const &other)
template<typename T>
auto operator| (T const &other) const -> Parser
std::vector< Detail::HelpColumns > getHelpColumns () const
void writeToStream (std::ostream &os) const
Detail::Result validate () const override
Detail::InternalParseResult parse (std::string const &exeName, Detail::TokenStream const &tokens) const override
auto operator|= (ExeName const &exeName) -> Parser &
auto operator|= (Arg const &arg) -> Parser &
auto operator|= (Opt const &opt) -> Parser &
Parser & operator|= (Parser const &other)
template<typename T>
auto operator| (T const &other) const -> Parser
std::vector< Detail::HelpColumns > getHelpColumns () const
void writeToStream (std::ostream &os) const
Detail::Result validate () const override
Detail::InternalParseResult parse (std::string const &exeName, Detail::TokenStream const &tokens) const override
Friends
auto operator<< (std::ostream &os, Parser const &parser) -> std::ostream &
auto operator<< (std::ostream &os, Parser const &parser) -> std::ostream &
Detailed Description
Definition at line 5040 of file catch_amalgamated.hpp.
Member Function Documentation
getHelpColumns() [1/2]
std::vector< Detail::HelpColumns > Catch::Clara::Parser::getHelpColumns () const
Definition at line 2746 of file catch_amalgamated.cpp.
Referenced by writeToStream().
getHelpColumns() [2/2]
std::vector< Detail::HelpColumns > Catch::Clara::Parser::getHelpColumns () const
operator|() [1/2]
template<typename T> auto Catch::Clara::Parser::operator| (T const & other) const->Parser inline
Definition at line 5065 of file catch_amalgamated.hpp.
operator|() [2/2]
template<typename T> auto Catch::Clara::Parser::operator| (T const & other) const->Parser inline
Definition at line 637 of file catch_clara.hpp.
operator|=() [1/8]
auto Catch::Clara::Parser::operator|= (Arg const & arg) ->Parser & inline
Definition at line 5052 of file catch_amalgamated.hpp.
operator|=() [2/8]
auto Catch::Clara::Parser::operator|= (Arg const & arg) ->Parser & inline
Definition at line 624 of file catch_clara.hpp.
operator|=() [3/8]
auto Catch::Clara::Parser::operator|= (ExeName const & exeName) ->Parser & inline
Definition at line 5047 of file catch_amalgamated.hpp.
operator|=() [4/8]
auto Catch::Clara::Parser::operator|= (ExeName const & exeName) ->Parser & inline
Definition at line 619 of file catch_clara.hpp.
operator|=() [5/8]
auto Catch::Clara::Parser::operator|= (Opt const & opt) ->Parser & inline
Definition at line 5057 of file catch_amalgamated.hpp.
operator|=() [6/8]
auto Catch::Clara::Parser::operator|= (Opt const & opt) ->Parser & inline
Definition at line 629 of file catch_clara.hpp.
operator|=() [7/8]
Parser & Catch::Clara::Parser::operator|= (Parser const & other)
Definition at line 2737 of file catch_amalgamated.cpp.
operator|=() [8/8]
Parser & Catch::Clara::Parser::operator|= (Parser const & other)
parse() [1/2]
Detail::InternalParseResult Catch::Clara::Parser::parse (std::string const & exeName, Detail::TokenStream const & tokens) const override
Definition at line 2814 of file catch_amalgamated.cpp.
References Catch::Clara::NoMatch, Catch::Clara::Detail::BasicResult< ParseState >::ok(), Catch::Clara::Detail::BasicResult< ParseState >::runtimeError(), and Catch::Clara::ShortCircuitAll.
parse() [2/2]
Detail::InternalParseResult Catch::Clara::Parser::parse (std::string const & exeName, Detail::TokenStream const & tokens) const override
validate() [1/2]
Detail::Result Catch::Clara::Parser::validate () const override
Definition at line 2799 of file catch_amalgamated.cpp.
References Catch::Clara::Detail::BasicResult< void >::ok().
validate() [2/2]
Detail::Result Catch::Clara::Parser::validate () const override
writeToStream() [1/2]
void Catch::Clara::Parser::writeToStream (std::ostream & os) const
Definition at line 2755 of file catch_amalgamated.cpp.
References CATCH_CONFIG_CONSOLE_WIDTH, getHelpColumns(), Catch::TextFlow::Column::indent(), Catch::TextFlow::Spacer(), and Catch::TextFlow::Column::width().
writeToStream() [2/2]
void Catch::Clara::Parser::writeToStream (std::ostream & os) const
Friends And Related Symbol Documentation
operator<< [1/2]
auto operator<< (std::ostream & os, Parser const & parser)->std::ostream & friend
Definition at line 5073 of file catch_amalgamated.hpp.
operator<< [2/2]
auto operator<< (std::ostream & os, Parser const & parser)->std::ostream & friend
Definition at line 645 of file catch_clara.hpp.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_clara.cpp