libthe-seed: Catch::XmlWriter Class Reference
Catch::XmlWriter Class Reference
#include <catch_amalgamated.hpp>
Classes
class ScopedElement
Public Member Functions
XmlWriter (std::ostream &os)
~XmlWriter ()
XmlWriter (XmlWriter const &)=delete
XmlWriter & operator= (XmlWriter const &)=delete
XmlWriter & startElement (std::string const &name, XmlFormatting fmt=XmlFormatting::Newline|XmlFormatting::Indent)
ScopedElement scopedElement (std::string const &name, XmlFormatting fmt=XmlFormatting::Newline|XmlFormatting::Indent)
XmlWriter & endElement (XmlFormatting fmt=XmlFormatting::Newline|XmlFormatting::Indent)
XmlWriter & writeAttribute (StringRef name, StringRef attribute)
The attribute content is XML-encoded.
XmlWriter & writeAttribute (StringRef name, bool attribute)
Writes the attribute as "true/false".
XmlWriter & writeAttribute (StringRef name, char const *attribute)
The attribute content is XML-encoded.
template<typename T, typename = typename std::enable_if_t< !std::is_convertible<T, StringRef>::value>>
XmlWriter & writeAttribute (StringRef name, T const &attribute)
The attribute value must provide op<<(ostream&, T). The resulting serialization is XML-encoded.
XmlWriter & writeText (StringRef text, XmlFormatting fmt=XmlFormatting::Newline|XmlFormatting::Indent)
Writes escaped text in a element.
XmlWriter & writeComment (StringRef text, XmlFormatting fmt=XmlFormatting::Newline|XmlFormatting::Indent)
Writes XML comment as "<!-- text -->".
void writeStylesheetRef (StringRef url)
void ensureTagClosed ()
XmlWriter (std::ostream &os)
~XmlWriter ()
XmlWriter (XmlWriter const &)=delete
XmlWriter & operator= (XmlWriter const &)=delete
XmlWriter & startElement (std::string const &name, XmlFormatting fmt=XmlFormatting::Newline|XmlFormatting::Indent)
ScopedElement scopedElement (std::string const &name, XmlFormatting fmt=XmlFormatting::Newline|XmlFormatting::Indent)
XmlWriter & endElement (XmlFormatting fmt=XmlFormatting::Newline|XmlFormatting::Indent)
XmlWriter & writeAttribute (StringRef name, StringRef attribute)
The attribute content is XML-encoded.
XmlWriter & writeAttribute (StringRef name, bool attribute)
Writes the attribute as "true/false".
XmlWriter & writeAttribute (StringRef name, char const *attribute)
The attribute content is XML-encoded.
template<typename T, typename = typename std::enable_if_t< !std::is_convertible<T, StringRef>::value>>
XmlWriter & writeAttribute (StringRef name, T const &attribute)
The attribute value must provide op<<(ostream&, T). The resulting serialization is XML-encoded.
XmlWriter & writeText (StringRef text, XmlFormatting fmt=XmlFormatting::Newline|XmlFormatting::Indent)
Writes escaped text in a element.
XmlWriter & writeComment (StringRef text, XmlFormatting fmt=XmlFormatting::Newline|XmlFormatting::Indent)
Writes XML comment as "<!-- text -->".
void writeStylesheetRef (StringRef url)
void ensureTagClosed ()
Detailed Description
Definition at line 10484 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
XmlWriter() [1/4]
Catch::XmlWriter::XmlWriter (std::ostream & os)
Definition at line 7352 of file catch_amalgamated.cpp.
Referenced by endElement(), operator=(), Catch::XmlWriter::ScopedElement::ScopedElement(), startElement(), writeAttribute(), writeAttribute(), writeAttribute(), writeAttribute(), writeComment(), writeText(), and XmlWriter().
~XmlWriter() [1/2]
Catch::XmlWriter::~XmlWriter ()
Definition at line 7357 of file catch_amalgamated.cpp.
References endElement().
XmlWriter() [2/4]
Catch::XmlWriter::XmlWriter (XmlWriter const &) delete
References XmlWriter().
XmlWriter() [3/4]
Catch::XmlWriter::XmlWriter (std::ostream & os)
~XmlWriter() [2/2]
Catch::XmlWriter::~XmlWriter ()
XmlWriter() [4/4]
Catch::XmlWriter::XmlWriter (XmlWriter const &) delete
References XmlWriter().
Member Function Documentation
endElement() [1/2]
XmlWriter & Catch::XmlWriter::endElement (XmlFormatting fmt = XmlFormatting::Newline | XmlFormatting::Indent)
Definition at line 7384 of file catch_amalgamated.cpp.
References XmlWriter().
Referenced by operator=(), and ~XmlWriter().
endElement() [2/2]
XmlWriter & Catch::XmlWriter::endElement (XmlFormatting fmt = XmlFormatting::Newline|XmlFormatting::Indent)
References Catch::Indent, Catch::Newline, and XmlWriter().
ensureTagClosed() [1/2]
void Catch::XmlWriter::ensureTagClosed ()
Definition at line 7449 of file catch_amalgamated.cpp.
Referenced by startElement(), writeComment(), and writeText().
ensureTagClosed() [2/2]
void Catch::XmlWriter::ensureTagClosed ()
operator=() [1/2]
XmlWriter & Catch::XmlWriter::operator= (XmlWriter const &) delete
References endElement(), Catch::Indent, Catch::Newline, scopedElement(), startElement(), writeAttribute(), and XmlWriter().
operator=() [2/2]
XmlWriter & Catch::XmlWriter::operator= (XmlWriter const &) delete
References XmlWriter().
scopedElement() [1/2]
XmlWriter::ScopedElement Catch::XmlWriter::scopedElement (std::string const & name, XmlFormatting fmt = XmlFormatting::Newline | XmlFormatting::Indent)
Definition at line 7378 of file catch_amalgamated.cpp.
References startElement().
Referenced by operator=(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
scopedElement() [2/2]
ScopedElement Catch::XmlWriter::scopedElement (std::string const & name, XmlFormatting fmt = XmlFormatting::Newline|XmlFormatting::Indent)
References Catch::Indent, and Catch::Newline.
startElement() [1/2]
XmlWriter & Catch::XmlWriter::startElement (std::string const & name, XmlFormatting fmt = XmlFormatting::Newline | XmlFormatting::Indent)
Definition at line 7364 of file catch_amalgamated.cpp.
References ensureTagClosed(), and XmlWriter().
Referenced by operator=(), and scopedElement().
startElement() [2/2]
XmlWriter & Catch::XmlWriter::startElement (std::string const & name, XmlFormatting fmt = XmlFormatting::Newline|XmlFormatting::Indent)
References Catch::Indent, Catch::Newline, and XmlWriter().
writeAttribute() [1/8]
XmlWriter & Catch::XmlWriter::writeAttribute (StringRef name, bool attribute)
Writes the attribute as "true/false".
Definition at line 7410 of file catch_amalgamated.cpp.
References writeAttribute(), and XmlWriter().
writeAttribute() [2/8]
XmlWriter & Catch::XmlWriter::writeAttribute (StringRef name, bool attribute)
Writes the attribute as "true/false".
References XmlWriter().
writeAttribute() [3/8]
XmlWriter & Catch::XmlWriter::writeAttribute (StringRef name, char const * attribute)
The attribute content is XML-encoded.
Definition at line 7415 of file catch_amalgamated.cpp.
References writeAttribute(), and XmlWriter().
writeAttribute() [4/8]
XmlWriter & Catch::XmlWriter::writeAttribute (StringRef name, char const * attribute)
The attribute content is XML-encoded.
References XmlWriter().
writeAttribute() [5/8]
XmlWriter & Catch::XmlWriter::writeAttribute (StringRef name, StringRef attribute)
The attribute content is XML-encoded.
Definition at line 7403 of file catch_amalgamated.cpp.
References Catch::StringRef::empty(), Catch::XmlEncode::ForAttributes, and XmlWriter().
Referenced by operator=(), writeAttribute(), writeAttribute(), and writeAttribute().
writeAttribute() [6/8]
XmlWriter & Catch::XmlWriter::writeAttribute (StringRef name, StringRef attribute)
The attribute content is XML-encoded.
References XmlWriter().
writeAttribute() [7/8]
template<typename T, typename = typename std::enable_if_t< !std::is_convertible<T, StringRef>::value>> XmlWriter & Catch::XmlWriter::writeAttribute (StringRef name, T const & attribute) inline
The attribute value must provide op<<(ostream&, T). The resulting serialization is XML-encoded.
Definition at line 10551 of file catch_amalgamated.hpp.
References Catch::ReusableStringStream::str(), writeAttribute(), and XmlWriter().
writeAttribute() [8/8]
template<typename T, typename = typename std::enable_if_t< !std::is_convertible<T, StringRef>::value>> XmlWriter & Catch::XmlWriter::writeAttribute (StringRef name, T const & attribute) inline
The attribute value must provide op<<(ostream&, T). The resulting serialization is XML-encoded.
Definition at line 115 of file catch_xmlwriter.hpp.
References Catch::ReusableStringStream::str(), writeAttribute(), and XmlWriter().
writeComment() [1/2]
XmlWriter & Catch::XmlWriter::writeComment (StringRef text, XmlFormatting fmt = XmlFormatting::Newline | XmlFormatting::Indent)
Writes XML comment as "<!-- text -->".
Definition at line 7435 of file catch_amalgamated.cpp.
References ensureTagClosed(), and XmlWriter().
Referenced by TEST_CASE().
writeComment() [2/2]
XmlWriter & Catch::XmlWriter::writeComment (StringRef text, XmlFormatting fmt = XmlFormatting::Newline|XmlFormatting::Indent)
Writes XML comment as "<!-- text -->".
References Catch::Indent, Catch::Newline, and XmlWriter().
writeStylesheetRef() [1/2]
void Catch::XmlWriter::writeStylesheetRef (StringRef url)
Definition at line 7445 of file catch_amalgamated.cpp.
writeStylesheetRef() [2/2]
void Catch::XmlWriter::writeStylesheetRef (StringRef url)
writeText() [1/2]
XmlWriter & Catch::XmlWriter::writeText (StringRef text, XmlFormatting fmt = XmlFormatting::Newline | XmlFormatting::Indent)
Writes escaped text in a element.
Definition at line 7421 of file catch_amalgamated.cpp.
References CATCH_ENFORCE, Catch::StringRef::empty(), ensureTagClosed(), Catch::XmlEncode::ForTextNodes, and XmlWriter().
Referenced by TEST_CASE().
writeText() [2/2]
XmlWriter & Catch::XmlWriter::writeText (StringRef text, XmlFormatting fmt = XmlFormatting::Newline|XmlFormatting::Indent)
Writes escaped text in a element.
References Catch::Indent, Catch::Newline, and XmlWriter().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_xmlwriter.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_xmlwriter.cpp