libthe-seed: clara::TextFlow::Columns::iterator Class Reference
clara::TextFlow::Columns::iterator Class Reference
#include <clara.hpp>
Public Types
using difference_type = std::ptrdiff_t
using value_type = std::string
using pointer = value_type*
using reference = value_type&
using iterator_category = std::forward_iterator_tag
Public Member Functions
iterator (Columns const &columns)
auto operator== (iterator const &other) const -> bool
auto operator!= (iterator const &other) const -> bool
auto operator* () const -> std::string
auto operator++ () -> iterator &
auto operator++ (int) -> iterator
Detailed Description
Definition at line 256 of file clara.hpp.
Member Typedef Documentation
difference_type
using clara::TextFlow::Columns::iterator::difference_type = std::ptrdiff_t
Definition at line 275 of file clara.hpp.
iterator_category
using clara::TextFlow::Columns::iterator::iterator_category = std::forward_iterator_tag
Definition at line 279 of file clara.hpp.
pointer
using clara::TextFlow::Columns::iterator::pointer = value_type*
Definition at line 277 of file clara.hpp.
reference
using clara::TextFlow::Columns::iterator::reference = value_type&
Definition at line 278 of file clara.hpp.
value_type
using clara::TextFlow::Columns::iterator::value_type = std::string
Definition at line 276 of file clara.hpp.
Constructor & Destructor Documentation
iterator()
clara::TextFlow::Columns::iterator::iterator (Columns const & columns) inline explicit
Definition at line 281 of file clara.hpp.
Member Function Documentation
operator!=()
auto clara::TextFlow::Columns::iterator::operator!= (iterator const & other) const->bool inline
Definition at line 294 of file clara.hpp.
operator*()
auto clara::TextFlow::Columns::iterator::operator* () const->std::string inline
Definition at line 297 of file clara.hpp.
References clara::TextFlow::Columns::end().
operator++() [1/2]
auto clara::TextFlow::Columns::iterator::operator++ () ->iterator & inline
Definition at line 316 of file clara.hpp.
References clara::TextFlow::Columns::end().
Referenced by operator++().
operator++() [2/2]
auto clara::TextFlow::Columns::iterator::operator++ (int) ->iterator inline
Definition at line 323 of file clara.hpp.
References operator++().
operator==()
auto clara::TextFlow::Columns::iterator::operator== (iterator const & other) const->bool inline
Definition at line 291 of file clara.hpp.
The documentation for this class was generated from the following file:
external/Catch2/third_party/clara.hpp