libthe-seed: Catch::AssertionHandler Class Reference
Catch::AssertionHandler Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
AssertionHandler (StringRef macroName, SourceLineInfo const &lineInfo, StringRef capturedExpression, ResultDisposition::Flags resultDisposition)
~AssertionHandler ()
template<typename T>
void handleExpr (ExprLhs< T > const &expr)
void handleExpr (ITransientExpression const &expr)
void handleMessage (ResultWas::OfType resultType, StringRef message)
void handleExceptionThrownAsExpected ()
void handleUnexpectedExceptionNotThrown ()
void handleExceptionNotThrownAsExpected ()
void handleThrowingCallSkipped ()
void handleUnexpectedInflightException ()
void complete ()
auto allowThrows () const -> bool
AssertionHandler (StringRef macroName, SourceLineInfo const &lineInfo, StringRef capturedExpression, ResultDisposition::Flags resultDisposition)
~AssertionHandler ()
template<typename T>
void handleExpr (ExprLhs< T > const &expr)
void handleExpr (ITransientExpression const &expr)
void handleMessage (ResultWas::OfType resultType, StringRef message)
void handleExceptionThrownAsExpected ()
void handleUnexpectedExceptionNotThrown ()
void handleExceptionNotThrownAsExpected ()
void handleThrowingCallSkipped ()
void handleUnexpectedInflightException ()
void complete ()
auto allowThrows () const -> bool
Detailed Description
Definition at line 5710 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
AssertionHandler() [1/2]
Catch::AssertionHandler::AssertionHandler (StringRef macroName, SourceLineInfo const & lineInfo, StringRef capturedExpression, ResultDisposition::Flags resultDisposition)
Definition at line 2352 of file catch_amalgamated.cpp.
References Catch::getResultCapture().
Referenced by allowThrows().
~AssertionHandler() [1/2]
Catch::AssertionHandler::~AssertionHandler () inline
Definition at line 5722 of file catch_amalgamated.hpp.
AssertionHandler() [2/2]
Catch::AssertionHandler::AssertionHandler (StringRef macroName, SourceLineInfo const & lineInfo, StringRef capturedExpression, ResultDisposition::Flags resultDisposition)
~AssertionHandler() [2/2]
Catch::AssertionHandler::~AssertionHandler () inline
Definition at line 37 of file catch_assertion_handler.hpp.
Member Function Documentation
allowThrows() [1/2]
auto Catch::AssertionHandler::allowThrows () const->bool
Definition at line 2370 of file catch_amalgamated.cpp.
References Catch::IConfig::allowThrows(), Catch::Context::getConfig(), and Catch::getCurrentContext().
allowThrows() [2/2]
auto Catch::AssertionHandler::allowThrows () const->bool
References AssertionHandler(), and Catch::handleExceptionMatchExpr().
complete() [1/2]
void Catch::AssertionHandler::complete ()
Definition at line 2374 of file catch_amalgamated.cpp.
References CATCH_BREAK_INTO_DEBUGGER, Catch::throw_test_failure_exception(), and Catch::throw_test_skip_exception().
complete() [2/2]
void Catch::AssertionHandler::complete ()
handleExceptionNotThrownAsExpected() [1/2]
void Catch::AssertionHandler::handleExceptionNotThrownAsExpected ()
Definition at line 2399 of file catch_amalgamated.cpp.
References Catch::ResultWas::Ok.
handleExceptionNotThrownAsExpected() [2/2]
void Catch::AssertionHandler::handleExceptionNotThrownAsExpected ()
handleExceptionThrownAsExpected() [1/2]
void Catch::AssertionHandler::handleExceptionThrownAsExpected ()
Definition at line 2396 of file catch_amalgamated.cpp.
References Catch::ResultWas::Ok.
handleExceptionThrownAsExpected() [2/2]
void Catch::AssertionHandler::handleExceptionThrownAsExpected ()
handleExpr() [1/4]
template<typename T> void Catch::AssertionHandler::handleExpr (ExprLhs< T > const & expr) inline
Definition at line 5730 of file catch_amalgamated.hpp.
References handleExpr(), and Catch::ExprLhs< LhsT >::makeUnaryExpr().
Referenced by Catch::handleExceptionMatchExpr(), and handleExpr().
handleExpr() [2/4]
template<typename T> void Catch::AssertionHandler::handleExpr (ExprLhs< T > const & expr) inline
Definition at line 45 of file catch_assertion_handler.hpp.
References handleExpr(), and Catch::ExprLhs< LhsT >::makeUnaryExpr().
handleExpr() [3/4]
void Catch::AssertionHandler::handleExpr (ITransientExpression const & expr)
Definition at line 2363 of file catch_amalgamated.cpp.
handleExpr() [4/4]
void Catch::AssertionHandler::handleExpr (ITransientExpression const & expr)
handleMessage() [1/2]
void Catch::AssertionHandler::handleMessage (ResultWas::OfType resultType, StringRef message)
Definition at line 2366 of file catch_amalgamated.cpp.
handleMessage() [2/2]
void Catch::AssertionHandler::handleMessage (ResultWas::OfType resultType, StringRef message)
handleThrowingCallSkipped() [1/2]
void Catch::AssertionHandler::handleThrowingCallSkipped ()
Definition at line 2407 of file catch_amalgamated.cpp.
References Catch::ResultWas::Ok.
handleThrowingCallSkipped() [2/2]
void Catch::AssertionHandler::handleThrowingCallSkipped ()
handleUnexpectedExceptionNotThrown() [1/2]
void Catch::AssertionHandler::handleUnexpectedExceptionNotThrown ()
Definition at line 2403 of file catch_amalgamated.cpp.
handleUnexpectedExceptionNotThrown() [2/2]
void Catch::AssertionHandler::handleUnexpectedExceptionNotThrown ()
handleUnexpectedInflightException() [1/2]
void Catch::AssertionHandler::handleUnexpectedInflightException ()
Definition at line 2392 of file catch_amalgamated.cpp.
References Catch::translateActiveException().
handleUnexpectedInflightException() [2/2]
void Catch::AssertionHandler::handleUnexpectedInflightException ()
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_assertion_handler.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_assertion_handler.cpp