libthe-seed: Catch::RedirectedStreams Class Reference
Catch::RedirectedStreams Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
RedirectedStreams (RedirectedStreams const &)=delete
RedirectedStreams & operator= (RedirectedStreams const &)=delete
RedirectedStreams (RedirectedStreams &&)=delete
RedirectedStreams & operator= (RedirectedStreams &&)=delete
RedirectedStreams (std::string &redirectedCout, std::string &redirectedCerr)
~RedirectedStreams ()
RedirectedStreams (RedirectedStreams const &)=delete
RedirectedStreams & operator= (RedirectedStreams const &)=delete
RedirectedStreams (RedirectedStreams &&)=delete
RedirectedStreams & operator= (RedirectedStreams &&)=delete
RedirectedStreams (std::string &redirectedCout, std::string &redirectedCerr)
~RedirectedStreams ()
Detailed Description
Definition at line 9385 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
RedirectedStreams() [1/6]
Catch::RedirectedStreams::RedirectedStreams (RedirectedStreams const &) delete
References RedirectedStreams().
Referenced by operator=(), operator=(), RedirectedStreams(), and RedirectedStreams().
RedirectedStreams() [2/6]
Catch::RedirectedStreams::RedirectedStreams (RedirectedStreams &&) delete
References RedirectedStreams().
RedirectedStreams() [3/6]
Catch::RedirectedStreams::RedirectedStreams (std::string & redirectedCout, std::string & redirectedCerr)
Definition at line 4515 of file catch_amalgamated.cpp.
~RedirectedStreams() [1/2]
Catch::RedirectedStreams::~RedirectedStreams ()
Definition at line 4520 of file catch_amalgamated.cpp.
RedirectedStreams() [4/6]
Catch::RedirectedStreams::RedirectedStreams (RedirectedStreams const &) delete
References RedirectedStreams().
RedirectedStreams() [5/6]
Catch::RedirectedStreams::RedirectedStreams (RedirectedStreams &&) delete
References RedirectedStreams().
RedirectedStreams() [6/6]
Catch::RedirectedStreams::RedirectedStreams (std::string & redirectedCout, std::string & redirectedCerr)
~RedirectedStreams() [2/2]
Catch::RedirectedStreams::~RedirectedStreams ()
Member Function Documentation
operator=() [1/4]
RedirectedStreams & Catch::RedirectedStreams::operator= (RedirectedStreams &&) delete
References RedirectedStreams().
operator=() [2/4]
RedirectedStreams & Catch::RedirectedStreams::operator= (RedirectedStreams &&) delete
References RedirectedStreams().
operator=() [3/4]
RedirectedStreams & Catch::RedirectedStreams::operator= (RedirectedStreams const &) delete
References RedirectedStreams().
operator=() [4/4]
RedirectedStreams & Catch::RedirectedStreams::operator= (RedirectedStreams const &) delete
References RedirectedStreams().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_output_redirect.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_output_redirect.cpp