libthe-seed: Catch::Section Class Reference
Catch::Section Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
Section (SectionInfo &&info)
Section (SourceLineInfo const &_lineInfo, StringRef _name, const char *const =nullptr)
~Section ()
operator bool () const
Section (SectionInfo &&info)
Section (SourceLineInfo const &_lineInfo, StringRef _name, const char *const =nullptr)
~Section ()
operator bool () const
Detailed Description
Definition at line 5966 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
Section() [1/4]
Catch::Section::Section (SectionInfo && info)
Definition at line 5760 of file catch_amalgamated.cpp.
References CATCH_MOVE, and Catch::getResultCapture().
Section() [2/4]
Catch::Section::Section (SourceLineInfo const & _lineInfo, StringRef _name, const char * const = nullptr)
Definition at line 5771 of file catch_amalgamated.cpp.
~Section() [1/2]
Catch::Section::~Section ()
Definition at line 5788 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::getResultCapture(), Catch::IResultCapture::sectionEnded(), Catch::IResultCapture::sectionEndedEarly(), and Catch::uncaught_exceptions().
Section() [3/4]
Catch::Section::Section (SectionInfo && info)
Section() [4/4]
Catch::Section::Section (SourceLineInfo const & _lineInfo, StringRef _name, const char * const = nullptr)
~Section() [2/2]
Catch::Section::~Section ()
Member Function Documentation
operator bool() [1/2]
Catch::Section::operator bool () const explicit
Definition at line 5800 of file catch_amalgamated.cpp.
operator bool() [2/2]
Catch::Section::operator bool () const explicit
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_section.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_section.cpp