libthe-seed: clara::TextFlow::Column Class Reference
clara::TextFlow::Column Class Reference
#include <clara.hpp>
Classes
class iterator
Public Types
using const_iterator = iterator
Public Member Functions
Column (std::string const &text)
auto width (size_t newWidth) -> Column &
auto indent (size_t newIndent) -> Column &
auto initialIndent (size_t newIndent) -> Column &
auto width () const -> size_t
auto begin () const -> iterator
auto end () const -> iterator
auto operator+ (Column const &other) -> Columns
auto toString () const -> std::string
Friends
std::ostream & operator<< (std::ostream &os, Column const &col)
Detailed Description
Definition at line 72 of file clara.hpp.
Member Typedef Documentation
const_iterator
using clara::TextFlow::Column::const_iterator = iterator
Definition at line 200 of file clara.hpp.
Constructor & Destructor Documentation
Column()
clara::TextFlow::Column::Column (std::string const & text) inline explicit
Definition at line 202 of file clara.hpp.
Referenced by indent(), initialIndent(), operator+(), operator<<, clara::TextFlow::Spacer::Spacer(), and width().
Member Function Documentation
begin()
auto clara::TextFlow::Column::begin () const->iterator inline
Definition at line 219 of file clara.hpp.
end()
auto clara::TextFlow::Column::end () const->iterator inline
Definition at line 220 of file clara.hpp.
indent()
auto clara::TextFlow::Column::indent (size_t newIndent) ->Column & inline
Definition at line 209 of file clara.hpp.
References Column().
initialIndent()
auto clara::TextFlow::Column::initialIndent (size_t newIndent) ->Column & inline
Definition at line 213 of file clara.hpp.
References Column().
operator+()
auto clara::TextFlow::Column::operator+ (Column const & other) ->Columns inline
Definition at line 364 of file clara.hpp.
References Column().
toString()
auto clara::TextFlow::Column::toString () const->std::string inline
Definition at line 236 of file clara.hpp.
width() [1/2]
auto clara::TextFlow::Column::width () const->size_t inline
Definition at line 218 of file clara.hpp.
width() [2/2]
auto clara::TextFlow::Column::width (size_t newWidth) ->Column & inline
Definition at line 204 of file clara.hpp.
References Column().
Referenced by clara::TextFlow::Spacer::Spacer(), and clara::detail::Parser::writeToStream().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, Column const & col) friend
Definition at line 222 of file clara.hpp.
References Column().
The documentation for this class was generated from the following file:
external/Catch2/third_party/clara.hpp