libthe-seed: Catch::StreamingReporterBase Class Reference
Catch::StreamingReporterBase Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
StreamingReporterBase (ReporterConfig &&_config)
~StreamingReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void testRunStarting (TestRunInfo const &_testRunInfo) override
void testCaseStarting (TestCaseInfo const &_testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &_sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &) override
void skipTest (TestCaseInfo const &) override
StreamingReporterBase (ReporterConfig &&_config)
~StreamingReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void testRunStarting (TestRunInfo const &_testRunInfo) override
void testCaseStarting (TestCaseInfo const &_testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &_sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &) override
void skipTest (TestCaseInfo const &) override
Public Member Functions inherited from Catch::ReporterBase
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
Public Member Functions inherited from Catch::IEventListener
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
Protected Attributes
TestRunInfo currentTestRunInfo { "test run has not started yet"_sr }
TestCaseInfo const * currentTestCaseInfo = nullptr
std::vector< SectionInfo > m_sectionStack
Stack of all active sections in the current test case.
Protected Attributes inherited from Catch::ReporterBase
Detail::unique_ptr< IStream > m_wrapped_stream
The stream wrapper as passed to us by outside code.
std::ostream & m_stream
Cached output stream from m_wrapped_stream to reduce number of indirect calls needed to write output.
Detail::unique_ptr< ColourImpl > m_colour
Colour implementation this reporter was configured for.
std::map< std::string, std::string > m_customOptions
The custom reporter options user passed down to the reporter.
Protected Attributes inherited from Catch::IEventListener
ReporterPreferences m_preferences
Derived classes can set up their preferences here.
IConfig const * m_config
The test run's config as filled in from CLI and defaults.
Detailed Description
Definition at line 12239 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
StreamingReporterBase() [1/2]
Catch::StreamingReporterBase::StreamingReporterBase (ReporterConfig && _config) inline
Definition at line 12243 of file catch_amalgamated.hpp.
References CATCH_MOVE, and Catch::ReporterBase::ReporterBase().
Referenced by Catch::AutomakeReporter::AutomakeReporter(), Catch::ConsoleReporter::ConsoleReporter(), Catch::TAPReporter::TAPReporter(), Catch::TeamCityReporter::TeamCityReporter(), and Catch::XmlReporter::XmlReporter().
~StreamingReporterBase() [1/2]
Catch::StreamingReporterBase::~StreamingReporterBase () override default
StreamingReporterBase() [2/2]
Catch::StreamingReporterBase::StreamingReporterBase (ReporterConfig && _config) inline
Definition at line 22 of file catch_reporter_streaming_base.hpp.
References CATCH_MOVE, and Catch::ReporterBase::ReporterBase().
~StreamingReporterBase() [2/2]
Catch::StreamingReporterBase::~StreamingReporterBase () override
Member Function Documentation
assertionEnded() [1/2]
void Catch::StreamingReporterBase::assertionEnded (AssertionStats const & assertionStats) inline override virtual
Called after assertion was fully evaluated.
Implements Catch::IEventListener.
Reimplemented in Catch::TAPReporter, Catch::TAPReporter, Catch::TeamCityReporter, Catch::TeamCityReporter, Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 12268 of file catch_amalgamated.hpp.
assertionEnded() [2/2]
void Catch::StreamingReporterBase::assertionEnded (AssertionStats const & assertionStats) inline override virtual
Called after assertion was fully evaluated.
Implements Catch::IEventListener.
Reimplemented in Catch::TAPReporter, Catch::TAPReporter, Catch::TeamCityReporter, Catch::TeamCityReporter, Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 47 of file catch_reporter_streaming_base.hpp.
assertionStarting() [1/2]
void Catch::StreamingReporterBase::assertionStarting (AssertionInfo const & assertionInfo) inline override virtual
Called before assertion success/failure is evaluated.
Implements Catch::IEventListener.
Reimplemented in Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 12267 of file catch_amalgamated.hpp.
assertionStarting() [2/2]
void Catch::StreamingReporterBase::assertionStarting (AssertionInfo const & assertionInfo) inline override virtual
Called before assertion success/failure is evaluated.
Implements Catch::IEventListener.
Reimplemented in Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 46 of file catch_reporter_streaming_base.hpp.
benchmarkEnded() [1/2]
void Catch::StreamingReporterBase::benchmarkEnded (BenchmarkStats<> const & benchmarkStats) inline override virtual
Called with the benchmark results if benchmark successfully finishes.
Implements Catch::IEventListener.
Reimplemented in Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 12250 of file catch_amalgamated.hpp.
benchmarkEnded() [2/2]
void Catch::StreamingReporterBase::benchmarkEnded (BenchmarkStats<> const & benchmarkStats) inline override virtual
Called with the benchmark results if benchmark successfully finishes.
Implements Catch::IEventListener.
Reimplemented in Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 29 of file catch_reporter_streaming_base.hpp.
benchmarkFailed() [1/2]
void Catch::StreamingReporterBase::benchmarkFailed (StringRef benchmarkName) inline override virtual
Called if running the benchmarks fails for any reason.
Implements Catch::IEventListener.
Reimplemented in Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 12251 of file catch_amalgamated.hpp.
benchmarkFailed() [2/2]
void Catch::StreamingReporterBase::benchmarkFailed (StringRef benchmarkName) inline override virtual
Called if running the benchmarks fails for any reason.
Implements Catch::IEventListener.
Reimplemented in Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 30 of file catch_reporter_streaming_base.hpp.
benchmarkPreparing() [1/2]
void Catch::StreamingReporterBase::benchmarkPreparing (StringRef benchmarkName) inline override virtual
Called when user-code is being probed before the actual benchmark runs.
Implements Catch::IEventListener.
Reimplemented in Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 12248 of file catch_amalgamated.hpp.
benchmarkPreparing() [2/2]
void Catch::StreamingReporterBase::benchmarkPreparing (StringRef benchmarkName) inline override virtual
Called when user-code is being probed before the actual benchmark runs.
Implements Catch::IEventListener.
Reimplemented in Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 27 of file catch_reporter_streaming_base.hpp.
benchmarkStarting() [1/2]
void Catch::StreamingReporterBase::benchmarkStarting (BenchmarkInfo const & benchmarkInfo) inline override virtual
Called after probe but before the user-code is being benchmarked.
Implements Catch::IEventListener.
Reimplemented in Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 12249 of file catch_amalgamated.hpp.
benchmarkStarting() [2/2]
void Catch::StreamingReporterBase::benchmarkStarting (BenchmarkInfo const & benchmarkInfo) inline override virtual
Called after probe but before the user-code is being benchmarked.
Implements Catch::IEventListener.
Reimplemented in Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 28 of file catch_reporter_streaming_base.hpp.
fatalErrorEncountered() [1/2]
void Catch::StreamingReporterBase::fatalErrorEncountered (StringRef error) inline override virtual
Called if a fatal error (signal/structured exception) occurred.
Implements Catch::IEventListener.
Definition at line 12253 of file catch_amalgamated.hpp.
fatalErrorEncountered() [2/2]
void Catch::StreamingReporterBase::fatalErrorEncountered (StringRef error) inline override virtual
Called if a fatal error (signal/structured exception) occurred.
Implements Catch::IEventListener.
Definition at line 32 of file catch_reporter_streaming_base.hpp.
noMatchingTestCases() [1/2]
void Catch::StreamingReporterBase::noMatchingTestCases (StringRef unmatchedSpec) inline override virtual
Called when no test cases match provided test spec.
Implements Catch::IEventListener.
Reimplemented in Catch::TAPReporter, and Catch::TAPReporter.
Definition at line 12254 of file catch_amalgamated.hpp.
noMatchingTestCases() [2/2]
void Catch::StreamingReporterBase::noMatchingTestCases (StringRef unmatchedSpec) inline override virtual
Called when no test cases match provided test spec.
Implements Catch::IEventListener.
Reimplemented in Catch::TAPReporter, and Catch::TAPReporter.
Definition at line 33 of file catch_reporter_streaming_base.hpp.
reportInvalidTestSpec() [1/2]
void Catch::StreamingReporterBase::reportInvalidTestSpec (StringRef invalidArgument) inline override virtual
Called for all invalid test specs from the cli.
Implements Catch::IEventListener.
Definition at line 12255 of file catch_amalgamated.hpp.
reportInvalidTestSpec() [2/2]
void Catch::StreamingReporterBase::reportInvalidTestSpec (StringRef invalidArgument) inline override virtual
Called for all invalid test specs from the cli.
Implements Catch::IEventListener.
Definition at line 34 of file catch_reporter_streaming_base.hpp.
sectionEnded() [1/2]
void Catch::StreamingReporterBase::sectionEnded (SectionStats const & sectionStats) inline override virtual
Called after a SECTION has finished running.
Implements Catch::IEventListener.
Reimplemented in Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 12270 of file catch_amalgamated.hpp.
References m_sectionStack.
Referenced by Catch::ConsoleReporter::sectionEnded(), and Catch::XmlReporter::sectionEnded().
sectionEnded() [2/2]
void Catch::StreamingReporterBase::sectionEnded (SectionStats const & sectionStats) inline override virtual
Called after a SECTION has finished running.
Implements Catch::IEventListener.
Reimplemented in Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 49 of file catch_reporter_streaming_base.hpp.
References m_sectionStack.
sectionStarting() [1/2]
void Catch::StreamingReporterBase::sectionStarting (SectionInfo const & sectionInfo) inline override virtual
Called when a SECTION is being entered. Not called for skipped sections.
Implements Catch::IEventListener.
Reimplemented in Catch::TeamCityReporter, Catch::TeamCityReporter, Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 12263 of file catch_amalgamated.hpp.
References m_sectionStack.
Referenced by Catch::ConsoleReporter::sectionStarting(), Catch::TeamCityReporter::sectionStarting(), and Catch::XmlReporter::sectionStarting().
sectionStarting() [2/2]
void Catch::StreamingReporterBase::sectionStarting (SectionInfo const & sectionInfo) inline override virtual
Called when a SECTION is being entered. Not called for skipped sections.
Implements Catch::IEventListener.
Reimplemented in Catch::TeamCityReporter, Catch::TeamCityReporter, Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 42 of file catch_reporter_streaming_base.hpp.
References m_sectionStack.
skipTest() [1/2]
void Catch::StreamingReporterBase::skipTest (TestCaseInfo const & testInfo) inline override virtual
Called with test cases that are skipped due to the test run aborting. NOT called for test cases that are explicitly skipped using the SKIP macro.
Deprecated - will be removed in the next major release.
Implements Catch::IEventListener.
Definition at line 12279 of file catch_amalgamated.hpp.
skipTest() [2/2]
void Catch::StreamingReporterBase::skipTest (TestCaseInfo const & testInfo) inline override virtual
Called with test cases that are skipped due to the test run aborting. NOT called for test cases that are explicitly skipped using the SKIP macro.
Deprecated - will be removed in the next major release.
Implements Catch::IEventListener.
Definition at line 58 of file catch_reporter_streaming_base.hpp.
testCaseEnded() [1/2]
void Catch::StreamingReporterBase::testCaseEnded (TestCaseStats const & testCaseStats) inline override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
Reimplemented in Catch::TeamCityReporter, Catch::TeamCityReporter, Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 12274 of file catch_amalgamated.hpp.
References currentTestCaseInfo.
Referenced by Catch::AutomakeReporter::testCaseEnded(), Catch::ConsoleReporter::testCaseEnded(), Catch::TeamCityReporter::testCaseEnded(), and Catch::XmlReporter::testCaseEnded().
testCaseEnded() [2/2]
void Catch::StreamingReporterBase::testCaseEnded (TestCaseStats const & testCaseStats) inline override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
Reimplemented in Catch::TeamCityReporter, Catch::TeamCityReporter, Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 53 of file catch_reporter_streaming_base.hpp.
References currentTestCaseInfo.
testCasePartialEnded() [1/2]
void Catch::StreamingReporterBase::testCasePartialEnded (TestCaseStats const & testCaseStats, uint64_t partNumber) inline override virtual
Called every time a TEST_CASE is entered, including repeats (due to sections).
Implements Catch::IEventListener.
Definition at line 12273 of file catch_amalgamated.hpp.
testCasePartialEnded() [2/2]
void Catch::StreamingReporterBase::testCasePartialEnded (TestCaseStats const & testCaseStats, uint64_t partNumber) inline override virtual
Called every time a TEST_CASE is entered, including repeats (due to sections).
Implements Catch::IEventListener.
Definition at line 52 of file catch_reporter_streaming_base.hpp.
testCasePartialStarting() [1/2]
void Catch::StreamingReporterBase::testCasePartialStarting (TestCaseInfo const & testInfo, uint64_t partNumber) inline override virtual
Called every time a TEST_CASE is entered, including repeats (due to sections).
Implements Catch::IEventListener.
Definition at line 12262 of file catch_amalgamated.hpp.
testCasePartialStarting() [2/2]
void Catch::StreamingReporterBase::testCasePartialStarting (TestCaseInfo const & testInfo, uint64_t partNumber) inline override virtual
Called every time a TEST_CASE is entered, including repeats (due to sections).
Implements Catch::IEventListener.
Definition at line 41 of file catch_reporter_streaming_base.hpp.
testCaseStarting() [1/2]
void Catch::StreamingReporterBase::testCaseStarting (TestCaseInfo const & testInfo) inline override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
Reimplemented in Catch::TeamCityReporter, Catch::TeamCityReporter, Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 12259 of file catch_amalgamated.hpp.
References currentTestCaseInfo.
Referenced by Catch::TeamCityReporter::testCaseStarting(), and Catch::XmlReporter::testCaseStarting().
testCaseStarting() [2/2]
void Catch::StreamingReporterBase::testCaseStarting (TestCaseInfo const & testInfo) inline override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
Reimplemented in Catch::TeamCityReporter, Catch::TeamCityReporter, Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 38 of file catch_reporter_streaming_base.hpp.
References currentTestCaseInfo.
testRunEnded() [1/2]
void Catch::StreamingReporterBase::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Implements Catch::IEventListener.
Reimplemented in Catch::TAPReporter, Catch::TAPReporter, Catch::TeamCityReporter, Catch::TeamCityReporter, Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 10087 of file catch_amalgamated.cpp.
References currentTestCaseInfo.
Referenced by Catch::CompactReporter::testRunEnded(), Catch::ConsoleReporter::testRunEnded(), Catch::TAPReporter::testRunEnded(), and Catch::XmlReporter::testRunEnded().
testRunEnded() [2/2]
void Catch::StreamingReporterBase::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Implements Catch::IEventListener.
Reimplemented in Catch::TAPReporter, Catch::TAPReporter, Catch::TeamCityReporter, Catch::TeamCityReporter, Catch::XmlReporter, and Catch::XmlReporter.
testRunStarting() [1/2]
void Catch::StreamingReporterBase::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Implements Catch::IEventListener.
Reimplemented in Catch::TAPReporter, Catch::TAPReporter, Catch::TeamCityReporter, Catch::TeamCityReporter, Catch::XmlReporter, and Catch::XmlReporter.
Definition at line 10083 of file catch_amalgamated.cpp.
References currentTestRunInfo.
Referenced by Catch::ConsoleReporter::testRunStarting(), and Catch::XmlReporter::testRunStarting().
testRunStarting() [2/2]
void Catch::StreamingReporterBase::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Implements Catch::IEventListener.
Reimplemented in Catch::TAPReporter, Catch::TAPReporter, Catch::TeamCityReporter, Catch::TeamCityReporter, Catch::XmlReporter, and Catch::XmlReporter.
Member Data Documentation
currentTestCaseInfo
TestCaseInfo const * Catch::StreamingReporterBase::currentTestCaseInfo = nullptr protected
Definition at line 12286 of file catch_amalgamated.hpp.
Referenced by Catch::TAPReporter::assertionEnded(), Catch::TeamCityReporter::assertionEnded(), testCaseEnded(), testCaseStarting(), and testRunEnded().
currentTestRunInfo
TestRunInfo Catch::StreamingReporterBase::currentTestRunInfo { "test run has not started yet"_sr } protected
Definition at line 12285 of file catch_amalgamated.hpp.
Referenced by testRunStarting().
m_sectionStack
std::vector< SectionInfo > Catch::StreamingReporterBase::m_sectionStack protected
Stack of all active sections in the current test case.
Definition at line 12289 of file catch_amalgamated.hpp.
Referenced by Catch::ConsoleReporter::sectionEnded(), sectionEnded(), and sectionStarting().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/reporters/catch_reporter_streaming_base.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/reporters/catch_reporter_streaming_base.cpp