libthe-seed: Catch::Clara::Opt Class Reference
Catch::Clara::Opt Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
template<typename LambdaT>
Opt (LambdaT const &ref)
Opt (bool &ref)
template<typename LambdaT, typename = typename std::enable_if_t< Detail::is_unary_function<LambdaT>::value>>
Opt (LambdaT const &ref, std::string const &hint)
template<typename LambdaT>
Opt (accept_many_t, LambdaT const &ref, std::string const &hint)
template<typename T, typename = typename std::enable_if_t< !Detail::is_unary_function<T>::value>>
Opt (T &ref, std::string const &hint)
auto operator[] (std::string const &optName) -> Opt &
std::vector< Detail::HelpColumns > getHelpColumns () const
bool isMatch (std::string const &optToken) const
Detail::InternalParseResult parse (std::string const &, Detail::TokenStream const &tokens) const override
Detail::Result validate () const override
template<typename LambdaT>
Opt (LambdaT const &ref)
Opt (bool &ref)
template<typename LambdaT, typename = typename std::enable_if_t< Detail::is_unary_function<LambdaT>::value>>
Opt (LambdaT const &ref, std::string const &hint)
template<typename LambdaT>
Opt (accept_many_t, LambdaT const &ref, std::string const &hint)
template<typename T, typename = typename std::enable_if_t< !Detail::is_unary_function<T>::value>>
Opt (T &ref, std::string const &hint)
auto operator[] (std::string const &optName) -> Opt &
std::vector< Detail::HelpColumns > getHelpColumns () const
bool isMatch (std::string const &optToken) const
Detail::InternalParseResult parse (std::string const &, Detail::TokenStream const &tokens) const override
Detail::Result validate () const override
Public Member Functions inherited from Catch::Clara::Detail::ParserRefImpl< Opt >
auto operator() (std::string const &description) -> Opt &
auto optional () -> Opt &
auto required () -> Opt &
auto isOptional () const -> bool
auto cardinality () const -> size_t override
std::string const & hint () const
Public Member Functions inherited from Catch::Clara::Detail::ComposableParserImpl< Opt >
Parser operator| (T const &other) const
Public Member Functions inherited from Catch::Clara::Detail::ParserBase
virtual ~ParserBase ()=default
virtual auto validate () const -> Result
virtual auto parse (std::string const &exeName, TokenStream const &tokens) const -> InternalParseResult=0
virtual size_t cardinality () const
InternalParseResult parse (Args const &args) const
virtual ~ParserBase ()=default
virtual auto validate () const -> Result
virtual auto parse (std::string const &exeName, TokenStream const &tokens) const -> InternalParseResult=0
virtual size_t cardinality () const
InternalParseResult parse (Args const &args) const
Protected Attributes
std::vector< std::string > m_optNames
Protected Attributes inherited from Catch::Clara::Detail::ParserRefImpl< Opt >
Optionality m_optionality
std::shared_ptr< BoundRef > m_ref
std::string m_hint
std::string m_description
Additional Inherited Members
Protected Member Functions inherited from Catch::Clara::Detail::ParserRefImpl< Opt >
ParserRefImpl (std::shared_ptr< BoundRef > const &ref)
Detailed Description
Definition at line 4968 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
Opt() [1/10]
template<typename LambdaT> Catch::Clara::Opt::Opt (LambdaT const & ref) inline explicit
Definition at line 4974 of file catch_amalgamated.hpp.
References Catch::Clara::Detail::ParserRefImpl< Opt >::ParserRefImpl().
Referenced by Catch::Clara::Help::Help(), and operator[]().
Opt() [2/10]
Catch::Clara::Opt::Opt (bool & ref) explicit
Definition at line 2608 of file catch_amalgamated.cpp.
References Catch::Clara::Detail::ParserRefImpl< Opt >::ParserRefImpl().
Opt() [3/10]
template<typename LambdaT, typename = typename std::enable_if_t< Detail::is_unary_function<LambdaT>::value>> Catch::Clara::Opt::Opt (LambdaT const & ref, std::string const & hint) inline
Definition at line 4983 of file catch_amalgamated.hpp.
References Catch::Clara::Detail::ParserRefImpl< Opt >::hint(), and Catch::Clara::Detail::ParserRefImpl< Opt >::ParserRefImpl().
Opt() [4/10]
template<typename LambdaT> Catch::Clara::Opt::Opt (accept_many_t , LambdaT const & ref, std::string const & hint) inline
Definition at line 4987 of file catch_amalgamated.hpp.
References Catch::Clara::accept_many, Catch::Clara::Detail::ParserRefImpl< Opt >::hint(), and Catch::Clara::Detail::ParserRefImpl< Opt >::ParserRefImpl().
Opt() [5/10]
template<typename T, typename = typename std::enable_if_t< !Detail::is_unary_function<T>::value>> Catch::Clara::Opt::Opt (T & ref, std::string const & hint) inline
Definition at line 4993 of file catch_amalgamated.hpp.
References Catch::Clara::Detail::ParserRefImpl< Opt >::hint(), and Catch::Clara::Detail::ParserRefImpl< Opt >::ParserRefImpl().
Opt() [6/10]
template<typename LambdaT> Catch::Clara::Opt::Opt (LambdaT const & ref) inline explicit
Definition at line 546 of file catch_clara.hpp.
References Catch::Clara::Detail::ParserRefImpl< Opt >::ParserRefImpl().
Opt() [7/10]
Catch::Clara::Opt::Opt (bool & ref) explicit
Opt() [8/10]
template<typename LambdaT, typename = typename std::enable_if_t< Detail::is_unary_function<LambdaT>::value>> Catch::Clara::Opt::Opt (LambdaT const & ref, std::string const & hint) inline
Definition at line 555 of file catch_clara.hpp.
References Catch::Clara::Detail::ParserRefImpl< Opt >::hint(), and Catch::Clara::Detail::ParserRefImpl< Opt >::ParserRefImpl().
Opt() [9/10]
template<typename LambdaT> Catch::Clara::Opt::Opt (accept_many_t , LambdaT const & ref, std::string const & hint) inline
Definition at line 559 of file catch_clara.hpp.
References Catch::Clara::accept_many, Catch::Clara::Detail::ParserRefImpl< Opt >::hint(), and Catch::Clara::Detail::ParserRefImpl< Opt >::ParserRefImpl().
Opt() [10/10]
template<typename T, typename = typename std::enable_if_t< !Detail::is_unary_function<T>::value>> Catch::Clara::Opt::Opt (T & ref, std::string const & hint) inline
Definition at line 565 of file catch_clara.hpp.
References Catch::Clara::Detail::ParserRefImpl< Opt >::hint(), and Catch::Clara::Detail::ParserRefImpl< Opt >::ParserRefImpl().
Member Function Documentation
getHelpColumns() [1/2]
std::vector< Detail::HelpColumns > Catch::Clara::Opt::getHelpColumns () const
Definition at line 2611 of file catch_amalgamated.cpp.
References Catch::Clara::Detail::ParserRefImpl< Opt >::m_description, Catch::Clara::Detail::ParserRefImpl< Opt >::m_hint, and m_optNames.
getHelpColumns() [2/2]
std::vector< Detail::HelpColumns > Catch::Clara::Opt::getHelpColumns () const
isMatch() [1/2]
bool Catch::Clara::Opt::isMatch (std::string const & optToken) const
Definition at line 2626 of file catch_amalgamated.cpp.
References m_optNames.
Referenced by parse().
isMatch() [2/2]
bool Catch::Clara::Opt::isMatch (std::string const & optToken) const
operator[]() [1/2]
auto Catch::Clara::Opt::operator[] (std::string const & optName) ->Opt & inline
Definition at line 4996 of file catch_amalgamated.hpp.
References m_optNames, and Opt().
operator[]() [2/2]
auto Catch::Clara::Opt::operator[] (std::string const & optName) ->Opt & inline
Definition at line 568 of file catch_clara.hpp.
References m_optNames, and Opt().
parse() [1/2]
Detail::InternalParseResult Catch::Clara::Opt::parse (std::string const & , Detail::TokenStream const & tokens) const override
Definition at line 2635 of file catch_amalgamated.cpp.
References Catch::Clara::Detail::Argument, isMatch(), Catch::Clara::Detail::ParserRefImpl< Opt >::m_ref, Catch::Clara::Matched, Catch::Clara::NoMatch, Catch::Clara::Detail::BasicResult< ParseState >::ok(), Catch::Clara::Detail::Option, Catch::Clara::Detail::BasicResult< ParseState >::runtimeError(), Catch::Clara::Detail::BoundFlagRefBase::setFlag(), Catch::Clara::ShortCircuitAll, and validate().
Referenced by TEST_CASE().
parse() [2/2]
Detail::InternalParseResult Catch::Clara::Opt::parse (std::string const & , Detail::TokenStream const & tokens) const override
validate() [1/2]
Detail::Result Catch::Clara::Opt::validate () const override
Definition at line 2687 of file catch_amalgamated.cpp.
References Catch::Clara::Detail::BasicResult< void >::logicError(), and m_optNames.
Referenced by parse().
validate() [2/2]
Detail::Result Catch::Clara::Opt::validate () const override
Member Data Documentation
m_optNames
std::vector< std::string > Catch::Clara::Opt::m_optNames protected
Definition at line 4970 of file catch_amalgamated.hpp.
Referenced by getHelpColumns(), isMatch(), operator[](), and validate().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_clara.cpp