libthe-seed: Catch::MultiReporter Class Reference
Catch::MultiReporter Class Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
void addListener (IEventListenerPtr &&listener)
void addReporter (IEventListenerPtr &&reporter)
void noMatchingTestCases (StringRef unmatchedSpec) override
Called when no test cases match provided test spec.
void fatalErrorEncountered (StringRef error) override
Called if a fatal error (signal/structured exception) occurred.
void reportInvalidTestSpec (StringRef arg) override
Called for all invalid test specs from the cli.
void benchmarkPreparing (StringRef name) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &benchmarkInfo) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &benchmarkStats) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef error) override
Called if running the benchmarks fails for any reason.
void testRunStarting (TestRunInfo const &testRunInfo) override
void testCaseStarting (TestCaseInfo const &testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &testInfo, uint64_t partNumber) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &assertionInfo) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &assertionStats) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &sectionStats) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &testInfo, uint64_t partNumber) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &testRunStats) override
void skipTest (TestCaseInfo const &testInfo) override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
Writes out information about provided reporters using reporter-specific format.
void listListeners (std::vector< ListenerDescription > const &descriptions) override
Writes out the provided listeners descriptions using reporter-specific format.
void listTests (std::vector< TestCaseHandle > const &tests) override
Writes out information about provided tests using reporter-specific format.
void listTags (std::vector< TagInfo > const &tags) override
Writes out information about the provided tags using reporter-specific format.
void addListener (IEventListenerPtr &&listener)
void addReporter (IEventListenerPtr &&reporter)
void noMatchingTestCases (StringRef unmatchedSpec) override
Called when no test cases match provided test spec.
void fatalErrorEncountered (StringRef error) override
Called if a fatal error (signal/structured exception) occurred.
void reportInvalidTestSpec (StringRef arg) override
Called for all invalid test specs from the cli.
void benchmarkPreparing (StringRef name) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &benchmarkInfo) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &benchmarkStats) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef error) override
Called if running the benchmarks fails for any reason.
void testRunStarting (TestRunInfo const &testRunInfo) override
void testCaseStarting (TestCaseInfo const &testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &testInfo, uint64_t partNumber) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &assertionInfo) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &assertionStats) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &sectionStats) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &testInfo, uint64_t partNumber) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &testRunStats) override
void skipTest (TestCaseInfo const &testInfo) override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
Writes out information about provided reporters using reporter-specific format.
void listListeners (std::vector< ListenerDescription > const &descriptions) override
Writes out the provided listeners descriptions using reporter-specific format.
void listTests (std::vector< TestCaseHandle > const &tests) override
Writes out information about provided tests using reporter-specific format.
void listTags (std::vector< TagInfo > const &tags) override
Writes out information about the provided tags using reporter-specific format.
IEventListener (IConfig const *config)
Public Member Functions inherited from Catch::IEventListener
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
Additional Inherited Members
Protected Attributes inherited from Catch::IEventListener
ReporterPreferences m_preferences
Derived classes can set up their preferences here.
IConfig const * m_config
The test run's config as filled in from CLI and defaults.
Detailed Description
Definition at line 12755 of file catch_amalgamated.hpp.
Member Function Documentation
addListener() [1/2]
void Catch::MultiReporter::addListener (IEventListenerPtr && listener)
Definition at line 9723 of file catch_amalgamated.cpp.
References CATCH_MOVE.
addListener() [2/2]
void Catch::MultiReporter::addListener (IEventListenerPtr && listener)
addReporter() [1/2]
void Catch::MultiReporter::addReporter (IEventListenerPtr && reporter)
Definition at line 9729 of file catch_amalgamated.cpp.
References CATCH_MOVE.
addReporter() [2/2]
void Catch::MultiReporter::addReporter (IEventListenerPtr && reporter)
assertionEnded() [1/2]
void Catch::MultiReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Implements Catch::IEventListener.
Definition at line 9816 of file catch_amalgamated.cpp.
References Catch::AssertionStats::assertionResult, Catch::AssertionResult::getResultType(), Catch::IEventListener::m_config, and Catch::ResultWas::Ok.
assertionEnded() [2/2]
void Catch::MultiReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Implements Catch::IEventListener.
assertionStarting() [1/2]
void Catch::MultiReporter::assertionStarting (AssertionInfo const & assertionInfo) override virtual
Called before assertion success/failure is evaluated.
Implements Catch::IEventListener.
Definition at line 9810 of file catch_amalgamated.cpp.
assertionStarting() [2/2]
void Catch::MultiReporter::assertionStarting (AssertionInfo const & assertionInfo) override virtual
Called before assertion success/failure is evaluated.
Implements Catch::IEventListener.
benchmarkEnded() [1/2]
void Catch::MultiReporter::benchmarkEnded (BenchmarkStats<> const & benchmarkStats) override virtual
Called with the benchmark results if benchmark successfully finishes.
Implements Catch::IEventListener.
Definition at line 9772 of file catch_amalgamated.cpp.
benchmarkEnded() [2/2]
void Catch::MultiReporter::benchmarkEnded (BenchmarkStats<> const & benchmarkStats) override virtual
Called with the benchmark results if benchmark successfully finishes.
Implements Catch::IEventListener.
benchmarkFailed() [1/2]
void Catch::MultiReporter::benchmarkFailed (StringRef benchmarkName) override virtual
Called if running the benchmarks fails for any reason.
Implements Catch::IEventListener.
Definition at line 9778 of file catch_amalgamated.cpp.
benchmarkFailed() [2/2]
void Catch::MultiReporter::benchmarkFailed (StringRef benchmarkName) override virtual
Called if running the benchmarks fails for any reason.
Implements Catch::IEventListener.
benchmarkPreparing() [1/2]
void Catch::MultiReporter::benchmarkPreparing (StringRef benchmarkName) override virtual
Called when user-code is being probed before the actual benchmark runs.
Implements Catch::IEventListener.
Definition at line 9762 of file catch_amalgamated.cpp.
benchmarkPreparing() [2/2]
void Catch::MultiReporter::benchmarkPreparing (StringRef benchmarkName) override virtual
Called when user-code is being probed before the actual benchmark runs.
Implements Catch::IEventListener.
benchmarkStarting() [1/2]
void Catch::MultiReporter::benchmarkStarting (BenchmarkInfo const & benchmarkInfo) override virtual
Called after probe but before the user-code is being benchmarked.
Implements Catch::IEventListener.
Definition at line 9767 of file catch_amalgamated.cpp.
benchmarkStarting() [2/2]
void Catch::MultiReporter::benchmarkStarting (BenchmarkInfo const & benchmarkInfo) override virtual
Called after probe but before the user-code is being benchmarked.
Implements Catch::IEventListener.
fatalErrorEncountered() [1/2]
void Catch::MultiReporter::fatalErrorEncountered (StringRef error) override virtual
Called if a fatal error (signal/structured exception) occurred.
Implements Catch::IEventListener.
Definition at line 9750 of file catch_amalgamated.cpp.
fatalErrorEncountered() [2/2]
void Catch::MultiReporter::fatalErrorEncountered (StringRef error) override virtual
Called if a fatal error (signal/structured exception) occurred.
Implements Catch::IEventListener.
IEventListener()
Catch::IEventListener::IEventListener (IConfig const * config) inline
Definition at line 8392 of file catch_amalgamated.hpp.
listListeners() [1/2]
void Catch::MultiReporter::listListeners (std::vector< ListenerDescription > const & descriptions) override virtual
Writes out the provided listeners descriptions using reporter-specific format.
Implements Catch::IEventListener.
Definition at line 9877 of file catch_amalgamated.cpp.
listListeners() [2/2]
void Catch::MultiReporter::listListeners (std::vector< ListenerDescription > const & descriptions) override virtual
Writes out the provided listeners descriptions using reporter-specific format.
Implements Catch::IEventListener.
listReporters() [1/2]
void Catch::MultiReporter::listReporters (std::vector< ReporterDescription > const & descriptions) override virtual
Writes out information about provided reporters using reporter-specific format.
Implements Catch::IEventListener.
Definition at line 9871 of file catch_amalgamated.cpp.
listReporters() [2/2]
void Catch::MultiReporter::listReporters (std::vector< ReporterDescription > const & descriptions) override virtual
Writes out information about provided reporters using reporter-specific format.
Implements Catch::IEventListener.
listTags() [1/2]
void Catch::MultiReporter::listTags (std::vector< TagInfo > const & tags) override virtual
Writes out information about the provided tags using reporter-specific format.
Implements Catch::IEventListener.
Definition at line 9890 of file catch_amalgamated.cpp.
listTags() [2/2]
void Catch::MultiReporter::listTags (std::vector< TagInfo > const & tags) override virtual
Writes out information about the provided tags using reporter-specific format.
Implements Catch::IEventListener.
listTests() [1/2]
void Catch::MultiReporter::listTests (std::vector< TestCaseHandle > const & tests) override virtual
Writes out information about provided tests using reporter-specific format.
Implements Catch::IEventListener.
Definition at line 9884 of file catch_amalgamated.cpp.
listTests() [2/2]
void Catch::MultiReporter::listTests (std::vector< TestCaseHandle > const & tests) override virtual
Writes out information about provided tests using reporter-specific format.
Implements Catch::IEventListener.
noMatchingTestCases() [1/2]
void Catch::MultiReporter::noMatchingTestCases (StringRef unmatchedSpec) override virtual
Called when no test cases match provided test spec.
Implements Catch::IEventListener.
Definition at line 9744 of file catch_amalgamated.cpp.
noMatchingTestCases() [2/2]
void Catch::MultiReporter::noMatchingTestCases (StringRef unmatchedSpec) override virtual
Called when no test cases match provided test spec.
Implements Catch::IEventListener.
reportInvalidTestSpec() [1/2]
void Catch::MultiReporter::reportInvalidTestSpec (StringRef invalidArgument) override virtual
Called for all invalid test specs from the cli.
Implements Catch::IEventListener.
Definition at line 9756 of file catch_amalgamated.cpp.
reportInvalidTestSpec() [2/2]
void Catch::MultiReporter::reportInvalidTestSpec (StringRef invalidArgument) override virtual
Called for all invalid test specs from the cli.
Implements Catch::IEventListener.
sectionEnded() [1/2]
void Catch::MultiReporter::sectionEnded (SectionStats const & sectionStats) override virtual
Called after a SECTION has finished running.
Implements Catch::IEventListener.
Definition at line 9829 of file catch_amalgamated.cpp.
sectionEnded() [2/2]
void Catch::MultiReporter::sectionEnded (SectionStats const & sectionStats) override virtual
Called after a SECTION has finished running.
Implements Catch::IEventListener.
sectionStarting() [1/2]
void Catch::MultiReporter::sectionStarting (SectionInfo const & sectionInfo) override virtual
Called when a SECTION is being entered. Not called for skipped sections.
Implements Catch::IEventListener.
Definition at line 9804 of file catch_amalgamated.cpp.
sectionStarting() [2/2]
void Catch::MultiReporter::sectionStarting (SectionInfo const & sectionInfo) override virtual
Called when a SECTION is being entered. Not called for skipped sections.
Implements Catch::IEventListener.
skipTest() [1/2]
void Catch::MultiReporter::skipTest (TestCaseInfo const & testInfo) override virtual
Called with test cases that are skipped due to the test run aborting. NOT called for test cases that are explicitly skipped using the SKIP macro.
Deprecated - will be removed in the next major release.
Implements Catch::IEventListener.
Definition at line 9865 of file catch_amalgamated.cpp.
skipTest() [2/2]
void Catch::MultiReporter::skipTest (TestCaseInfo const & testInfo) override virtual
Called with test cases that are skipped due to the test run aborting. NOT called for test cases that are explicitly skipped using the SKIP macro.
Deprecated - will be removed in the next major release.
Implements Catch::IEventListener.
testCaseEnded() [1/2]
void Catch::MultiReporter::testCaseEnded (TestCaseStats const & testCaseStats) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
Definition at line 9852 of file catch_amalgamated.cpp.
testCaseEnded() [2/2]
void Catch::MultiReporter::testCaseEnded (TestCaseStats const & testCaseStats) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
testCasePartialEnded() [1/2]
void Catch::MultiReporter::testCasePartialEnded (TestCaseStats const & testCaseStats, uint64_t partNumber) override virtual
Called every time a TEST_CASE is entered, including repeats (due to sections).
Implements Catch::IEventListener.
Definition at line 9835 of file catch_amalgamated.cpp.
References Catch::cerr(), Catch::cout(), Catch::IEventListener::m_preferences, Catch::TestCaseStats::stdErr, and Catch::TestCaseStats::stdOut.
testCasePartialEnded() [2/2]
void Catch::MultiReporter::testCasePartialEnded (TestCaseStats const & testCaseStats, uint64_t partNumber) override virtual
Called every time a TEST_CASE is entered, including repeats (due to sections).
Implements Catch::IEventListener.
testCasePartialStarting() [1/2]
void Catch::MultiReporter::testCasePartialStarting (TestCaseInfo const & testInfo, uint64_t partNumber) override virtual
Called every time a TEST_CASE is entered, including repeats (due to sections).
Implements Catch::IEventListener.
Definition at line 9797 of file catch_amalgamated.cpp.
testCasePartialStarting() [2/2]
void Catch::MultiReporter::testCasePartialStarting (TestCaseInfo const & testInfo, uint64_t partNumber) override virtual
Called every time a TEST_CASE is entered, including repeats (due to sections).
Implements Catch::IEventListener.
testCaseStarting() [1/2]
void Catch::MultiReporter::testCaseStarting (TestCaseInfo const & testInfo) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
Definition at line 9790 of file catch_amalgamated.cpp.
testCaseStarting() [2/2]
void Catch::MultiReporter::testCaseStarting (TestCaseInfo const & testInfo) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
testRunEnded() [1/2]
void Catch::MultiReporter::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Implements Catch::IEventListener.
Definition at line 9858 of file catch_amalgamated.cpp.
testRunEnded() [2/2]
void Catch::MultiReporter::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Implements Catch::IEventListener.
testRunStarting() [1/2]
void Catch::MultiReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Implements Catch::IEventListener.
Definition at line 9784 of file catch_amalgamated.cpp.
testRunStarting() [2/2]
void Catch::MultiReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Implements Catch::IEventListener.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/reporters/catch_reporter_multi.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/reporters/catch_reporter_multi.cpp