libthe-seed: Catch::IMutableEnumValuesRegistry Class Reference
Catch::IMutableEnumValuesRegistry Class Reference abstract
#include <catch_amalgamated.hpp>
Public Member Functions
virtual ~IMutableEnumValuesRegistry ()
virtual Detail::EnumInfo const & registerEnum (StringRef enumName, StringRef allEnums, std::vector< int > const &values)=0
template<typename E>
Detail::EnumInfo const & registerEnum (StringRef enumName, StringRef allEnums, std::initializer_list< E > values)
virtual ~IMutableEnumValuesRegistry ()
virtual Detail::EnumInfo const & registerEnum (StringRef enumName, StringRef allEnums, std::vector< int > const &values)=0
template<typename E>
Detail::EnumInfo const & registerEnum (StringRef enumName, StringRef allEnums, std::initializer_list< E > values)
Detailed Description
Definition at line 2588 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
~IMutableEnumValuesRegistry() [1/2]
Catch::IMutableEnumValuesRegistry::~IMutableEnumValuesRegistry () virtual default
~IMutableEnumValuesRegistry() [2/2]
virtual Catch::IMutableEnumValuesRegistry::~IMutableEnumValuesRegistry () virtual
Member Function Documentation
registerEnum() [1/4]
template<typename E> Detail::EnumInfo const & Catch::IMutableEnumValuesRegistry::registerEnum (StringRef enumName, StringRef allEnums, std::initializer_list< E > values) inline
Definition at line 2595 of file catch_amalgamated.hpp.
References registerEnum().
registerEnum() [2/4]
template<typename E> Detail::EnumInfo const & Catch::IMutableEnumValuesRegistry::registerEnum (StringRef enumName, StringRef allEnums, std::initializer_list< E > values) inline
Definition at line 35 of file catch_interfaces_enum_values_registry.hpp.
References registerEnum().
registerEnum() [3/4]
virtual Detail::EnumInfo const & Catch::IMutableEnumValuesRegistry::registerEnum (StringRef enumName, StringRef allEnums, std::vector< int > const & values) pure virtual
Referenced by registerEnum().
registerEnum() [4/4]
virtual Detail::EnumInfo const & Catch::IMutableEnumValuesRegistry::registerEnum (StringRef enumName, StringRef allEnums, std::vector< int > const & values) pure virtual
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/interfaces/catch_interfaces_enum_values_registry.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_enum_values_registry.cpp