libthe-seed: Catch::Clara::Detail::TokenStream Class Reference
Catch::Clara::Detail::TokenStream Class Reference
#include <catch_amalgamated.hpp>
Public Member Functions
TokenStream (Args const &args)
TokenStream (Iterator it, Iterator itEnd)
operator bool () const
size_t count () const
Token operator* () const
Token const * operator-> () const
TokenStream & operator++ ()
TokenStream (Args const &args)
TokenStream (Iterator it, Iterator itEnd)
operator bool () const
size_t count () const
Token operator* () const
Token const * operator-> () const
TokenStream & operator++ ()
Detailed Description
Definition at line 4537 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
TokenStream() [1/4]
Catch::Clara::Detail::TokenStream::TokenStream (Args const & args) explicit
Definition at line 2516 of file catch_amalgamated.cpp.
References TokenStream().
Referenced by operator++(), and TokenStream().
TokenStream() [2/4]
Catch::Clara::Detail::TokenStream::TokenStream (Iterator it, Iterator itEnd)
Definition at line 2519 of file catch_amalgamated.cpp.
TokenStream() [3/4]
Catch::Clara::Detail::TokenStream::TokenStream (Args const & args) explicit
TokenStream() [4/4]
Catch::Clara::Detail::TokenStream::TokenStream (Iterator it, Iterator itEnd)
Member Function Documentation
count() [1/2]
size_t Catch::Clara::Detail::TokenStream::count () const inline
Definition at line 4553 of file catch_amalgamated.hpp.
count() [2/2]
size_t Catch::Clara::Detail::TokenStream::count () const inline
Definition at line 125 of file catch_clara.hpp.
operator bool() [1/2]
Catch::Clara::Detail::TokenStream::operator bool () const inline explicit
Definition at line 4549 of file catch_amalgamated.hpp.
operator bool() [2/2]
Catch::Clara::Detail::TokenStream::operator bool () const inline explicit
Definition at line 121 of file catch_clara.hpp.
operator*() [1/2]
Token Catch::Clara::Detail::TokenStream::operator* () const inline
Definition at line 4557 of file catch_amalgamated.hpp.
operator*() [2/2]
Token Catch::Clara::Detail::TokenStream::operator* () const inline
Definition at line 129 of file catch_clara.hpp.
operator++() [1/2]
TokenStream & Catch::Clara::Detail::TokenStream::operator++ ()
Definition at line 2524 of file catch_amalgamated.cpp.
References TokenStream().
operator++() [2/2]
TokenStream & Catch::Clara::Detail::TokenStream::operator++ ()
References TokenStream().
operator->() [1/2]
Token const * Catch::Clara::Detail::TokenStream::operator-> () const inline
Definition at line 4562 of file catch_amalgamated.hpp.
operator->() [2/2]
Token const * Catch::Clara::Detail::TokenStream::operator-> () const inline
Definition at line 134 of file catch_clara.hpp.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_clara.cpp