libthe-seed: Catch::ConsoleReporter Class Reference
Catch::ConsoleReporter Class Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
ConsoleReporter (ReporterConfig &&config)
~ConsoleReporter () override
void noMatchingTestCases (StringRef unmatchedSpec) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef arg) override
Called for all invalid test specs from the cli.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &_assertionStats) override
Called after assertion was fully evaluated.
void sectionStarting (SectionInfo const &_sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void sectionEnded (SectionStats const &_sectionStats) override
Called after a SECTION has finished running.
void benchmarkPreparing (StringRef name) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &info) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &stats) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef error) override
Called if running the benchmarks fails for any reason.
void testCaseEnded (TestCaseStats const &_testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &_testRunStats) override
void testRunStarting (TestRunInfo const &_testRunInfo) override
ConsoleReporter (ReporterConfig &&config)
~ConsoleReporter () override
void noMatchingTestCases (StringRef unmatchedSpec) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef arg) override
Called for all invalid test specs from the cli.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &_assertionStats) override
Called after assertion was fully evaluated.
void sectionStarting (SectionInfo const &_sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void sectionEnded (SectionStats const &_sectionStats) override
Called after a SECTION has finished running.
void benchmarkPreparing (StringRef name) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &info) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &stats) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef error) override
Called if running the benchmarks fails for any reason.
void testCaseEnded (TestCaseStats const &_testCaseStats) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &_testRunStats) override
void testRunStarting (TestRunInfo const &_testRunInfo) override
Public Member Functions inherited from Catch::StreamingReporterBase
StreamingReporterBase (ReporterConfig &&_config)
~StreamingReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void testRunStarting (TestRunInfo const &_testRunInfo) override
void testCaseStarting (TestCaseInfo const &_testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &_sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &) override
void skipTest (TestCaseInfo const &) override
StreamingReporterBase (ReporterConfig &&_config)
~StreamingReporterBase () override
void benchmarkPreparing (StringRef) override
Called when user-code is being probed before the actual benchmark runs.
void benchmarkStarting (BenchmarkInfo const &) override
Called after probe but before the user-code is being benchmarked.
void benchmarkEnded (BenchmarkStats<> const &) override
Called with the benchmark results if benchmark successfully finishes.
void benchmarkFailed (StringRef) override
Called if running the benchmarks fails for any reason.
void fatalErrorEncountered (StringRef) override
Called if a fatal error (signal/structured exception) occurred.
void noMatchingTestCases (StringRef) override
Called when no test cases match provided test spec.
void reportInvalidTestSpec (StringRef) override
Called for all invalid test specs from the cli.
void testRunStarting (TestRunInfo const &_testRunInfo) override
void testCaseStarting (TestCaseInfo const &_testInfo) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testCasePartialStarting (TestCaseInfo const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void sectionStarting (SectionInfo const &_sectionInfo) override
Called when a SECTION is being entered. Not called for skipped sections.
void assertionStarting (AssertionInfo const &) override
Called before assertion success/failure is evaluated.
void assertionEnded (AssertionStats const &) override
Called after assertion was fully evaluated.
void sectionEnded (SectionStats const &) override
Called after a SECTION has finished running.
void testCasePartialEnded (TestCaseStats const &, uint64_t) override
Called every time a TEST_CASE is entered, including repeats (due to sections).
void testCaseEnded (TestCaseStats const &) override
Called once for each TEST_CASE, no matter how many times it is entered.
void testRunEnded (TestRunStats const &) override
void skipTest (TestCaseInfo const &) override
Public Member Functions inherited from Catch::ReporterBase
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
ReporterBase (ReporterConfig &&config)
~ReporterBase () override
void listReporters (std::vector< ReporterDescription > const &descriptions) override
void listListeners (std::vector< ListenerDescription > const &descriptions) override
void listTests (std::vector< TestCaseHandle > const &tests) override
void listTags (std::vector< TagInfo > const &tags) override
Public Member Functions inherited from Catch::IEventListener
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
IEventListener (IConfig const *config)
virtual ~IEventListener ()
ReporterPreferences const & getPreferences () const
Static Public Member Functions
static std::string getDescription ()
static std::string getDescription ()
Additional Inherited Members
Protected Attributes inherited from Catch::StreamingReporterBase
TestRunInfo currentTestRunInfo { "test run has not started yet"_sr }
TestCaseInfo const * currentTestCaseInfo = nullptr
std::vector< SectionInfo > m_sectionStack
Stack of all active sections in the current test case.
Protected Attributes inherited from Catch::ReporterBase
Detail::unique_ptr< IStream > m_wrapped_stream
The stream wrapper as passed to us by outside code.
std::ostream & m_stream
Cached output stream from m_wrapped_stream to reduce number of indirect calls needed to write output.
Detail::unique_ptr< ColourImpl > m_colour
Colour implementation this reporter was configured for.
std::map< std::string, std::string > m_customOptions
The custom reporter options user passed down to the reporter.
Protected Attributes inherited from Catch::IEventListener
ReporterPreferences m_preferences
Derived classes can set up their preferences here.
IConfig const * m_config
The test run's config as filled in from CLI and defaults.
Detailed Description
Definition at line 12364 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ConsoleReporter() [1/2]
Catch::ConsoleReporter::ConsoleReporter (ReporterConfig && config)
Definition at line 8616 of file catch_amalgamated.cpp.
References CATCH_MOVE, ConsoleReporter(), Catch::ReporterBase::m_stream, and Catch::StreamingReporterBase::StreamingReporterBase().
Referenced by ConsoleReporter().
~ConsoleReporter() [1/2]
Catch::ConsoleReporter::~ConsoleReporter () override default
References assertionEnded(), assertionStarting(), benchmarkEnded(), benchmarkFailed(), benchmarkPreparing(), benchmarkStarting(), getDescription(), noMatchingTestCases(), reportInvalidTestSpec(), sectionEnded(), sectionStarting(), testCaseEnded(), testRunEnded(), and testRunStarting().
ConsoleReporter() [2/2]
Catch::ConsoleReporter::ConsoleReporter (ReporterConfig && config)
~ConsoleReporter() [2/2]
Catch::ConsoleReporter::~ConsoleReporter () override
Member Function Documentation
assertionEnded() [1/2]
void Catch::ConsoleReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Implements Catch::IEventListener.
Definition at line 8655 of file catch_amalgamated.cpp.
References assertionEnded(), Catch::AssertionStats::assertionResult, Catch::ResultWas::ExplicitSkip, Catch::AssertionResult::getResultType(), Catch::AssertionResult::isOk(), Catch::ReporterBase::m_colour, Catch::IEventListener::m_config, Catch::ReporterBase::m_stream, and Catch::ResultWas::Warning.
Referenced by assertionEnded(), and ~ConsoleReporter().
assertionEnded() [2/2]
void Catch::ConsoleReporter::assertionEnded (AssertionStats const & assertionStats) override virtual
Called after assertion was fully evaluated.
Implements Catch::IEventListener.
assertionStarting() [1/2]
void Catch::ConsoleReporter::assertionStarting (AssertionInfo const & assertionInfo) override virtual
Called before assertion success/failure is evaluated.
Implements Catch::IEventListener.
Definition at line 8653 of file catch_amalgamated.cpp.
References assertionStarting().
Referenced by assertionStarting(), and ~ConsoleReporter().
assertionStarting() [2/2]
void Catch::ConsoleReporter::assertionStarting (AssertionInfo const & assertionInfo) override virtual
Called before assertion success/failure is evaluated.
Implements Catch::IEventListener.
benchmarkEnded() [1/2]
void Catch::ConsoleReporter::benchmarkEnded (BenchmarkStats<> const & benchmarkStats) override virtual
Called with the benchmark results if benchmark successfully finishes.
Implements Catch::IEventListener.
Definition at line 8722 of file catch_amalgamated.cpp.
References benchmarkEnded(), Catch::IEventListener::m_config, Catch::BenchmarkStats< Dummy >::mean, and Catch::BenchmarkStats< Dummy >::standardDeviation.
Referenced by benchmarkEnded(), and ~ConsoleReporter().
benchmarkEnded() [2/2]
void Catch::ConsoleReporter::benchmarkEnded (BenchmarkStats<> const & benchmarkStats) override virtual
Called with the benchmark results if benchmark successfully finishes.
Implements Catch::IEventListener.
benchmarkFailed() [1/2]
void Catch::ConsoleReporter::benchmarkFailed (StringRef benchmarkName) override virtual
Called if running the benchmarks fails for any reason.
Implements Catch::IEventListener.
Definition at line 8739 of file catch_amalgamated.cpp.
References benchmarkFailed(), Catch::ReporterBase::m_colour, Catch::ReporterBase::m_stream, and Catch::Colour::Red.
Referenced by benchmarkFailed(), and ~ConsoleReporter().
benchmarkFailed() [2/2]
void Catch::ConsoleReporter::benchmarkFailed (StringRef benchmarkName) override virtual
Called if running the benchmarks fails for any reason.
Implements Catch::IEventListener.
benchmarkPreparing() [1/2]
void Catch::ConsoleReporter::benchmarkPreparing (StringRef benchmarkName) override virtual
Called when user-code is being probed before the actual benchmark runs.
Implements Catch::IEventListener.
Definition at line 8699 of file catch_amalgamated.cpp.
References benchmarkPreparing(), and Catch::TextFlow::Column::width().
Referenced by benchmarkPreparing(), and ~ConsoleReporter().
benchmarkPreparing() [2/2]
void Catch::ConsoleReporter::benchmarkPreparing (StringRef benchmarkName) override virtual
Called when user-code is being probed before the actual benchmark runs.
Implements Catch::IEventListener.
benchmarkStarting() [1/2]
void Catch::ConsoleReporter::benchmarkStarting (BenchmarkInfo const & benchmarkInfo) override virtual
Called after probe but before the user-code is being benchmarked.
Implements Catch::IEventListener.
Definition at line 8716 of file catch_amalgamated.cpp.
References benchmarkStarting(), Catch::BenchmarkInfo::estimatedDuration, Catch::BenchmarkInfo::iterations, Catch::IEventListener::m_config, and Catch::BenchmarkInfo::samples.
Referenced by benchmarkStarting(), and ~ConsoleReporter().
benchmarkStarting() [2/2]
void Catch::ConsoleReporter::benchmarkStarting (BenchmarkInfo const & benchmarkInfo) override virtual
Called after probe but before the user-code is being benchmarked.
Implements Catch::IEventListener.
getDescription() [1/2]
std::string Catch::ConsoleReporter::getDescription () static
Definition at line 8641 of file catch_amalgamated.cpp.
References getDescription().
Referenced by getDescription(), and ~ConsoleReporter().
getDescription() [2/2]
std::string Catch::ConsoleReporter::getDescription () static
noMatchingTestCases() [1/2]
void Catch::ConsoleReporter::noMatchingTestCases (StringRef unmatchedSpec) override virtual
Called when no test cases match provided test spec.
Implements Catch::IEventListener.
Definition at line 8645 of file catch_amalgamated.cpp.
References Catch::ReporterBase::m_stream, and noMatchingTestCases().
Referenced by noMatchingTestCases(), and ~ConsoleReporter().
noMatchingTestCases() [2/2]
void Catch::ConsoleReporter::noMatchingTestCases (StringRef unmatchedSpec) override virtual
Called when no test cases match provided test spec.
Implements Catch::IEventListener.
reportInvalidTestSpec() [1/2]
void Catch::ConsoleReporter::reportInvalidTestSpec (StringRef invalidArgument) override virtual
Called for all invalid test specs from the cli.
Implements Catch::IEventListener.
Definition at line 8649 of file catch_amalgamated.cpp.
References Catch::ReporterBase::m_stream, and reportInvalidTestSpec().
Referenced by reportInvalidTestSpec(), and ~ConsoleReporter().
reportInvalidTestSpec() [2/2]
void Catch::ConsoleReporter::reportInvalidTestSpec (StringRef invalidArgument) override virtual
Called for all invalid test specs from the cli.
Implements Catch::IEventListener.
sectionEnded() [1/2]
void Catch::ConsoleReporter::sectionEnded (SectionStats const & sectionStats) override virtual
Called after a SECTION has finished running.
Implements Catch::IEventListener.
Definition at line 8677 of file catch_amalgamated.cpp.
References Catch::SectionStats::durationInSeconds, Catch::getFormattedDuration(), Catch::ReporterBase::m_colour, Catch::IEventListener::m_config, Catch::StreamingReporterBase::m_sectionStack, Catch::ReporterBase::m_stream, Catch::SectionStats::missingAssertions, Catch::SectionInfo::name, Catch::Colour::ResultError, sectionEnded(), Catch::StreamingReporterBase::sectionEnded(), Catch::SectionStats::sectionInfo, and Catch::shouldShowDuration().
Referenced by sectionEnded(), and ~ConsoleReporter().
sectionEnded() [2/2]
void Catch::ConsoleReporter::sectionEnded (SectionStats const & sectionStats) override virtual
Called after a SECTION has finished running.
Implements Catch::IEventListener.
sectionStarting() [1/2]
void Catch::ConsoleReporter::sectionStarting (SectionInfo const & sectionInfo) override virtual
Called when a SECTION is being entered. Not called for skipped sections.
Implements Catch::IEventListener.
Definition at line 8672 of file catch_amalgamated.cpp.
References sectionStarting(), and Catch::StreamingReporterBase::sectionStarting().
Referenced by sectionStarting(), and ~ConsoleReporter().
sectionStarting() [2/2]
void Catch::ConsoleReporter::sectionStarting (SectionInfo const & sectionInfo) override virtual
Called when a SECTION is being entered. Not called for skipped sections.
Implements Catch::IEventListener.
testCaseEnded() [1/2]
void Catch::ConsoleReporter::testCaseEnded (TestCaseStats const & testCaseStats) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
Definition at line 8746 of file catch_amalgamated.cpp.
References testCaseEnded(), and Catch::StreamingReporterBase::testCaseEnded().
Referenced by testCaseEnded(), and ~ConsoleReporter().
testCaseEnded() [2/2]
void Catch::ConsoleReporter::testCaseEnded (TestCaseStats const & testCaseStats) override virtual
Called once for each TEST_CASE, no matter how many times it is entered.
Implements Catch::IEventListener.
testRunEnded() [1/2]
void Catch::ConsoleReporter::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Implements Catch::IEventListener.
Definition at line 8751 of file catch_amalgamated.cpp.
References Catch::ReporterBase::m_colour, Catch::ReporterBase::m_stream, Catch::printTestRunTotals(), testRunEnded(), Catch::StreamingReporterBase::testRunEnded(), and Catch::TestRunStats::totals.
Referenced by testRunEnded(), and ~ConsoleReporter().
testRunEnded() [2/2]
void Catch::ConsoleReporter::testRunEnded (TestRunStats const & testRunStats) override virtual
Called once after all tests in a testing run are finished
Not called if tests weren't run (e.g. only listings happened)
Implements Catch::IEventListener.
testRunStarting() [1/2]
void Catch::ConsoleReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Implements Catch::IEventListener.
Definition at line 8757 of file catch_amalgamated.cpp.
References Catch::Colour::BrightYellow, Catch::getSeed(), Catch::ReporterBase::m_colour, Catch::IEventListener::m_config, Catch::ReporterBase::m_stream, testRunStarting(), and Catch::StreamingReporterBase::testRunStarting().
Referenced by testRunStarting(), and ~ConsoleReporter().
testRunStarting() [2/2]
void Catch::ConsoleReporter::testRunStarting (TestRunInfo const & testRunInfo) override virtual
Called once in a testing run before tests are started
Not called if tests won't be run (e.g. only listing will happen)
Implements Catch::IEventListener.
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/reporters/catch_reporter_console.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/reporters/catch_reporter_console.cpp