libthe-seed: Catch::Matchers::MatcherUntypedBase Class Reference
Catch::Matchers::MatcherUntypedBase Class Reference abstract
#include <catch_amalgamated.hpp>
Public Member Functions
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase (MatcherUntypedBase &&)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
MatcherUntypedBase & operator= (MatcherUntypedBase &&)=delete
std::string toString () const
Protected Member Functions
virtual ~MatcherUntypedBase ()
virtual std::string describe () const =0
virtual ~MatcherUntypedBase ()
virtual std::string describe () const =0
Protected Attributes
std::string m_cachedToString
Detailed Description
Definition at line 10696 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
MatcherUntypedBase() [1/6]
Catch::Matchers::MatcherUntypedBase::MatcherUntypedBase () default
Referenced by MatcherUntypedBase(), MatcherUntypedBase(), operator=(), and operator=().
MatcherUntypedBase() [2/6]
Catch::Matchers::MatcherUntypedBase::MatcherUntypedBase (MatcherUntypedBase const &) default
References MatcherUntypedBase().
MatcherUntypedBase() [3/6]
Catch::Matchers::MatcherUntypedBase::MatcherUntypedBase (MatcherUntypedBase &&) default
References MatcherUntypedBase().
~MatcherUntypedBase() [1/2]
Catch::Matchers::MatcherUntypedBase::~MatcherUntypedBase () protected virtual default
MatcherUntypedBase() [4/6]
Catch::Matchers::MatcherUntypedBase::MatcherUntypedBase () default
MatcherUntypedBase() [5/6]
Catch::Matchers::MatcherUntypedBase::MatcherUntypedBase (MatcherUntypedBase const &) default
References MatcherUntypedBase().
MatcherUntypedBase() [6/6]
Catch::Matchers::MatcherUntypedBase::MatcherUntypedBase (MatcherUntypedBase &&) default
References MatcherUntypedBase().
~MatcherUntypedBase() [2/2]
virtual Catch::Matchers::MatcherUntypedBase::~MatcherUntypedBase () protected virtual
Member Function Documentation
describe() [1/2]
virtual std::string Catch::Matchers::MatcherUntypedBase::describe () const protected pure virtual
Implemented in Catch::Matchers::AllMatchMatcher< Matcher >, Catch::Matchers::AllMatchMatcher< Matcher >, Catch::Matchers::AllTrueMatcher, Catch::Matchers::AllTrueMatcher, Catch::Matchers::AnyMatchMatcher< Matcher >, Catch::Matchers::AnyMatchMatcher< Matcher >, Catch::Matchers::AnyTrueMatcher, Catch::Matchers::AnyTrueMatcher, Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::ContainsElementMatcher< T, Equality >, Catch::Matchers::ContainsElementMatcher< T, Equality >, Catch::Matchers::ContainsMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::ContainsMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::ContainsMatcherMatcher< Matcher >, Catch::Matchers::ContainsMatcherMatcher< Matcher >, Catch::Matchers::Detail::MatchAllOf< ArgT >, Catch::Matchers::Detail::MatchAllOf< ArgT >, Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >, Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >, Catch::Matchers::Detail::MatchAnyOf< ArgT >, Catch::Matchers::Detail::MatchAnyOf< ArgT >, Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >, Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >, Catch::Matchers::Detail::MatchNotOf< ArgT >, Catch::Matchers::Detail::MatchNotOf< ArgT >, Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >, Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >, Catch::Matchers::EqualsMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::EqualsMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::ExceptionMessageMatcher, Catch::Matchers::ExceptionMessageMatcher, Catch::Matchers::ExceptionMessageMatchesMatcher< StringMatcherType >, Catch::Matchers::ExceptionMessageMatchesMatcher< StringMatcherType >, Catch::Matchers::HasSizeMatcher, Catch::Matchers::HasSizeMatcher, Catch::Matchers::IsEmptyMatcher, Catch::Matchers::IsEmptyMatcher, Catch::Matchers::IsNaNMatcher, Catch::Matchers::IsNaNMatcher, Catch::Matchers::NoneMatchMatcher< Matcher >, Catch::Matchers::NoneMatchMatcher< Matcher >, Catch::Matchers::NoneTrueMatcher, Catch::Matchers::NoneTrueMatcher, Catch::Matchers::PredicateMatcher< T, Predicate >, Catch::Matchers::PredicateMatcher< T, Predicate >, Catch::Matchers::RangeEqualsMatcher< TargetRangeLike, Equality >, Catch::Matchers::RangeEqualsMatcher< TargetRangeLike, Equality >, Catch::Matchers::RegexMatcher, Catch::Matchers::RegexMatcher, Catch::Matchers::SizeMatchesMatcher< Matcher >, Catch::Matchers::SizeMatchesMatcher< Matcher >, Catch::Matchers::StringMatcherBase, Catch::Matchers::StringMatcherBase, Catch::Matchers::UnorderedEqualsMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::UnorderedEqualsMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >, Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >, Catch::Matchers::VectorContainsElementMatcher< T, Alloc >, Catch::Matchers::VectorContainsElementMatcher< T, Alloc >, Catch::Matchers::WithinAbsMatcher, Catch::Matchers::WithinAbsMatcher, Catch::Matchers::WithinRelMatcher, Catch::Matchers::WithinRelMatcher, Catch::Matchers::WithinUlpsMatcher, and Catch::Matchers::WithinUlpsMatcher.
Referenced by toString().
describe() [2/2]
virtual std::string Catch::Matchers::MatcherUntypedBase::describe () const protected pure virtual
Implemented in Catch::Matchers::AllMatchMatcher< Matcher >, Catch::Matchers::AllMatchMatcher< Matcher >, Catch::Matchers::AllTrueMatcher, Catch::Matchers::AllTrueMatcher, Catch::Matchers::AnyMatchMatcher< Matcher >, Catch::Matchers::AnyMatchMatcher< Matcher >, Catch::Matchers::AnyTrueMatcher, Catch::Matchers::AnyTrueMatcher, Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::ContainsElementMatcher< T, Equality >, Catch::Matchers::ContainsElementMatcher< T, Equality >, Catch::Matchers::ContainsMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::ContainsMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::ContainsMatcherMatcher< Matcher >, Catch::Matchers::ContainsMatcherMatcher< Matcher >, Catch::Matchers::Detail::MatchAllOf< ArgT >, Catch::Matchers::Detail::MatchAllOf< ArgT >, Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >, Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >, Catch::Matchers::Detail::MatchAnyOf< ArgT >, Catch::Matchers::Detail::MatchAnyOf< ArgT >, Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >, Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >, Catch::Matchers::Detail::MatchNotOf< ArgT >, Catch::Matchers::Detail::MatchNotOf< ArgT >, Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >, Catch::Matchers::Detail::MatchNotOfGeneric< MatcherT >, Catch::Matchers::EqualsMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::EqualsMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::ExceptionMessageMatcher, Catch::Matchers::ExceptionMessageMatcher, Catch::Matchers::ExceptionMessageMatchesMatcher< StringMatcherType >, Catch::Matchers::ExceptionMessageMatchesMatcher< StringMatcherType >, Catch::Matchers::HasSizeMatcher, Catch::Matchers::HasSizeMatcher, Catch::Matchers::IsEmptyMatcher, Catch::Matchers::IsEmptyMatcher, Catch::Matchers::IsNaNMatcher, Catch::Matchers::IsNaNMatcher, Catch::Matchers::NoneMatchMatcher< Matcher >, Catch::Matchers::NoneMatchMatcher< Matcher >, Catch::Matchers::NoneTrueMatcher, Catch::Matchers::NoneTrueMatcher, Catch::Matchers::PredicateMatcher< T, Predicate >, Catch::Matchers::PredicateMatcher< T, Predicate >, Catch::Matchers::RangeEqualsMatcher< TargetRangeLike, Equality >, Catch::Matchers::RangeEqualsMatcher< TargetRangeLike, Equality >, Catch::Matchers::RegexMatcher, Catch::Matchers::RegexMatcher, Catch::Matchers::SizeMatchesMatcher< Matcher >, Catch::Matchers::SizeMatchesMatcher< Matcher >, Catch::Matchers::StringMatcherBase, Catch::Matchers::StringMatcherBase, Catch::Matchers::UnorderedEqualsMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::UnorderedEqualsMatcher< T, AllocComp, AllocMatch >, Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >, Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >, Catch::Matchers::VectorContainsElementMatcher< T, Alloc >, Catch::Matchers::VectorContainsElementMatcher< T, Alloc >, Catch::Matchers::WithinAbsMatcher, Catch::Matchers::WithinAbsMatcher, Catch::Matchers::WithinRelMatcher, Catch::Matchers::WithinRelMatcher, Catch::Matchers::WithinUlpsMatcher, and Catch::Matchers::WithinUlpsMatcher.
References m_cachedToString.
operator=() [1/4]
MatcherUntypedBase & Catch::Matchers::MatcherUntypedBase::operator= (MatcherUntypedBase &&) delete
References MatcherUntypedBase(), and toString().
operator=() [2/4]
MatcherUntypedBase & Catch::Matchers::MatcherUntypedBase::operator= (MatcherUntypedBase &&) delete
References MatcherUntypedBase().
operator=() [3/4]
MatcherUntypedBase & Catch::Matchers::MatcherUntypedBase::operator= (MatcherUntypedBase const &) delete
References MatcherUntypedBase().
operator=() [4/4]
MatcherUntypedBase & Catch::Matchers::MatcherUntypedBase::operator= (MatcherUntypedBase const &) delete
References MatcherUntypedBase().
toString() [1/2]
std::string Catch::Matchers::MatcherUntypedBase::toString () const
Definition at line 7480 of file catch_amalgamated.cpp.
References describe(), and m_cachedToString.
Referenced by operator=().
toString() [2/2]
std::string Catch::Matchers::MatcherUntypedBase::toString () const
Member Data Documentation
m_cachedToString
std::string Catch::Matchers::MatcherUntypedBase::m_cachedToString mutable protected
Definition at line 10711 of file catch_amalgamated.hpp.
Referenced by describe(), and toString().
The documentation for this class was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/matchers/catch_matchers.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/matchers/catch_matchers.cpp