libthe-seed: external/Catch2/tests/SelfTest/IntrospectiveTests/CmdLineHelpers.tests.cpp File Reference
CmdLineHelpers.tests.cpp File Reference
#include <catch2/catch_test_macros.hpp>
#include <catch2/internal/catch_reporter_spec_parser.hpp>
#include <catch2/matchers/catch_matchers_vector.hpp>
#include <catch2/interfaces/catch_interfaces_config.hpp>
Functions
TEST_CASE ("Reporter spec splitting", "[reporter-spec][cli][approvals]")
TEST_CASE ("Parsing colour mode", "[cli][colour][approvals]")
TEST_CASE ("Parsing reporter specs", "[cli][reporter-spec][approvals]")
Function Documentation
TEST_CASE() [1/3]
TEST_CASE ("Parsing colour mode" , "" [cli][colour][approvals])
Definition at line 49 of file CmdLineHelpers.tests.cpp.
References REQUIRE, REQUIRE_FALSE, SECTION, and Catch::Detail::stringToColourMode().
TEST_CASE() [2/3]
TEST_CASE ("Parsing reporter specs" , "" [cli][reporter-spec][approvals])
Definition at line 67 of file CmdLineHelpers.tests.cpp.
References Catch::ANSI, Catch::parseReporterSpec(), REQUIRE, REQUIRE_FALSE, and SECTION.
TEST_CASE() [3/3]
TEST_CASE ("Reporter spec splitting" , "" [reporter-spec][cli][approvals])
Definition at line 14 of file CmdLineHelpers.tests.cpp.
References Catch::Matchers::Equals(), REQUIRE_THAT, SECTION, and Catch::Detail::splitReporterSpec().