libthe-seed: external/Catch2/tools/misc/coverage-helper.cpp File Reference
coverage-helper.cpp File Reference
#include <algorithm>
#include <array>
#include <cassert>
#include <fstream>
#include <iostream>
#include <memory>
#include <numeric>
#include <regex>
#include <string>
#include <vector>
Functions
std::string escape_arg (const std::string &arg)
void create_empty_file (std::string const &path)
bool starts_with (std::string const &str, std::string const &pref)
int parse_log_file_arg (std::string const &arg)
std::string catch_path (std::string path)
std::string windowsify_path (std::string path)
int exec_cmd (std::string const &cmd, int log_num, std::string const &path)
int main (int argc, char **argv)
Variables
const std::string separator = "--sep--"
const std::string logfile_prefix = "--log-file="
Function Documentation
catch_path()
std::string catch_path (std::string path)
Definition at line 71 of file coverage-helper.cpp.
Referenced by main().
create_empty_file()
void create_empty_file (std::string const & path)
Definition at line 46 of file coverage-helper.cpp.
Referenced by parse_log_file_arg().
escape_arg()
std::string escape_arg (const std::string & arg)
Definition at line 12 of file coverage-helper.cpp.
Referenced by exec_cmd(), and main().
exec_cmd()
int exec_cmd (std::string const & cmd, int log_num, std::string const & path)
Definition at line 93 of file coverage-helper.cpp.
References escape_arg().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 125 of file coverage-helper.cpp.
References catch_path(), escape_arg(), exec_cmd(), parse_log_file_arg(), separator, and windowsify_path().
parse_log_file_arg()
int parse_log_file_arg (std::string const & arg)
Definition at line 58 of file coverage-helper.cpp.
References create_empty_file(), logfile_prefix, and starts_with().
Referenced by main().
starts_with()
bool starts_with (std::string const & str, std::string const & pref)
Definition at line 54 of file coverage-helper.cpp.
Referenced by parse_log_file_arg().
windowsify_path()
std::string windowsify_path (std::string path)
Definition at line 84 of file coverage-helper.cpp.
Referenced by main().
Variable Documentation
logfile_prefix
const std::string logfile_prefix = "--log-file="
Definition at line 52 of file coverage-helper.cpp.
Referenced by parse_log_file_arg().
separator
const std::string separator = "--sep--"
Definition at line 51 of file coverage-helper.cpp.
Referenced by main(), and Catch::Detail::splitReporterSpec().