libthe-seed: external/Catch2/tests/SelfTest/UsageTests/Exception.tests.cpp File Reference
Exception.tests.cpp File Reference
#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_translate_exception.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>
#include <string>
#include <stdexcept>
Functions
TEST_CASE ("When checked exceptions are thrown they can be expected or unexpected", "[!throws]")
TEST_CASE ("Expected exceptions that don't throw or unexpected exceptions fail the test", "[.][failing][!throws]")
TEST_CASE ("When unchecked exceptions are thrown directly they are always failures", "[.][failing][!throws]")
TEST_CASE ("An unchecked exception reports the line of the last assertion", "[.][failing][!throws]")
TEST_CASE ("When unchecked exceptions are thrown from sections they are always failures", "[.][failing][!throws]")
TEST_CASE ("When unchecked exceptions are thrown from functions they are always failures", "[.][failing][!throws]")
TEST_CASE ("When unchecked exceptions are thrown during a REQUIRE the test should abort fail", "[.][failing][!throws]")
TEST_CASE ("When unchecked exceptions are thrown during a CHECK the test should continue", "[.][failing][!throws]")
TEST_CASE ("When unchecked exceptions are thrown, but caught, they do not affect the test", "[!throws]")
CATCH_TRANSLATE_EXCEPTION (CustomException const &ex)
CATCH_TRANSLATE_EXCEPTION (CustomStdException const &ex)
CATCH_TRANSLATE_EXCEPTION (double const &ex)
TEST_CASE ("Non-std exceptions can be translated", "[.][failing][!throws]")
TEST_CASE ("Custom std-exceptions can be custom translated", "[.][failing][!throws]")
TEST_CASE ("Custom exceptions can be translated when testing for nothrow", "[.][failing][!throws]")
TEST_CASE ("Custom exceptions can be translated when testing for throwing as something else", "[.][failing][!throws]")
TEST_CASE ("Unexpected exceptions can be translated", "[.][failing][!throws]")
TEST_CASE ("Thrown string literals are translated", "[.][failing][!throws]")
TEST_CASE ("thrown std::strings are translated", "[.][failing][!throws]")
TEST_CASE ("Exception messages can be tested for", "[!throws]")
TEST_CASE ("Mismatching exception messages failing the test", "[.][failing][!throws]")
TEST_CASE ("#748 - captures with unexpected exceptions", "[.][failing][!throws][!shouldfail]")
Function Documentation
CATCH_TRANSLATE_EXCEPTION() [1/3]
CATCH_TRANSLATE_EXCEPTION (CustomException const & ex)
Definition at line 126 of file Exception.tests.cpp.
CATCH_TRANSLATE_EXCEPTION() [2/3]
CATCH_TRANSLATE_EXCEPTION (CustomStdException const & ex)
Definition at line 130 of file Exception.tests.cpp.
CATCH_TRANSLATE_EXCEPTION() [3/3]
CATCH_TRANSLATE_EXCEPTION (double const & ex)
Definition at line 134 of file Exception.tests.cpp.
References Catch::Detail::stringify().
TEST_CASE() [1/19]
TEST_CASE ("#748 - captures with unexpected exceptions" , "" [.][failing][!throws][!shouldfail])
Definition at line 187 of file Exception.tests.cpp.
References CAPTURE, REQUIRE_NOTHROW, REQUIRE_THROWS, and SECTION.
TEST_CASE() [2/19]
TEST_CASE ("An unchecked exception reports the line of the last assertion" , "" [.][failing][!throws])
Definition at line 89 of file Exception.tests.cpp.
References CHECK.
TEST_CASE() [3/19]
TEST_CASE ("Custom exceptions can be translated when testing for nothrow" , "" [.][failing][!throws])
Definition at line 146 of file Exception.tests.cpp.
References REQUIRE_NOTHROW.
TEST_CASE() [4/19]
TEST_CASE ("Custom exceptions can be translated when testing for throwing as something else" , "" [.][failing][!throws])
Definition at line 150 of file Exception.tests.cpp.
References REQUIRE_THROWS_AS.
TEST_CASE() [5/19]
TEST_CASE ("Custom std-exceptions can be custom translated" , "" [.][failing][!throws])
Definition at line 142 of file Exception.tests.cpp.
TEST_CASE() [6/19]
TEST_CASE ("Exception messages can be tested for" , "" [!throws])
Definition at line 167 of file Exception.tests.cpp.
References Catch::Matchers::ContainsSubstring(), Catch::Matchers::EndsWith(), Catch::Matchers::Equals(), Catch::No, REQUIRE_THROWS_WITH, SECTION, and Catch::Matchers::StartsWith().
TEST_CASE() [7/19]
TEST_CASE ("Expected exceptions that don't throw or unexpected exceptions fail the test" , "" [.][failing][!throws])
Definition at line 79 of file Exception.tests.cpp.
References CHECK_NOTHROW, and CHECK_THROWS_AS.
TEST_CASE() [8/19]
TEST_CASE ("Mismatching exception messages failing the test" , "" [.][failing][!throws])
Definition at line 181 of file Exception.tests.cpp.
References REQUIRE_THROWS_WITH.
TEST_CASE() [9/19]
TEST_CASE ("Non-std exceptions can be translated" , "" [.][failing][!throws])
Definition at line 138 of file Exception.tests.cpp.
TEST_CASE() [10/19]
TEST_CASE ("thrown std::strings are translated" , "" [.][failing][!throws])
Definition at line 162 of file Exception.tests.cpp.
TEST_CASE() [11/19]
TEST_CASE ("Thrown string literals are translated" , "" [.][failing][!throws])
Definition at line 158 of file Exception.tests.cpp.
TEST_CASE() [12/19]
TEST_CASE ("Unexpected exceptions can be translated" , "" [.][failing][!throws])
Definition at line 154 of file Exception.tests.cpp.
TEST_CASE() [13/19]
TEST_CASE ("When checked exceptions are thrown they can be expected or unexpected" , "" [!throws])
Definition at line 73 of file Exception.tests.cpp.
References REQUIRE_NOTHROW, REQUIRE_THROWS, and REQUIRE_THROWS_AS.
TEST_CASE() [14/19]
TEST_CASE ("When unchecked exceptions are thrown directly they are always failures" , "" [.][failing][!throws])
Definition at line 85 of file Exception.tests.cpp.
TEST_CASE() [15/19]
TEST_CASE ("When unchecked exceptions are thrown during a CHECK the test should continue" , "" [.][failing][!throws])
Definition at line 109 of file Exception.tests.cpp.
References CHECK, and FAIL.
TEST_CASE() [16/19]
TEST_CASE ("When unchecked exceptions are thrown during a REQUIRE the test should abort fail" , "" [.][failing][!throws])
Definition at line 104 of file Exception.tests.cpp.
References FAIL, and REQUIRE.
TEST_CASE() [17/19]
TEST_CASE ("When unchecked exceptions are thrown from functions they are always failures" , "" [.][failing][!throws])
Definition at line 100 of file Exception.tests.cpp.
References CHECK.
TEST_CASE() [18/19]
TEST_CASE ("When unchecked exceptions are thrown from sections they are always failures" , "" [.][failing][!throws])
Definition at line 94 of file Exception.tests.cpp.
References SECTION.
TEST_CASE() [19/19]
TEST_CASE ("When unchecked exceptions are thrown, but caught, they do not affect the test" , "" [!throws])
Definition at line 118 of file Exception.tests.cpp.