libthe-seed: external/Catch2/tests/SelfTest/IntrospectiveTests/FloatingPoint.tests.cpp File Reference
FloatingPoint.tests.cpp File Reference
#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_template_test_macros.hpp>
#include <catch2/internal/catch_floating_point_helpers.hpp>
Functions
TEST_CASE ("convertToBits", "[floating-point][conversion]")
TEMPLATE_TEST_CASE ("type-shared ulpDistance tests", "[floating-point][ulp][approvals]", float, double)
TEST_CASE ("UlpDistance", "[floating-point][ulp][approvals]")
Function Documentation
TEMPLATE_TEST_CASE()
TEMPLATE_TEST_CASE ("type-shared ulpDistance tests" , "" [floating-point][ulp][approvals], float , double)
Definition at line 25 of file FloatingPoint.tests.cpp.
References CHECK, and Catch::ulpDistance().
TEST_CASE() [1/2]
TEST_CASE ("convertToBits" , "" [floating-point][conversion])
Definition at line 14 of file FloatingPoint.tests.cpp.
References CHECK, and Catch::Detail::convertToBits().
TEST_CASE() [2/2]
TEST_CASE ("UlpDistance" , "" [floating-point][ulp][approvals])
Definition at line 67 of file FloatingPoint.tests.cpp.
References CHECK, and Catch::ulpDistance().