libthe-seed: external/Catch2/tests/SelfTest/UsageTests/Generators.tests.cpp File Reference
Generators.tests.cpp File Reference
#include <catch2/catch_test_macros.hpp>
#include <catch2/generators/catch_generator_exception.hpp>
#include <catch2/generators/catch_generators_adapters.hpp>
#include <catch2/generators/catch_generators_random.hpp>
#include <catch2/generators/catch_generators_range.hpp>
#include <cstring>
Functions
TEST_CASE ("Generators -- simple", "[generators]")
TEST_CASE ("3x3x3 ints", "[generators]")
TEST_CASE ("tables", "[generators]")
TEST_CASE ("strlen3", "[generators]")
TEST_CASE ("Generators -- adapters", "[generators][generic]")
TEST_CASE ("Random generator", "[generators][approvals]")
TEST_CASE ("Nested generators and captured variables", "[generators]")
TEST_CASE ("Copy and then generate a range", "[generators]")
TEST_CASE ("#1913 - GENERATE inside a for loop should not keep recreating the generator", "[regression][generators]")
TEST_CASE ("#1913 - GENERATEs can share a line", "[regression][generators]")
TEST_CASE ("#2615 - Throwing in constructor generator fails test case but does not abort", "[!shouldfail]")
Function Documentation
TEST_CASE() [1/11]
TEST_CASE ("#1913 - GENERATE inside a for loop should not keep recreating the generator" , "" [regression][generators])
Definition at line 268 of file Generators.tests.cpp.
References GENERATE, and REQUIRE.
TEST_CASE() [2/11]
TEST_CASE ("#1913 - GENERATEs can share a line" , "" [regression][generators])
Definition at line 279 of file Generators.tests.cpp.
References GENERATE, and REQUIRE.
TEST_CASE() [3/11]
TEST_CASE ("#2615 - Throwing in constructor generator fails test case but does not abort" , "" [!shouldfail])
Definition at line 308 of file Generators.tests.cpp.
References GENERATE, and REQUIRE.
TEST_CASE() [4/11]
TEST_CASE ("3x3x3 ints" , "" [generators])
Definition at line 34 of file Generators.tests.cpp.
References CHECK, GENERATE, and REQUIRE.
TEST_CASE() [5/11]
TEST_CASE ("Copy and then generate a range" , "" [generators])
Definition at line 243 of file Generators.tests.cpp.
References Catch::Generators::from_range(), GENERATE, GENERATE_REF, REQUIRE, and SECTION.
TEST_CASE() [6/11]
TEST_CASE ("Generators -- adapters" , "" [generators][generic])
Definition at line 127 of file Generators.tests.cpp.
References Catch::Generators::chunk(), Catch::Generators::filter(), GENERATE, Catch::Generators::map(), Catch::Generators::repeat(), REQUIRE, REQUIRE_THROWS_AS, SECTION, Catch::Generators::take(), Catch::Generators::value(), and Catch::Generators::values().
TEST_CASE() [7/11]
TEST_CASE ("Generators -- simple" , "" [generators])
Definition at line 19 of file Generators.tests.cpp.
References GENERATE, REQUIRE, and SECTION.
TEST_CASE() [8/11]
TEST_CASE ("Nested generators and captured variables" , "" [generators])
Definition at line 209 of file Generators.tests.cpp.
References GENERATE, GENERATE_COPY, Catch::Generators::range(), REQUIRE, Catch::Generators::table(), and Catch::Generators::values().
TEST_CASE() [9/11]
TEST_CASE ("Random generator" , "" [generators][approvals])
Definition at line 193 of file Generators.tests.cpp.
References GENERATE, Catch::Generators::random(), REQUIRE, SECTION, STATIC_REQUIRE, Catch::Generators::take(), and Catch::Generators::value().
TEST_CASE() [10/11]
TEST_CASE ("strlen3" , "" [generators])
Definition at line 88 of file Generators.tests.cpp.
References GENERATE, and REQUIRE.
TEST_CASE() [11/11]
TEST_CASE ("tables" , "" [generators])
Definition at line 45 of file Generators.tests.cpp.
References GENERATE, and REQUIRE.