libthe-seed: external/Catch2/tests/SelfTest/IntrospectiveTests/GeneratorsImpl.tests.cpp File Reference
GeneratorsImpl.tests.cpp File Reference
#include <helpers/range_test_helpers.hpp>
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <catch2/generators/catch_generator_exception.hpp>
#include <catch2/generators/catch_generators_adapters.hpp>
#include <catch2/generators/catch_generators_random.hpp>
#include <catch2/generators/catch_generators_range.hpp>
Functions
TEST_CASE ("Generators internals", "[generators][internals]")
TEST_CASE ("GENERATE capture macros", "[generators][internals][approvals]")
TEST_CASE ("#1809 - GENERATE_COPY and SingleValueGenerator does not compile", "[generators][compilation][approvals]")
TEST_CASE ("Multiple random generators in one test case output different values", "[generators][internals][approvals]")
TEST_CASE ("#2040 - infinite compilation recursion in GENERATE with MSVC", "[generators][compilation][approvals]")
TEST_CASE ("GENERATE handles function (pointers)", "[generators][compilation][approvals]")
TEST_CASE ("GENERATE decays arrays", "[generators][compilation][approvals]")
TEST_CASE ("Generators count returned elements", "[generators][approvals]")
TEST_CASE ("Generators can stringify their elements", "[generators][approvals]")
TEST_CASE ("Generators can override element stringification", "[generators][approvals]")
TEST_CASE ("Generator element stringification is cached", "[generators][approvals]")
TEST_CASE ("Random generators can be seeded", "[generators][approvals]")
TEST_CASE ("Filter generator throws exception for empty generator", "[generators]")
TEST_CASE ("from_range(container) supports ADL begin/end and arrays", "[generators][from-range][approvals]")
Function Documentation
TEST_CASE() [1/14]
TEST_CASE ("#1809 - GENERATE_COPY and SingleValueGenerator does not compile" , "" [generators][compilation][approvals])
Definition at line 348 of file GeneratorsImpl.tests.cpp.
References GENERATE_COPY, and SUCCEED.
TEST_CASE() [2/14]
TEST_CASE ("#2040 - infinite compilation recursion in GENERATE with MSVC" , "" [generators][compilation][approvals])
Definition at line 390 of file GeneratorsImpl.tests.cpp.
References CHECK, and GENERATE_COPY.
TEST_CASE() [3/14]
TEST_CASE ("Filter generator throws exception for empty generator" , "" [generators])
Definition at line 542 of file GeneratorsImpl.tests.cpp.
References Catch::Generators::filter(), REQUIRE_THROWS_AS, and Catch::Generators::value().
TEST_CASE() [4/14]
TEST_CASE ("from_range(container) supports ADL begin/end and arrays" , "" [generators][from-range][approvals])
Definition at line 551 of file GeneratorsImpl.tests.cpp.
References Catch::Generators::from_range(), Catch::Generators::range(), REQUIRE, REQUIRE_FALSE, and SECTION.
TEST_CASE() [5/14]
TEST_CASE ("GENERATE capture macros" , "" [generators][internals][approvals])
Definition at line 339 of file GeneratorsImpl.tests.cpp.
References GENERATE, GENERATE_REF, Catch::Detail::make_unique(), Catch::Generators::random(), REQUIRE, Catch::Generators::take(), and Catch::Generators::value().
TEST_CASE() [6/14]
TEST_CASE ("GENERATE decays arrays" , "" [generators][compilation][approvals])
Definition at line 415 of file GeneratorsImpl.tests.cpp.
References GENERATE, STATIC_REQUIRE, and Catch::Generators::value().
TEST_CASE() [7/14]
TEST_CASE ("GENERATE handles function (pointers)" , "" [generators][compilation][approvals])
Definition at line 410 of file GeneratorsImpl.tests.cpp.
References f(), GENERATE, and REQUIRE.
TEST_CASE() [8/14]
TEST_CASE ("Generator element stringification is cached" , "" [generators][approvals])
Definition at line 507 of file GeneratorsImpl.tests.cpp.
References REQUIRE.
TEST_CASE() [9/14]
TEST_CASE ("Generators can override element stringification" , "" [generators][approvals])
Definition at line 469 of file GeneratorsImpl.tests.cpp.
References REQUIRE.
TEST_CASE() [10/14]
TEST_CASE ("Generators can stringify their elements" , "" [generators][approvals])
Definition at line 432 of file GeneratorsImpl.tests.cpp.
References REQUIRE.
TEST_CASE() [11/14]
TEST_CASE ("Generators count returned elements" , "" [generators][approvals])
Definition at line 421 of file GeneratorsImpl.tests.cpp.
References REQUIRE, and REQUIRE_FALSE.
TEST_CASE() [12/14]
TEST_CASE ("Generators internals" , "" [generators][internals])
Definition at line 24 of file GeneratorsImpl.tests.cpp.
References Catch::Generators::filter(), INFO, Catch::Generators::makeGenerators(), Catch::Generators::map(), Catch::Generators::range(), Catch::Generators::repeat(), REQUIRE, REQUIRE_FALSE, REQUIRE_THROWS_AS, SECTION, Catch::Generators::take(), Catch::Generators::value(), and Catch::Generators::values().
TEST_CASE() [13/14]
TEST_CASE ("Multiple random generators in one test case output different values" , "" [generators][internals][approvals])
Definition at line 363 of file GeneratorsImpl.tests.cpp.
References Catch::Generators::random(), REQUIRE, and SECTION.
TEST_CASE() [14/14]
TEST_CASE ("Random generators can be seeded" , "" [generators][approvals])
Definition at line 519 of file GeneratorsImpl.tests.cpp.
References Catch::Generators::RandomFloatingGenerator< Float >::get(), Catch::Generators::RandomIntegerGenerator< Integer >::get(), Catch::Generators::RandomFloatingGenerator< Float >::next(), Catch::Generators::RandomIntegerGenerator< Integer >::next(), REQUIRE, and SECTION.