libthe-seed: external/Catch2/tests/SelfTest/IntrospectiveTests/InternalBenchmark.tests.cpp File Reference
InternalBenchmark.tests.cpp File Reference
#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_approx.hpp>
#include <catch2/catch_config.hpp>
#include <catch2/benchmark/catch_benchmark.hpp>
#include <catch2/benchmark/catch_chronometer.hpp>
#include <catch2/benchmark/detail/catch_analyse.hpp>
#include <catch2/benchmark/detail/catch_benchmark_function.hpp>
#include <catch2/benchmark/detail/catch_estimate_clock.hpp>
#include <numeric>
Functions
TEST_CASE ("warmup", "[benchmark]")
TEST_CASE ("resolution", "[benchmark]")
TEST_CASE ("estimate_clock_resolution", "[benchmark]")
TEST_CASE ("benchmark function call", "[benchmark]")
TEST_CASE ("uniform samples", "[benchmark]")
TEST_CASE ("normal_cdf", "[benchmark]")
TEST_CASE ("erfc_inv", "[benchmark]")
TEST_CASE ("normal_quantile", "[benchmark]")
TEST_CASE ("mean", "[benchmark]")
TEST_CASE ("weighted_average_quantile", "[benchmark]")
TEST_CASE ("classify_outliers", "[benchmark]")
TEST_CASE ("analyse", "[approvals][benchmark]")
TEST_CASE ("analyse no analysis", "[benchmark]")
TEST_CASE ("run_for_at_least, int", "[benchmark]")
TEST_CASE ("run_for_at_least, chronometer", "[benchmark]")
TEST_CASE ("measure", "[benchmark]")
TEST_CASE ("run benchmark", "[benchmark][approvals]")
TEST_CASE ("Failing benchmarks", "[!benchmark][.approvals]")
TEST_CASE ("Failing benchmark respects should-fail", "[!shouldfail][!benchmark][approvals]")
Function Documentation
TEST_CASE() [1/19]
TEST_CASE ("analyse no analysis" , "" [benchmark])
Definition at line 326 of file InternalBenchmark.tests.cpp.
References Catch::Benchmark::Detail::analyse(), Catch::ConfigData::benchmarkConfidenceInterval, Catch::ConfigData::benchmarkNoAnalysis, Catch::ConfigData::benchmarkResamples, Catch::ConfigData::benchmarkSamples, and CHECK.
TEST_CASE() [2/19]
TEST_CASE ("analyse" , "" [approvals][benchmark])
Definition at line 287 of file InternalBenchmark.tests.cpp.
References Catch::Benchmark::Detail::analyse(), Catch::ConfigData::benchmarkConfidenceInterval, Catch::ConfigData::benchmarkNoAnalysis, Catch::ConfigData::benchmarkResamples, Catch::ConfigData::benchmarkSamples, and CHECK.
TEST_CASE() [3/19]
TEST_CASE ("benchmark function call" , "" [benchmark])
Definition at line 119 of file InternalBenchmark.tests.cpp.
References CHECK, and SECTION.
TEST_CASE() [4/19]
TEST_CASE ("classify_outliers" , "" [benchmark])
Definition at line 222 of file InternalBenchmark.tests.cpp.
References Catch::Benchmark::Detail::classify_outliers(), Catch::Benchmark::OutlierClassification::high_mild, Catch::Benchmark::OutlierClassification::high_severe, Catch::Benchmark::OutlierClassification::low_mild, Catch::Benchmark::OutlierClassification::low_severe, REQUIRE, Catch::Benchmark::OutlierClassification::samples_seen, SECTION, and Catch::Benchmark::OutlierClassification::total().
TEST_CASE() [5/19]
TEST_CASE ("erfc_inv" , "" [benchmark])
Definition at line 185 of file InternalBenchmark.tests.cpp.
References CHECK, and Catch::Benchmark::Detail::erfc_inv().
TEST_CASE() [6/19]
TEST_CASE ("estimate_clock_resolution" , "" [benchmark])
Definition at line 108 of file InternalBenchmark.tests.cpp.
References Catch::Benchmark::Detail::estimate_clock_resolution(), and REQUIRE.
TEST_CASE() [7/19]
TEST_CASE ("Failing benchmark respects should-fail" , "" [!shouldfail][!benchmark][approvals])
Definition at line 452 of file InternalBenchmark.tests.cpp.
References BENCHMARK, and REQUIRE.
TEST_CASE() [8/19]
TEST_CASE ("Failing benchmarks" , "" [!benchmark][.approvals])
Definition at line 431 of file InternalBenchmark.tests.cpp.
References BENCHMARK, FAIL, REQUIRE, and SECTION.
TEST_CASE() [9/19]
TEST_CASE ("mean" , "" [benchmark])
Definition at line 202 of file InternalBenchmark.tests.cpp.
References Catch::Benchmark::Detail::mean(), and REQUIRE.
TEST_CASE() [10/19]
TEST_CASE ("measure" , "" [benchmark])
Definition at line 395 of file InternalBenchmark.tests.cpp.
References CHECK, and Catch::Benchmark::Detail::measure().
TEST_CASE() [11/19]
TEST_CASE ("normal_cdf" , "" [benchmark])
Definition at line 175 of file InternalBenchmark.tests.cpp.
References CHECK, and Catch::Benchmark::Detail::normal_cdf().
TEST_CASE() [12/19]
TEST_CASE ("normal_quantile" , "" [benchmark])
Definition at line 193 of file InternalBenchmark.tests.cpp.
References CHECK, and Catch::Benchmark::Detail::normal_quantile().
TEST_CASE() [13/19]
TEST_CASE ("resolution" , "" [benchmark])
Definition at line 94 of file InternalBenchmark.tests.cpp.
References REQUIRE, and Catch::Benchmark::Detail::resolution().
TEST_CASE() [14/19]
TEST_CASE ("run benchmark" , "" [benchmark][approvals])
Definition at line 416 of file InternalBenchmark.tests.cpp.
References CHECK, and Catch::Benchmark::Benchmark::run().
TEST_CASE() [15/19]
TEST_CASE (" run_for_at_least, chronometer" , "" [benchmark])
Definition at line 375 of file InternalBenchmark.tests.cpp.
References CHECK, Catch::Benchmark::Chronometer::measure(), REQUIRE, Catch::Benchmark::Detail::run_for_at_least(), and Catch::Benchmark::Chronometer::runs().
TEST_CASE() [16/19]
TEST_CASE (" run_for_at_least, int" , "" [benchmark])
Definition at line 359 of file InternalBenchmark.tests.cpp.
References CHECK, REQUIRE, and Catch::Benchmark::Detail::run_for_at_least().
TEST_CASE() [17/19]
TEST_CASE ("uniform samples" , "" [benchmark])
Definition at line 155 of file InternalBenchmark.tests.cpp.
References Catch::Benchmark::Detail::bootstrap(), and CHECK.
TEST_CASE() [18/19]
TEST_CASE ("warmup" , "" [benchmark])
Definition at line 82 of file InternalBenchmark.tests.cpp.
References REQUIRE, Catch::Benchmark::Detail::warmup(), and Catch::Benchmark::Detail::warmup_time.
TEST_CASE() [19/19]
TEST_CASE ("weighted_average_quantile" , "" [benchmark])
Definition at line 210 of file InternalBenchmark.tests.cpp.
References REQUIRE, and Catch::Benchmark::Detail::weighted_average_quantile().