libthe-seed: external/Catch2/tests/SelfTest/UsageTests/MatchersRanges.tests.cpp File Reference
MatchersRanges.tests.cpp File Reference
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_container_properties.hpp>
#include <catch2/matchers/catch_matchers_contains.hpp>
#include <catch2/matchers/catch_matchers_range_equals.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
#include <catch2/matchers/catch_matchers_quantifiers.hpp>
#include <catch2/matchers/catch_matchers_predicate.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>
#include <helpers/range_test_helpers.hpp>
#include <cmath>
#include <list>
#include <map>
#include <type_traits>
#include <vector>
#include <memory>
Namespaces
namespace Catch
Functions
TEST_CASE ("Basic use of the Contains range matcher", "[matchers][templated][contains]")
TEST_CASE ("Basic use of the Empty range matcher", "[matchers][templated][empty]")
TEST_CASE ("Usage of the SizeIs range matcher", "[matchers][templated][size]")
TEST_CASE ("Usage of AllMatch range matcher", "[matchers][templated][quantifiers]")
TEST_CASE ("Usage of AnyMatch range matcher", "[matchers][templated][quantifiers]")
TEST_CASE ("Usage of NoneMatch range matcher", "[matchers][templated][quantifiers]")
TEST_CASE ("Usage of AllTrue range matcher", "[matchers][templated][quantifiers]")
TEST_CASE ("Usage of NoneTrue range matcher", "[matchers][templated][quantifiers]")
TEST_CASE ("Usage of AnyTrue range matcher", "[matchers][templated][quantifiers]")
TEST_CASE ("All/Any/None True matchers support types with ADL begin", "[approvals][matchers][quantifiers][templated]")
TEST_CASE ("Usage of RangeEquals range matcher", "[matchers][templated][quantifiers]")
TEST_CASE ("Usage of UnorderedRangeEquals range matcher", "[matchers][templated][quantifiers]")
TEST_CASE ("Type conversions of RangeEquals and similar", "[matchers][templated][quantifiers]")
Function Documentation
TEST_CASE() [1/13]
TEST_CASE ("All/Any/None True matchers support types with ADL begin" , "" [approvals][matchers][quantifiers][templated])
Definition at line 569 of file MatchersRanges.tests.cpp.
References Catch::Matchers::AllTrue(), Catch::Matchers::AnyTrue(), Catch::Matchers::NoneTrue(), REQUIRE_THAT, and SECTION.
TEST_CASE() [2/13]
TEST_CASE ("Basic use of the Contains range matcher" , "" [matchers][templated][contains])
Definition at line 44 of file MatchersRanges.tests.cpp.
References Catch::Matchers::Contains(), REQUIRE_THAT, SECTION, and Catch::Matchers::WithinAbs().
TEST_CASE() [3/13]
TEST_CASE ("Basic use of the Empty range matcher" , "" [matchers][templated][empty])
Definition at line 112 of file MatchersRanges.tests.cpp.
References Catch::Matchers::IsEmpty(), REQUIRE_THAT, and SECTION.
TEST_CASE() [4/13]
TEST_CASE ("Type conversions of RangeEquals and similar" , "" [matchers][templated][quantifiers])
Definition at line 837 of file MatchersRanges.tests.cpp.
References CHECK_THAT, Catch::Matchers::RangeEquals(), REQUIRE_THAT, SECTION, STATIC_REQUIRE, and Catch::Matchers::UnorderedRangeEquals().
TEST_CASE() [5/13]
TEST_CASE ("Usage of AllMatch range matcher" , "" [matchers][templated][quantifiers])
Definition at line 192 of file MatchersRanges.tests.cpp.
References Catch::Matchers::AllMatch(), Catch::Matchers::Contains(), with_mocked_iterator_access< T >::m_derefed, Catch::Matchers::Predicate(), REQUIRE, REQUIRE_FALSE, REQUIRE_THAT, SECTION, and Catch::Matchers::SizeIs().
TEST_CASE() [6/13]
TEST_CASE ("Usage of AllTrue range matcher" , "" [matchers][templated][quantifiers])
Definition at line 372 of file MatchersRanges.tests.cpp.
References Catch::Matchers::AllTrue(), with_mocked_iterator_access< T >::m_derefed, REQUIRE, REQUIRE_FALSE, REQUIRE_THAT, and SECTION.
TEST_CASE() [7/13]
TEST_CASE ("Usage of AnyMatch range matcher" , "" [matchers][templated][quantifiers])
Definition at line 246 of file MatchersRanges.tests.cpp.
References Catch::Matchers::AnyMatch(), Catch::Matchers::Contains(), with_mocked_iterator_access< T >::m_derefed, Catch::Matchers::Predicate(), REQUIRE, REQUIRE_FALSE, REQUIRE_THAT, SECTION, and Catch::Matchers::SizeIs().
TEST_CASE() [8/13]
TEST_CASE ("Usage of AnyTrue range matcher" , "" [matchers][templated][quantifiers])
Definition at line 503 of file MatchersRanges.tests.cpp.
References Catch::Matchers::AnyTrue(), with_mocked_iterator_access< T >::m_derefed, REQUIRE, REQUIRE_FALSE, REQUIRE_THAT, and SECTION.
TEST_CASE() [9/13]
TEST_CASE ("Usage of NoneMatch range matcher" , "" [matchers][templated][quantifiers])
Definition at line 298 of file MatchersRanges.tests.cpp.
References Catch::Matchers::Contains(), with_mocked_iterator_access< T >::m_derefed, Catch::Matchers::NoneMatch(), Catch::Matchers::Predicate(), REQUIRE, REQUIRE_FALSE, REQUIRE_THAT, SECTION, and Catch::Matchers::SizeIs().
TEST_CASE() [10/13]
TEST_CASE ("Usage of NoneTrue range matcher" , "" [matchers][templated][quantifiers])
Definition at line 437 of file MatchersRanges.tests.cpp.
References with_mocked_iterator_access< T >::m_derefed, Catch::Matchers::NoneTrue(), REQUIRE, REQUIRE_FALSE, REQUIRE_THAT, and SECTION.
TEST_CASE() [11/13]
TEST_CASE ("Usage of RangeEquals range matcher" , "" [matchers][templated][quantifiers])
Definition at line 661 of file MatchersRanges.tests.cpp.
References CHECK_THAT, with_mocked_iterator_access< T >::m_derefed, Catch::Matchers::RangeEquals(), REQUIRE, REQUIRE_FALSE, REQUIRE_THAT, and SECTION.
TEST_CASE() [12/13]
TEST_CASE ("Usage of the SizeIs range matcher" , "" [matchers][templated][size])
Definition at line 167 of file MatchersRanges.tests.cpp.
References REQUIRE_THAT, SECTION, and Catch::Matchers::SizeIs().
TEST_CASE() [13/13]
TEST_CASE ("Usage of UnorderedRangeEquals range matcher" , "" [matchers][templated][quantifiers])
Definition at line 754 of file MatchersRanges.tests.cpp.
References CHECK_THAT, REQUIRE_THAT, SECTION, and Catch::Matchers::UnorderedRangeEquals().