libthe-seed: external/Catch2/tests/SelfTest/UsageTests/Matchers.tests.cpp File Reference
Matchers.tests.cpp File Reference
#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_template_test_macros.hpp>
#include <catch2/matchers/catch_matchers_exception.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
#include <catch2/matchers/catch_matchers_predicate.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>
#include <catch2/matchers/catch_matchers_vector.hpp>
#include <catch2/matchers/catch_matchers_templated.hpp>
#include <algorithm>
#include <exception>
#include <cmath>
#include <list>
#include <sstream>
Functions
TEST_CASE ("String matchers", "[matchers]")
TEST_CASE ("Contains string matcher", "[.][failing][matchers]")
TEST_CASE ("StartsWith string matcher", "[.][failing][matchers]")
TEST_CASE ("EndsWith string matcher", "[.][failing][matchers]")
TEST_CASE ("Equals string matcher", "[.][failing][matchers]")
TEST_CASE ("Equals", "[matchers]")
TEST_CASE ("Regex string matcher -- libstdc++-4.8 workaround", "[matchers][approvals]")
TEST_CASE ("Regex string matcher", "[matchers][.failing]")
TEST_CASE ("Matchers can be (AllOf) composed with the && operator", "[matchers][operators][operator&&]")
TEST_CASE ("Matchers can be (AnyOf) composed with the || operator", "[matchers][operators][operator||]")
TEST_CASE ("Matchers can be composed with both && and ||", "[matchers][operators][operator||][operator&&]")
TEST_CASE ("Matchers can be composed with both && and || - failing", "[matchers][operators][operator||][operator&&][.failing]")
TEST_CASE ("Matchers can be negated (Not) with the ! operator", "[matchers][operators][not]")
TEST_CASE ("Matchers can be negated (Not) with the ! operator - failing", "[matchers][operators][not][.failing]")
TEST_CASE ("Vector matchers", "[matchers][vector]")
TEST_CASE ("Vector matchers that fail", "[matchers][vector][.][failing]")
TEST_CASE ("Vector matcher with elements without !=", "[matchers][vector][approvals]")
TEST_CASE ("Exception matchers that succeed", "[matchers][exceptions][!throws]")
TEST_CASE ("Exception matchers that fail", "[matchers][exceptions][!throws][.failing]")
TEST_CASE ("Floating point matchers: float", "[matchers][floating-point]")
TEST_CASE ("Floating point matchers: double", "[matchers][floating-point]")
TEST_CASE ("Floating point matchers that are problematic in approvals", "[approvals][matchers][floating-point]")
TEST_CASE ("Arbitrary predicate matcher", "[matchers][generic]")
TEST_CASE ("Regression test #1", "[matchers][vector]")
TEST_CASE ("Predicate matcher can accept const char*", "[matchers][compilation]")
TEST_CASE ("Vector Approx matcher", "[matchers][approx][vector]")
TEST_CASE ("Vector Approx matcher -- failing", "[matchers][approx][vector][.failing]")
TEST_CASE ("Exceptions matchers", "[matchers][exceptions][!throws]")
TEST_CASE ("Exception message can be matched", "[matchers][exceptions][!throws]")
TEST_CASE ("Composed matchers shortcircuit", "[matchers][composed]")
TEST_CASE ("Composed generic matchers shortcircuit", "[matchers][composed][generic]")
template<typename Range>
auto EqualsRange (const Range &range) -> EqualsRangeMatcher< Range >
TEST_CASE ("Combining templated matchers", "[matchers][templated]")
TEST_CASE ("Combining templated and concrete matchers", "[matchers][templated]")
TEST_CASE ("Combining concrete matchers does not use templated matchers", "[matchers][templated]")
TEST_CASE ("Combining only templated matchers", "[matchers][templated]")
TEST_CASE ("Combining MatchAnyOfGeneric does not nest", "[matchers][templated]")
TEST_CASE ("Combining MatchAllOfGeneric does not nest", "[matchers][templated]")
TEST_CASE ("Combining MatchNotOfGeneric does not nest", "[matchers][templated]")
TEST_CASE ("Overloaded comma or address-of operators are not used", "[matchers][templated]")
TEST_CASE ("Matchers are not moved or copied", "[matchers][templated][approvals]")
TEST_CASE ("Immovable matchers can be used", "[matchers][templated][approvals]")
TEST_CASE ("Matchers can take references", "[matchers][templated][approvals]")
TEMPLATE_TEST_CASE ("#2152 - ULP checks between differently signed values were wrong", "[matchers][floating-point][ulp]", float, double)
Function Documentation
EqualsRange()
template<typename Range> auto EqualsRange (const Range & range) ->EqualsRangeMatcher< Range >
Definition at line 817 of file Matchers.tests.cpp.
Referenced by TEST_CASE(), and TEST_CASE().
TEMPLATE_TEST_CASE()
TEMPLATE_TEST_CASE ("#2152 - ULP checks between differently signed values were wrong" , "" [matchers][floating-point][ulp], float , double)
Definition at line 1132 of file Matchers.tests.cpp.
References CHECK_THAT, and Catch::Matchers::WithinULP().
TEST_CASE() [1/42]
TEST_CASE ("Arbitrary predicate matcher" , "" [matchers][generic])
Definition at line 598 of file Matchers.tests.cpp.
References Catch::Matchers::Predicate(), REQUIRE_THAT, and SECTION.
TEST_CASE() [2/42]
TEST_CASE ("Combining concrete matchers does not use templated matchers" , "" [matchers][templated])
Definition at line 876 of file Matchers.tests.cpp.
References Catch::Matchers::EndsWith(), Catch::Matchers::StartsWith(), and STATIC_REQUIRE.
TEST_CASE() [3/42]
TEST_CASE ("Combining MatchAllOfGeneric does not nest" , "" [matchers][templated])
Definition at line 969 of file Matchers.tests.cpp.
References REQUIRE_THAT, and STATIC_REQUIRE.
TEST_CASE() [4/42]
TEST_CASE ("Combining MatchAnyOfGeneric does not nest" , "" [matchers][templated])
Definition at line 936 of file Matchers.tests.cpp.
References REQUIRE_THAT, and STATIC_REQUIRE.
TEST_CASE() [5/42]
TEST_CASE ("Combining MatchNotOfGeneric does not nest" , "" [matchers][templated])
Definition at line 1002 of file Matchers.tests.cpp.
References REQUIRE_THAT, and STATIC_REQUIRE.
TEST_CASE() [6/42]
TEST_CASE ("Combining only templated matchers" , "" [matchers][templated])
Definition at line 911 of file Matchers.tests.cpp.
References REQUIRE_THAT, and STATIC_REQUIRE.
TEST_CASE() [7/42]
TEST_CASE ("Combining templated and concrete matchers" , "" [matchers][templated])
Definition at line 832 of file Matchers.tests.cpp.
References Catch::Matchers::EndsWith(), EqualsRange(), Catch::Matchers::Predicate(), REQUIRE_THAT, and Catch::Matchers::StartsWith().
TEST_CASE() [8/42]
TEST_CASE ("Combining templated matchers" , "" [matchers][templated])
Definition at line 821 of file Matchers.tests.cpp.
References EqualsRange(), and REQUIRE_THAT.
TEST_CASE() [9/42]
TEST_CASE ("Composed generic matchers shortcircuit" , "" [matchers][composed][generic])
Definition at line 763 of file Matchers.tests.cpp.
References CHECK, CHECK_FALSE, REQUIRE, and SECTION.
TEST_CASE() [10/42]
TEST_CASE ("Composed matchers shortcircuit" , "" [matchers][composed])
Definition at line 720 of file Matchers.tests.cpp.
References CHECK, CHECK_FALSE, Catch::Matchers::Detail::MatchAllOf< ArgT >::match(), Catch::Matchers::Detail::MatchAnyOf< ArgT >::match(), REQUIRE, and SECTION.
TEST_CASE() [11/42]
TEST_CASE ("Contains string matcher" , "" [.][failing][matchers])
Definition at line 126 of file Matchers.tests.cpp.
References CHECK_THAT, Catch::Matchers::ContainsSubstring(), and Catch::No.
TEST_CASE() [12/42]
TEST_CASE ("EndsWith string matcher" , "" [.][failing][matchers])
Definition at line 138 of file Matchers.tests.cpp.
References CHECK_THAT, Catch::Matchers::EndsWith(), and Catch::No.
TEST_CASE() [13/42]
TEST_CASE ("Equals string matcher" , "" [.][failing][matchers])
Definition at line 144 of file Matchers.tests.cpp.
References CHECK_THAT, Catch::Matchers::Equals(), and Catch::No.
TEST_CASE() [14/42]
TEST_CASE ("Equals" , "" [matchers])
Definition at line 151 of file Matchers.tests.cpp.
References CHECK_THAT, Catch::Matchers::Equals(), and Catch::No.
TEST_CASE() [15/42]
TEST_CASE ("Exception matchers that fail" , "" [matchers][exceptions][!throws][.failing])
Definition at line 436 of file Matchers.tests.cpp.
References CHECK_THROWS_MATCHES, REQUIRE_THROWS_MATCHES, and SECTION.
TEST_CASE() [16/42]
TEST_CASE ("Exception matchers that succeed" , "" [matchers][exceptions][!throws])
Definition at line 428 of file Matchers.tests.cpp.
References CHECK_THROWS_MATCHES, and REQUIRE_THROWS_MATCHES.
TEST_CASE() [17/42]
TEST_CASE ("Exception message can be matched" , "" [matchers][exceptions][!throws])
Definition at line 690 of file Matchers.tests.cpp.
References Catch::Matchers::EndsWith(), Catch::Matchers::MessageMatches(), REQUIRE_THROWS_MATCHES, and Catch::Matchers::StartsWith().
TEST_CASE() [18/42]
TEST_CASE ("Exceptions matchers" , "" [matchers][exceptions][!throws])
Definition at line 675 of file Matchers.tests.cpp.
References Catch::Matchers::Message(), and REQUIRE_THROWS_MATCHES.
TEST_CASE() [19/42]
TEST_CASE ("Floating point matchers that are problematic in approvals" , "" [approvals][matchers][floating-point])
Definition at line 582 of file Matchers.tests.cpp.
References Catch::Matchers::IsNaN(), REQUIRE_THAT, Catch::Matchers::WithinAbs(), Catch::Matchers::WithinRel(), and Catch::Matchers::WithinULP().
TEST_CASE() [20/42]
TEST_CASE ("Floating point matchers: double" , "" [matchers][floating-point])
Definition at line 524 of file Matchers.tests.cpp.
References Catch::Matchers::IsNaN(), REQUIRE_NOTHROW, REQUIRE_THAT, REQUIRE_THROWS_AS, SECTION, Catch::Matchers::WithinAbs(), Catch::Matchers::WithinRel(), and Catch::Matchers::WithinULP().
TEST_CASE() [21/42]
TEST_CASE ("Floating point matchers: float" , "" [matchers][floating-point])
Definition at line 460 of file Matchers.tests.cpp.
References Catch::Matchers::IsNaN(), REQUIRE_NOTHROW, REQUIRE_THAT, REQUIRE_THROWS_AS, SECTION, Catch::Matchers::WithinAbs(), Catch::Matchers::WithinRel(), and Catch::Matchers::WithinULP().
TEST_CASE() [22/42]
TEST_CASE ("Immovable matchers can be used" , "" [matchers][templated][approvals])
Definition at line 1111 of file Matchers.tests.cpp.
References REQUIRE_THAT.
TEST_CASE() [23/42]
TEST_CASE ("Matchers are not moved or copied" , "" [matchers][templated][approvals])
Definition at line 1104 of file Matchers.tests.cpp.
References REQUIRE_NOTHROW.
TEST_CASE() [24/42]
TEST_CASE ("Matchers can be (AllOf) composed with the && operator" , "" [matchers][operators][operator &&])
Definition at line 188 of file Matchers.tests.cpp.
References CHECK_THAT, and Catch::Matchers::ContainsSubstring().
TEST_CASE() [25/42]
TEST_CASE ("Matchers can be (AnyOf) composed with the || operator" , "" [matchers][operators][operator||])
Definition at line 195 of file Matchers.tests.cpp.
References CHECK_THAT, and Catch::Matchers::ContainsSubstring().
TEST_CASE() [26/42]
TEST_CASE ("Matchers can be composed with both && and || - failing" , "" [matchers][operators][operator||][operator&&][.failing])
Definition at line 212 of file Matchers.tests.cpp.
References CHECK_THAT, and Catch::Matchers::ContainsSubstring().
TEST_CASE() [27/42]
TEST_CASE ("Matchers can be composed with both && and ||" , "" [matchers][operators][operator||][operator&&])
Definition at line 205 of file Matchers.tests.cpp.
References CHECK_THAT, and Catch::Matchers::ContainsSubstring().
TEST_CASE() [28/42]
TEST_CASE ("Matchers can be negated (Not) with the ! operator - failing" , "" [matchers][operators][not][.failing])
Definition at line 224 of file Matchers.tests.cpp.
References CHECK_THAT, and Catch::Matchers::ContainsSubstring().
TEST_CASE() [29/42]
TEST_CASE ("Matchers can be negated (Not) with the ! operator" , "" [matchers][operators][not])
Definition at line 219 of file Matchers.tests.cpp.
References CHECK_THAT, and Catch::Matchers::ContainsSubstring().
TEST_CASE() [30/42]
TEST_CASE ("Matchers can take references" , "" [matchers][templated][approvals])
Definition at line 1123 of file Matchers.tests.cpp.
References REQUIRE_THAT.
TEST_CASE() [31/42]
TEST_CASE ("Overloaded comma or address-of operators are not used" , "" [matchers][templated])
Definition at line 1054 of file Matchers.tests.cpp.
References REQUIRE_NOTHROW, and REQUIRE_THROWS_AS.
TEST_CASE() [32/42]
TEST_CASE ("Predicate matcher can accept const char*" , "" [matchers][compilation])
Definition at line 628 of file Matchers.tests.cpp.
References Catch::Matchers::Predicate(), and REQUIRE_THAT.
TEST_CASE() [33/42]
TEST_CASE ("Regex string matcher -- libstdc++-4.8 workaround" , "" [matchers][approvals])
Definition at line 159 of file Matchers.tests.cpp.
References Catch::Matchers::Matches(), Catch::No, and REQUIRE_THAT.
TEST_CASE() [34/42]
TEST_CASE ("Regex string matcher" , "" [matchers][.failing])
Definition at line 179 of file Matchers.tests.cpp.
References CHECK_THAT, and Catch::Matchers::Matches().
TEST_CASE() [35/42]
TEST_CASE ("Regression test #1" , "" [matchers][vector])
Definition at line 619 of file Matchers.tests.cpp.
References CHECK_THAT, and Catch::Matchers::UnorderedEquals().
TEST_CASE() [36/42]
TEST_CASE ("StartsWith string matcher" , "" [.][failing][matchers])
Definition at line 132 of file Matchers.tests.cpp.
References CHECK_THAT, Catch::No, and Catch::Matchers::StartsWith().
TEST_CASE() [37/42]
TEST_CASE ("String matchers" , "" [matchers])
Definition at line 110 of file Matchers.tests.cpp.
References CHECK_THAT, Catch::Matchers::ContainsSubstring(), Catch::Matchers::EndsWith(), Catch::No, REQUIRE_THAT, and Catch::Matchers::StartsWith().
TEST_CASE() [38/42]
TEST_CASE ("Vector Approx matcher -- failing" , "" [matchers][approx][vector][.failing])
Definition at line 662 of file Matchers.tests.cpp.
References Catch::Matchers::Approx(), CHECK_THAT, and SECTION.
TEST_CASE() [39/42]
TEST_CASE ("Vector Approx matcher" , "" [matchers][approx][vector])
Definition at line 635 of file Matchers.tests.cpp.
References Catch::Matchers::Approx(), REQUIRE_THAT, and SECTION.
TEST_CASE() [40/42]
TEST_CASE ()
Definition at line 418 of file Matchers.tests.cpp.
References Catch::Matchers::Equals(), and REQUIRE_THAT.
TEST_CASE() [41/42]
TEST_CASE ("Vector matchers that fail" , "" [matchers][vector][.][failing])
Definition at line 356 of file Matchers.tests.cpp.
References CHECK_THAT, Catch::Matchers::Contains(), Catch::Matchers::Equals(), SECTION, Catch::Matchers::UnorderedEquals(), and Catch::Matchers::VectorContains().
TEST_CASE() [42/42]
TEST_CASE ("Vector matchers" , "" [matchers][vector])
Definition at line 256 of file Matchers.tests.cpp.
References CHECK_THAT, Catch::Matchers::Contains(), Catch::Matchers::Equals(), REQUIRE_THAT, SECTION, Catch::Matchers::UnorderedEquals(), and Catch::Matchers::VectorContains().