libthe-seed: Catch::Generators::Detail Namespace Reference
Catch::Generators::Detail Namespace Reference
Functions
void throw_generator_exception (char const *msg)
Throws GeneratorException with the provided message.
std::uint32_t getSeed ()
Function Documentation
getSeed()
std::uint32_t Catch::Generators::Detail::getSeed ()
Definition at line 2190 of file catch_amalgamated.cpp.
References Catch::sharedRng().
Referenced by Catch::Generators::random().
throw_generator_exception()
void Catch::Generators::Detail::throw_generator_exception (char const * msg)
Throws GeneratorException with the provided message.
Definition at line 2165 of file catch_amalgamated.cpp.
References Catch::throw_exception().
Referenced by Catch::Generators::ChunkGenerator< T >::ChunkGenerator().