libthe-seed: Catch::Matchers::Detail Namespace Reference
Catch::Matchers::Detail Namespace Reference
Classes
class MatchAllOf
class MatchAnyOf
class MatchNotOf
class MatchAllOfGeneric
class MatchAnyOfGeneric
class MatchNotOfGeneric
Typedefs
template<typename T>
using is_generic_matcher
template<typename... Ts>
using are_generic_matchers = Catch::Detail::conjunction<is_generic_matcher<Ts>...>
template<typename T>
using is_matcher
Enumerations
enum class FloatingPointKind : uint8_t { Float , Double , Float , Double }
enum class FloatingPointKind : uint8_t { Float , Double , Float , Double }
Functions
std::string describe_multi_matcher (StringRef combine, std::string const *descriptions_begin, std::string const *descriptions_end)
template<typename ArgT>
MatchAllOf< ArgT > operator&& (MatchAllOf< ArgT > const &lhs, MatcherBase< ArgT > const &rhs)=delete
lvalue overload is intentionally deleted, users should not be trying to compose stored composition matchers
template<typename ArgT>
MatchAllOf< ArgT > operator&& (MatcherBase< ArgT > const &lhs, MatchAllOf< ArgT > const &rhs)=delete
lvalue overload is intentionally deleted, users should not be trying to compose stored composition matchers
template<typename ArgT>
MatchAnyOf< ArgT > operator|| (MatchAnyOf< ArgT > const &lhs, MatcherBase< ArgT > const &rhs)=delete
lvalue overload is intentionally deleted, users should not be trying to compose stored composition matchers
template<typename ArgT>
MatchAnyOf< ArgT > operator|| (MatcherBase< ArgT > const &lhs, MatchAnyOf< ArgT > const &rhs)=delete
lvalue overload is intentionally deleted, users should not be trying to compose stored composition matchers
template<std::size_t N, std::size_t M>
std::array< void const *, N+M > array_cat (std::array< void const *, N > &&lhs, std::array< void const *, M > &&rhs)
template<std::size_t N>
std::array< void const *, N+1 > array_cat (std::array< void const *, N > &&lhs, void const *rhs)
template<std::size_t N>
std::array< void const *, N+1 > array_cat (void const *lhs, std::array< void const *, N > &&rhs)
template<std::size_t N, typename Arg>
bool match_all_of (Arg &&, std::array< void const *, N > const &, std::index_sequence<>)
template<typename T, typename... MatcherTs, std::size_t N, typename Arg, std::size_t Idx, std::size_t... Indices>
bool match_all_of (Arg &&arg, std::array< void const *, N > const &matchers, std::index_sequence< Idx, Indices... >)
template<std::size_t N, typename Arg>
bool match_any_of (Arg &&, std::array< void const *, N > const &, std::index_sequence<>)
template<typename T, typename... MatcherTs, std::size_t N, typename Arg, std::size_t Idx, std::size_t... Indices>
bool match_any_of (Arg &&arg, std::array< void const *, N > const &matchers, std::index_sequence< Idx, Indices... >)
template<typename... MatcherTs, std::size_t... Idx>
std::string describe_multi_matcher (StringRef combine, std::array< void const *, sizeof...(MatcherTs)> const &matchers, std::index_sequence< Idx... >)
std::string finalizeDescription (const std::string &desc)
Typedef Documentation
are_generic_matchers
template<typename... Ts> using Catch::Matchers::Detail::are_generic_matchers = Catch::Detail::conjunction<is_generic_matcher<Ts>...>
Definition at line 10976 of file catch_amalgamated.hpp.
is_generic_matcher
template<typename T> using Catch::Matchers::Detail::is_generic_matcher
Initial value:
 std::is_base_of<
            Catch::Matchers::MatcherGenericBase,
            std::remove_cv_t<std::remove_reference_t<T>>
        >
Definition at line 10970 of file catch_amalgamated.hpp.
is_matcher
template<typename T> using Catch::Matchers::Detail::is_matcher
Initial value:
 std::is_base_of<
            Catch::Matchers::MatcherUntypedBase,
            std::remove_cv_t<std::remove_reference_t<T>>
        >
Definition at line 10979 of file catch_amalgamated.hpp.
Enumeration Type Documentation
FloatingPointKind [1/2]
enum class Catch::Matchers::Detail::FloatingPointKind : uint8_t strong
Enumerator
Float
Double
Float
Double
Definition at line 7609 of file catch_amalgamated.cpp.
FloatingPointKind [2/2]
enum class Catch::Matchers::Detail::FloatingPointKind : uint8_t strong
Enumerator
Float
Double
Float
Double
Definition at line 83 of file catch_matchers_floating_point.cpp.
Function Documentation
array_cat() [1/3]
template<std::size_t N, std::size_t M> std::array< void const *, N+M > Catch::Matchers::Detail::array_cat (std::array< void const *, N > && lhs, std::array< void const *, M > && rhs)
Definition at line 10947 of file catch_amalgamated.hpp.
References array_cat().
Referenced by array_cat(), array_cat(), array_cat(), Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::operator&&, Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::operator&&, Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::operator&&, Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::operator||, Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::operator||, and Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::operator||.
array_cat() [2/3]
template<std::size_t N> std::array< void const *, N+1 > Catch::Matchers::Detail::array_cat (std::array< void const *, N > && lhs, void const * rhs)
Definition at line 10955 of file catch_amalgamated.hpp.
References array_cat().
array_cat() [3/3]
template<std::size_t N> std::array< void const *, N+1 > Catch::Matchers::Detail::array_cat (void const * lhs, std::array< void const *, N > && rhs)
Definition at line 10963 of file catch_amalgamated.hpp.
References array_cat().
describe_multi_matcher() [1/2]
template<typename... MatcherTs, std::size_t... Idx> std::string Catch::Matchers::Detail::describe_multi_matcher (StringRef combine, std::array< void const *, sizeof...(MatcherTs)> const & matchers, std::index_sequence< Idx... >)
Definition at line 11009 of file catch_amalgamated.hpp.
References Catch::StringRef::data(), and describe_multi_matcher().
describe_multi_matcher() [2/2]
std::string Catch::Matchers::Detail::describe_multi_matcher (StringRef combine, std::string const * descriptions_begin, std::string const * descriptions_end)
Definition at line 7911 of file catch_amalgamated.cpp.
References Catch::StringRef::size().
Referenced by Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::describe(), Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::describe(), and describe_multi_matcher().
finalizeDescription()
std::string Catch::Matchers::Detail::finalizeDescription (const std::string & desc)
Definition at line 7772 of file catch_amalgamated.cpp.
match_all_of() [1/2]
template<std::size_t N, typename Arg> bool Catch::Matchers::Detail::match_all_of (Arg && , std::array< void const *, N > const & , std::index_sequence<>)
Definition at line 10986 of file catch_amalgamated.hpp.
References match_all_of().
Referenced by Catch::Matchers::Detail::MatchAllOfGeneric< MatcherTs >::match(), match_all_of(), and match_all_of().
match_all_of() [2/2]
template<typename T, typename... MatcherTs, std::size_t N, typename Arg, std::size_t Idx, std::size_t... Indices> bool Catch::Matchers::Detail::match_all_of (Arg && arg, std::array< void const *, N > const & matchers, std::index_sequence< Idx, Indices... >)
Definition at line 10991 of file catch_amalgamated.hpp.
References match_all_of().
match_any_of() [1/2]
template<std::size_t N, typename Arg> bool Catch::Matchers::Detail::match_any_of (Arg && , std::array< void const *, N > const & , std::index_sequence<>)
Definition at line 10997 of file catch_amalgamated.hpp.
References match_any_of().
Referenced by Catch::Matchers::Detail::MatchAnyOfGeneric< MatcherTs >::match(), match_any_of(), and match_any_of().
match_any_of() [2/2]
template<typename T, typename... MatcherTs, std::size_t N, typename Arg, std::size_t Idx, std::size_t... Indices> bool Catch::Matchers::Detail::match_any_of (Arg && arg, std::array< void const *, N > const & matchers, std::index_sequence< Idx, Indices... >)
Definition at line 11002 of file catch_amalgamated.hpp.
References match_any_of().
operator&&() [1/2]
template<typename ArgT> MatchAllOf< ArgT > Catch::Matchers::Detail::operator&& (MatchAllOf< ArgT > const & lhs, MatcherBase< ArgT > const & rhs) delete
lvalue overload is intentionally deleted, users should not be trying to compose stored composition matchers
operator&&() [2/2]
template<typename ArgT> MatchAllOf< ArgT > Catch::Matchers::Detail::operator&& (MatcherBase< ArgT > const & lhs, MatchAllOf< ArgT > const & rhs) delete
lvalue overload is intentionally deleted, users should not be trying to compose stored composition matchers
operator||() [1/2]
template<typename ArgT> MatchAnyOf< ArgT > Catch::Matchers::Detail::operator|| (MatchAnyOf< ArgT > const & lhs, MatcherBase< ArgT > const & rhs) delete
lvalue overload is intentionally deleted, users should not be trying to compose stored composition matchers
operator||() [2/2]
template<typename ArgT> MatchAnyOf< ArgT > Catch::Matchers::Detail::operator|| (MatcherBase< ArgT > const & lhs, MatchAnyOf< ArgT > const & rhs) delete
lvalue overload is intentionally deleted, users should not be trying to compose stored composition matchers