libthe-seed: clara::detail Namespace Reference
clara::detail Namespace Reference
Classes
struct UnaryLambdaTraits
struct UnaryLambdaTraits< ReturnT(ClassT::*)(Args...) const >
struct UnaryLambdaTraits< ReturnT(ClassT::*)(ArgT) const >
class Args
struct Token
class TokenStream
class ResultBase
class ResultValueBase
class ResultValueBase< void >
class BasicResult
class ParseState
struct HelpColumns
struct NonCopyable
struct BoundRef
struct BoundValueRefBase
struct BoundFlagRefBase
struct BoundValueRef
struct BoundValueRef< std::vector< T > >
struct BoundFlagRef
struct LambdaInvoker
struct LambdaInvoker< void >
struct BoundLambda
struct BoundFlagLambda
class ParserBase
class ComposableParserImpl
class ParserRefImpl
class ExeName
class Arg
class Opt
struct Help
struct Parser
Typedefs
using Result = BasicResult<void>
using ParserResult = BasicResult<ParseResultType>
using InternalParseResult = BasicResult<ParseState>
Enumerations
enum class TokenType { Option , Argument }
enum class ParseResultType { Matched , NoMatch , ShortCircuitAll , ShortCircuitSame }
enum class Optionality { Optional , Required }
Functions
auto isOptPrefix (char c) -> bool
template<typename T>
auto convertInto (std::string const &source, T &target) -> ParserResult
auto convertInto (std::string const &source, std::string &target) -> ParserResult
auto convertInto (std::string const &source, bool &target) -> ParserResult
template<typename ArgType, typename L>
auto invokeLambda (L const &lambda, std::string const &arg) -> ParserResult
auto normaliseOpt (std::string const &optName) -> std::string
Typedef Documentation
InternalParseResult
using clara::detail::InternalParseResult = BasicResult<ParseState>
Definition at line 647 of file clara.hpp.
ParserResult
using clara::detail::ParserResult = BasicResult<ParseResultType>
Definition at line 646 of file clara.hpp.
Result
using clara::detail::Result = BasicResult<void>
Definition at line 645 of file clara.hpp.
Enumeration Type Documentation
Optionality
enum class clara::detail::Optionality strong
Enumerator
Optional
Required
Definition at line 805 of file clara.hpp.
ParseResultType
enum class clara::detail::ParseResultType strong
Enumerator
Matched
NoMatch
ShortCircuitAll
ShortCircuitSame
Definition at line 625 of file clara.hpp.
TokenType
enum class clara::detail::TokenType strong
Enumerator
Option
Argument
Definition at line 430 of file clara.hpp.
Function Documentation
convertInto() [1/3]
auto clara::detail::convertInto (std::string const & source, bool & target)->ParserResult inline
Definition at line 668 of file clara.hpp.
References Matched, clara::detail::BasicResult< ParseResultType >::ok(), and clara::detail::BasicResult< ParseResultType >::runtimeError().
convertInto() [2/3]
auto clara::detail::convertInto (std::string const & source, std::string & target)->ParserResult inline
Definition at line 664 of file clara.hpp.
References Matched, and clara::detail::BasicResult< ParseResultType >::ok().
convertInto() [3/3]
template<typename T> auto clara::detail::convertInto (std::string const & source, T & target)->ParserResult inline
Definition at line 655 of file clara.hpp.
References Matched, clara::detail::BasicResult< ParseResultType >::ok(), and clara::detail::BasicResult< ParseResultType >::runtimeError().
Referenced by invokeLambda(), clara::detail::BoundValueRef< T >::setValue(), and clara::detail::BoundValueRef< std::vector< T > >::setValue().
invokeLambda()
template<typename ArgType, typename L> auto clara::detail::invokeLambda (L const & lambda, std::string const & arg)->ParserResult inline
Definition at line 770 of file clara.hpp.
References convertInto().
Referenced by clara::detail::BoundLambda< L >::setValue().
isOptPrefix()
auto clara::detail::isOptPrefix (char c) ->bool inline
Definition at line 438 of file clara.hpp.
normaliseOpt()
auto clara::detail::normaliseOpt (std::string const & optName) ->std::string inline
Definition at line 951 of file clara.hpp.
Referenced by clara::detail::Opt::isMatch().