libthe-seed: Catch::Detail Namespace Reference
Catch::Detail Namespace Reference
Classes
class unique_ptr
class NonCopyable
Deriving classes become noncopyable and nonmovable.
struct make_void
struct EnumInfo
class IsStreamInsertable
struct is_range_impl
struct is_range_impl< T, void_t< decltype(begin(std::declval< T >()))> >
struct conjunction
struct conjunction< B1 >
struct conjunction< B1, Bn... >
struct disjunction
struct disjunction< B1 >
struct disjunction< B1, Bn... >
struct negation
struct CaseInsensitiveLess
Provides case-insensitive op< semantics when called.
struct CaseInsensitiveEqualTo
Provides case-insensitive op== semantics when called.
class EnumValuesRegistry
class AssertionOrBenchmarkResult
Represents either an assertion or a benchmark result to be handled by cumulative reporter later.
struct has_description
struct has_description< T, void_t< decltype(T::getDescription())> >
Typedefs
template<typename... Ts>
using void_t = typename make_void<Ts...>::type
Functions
std::string convertIntoString (StringRef string, bool escapeInvisibles)
Encases `string in quotes, and optionally escapes invisibles.
std::string convertIntoString (StringRef string)
Encases string in quotes, and escapes invisibles if user requested it via CLI.
std::string rawMemoryToString (const void *object, std::size_t size)
void registerTranslatorImpl (Detail::unique_ptr< IExceptionTranslator > &&translator)
std::vector< StringRef > parseEnums (StringRef enums)
Catch::Detail::unique_ptr< EnumInfo > makeEnumInfo (StringRef enumName, StringRef allValueNames, std::vector< int > const &values)
uint32_t convertToBits (float f)
uint64_t convertToBits (double d)
char const * getEnv (char const *varName)
Wrapper over std::getenv that compiles on UWP (and always returns nullptr there).
std::vector< std::string > splitReporterSpec (StringRef reporterSpec)
Splits the reporter spec into reporter name and kv-pair options.
Optional< ColourMode > stringToColourMode (StringRef colourMode)
void registerReporterImpl (std::string const &name, IReporterFactoryPtr reporterPtr)
Indirection for reporter registration, so that the error handling is independent on the reporter's concrete type.
void registerListenerImpl (Detail::unique_ptr< EventListenerFactory > listenerFactory)
Actually registers the factory, independent on listener's concrete type.
template<typename T, typename... Args>
unique_ptr< T > make_unique (Args &&... args)
std::size_t catch_strnlen (const char *str, std::size_t n)
template<typename T>
std::string rawMemoryToString (const T &object)
template<typename E>
std::string convertUnknownEnumToString (E e)
template<typename T>
std::enable_if_t< !std::is_enum< T >::value &&!std::is_base_of< std::exception, T >::value, std::string > convertUnstreamable (T const &)
template<typename T>
std::enable_if_t< !std::is_enum< T >::value &&std::is_base_of< std::exception, T >::value, std::string > convertUnstreamable (T const &ex)
template<typename T>
std::enable_if_t< std::is_enum< T >::value, std::string > convertUnstreamable (T const &value)
template<typename T>
std::string stringify (const T &e)
template<typename InputIterator, typename Sentinel = InputIterator>
std::string rangeToString (InputIterator first, Sentinel last)
template<typename Container>
constexpr auto empty (Container const &cont) -> decltype(cont.empty())
template<typename T, std::size_t N>
constexpr bool empty (const T(&)[N]) noexcept
template<typename T>
constexpr bool empty (std::initializer_list< T > list) noexcept
template<typename Container>
constexpr auto size (Container const &cont) -> decltype(cont.size())
template<typename T, std::size_t N>
constexpr std::size_t size (const T(&)[N]) noexcept
template<typename ForwardIter, typename Sentinel, typename T, typename Comparator>
ForwardIter find_sentinel (ForwardIter start, Sentinel sentinel, T const &value, Comparator cmp)
template<typename ForwardIter, typename Sentinel, typename T, typename Comparator>
std::ptrdiff_t count_sentinel (ForwardIter start, Sentinel sentinel, T const &value, Comparator cmp)
template<typename ForwardIter, typename Sentinel>
std::enable_if_t<!std::is_same< ForwardIter, Sentinel >::value, std::ptrdiff_t > sentinel_distance (ForwardIter iter, const Sentinel sentinel)
template<typename ForwardIter>
std::ptrdiff_t sentinel_distance (ForwardIter first, ForwardIter last)
template<typename ForwardIter1, typename Sentinel1, typename ForwardIter2, typename Sentinel2, typename Comparator>
bool check_element_counts (ForwardIter1 first_1, const Sentinel1 end_1, ForwardIter2 first_2, const Sentinel2 end_2, Comparator cmp)
template<typename ForwardIter1, typename Sentinel1, typename ForwardIter2, typename Sentinel2, typename Comparator>
bool is_permutation (ForwardIter1 first_1, const Sentinel1 end_1, ForwardIter2 first_2, const Sentinel2 end_2, Comparator cmp)
Variables
constexpr StringRef unprintableString = "{?}"_sr
Typedef Documentation
void_t
template<typename... Ts> using Catch::Detail::void_t = typename make_void<Ts...>::type
Definition at line 2560 of file catch_amalgamated.hpp.
Function Documentation
catch_strnlen()
std::size_t Catch::Detail::catch_strnlen (const char * str, std::size_t n) inline
Definition at line 2629 of file catch_amalgamated.hpp.
References catch_strnlen().
Referenced by catch_strnlen(), Catch::StringMaker< char[SZ]>::convert(), Catch::StringMaker< signed char[SZ]>::convert(), and Catch::StringMaker< unsigned char[SZ]>::convert().
check_element_counts()
template<typename ForwardIter1, typename Sentinel1, typename ForwardIter2, typename Sentinel2, typename Comparator> bool Catch::Detail::check_element_counts (ForwardIter1 first_1, const Sentinel1 end_1, ForwardIter2 first_2, const Sentinel2 end_2, Comparator cmp)
Definition at line 9177 of file catch_amalgamated.hpp.
References check_element_counts(), count_sentinel(), and find_sentinel().
Referenced by check_element_counts(), and is_permutation().
convertIntoString() [1/2]
std::string Catch::Detail::convertIntoString (StringRef string)
Encases string in quotes, and escapes invisibles if user requested it via CLI.
Definition at line 1872 of file catch_amalgamated.cpp.
References convertIntoString(), and Catch::getCurrentContext().
convertIntoString() [2/2]
std::string Catch::Detail::convertIntoString (StringRef string, bool escape_invisibles)
Encases `string in quotes, and optionally escapes invisibles.
Definition at line 1834 of file catch_amalgamated.cpp.
References size().
Referenced by Catch::StringMaker< char * >::convert(), Catch::StringMaker< char[SZ]>::convert(), Catch::StringMaker< signed char[SZ]>::convert(), Catch::StringMaker< std::string >::convert(), Catch::StringMaker< unsigned char[SZ]>::convert(), convertIntoString(), and TEST_CASE().
convertToBits() [1/2]
uint64_t Catch::Detail::convertToBits (double d)
Definition at line 4079 of file catch_amalgamated.cpp.
convertToBits() [2/2]
uint32_t Catch::Detail::convertToBits (float f)
Definition at line 4072 of file catch_amalgamated.cpp.
Referenced by TEST_CASE(), and Catch::ulpDistance().
convertUnknownEnumToString()
template<typename E> std::string Catch::Detail::convertUnknownEnumToString (E e)
Definition at line 2740 of file catch_amalgamated.hpp.
References convertUnknownEnumToString().
Referenced by convertUnknownEnumToString(), and convertUnstreamable().
convertUnstreamable() [1/3]
template<typename T> std::enable_if_t< !std::is_enum< T >::value &&!std::is_base_of< std::exception, T >::value, std::string > Catch::Detail::convertUnstreamable (T const &)
Definition at line 2672 of file catch_amalgamated.hpp.
References convertUnstreamable(), and unprintableString.
Referenced by Catch::StringMaker< T, typename >::convert(), convertUnstreamable(), convertUnstreamable(), and convertUnstreamable().
convertUnstreamable() [2/3]
template<typename T> std::enable_if_t< !std::is_enum< T >::value &&std::is_base_of< std::exception, T >::value, std::string > Catch::Detail::convertUnstreamable (T const & ex)
Definition at line 2678 of file catch_amalgamated.hpp.
References convertUnstreamable().
convertUnstreamable() [3/3]
template<typename T> std::enable_if_t< std::is_enum< T >::value, std::string > Catch::Detail::convertUnstreamable (T const & value)
Definition at line 2686 of file catch_amalgamated.hpp.
References convertUnknownEnumToString(), and convertUnstreamable().
count_sentinel()
template<typename ForwardIter, typename Sentinel, typename T, typename Comparator> std::ptrdiff_t Catch::Detail::count_sentinel (ForwardIter start, Sentinel sentinel, T const & value, Comparator cmp)
Definition at line 9142 of file catch_amalgamated.hpp.
References count_sentinel().
Referenced by check_element_counts(), and count_sentinel().
empty() [1/3]
template<typename T, std::size_t N> bool Catch::Detail::empty (const T(&)[N]) constexpr noexcept
Definition at line 8707 of file catch_amalgamated.hpp.
References empty().
empty() [2/3]
template<typename Container> auto Catch::Detail::empty (Container const & cont) ->decltype(cont.empty()) constexpr
Definition at line 8703 of file catch_amalgamated.hpp.
References empty().
Referenced by empty(), empty(), empty(), and Catch::Matchers::IsEmptyMatcher::match().
empty() [3/3]
template<typename T> bool Catch::Detail::empty (std::initializer_list< T > list) constexpr noexcept
Definition at line 8714 of file catch_amalgamated.hpp.
References empty(), and Catch::list().
find_sentinel()
template<typename ForwardIter, typename Sentinel, typename T, typename Comparator> ForwardIter Catch::Detail::find_sentinel (ForwardIter start, Sentinel sentinel, T const & value, Comparator cmp)
Definition at line 9127 of file catch_amalgamated.hpp.
References find_sentinel().
Referenced by check_element_counts(), and find_sentinel().
getEnv()
char const * Catch::Detail::getEnv (char const * varName)
Wrapper over std::getenv that compiles on UWP (and always returns nullptr there).
Definition at line 4103 of file catch_amalgamated.cpp.
is_permutation()
template<typename ForwardIter1, typename Sentinel1, typename ForwardIter2, typename Sentinel2, typename Comparator> bool Catch::Detail::is_permutation (ForwardIter1 first_1, const Sentinel1 end_1, ForwardIter2 first_2, const Sentinel2 end_2, Comparator cmp)
Definition at line 9211 of file catch_amalgamated.hpp.
References check_element_counts(), is_permutation(), and sentinel_distance().
Referenced by is_permutation(), and Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >::match().
make_unique()
template<typename T, typename... Args> unique_ptr< T > Catch::Detail::make_unique (Args &&... args)
Definition at line 939 of file catch_amalgamated.hpp.
References CATCH_FORWARD.
Referenced by Catch::TestCaseTracking::SectionTracker::acquire(), Catch::Generators::chunk(), Catch::Session::config(), Catch::RunContext::createGeneratorTracker(), Catch::ExceptionTranslatorRegistrar::ExceptionTranslatorRegistrar(), Catch::Generators::filter(), Catch::Generators::from_range(), Catch::Generators::from_range(), Catch::Generators::generate(), Catch::ListenerRegistrar< T >::ListenerRegistrar(), Catch::makeColourImpl(), makeEnumInfo(), Catch::makeStream(), Catch::makeTestCaseInfo(), Catch::makeTestInvoker(), Catch::makeTestInvoker(), Catch::Generators::map(), Catch::Benchmark::Detail::measure_environment(), Catch::Generators::random(), Catch::Generators::range(), Catch::Generators::range(), Catch::Generators::repeat(), Catch::ReporterRegistrar< T >::ReporterRegistrar(), Catch::ReporterRegistry::ReporterRegistry(), Catch::CumulativeReporterBase::sectionStarting(), Catch::TestCaseTracking::TrackerContext::startRun(), Catch::Generators::take(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), Catch::CumulativeReporterBase::testCaseEnded(), Catch::CumulativeReporterBase::testRunEnded(), Catch::Generators::value(), and Catch::Generators::values().
makeEnumInfo()
Catch::Detail::unique_ptr< EnumInfo > Catch::Detail::makeEnumInfo (StringRef enumName, StringRef allValueNames, std::vector< int > const & values)
Definition at line 3723 of file catch_amalgamated.cpp.
References make_unique(), and parseEnums().
Referenced by TEST_CASE().
parseEnums()
std::vector< StringRef > Catch::Detail::parseEnums (StringRef enums)
Definition at line 3703 of file catch_amalgamated.cpp.
References Catch::splitStringRef(), and Catch::trim().
Referenced by makeEnumInfo(), and TEST_CASE().
rangeToString()
template<typename InputIterator, typename Sentinel = InputIterator> std::string Catch::Detail::rangeToString (InputIterator first, Sentinel last)
Definition at line 2929 of file catch_amalgamated.hpp.
References rangeToString(), Catch::ReusableStringStream::str(), and stringify().
Referenced by rangeToString().
rawMemoryToString() [1/2]
template<typename T> std::string Catch::Detail::rawMemoryToString (const T & object)
Definition at line 2649 of file catch_amalgamated.hpp.
References rawMemoryToString().
rawMemoryToString() [2/2]
std::string Catch::Detail::rawMemoryToString (const void * object, std::size_t size)
Definition at line 1876 of file catch_amalgamated.cpp.
References size(), and Catch::ReusableStringStream::str().
Referenced by rawMemoryToString().
registerListenerImpl()
void Catch::Detail::registerListenerImpl (Detail::unique_ptr< EventListenerFactory > listenerFactory)
Actually registers the factory, independent on listener's concrete type.
Definition at line 9918 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::getMutableRegistryHub(), and Catch::IMutableRegistryHub::registerListener().
registerReporterImpl()
void Catch::Detail::registerReporterImpl (std::string const & name, IReporterFactoryPtr reporterPtr)
Indirection for reporter registration, so that the error handling is independent on the reporter's concrete type.
Definition at line 9905 of file catch_amalgamated.cpp.
References CATCH_CATCH_ALL, CATCH_MOVE, CATCH_TRY, Catch::getMutableRegistryHub(), Catch::IMutableRegistryHub::registerReporter(), and Catch::IMutableRegistryHub::registerStartupException().
registerTranslatorImpl()
void Catch::Detail::registerTranslatorImpl (Detail::unique_ptr< IExceptionTranslator > && translator)
Definition at line 2097 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::getMutableRegistryHub(), and Catch::IMutableRegistryHub::registerTranslator().
Referenced by Catch::ExceptionTranslatorRegistrar::ExceptionTranslatorRegistrar().
sentinel_distance() [1/2]
template<typename ForwardIter> std::ptrdiff_t Catch::Detail::sentinel_distance (ForwardIter first, ForwardIter last)
Definition at line 9167 of file catch_amalgamated.hpp.
References sentinel_distance().
sentinel_distance() [2/2]
template<typename ForwardIter, typename Sentinel> std::enable_if_t<!std::is_same< ForwardIter, Sentinel >::value, std::ptrdiff_t > Catch::Detail::sentinel_distance (ForwardIter iter, const Sentinel sentinel)
Definition at line 9157 of file catch_amalgamated.hpp.
References sentinel_distance().
Referenced by is_permutation(), sentinel_distance(), and sentinel_distance().
size() [1/2]
template<typename T, std::size_t N> std::size_t Catch::Detail::size (const T(&)[N]) constexpr noexcept
Definition at line 8724 of file catch_amalgamated.hpp.
References size().
size() [2/2]
template<typename Container> auto Catch::Detail::size (Container const & cont) ->decltype(cont.size()) constexpr
Definition at line 8720 of file catch_amalgamated.hpp.
References size().
Referenced by convertIntoString(), Catch::Matchers::HasSizeMatcher::match(), Catch::Matchers::SizeMatchesMatcher< Matcher >::match(), rawMemoryToString(), size(), and size().
splitReporterSpec()
std::vector< std::string > Catch::Detail::splitReporterSpec (StringRef reporterSpec)
Splits the reporter spec into reporter name and kv-pair options.
Definition at line 4867 of file catch_amalgamated.cpp.
References separator, Catch::StringRef::size(), and Catch::StringRef::substr().
Referenced by Catch::parseReporterSpec(), and TEST_CASE().
stringify()
template<typename T> std::string Catch::Detail::stringify (const T & e)
Definition at line 2735 of file catch_amalgamated.hpp.
References stringify().
Referenced by Catch::Capturer::captureValues(), Catch::Capturer::captureValues(), CATCH_REGISTER_ENUM(), CATCH_TRANSLATE_EXCEPTION(), Catch::defaultListTests(), Catch::Matchers::ApproxMatcher< T, AllocComp, AllocMatch >::describe(), Catch::Matchers::ContainsElementMatcher< T, Equality >::describe(), Catch::Matchers::ContainsMatcher< T, AllocComp, AllocMatch >::describe(), Catch::Matchers::EqualsMatcher< T, AllocComp, AllocMatch >::describe(), Catch::Matchers::RangeEqualsMatcher< TargetRangeLike, Equality >::describe(), Catch::Matchers::RegexMatcher::describe(), Catch::Matchers::UnorderedEqualsMatcher< T, AllocComp, AllocMatch >::describe(), Catch::Matchers::UnorderedRangeEqualsMatcher< TargetRangeLike, Equality >::describe(), Catch::Matchers::VectorContainsElementMatcher< T, Alloc >::describe(), Catch::Matchers::WithinAbsMatcher::describe(), rangeToString(), Catch::rangeToString(), Catch::MatchExpr< ArgT, MatcherT >::streamReconstructedExpression(), stringify(), TEMPLATE_TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and Catch::Approx::toString().
stringToColourMode()
Optional< ColourMode > Catch::Detail::stringToColourMode (StringRef colourMode)
Definition at line 4916 of file catch_amalgamated.cpp.
References Catch::ANSI, Catch::None, Catch::PlatformDefault, and Catch::Win32.
Referenced by Catch::makeCommandLineParser(), Catch::parseReporterSpec(), and TEST_CASE().
Variable Documentation
unprintableString
StringRef Catch::Detail::unprintableString = "{?}"_sr constexpr
Definition at line 2637 of file catch_amalgamated.hpp.
Referenced by convertUnstreamable().