libthe-seed: Catch::Benchmark::Detail Namespace Reference
Catch::Benchmark::Detail Namespace Reference
Classes
struct ChronometerConcept
struct ChronometerModel
struct is_related
struct BenchmarkFunction
We need to reinvent std::function because every piece of code that might add overhead in a measurement context needs to have consistent performance characteristics so that we can account for it in the measurement. Implementations of std::function with optimizations that aren't always applicable, like small buffer optimizations, are not uncommon. This is effectively an implementation of std::function without any such optimizations; it may be slow, but it is consistently slow.
struct repeater
struct CompleteType
struct CompleteType< void >
struct CompleteInvoker
struct CompleteInvoker< void >
struct bootstrap_analysis
struct ObjectStorage
Typedefs
template<typename T>
using CompleteType_t = typename CompleteType<T>::type
template<typename Clock, typename Fun>
using run_for_at_least_argument_t = std::conditional_t<is_callable<Fun(Chronometer)>::value, Chronometer, int>
using sample = std::vector<double>
Functions
void throw_optimized_away_error ()
bool directCompare (double lhs, double rhs)
double weighted_average_quantile (int k, int q, std::vector< double >::iterator first, std::vector< double >::iterator last)
OutlierClassification classify_outliers (std::vector< double >::const_iterator first, std::vector< double >::const_iterator last)
double mean (std::vector< double >::const_iterator first, std::vector< double >::const_iterator last)
double erfc_inv (double x)
double normal_quantile (double p)
bootstrap_analysis analyse_samples (double confidence_level, unsigned int n_resamples, std::vector< double >::iterator first, std::vector< double >::iterator last)
template<typename Fun>
repeater< std::decay_t< Fun > > repeat (Fun &&fun)
template<typename Fun, typename... Args>
CompleteType_t< FunctionReturnType< Fun, Args... > > complete_invoke (Fun &&fun, Args &&... args)
template<typename Clock, typename Fun, typename... Args>
TimingOf< Clock, Fun, Args... > measure (Fun &&fun, Args &&... args)
template<typename Clock, typename Fun>
TimingOf< Clock, Fun, int > measure_one (Fun &&fun, int iters, std::false_type)
template<typename Clock, typename Fun>
TimingOf< Clock, Fun, Chronometer > measure_one (Fun &&fun, int iters, std::true_type)
template<typename Clock, typename Fun>
TimingOf< Clock, Fun, run_for_at_least_argument_t< Clock, Fun > > run_for_at_least (ClockDuration< Clock > how_long, const int initial_iterations, Fun &&fun)
template<typename Estimator>
sample jackknife (Estimator &&estimator, std::vector< double >::iterator first, std::vector< double >::iterator last)
double normal_cdf (double x)
template<typename Estimator>
Estimate< double > bootstrap (double confidence_level, std::vector< double >::iterator first, std::vector< double >::iterator last, sample const &resample, Estimator &&estimator)
template<typename Clock>
std::vector< double > resolution (int k)
template<typename Clock>
int warmup ()
template<typename Clock>
EnvironmentEstimate< FloatDuration< Clock > > estimate_clock_resolution (int iterations)
template<typename Clock>
EnvironmentEstimate< FloatDuration< Clock > > estimate_clock_cost (FloatDuration< Clock > resolution)
template<typename Clock>
Environment< FloatDuration< Clock > > measure_environment ()
template<typename Duration, typename Iterator>
SampleAnalysis< Duration > analyse (const IConfig &cfg, Environment< Duration >, Iterator first, Iterator last)
SampleAnalysis analyse (const IConfig &cfg, FDuration *first, FDuration *last)
template<typename Clock>
EnvironmentEstimate estimate_clock_resolution (int iterations)
template<typename Clock>
EnvironmentEstimate estimate_clock_cost (FDuration resolution)
template<typename Clock>
Environment measure_environment ()
template<typename Clock, typename Fun, typename... Args>
TimingOf< Fun, Args... > measure (Fun &&fun, Args &&... args)
template<typename Clock, typename Fun>
TimingOf< Fun, int > measure_one (Fun &&fun, int iters, std::false_type)
template<typename Clock, typename Fun>
TimingOf< Fun, Chronometer > measure_one (Fun &&fun, int iters, std::true_type)
template<typename Clock, typename Fun>
TimingOf< Fun, run_for_at_least_argument_t< Clock, Fun > > run_for_at_least (IDuration how_long, const int initial_iterations, Fun &&fun)
double weighted_average_quantile (int k, int q, double *first, double *last)
OutlierClassification classify_outliers (double const *first, double const *last)
double mean (double const *first, double const *last)
Estimate< double > bootstrap (double confidence_level, double *first, double *last, sample const &resample, double(*estimator)(double const *, double const *))
bootstrap_analysis analyse_samples (double confidence_level, unsigned int n_resamples, double *first, double *last)
Variables
constexpr auto warmup_iterations = 10000
constexpr auto warmup_time = std::chrono::milliseconds(100)
constexpr auto minimum_ticks = 1000
constexpr auto warmup_seed = 10000
constexpr auto clock_resolution_estimation_time = std::chrono::milliseconds(500)
constexpr auto clock_cost_estimation_time_limit = std::chrono::seconds(1)
constexpr auto clock_cost_estimation_tick_limit = 100000
constexpr auto clock_cost_estimation_time = std::chrono::milliseconds(10)
constexpr auto clock_cost_estimation_iterations = 10000
Typedef Documentation
CompleteType_t
template<typename T> using Catch::Benchmark::Detail::CompleteType_t = typename CompleteType<T>::type
Definition at line 1748 of file catch_amalgamated.hpp.
run_for_at_least_argument_t
template<typename Clock, typename Fun> using Catch::Benchmark::Detail::run_for_at_least_argument_t = std::conditional_t<is_callable<Fun(Chronometer)>::value, Chronometer, int>
Definition at line 1842 of file catch_amalgamated.hpp.
sample
typedef std::vector< double > Catch::Benchmark::Detail::sample = std::vector<double>
Definition at line 1933 of file catch_amalgamated.hpp.
Function Documentation
analyse() [1/2]
template<typename Duration, typename Iterator> SampleAnalysis< Duration > Catch::Benchmark::Detail::analyse (const IConfig & cfg, Environment< Duration > , Iterator first, Iterator last)
Definition at line 2196 of file catch_amalgamated.hpp.
References analyse(), analyse_samples(), Catch::IConfig::benchmarkConfidenceInterval(), Catch::IConfig::benchmarkNoAnalysis(), Catch::IConfig::benchmarkResamples(), CATCH_MOVE, classify_outliers(), and mean().
Referenced by analyse(), Catch::Benchmark::Benchmark::run(), TEST_CASE(), and TEST_CASE().
analyse() [2/2]
SampleAnalysis Catch::Benchmark::Detail::analyse (const IConfig & cfg, FDuration * first, FDuration * last)
Definition at line 22 of file catch_analyse.cpp.
References analyse_samples(), Catch::IConfig::benchmarkConfidenceInterval(), Catch::IConfig::benchmarkNoAnalysis(), Catch::IConfig::benchmarkResamples(), CATCH_MOVE, classify_outliers(), and mean().
analyse_samples() [1/2]
bootstrap_analysis Catch::Benchmark::Detail::analyse_samples (double confidence_level, unsigned int n_resamples, double * first, double * last)
Definition at line 366 of file catch_stats.cpp.
References bootstrap(), CATCH_INTERNAL_START_WARNINGS_SUPPRESSION, CATCH_INTERNAL_STOP_WARNINGS_SUPPRESSION, CATCH_INTERNAL_SUPPRESS_GLOBALS_WARNINGS, and mean().
analyse_samples() [2/2]
bootstrap_analysis Catch::Benchmark::Detail::analyse_samples (double confidence_level, unsigned int n_resamples, std::vector< double >::iterator first, std::vector< double >::iterator last)
Definition at line 357 of file catch_amalgamated.cpp.
References bootstrap(), CATCH_INTERNAL_START_WARNINGS_SUPPRESSION, CATCH_INTERNAL_STOP_WARNINGS_SUPPRESSION, CATCH_INTERNAL_SUPPRESS_GLOBALS_WARNINGS, and mean().
Referenced by analyse(), and analyse().
bootstrap() [1/2]
Estimate< double > Catch::Benchmark::Detail::bootstrap (double confidence_level, double * first, double * last, sample const & resample, double(* estimator)(double const *, double const *))
Definition at line 309 of file catch_stats.cpp.
References directCompare(), jackknife(), mean(), normal_cdf(), and normal_quantile().
bootstrap() [2/2]
template<typename Estimator> Estimate< double > Catch::Benchmark::Detail::bootstrap (double confidence_level, std::vector< double >::iterator first, std::vector< double >::iterator last, sample const & resample, Estimator && estimator)
Definition at line 1975 of file catch_amalgamated.hpp.
References bootstrap(), directCompare(), jackknife(), mean(), normal_cdf(), and normal_quantile().
Referenced by analyse_samples(), analyse_samples(), bootstrap(), and TEST_CASE().
classify_outliers() [1/2]
OutlierClassification Catch::Benchmark::Detail::classify_outliers (double const * first, double const * last)
Definition at line 246 of file catch_stats.cpp.
References weighted_average_quantile().
classify_outliers() [2/2]
OutlierClassification Catch::Benchmark::Detail::classify_outliers (std::vector< double >::const_iterator first, std::vector< double >::const_iterator last)
Definition at line 296 of file catch_amalgamated.cpp.
References weighted_average_quantile().
Referenced by analyse(), analyse(), estimate_clock_cost(), estimate_clock_cost(), estimate_clock_resolution(), and TEST_CASE().
complete_invoke()
template<typename Fun, typename... Args> CompleteType_t< FunctionReturnType< Fun, Args... > > Catch::Benchmark::Detail::complete_invoke (Fun && fun, Args &&... args)
Definition at line 1768 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and complete_invoke().
Referenced by complete_invoke(), measure(), measure_one(), and Catch::Benchmark::user_code().
directCompare()
bool Catch::Benchmark::Detail::directCompare (double lhs, double rhs)
Definition at line 275 of file catch_amalgamated.cpp.
Referenced by bootstrap(), bootstrap(), weighted_average_quantile(), and weighted_average_quantile().
erfc_inv()
double Catch::Benchmark::Detail::erfc_inv (double x)
Definition at line 337 of file catch_amalgamated.cpp.
Referenced by normal_quantile(), and TEST_CASE().
estimate_clock_cost() [1/2]
template<typename Clock> EnvironmentEstimate Catch::Benchmark::Detail::estimate_clock_cost (FDuration resolution)
Definition at line 71 of file catch_estimate_clock.hpp.
References classify_outliers(), clock_cost_estimation_iterations, clock_cost_estimation_tick_limit, clock_cost_estimation_time, clock_cost_estimation_time_limit, mean(), measure(), resolution(), and run_for_at_least().
estimate_clock_cost() [2/2]
template<typename Clock> EnvironmentEstimate< FloatDuration< Clock > > Catch::Benchmark::Detail::estimate_clock_cost (FloatDuration< Clock > resolution)
Definition at line 2087 of file catch_amalgamated.hpp.
References classify_outliers(), clock_cost_estimation_iterations, clock_cost_estimation_tick_limit, clock_cost_estimation_time, clock_cost_estimation_time_limit, estimate_clock_cost(), mean(), measure(), resolution(), and run_for_at_least().
Referenced by estimate_clock_cost(), and measure_environment().
estimate_clock_resolution() [1/2]
template<typename Clock> EnvironmentEstimate< FloatDuration< Clock > > Catch::Benchmark::Detail::estimate_clock_resolution (int iterations)
Definition at line 2078 of file catch_amalgamated.hpp.
References classify_outliers(), clock_resolution_estimation_time, estimate_clock_resolution(), mean(), resolution(), and run_for_at_least().
Referenced by estimate_clock_resolution(), measure_environment(), and TEST_CASE().
estimate_clock_resolution() [2/2]
template<typename Clock> EnvironmentEstimate Catch::Benchmark::Detail::estimate_clock_resolution (int iterations)
Definition at line 62 of file catch_estimate_clock.hpp.
References classify_outliers(), clock_resolution_estimation_time, mean(), resolution(), and run_for_at_least().
jackknife()
template<typename Estimator> sample Catch::Benchmark::Detail::jackknife (Estimator && estimator, std::vector< double >::iterator first, std::vector< double >::iterator last)
Definition at line 1949 of file catch_amalgamated.hpp.
References jackknife().
Referenced by bootstrap(), bootstrap(), and jackknife().
mean() [1/2]
double Catch::Benchmark::Detail::mean (double const * first, double const * last)
Definition at line 274 of file catch_stats.cpp.
mean() [2/2]
double Catch::Benchmark::Detail::mean (std::vector< double >::const_iterator first, std::vector< double >::const_iterator last)
Definition at line 325 of file catch_amalgamated.cpp.
Referenced by analyse(), analyse(), analyse_samples(), analyse_samples(), bootstrap(), bootstrap(), estimate_clock_cost(), estimate_clock_cost(), estimate_clock_resolution(), and TEST_CASE().
measure() [1/2]
template<typename Clock, typename Fun, typename... Args> TimingOf< Clock, Fun, Args... > Catch::Benchmark::Detail::measure (Fun && fun, Args &&... args)
Definition at line 1811 of file catch_amalgamated.hpp.
References CATCH_FORWARD, complete_invoke(), and measure().
Referenced by estimate_clock_cost(), estimate_clock_cost(), measure(), measure_one(), and TEST_CASE().
measure() [2/2]
template<typename Clock, typename Fun, typename... Args> TimingOf< Fun, Args... > Catch::Benchmark::Detail::measure (Fun && fun, Args &&... args)
Definition at line 21 of file catch_measure.hpp.
References CATCH_FORWARD, and complete_invoke().
measure_environment() [1/2]
template<typename Clock> Environment< FloatDuration< Clock > > Catch::Benchmark::Detail::measure_environment ()
Definition at line 2117 of file catch_amalgamated.hpp.
References estimate_clock_cost(), estimate_clock_resolution(), Catch::Detail::make_unique(), measure_environment(), resolution(), and warmup().
Referenced by measure_environment(), and Catch::Benchmark::Benchmark::run().
measure_environment() [2/2]
template<typename Clock> Environment Catch::Benchmark::Detail::measure_environment ()
Definition at line 101 of file catch_estimate_clock.hpp.
References estimate_clock_cost(), estimate_clock_resolution(), Catch::Detail::make_unique(), resolution(), and warmup().
measure_one() [1/4]
template<typename Clock, typename Fun> TimingOf< Clock, Fun, int > Catch::Benchmark::Detail::measure_one (Fun && fun, int iters, std::false_type)
Definition at line 1830 of file catch_amalgamated.hpp.
References measure(), and measure_one().
Referenced by measure_one(), measure_one(), run_for_at_least(), and run_for_at_least().
measure_one() [2/4]
template<typename Clock, typename Fun> TimingOf< Fun, int > Catch::Benchmark::Detail::measure_one (Fun && fun, int iters, std::false_type)
Definition at line 27 of file catch_run_for_at_least.hpp.
References measure().
measure_one() [3/4]
template<typename Clock, typename Fun> TimingOf< Clock, Fun, Chronometer > Catch::Benchmark::Detail::measure_one (Fun && fun, int iters, std::true_type)
Definition at line 1834 of file catch_amalgamated.hpp.
References CATCH_MOVE, complete_invoke(), Catch::Benchmark::Detail::ChronometerModel< Clock >::elapsed(), and measure_one().
measure_one() [4/4]
template<typename Clock, typename Fun> TimingOf< Fun, Chronometer > Catch::Benchmark::Detail::measure_one (Fun && fun, int iters, std::true_type)
Definition at line 31 of file catch_run_for_at_least.hpp.
References CATCH_MOVE, complete_invoke(), and Catch::Benchmark::Detail::ChronometerModel< Clock >::elapsed().
normal_cdf()
double Catch::Benchmark::Detail::normal_cdf (double x) inline
Definition at line 1966 of file catch_amalgamated.hpp.
References normal_cdf().
Referenced by bootstrap(), bootstrap(), normal_cdf(), and TEST_CASE().
normal_quantile()
double Catch::Benchmark::Detail::normal_quantile (double p)
Definition at line 341 of file catch_amalgamated.cpp.
References erfc_inv().
Referenced by bootstrap(), bootstrap(), and TEST_CASE().
repeat()
template<typename Fun> repeater< std::decay_t< Fun > > Catch::Benchmark::Detail::repeat (Fun && fun)
Definition at line 1709 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and repeat().
Referenced by repeat(), Catch::Benchmark::ExecutionPlan< Duration >::run(), and Catch::Benchmark::ExecutionPlan< Duration >::run().
resolution()
template<typename Clock> std::vector< double > Catch::Benchmark::Detail::resolution (int k)
Definition at line 2045 of file catch_amalgamated.hpp.
References resolution().
Referenced by estimate_clock_cost(), estimate_clock_cost(), estimate_clock_resolution(), measure_environment(), resolution(), TEST_CASE(), and warmup().
run_for_at_least() [1/2]
template<typename Clock, typename Fun> TimingOf< Clock, Fun, run_for_at_least_argument_t< Clock, Fun > > Catch::Benchmark::Detail::run_for_at_least (ClockDuration< Clock > how_long, const int initial_iterations, Fun && fun)
Definition at line 1850 of file catch_amalgamated.hpp.
References CATCH_MOVE, Catch::Benchmark::Timing< Duration, Result >::elapsed, measure_one(), Catch::Benchmark::Timing< Duration, Result >::result, run_for_at_least(), and throw_optimized_away_error().
Referenced by estimate_clock_cost(), estimate_clock_cost(), estimate_clock_resolution(), Catch::Benchmark::Benchmark::prepare(), Catch::Benchmark::Benchmark::prepare(), Catch::Benchmark::ExecutionPlan< Duration >::run(), Catch::Benchmark::ExecutionPlan< Duration >::run(), run_for_at_least(), TEST_CASE(), TEST_CASE(), and warmup().
run_for_at_least() [2/2]
template<typename Clock, typename Fun> TimingOf< Fun, run_for_at_least_argument_t< Clock, Fun > > Catch::Benchmark::Detail::run_for_at_least (IDuration how_long, const int initial_iterations, Fun && fun)
Definition at line 47 of file catch_run_for_at_least.hpp.
References CATCH_MOVE, Catch::Benchmark::Timing< Duration, Result >::elapsed, measure_one(), Catch::Benchmark::Timing< Duration, Result >::result, and throw_optimized_away_error().
throw_optimized_away_error()
void Catch::Benchmark::Detail::throw_optimized_away_error ()
Definition at line 77 of file catch_amalgamated.cpp.
References Catch::throw_exception().
Referenced by run_for_at_least(), and run_for_at_least().
warmup()
template<typename Clock> int Catch::Benchmark::Detail::warmup ()
Definition at line 2073 of file catch_amalgamated.hpp.
References resolution(), run_for_at_least(), warmup(), warmup_seed, and warmup_time.
Referenced by measure_environment(), TEST_CASE(), and warmup().
weighted_average_quantile() [1/2]
double Catch::Benchmark::Detail::weighted_average_quantile (int k, int q, double * first, double * last)
Definition at line 227 of file catch_stats.cpp.
References directCompare(), and g().
weighted_average_quantile() [2/2]
double Catch::Benchmark::Detail::weighted_average_quantile (int k, int q, std::vector< double >::iterator first, std::vector< double >::iterator last)
Definition at line 280 of file catch_amalgamated.cpp.
References directCompare(), and g().
Referenced by classify_outliers(), classify_outliers(), and TEST_CASE().
Variable Documentation
clock_cost_estimation_iterations
auto Catch::Benchmark::Detail::clock_cost_estimation_iterations = 10000 constexpr
Definition at line 2070 of file catch_amalgamated.hpp.
Referenced by estimate_clock_cost(), and estimate_clock_cost().
clock_cost_estimation_tick_limit
auto Catch::Benchmark::Detail::clock_cost_estimation_tick_limit = 100000 constexpr
Definition at line 2068 of file catch_amalgamated.hpp.
Referenced by estimate_clock_cost(), and estimate_clock_cost().
clock_cost_estimation_time
auto Catch::Benchmark::Detail::clock_cost_estimation_time = std::chrono::milliseconds(10) constexpr
Definition at line 2069 of file catch_amalgamated.hpp.
Referenced by estimate_clock_cost(), and estimate_clock_cost().
clock_cost_estimation_time_limit
auto Catch::Benchmark::Detail::clock_cost_estimation_time_limit = std::chrono::seconds(1) constexpr
Definition at line 2067 of file catch_amalgamated.hpp.
Referenced by estimate_clock_cost(), and estimate_clock_cost().
clock_resolution_estimation_time
auto Catch::Benchmark::Detail::clock_resolution_estimation_time = std::chrono::milliseconds(500) constexpr
Definition at line 2066 of file catch_amalgamated.hpp.
Referenced by estimate_clock_resolution().
minimum_ticks
auto Catch::Benchmark::Detail::minimum_ticks = 1000 constexpr
Definition at line 2064 of file catch_amalgamated.hpp.
Referenced by Catch::Benchmark::Benchmark::prepare(), and Catch::Benchmark::Benchmark::prepare().
warmup_iterations
auto Catch::Benchmark::Detail::warmup_iterations = 10000 constexpr
Definition at line 2062 of file catch_amalgamated.hpp.
Referenced by Catch::Benchmark::Benchmark::prepare(), and Catch::Benchmark::Benchmark::prepare().
warmup_seed
auto Catch::Benchmark::Detail::warmup_seed = 10000 constexpr
Definition at line 2065 of file catch_amalgamated.hpp.
Referenced by warmup().
warmup_time
auto Catch::Benchmark::Detail::warmup_time = std::chrono::milliseconds(100) constexpr
Definition at line 2063 of file catch_amalgamated.hpp.
Referenced by TEST_CASE(), and warmup().