libthe-seed: JSONLoader Namespace Reference
JSONLoader Namespace Reference
Classes
class Loader
Functions
void StringParse (ecs::Container *, std::string data)
void FileParse (ecs::Container *, std::string filename)
Function Documentation
FileParse()
void JSONLoader::FileParse (ecs::Container * container, std::string filename)
Definition at line 43 of file JSONLoader.cpp.
     {
         std::string data;
         std::ifstream file;
         std::streampos fsize, fstart = 0;
         file.open(filename);
         fstart = file.tellg();
         file.seekg(0, std::ios::end);
         fsize = file.tellg() - fstart;
         file.seekg(0, std::ios::beg);
         data.resize(fsize);
         file.read(&data[0], fsize);
         file.close();
         StringParse(container, data);
     }
References StringParse().
StringParse()
void JSONLoader::StringParse (ecs::Container * container, std::string data)
Definition at line 38 of file JSONLoader.cpp.
     {
         Loader(container, data).Parse();
     }
References JSONLoader::Loader::Parse().
Referenced by FileParse().