libthe-seed: Catch::Matchers Namespace Reference
Catch::Matchers Namespace Reference
Namespaces
namespace Detail
Classes
class MatcherBase
class MatcherUntypedBase
class MatcherGenericBase
class IsEmptyMatcher
class HasSizeMatcher
class SizeMatchesMatcher
class ContainsElementMatcher
Matcher for checking that an element in range is equal to specific element.
class ContainsMatcherMatcher
Meta-matcher for checking that an element in a range matches a specific matcher.
class ExceptionMessageMatcher
class ExceptionMessageMatchesMatcher
class WithinAbsMatcher
class WithinUlpsMatcher
class WithinRelMatcher
class IsNaNMatcher
class PredicateMatcher
class AllMatchMatcher
class NoneMatchMatcher
class AnyMatchMatcher
class AllTrueMatcher
class NoneTrueMatcher
class AnyTrueMatcher
class RangeEqualsMatcher
class UnorderedRangeEqualsMatcher
struct CasedString
class StringMatcherBase
class StringEqualsMatcher
class StringContainsMatcher
class StartsWithMatcher
class EndsWithMatcher
class RegexMatcher
class VectorContainsElementMatcher
class ContainsMatcher
class EqualsMatcher
class ApproxMatcher
class UnorderedEqualsMatcher
Functions
IsEmptyMatcher IsEmpty ()
Creates a matcher that accepts empty ranges/containers.
HasSizeMatcher SizeIs (std::size_t sz)
Creates a matcher that accepts ranges/containers with specific size.
ExceptionMessageMatcher Message (std::string const &message)
Creates a matcher that checks whether a std derived exception has the provided message.
WithinUlpsMatcher WithinULP (double target, uint64_t maxUlpDiff)
Creates a matcher that accepts doubles within certain ULP range of target.
WithinUlpsMatcher WithinULP (float target, uint64_t maxUlpDiff)
Creates a matcher that accepts floats within certain ULP range of target.
WithinAbsMatcher WithinAbs (double target, double margin)
Creates a matcher that accepts numbers within certain range of target.
WithinRelMatcher WithinRel (double target, double eps)
Creates a matcher that accepts doubles within certain relative range of target.
WithinRelMatcher WithinRel (double target)
Creates a matcher that accepts doubles within 100*DBL_EPS relative range of target.
WithinRelMatcher WithinRel (float target, float eps)
Creates a matcher that accepts doubles within certain relative range of target.
WithinRelMatcher WithinRel (float target)
Creates a matcher that accepts floats within 100*FLT_EPS relative range of target.
IsNaNMatcher IsNaN ()
AllTrueMatcher AllTrue ()
NoneTrueMatcher NoneTrue ()
AnyTrueMatcher AnyTrue ()
StringEqualsMatcher Equals (std::string const &str, CaseSensitive caseSensitivity=CaseSensitive::Yes)
Creates matcher that accepts strings that are exactly equal to str.
StringContainsMatcher ContainsSubstring (std::string const &str, CaseSensitive caseSensitivity=CaseSensitive::Yes)
Creates matcher that accepts strings that contain str.
EndsWithMatcher EndsWith (std::string const &str, CaseSensitive caseSensitivity=CaseSensitive::Yes)
Creates matcher that accepts strings that end with str.
StartsWithMatcher StartsWith (std::string const &str, CaseSensitive caseSensitivity=CaseSensitive::Yes)
Creates matcher that accepts strings that start with str.
RegexMatcher Matches (std::string const &regex, CaseSensitive caseSensitivity=CaseSensitive::Yes)
Creates matcher that accepts strings matching regex.
template<typename T>
Detail::MatchAllOf< T > operator&& (MatcherBase< T > const &lhs, MatcherBase< T > const &rhs)
template<typename T>
Detail::MatchAnyOf< T > operator|| (MatcherBase< T > const &lhs, MatcherBase< T > const &rhs)
template<typename T>
Detail::MatchNotOf< T > operator! (MatcherBase< T > const &matcher)
template<typename MatcherLHS, typename MatcherRHS>
std::enable_if_t< Detail::are_generic_matchers< MatcherLHS, MatcherRHS >::value, Detail::MatchAllOfGeneric< MatcherLHS, MatcherRHS > > operator&& (MatcherLHS const &lhs, MatcherRHS const &rhs)
template<typename MatcherLHS, typename MatcherRHS>
std::enable_if_t< Detail::are_generic_matchers< MatcherLHS, MatcherRHS >::value, Detail::MatchAnyOfGeneric< MatcherLHS, MatcherRHS > > operator|| (MatcherLHS const &lhs, MatcherRHS const &rhs)
template<typename MatcherT>
std::enable_if_t< Detail::is_generic_matcher< MatcherT >::value, Detail::MatchNotOfGeneric< MatcherT > > operator! (MatcherT const &matcher)
Wrap provided generic matcher in generic negator.
template<typename MatcherLHS, typename ArgRHS>
std::enable_if_t< Detail::is_generic_matcher< MatcherLHS >::value, Detail::MatchAllOfGeneric< MatcherLHS, MatcherBase< ArgRHS > > > operator&& (MatcherLHS const &lhs, MatcherBase< ArgRHS > const &rhs)
template<typename ArgLHS, typename MatcherRHS>
std::enable_if_t< Detail::is_generic_matcher< MatcherRHS >::value, Detail::MatchAllOfGeneric< MatcherBase< ArgLHS >, MatcherRHS > > operator&& (MatcherBase< ArgLHS > const &lhs, MatcherRHS const &rhs)
template<typename MatcherLHS, typename ArgRHS>
std::enable_if_t< Detail::is_generic_matcher< MatcherLHS >::value, Detail::MatchAnyOfGeneric< MatcherLHS, MatcherBase< ArgRHS > > > operator|| (MatcherLHS const &lhs, MatcherBase< ArgRHS > const &rhs)
template<typename ArgLHS, typename MatcherRHS>
std::enable_if_t< Detail::is_generic_matcher< MatcherRHS >::value, Detail::MatchAnyOfGeneric< MatcherBase< ArgLHS >, MatcherRHS > > operator|| (MatcherBase< ArgLHS > const &lhs, MatcherRHS const &rhs)
template<typename Matcher>
std::enable_if_t< Detail::is_matcher< Matcher >::value, SizeMatchesMatcher< Matcher > > SizeIs (Matcher &&m)
template<typename T>
std::enable_if_t<!Detail::is_matcher< T >::value, ContainsElementMatcher< T, std::equal_to<> > > Contains (T &&elem)
template<typename Matcher>
std::enable_if_t< Detail::is_matcher< Matcher >::value, ContainsMatcherMatcher< Matcher > > Contains (Matcher &&matcher)
Creates a matcher that checks whether a range contains element matching a matcher.
template<typename T, typename Equality>
ContainsElementMatcher< T, Equality > Contains (T &&elem, Equality &&eq)
template<typename StringMatcherType>
ExceptionMessageMatchesMatcher< StringMatcherType > MessageMatches (StringMatcherType &&matcher)
Creates a matcher that checks whether a message from an std derived exception matches a provided matcher.
template<typename T, typename Pred>
PredicateMatcher< T, Pred > Predicate (Pred &&predicate, std::string const &description="")
template<typename Matcher>
AllMatchMatcher< Matcher > AllMatch (Matcher &&matcher)
template<typename Matcher>
NoneMatchMatcher< Matcher > NoneMatch (Matcher &&matcher)
template<typename Matcher>
AnyMatchMatcher< Matcher > AnyMatch (Matcher &&matcher)
template<typename RangeLike>
std::enable_if_t<!Detail::is_matcher< RangeLike >::value, RangeEqualsMatcher< RangeLike, std::equal_to<> > > RangeEquals (RangeLike &&range)
template<typename RangeLike, typename Equality>
RangeEqualsMatcher< RangeLike, Equality > RangeEquals (RangeLike &&range, Equality &&predicate)
template<typename RangeLike>
std::enable_if_t< !Detail::is_matcher< RangeLike >::value, UnorderedRangeEqualsMatcher< RangeLike, std::equal_to<> > > UnorderedRangeEquals (RangeLike &&range)
template<typename RangeLike, typename Equality>
UnorderedRangeEqualsMatcher< RangeLike, Equality > UnorderedRangeEquals (RangeLike &&range, Equality &&predicate)
template<typename T, typename AllocComp = std::allocator<T>, typename AllocMatch = AllocComp>
ContainsMatcher< T, AllocComp, AllocMatch > Contains (std::vector< T, AllocComp > const &comparator)
Creates a matcher that matches vectors that contain all elements in comparator.
template<typename T, typename Alloc = std::allocator<T>>
VectorContainsElementMatcher< T, Alloc > VectorContains (T const &comparator)
Creates a matcher that matches vectors that contain comparator as an element.
template<typename T, typename AllocComp = std::allocator<T>, typename AllocMatch = AllocComp>
EqualsMatcher< T, AllocComp, AllocMatch > Equals (std::vector< T, AllocComp > const &comparator)
Creates a matcher that matches vectors that are exactly equal to comparator.
template<typename T, typename AllocComp = std::allocator<T>, typename AllocMatch = AllocComp>
ApproxMatcher< T, AllocComp, AllocMatch > Approx (std::vector< T, AllocComp > const &comparator)
Creates a matcher that matches vectors that comparator as an element.
template<typename T, typename AllocComp = std::allocator<T>, typename AllocMatch = AllocComp>
UnorderedEqualsMatcher< T, AllocComp, AllocMatch > UnorderedEquals (std::vector< T, AllocComp > const &target)
Creates a matcher that matches vectors that is equal to target modulo permutation.
Function Documentation
AllMatch()
template<typename Matcher> AllMatchMatcher< Matcher > Catch::Matchers::AllMatch (Matcher && matcher)
Definition at line 11702 of file catch_amalgamated.hpp.
References AllMatch(), and CATCH_FORWARD.
Referenced by AllMatch(), and TEST_CASE().
AllTrue()
AllTrueMatcher Catch::Matchers::AllTrue ()
Definition at line 7786 of file catch_amalgamated.cpp.
Referenced by TEST_CASE(), and TEST_CASE().
AnyMatch()
template<typename Matcher> AnyMatchMatcher< Matcher > Catch::Matchers::AnyMatch (Matcher && matcher)
Definition at line 11714 of file catch_amalgamated.hpp.
References AnyMatch(), and CATCH_FORWARD.
Referenced by AnyMatch(), and TEST_CASE().
AnyTrue()
AnyTrueMatcher Catch::Matchers::AnyTrue ()
Definition at line 7794 of file catch_amalgamated.cpp.
Referenced by TEST_CASE(), and TEST_CASE().
Approx()
template<typename T, typename AllocComp = std::allocator<T>, typename AllocMatch = AllocComp> ApproxMatcher< T, AllocComp, AllocMatch > Catch::Matchers::Approx (std::vector< T, AllocComp > const & comparator)
Creates a matcher that matches vectors that comparator as an element.
Definition at line 12117 of file catch_amalgamated.hpp.
References Approx().
Referenced by Approx(), TEST_CASE(), and TEST_CASE().
Contains() [1/4]
template<typename Matcher> std::enable_if_t< Detail::is_matcher< Matcher >::value, ContainsMatcherMatcher< Matcher > > Catch::Matchers::Contains (Matcher && matcher)
Creates a matcher that checks whether a range contains element matching a matcher.
Definition at line 11360 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and Contains().
Contains() [2/4]
template<typename T, typename AllocComp = std::allocator<T>, typename AllocMatch = AllocComp> ContainsMatcher< T, AllocComp, AllocMatch > Catch::Matchers::Contains (std::vector< T, AllocComp > const & comparator)
Creates a matcher that matches vectors that contain all elements in comparator.
Definition at line 12099 of file catch_amalgamated.hpp.
References Contains().
Contains() [3/4]
template<typename T> std::enable_if_t<!Detail::is_matcher< T >::value, ContainsElementMatcher< T, std::equal_to<> > > Catch::Matchers::Contains (T && elem)
Creates a matcher that checks whether a range contains a specific element.
Uses std::equal_to to do the comparison
Definition at line 11353 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and Contains().
Referenced by Contains(), Contains(), Contains(), Contains(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
Contains() [4/4]
template<typename T, typename Equality> ContainsElementMatcher< T, Equality > Catch::Matchers::Contains (T && elem, Equality && eq)
Creates a matcher that checks whether a range contains a specific element.
Uses eq to do the comparisons, the element is provided on the rhs
Definition at line 11370 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and Contains().
ContainsSubstring()
StringContainsMatcher Catch::Matchers::ContainsSubstring (std::string const & str, CaseSensitive caseSensitivity)
Creates matcher that accepts strings that contain str.
Definition at line 7886 of file catch_amalgamated.cpp.
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
EndsWith()
EndsWithMatcher Catch::Matchers::EndsWith (std::string const & str, CaseSensitive caseSensitivity)
Creates matcher that accepts strings that end with str.
Definition at line 7889 of file catch_amalgamated.cpp.
Referenced by templated_tests(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
Equals() [1/2]
StringEqualsMatcher Catch::Matchers::Equals (std::string const & str, CaseSensitive caseSensitivity)
Creates matcher that accepts strings that are exactly equal to str.
Definition at line 7883 of file catch_amalgamated.cpp.
Referenced by CATCH_TEST_CASE(), Equals(), Catch::handleExceptionMatchExpr(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
Equals() [2/2]
template<typename T, typename AllocComp = std::allocator<T>, typename AllocMatch = AllocComp> EqualsMatcher< T, AllocComp, AllocMatch > Catch::Matchers::Equals (std::vector< T, AllocComp > const & comparator)
Creates a matcher that matches vectors that are exactly equal to comparator.
Definition at line 12111 of file catch_amalgamated.hpp.
References Equals().
IsEmpty()
IsEmptyMatcher Catch::Matchers::IsEmpty ()
Creates a matcher that accepts empty ranges/containers.
Definition at line 7508 of file catch_amalgamated.cpp.
Referenced by TEST_CASE().
IsNaN()
IsNaNMatcher Catch::Matchers::IsNaN ()
Definition at line 7764 of file catch_amalgamated.cpp.
Referenced by TEST_CASE(), TEST_CASE(), and TEST_CASE().
Matches()
RegexMatcher Catch::Matchers::Matches (std::string const & regex, CaseSensitive caseSensitivity)
Creates matcher that accepts strings matching regex.
Definition at line 7896 of file catch_amalgamated.cpp.
Referenced by TEST_CASE(), and TEST_CASE().
Message()
ExceptionMessageMatcher Catch::Matchers::Message (std::string const & message)
Creates a matcher that checks whether a std derived exception has the provided message.
Definition at line 7532 of file catch_amalgamated.cpp.
Referenced by TEST_CASE().
MessageMatches()
template<typename StringMatcherType> ExceptionMessageMatchesMatcher< StringMatcherType > Catch::Matchers::MessageMatches (StringMatcherType && matcher)
Creates a matcher that checks whether a message from an std derived exception matches a provided matcher.
Definition at line 11425 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and MessageMatches().
Referenced by MessageMatches(), and TEST_CASE().
NoneMatch()
template<typename Matcher> NoneMatchMatcher< Matcher > Catch::Matchers::NoneMatch (Matcher && matcher)
Definition at line 11708 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and NoneMatch().
Referenced by NoneMatch(), and TEST_CASE().
NoneTrue()
NoneTrueMatcher Catch::Matchers::NoneTrue ()
Definition at line 7790 of file catch_amalgamated.cpp.
Referenced by TEST_CASE(), and TEST_CASE().
operator!() [1/2]
template<typename T> Detail::MatchNotOf< T > Catch::Matchers::operator! (MatcherBase< T > const & matcher)
Definition at line 10859 of file catch_amalgamated.hpp.
operator!() [2/2]
template<typename MatcherT> std::enable_if_t< Detail::is_generic_matcher< MatcherT >::value, Detail::MatchNotOfGeneric< MatcherT > > Catch::Matchers::operator! (MatcherT const & matcher)
Wrap provided generic matcher in generic negator.
Definition at line 11172 of file catch_amalgamated.hpp.
operator&&() [1/4]
template<typename ArgLHS, typename MatcherRHS> std::enable_if_t< Detail::is_generic_matcher< MatcherRHS >::value, Detail::MatchAllOfGeneric< MatcherBase< ArgLHS >, MatcherRHS > > Catch::Matchers::operator&& (MatcherBase< ArgLHS > const & lhs, MatcherRHS const & rhs)
Definition at line 11186 of file catch_amalgamated.hpp.
operator&&() [2/4]
template<typename T> Detail::MatchAllOf< T > Catch::Matchers::operator&& (MatcherBase< T > const & lhs, MatcherBase< T > const & rhs)
Definition at line 10850 of file catch_amalgamated.hpp.
operator&&() [3/4]
template<typename MatcherLHS, typename ArgRHS> std::enable_if_t< Detail::is_generic_matcher< MatcherLHS >::value, Detail::MatchAllOfGeneric< MatcherLHS, MatcherBase< ArgRHS > > > Catch::Matchers::operator&& (MatcherLHS const & lhs, MatcherBase< ArgRHS > const & rhs)
Definition at line 11180 of file catch_amalgamated.hpp.
operator&&() [4/4]
template<typename MatcherLHS, typename MatcherRHS> std::enable_if_t< Detail::are_generic_matchers< MatcherLHS, MatcherRHS >::value, Detail::MatchAllOfGeneric< MatcherLHS, MatcherRHS > > Catch::Matchers::operator&& (MatcherLHS const & lhs, MatcherRHS const & rhs)
Definition at line 11159 of file catch_amalgamated.hpp.
operator||() [1/4]
template<typename ArgLHS, typename MatcherRHS> std::enable_if_t< Detail::is_generic_matcher< MatcherRHS >::value, Detail::MatchAnyOfGeneric< MatcherBase< ArgLHS >, MatcherRHS > > Catch::Matchers::operator|| (MatcherBase< ArgLHS > const & lhs, MatcherRHS const & rhs)
Definition at line 11198 of file catch_amalgamated.hpp.
operator||() [2/4]
template<typename T> Detail::MatchAnyOf< T > Catch::Matchers::operator|| (MatcherBase< T > const & lhs, MatcherBase< T > const & rhs)
Definition at line 10854 of file catch_amalgamated.hpp.
operator||() [3/4]
template<typename MatcherLHS, typename ArgRHS> std::enable_if_t< Detail::is_generic_matcher< MatcherLHS >::value, Detail::MatchAnyOfGeneric< MatcherLHS, MatcherBase< ArgRHS > > > Catch::Matchers::operator|| (MatcherLHS const & lhs, MatcherBase< ArgRHS > const & rhs)
Definition at line 11192 of file catch_amalgamated.hpp.
operator||() [4/4]
template<typename MatcherLHS, typename MatcherRHS> std::enable_if_t< Detail::are_generic_matchers< MatcherLHS, MatcherRHS >::value, Detail::MatchAnyOfGeneric< MatcherLHS, MatcherRHS > > Catch::Matchers::operator|| (MatcherLHS const & lhs, MatcherRHS const & rhs)
Definition at line 11165 of file catch_amalgamated.hpp.
Predicate()
template<typename T, typename Pred> PredicateMatcher< T, Pred > Catch::Matchers::Predicate (Pred && predicate, std::string const & description = "")
Creates a matcher that calls delegates match to the provided predicate.
The user has to explicitly specify the argument type to the matcher
Definition at line 11562 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and Predicate().
Referenced by CATCH_TEST_CASE(), Predicate(), Catch::Matchers::PredicateMatcher< T, Predicate >::PredicateMatcher(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
RangeEquals() [1/2]
template<typename RangeLike> std::enable_if_t<!Detail::is_matcher< RangeLike >::value, RangeEqualsMatcher< RangeLike, std::equal_to<> > > Catch::Matchers::RangeEquals (RangeLike && range)
Creates a matcher that checks if all elements in a range are equal to all elements in another range.
Uses std::equal_to to do the comparison
Definition at line 11822 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and RangeEquals().
Referenced by RangeEquals(), RangeEquals(), TEST_CASE(), and TEST_CASE().
RangeEquals() [2/2]
template<typename RangeLike, typename Equality> RangeEqualsMatcher< RangeLike, Equality > Catch::Matchers::RangeEquals (RangeLike && range, Equality && predicate)
Creates a matcher that checks if all elements in a range are equal to all elements in another range.
Uses to provided predicate predicate to do the comparisons
Definition at line 11834 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and RangeEquals().
SizeIs() [1/2]
template<typename Matcher> std::enable_if_t< Detail::is_matcher< Matcher >::value, SizeMatchesMatcher< Matcher > > Catch::Matchers::SizeIs (Matcher && m)
Definition at line 11275 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and SizeIs().
SizeIs() [2/2]
HasSizeMatcher Catch::Matchers::SizeIs (std::size_t sz)
Creates a matcher that accepts ranges/containers with specific size.
Definition at line 7512 of file catch_amalgamated.cpp.
Referenced by SizeIs(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
StartsWith()
StartsWithMatcher Catch::Matchers::StartsWith (std::string const & str, CaseSensitive caseSensitivity)
Creates matcher that accepts strings that start with str.
Definition at line 7892 of file catch_amalgamated.cpp.
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
UnorderedEquals()
template<typename T, typename AllocComp = std::allocator<T>, typename AllocMatch = AllocComp> UnorderedEqualsMatcher< T, AllocComp, AllocMatch > Catch::Matchers::UnorderedEquals (std::vector< T, AllocComp > const & target)
Creates a matcher that matches vectors that is equal to target modulo permutation.
Definition at line 12123 of file catch_amalgamated.hpp.
References UnorderedEquals().
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), and UnorderedEquals().
UnorderedRangeEquals() [1/2]
template<typename RangeLike> std::enable_if_t< !Detail::is_matcher< RangeLike >::value, UnorderedRangeEqualsMatcher< RangeLike, std::equal_to<> > > Catch::Matchers::UnorderedRangeEquals (RangeLike && range)
Creates a matcher that checks if all elements in a range are equal to all elements in another range, in some permutation
Uses std::equal_to to do the comparison
Definition at line 11848 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and UnorderedRangeEquals().
Referenced by TEST_CASE(), TEST_CASE(), UnorderedRangeEquals(), and UnorderedRangeEquals().
UnorderedRangeEquals() [2/2]
template<typename RangeLike, typename Equality> UnorderedRangeEqualsMatcher< RangeLike, Equality > Catch::Matchers::UnorderedRangeEquals (RangeLike && range, Equality && predicate)
Creates a matcher that checks if all elements in a range are equal to all elements in another range, in some permutation.
Uses to provided predicate predicate to do the comparisons
Definition at line 11860 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and UnorderedRangeEquals().
VectorContains()
template<typename T, typename Alloc = std::allocator<T>> VectorContainsElementMatcher< T, Alloc > Catch::Matchers::VectorContains (T const & comparator)
Creates a matcher that matches vectors that contain comparator as an element.
Definition at line 12105 of file catch_amalgamated.hpp.
References VectorContains().
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and VectorContains().
WithinAbs()
WithinAbsMatcher Catch::Matchers::WithinAbs (double target, double margin)
Creates a matcher that accepts numbers within certain range of target.
Definition at line 7733 of file catch_amalgamated.cpp.
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
WithinRel() [1/4]
WithinRelMatcher Catch::Matchers::WithinRel (double target)
Creates a matcher that accepts doubles within 100*DBL_EPS relative range of target.
Definition at line 7741 of file catch_amalgamated.cpp.
WithinRel() [2/4]
WithinRelMatcher Catch::Matchers::WithinRel (double target, double eps)
Creates a matcher that accepts doubles within certain relative range of target.
Definition at line 7737 of file catch_amalgamated.cpp.
Referenced by TEST_CASE(), TEST_CASE(), and TEST_CASE().
WithinRel() [3/4]
WithinRelMatcher Catch::Matchers::WithinRel (float target)
Creates a matcher that accepts floats within 100*FLT_EPS relative range of target.
Definition at line 7749 of file catch_amalgamated.cpp.
WithinRel() [4/4]
WithinRelMatcher Catch::Matchers::WithinRel (float target, float eps)
Creates a matcher that accepts doubles within certain relative range of target.
Definition at line 7745 of file catch_amalgamated.cpp.
WithinULP() [1/2]
WithinUlpsMatcher Catch::Matchers::WithinULP (double target, uint64_t maxUlpDiff)
Creates a matcher that accepts doubles within certain ULP range of target.
Definition at line 7725 of file catch_amalgamated.cpp.
Referenced by TEMPLATE_TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
WithinULP() [2/2]
WithinUlpsMatcher Catch::Matchers::WithinULP (float target, uint64_t maxUlpDiff)
Creates a matcher that accepts floats within certain ULP range of target.
Definition at line 7729 of file catch_amalgamated.cpp.