libthe-seed: Catch::Generators Namespace Reference
Catch::Generators Namespace Reference
Namespaces
namespace Detail
Classes
class GeneratorUntypedBase
class IGenerator
class GeneratorWrapper
class SingleValueGenerator
class FixedValuesGenerator
class Generators
struct as
class TakeGenerator
class FilterGenerator
class RepeatGenerator
class MapGenerator
class ChunkGenerator
class RandomFloatingGenerator
class RandomIntegerGenerator
class RangeGenerator
class IteratorGenerator
Typedefs
using GeneratorBasePtr = Catch::Detail::unique_ptr<GeneratorUntypedBase>
template<typename T>
using GeneratorPtr = Catch::Detail::unique_ptr<IGenerator<T>>
Functions
IGeneratorTracker * acquireGeneratorTracker (StringRef generatorName, SourceLineInfo const &lineInfo)
IGeneratorTracker * createGeneratorTracker (StringRef generatorName, SourceLineInfo lineInfo, GeneratorBasePtr &&generator)
template<typename T, typename DecayedT = std::decay_t<T>>
GeneratorWrapper< DecayedT > value (T &&value)
template<typename T>
GeneratorWrapper< T > values (std::initializer_list< T > values)
template<typename... Ts>
GeneratorWrapper< std::tuple< std::decay_t< Ts >... > > table (std::initializer_list< std::tuple< std::decay_t< Ts >... > > tuples)
template<typename T, typename... Gs>
auto makeGenerators (GeneratorWrapper< T > &&generator, Gs &&... moreGenerators) -> Generators< T >
template<typename T>
auto makeGenerators (GeneratorWrapper< T > &&generator) -> Generators< T >
template<typename T, typename... Gs>
auto makeGenerators (T &&val, Gs &&... moreGenerators) -> Generators< std::decay_t< T > >
template<typename T, typename U, typename... Gs>
auto makeGenerators (as< T >, U &&val, Gs &&... moreGenerators) -> Generators< T >
template<typename L>
auto generate (StringRef generatorName, SourceLineInfo const &lineInfo, L const &generatorExpression) -> typename decltype(generatorExpression())::type
template<typename T>
GeneratorWrapper< T > take (size_t target, GeneratorWrapper< T > &&generator)
template<typename T, typename Predicate>
GeneratorWrapper< T > filter (Predicate &&pred, GeneratorWrapper< T > &&generator)
template<typename T>
GeneratorWrapper< T > repeat (size_t repeats, GeneratorWrapper< T > &&generator)
template<typename Func, typename U, typename T = FunctionReturnType<Func, U>>
GeneratorWrapper< T > map (Func &&function, GeneratorWrapper< U > &&generator)
template<typename T>
GeneratorWrapper< std::vector< T > > chunk (size_t size, GeneratorWrapper< T > &&generator)
template<typename T>
std::enable_if_t< std::is_integral< T >::value, GeneratorWrapper< T > > random (T a, T b)
template<typename T>
std::enable_if_t< std::is_floating_point< T >::value, GeneratorWrapper< T > > random (T a, T b)
template<typename T>
GeneratorWrapper< T > range (T const &start, T const &end, T const &step)
template<typename T>
GeneratorWrapper< T > range (T const &start, T const &end)
template<typename InputIterator, typename InputSentinel, typename ResultType = typename std::iterator_traits<InputIterator>::value_type>
GeneratorWrapper< ResultType > from_range (InputIterator from, InputSentinel to)
template<typename Container, typename ResultType = typename Container::value_type>
GeneratorWrapper< ResultType > from_range (Container const &cnt)
template<typename Container>
auto from_range (Container const &cnt)
Typedef Documentation
GeneratorBasePtr
typedef Catch::Detail::unique_ptr< GeneratorUntypedBase > Catch::Generators::GeneratorBasePtr = Catch::Detail::unique_ptr<GeneratorUntypedBase>
Definition at line 986 of file catch_amalgamated.hpp.
GeneratorPtr
template<typename T> using Catch::Generators::GeneratorPtr = Catch::Detail::unique_ptr<IGenerator<T>>
Definition at line 7551 of file catch_amalgamated.hpp.
Function Documentation
acquireGeneratorTracker()
IGeneratorTracker * Catch::Generators::acquireGeneratorTracker (StringRef generatorName, SourceLineInfo const & lineInfo)
Definition at line 2172 of file catch_amalgamated.cpp.
References Catch::IResultCapture::acquireGeneratorTracker(), and Catch::getResultCapture().
Referenced by generate().
chunk()
template<typename T> GeneratorWrapper< std::vector< T > > Catch::Generators::chunk (size_t size, GeneratorWrapper< T > && generator)
Definition at line 7969 of file catch_amalgamated.hpp.
References CATCH_MOVE, chunk(), and Catch::Detail::make_unique().
Referenced by chunk(), and TEST_CASE().
createGeneratorTracker()
IGeneratorTracker * Catch::Generators::createGeneratorTracker (StringRef generatorName, SourceLineInfo lineInfo, GeneratorBasePtr && generator)
Definition at line 2176 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::IResultCapture::createGeneratorTracker(), and Catch::getResultCapture().
Referenced by generate().
filter()
template<typename T, typename Predicate> GeneratorWrapper< T > Catch::Generators::filter (Predicate && pred, GeneratorWrapper< T > && generator)
Definition at line 7831 of file catch_amalgamated.hpp.
References CATCH_FORWARD, CATCH_MOVE, filter(), and Catch::Detail::make_unique().
Referenced by filter(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
from_range() [1/3]
template<typename Container, typename ResultType = typename Container::value_type> GeneratorWrapper< ResultType > Catch::Generators::from_range (Container const & cnt)
Definition at line 8218 of file catch_amalgamated.hpp.
References from_range(), and Catch::Detail::make_unique().
from_range() [2/3]
template<typename Container> auto Catch::Generators::from_range (Container const & cnt)
Definition at line 100 of file catch_generators_range.hpp.
References from_range().
from_range() [3/3]
template<typename InputIterator, typename InputSentinel, typename ResultType = typename std::iterator_traits<InputIterator>::value_type> GeneratorWrapper< ResultType > Catch::Generators::from_range (InputIterator from, InputSentinel to)
Definition at line 8212 of file catch_amalgamated.hpp.
References from_range(), and Catch::Detail::make_unique().
Referenced by from_range(), from_range(), TEST_CASE(), and TEST_CASE().
generate()
template<typename L> auto Catch::Generators::generate (StringRef generatorName, SourceLineInfo const & lineInfo, L const & generatorExpression)->typenamedecltype(generatorExpression())::type
Definition at line 7709 of file catch_amalgamated.hpp.
References acquireGeneratorTracker(), createGeneratorTracker(), generate(), Catch::IGeneratorTracker::getGenerator(), and Catch::Detail::make_unique().
Referenced by generate(), and TEST_CASE().
makeGenerators() [1/4]
template<typename T, typename U, typename... Gs> auto Catch::Generators::makeGenerators (as< T > , U && val, Gs &&... moreGenerators)->Generators< T >
Definition at line 7698 of file catch_amalgamated.hpp.
References CATCH_FORWARD, makeGenerators(), and value().
makeGenerators() [2/4]
template<typename T> auto Catch::Generators::makeGenerators (GeneratorWrapper< T > && generator) ->Generators< T >
Definition at line 7690 of file catch_amalgamated.hpp.
References CATCH_MOVE, and makeGenerators().
makeGenerators() [3/4]
template<typename T, typename... Gs> auto Catch::Generators::makeGenerators (GeneratorWrapper< T > && generator, Gs &&... moreGenerators)->Generators< T >
Definition at line 7686 of file catch_amalgamated.hpp.
References CATCH_FORWARD, CATCH_MOVE, and makeGenerators().
Referenced by makeGenerators(), makeGenerators(), makeGenerators(), makeGenerators(), TEST_CASE(), and TEST_CASE().
makeGenerators() [4/4]
template<typename T, typename... Gs> auto Catch::Generators::makeGenerators (T && val, Gs &&... moreGenerators)->Generators< std::decay_t< T > >
Definition at line 7694 of file catch_amalgamated.hpp.
References CATCH_FORWARD, makeGenerators(), and value().
map()
template<typename Func, typename U, typename T = FunctionReturnType<Func, U>> GeneratorWrapper< T > Catch::Generators::map (Func && function, GeneratorWrapper< U > && generator)
Definition at line 7919 of file catch_amalgamated.hpp.
References CATCH_FORWARD, CATCH_MOVE, Catch::Detail::make_unique(), and map().
Referenced by map(), TEST_CASE(), and TEST_CASE().
random() [1/2]
template<typename T> std::enable_if_t< std::is_floating_point< T >::value, GeneratorWrapper< T > > Catch::Generators::random (T a, T b)
Definition at line 8112 of file catch_amalgamated.hpp.
References Catch::Generators::Detail::getSeed(), Catch::Detail::make_unique(), and random().
random() [2/2]
template<typename T> std::enable_if_t< std::is_integral< T >::value, GeneratorWrapper< T > > Catch::Generators::random (T a, T b)
Definition at line 8095 of file catch_amalgamated.hpp.
References Catch::Generators::Detail::getSeed(), Catch::Detail::make_unique(), and random().
Referenced by random(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
range() [1/2]
template<typename T> GeneratorWrapper< T > Catch::Generators::range (T const & start, T const & end)
Definition at line 8177 of file catch_amalgamated.hpp.
References Catch::Detail::make_unique(), and range().
range() [2/2]
template<typename T> GeneratorWrapper< T > Catch::Generators::range (T const & start, T const & end, T const & step)
Definition at line 8171 of file catch_amalgamated.hpp.
References Catch::Detail::make_unique(), and range().
Referenced by range(), range(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
repeat()
template<typename T> GeneratorWrapper< T > Catch::Generators::repeat (size_t repeats, GeneratorWrapper< T > && generator)
Definition at line 7887 of file catch_amalgamated.hpp.
References CATCH_MOVE, Catch::Detail::make_unique(), and repeat().
Referenced by repeat(), TEST_CASE(), and TEST_CASE().
table()
template<typename... Ts> GeneratorWrapper< std::tuple< std::decay_t< Ts >... > > Catch::Generators::table (std::initializer_list< std::tuple< std::decay_t< Ts >... > > tuples)
Definition at line 7677 of file catch_amalgamated.hpp.
References table(), and values().
Referenced by table(), and TEST_CASE().
take()
template<typename T> GeneratorWrapper< T > Catch::Generators::take (size_t target, GeneratorWrapper< T > && generator)
Definition at line 7790 of file catch_amalgamated.hpp.
References CATCH_MOVE, Catch::Detail::make_unique(), and take().
Referenced by take(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
value()
template<typename T, typename DecayedT = std::decay_t<T>> GeneratorWrapper< DecayedT > Catch::Generators::value (T && value)
Definition at line 7611 of file catch_amalgamated.hpp.
References CATCH_FORWARD, Catch::Detail::make_unique(), and value().
Referenced by makeGenerators(), makeGenerators(), Catch::Generators::SingleValueGenerator< T >::SingleValueGenerator(), Catch::Generators::SingleValueGenerator< T >::SingleValueGenerator(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and value().
values()
template<typename T> GeneratorWrapper< T > Catch::Generators::values (std::initializer_list< T > values)
Definition at line 7617 of file catch_amalgamated.hpp.
References Catch::Detail::make_unique(), and values().
Referenced by Catch::Generators::FixedValuesGenerator< T >::FixedValuesGenerator(), table(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and values().