libthe-seed: Catch Namespace Reference
Catch Namespace Reference
Namespaces
namespace Benchmark
namespace literals
namespace Detail
namespace Generators
namespace Clara
namespace TestCaseTracking
namespace TextFlow
namespace Matchers
Classes
class Context
struct TestFailureException
Used to signal that an assertion macro failed.
struct TestSkipException
Used to signal that the remainder of a test should be skipped.
class StringRef
A non-owning string class (similar to the forthcoming std::string_view) Note that, because a StringRef may be a substring of another string, it may not be null terminated.
struct ResultWas
struct ResultDisposition
struct BenchmarkStats
class IResultCapture
struct WarnAbout
struct WaitForKeypress
class IConfig
class IRegistryHub
class IMutableRegistryHub
struct BenchmarkInfo
struct true_given
struct is_callable_tester
struct is_callable
struct is_callable< Fun(Args...)>
class ReusableStringStream
class IMutableEnumValuesRegistry
struct StringMaker
struct StringMaker< std::string >
struct StringMaker< char const * >
struct StringMaker< char * >
struct StringMaker< std::wstring >
struct StringMaker< wchar_t const * >
struct StringMaker< wchar_t * >
struct StringMaker< char[SZ]>
struct StringMaker< signed char[SZ]>
struct StringMaker< unsigned char[SZ]>
struct StringMaker< int >
struct StringMaker< long >
struct StringMaker< long long >
struct StringMaker< unsigned int >
struct StringMaker< unsigned long >
struct StringMaker< unsigned long long >
struct StringMaker< bool >
struct StringMaker< char >
struct StringMaker< signed char >
struct StringMaker< unsigned char >
struct StringMaker< std::nullptr_t >
struct StringMaker< float >
struct StringMaker< double >
struct StringMaker< T * >
struct StringMaker< R C::* >
struct is_range
struct StringMaker< R, std::enable_if_t< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value > >
struct StringMaker< T[SZ]>
struct ratio_string
struct ratio_string< std::atto >
struct ratio_string< std::femto >
struct ratio_string< std::pico >
struct ratio_string< std::nano >
struct ratio_string< std::micro >
struct ratio_string< std::milli >
struct StringMaker< std::chrono::duration< Value, Ratio > >
struct StringMaker< std::chrono::duration< Value, std::ratio< 1 > > >
struct StringMaker< std::chrono::duration< Value, std::ratio< 60 > > >
struct StringMaker< std::chrono::duration< Value, std::ratio< 3600 > > >
struct StringMaker< std::chrono::time_point< Clock, Duration > >
struct StringMaker< std::chrono::time_point< std::chrono::system_clock, Duration > >
class Approx
struct StringMaker< Catch::Approx >
struct SourceLineInfo
struct AssertionInfo
class LazyExpression
struct AssertionResultData
class AssertionResult
class WildcardPattern
class TestSpec
class Optional
struct Colour
class ColourImpl
class ReporterSpec
struct ProcessedReporterSpec
struct ConfigData
class Config
struct StreamEndStop
struct MessageInfo
struct MessageStream
struct MessageBuilder
class ScopedMessage
class Capturer
struct Counts
struct Totals
struct SectionInfo
struct SectionEndInfo
class Session
struct TagAlias
struct RegistrarForTagAliases
struct always_false
class ITransientExpression
class BinaryExpr
class UnaryExpr
class ExprLhs
struct Decomposer
struct AssertionReaction
class AssertionHandler
class Timer
class Section
class ITestInvoker
class TestInvokerAsMethod
struct NameAndTags
struct AutoReg
struct Tag
struct TestCaseInfo
class TestCaseHandle
class IExceptionTranslator
class IExceptionTranslatorRegistry
class ExceptionTranslatorRegistrar
struct Version
class GeneratorException
class IGeneratorTracker
class SimplePcg32
struct TestRunInfo
struct ReporterConfig
struct AssertionStats
struct SectionStats
struct TestCaseStats
struct TestRunStats
struct ReporterPreferences
By setting up its preferences, a reporter can modify Catch2's behaviour in some regards, e.g. it can request Catch2 to capture writes to stdout/stderr during test execution, and pass them to the reporter.
class IEventListener
class IReporterFactory
class EventListenerFactory
class ITagAliasRegistry
class ITestCaseRegistry
class ErrnoGuard
Simple RAII class that stores the value of errno at construction and restores it at destruction.
class ExceptionTranslatorRegistry
class FatalConditionHandler
class FatalConditionHandlerGuard
Simple RAII guard for (dis)engaging the FatalConditionHandler.
class IStream
struct LeakDetector
struct ReporterDescription
struct ListenerDescription
struct TagInfo
class RedirectedStream
class RedirectedStdOut
class RedirectedStdErr
class RedirectedStreams
class ReporterRegistry
class RunContext
struct ISingleton
class Singleton
class StartupExceptionRegistry
class pluralise
class TagAliasRegistry
class TestCaseInfoHasher
class TestRegistry
class TestSpecParser
class XmlEncode
class XmlWriter
class MatchExpr
class ReporterBase
class StreamingReporterBase
class AutomakeReporter
class CompactReporter
class ConsoleReporter
class CumulativeReporterBase
class EventListenerBase
struct lineOfChars
class JunitReporter
class MultiReporter
class ReporterFactory
class ReporterRegistrar
class ListenerRegistrar
class SonarQubeReporter
class TAPReporter
class TeamCityReporter
class XmlReporter
struct is_range< with_mocked_iterator_access< T > >
struct StringMaker< with_mocked_iterator_access< T > >
class ITracker
class TrackerContext
class SectionTracker
Typedefs
using RegistryHubSingleton = Singleton<RegistryHub, IRegistryHub, IMutableRegistryHub>
using IReporterFactoryPtr = Detail::unique_ptr<IReporterFactory>
template<typename Func, typename... U>
using FunctionReturnType = std::remove_reference_t<std::remove_cv_t<std::result_of_t<Func(U...)>>>
using exceptionTranslateFunction = std::string(*)()
using ExceptionTranslators = std::vector<Detail::unique_ptr<IExceptionTranslator const>>
using IEventListenerPtr = Detail::unique_ptr<IEventListener>
using StringMatcher = Matchers::MatcherBase<std::string>
Enumerations
enum class Verbosity {
Quiet = 0 , Normal , High , Quiet = 0 ,
Normal , High
}
enum class ShowDurations {
DefaultForReporter , Always , Never , DefaultForReporter ,
Always , Never
}
enum class TestRunOrder {
Declared , LexicographicallySorted , Randomized , Declared ,
LexicographicallySorted , Randomized
}
enum class ColourMode : std::uint8_t {
PlatformDefault , ANSI , Win32 , None ,
PlatformDefault , ANSI , Win32 , None
}
enum class CaseSensitive { Yes , No , Yes , No }
enum class GenerateFrom {
Time , RandomDevice , Default , Time ,
RandomDevice , Default
}
enum class TestCaseProperties : uint8_t {
None = 0 , IsHidden = 1 << 1 , ShouldFail = 1 << 2 , MayFail = 1 << 3 ,
Throws = 1 << 4 , NonPortable = 1 << 5 , Benchmark = 1 << 6 , None = 0 ,
IsHidden = 1 << 1 , ShouldFail = 1 << 2 , MayFail = 1 << 3 , Throws = 1 << 4 ,
NonPortable = 1 << 5 , Benchmark = 1 << 6
}
enum class XmlFormatting {
None = 0x00 , Indent = 0x01 , Newline = 0x02 , None = 0x00 ,
Indent = 0x01 , Newline = 0x02
}
enum class TestCaseProperties : uint8_t {
None = 0 , IsHidden = 1 << 1 , ShouldFail = 1 << 2 , MayFail = 1 << 3 ,
Throws = 1 << 4 , NonPortable = 1 << 5 , Benchmark = 1 << 6 , None = 0 ,
IsHidden = 1 << 1 , ShouldFail = 1 << 2 , MayFail = 1 << 3 , Throws = 1 << 4 ,
NonPortable = 1 << 5 , Benchmark = 1 << 6
}
enum class Verbosity {
Quiet = 0 , Normal , High , Quiet = 0 ,
Normal , High
}
enum class ShowDurations {
DefaultForReporter , Always , Never , DefaultForReporter ,
Always , Never
}
enum class TestRunOrder {
Declared , LexicographicallySorted , Randomized , Declared ,
LexicographicallySorted , Randomized
}
enum class ColourMode : std::uint8_t {
PlatformDefault , ANSI , Win32 , None ,
PlatformDefault , ANSI , Win32 , None
}
enum class CaseSensitive { Yes , No , Yes , No }
enum class GenerateFrom {
Time , RandomDevice , Default , Time ,
RandomDevice , Default
}
enum class XmlFormatting {
None = 0x00 , Indent = 0x01 , Newline = 0x02 , None = 0x00 ,
Indent = 0x01 , Newline = 0x02
}
Functions
std::ostream & cout ()
std::ostream & clog ()
std::ostream & cerr ()
bool operator== (ProcessedReporterSpec const &lhs, ProcessedReporterSpec const &rhs)
std::uint32_t getSeed ()
Returns Catch2's current RNG seed.
IRegistryHub const & getRegistryHub ()
IMutableRegistryHub & getMutableRegistryHub ()
void cleanUp ()
std::string translateActiveException ()
bool operator< (Tag const &lhs, Tag const &rhs)
bool operator== (Tag const &lhs, Tag const &rhs)
Detail::unique_ptr< TestCaseInfo > makeTestCaseInfo (StringRef _className, NameAndTags const &nameAndTags, SourceLineInfo const &_lineInfo)
bool operator< (TestCaseInfo const &lhs, TestCaseInfo const &rhs)
std::ostream & operator<< (std::ostream &os, Version const &version)
Version const & libraryVersion ()
void handleExceptionMatchExpr (AssertionHandler &handler, std::string const &str)
Clara::Parser makeCommandLineParser (ConfigData &config)
Detail::unique_ptr< ColourImpl > makeColourImpl (ColourMode colourSelection, IStream *stream)
Provides ColourImpl based on global config and target compilation platform.
bool isColourImplAvailable (ColourMode colourSelection)
Checks if specific colour impl has been compiled into the binary.
void cleanUpContext ()
Context & getCurrentMutableContext ()
SimplePcg32 & sharedRng ()
void writeToDebugConsole (std::string const &text)
bool isDebuggerActive ()
void formatReconstructedExpression (std::ostream &os, std::string const &lhs, StringRef op, std::string const &rhs)
void throw_exception (std::exception const &e)
void throw_logic_error (std::string const &msg)
void throw_domain_error (std::string const &msg)
void throw_runtime_error (std::string const &msg)
auto makeStream (std::string const &filename) -> Detail::unique_ptr< IStream >
auto operator<< (std::ostream &os, LazyExpression const &lazyExpr) ->std::ostream &
bool list (IEventListener &reporter, Config const &config)
Optional< unsigned int > parseUInt (std::string const &input, int base)
bool isnan (float f)
bool isnan (double d)
bool operator== (SimplePcg32 const &lhs, SimplePcg32 const &rhs)
bool operator!= (SimplePcg32 const &lhs, SimplePcg32 const &rhs)
std::uint32_t generateRandomSeed (GenerateFrom from)
bool operator== (ReporterSpec const &lhs, ReporterSpec const &rhs)
Optional< ReporterSpec > parseReporterSpec (StringRef reporterSpec)
bool isOk (ResultWas::OfType resultType)
bool isJustInfo (int flags)
ResultDisposition::Flags operator| (ResultDisposition::Flags lhs, ResultDisposition::Flags rhs)
bool shouldContinueOnFailure (int flags)
bool shouldSuppressFailure (int flags)
IResultCapture & getResultCapture ()
void seedRng (IConfig const &config)
unsigned int rngSeed ()
void addSingleton (ISingleton *singleton)
void cleanupSingletons ()
std::ostream & operator<< (std::ostream &os, SourceLineInfo const &info)
bool startsWith (std::string const &s, std::string const &prefix)
bool startsWith (StringRef s, char prefix)
bool endsWith (std::string const &s, std::string const &suffix)
bool endsWith (std::string const &s, char suffix)
bool contains (std::string const &s, std::string const &infix)
void toLowerInPlace (std::string &s)
std::string toLower (std::string const &s)
char toLower (char c)
std::string trim (std::string const &str)
Returns a new string without whitespace at the start/end.
StringRef trim (StringRef ref)
Returns a substring of the original ref without whitespace. Beware lifetimes!
bool replaceInPlace (std::string &str, std::string const &replaceThis, std::string const &withThis)
std::vector< StringRef > splitStringRef (StringRef str, char delimiter)
std::ostream & operator<< (std::ostream &os, pluralise const &pluraliser)
auto operator<< (std::ostream &os, StringRef str) -> std::ostream &
std::string operator+ (StringRef lhs, StringRef rhs)
auto operator+= (std::string &lhs, StringRef rhs) -> std::string &
std::vector< TestCaseHandle > sortTests (IConfig const &config, std::vector< TestCaseHandle > const &unsortedTestCases)
bool isThrowSafe (TestCaseHandle const &testCase, IConfig const &config)
std::vector< TestCaseHandle > filterTests (std::vector< TestCaseHandle > const &testCases, TestSpec const &testSpec, IConfig const &config)
std::vector< TestCaseHandle > const & getAllTestCasesSorted (IConfig const &config)
void throw_test_failure_exception ()
void throw_test_skip_exception ()
Detail::unique_ptr< ITestInvoker > makeTestInvoker (void(*testAsFunction)())
bool uncaught_exceptions ()
XmlFormatting operator| (XmlFormatting lhs, XmlFormatting rhs)
XmlFormatting operator& (XmlFormatting lhs, XmlFormatting rhs)
std::ostream & operator<< (std::ostream &os, XmlEncode const &xmlEncode)
void handleExceptionMatchExpr (AssertionHandler &handler, StringMatcher const &matcher)
std::string getFormattedDuration (double duration)
bool shouldShowDuration (IConfig const &config, double duration)
Should the reporter show duration of test given current configuration?
std::string serializeFilters (std::vector< std::string > const &filters)
std::ostream & operator<< (std::ostream &out, lineOfChars value)
void defaultListReporters (std::ostream &out, std::vector< ReporterDescription > const &descriptions, Verbosity verbosity)
void defaultListListeners (std::ostream &out, std::vector< ListenerDescription > const &descriptions)
void defaultListTags (std::ostream &out, std::vector< TagInfo > const &tags, bool isFiltered)
void defaultListTests (std::ostream &out, ColourImpl *streamColour, std::vector< TestCaseHandle > const &tests, bool isFiltered, Verbosity verbosity)
void printTestRunTotals (std::ostream &stream, ColourImpl &streamColour, Totals const &totals)
Context const & getCurrentContext ()
constexpr auto operator""_sr (char const *rawChars, std::size_t size) noexcept -> StringRef
bool isFalseTest (int flags)
template<typename Range>
std::string rangeToString (Range const &range)
template<typename Allocator>
std::string rangeToString (std::vector< bool, Allocator > const &v)
template<typename C>
Detail::unique_ptr< ITestInvoker > makeTestInvoker (void(C::*testAsMethod)())
template<typename FP>
uint64_t ulpDistance (FP lhs, FP rhs)
template<typename Container>
Container createShard (Container const &container, std::size_t const shardCount, std::size_t const shardIndex)
template<typename T>
std::string to_string (T const &t)
template<typename ArgT, typename MatcherT>
auto makeMatchExpr (ArgT &&arg, MatcherT const &matcher) -> MatchExpr< ArgT, MatcherT >
template<typename Ex>
void throw_exception (Ex const &e)
TestSpec parseTestSpec (std::string const &arg)
Variables
int StringMaker< float >::precision = 5
int StringMaker< double >::precision = 10
Typedef Documentation
exceptionTranslateFunction
using Catch::exceptionTranslateFunction = std::string(*)()
Definition at line 7242 of file catch_amalgamated.hpp.
ExceptionTranslators
using Catch::ExceptionTranslators = std::vector<Detail::unique_ptr<IExceptionTranslator const>>
Definition at line 7245 of file catch_amalgamated.hpp.
FunctionReturnType
template<typename Func, typename... U> using Catch::FunctionReturnType = std::remove_reference_t<std::remove_cv_t<std::result_of_t<Func(U...)>>>
Definition at line 1528 of file catch_amalgamated.hpp.
IEventListenerPtr
typedef Detail::unique_ptr< IEventListener > Catch::IEventListenerPtr = Detail::unique_ptr<IEventListener>
Definition at line 8470 of file catch_amalgamated.hpp.
IReporterFactoryPtr
typedef Detail::unique_ptr< IReporterFactory > Catch::IReporterFactoryPtr = Detail::unique_ptr<IReporterFactory>
Definition at line 1200 of file catch_amalgamated.hpp.
RegistryHubSingleton
typedef Singleton< RegistryHub, IRegistryHub, IMutableRegistryHub > Catch::RegistryHubSingleton = Singleton<RegistryHub, IRegistryHub, IMutableRegistryHub>
Definition at line 998 of file catch_amalgamated.cpp.
StringMatcher
typedef Matchers::MatcherBase< std::string > Catch::StringMatcher = Matchers::MatcherBase<std::string>
Definition at line 10644 of file catch_amalgamated.hpp.
Enumeration Type Documentation
CaseSensitive [1/2]
enum class Catch::CaseSensitive strong
Enumerator
Yes
No
Yes
No
Definition at line 3535 of file catch_amalgamated.hpp.
CaseSensitive [2/2]
enum class Catch::CaseSensitive strong
Enumerator
Yes
No
Yes
No
Definition at line 13 of file catch_case_sensitive.hpp.
ColourMode [1/2]
enum class Catch::ColourMode : std::uint8_t strong
Enumerator
PlatformDefault
Let Catch2 pick implementation based on platform detection.
ANSI
Use ANSI colour code escapes.
Win32
Use Win32 console colour API.
None
Don't use any colour.
PlatformDefault
Let Catch2 pick implementation based on platform detection.
ANSI
Use ANSI colour code escapes.
Win32
Use Win32 console colour API.
None
Don't use any colour.
Definition at line 1119 of file catch_amalgamated.hpp.
ColourMode [2/2]
enum class Catch::ColourMode : std::uint8_t strong
Enumerator
PlatformDefault
Let Catch2 pick implementation based on platform detection.
ANSI
Use ANSI colour code escapes.
Win32
Use Win32 console colour API.
None
Don't use any colour.
PlatformDefault
Let Catch2 pick implementation based on platform detection.
ANSI
Use ANSI colour code escapes.
Win32
Use Win32 console colour API.
None
Don't use any colour.
Definition at line 45 of file catch_interfaces_config.hpp.
GenerateFrom [1/2]
enum class Catch::GenerateFrom strong
Enumerator
Time
RandomDevice
Default
Currently equivalent to RandomDevice, but can change at any point.
Time
RandomDevice
Default
Currently equivalent to RandomDevice, but can change at any point.
Definition at line 3789 of file catch_amalgamated.hpp.
GenerateFrom [2/2]
enum class Catch::GenerateFrom strong
Enumerator
Time
RandomDevice
Default
Currently equivalent to RandomDevice, but can change at any point.
Time
RandomDevice
Default
Currently equivalent to RandomDevice, but can change at any point.
Definition at line 15 of file catch_random_seed_generation.hpp.
ShowDurations [1/2]
enum class Catch::ShowDurations strong
Enumerator
DefaultForReporter
Always
Never
DefaultForReporter
Always
Never
Definition at line 1109 of file catch_amalgamated.hpp.
ShowDurations [2/2]
enum class Catch::ShowDurations strong
Enumerator
DefaultForReporter
Always
Never
DefaultForReporter
Always
Never
Definition at line 35 of file catch_interfaces_config.hpp.
TestCaseProperties [1/2]
enum class Catch::TestCaseProperties : uint8_t strong
Enumerator
None
IsHidden
ShouldFail
MayFail
Throws
NonPortable
Benchmark
None
IsHidden
ShouldFail
MayFail
Throws
NonPortable
Benchmark
Definition at line 7143 of file catch_amalgamated.hpp.
TestCaseProperties [2/2]
enum class Catch::TestCaseProperties : uint8_t strong
Enumerator
None
IsHidden
ShouldFail
MayFail
Throws
NonPortable
Benchmark
None
IsHidden
ShouldFail
MayFail
Throws
NonPortable
Benchmark
Definition at line 48 of file catch_test_case_info.hpp.
TestRunOrder [1/2]
enum class Catch::TestRunOrder strong
Enumerator
Declared
LexicographicallySorted
Randomized
Declared
LexicographicallySorted
Randomized
Definition at line 1114 of file catch_amalgamated.hpp.
TestRunOrder [2/2]
enum class Catch::TestRunOrder strong
Enumerator
Declared
LexicographicallySorted
Randomized
Declared
LexicographicallySorted
Randomized
Definition at line 40 of file catch_interfaces_config.hpp.
Verbosity [1/2]
enum class Catch::Verbosity strong
Enumerator
Quiet
Normal
High
Quiet
Normal
High
Definition at line 1095 of file catch_amalgamated.hpp.
Verbosity [2/2]
enum class Catch::Verbosity strong
Enumerator
Quiet
Normal
High
Quiet
Normal
High
Definition at line 21 of file catch_interfaces_config.hpp.
XmlFormatting [1/2]
enum class Catch::XmlFormatting strong
Enumerator
None
Indent
Newline
None
Indent
Newline
Definition at line 10454 of file catch_amalgamated.hpp.
XmlFormatting [2/2]
enum class Catch::XmlFormatting strong
Enumerator
None
Indent
Newline
None
Indent
Newline
Definition at line 18 of file catch_xmlwriter.hpp.
Function Documentation
addSingleton()
void Catch::addSingleton (ISingleton * singleton)
Definition at line 5824 of file catch_amalgamated.cpp.
cerr()
std::ostream & Catch::cerr ()
Definition at line 55 of file 231-Cfg-OutputStreams.cpp.
References clog().
Referenced by Catch::RedirectedStdErr::RedirectedStdErr(), Catch::MultiReporter::testCasePartialEnded(), and throw_exception().
cleanUp()
void Catch::cleanUp ()
Definition at line 1006 of file catch_amalgamated.cpp.
References cleanUpContext(), and cleanupSingletons().
Referenced by Catch::IMutableRegistryHub::getMutableEnumValuesRegistry(), Catch::LeakDetector::~LeakDetector(), and Catch::Session::~Session().
cleanUpContext()
void Catch::cleanUpContext ()
Definition at line 3457 of file catch_amalgamated.cpp.
Referenced by cleanUp().
cleanupSingletons()
void Catch::cleanupSingletons ()
Definition at line 5827 of file catch_amalgamated.cpp.
Referenced by cleanUp().
clog()
std::ostream & Catch::clog ()
Definition at line 51 of file 231-Cfg-OutputStreams.cpp.
Referenced by cerr(), and Catch::RedirectedStdErr::RedirectedStdErr().
contains()
bool Catch::contains (std::string const & s, std::string const & infix)
Definition at line 5923 of file catch_amalgamated.cpp.
Referenced by Catch::Matchers::StringContainsMatcher::match(), and Catch::WildcardPattern::matches().
cout()
std::ostream & Catch::cout ()
Definition at line 47 of file 231-Cfg-OutputStreams.cpp.
Referenced by Catch::Session::libIdentify(), Catch::RedirectedStdOut::RedirectedStdOut(), Catch::Session::run(), Catch::Session::showHelp(), Catch::MultiReporter::testCasePartialEnded(), and writeToDebugConsole().
createShard()
template<typename Container> Container Catch::createShard (Container const & container, std::size_t const shardCount, std::size_t const shardIndex)
Definition at line 9913 of file catch_amalgamated.hpp.
References createShard().
Referenced by createShard(), filterTests(), and TEST_CASE().
defaultListListeners()
void Catch::defaultListListeners (std::ostream & out, std::vector< ListenerDescription > const & descriptions)
Lists listeners descriptions to the provided stream in user-friendly format
Definition at line 9214 of file catch_amalgamated.cpp.
References CATCH_CONFIG_CONSOLE_WIDTH, Catch::TextFlow::Column::indent(), Catch::TextFlow::Column::initialIndent(), and Catch::TextFlow::Column::width().
Referenced by Catch::ReporterBase::listListeners(), and TEST_CASE().
defaultListReporters()
void Catch::defaultListReporters (std::ostream & out, std::vector< ReporterDescription > const & descriptions, Verbosity verbosity)
Lists reporter descriptions to the provided stream in user-friendly format
Used as the default listing implementation by the first party reporter bases. The output should be backwards compatible with the output of Catch2 v2 binaries.
Definition at line 9181 of file catch_amalgamated.cpp.
References CATCH_CONFIG_CONSOLE_WIDTH, Catch::TextFlow::Column::indent(), Catch::TextFlow::Column::initialIndent(), Quiet, and Catch::TextFlow::Column::width().
Referenced by Catch::ReporterBase::listReporters(), and TEST_CASE().
defaultListTags()
void Catch::defaultListTags (std::ostream & out, std::vector< TagInfo > const & tags, bool isFiltered)
Lists tag information to the provided stream in user-friendly format
Used as the default listing implementation by the first party reporter bases. The output should be backwards compatible with the output of Catch2 v2 binaries.
Definition at line 9246 of file catch_amalgamated.cpp.
References CATCH_CONFIG_CONSOLE_WIDTH, Catch::TextFlow::Column::indent(), Catch::TextFlow::Column::initialIndent(), Catch::ReusableStringStream::str(), and Catch::TextFlow::Column::width().
Referenced by Catch::ReporterBase::listTags(), and TEST_CASE().
defaultListTests()
void Catch::defaultListTests (std::ostream & out, ColourImpl * streamColour, std::vector< TestCaseHandle > const & tests, bool isFiltered, Verbosity verbosity)
Lists test case information to the provided stream in user-friendly format
Used as the default listing implementation by the first party reporter bases. The output is backwards compatible with the output of Catch2 v2 binaries, and also supports the format specific to the old --list-test-names-only option, for people who used it in integrations.
Definition at line 9268 of file catch_amalgamated.cpp.
References Catch::ColourImpl::ColourGuard::engage(), Catch::ColourImpl::guardColour(), High, Catch::TextFlow::Column::indent(), Catch::Colour::None, Quiet, Catch::Colour::SecondaryText, and Catch::Detail::stringify().
Referenced by Catch::ReporterBase::listTests(), and TEST_CASE().
endsWith() [1/2]
bool Catch::endsWith (std::string const & s, char suffix)
Definition at line 5920 of file catch_amalgamated.cpp.
endsWith() [2/2]
bool Catch::endsWith (std::string const & s, std::string const & suffix)
Definition at line 5917 of file catch_amalgamated.cpp.
References Catch::StringRef::size().
Referenced by Catch::TagAliasRegistry::add(), Catch::Matchers::EndsWithMatcher::match(), Catch::WildcardPattern::matches(), and Catch::WildcardPattern::WildcardPattern().
filterTests()
std::vector< TestCaseHandle > Catch::filterTests (std::vector< TestCaseHandle > const & testCases, TestSpec const & testSpec, IConfig const & config)
Definition at line 6231 of file catch_amalgamated.cpp.
References createShard(), filterTests(), Catch::TestSpec::hasFilters(), TestCaseInfo::isHidden(), Catch::IConfig::shardCount(), and Catch::IConfig::shardIndex().
Referenced by filterTests().
formatReconstructedExpression()
void Catch::formatReconstructedExpression (std::ostream & os, std::string const & lhs, StringRef op, std::string const & rhs)
Definition at line 3636 of file catch_amalgamated.cpp.
generateRandomSeed()
std::uint32_t Catch::generateRandomSeed (GenerateFrom from)
Definition at line 4755 of file catch_amalgamated.cpp.
References CATCH_ERROR, Default, RandomDevice, and Time.
Referenced by makeCommandLineParser(), TEST_CASE(), and TEST_CASE().
getAllTestCasesSorted()
std::vector< TestCaseHandle > const & Catch::getAllTestCasesSorted (IConfig const & config)
Definition at line 6242 of file catch_amalgamated.cpp.
References getAllTestCasesSorted(), and getRegistryHub().
Referenced by getAllTestCasesSorted().
getCurrentContext()
Context const & Catch::getCurrentContext () inline
Definition at line 560 of file catch_amalgamated.hpp.
Referenced by Catch::AssertionHandler::allowThrows(), Catch::Detail::convertIntoString(), getResultCapture(), getSeed(), Catch::Benchmark::Benchmark::operator=(), rngSeed(), and Catch::Benchmark::Benchmark::run().
getCurrentMutableContext()
Context & Catch::getCurrentMutableContext ()
Definition at line 3465 of file catch_amalgamated.cpp.
Referenced by Catch::Session::applyCommandLine(), Catch::RunContext::RunContext(), and Catch::Session::Session().
getFormattedDuration()
std::string Catch::getFormattedDuration (double duration)
Definition at line 9120 of file catch_amalgamated.cpp.
Referenced by Catch::CompactReporter::sectionEnded(), and Catch::ConsoleReporter::sectionEnded().
getMutableRegistryHub()
IMutableRegistryHub & Catch::getMutableRegistryHub ()
Definition at line 1003 of file catch_amalgamated.cpp.
References Catch::Singleton< RegistryHub, IRegistryHub, IMutableRegistryHub >::getMutable().
Referenced by Catch::AutoReg::AutoReg(), Catch::IMutableRegistryHub::getMutableEnumValuesRegistry(), Catch::Detail::registerListenerImpl(), Catch::Detail::registerReporterImpl(), Catch::Detail::registerTranslatorImpl(), Catch::RegistrarForTagAliases::RegistrarForTagAliases(), and Catch::Session::Session().
getRegistryHub()
IRegistryHub const & Catch::getRegistryHub ()
Definition at line 1000 of file catch_amalgamated.cpp.
References Catch::Singleton< RegistryHub, IRegistryHub, IMutableRegistryHub >::get().
Referenced by Catch::ITagAliasRegistry::get(), getAllTestCasesSorted(), Catch::IMutableRegistryHub::getMutableEnumValuesRegistry(), makeCommandLineParser(), Catch::Session::Session(), TEST_CASE(), and translateActiveException().
getResultCapture()
IResultCapture & Catch::getResultCapture ()
Definition at line 5739 of file catch_amalgamated.cpp.
References CATCH_INTERNAL_ERROR, getCurrentContext(), and getResultCapture().
Referenced by Catch::Generators::acquireGeneratorTracker(), Catch::AssertionHandler::AssertionHandler(), Catch::Capturer::Capturer(), Catch::Generators::createGeneratorTracker(), getResultCapture(), Catch::Benchmark::Benchmark::run(), Catch::ScopedMessage::ScopedMessage(), Catch::Section::Section(), Catch::ScopedMessage::~ScopedMessage(), and Catch::Section::~Section().
getSeed()
std::uint32_t Catch::getSeed ()
Returns Catch2's current RNG seed.
Definition at line 819 of file catch_amalgamated.cpp.
References Catch::Context::getConfig(), getCurrentContext(), and Catch::IConfig::rngSeed().
Referenced by Catch::CompactReporter::testRunStarting(), and Catch::ConsoleReporter::testRunStarting().
handleExceptionMatchExpr() [1/2]
void Catch::handleExceptionMatchExpr (AssertionHandler & handler, std::string const & str)
Definition at line 2413 of file catch_amalgamated.cpp.
References Catch::Matchers::Equals(), and handleExceptionMatchExpr().
Referenced by Catch::AssertionHandler::allowThrows(), and handleExceptionMatchExpr().
handleExceptionMatchExpr() [2/2]
void Catch::handleExceptionMatchExpr (AssertionHandler & handler, StringMatcher const & matcher)
Definition at line 7946 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::AssertionHandler::handleExpr(), and translateActiveException().
isColourImplAvailable()
bool Catch::isColourImplAvailable (ColourMode colourSelection)
Checks if specific colour impl has been compiled into the binary.
Definition at line 3429 of file catch_amalgamated.cpp.
References ANSI, None, PlatformDefault, and Win32.
Referenced by makeCommandLineParser().
isDebuggerActive()
bool Catch::isDebuggerActive ()
Definition at line 3625 of file catch_amalgamated.cpp.
isFalseTest()
bool Catch::isFalseTest (int flags) inline
Definition at line 830 of file catch_amalgamated.hpp.
References Catch::ResultDisposition::FalseTest.
Referenced by Catch::AssertionResult::getExpression(), and Catch::RunContext::handleExpr().
isJustInfo()
bool Catch::isJustInfo (int flags)
Definition at line 5015 of file catch_amalgamated.cpp.
References Catch::ResultWas::Info.
isnan() [1/2]
bool Catch::isnan (double d)
Definition at line 4667 of file catch_amalgamated.cpp.
isnan() [2/2]
bool Catch::isnan (float f)
Definition at line 4664 of file catch_amalgamated.cpp.
Referenced by ulpDistance().
isOk()
bool Catch::isOk (ResultWas::OfType resultType)
Definition at line 5012 of file catch_amalgamated.cpp.
References Catch::ResultWas::FailureBit.
Referenced by Catch::RunContext::handleMessage(), Catch::RunContext::handleNonExpr(), Catch::AssertionResult::isOk(), and Catch::AssertionResult::succeeded().
isThrowSafe()
bool Catch::isThrowSafe (TestCaseHandle const & testCase, IConfig const & config)
Definition at line 6227 of file catch_amalgamated.cpp.
References Catch::IConfig::allowThrows(), Catch::TestCaseHandle::getTestCaseInfo(), isThrowSafe(), and Catch::TestCaseInfo::throws().
Referenced by isThrowSafe(), and Catch::TestSpec::matchesByFilter().
libraryVersion()
Version const & Catch::libraryVersion ()
Definition at line 2135 of file catch_amalgamated.cpp.
Referenced by Catch::Session::libIdentify(), Catch::Session::showHelp(), and Catch::XmlReporter::testRunStarting().
list()
bool Catch::list (IEventListener & reporter, Config const & config)
Definition at line 4403 of file catch_amalgamated.cpp.
References Catch::Config::listListeners(), Catch::Config::listReporters(), Catch::Config::listTags(), and Catch::Config::listTests().
Referenced by Catch::Detail::empty().
makeColourImpl()
Detail::unique_ptr< ColourImpl > Catch::makeColourImpl (ColourMode implSelection, IStream * stream)
Provides ColourImpl based on global config and target compilation platform.
Definition at line 3400 of file catch_amalgamated.cpp.
References ANSI, CATCH_ERROR, Catch::Detail::make_unique(), None, PlatformDefault, and Win32.
Referenced by Catch::Session::applyCommandLine(), Catch::ReporterBase::ReporterBase(), Catch::Session::Session(), and TEST_CASE().
makeCommandLineParser()
Clara::Parser Catch::makeCommandLineParser (ConfigData & config)
Definition at line 2893 of file catch_amalgamated.cpp.
References Catch::ConfigData::abortAfter, Catch::ConfigData::allowZeroTests, Always, Catch::WaitForKeypress::BeforeExit, Catch::WaitForKeypress::BeforeStart, Catch::WaitForKeypress::BeforeStartAndExit, Catch::ConfigData::benchmarkConfidenceInterval, Catch::ConfigData::benchmarkNoAnalysis, Catch::ConfigData::benchmarkResamples, Catch::ConfigData::benchmarkSamples, Catch::ConfigData::benchmarkWarmupTime, CATCH_MOVE, Declared, Catch::ConfigData::defaultColourMode, Catch::ConfigData::defaultOutputFilename, f(), Catch::ConfigData::filenamesAsTags, generateRandomSeed(), Catch::ReporterRegistry::getFactories(), getRegistryHub(), Catch::IRegistryHub::getReporterRegistry(), High, isColourImplAvailable(), LexicographicallySorted, Catch::ConfigData::libIdentify, Catch::ConfigData::listListeners, Catch::ConfigData::listReporters, Catch::ConfigData::listTags, Catch::ConfigData::listTests, Catch::ConfigData::minDuration, Catch::ConfigData::name, Never, Catch::WaitForKeypress::Never, Catch::WarnAbout::NoAssertions, Normal, Catch::ConfigData::noThrow, parseReporterSpec(), parseUInt(), Catch::ConfigData::processName, Quiet, RandomDevice, Randomized, Catch::ConfigData::reporterSpecifications, Catch::ConfigData::rngSeed, Catch::ConfigData::runOrder, Catch::ConfigData::sectionsToRun, Catch::ConfigData::shardCount, Catch::ConfigData::shardIndex, Catch::ConfigData::shouldDebugBreak, Catch::ConfigData::showDurations, Catch::ConfigData::showHelp, Catch::ConfigData::showInvisibles, Catch::ConfigData::showSuccessfulTests, Catch::ConfigData::skipBenchmarks, startsWith(), Catch::Detail::stringToColourMode(), Catch::ConfigData::testsOrTags, Time, toLower(), trim(), Catch::WarnAbout::UnmatchedTestSpec, Catch::ConfigData::verbosity, Catch::ConfigData::waitForKeypress, and Catch::ConfigData::warnings.
Referenced by Catch::Session::Session(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
makeMatchExpr()
template<typename ArgT, typename MatcherT> auto Catch::makeMatchExpr (ArgT && arg, MatcherT const & matcher)->MatchExpr< ArgT, MatcherT >
Definition at line 10649 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and makeMatchExpr().
Referenced by makeMatchExpr().
makeStream()
auto Catch::makeStream (std::string const & filename) ->Detail::unique_ptr< IStream >
Creates a stream wrapper that writes to specific file.
Also recognizes 4 special filenames
- for stdout
stdout for stdout
stderr for stderr
debug for platform specific debugging output
Exceptions
if passed an unrecognized %-prefixed stream
Definition at line 4248 of file catch_amalgamated.cpp.
References CATCH_ERROR, and Catch::Detail::make_unique().
Referenced by Catch::Session::applyCommandLine(), Catch::Session::Session(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
makeTestCaseInfo()
Detail::unique_ptr< TestCaseInfo > Catch::makeTestCaseInfo (StringRef _className, NameAndTags const & nameAndTags, SourceLineInfo const & _lineInfo)
Definition at line 1477 of file catch_amalgamated.cpp.
References Catch::Detail::make_unique().
Referenced by Catch::AutoReg::AutoReg().
makeTestInvoker() [1/2]
Detail::unique_ptr< ITestInvoker > Catch::makeTestInvoker (void(* testAsFunction)())
Definition at line 6576 of file catch_amalgamated.cpp.
References Catch::Detail::make_unique().
Referenced by makeTestInvoker().
makeTestInvoker() [2/2]
template<typename C> Detail::unique_ptr< ITestInvoker > Catch::makeTestInvoker (void(C::* testAsMethod)())
Definition at line 6108 of file catch_amalgamated.hpp.
References Catch::Detail::make_unique(), and makeTestInvoker().
operator!=()
bool Catch::operator!= (SimplePcg32 const & lhs, SimplePcg32 const & rhs)
Definition at line 4741 of file catch_amalgamated.cpp.
operator""_sr()
auto Catch::operator""_sr (char const * rawChars, std::size_t size)->StringRef constexpr noexcept
Definition at line 774 of file catch_amalgamated.hpp.
operator&()
XmlFormatting Catch::operator& (XmlFormatting lhs, XmlFormatting rhs)
Definition at line 7196 of file catch_amalgamated.cpp.
operator+()
std::string Catch::operator+ (StringRef lhs, StringRef rhs)
Definition at line 6043 of file catch_amalgamated.cpp.
operator+=()
auto Catch::operator+= (std::string & lhs, StringRef rhs)->std::string &
Definition at line 6051 of file catch_amalgamated.cpp.
operator<() [1/2]
bool Catch::operator< (Tag const & lhs, Tag const & rhs)
Definition at line 1467 of file catch_amalgamated.cpp.
operator<() [2/2]
bool Catch::operator< (TestCaseInfo const & lhs, TestCaseInfo const & rhs)
Definition at line 1606 of file catch_amalgamated.cpp.
operator<<() [1/7]
auto Catch::operator<< (std::ostream & os, LazyExpression const & lazyExpr)->std::ostream &
Definition at line 4273 of file catch_amalgamated.cpp.
operator<<() [2/7]
std::ostream & Catch::operator<< (std::ostream & os, pluralise const & pluraliser)
Definition at line 5989 of file catch_amalgamated.cpp.
operator<<() [3/7]
std::ostream & Catch::operator<< (std::ostream & os, SourceLineInfo const & info)
Definition at line 5853 of file catch_amalgamated.cpp.
operator<<() [4/7]
auto Catch::operator<< (std::ostream & os, StringRef str)->std::ostream &
Definition at line 6039 of file catch_amalgamated.cpp.
operator<<() [5/7]
std::ostream & Catch::operator<< (std::ostream & os, Version const & version)
Definition at line 2123 of file catch_amalgamated.cpp.
operator<<() [6/7]
std::ostream & Catch::operator<< (std::ostream & os, XmlEncode const & xmlEncode)
Definition at line 7303 of file catch_amalgamated.cpp.
operator<<() [7/7]
std::ostream & Catch::operator<< (std::ostream & out, lineOfChars value)
Definition at line 9173 of file catch_amalgamated.cpp.
operator==() [1/4]
bool Catch::operator== (ProcessedReporterSpec const & lhs, ProcessedReporterSpec const & rhs)
Definition at line 652 of file catch_amalgamated.cpp.
operator==() [2/4]
bool Catch::operator== (ReporterSpec const & lhs, ReporterSpec const & rhs)
Definition at line 4932 of file catch_amalgamated.cpp.
operator==() [3/4]
bool Catch::operator== (SimplePcg32 const & lhs, SimplePcg32 const & rhs)
Definition at line 4737 of file catch_amalgamated.cpp.
operator==() [4/4]
bool Catch::operator== (Tag const & lhs, Tag const & rhs)
Definition at line 1471 of file catch_amalgamated.cpp.
operator|() [1/2]
ResultDisposition::Flags Catch::operator| (ResultDisposition::Flags lhs, ResultDisposition::Flags rhs)
Definition at line 5019 of file catch_amalgamated.cpp.
operator|() [2/2]
XmlFormatting Catch::operator| (XmlFormatting lhs, XmlFormatting rhs)
Definition at line 7189 of file catch_amalgamated.cpp.
parseReporterSpec()
Optional< ReporterSpec > Catch::parseReporterSpec (StringRef reporterSpec)
Parses provided reporter spec string into
Returns empty optional on errors, e.g.
field that is not first and not a key+value pair
duplicated keys in kv pair
unknown catch reporter option
empty key/value in an custom kv pair
...
Definition at line 4939 of file catch_amalgamated.cpp.
References CATCH_MOVE, Catch::Detail::splitReporterSpec(), and Catch::Detail::stringToColourMode().
Referenced by makeCommandLineParser(), and TEST_CASE().
parseTestSpec()
TestSpec Catch::parseTestSpec (std::string const & arg)
Definition at line 16 of file parse_test_spec.cpp.
References Catch::ITagAliasRegistry::get(), Catch::TestSpecParser::parse(), and Catch::TestSpecParser::testSpec().
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
parseUInt()
Optional< unsigned int > Catch::parseUInt (std::string const & input, int base = 10)
Parses unsigned int from the input, using provided base
Effectively a wrapper around std::stoul but with better error checking e.g. "-1" is rejected, instead of being parsed as UINT_MAX.
Definition at line 4620 of file catch_amalgamated.cpp.
References CATCH_CATCH_ANON, CATCH_TRY, and trim().
Referenced by makeCommandLineParser(), and TEST_CASE().
printTestRunTotals()
void Catch::printTestRunTotals (std::ostream & stream, ColourImpl & streamColour, Totals const & totals)
Prints test run totals to the provided stream in user-friendly format
Used by the console and compact reporters.
Definition at line 9368 of file catch_amalgamated.cpp.
References Catch::Counts::allPassed(), Catch::Totals::assertions, Catch::Counts::failed, Catch::Counts::failedButOk, Catch::ColourImpl::guardColour(), Catch::Colour::None, Catch::Counts::passed, Catch::Colour::ResultError, Catch::Colour::ResultExpectedFailure, Catch::Colour::ResultSuccess, Catch::Colour::Skip, Catch::Counts::skipped, Catch::Colour::Success, Catch::Totals::testCases, Catch::Counts::total(), and Catch::Colour::Warning.
Referenced by Catch::CompactReporter::testRunEnded(), and Catch::ConsoleReporter::testRunEnded().
rangeToString() [1/2]
template<typename Range> std::string Catch::rangeToString (Range const & range)
Definition at line 3084 of file catch_amalgamated.hpp.
References rangeToString().
Referenced by Catch::StringMaker< R, std::enable_if_t< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value > >::convert(), Catch::StringMaker< T[SZ]>::convert(), rangeToString(), and rangeToString().
rangeToString() [2/2]
template<typename Allocator> std::string Catch::rangeToString (std::vector< bool, Allocator > const & v)
Definition at line 3090 of file catch_amalgamated.hpp.
References rangeToString(), Catch::ReusableStringStream::str(), and Catch::Detail::stringify().
replaceInPlace()
bool Catch::replaceInPlace (std::string & str, std::string const & replaceThis, std::string const & withThis)
Definition at line 5960 of file catch_amalgamated.cpp.
Referenced by TEST_CASE().
rngSeed()
unsigned int Catch::rngSeed ()
Definition at line 5750 of file catch_amalgamated.cpp.
References Catch::Context::getConfig(), getCurrentContext(), and Catch::IConfig::rngSeed().
seedRng()
void Catch::seedRng (IConfig const & config)
Definition at line 5746 of file catch_amalgamated.cpp.
References Catch::IConfig::rngSeed(), Catch::SimplePcg32::seed(), and sharedRng().
Referenced by Catch::RunContext::runTest(), and sortTests().
serializeFilters()
std::string Catch::serializeFilters (std::vector< std::string > const & filters)
Definition at line 9151 of file catch_amalgamated.cpp.
sharedRng()
SimplePcg32 & Catch::sharedRng ()
Definition at line 3477 of file catch_amalgamated.cpp.
Referenced by Catch::Generators::Detail::getSeed(), and seedRng().
shouldContinueOnFailure()
bool Catch::shouldContinueOnFailure (int flags)
Definition at line 5023 of file catch_amalgamated.cpp.
References Catch::ResultDisposition::ContinueOnFailure.
shouldShowDuration()
bool Catch::shouldShowDuration (IConfig const & config, double duration)
Should the reporter show duration of test given current configuration?
Definition at line 9140 of file catch_amalgamated.cpp.
References Always, Catch::IConfig::minDuration(), Never, and Catch::IConfig::showDurations().
Referenced by Catch::CompactReporter::sectionEnded(), and Catch::ConsoleReporter::sectionEnded().
shouldSuppressFailure()
bool Catch::shouldSuppressFailure (int flags)
Definition at line 5024 of file catch_amalgamated.cpp.
References Catch::ResultDisposition::SuppressFail.
Referenced by Catch::AssertionResult::isOk().
sortTests()
std::vector< TestCaseHandle > Catch::sortTests (IConfig const & config, std::vector< TestCaseHandle > const & unsortedTestCases)
Definition at line 6175 of file catch_amalgamated.cpp.
References Declared, LexicographicallySorted, Randomized, Catch::IConfig::rngSeed(), Catch::IConfig::runOrder(), and seedRng().
Referenced by Catch::TestRegistry::getAllTestsSorted().
splitStringRef()
std::vector< StringRef > Catch::splitStringRef (StringRef str, char delimiter)
Definition at line 5974 of file catch_amalgamated.cpp.
References Catch::StringRef::size(), and Catch::StringRef::substr().
Referenced by Catch::Detail::parseEnums(), and TEST_CASE().
startsWith() [1/2]
bool Catch::startsWith (std::string const & s, std::string const & prefix)
Definition at line 5911 of file catch_amalgamated.cpp.
Referenced by Catch::TagAliasRegistry::add(), makeCommandLineParser(), Catch::Matchers::StartsWithMatcher::match(), Catch::WildcardPattern::matches(), TEST_CASE(), and Catch::WildcardPattern::WildcardPattern().
startsWith() [2/2]
bool Catch::startsWith (StringRef s, char prefix)
Definition at line 5914 of file catch_amalgamated.cpp.
References Catch::StringRef::empty().
throw_domain_error()
void Catch::throw_domain_error (std::string const & msg)
Definition at line 3667 of file catch_amalgamated.cpp.
References throw_exception().
throw_exception() [1/2]
template<typename Ex> void Catch::throw_exception (Ex const & e)
Definition at line 21 of file catch_enforce.hpp.
throw_exception() [2/2]
void Catch::throw_exception (std::exception const & e)
Definition at line 3654 of file catch_amalgamated.cpp.
References cerr().
Referenced by throw_domain_error(), Catch::Generators::Detail::throw_generator_exception(), throw_logic_error(), Catch::Benchmark::Detail::throw_optimized_away_error(), and throw_runtime_error().
throw_logic_error()
void Catch::throw_logic_error (std::string const & msg)
Definition at line 3662 of file catch_amalgamated.cpp.
References throw_exception().
throw_runtime_error()
void Catch::throw_runtime_error (std::string const & msg)
Definition at line 3672 of file catch_amalgamated.cpp.
References throw_exception().
throw_test_failure_exception()
void Catch::throw_test_failure_exception ()
Outlines throwing of TestFailureException into a single TU
Also handles CATCH_CONFIG_DISABLE_EXCEPTIONS for callers.
Definition at line 6508 of file catch_amalgamated.cpp.
References CATCH_ERROR.
Referenced by Catch::AssertionHandler::complete().
throw_test_skip_exception()
void Catch::throw_test_skip_exception ()
Outlines throwing of TestSkipException into a single TU
Also handles CATCH_CONFIG_DISABLE_EXCEPTIONS for callers.
Definition at line 6516 of file catch_amalgamated.cpp.
References CATCH_ERROR.
Referenced by Catch::AssertionHandler::complete().
to_string()
template<typename T> std::string Catch::to_string (T const & t)
Definition at line 10422 of file catch_amalgamated.hpp.
References Catch::ReusableStringStream::str(), and to_string().
Referenced by to_string().
toLower() [1/2]
char Catch::toLower (char c)
Definition at line 5936 of file catch_amalgamated.cpp.
toLower() [2/2]
std::string Catch::toLower (std::string const & s)
Definition at line 5931 of file catch_amalgamated.cpp.
References toLowerInPlace().
Referenced by Catch::Matchers::CasedString::adjustString(), Catch::Clara::Detail::convertInto(), makeCommandLineParser(), and toLowerInPlace().
toLowerInPlace()
void Catch::toLowerInPlace (std::string & s)
Definition at line 5926 of file catch_amalgamated.cpp.
References toLower().
Referenced by toLower().
translateActiveException()
std::string Catch::translateActiveException ()
Definition at line 1010 of file catch_amalgamated.cpp.
References Catch::IRegistryHub::getExceptionTranslatorRegistry(), getRegistryHub(), and Catch::IExceptionTranslatorRegistry::translateActiveException().
Referenced by Catch::IMutableRegistryHub::getMutableEnumValuesRegistry(), handleExceptionMatchExpr(), Catch::AssertionHandler::handleUnexpectedInflightException(), and Catch::Benchmark::Benchmark::run().
trim() [1/2]
std::string Catch::trim (std::string const & str)
Returns a new string without whitespace at the start/end.
Definition at line 5940 of file catch_amalgamated.cpp.
Referenced by makeCommandLineParser(), Catch::Detail::parseEnums(), parseUInt(), Catch::XmlReporter::sectionStarting(), Catch::TestCaseTracking::SectionTracker::SectionTracker(), TEST_CASE(), Catch::XmlReporter::testCaseEnded(), Catch::XmlReporter::testCaseStarting(), and Catch::SonarQubeReporter::writeSection().
trim() [2/2]
StringRef Catch::trim (StringRef ref)
Returns a substring of the original ref without whitespace. Beware lifetimes!
Definition at line 5948 of file catch_amalgamated.cpp.
References Catch::StringRef::size(), and Catch::StringRef::substr().
ulpDistance()
template<typename FP> uint64_t Catch::ulpDistance (FP lhs, FP rhs)
Calculates the ULP distance between two floating point numbers
The ULP distance of two floating point numbers is the count of valid floating point numbers representable between them.
There are some exceptions between how this function counts the distance, and the interpretation of the standard as implemented. by e.g. nextafter. For this function it always holds that:
(x == y) => ulpDistance(x, y) == 0 (so ulpDistance(-0, 0) == 0)
ulpDistance(maxFinite, INF) == 1
ulpDistance(x, -x) == 2 * ulpDistance(x, 0)
Precondition
!isnan(lhs)
!isnan(rhs)
floating point numbers are represented in IEEE-754 format
Definition at line 9048 of file catch_amalgamated.hpp.
References Catch::Detail::convertToBits(), isnan(), and ulpDistance().
Referenced by TEMPLATE_TEST_CASE(), TEST_CASE(), and ulpDistance().
uncaught_exceptions()
bool Catch::uncaught_exceptions ()
Definition at line 7082 of file catch_amalgamated.cpp.
Referenced by Catch::Capturer::~Capturer(), Catch::ScopedMessage::~ScopedMessage(), and Catch::Section::~Section().
writeToDebugConsole()
void Catch::writeToDebugConsole (std::string const & text)
Definition at line 3510 of file catch_amalgamated.cpp.
References cout().
Variable Documentation
StringMaker< double >::precision
int Catch::StringMaker< double >::precision = 10
Definition at line 2025 of file catch_amalgamated.cpp.
StringMaker< float >::precision
int Catch::StringMaker< float >::precision = 5
Definition at line 2019 of file catch_amalgamated.cpp.