libthe-seed: Catch::Clara::Detail Namespace Reference
Catch::Clara::Detail Namespace Reference
Classes
struct fake_arg
struct is_unary_function
struct is_unary_function< F, Catch::Detail::void_t< decltype(std::declval< F >()(fake_arg())) > >
struct UnaryLambdaTraits
struct UnaryLambdaTraits< ReturnT(ClassT::*)(Args...) const >
struct UnaryLambdaTraits< ReturnT(ClassT::*)(ArgT) const >
struct Token
class TokenStream
class ResultBase
class ResultValueBase
class ResultValueBase< void >
class BasicResult
class ParseState
struct HelpColumns
struct BoundRef
struct BoundValueRefBase
struct BoundFlagRefBase
struct BoundValueRef
struct BoundValueRef< std::vector< T > >
struct BoundFlagRef
struct LambdaInvoker
struct LambdaInvoker< void >
struct BoundLambda
struct BoundManyLambda
struct BoundFlagLambda
class ParserBase
class ComposableParserImpl
class ParserRefImpl
Typedefs
using Result = BasicResult<void>
using ParserResult = BasicResult<ParseResultType>
using InternalParseResult = BasicResult<ParseState>
Enumerations
enum class TokenType { Option , Argument , Option , Argument }
enum class ResultType {
Ok , LogicError , RuntimeError , Ok ,
LogicError , RuntimeError
}
Denotes type of a parsing result.
enum class Optionality { Optional , Required , Optional , Required }
enum class TokenType { Option , Argument , Option , Argument }
enum class ResultType {
Ok , LogicError , RuntimeError , Ok ,
LogicError , RuntimeError
}
Denotes type of a parsing result.
enum class Optionality { Optional , Required , Optional , Required }
Functions
ParserResult convertInto (std::string const &source, std::string &target)
ParserResult convertInto (std::string const &source, bool &target)
template<typename T>
ParserResult convertInto (std::string const &source, T &target)
template<typename ArgType, typename L>
auto invokeLambda (L const &lambda, std::string const &arg) -> ParserResult
Typedef Documentation
InternalParseResult
typedef BasicResult< ParseState > Catch::Clara::Detail::InternalParseResult = BasicResult<ParseState>
Definition at line 4712 of file catch_amalgamated.hpp.
ParserResult
typedef BasicResult< ParseResultType > Catch::Clara::Detail::ParserResult = BasicResult<ParseResultType>
Definition at line 4711 of file catch_amalgamated.hpp.
Result
typedef BasicResult< void > Catch::Clara::Detail::Result = BasicResult<void>
Definition at line 4710 of file catch_amalgamated.hpp.
Enumeration Type Documentation
Optionality [1/2]
enum class Catch::Clara::Detail::Optionality strong
Enumerator
Optional
Required
Optional
Required
Definition at line 4869 of file catch_amalgamated.hpp.
Optionality [2/2]
enum class Catch::Clara::Detail::Optionality strong
Enumerator
Optional
Required
Optional
Required
Definition at line 441 of file catch_clara.hpp.
ResultType [1/2]
enum class Catch::Clara::Detail::ResultType strong
Denotes type of a parsing result.
Enumerator
Ok
No errors.
LogicError
Error in user-specified arguments for construction.
RuntimeError
Error in parsing inputs.
Ok
No errors.
LogicError
Error in user-specified arguments for construction.
RuntimeError
Error in parsing inputs.
Definition at line 4571 of file catch_amalgamated.hpp.
ResultType [2/2]
enum class Catch::Clara::Detail::ResultType strong
Denotes type of a parsing result.
Enumerator
Ok
No errors.
LogicError
Error in user-specified arguments for construction.
RuntimeError
Error in parsing inputs.
Ok
No errors.
LogicError
Error in user-specified arguments for construction.
RuntimeError
Error in parsing inputs.
Definition at line 143 of file catch_clara.hpp.
TokenType [1/2]
enum class Catch::Clara::Detail::TokenType strong
Enumerator
Option
Argument
Option
Argument
Definition at line 4529 of file catch_amalgamated.hpp.
TokenType [2/2]
enum class Catch::Clara::Detail::TokenType strong
Enumerator
Option
Argument
Option
Argument
Definition at line 101 of file catch_clara.hpp.
Function Documentation
convertInto() [1/3]
ParserResult Catch::Clara::Detail::convertInto (std::string const & source, bool & target)
Definition at line 2541 of file catch_amalgamated.cpp.
References Catch::Clara::Matched, Catch::Clara::Detail::BasicResult< ParseResultType >::ok(), Catch::Clara::Detail::BasicResult< ParseResultType >::runtimeError(), and Catch::toLower().
convertInto() [2/3]
ParserResult Catch::Clara::Detail::convertInto (std::string const & source, std::string & target)
Definition at line 2535 of file catch_amalgamated.cpp.
References Catch::Clara::Matched, and Catch::Clara::Detail::BasicResult< ParseResultType >::ok().
Referenced by convertInto(), invokeLambda(), Catch::Clara::Detail::BoundValueRef< T >::setValue(), and Catch::Clara::Detail::BoundValueRef< std::vector< T > >::setValue().
convertInto() [3/3]
template<typename T> ParserResult Catch::Clara::Detail::convertInto (std::string const & source, T & target)
Definition at line 4720 of file catch_amalgamated.hpp.
References convertInto(), Catch::Clara::Matched, Catch::Clara::Detail::BasicResult< ParseResultType >::ok(), and Catch::Clara::Detail::BasicResult< ParseResultType >::runtimeError().
invokeLambda()
template<typename ArgType, typename L> auto Catch::Clara::Detail::invokeLambda (L const & lambda, std::string const & arg)->ParserResult
Definition at line 4820 of file catch_amalgamated.hpp.
References convertInto(), and invokeLambda().
Referenced by invokeLambda(), and Catch::Clara::Detail::BoundLambda< L >::setValue().