libthe-seed: Catch::Benchmark Namespace Reference
Catch::Benchmark Namespace Reference
Namespaces
namespace Detail
Classes
struct Estimate
struct OutlierClassification
struct now
struct EnvironmentEstimate
struct Environment
struct Chronometer
struct Timing
struct ExecutionPlan
struct SampleAnalysis
struct Benchmark
Typedefs
template<typename Clock>
using ClockDuration = typename Clock::duration
template<typename Clock>
using FloatDuration = std::chrono::duration<double, typename Clock::period>
template<typename Clock>
using TimePoint = typename Clock::time_point
using default_clock = std::chrono::steady_clock
using fp_seconds = std::chrono::duration<double, std::ratio<1>>
template<typename Clock, typename Func, typename... Args>
using TimingOf = Timing<ClockDuration<Clock>, Detail::CompleteType_t<FunctionReturnType<Func, Args...>>>
template<typename T>
using storage_for = Detail::ObjectStorage<T, true>
template<typename T>
using destructable_object = Detail::ObjectStorage<T, false>
using IDuration = std::chrono::nanoseconds
using FDuration = std::chrono::duration<double, std::nano>
Functions
template<typename T>
void deoptimize_value (T &&x)
template<typename Fn, typename... Args>
auto invoke_deoptimized (Fn &&fn, Args &&... args) -> std::enable_if_t<!std::is_same< void, decltype(fn(args...))>::value >
template<typename Fn, typename... Args>
auto invoke_deoptimized (Fn &&fn, Args &&... args) -> std::enable_if_t< std::is_same< void, decltype(fn(args...))>::value >
template<typename Fun>
Detail::CompleteType_t< FunctionReturnType< Fun > > user_code (Fun &&fun)
Typedef Documentation
ClockDuration
template<typename Clock> using Catch::Benchmark::ClockDuration = typename Clock::duration
Definition at line 1352 of file catch_amalgamated.hpp.
default_clock
using Catch::Benchmark::default_clock = std::chrono::steady_clock
Definition at line 1359 of file catch_amalgamated.hpp.
destructable_object
template<typename T> using Catch::Benchmark::destructable_object = Detail::ObjectStorage<T, false>
Definition at line 2444 of file catch_amalgamated.hpp.
FDuration
using Catch::Benchmark::FDuration = std::chrono::duration<double, std::nano>
Definition at line 18 of file catch_clock.hpp.
FloatDuration
template<typename Clock> using Catch::Benchmark::FloatDuration = std::chrono::duration<double, typename Clock::period>
Definition at line 1354 of file catch_amalgamated.hpp.
fp_seconds
using Catch::Benchmark::fp_seconds = std::chrono::duration<double, std::ratio<1>>
Definition at line 1368 of file catch_amalgamated.hpp.
IDuration
using Catch::Benchmark::IDuration = std::chrono::nanoseconds
Definition at line 17 of file catch_clock.hpp.
storage_for
template<typename T> using Catch::Benchmark::storage_for = Detail::ObjectStorage<T, true>
Definition at line 2441 of file catch_amalgamated.hpp.
TimePoint
template<typename Clock> using Catch::Benchmark::TimePoint = typename Clock::time_point
Definition at line 1357 of file catch_amalgamated.hpp.
TimingOf
template<typename Clock, typename Func, typename... Args> using Catch::Benchmark::TimingOf = Timing<ClockDuration<Clock>, Detail::CompleteType_t<FunctionReturnType<Func, Args...>>>
Definition at line 1801 of file catch_amalgamated.hpp.
Function Documentation
deoptimize_value()
template<typename T> void Catch::Benchmark::deoptimize_value (T && x) inline
Definition at line 1479 of file catch_amalgamated.hpp.
References deoptimize_value().
Referenced by deoptimize_value(), and invoke_deoptimized().
invoke_deoptimized() [1/2]
template<typename Fn, typename... Args> auto Catch::Benchmark::invoke_deoptimized (Fn && fn, Args &&... args)->std::enable_if_t< std::is_same< void, decltype(fn(args...))>::value > inline
Definition at line 1489 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and invoke_deoptimized().
invoke_deoptimized() [2/2]
template<typename Fn, typename... Args> auto Catch::Benchmark::invoke_deoptimized (Fn && fn, Args &&... args)->std::enable_if_t<!std::is_same< void, decltype(fn(args...))>::value > inline
Definition at line 1484 of file catch_amalgamated.hpp.
References CATCH_FORWARD, deoptimize_value(), and invoke_deoptimized().
Referenced by invoke_deoptimized(), and invoke_deoptimized().
user_code()
template<typename Fun> Detail::CompleteType_t< FunctionReturnType< Fun > > Catch::Benchmark::user_code (Fun && fun)
Definition at line 1775 of file catch_amalgamated.hpp.
References CATCH_FORWARD, Catch::Benchmark::Detail::complete_invoke(), and user_code().
Referenced by Catch::Benchmark::Benchmark::run(), and user_code().