libthe-seed: Catch::StringMaker< T, typename > Struct Template Reference
Catch::StringMaker< T, typename > Struct Template Reference
#include <catch_amalgamated.hpp>
Static Public Member Functions
template<typename Fake = T>
static std::enable_if_t<::Catch::Detail::IsStreamInsertable< Fake >::value, std::string > convert (const Fake &value)
template<typename Fake = T>
static std::enable_if_t<!::Catch::Detail::IsStreamInsertable< Fake >::value, std::string > convert (const Fake &value)
template<typename Fake = T>
static std::enable_if_t<::Catch::Detail::IsStreamInsertable< Fake >::value, std::string > convert (const Fake &value)
template<typename Fake = T>
static std::enable_if_t<!::Catch::Detail::IsStreamInsertable< Fake >::value, std::string > convert (const Fake &value)
Detailed Description
template<typename T, typename = void>
struct Catch::StringMaker< T, typename >
Definition at line 2706 of file catch_amalgamated.hpp.
Member Function Documentation
convert() [1/4]
template<typename T, typename = void> template<typename Fake = T> std::enable_if_t<!::Catch::Detail::IsStreamInsertable< Fake >::value, std::string > Catch::StringMaker< T, typename >::convert (const Fake & value) inline static
Definition at line 2721 of file catch_amalgamated.hpp.
References Catch::Detail::convertUnstreamable().
convert() [2/4]
template<typename T, typename = void> template<typename Fake = T> std::enable_if_t<::Catch::Detail::IsStreamInsertable< Fake >::value, std::string > Catch::StringMaker< T, typename >::convert (const Fake & value) inline static
Definition at line 2710 of file catch_amalgamated.hpp.
References Catch::ReusableStringStream::str().
convert() [3/4]
template<typename T, typename = void> template<typename Fake = T> std::enable_if_t<!::Catch::Detail::IsStreamInsertable< Fake >::value, std::string > Catch::StringMaker< T, typename >::convert (const Fake & value) inline static
Definition at line 135 of file catch_tostring.hpp.
References Catch::Detail::convertUnstreamable().
convert() [4/4]
template<typename T, typename = void> template<typename Fake = T> std::enable_if_t<::Catch::Detail::IsStreamInsertable< Fake >::value, std::string > Catch::StringMaker< T, typename >::convert (const Fake & value) inline static
Definition at line 124 of file catch_tostring.hpp.
References Catch::ReusableStringStream::str().
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/catch_tostring.hpp