libthe-seed: Catch::TestCaseTracking::NameAndLocationRef Struct Reference
Catch::TestCaseTracking::NameAndLocationRef Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
constexpr NameAndLocationRef (StringRef name_, SourceLineInfo location_)
constexpr NameAndLocationRef (StringRef name_, SourceLineInfo location_)
Public Attributes
StringRef name
SourceLineInfo location
Friends
bool operator== (NameAndLocation const &lhs, NameAndLocationRef const &rhs)
bool operator== (NameAndLocationRef const &lhs, NameAndLocation const &rhs)
bool operator== (NameAndLocation const &lhs, NameAndLocationRef const &rhs)
bool operator== (NameAndLocationRef const &lhs, NameAndLocation const &rhs)
Detailed Description
This is a variant of NameAndLocation that does not own the name string
This avoids extra allocations when trying to locate a tracker by its name and location, as long as we make sure that trackers only keep around the owning variant.
Definition at line 9564 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
NameAndLocationRef() [1/2]
Catch::TestCaseTracking::NameAndLocationRef::NameAndLocationRef (StringRef name_, SourceLineInfo location_) inline constexpr
Definition at line 9568 of file catch_amalgamated.hpp.
References location, and name.
Referenced by operator==, and operator==.
NameAndLocationRef() [2/2]
Catch::TestCaseTracking::NameAndLocationRef::NameAndLocationRef (StringRef name_, SourceLineInfo location_) inline constexpr
Definition at line 51 of file catch_test_case_tracker.hpp.
References location, and name.
Friends And Related Symbol Documentation
operator== [1/4]
bool operator== (NameAndLocation const & lhs, NameAndLocationRef const & rhs) friend
Definition at line 9572 of file catch_amalgamated.hpp.
References Catch::SourceLineInfo::line, Catch::TestCaseTracking::NameAndLocation::location, location, Catch::TestCaseTracking::NameAndLocation::name, name, and NameAndLocationRef().
operator== [2/4]
bool operator== (NameAndLocation const & lhs, NameAndLocationRef const & rhs) friend
Definition at line 55 of file catch_test_case_tracker.hpp.
References NameAndLocationRef().
operator== [3/4]
bool operator== (NameAndLocationRef const & lhs, NameAndLocation const & rhs) friend
Definition at line 9582 of file catch_amalgamated.hpp.
References NameAndLocationRef().
operator== [4/4]
bool operator== (NameAndLocationRef const & lhs, NameAndLocation const & rhs) friend
Definition at line 65 of file catch_test_case_tracker.hpp.
References NameAndLocationRef().
Member Data Documentation
location
SourceLineInfo Catch::TestCaseTracking::NameAndLocationRef::location
Definition at line 9566 of file catch_amalgamated.hpp.
Referenced by NameAndLocationRef(), and operator==.
name
StringRef Catch::TestCaseTracking::NameAndLocationRef::name
Definition at line 9565 of file catch_amalgamated.hpp.
Referenced by NameAndLocationRef(), and operator==.
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_test_case_tracker.hpp