libthe-seed: Catch::ReporterConfig Struct Reference
Catch::ReporterConfig Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
ReporterConfig (IConfig const *_fullConfig, Detail::unique_ptr< IStream > _stream, ColourMode colourMode, std::map< std::string, std::string > customOptions)
ReporterConfig (ReporterConfig &&)=default
ReporterConfig & operator= (ReporterConfig &&)=default
~ReporterConfig ()
Detail::unique_ptr< IStream > takeStream () &&
IConfig const * fullConfig () const
ColourMode colourMode () const
std::map< std::string, std::string > const & customOptions () const
ReporterConfig (IConfig const *_fullConfig, Detail::unique_ptr< IStream > _stream, ColourMode colourMode, std::map< std::string, std::string > customOptions)
ReporterConfig (ReporterConfig &&)=default
ReporterConfig & operator= (ReporterConfig &&)=default
~ReporterConfig ()
Detail::unique_ptr< IStream > takeStream () &&
IConfig const * fullConfig () const
ColourMode colourMode () const
std::map< std::string, std::string > const & customOptions () const
Detailed Description
Definition at line 8287 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
ReporterConfig() [1/4]
Catch::ReporterConfig::ReporterConfig (IConfig const * _fullConfig, Detail::unique_ptr< IStream > _stream, ColourMode colourMode, std::map< std::string, std::string > customOptions)
Definition at line 2256 of file catch_amalgamated.cpp.
References CATCH_MOVE, colourMode(), and customOptions().
Referenced by operator=(), and ReporterConfig().
ReporterConfig() [2/4]
Catch::ReporterConfig::ReporterConfig (ReporterConfig &&) default
References ReporterConfig().
~ReporterConfig() [1/2]
Catch::ReporterConfig::~ReporterConfig () default
References colourMode(), customOptions(), fullConfig(), and takeStream().
ReporterConfig() [3/4]
Catch::ReporterConfig::ReporterConfig (IConfig const * _fullConfig, Detail::unique_ptr< IStream > _stream, ColourMode colourMode, std::map< std::string, std::string > customOptions)
References colourMode(), and customOptions().
ReporterConfig() [4/4]
Catch::ReporterConfig::ReporterConfig (ReporterConfig &&) default
References ReporterConfig().
~ReporterConfig() [2/2]
Catch::ReporterConfig::~ReporterConfig ()
Member Function Documentation
colourMode() [1/2]
ColourMode Catch::ReporterConfig::colourMode () const
Definition at line 2271 of file catch_amalgamated.cpp.
Referenced by ReporterConfig(), and ~ReporterConfig().
colourMode() [2/2]
ColourMode Catch::ReporterConfig::colourMode () const
customOptions() [1/2]
std::map< std::string, std::string > const & Catch::ReporterConfig::customOptions () const
Definition at line 2274 of file catch_amalgamated.cpp.
Referenced by ReporterConfig(), and ~ReporterConfig().
customOptions() [2/2]
std::map< std::string, std::string > const & Catch::ReporterConfig::customOptions () const
fullConfig() [1/2]
IConfig const * Catch::ReporterConfig::fullConfig () const
Definition at line 2270 of file catch_amalgamated.cpp.
Referenced by ~ReporterConfig().
fullConfig() [2/2]
IConfig const * Catch::ReporterConfig::fullConfig () const
operator=() [1/2]
ReporterConfig & Catch::ReporterConfig::operator= (ReporterConfig &&) default
References ReporterConfig().
operator=() [2/2]
ReporterConfig & Catch::ReporterConfig::operator= (ReporterConfig &&) default
References ReporterConfig().
takeStream() [1/2]
Detail::unique_ptr< IStream > Catch::ReporterConfig::takeStream () &&
Definition at line 2266 of file catch_amalgamated.cpp.
References CATCH_MOVE.
Referenced by ~ReporterConfig().
takeStream() [2/2]
Detail::unique_ptr< IStream > Catch::ReporterConfig::takeStream () &&
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/interfaces/catch_interfaces_reporter.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/interfaces/catch_interfaces_reporter.cpp