libthe-seed: Catch::TestCaseTracking::NameAndLocation Struct Reference
Catch::TestCaseTracking::NameAndLocation Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
NameAndLocation (std::string &&_name, SourceLineInfo const &_location)
NameAndLocation (std::string &&_name, SourceLineInfo const &_location)
Public Attributes
std::string name
SourceLineInfo location
Friends
bool operator== (NameAndLocation const &lhs, NameAndLocation const &rhs)
bool operator!= (NameAndLocation const &lhs, NameAndLocation const &rhs)
bool operator== (NameAndLocation const &lhs, NameAndLocation const &rhs)
bool operator!= (NameAndLocation const &lhs, NameAndLocation const &rhs)
Detailed Description
Definition at line 9538 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
NameAndLocation() [1/2]
Catch::TestCaseTracking::NameAndLocation::NameAndLocation (std::string && _name, SourceLineInfo const & _location)
Definition at line 6287 of file catch_amalgamated.cpp.
References CATCH_MOVE, location, and name.
Referenced by operator!=, and operator==.
NameAndLocation() [2/2]
Catch::TestCaseTracking::NameAndLocation::NameAndLocation (std::string && _name, SourceLineInfo const & _location)
Friends And Related Symbol Documentation
operator!= [1/2]
bool operator!= (NameAndLocation const & lhs, NameAndLocation const & rhs) friend
Definition at line 9551 of file catch_amalgamated.hpp.
References NameAndLocation().
operator!= [2/2]
bool operator!= (NameAndLocation const & lhs, NameAndLocation const & rhs) friend
Definition at line 34 of file catch_test_case_tracker.hpp.
References NameAndLocation().
operator== [1/2]
bool operator== (NameAndLocation const & lhs, NameAndLocation const & rhs) friend
Definition at line 9543 of file catch_amalgamated.hpp.
References Catch::SourceLineInfo::line, location, name, and NameAndLocation().
operator== [2/2]
bool operator== (NameAndLocation const & lhs, NameAndLocation const & rhs) friend
Definition at line 26 of file catch_test_case_tracker.hpp.
References NameAndLocation().
Member Data Documentation
location
SourceLineInfo Catch::TestCaseTracking::NameAndLocation::location
Definition at line 9540 of file catch_amalgamated.hpp.
Referenced by NameAndLocation(), operator==, and Catch::TestCaseTracking::NameAndLocationRef::operator==.
name
std::string Catch::TestCaseTracking::NameAndLocation::name
Definition at line 9539 of file catch_amalgamated.hpp.
Referenced by NameAndLocation(), operator==, and Catch::TestCaseTracking::NameAndLocationRef::operator==.
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_test_case_tracker.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_test_case_tracker.cpp