libthe-seed: clara::detail::NonCopyable Struct Reference
clara::detail::NonCopyable Struct Reference
#include <clara.hpp>
Public Member Functions
NonCopyable ()=default
NonCopyable (NonCopyable const &)=delete
NonCopyable (NonCopyable &&)=delete
NonCopyable & operator= (NonCopyable const &)=delete
NonCopyable & operator= (NonCopyable &&)=delete
Detailed Description
Definition at line 690 of file clara.hpp.
Constructor & Destructor Documentation
NonCopyable() [1/3]
clara::detail::NonCopyable::NonCopyable () default
Referenced by NonCopyable(), NonCopyable(), operator=(), and operator=().
NonCopyable() [2/3]
clara::detail::NonCopyable::NonCopyable (NonCopyable const &) delete
References NonCopyable().
NonCopyable() [3/3]
clara::detail::NonCopyable::NonCopyable (NonCopyable &&) delete
References NonCopyable().
Member Function Documentation
operator=() [1/2]
NonCopyable & clara::detail::NonCopyable::operator= (NonCopyable &&) delete
References NonCopyable().
operator=() [2/2]
NonCopyable & clara::detail::NonCopyable::operator= (NonCopyable const &) delete
References NonCopyable().
The documentation for this struct was generated from the following file:
external/Catch2/third_party/clara.hpp