libthe-seed: Catch::Benchmark::ExecutionPlan< Duration > Struct Template Reference
Catch::Benchmark::ExecutionPlan< Duration > Struct Template Reference
#include <catch_amalgamated.hpp>
Public Member Functions
template<typename Duration2>
operator ExecutionPlan< Duration2 > () const
template<typename Clock>
std::vector< FloatDuration< Clock > > run (const IConfig &cfg, Environment< FloatDuration< Clock > > env) const
template<typename Clock>
std::vector< FDuration > run (const IConfig &cfg, Environment env) const
Public Attributes
int iterations_per_sample
Duration estimated_duration
Detail::BenchmarkFunction benchmark
Duration warmup_time
int warmup_iterations
FDuration estimated_duration
FDuration warmup_time
Detailed Description
template<typename Duration>
struct Catch::Benchmark::ExecutionPlan< Duration >
Definition at line 1875 of file catch_amalgamated.hpp.
Member Function Documentation
operator ExecutionPlan< Duration2 >()
template<typename Duration> template<typename Duration2> Catch::Benchmark::ExecutionPlan< Duration >::operator ExecutionPlan< Duration2 > () const inline
Definition at line 1883 of file catch_amalgamated.hpp.
References benchmark, estimated_duration, iterations_per_sample, warmup_iterations, and warmup_time.
run() [1/2]
template<typename Duration> template<typename Clock> std::vector< FDuration > Catch::Benchmark::ExecutionPlan< Duration >::run (const IConfig & cfg, Environment env) const inline
Definition at line 32 of file catch_execution_plan.hpp.
References benchmark, Catch::IConfig::benchmarkSamples(), Catch::Benchmark::Environment< Clock >::clock_cost, Catch::Benchmark::Detail::ChronometerModel< Clock >::elapsed(), iterations_per_sample, Catch::Benchmark::EnvironmentEstimate< Duration >::mean, Catch::Benchmark::Detail::repeat(), Catch::Benchmark::Detail::run_for_at_least(), warmup_iterations, and warmup_time.
run() [2/2]
template<typename Duration> template<typename Clock> std::vector< FloatDuration< Clock > > Catch::Benchmark::ExecutionPlan< Duration >::run (const IConfig & cfg, Environment< FloatDuration< Clock > > env) const inline
Definition at line 1888 of file catch_amalgamated.hpp.
References Catch::IConfig::benchmarkSamples(), Catch::Benchmark::Detail::ChronometerModel< Clock >::elapsed(), iterations_per_sample, Catch::Benchmark::Detail::repeat(), Catch::Benchmark::Detail::run_for_at_least(), warmup_iterations, and warmup_time.
Member Data Documentation
benchmark
template<typename Duration> Detail::BenchmarkFunction Catch::Benchmark::ExecutionPlan< Duration >::benchmark
Definition at line 1878 of file catch_amalgamated.hpp.
Referenced by operator ExecutionPlan< Duration2 >(), and run().
estimated_duration [1/2]
template<typename Duration> Duration Catch::Benchmark::ExecutionPlan< Duration >::estimated_duration
Definition at line 1877 of file catch_amalgamated.hpp.
Referenced by operator ExecutionPlan< Duration2 >().
estimated_duration [2/2]
template<typename Duration> FDuration Catch::Benchmark::ExecutionPlan< Duration >::estimated_duration
Definition at line 26 of file catch_execution_plan.hpp.
iterations_per_sample
template<typename Duration> int Catch::Benchmark::ExecutionPlan< Duration >::iterations_per_sample
Definition at line 1876 of file catch_amalgamated.hpp.
Referenced by operator ExecutionPlan< Duration2 >(), run(), and run().
warmup_iterations
template<typename Duration> int Catch::Benchmark::ExecutionPlan< Duration >::warmup_iterations
Definition at line 1880 of file catch_amalgamated.hpp.
Referenced by operator ExecutionPlan< Duration2 >(), run(), and run().
warmup_time [1/2]
template<typename Duration> Duration Catch::Benchmark::ExecutionPlan< Duration >::warmup_time
Definition at line 1879 of file catch_amalgamated.hpp.
Referenced by operator ExecutionPlan< Duration2 >(), run(), and run().
warmup_time [2/2]
template<typename Duration> FDuration Catch::Benchmark::ExecutionPlan< Duration >::warmup_time
Definition at line 28 of file catch_execution_plan.hpp.
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/benchmark/catch_execution_plan.hpp