libthe-seed: Catch::Benchmark::Detail::ChronometerConcept Struct Reference
Catch::Benchmark::Detail::ChronometerConcept Struct Reference abstract
#include <catch_amalgamated.hpp>
Public Member Functions
virtual void start ()=0
virtual void finish ()=0
virtual ~ChronometerConcept ()
ChronometerConcept ()=default
ChronometerConcept (ChronometerConcept const &)=default
ChronometerConcept & operator= (ChronometerConcept const &)=default
virtual void start ()=0
virtual void finish ()=0
virtual ~ChronometerConcept ()
ChronometerConcept ()=default
ChronometerConcept (ChronometerConcept const &)=default
ChronometerConcept & operator= (ChronometerConcept const &)=default
Detailed Description
Definition at line 1542 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
~ChronometerConcept() [1/2]
Catch::Benchmark::Detail::ChronometerConcept::~ChronometerConcept () virtual default
ChronometerConcept() [1/4]
Catch::Benchmark::Detail::ChronometerConcept::ChronometerConcept () default
Referenced by ChronometerConcept(), and operator=().
ChronometerConcept() [2/4]
Catch::Benchmark::Detail::ChronometerConcept::ChronometerConcept (ChronometerConcept const &) default
References ChronometerConcept().
~ChronometerConcept() [2/2]
virtual Catch::Benchmark::Detail::ChronometerConcept::~ChronometerConcept () virtual
ChronometerConcept() [3/4]
Catch::Benchmark::Detail::ChronometerConcept::ChronometerConcept () default
ChronometerConcept() [4/4]
Catch::Benchmark::Detail::ChronometerConcept::ChronometerConcept (ChronometerConcept const &) default
References ChronometerConcept().
Member Function Documentation
finish() [1/2]
virtual void Catch::Benchmark::Detail::ChronometerConcept::finish () pure virtual
Implemented in Catch::Benchmark::Detail::ChronometerModel< Clock >, and Catch::Benchmark::Detail::ChronometerModel< Clock >.
finish() [2/2]
virtual void Catch::Benchmark::Detail::ChronometerConcept::finish () pure virtual
Implemented in Catch::Benchmark::Detail::ChronometerModel< Clock >, and Catch::Benchmark::Detail::ChronometerModel< Clock >.
operator=() [1/2]
ChronometerConcept & Catch::Benchmark::Detail::ChronometerConcept::operator= (ChronometerConcept const &) default
References ChronometerConcept().
operator=() [2/2]
ChronometerConcept & Catch::Benchmark::Detail::ChronometerConcept::operator= (ChronometerConcept const &) default
References ChronometerConcept().
start() [1/2]
virtual void Catch::Benchmark::Detail::ChronometerConcept::start () pure virtual
Implemented in Catch::Benchmark::Detail::ChronometerModel< Clock >, and Catch::Benchmark::Detail::ChronometerModel< Clock >.
start() [2/2]
virtual void Catch::Benchmark::Detail::ChronometerConcept::start () pure virtual
Implemented in Catch::Benchmark::Detail::ChronometerModel< Clock >, and Catch::Benchmark::Detail::ChronometerModel< Clock >.
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/benchmark/catch_chronometer.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/benchmark/catch_chronometer.cpp