libthe-seed: Catch::SourceLineInfo Struct Reference
Catch::SourceLineInfo Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
SourceLineInfo ()=delete
constexpr SourceLineInfo (char const *_file, std::size_t _line) noexcept
bool operator== (SourceLineInfo const &other) const noexcept
bool operator< (SourceLineInfo const &other) const noexcept
SourceLineInfo ()=delete
constexpr SourceLineInfo (char const *_file, std::size_t _line) noexcept
bool operator== (SourceLineInfo const &other) const noexcept
bool operator< (SourceLineInfo const &other) const noexcept
Public Attributes
char const * file
std::size_t line
Friends
std::ostream & operator<< (std::ostream &os, SourceLineInfo const &info)
std::ostream & operator<< (std::ostream &os, SourceLineInfo const &info)
Detailed Description
Definition at line 3386 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
SourceLineInfo() [1/4]
Catch::SourceLineInfo::SourceLineInfo () delete
Referenced by operator<(), operator<<, and operator==().
SourceLineInfo() [2/4]
Catch::SourceLineInfo::SourceLineInfo (char const * _file, std::size_t _line) inline constexpr noexcept
Definition at line 3389 of file catch_amalgamated.hpp.
References file, and line.
SourceLineInfo() [3/4]
Catch::SourceLineInfo::SourceLineInfo () delete
SourceLineInfo() [4/4]
Catch::SourceLineInfo::SourceLineInfo (char const * _file, std::size_t _line) inline constexpr noexcept
Definition at line 19 of file catch_source_line_info.hpp.
Member Function Documentation
operator<() [1/2]
bool Catch::SourceLineInfo::operator< (SourceLineInfo const & other) const noexcept
Definition at line 5847 of file catch_amalgamated.cpp.
References file, line, and SourceLineInfo().
operator<() [2/2]
bool Catch::SourceLineInfo::operator< (SourceLineInfo const & other) const noexcept
References file, line, and SourceLineInfo().
operator==() [1/2]
bool Catch::SourceLineInfo::operator== (SourceLineInfo const & other) const noexcept
Definition at line 5844 of file catch_amalgamated.cpp.
References file, line, and SourceLineInfo().
operator==() [2/2]
bool Catch::SourceLineInfo::operator== (SourceLineInfo const & other) const noexcept
References SourceLineInfo().
Friends And Related Symbol Documentation
operator<< [1/2]
std::ostream & operator<< (std::ostream & os, SourceLineInfo const & info) friend
Definition at line 5853 of file catch_amalgamated.cpp.
References file, line, and SourceLineInfo().
operator<< [2/2]
std::ostream & operator<< (std::ostream & os, SourceLineInfo const & info) friend
Definition at line 5853 of file catch_amalgamated.cpp.
Member Data Documentation
file
char const * Catch::SourceLineInfo::file
Definition at line 3397 of file catch_amalgamated.hpp.
Referenced by operator<(), operator<<, operator==(), SourceLineInfo(), Catch::TestCaseInfo::TestCaseInfo(), and Catch::XmlReporter::writeSourceInfo().
line
std::size_t Catch::SourceLineInfo::line
Definition at line 3398 of file catch_amalgamated.hpp.
Referenced by operator<(), operator<<, operator==(), Catch::TestCaseTracking::NameAndLocation::operator==, Catch::TestCaseTracking::NameAndLocationRef::operator==, SourceLineInfo(), and Catch::XmlReporter::writeSourceInfo().
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_source_line_info.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_source_line_info.cpp