libthe-seed: Catch::AssertionStats Struct Reference
Catch::AssertionStats Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
AssertionStats (AssertionResult const &_assertionResult, std::vector< MessageInfo > const &_infoMessages, Totals const &_totals)
AssertionStats (AssertionStats const &)=default
AssertionStats (AssertionStats &&)=default
AssertionStats & operator= (AssertionStats const &)=delete
AssertionStats & operator= (AssertionStats &&)=delete
AssertionStats (AssertionResult const &_assertionResult, std::vector< MessageInfo > const &_infoMessages, Totals const &_totals)
AssertionStats (AssertionStats const &)=default
AssertionStats (AssertionStats &&)=default
AssertionStats & operator= (AssertionStats const &)=delete
AssertionStats & operator= (AssertionStats &&)=delete
Public Attributes
AssertionResult assertionResult
std::vector< MessageInfo > infoMessages
Totals totals
Detailed Description
Definition at line 8309 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
AssertionStats() [1/6]
Catch::AssertionStats::AssertionStats (AssertionResult const & _assertionResult, std::vector< MessageInfo > const & _infoMessages, Totals const & _totals)
Definition at line 2280 of file catch_amalgamated.cpp.
References assertionResult, infoMessages, and totals.
Referenced by AssertionStats(), AssertionStats(), operator=(), and operator=().
AssertionStats() [2/6]
Catch::AssertionStats::AssertionStats (AssertionStats const &) default
References AssertionStats().
AssertionStats() [3/6]
Catch::AssertionStats::AssertionStats (AssertionStats &&) default
References AssertionStats().
AssertionStats() [4/6]
Catch::AssertionStats::AssertionStats (AssertionResult const & _assertionResult, std::vector< MessageInfo > const & _infoMessages, Totals const & _totals)
AssertionStats() [5/6]
Catch::AssertionStats::AssertionStats (AssertionStats const &) default
References AssertionStats().
AssertionStats() [6/6]
Catch::AssertionStats::AssertionStats (AssertionStats &&) default
References AssertionStats().
Member Function Documentation
operator=() [1/4]
AssertionStats & Catch::AssertionStats::operator= (AssertionStats &&) delete
References AssertionStats().
operator=() [2/4]
AssertionStats & Catch::AssertionStats::operator= (AssertionStats &&) delete
References assertionResult, AssertionStats(), infoMessages, and totals.
operator=() [3/4]
AssertionStats & Catch::AssertionStats::operator= (AssertionStats const &) delete
References AssertionStats().
operator=() [4/4]
AssertionStats & Catch::AssertionStats::operator= (AssertionStats const &) delete
References AssertionStats().
Member Data Documentation
assertionResult
AssertionResult Catch::AssertionStats::assertionResult
Definition at line 8319 of file catch_amalgamated.hpp.
Referenced by Catch::CompactReporter::assertionEnded(), Catch::ConsoleReporter::assertionEnded(), Catch::CumulativeReporterBase::assertionEnded(), Catch::JunitReporter::assertionEnded(), Catch::MultiReporter::assertionEnded(), Catch::TeamCityReporter::assertionEnded(), Catch::XmlReporter::assertionEnded(), AssertionStats(), operator=(), and Catch::SonarQubeReporter::writeAssertion().
infoMessages
std::vector< MessageInfo > Catch::AssertionStats::infoMessages
Definition at line 8320 of file catch_amalgamated.hpp.
Referenced by Catch::TeamCityReporter::assertionEnded(), Catch::XmlReporter::assertionEnded(), AssertionStats(), operator=(), and Catch::SonarQubeReporter::writeAssertion().
totals
Totals Catch::AssertionStats::totals
Definition at line 8321 of file catch_amalgamated.hpp.
Referenced by AssertionStats(), and operator=().
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/interfaces/catch_interfaces_reporter.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/interfaces/catch_interfaces_reporter.cpp