libthe-seed: Catch::Benchmark::Chronometer Struct Reference
Catch::Benchmark::Chronometer Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
template<typename Fun>
void measure (Fun &&fun)
int runs () const
Chronometer (Detail::ChronometerConcept &meter, int repeats_)
template<typename Fun>
void measure (Fun &&fun)
int runs () const
Chronometer (Detail::ChronometerConcept &meter, int repeats_)
Detailed Description
Definition at line 1563 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
Chronometer() [1/2]
Catch::Benchmark::Chronometer::Chronometer (Detail::ChronometerConcept & meter, int repeats_) inline
Definition at line 1570 of file catch_amalgamated.hpp.
Chronometer() [2/2]
Catch::Benchmark::Chronometer::Chronometer (Detail::ChronometerConcept & meter, int repeats_) inline
Definition at line 52 of file catch_chronometer.hpp.
Member Function Documentation
measure() [1/2]
template<typename Fun> void Catch::Benchmark::Chronometer::measure (Fun && fun) inline
Definition at line 1566 of file catch_amalgamated.hpp.
References CATCH_FORWARD, and measure().
Referenced by measure(), and TEST_CASE().
measure() [2/2]
template<typename Fun> void Catch::Benchmark::Chronometer::measure (Fun && fun) inline
Definition at line 48 of file catch_chronometer.hpp.
References CATCH_FORWARD, and measure().
Referenced by measure().
runs() [1/2]
int Catch::Benchmark::Chronometer::runs () const inline
Definition at line 1568 of file catch_amalgamated.hpp.
Referenced by TEST_CASE().
runs() [2/2]
int Catch::Benchmark::Chronometer::runs () const inline
Definition at line 50 of file catch_chronometer.hpp.
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/benchmark/catch_chronometer.hpp