libthe-seed: Catch::Clara::Detail::BoundFlagRefBase Struct Reference
Catch::Clara::Detail::BoundFlagRefBase Struct Reference abstract
#include <catch_amalgamated.hpp>
Public Member Functions
virtual auto setFlag (bool flag) -> ParserResult=0
bool isFlag () const override
virtual auto setFlag (bool flag) -> ParserResult=0
bool isFlag () const override
Public Member Functions inherited from Catch::Clara::Detail::BoundRef
virtual ~BoundRef ()=default
virtual bool isContainer () const
virtual ~BoundRef ()=default
virtual bool isContainer () const
Additional Inherited Members
Protected Member Functions inherited from Catch::Detail::NonCopyable
NonCopyable () noexcept=default
NonCopyable () noexcept=default
Detailed Description
Definition at line 4757 of file catch_amalgamated.hpp.
Member Function Documentation
isFlag() [1/2]
bool Catch::Clara::Detail::BoundFlagRefBase::isFlag () const override virtual
Reimplemented from Catch::Clara::Detail::BoundRef.
Definition at line 2580 of file catch_amalgamated.cpp.
Referenced by setFlag().
isFlag() [2/2]
bool Catch::Clara::Detail::BoundFlagRefBase::isFlag () const override virtual
Reimplemented from Catch::Clara::Detail::BoundRef.
setFlag() [1/2]
virtual auto Catch::Clara::Detail::BoundFlagRefBase::setFlag (bool flag) ->ParserResult pure virtual
Implemented in Catch::Clara::Detail::BoundFlagLambda< L >, and Catch::Clara::Detail::BoundFlagLambda< L >.
References isFlag().
Referenced by Catch::Clara::Opt::parse().
setFlag() [2/2]
virtual auto Catch::Clara::Detail::BoundFlagRefBase::setFlag (bool flag) ->ParserResult pure virtual
Implemented in Catch::Clara::Detail::BoundFlagLambda< L >, and Catch::Clara::Detail::BoundFlagLambda< L >.
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_clara.cpp