libthe-seed: Catch::Version Struct Reference
Catch::Version Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
Version (Version const &)=delete
Version & operator= (Version const &)=delete
Version (unsigned int _majorVersion, unsigned int _minorVersion, unsigned int _patchNumber, char const *const _branchName, unsigned int _buildNumber)
Version (Version const &)=delete
Version & operator= (Version const &)=delete
Version (unsigned int _majorVersion, unsigned int _minorVersion, unsigned int _patchNumber, char const *const _branchName, unsigned int _buildNumber)
Public Attributes
unsigned int const majorVersion
unsigned int const minorVersion
unsigned int const patchNumber
char const *const branchName
unsigned int const buildNumber
Friends
std::ostream & operator<< (std::ostream &os, Version const &version)
std::ostream & operator<< (std::ostream &os, Version const &version)
Detailed Description
Definition at line 7347 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
Version() [1/4]
Catch::Version::Version (Version const &) delete
References Version().
Referenced by operator<<, operator=(), Version(), and Version().
Version() [2/4]
Catch::Version::Version (unsigned int _majorVersion, unsigned int _minorVersion, unsigned int _patchNumber, char const *const _branchName, unsigned int _buildNumber)
Definition at line 2110 of file catch_amalgamated.cpp.
References branchName, buildNumber, majorVersion, minorVersion, and patchNumber.
Version() [3/4]
Catch::Version::Version (Version const &) delete
References Version().
Version() [4/4]
Catch::Version::Version (unsigned int _majorVersion, unsigned int _minorVersion, unsigned int _patchNumber, char const *const _branchName, unsigned int _buildNumber)
References branchName, buildNumber, majorVersion, minorVersion, patchNumber, and Version().
Member Function Documentation
operator=() [1/2]
Version & Catch::Version::operator= (Version const &) delete
References Version().
operator=() [2/2]
Version & Catch::Version::operator= (Version const &) delete
References Version().
Friends And Related Symbol Documentation
operator<< [1/2]
std::ostream & operator<< (std::ostream & os, Version const & version) friend
Definition at line 2123 of file catch_amalgamated.cpp.
References branchName, buildNumber, majorVersion, minorVersion, patchNumber, and Version().
operator<< [2/2]
std::ostream & operator<< (std::ostream & os, Version const & version) friend
Definition at line 2123 of file catch_amalgamated.cpp.
Member Data Documentation
branchName
char const *const Catch::Version::branchName
Definition at line 7361 of file catch_amalgamated.hpp.
Referenced by operator<<, and Version().
buildNumber
unsigned int const Catch::Version::buildNumber
Definition at line 7362 of file catch_amalgamated.hpp.
Referenced by operator<<, and Version().
majorVersion
unsigned int const Catch::Version::majorVersion
Definition at line 7356 of file catch_amalgamated.hpp.
Referenced by operator<<, and Version().
minorVersion
unsigned int const Catch::Version::minorVersion
Definition at line 7357 of file catch_amalgamated.hpp.
Referenced by operator<<, and Version().
patchNumber
unsigned int const Catch::Version::patchNumber
Definition at line 7358 of file catch_amalgamated.hpp.
Referenced by operator<<, and Version().
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/catch_version.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/catch_version.cpp