libthe-seed: Catch::Clara::Detail::BoundRef Struct Reference
Catch::Clara::Detail::BoundRef Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
virtual ~BoundRef ()=default
virtual bool isContainer () const
virtual bool isFlag () const
virtual ~BoundRef ()=default
virtual bool isContainer () const
virtual bool isFlag () const
Additional Inherited Members
Protected Member Functions inherited from Catch::Detail::NonCopyable
NonCopyable () noexcept=default
NonCopyable () noexcept=default
Detailed Description
Definition at line 4748 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
~BoundRef() [1/2]
virtual Catch::Clara::Detail::BoundRef::~BoundRef () virtual default
References isContainer(), and isFlag().
~BoundRef() [2/2]
virtual Catch::Clara::Detail::BoundRef::~BoundRef () virtual default
Member Function Documentation
isContainer() [1/2]
bool Catch::Clara::Detail::BoundRef::isContainer () const virtual
Reimplemented in Catch::Clara::Detail::BoundManyLambda< L >, and Catch::Clara::Detail::BoundManyLambda< L >.
Definition at line 2576 of file catch_amalgamated.cpp.
Referenced by ~BoundRef().
isContainer() [2/2]
virtual bool Catch::Clara::Detail::BoundRef::isContainer () const virtual
Reimplemented in Catch::Clara::Detail::BoundManyLambda< L >, and Catch::Clara::Detail::BoundManyLambda< L >.
isFlag() [1/2]
bool Catch::Clara::Detail::BoundRef::isFlag () const virtual
Reimplemented in Catch::Clara::Detail::BoundFlagRefBase, and Catch::Clara::Detail::BoundFlagRefBase.
Definition at line 2578 of file catch_amalgamated.cpp.
Referenced by ~BoundRef().
isFlag() [2/2]
virtual bool Catch::Clara::Detail::BoundRef::isFlag () const virtual
Reimplemented in Catch::Clara::Detail::BoundFlagRefBase, and Catch::Clara::Detail::BoundFlagRefBase.
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_clara.cpp