libthe-seed: Catch::Benchmark::Benchmark Struct Reference
Catch::Benchmark::Benchmark Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
Benchmark (std::string &&benchmarkName)
template<class FUN>
Benchmark (std::string &&benchmarkName, FUN &&func)
template<typename Clock>
ExecutionPlan< FloatDuration< Clock > > prepare (const IConfig &cfg, Environment< FloatDuration< Clock > > env) const
template<typename Clock = default_clock>
void run ()
template<typename Fun, std::enable_if_t<!Detail::is_related< Fun, Benchmark >::value, int > = 0>
Benchmark & operator= (Fun func)
operator bool ()
Benchmark (std::string &&benchmarkName)
template<class FUN>
Benchmark (std::string &&benchmarkName, FUN &&func)
template<typename Clock>
ExecutionPlan prepare (const IConfig &cfg, Environment env) const
template<typename Clock = default_clock>
void run ()
template<typename Fun, std::enable_if_t<!Detail::is_related< Fun, Benchmark >::value, int > = 0>
Benchmark & operator= (Fun func)
operator bool ()
Detailed Description
Definition at line 2265 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
Benchmark() [1/4]
Catch::Benchmark::Benchmark::Benchmark (std::string && benchmarkName) inline
Definition at line 2266 of file catch_amalgamated.hpp.
References CATCH_MOVE.
Referenced by operator=().
Benchmark() [2/4]
template<class FUN> Catch::Benchmark::Benchmark::Benchmark (std::string && benchmarkName, FUN && func) inline
Definition at line 2270 of file catch_amalgamated.hpp.
References CATCH_MOVE.
Benchmark() [3/4]
Catch::Benchmark::Benchmark::Benchmark (std::string && benchmarkName) inline
Definition at line 40 of file catch_benchmark.hpp.
References CATCH_MOVE.
Benchmark() [4/4]
template<class FUN> Catch::Benchmark::Benchmark::Benchmark (std::string && benchmarkName, FUN && func) inline
Definition at line 44 of file catch_benchmark.hpp.
References CATCH_MOVE.
Member Function Documentation
operator bool() [1/2]
Catch::Benchmark::Benchmark::operator bool () inline explicit
Definition at line 2334 of file catch_amalgamated.hpp.
operator bool() [2/2]
Catch::Benchmark::Benchmark::operator bool () inline explicit
Definition at line 110 of file catch_benchmark.hpp.
operator=() [1/2]
template<typename Fun, std::enable_if_t<!Detail::is_related< Fun, Benchmark >::value, int > = 0> Benchmark & Catch::Benchmark::Benchmark::operator= (Fun func) inline
Definition at line 2325 of file catch_amalgamated.hpp.
References Benchmark(), Catch::getCurrentContext(), and run().
operator=() [2/2]
template<typename Fun, std::enable_if_t<!Detail::is_related< Fun, Benchmark >::value, int > = 0> Benchmark & Catch::Benchmark::Benchmark::operator= (Fun func) inline
Definition at line 101 of file catch_benchmark.hpp.
References Benchmark(), Catch::Context::getConfig(), Catch::getCurrentContext(), and run().
prepare() [1/2]
template<typename Clock> ExecutionPlan Catch::Benchmark::Benchmark::prepare (const IConfig & cfg, Environment env) const inline
Definition at line 48 of file catch_benchmark.hpp.
References Catch::IConfig::benchmarkSamples(), Catch::IConfig::benchmarkWarmupTime(), Catch::Benchmark::Environment< Clock >::clock_resolution, Catch::Benchmark::EnvironmentEstimate< Duration >::mean, Catch::Benchmark::Detail::minimum_ticks, Catch::Benchmark::Detail::run_for_at_least(), and Catch::Benchmark::Detail::warmup_iterations.
prepare() [2/2]
template<typename Clock> ExecutionPlan< FloatDuration< Clock > > Catch::Benchmark::Benchmark::prepare (const IConfig & cfg, Environment< FloatDuration< Clock > > env) const inline
Definition at line 2274 of file catch_amalgamated.hpp.
References Catch::IConfig::benchmarkSamples(), Catch::IConfig::benchmarkWarmupTime(), Catch::Benchmark::Detail::minimum_ticks, Catch::Benchmark::Detail::run_for_at_least(), and Catch::Benchmark::Detail::warmup_iterations.
Referenced by run().
run() [1/2]
template<typename Clock = default_clock> void Catch::Benchmark::Benchmark::run () inline
Definition at line 2283 of file catch_amalgamated.hpp.
References Catch::Benchmark::Detail::analyse(), CATCH_CATCH_ALL, CATCH_CATCH_ANON, CATCH_MOVE, CATCH_TRY, Catch::getCurrentContext(), Catch::getResultCapture(), Catch::Benchmark::Detail::measure_environment(), prepare(), run(), Catch::translateActiveException(), and Catch::Benchmark::user_code().
Referenced by operator=(), run(), and TEST_CASE().
run() [2/2]
template<typename Clock = default_clock> void Catch::Benchmark::Benchmark::run () inline
Definition at line 57 of file catch_benchmark.hpp.
References Catch::Benchmark::Detail::analyse(), Catch::IResultCapture::benchmarkEnded(), Catch::IResultCapture::benchmarkFailed(), Catch::IResultCapture::benchmarkPreparing(), Catch::IResultCapture::benchmarkStarting(), CATCH_CATCH_ALL, CATCH_CATCH_ANON, CATCH_MOVE, CATCH_TRY, Catch::Context::getConfig(), Catch::getCurrentContext(), Catch::getResultCapture(), Catch::Benchmark::Detail::measure_environment(), prepare(), run(), Catch::translateActiveException(), and Catch::Benchmark::user_code().
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/benchmark/catch_benchmark.hpp