libthe-seed: Catch::Clara::Detail::BoundLambda< L > Struct Template Reference
Catch::Clara::Detail::BoundLambda< L > Struct Template Reference
#include <catch_amalgamated.hpp>
Public Member Functions
BoundLambda (L const &lambda)
auto setValue (std::string const &arg) -> ParserResult override
BoundLambda (L const &lambda)
auto setValue (std::string const &arg) -> ParserResult override
Public Member Functions inherited from Catch::Clara::Detail::BoundRef
virtual ~BoundRef ()=default
virtual bool isContainer () const
virtual bool isFlag () const
virtual ~BoundRef ()=default
virtual bool isContainer () const
virtual bool isFlag () const
Public Attributes
L m_lambda
Additional Inherited Members
Protected Member Functions inherited from Catch::Detail::NonCopyable
NonCopyable () noexcept=default
NonCopyable () noexcept=default
Detailed Description
template<typename L>
struct Catch::Clara::Detail::BoundLambda< L >
Definition at line 4829 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
BoundLambda() [1/2]
template<typename L> Catch::Clara::Detail::BoundLambda< L >::BoundLambda (L const & lambda) inline explicit
Definition at line 4835 of file catch_amalgamated.hpp.
References m_lambda.
Referenced by Catch::Clara::Detail::BoundManyLambda< L >::BoundManyLambda().
BoundLambda() [2/2]
template<typename L> Catch::Clara::Detail::BoundLambda< L >::BoundLambda (L const & lambda) inline explicit
Definition at line 407 of file catch_clara.hpp.
References m_lambda.
Member Function Documentation
setValue() [1/2]
template<typename L> auto Catch::Clara::Detail::BoundLambda< L >::setValue (std::string const & arg) ->ParserResult inline override virtual
Implements Catch::Clara::Detail::BoundValueRefBase.
Definition at line 4837 of file catch_amalgamated.hpp.
References Catch::Clara::Detail::invokeLambda(), and m_lambda.
setValue() [2/2]
template<typename L> auto Catch::Clara::Detail::BoundLambda< L >::setValue (std::string const & arg) ->ParserResult inline override virtual
Implements Catch::Clara::Detail::BoundValueRefBase.
Definition at line 409 of file catch_clara.hpp.
References Catch::Clara::Detail::invokeLambda(), and m_lambda.
Member Data Documentation
m_lambda
template<typename L> L Catch::Clara::Detail::BoundLambda< L >::m_lambda
Definition at line 4830 of file catch_amalgamated.hpp.
Referenced by BoundLambda(), and setValue().
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_clara.hpp