libthe-seed: Catch::MessageInfo Struct Reference
Catch::MessageInfo Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
MessageInfo (StringRef _macroName, SourceLineInfo const &_lineInfo, ResultWas::OfType _type)
bool operator== (MessageInfo const &other) const
bool operator< (MessageInfo const &other) const
MessageInfo (StringRef _macroName, SourceLineInfo const &_lineInfo, ResultWas::OfType _type)
bool operator== (MessageInfo const &other) const
bool operator< (MessageInfo const &other) const
Public Attributes
StringRef macroName
std::string message
SourceLineInfo lineInfo
ResultWas::OfType type
unsigned int sequence
Detailed Description
Definition at line 4201 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
MessageInfo() [1/2]
Catch::MessageInfo::MessageInfo (StringRef _macroName, SourceLineInfo const & _lineInfo, ResultWas::OfType _type)
Definition at line 4460 of file catch_amalgamated.cpp.
References lineInfo, macroName, sequence, and type.
Referenced by operator<(), and operator==().
MessageInfo() [2/2]
Catch::MessageInfo::MessageInfo (StringRef _macroName, SourceLineInfo const & _lineInfo, ResultWas::OfType _type)
References lineInfo, macroName, message, sequence, and type.
Member Function Documentation
operator<() [1/2]
bool Catch::MessageInfo::operator< (MessageInfo const & other) const inline
Definition at line 4215 of file catch_amalgamated.hpp.
References MessageInfo(), and sequence.
operator<() [2/2]
bool Catch::MessageInfo::operator< (MessageInfo const & other) const inline
Definition at line 33 of file catch_message_info.hpp.
References MessageInfo(), and sequence.
operator==() [1/2]
bool Catch::MessageInfo::operator== (MessageInfo const & other) const inline
Definition at line 4212 of file catch_amalgamated.hpp.
References MessageInfo(), and sequence.
operator==() [2/2]
bool Catch::MessageInfo::operator== (MessageInfo const & other) const inline
Definition at line 30 of file catch_message_info.hpp.
References MessageInfo(), and sequence.
Member Data Documentation
lineInfo
SourceLineInfo Catch::MessageInfo::lineInfo
Definition at line 4208 of file catch_amalgamated.hpp.
Referenced by MessageInfo().
macroName
StringRef Catch::MessageInfo::macroName
Definition at line 4206 of file catch_amalgamated.hpp.
Referenced by MessageInfo().
message
std::string Catch::MessageInfo::message
Definition at line 4207 of file catch_amalgamated.hpp.
Referenced by MessageInfo().
sequence
unsigned int Catch::MessageInfo::sequence
Definition at line 4210 of file catch_amalgamated.hpp.
Referenced by MessageInfo(), operator<(), and operator==().
type
ResultWas::OfType Catch::MessageInfo::type
Definition at line 4209 of file catch_amalgamated.hpp.
Referenced by MessageInfo().
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_message_info.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_message_info.cpp