libthe-seed: Catch::Benchmark::Detail::ChronometerModel< Clock > Struct Template Reference
Catch::Benchmark::Detail::ChronometerModel< Clock > Struct Template Reference final
#include <catch_amalgamated.hpp>
Public Member Functions
void start () override
void finish () override
ClockDuration< Clock > elapsed () const
void start () override
void finish () override
IDuration elapsed () const
Public Member Functions inherited from Catch::Benchmark::Detail::ChronometerConcept
virtual ~ChronometerConcept ()
ChronometerConcept ()=default
ChronometerConcept (ChronometerConcept const &)=default
ChronometerConcept & operator= (ChronometerConcept const &)=default
virtual ~ChronometerConcept ()
ChronometerConcept ()=default
ChronometerConcept (ChronometerConcept const &)=default
ChronometerConcept & operator= (ChronometerConcept const &)=default
Public Attributes
TimePoint< Clock > started
TimePoint< Clock > finished
Detailed Description
template<typename Clock>
struct Catch::Benchmark::Detail::ChronometerModel< Clock >
Definition at line 1552 of file catch_amalgamated.hpp.
Member Function Documentation
elapsed() [1/2]
template<typename Clock> ClockDuration< Clock > Catch::Benchmark::Detail::ChronometerModel< Clock >::elapsed () const inline
Definition at line 1556 of file catch_amalgamated.hpp.
References finished, and started.
Referenced by Catch::Benchmark::Detail::measure_one(), Catch::Benchmark::ExecutionPlan< Duration >::run(), and Catch::Benchmark::ExecutionPlan< Duration >::run().
elapsed() [2/2]
template<typename Clock> IDuration Catch::Benchmark::Detail::ChronometerModel< Clock >::elapsed () const inline
Definition at line 35 of file catch_chronometer.hpp.
References finished, and started.
finish() [1/2]
template<typename Clock> void Catch::Benchmark::Detail::ChronometerModel< Clock >::finish () inline override virtual
Implements Catch::Benchmark::Detail::ChronometerConcept.
Definition at line 1554 of file catch_amalgamated.hpp.
References finished.
finish() [2/2]
template<typename Clock> void Catch::Benchmark::Detail::ChronometerModel< Clock >::finish () inline override virtual
Implements Catch::Benchmark::Detail::ChronometerConcept.
Definition at line 33 of file catch_chronometer.hpp.
References finished.
start() [1/2]
template<typename Clock> void Catch::Benchmark::Detail::ChronometerModel< Clock >::start () inline override virtual
Implements Catch::Benchmark::Detail::ChronometerConcept.
Definition at line 1553 of file catch_amalgamated.hpp.
References started.
start() [2/2]
template<typename Clock> void Catch::Benchmark::Detail::ChronometerModel< Clock >::start () inline override virtual
Implements Catch::Benchmark::Detail::ChronometerConcept.
Definition at line 32 of file catch_chronometer.hpp.
References started.
Member Data Documentation
finished
template<typename Clock> TimePoint< Clock > Catch::Benchmark::Detail::ChronometerModel< Clock >::finished
Definition at line 1559 of file catch_amalgamated.hpp.
Referenced by elapsed(), and finish().
started
template<typename Clock> TimePoint< Clock > Catch::Benchmark::Detail::ChronometerModel< Clock >::started
Definition at line 1558 of file catch_amalgamated.hpp.
Referenced by elapsed(), and start().
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/benchmark/catch_chronometer.hpp