libthe-seed: Catch::Matchers::CasedString Struct Reference
Catch::Matchers::CasedString Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
CasedString (std::string const &str, CaseSensitive caseSensitivity)
std::string adjustString (std::string const &str) const
StringRef caseSensitivitySuffix () const
CasedString (std::string const &str, CaseSensitive caseSensitivity)
std::string adjustString (std::string const &str) const
StringRef caseSensitivitySuffix () const
Public Attributes
CaseSensitive m_caseSensitivity
std::string m_str
Detailed Description
Definition at line 11878 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
CasedString() [1/2]
Catch::Matchers::CasedString::CasedString (std::string const & str, CaseSensitive caseSensitivity)
Definition at line 7805 of file catch_amalgamated.cpp.
References adjustString(), m_caseSensitivity, and m_str.
CasedString() [2/2]
Catch::Matchers::CasedString::CasedString (std::string const & str, CaseSensitive caseSensitivity)
Member Function Documentation
adjustString() [1/2]
std::string Catch::Matchers::CasedString::adjustString (std::string const & str) const
Definition at line 7809 of file catch_amalgamated.cpp.
References m_caseSensitivity, Catch::No, and Catch::toLower().
Referenced by CasedString().
adjustString() [2/2]
std::string Catch::Matchers::CasedString::adjustString (std::string const & str) const
caseSensitivitySuffix() [1/2]
StringRef Catch::Matchers::CasedString::caseSensitivitySuffix () const
Definition at line 7814 of file catch_amalgamated.cpp.
References m_caseSensitivity, and Catch::Yes.
caseSensitivitySuffix() [2/2]
StringRef Catch::Matchers::CasedString::caseSensitivitySuffix () const
References m_caseSensitivity, and m_str.
Member Data Documentation
m_caseSensitivity
CaseSensitive Catch::Matchers::CasedString::m_caseSensitivity
Definition at line 11883 of file catch_amalgamated.hpp.
Referenced by adjustString(), CasedString(), and caseSensitivitySuffix().
m_str
std::string Catch::Matchers::CasedString::m_str
Definition at line 11884 of file catch_amalgamated.hpp.
Referenced by CasedString(), and caseSensitivitySuffix().
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/matchers/catch_matchers_string.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/matchers/catch_matchers_string.cpp