libthe-seed: Catch::AutoReg Struct Reference
Catch::AutoReg Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
AutoReg (Detail::unique_ptr< ITestInvoker > invoker, SourceLineInfo const &lineInfo, StringRef classOrMethod, NameAndTags const &nameAndTags) noexcept
AutoReg (Detail::unique_ptr< ITestInvoker > invoker, SourceLineInfo const &lineInfo, StringRef classOrMethod, NameAndTags const &nameAndTags) noexcept
Additional Inherited Members
Protected Member Functions inherited from Catch::Detail::NonCopyable
NonCopyable () noexcept=default
NonCopyable () noexcept=default
Detailed Description
Definition at line 6120 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
AutoReg() [1/2]
Catch::AutoReg::AutoReg (Detail::unique_ptr< ITestInvoker > invoker, SourceLineInfo const & lineInfo, StringRef classOrMethod, NameAndTags const & nameAndTags) noexcept
Definition at line 6580 of file catch_amalgamated.cpp.
References CATCH_CATCH_ALL, CATCH_MOVE, CATCH_TRY, Catch::getMutableRegistryHub(), Catch::makeTestCaseInfo(), Catch::IMutableRegistryHub::registerStartupException(), and Catch::IMutableRegistryHub::registerTest().
AutoReg() [2/2]
Catch::AutoReg::AutoReg (Detail::unique_ptr< ITestInvoker > invoker, SourceLineInfo const & lineInfo, StringRef classOrMethod, NameAndTags const & nameAndTags) noexcept
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/internal/catch_test_registry.hpp
external/Catch2/extras/catch_amalgamated.cpp
external/Catch2/src/catch2/internal/catch_test_registry.cpp