libthe-seed: Catch::MessageBuilder Struct Reference
Catch::MessageBuilder Struct Reference
#include <catch_amalgamated.hpp>
Public Member Functions
MessageBuilder (StringRef macroName, SourceLineInfo const &lineInfo, ResultWas::OfType type)
template<typename T>
MessageBuilder && operator<< (T const &value) &&
MessageBuilder (StringRef macroName, SourceLineInfo const &lineInfo, ResultWas::OfType type)
template<typename T>
MessageBuilder && operator<< (T const &value) &&
Public Member Functions inherited from Catch::MessageStream
template<typename T>
MessageStream & operator<< (T const &value)
template<typename T>
MessageStream & operator<< (T const &value)
Public Attributes
MessageInfo m_info
Public Attributes inherited from Catch::MessageStream
ReusableStringStream m_stream
Detailed Description
Definition at line 4245 of file catch_amalgamated.hpp.
Constructor & Destructor Documentation
MessageBuilder() [1/2]
Catch::MessageBuilder::MessageBuilder (StringRef macroName, SourceLineInfo const & lineInfo, ResultWas::OfType type) inline
Definition at line 4246 of file catch_amalgamated.hpp.
References m_info.
Referenced by operator<<().
MessageBuilder() [2/2]
Catch::MessageBuilder::MessageBuilder (StringRef macroName, SourceLineInfo const & lineInfo, ResultWas::OfType type) inline
Definition at line 39 of file catch_message.hpp.
References m_info.
Member Function Documentation
operator<<() [1/2]
template<typename T> MessageBuilder && Catch::MessageBuilder::operator<< (T const & value) && inline
Definition at line 4252 of file catch_amalgamated.hpp.
References CATCH_MOVE, Catch::MessageStream::m_stream, and MessageBuilder().
operator<<() [2/2]
template<typename T> MessageBuilder && Catch::MessageBuilder::operator<< (T const & value) && inline
Definition at line 45 of file catch_message.hpp.
References CATCH_MOVE, Catch::MessageStream::m_stream, and MessageBuilder().
Member Data Documentation
m_info
MessageInfo Catch::MessageBuilder::m_info
Definition at line 4257 of file catch_amalgamated.hpp.
Referenced by MessageBuilder().
The documentation for this struct was generated from the following files:
external/Catch2/extras/catch_amalgamated.hpp
external/Catch2/src/catch2/catch_message.hpp