libthe-seed: external/Catch2/tests/SelfTest/IntrospectiveTests/TestSpec.tests.cpp File Reference
TestSpec.tests.cpp File Reference
#include <catch2/catch_config.hpp>
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>
#include <catch2/internal/catch_test_spec_parser.hpp>
#include <catch2/catch_user_config.hpp>
#include <catch2/catch_test_case_info.hpp>
#include <catch2/internal/catch_commandline.hpp>
#include <catch2/generators/catch_generators.hpp>
#include <catch2/internal/catch_compiler_capabilities.hpp>
#include <helpers/parse_test_spec.hpp>
Functions
TEST_CASE ("Parse test names and tags", "[command-line][test-spec][approvals]")
TEST_CASE ("#1905 -- test spec parser properly clears internal state between compound tests", "[command-line][test-spec]")
TEST_CASE ("#1912 -- test spec parser handles escaping", "[command-line][test-spec]")
TEST_CASE ("Test spec serialization is round-trippable", "[test-spec][serialization][approvals]")
Function Documentation
TEST_CASE() [1/4]
TEST_CASE ("#1905 -- test spec parser properly clears internal state between compound tests" , "" [command-line][test-spec])
Definition at line 301 of file TestSpec.tests.cpp.
References Catch::parseTestSpec(), REQUIRE, and REQUIRE_FALSE.
TEST_CASE() [2/4]
TEST_CASE ("#1912 -- test spec parser handles escaping" , "" [command-line][test-spec])
Definition at line 312 of file TestSpec.tests.cpp.
References Catch::parseTestSpec(), REQUIRE, REQUIRE_FALSE, and SECTION.
TEST_CASE() [3/4]
TEST_CASE ("Parse test names and tags" , "" [command-line][test-spec][approvals])
Definition at line 26 of file TestSpec.tests.cpp.
References CHECK, CHECK_FALSE, Catch::parseTestSpec(), and SECTION.
TEST_CASE() [4/4]
TEST_CASE ("Test spec serialization is round-trippable" , "" [test-spec][serialization][approvals])
Definition at line 330 of file TestSpec.tests.cpp.
References CHECK, Catch::parseTestSpec(), SECTION, and Catch::ReusableStringStream::str().