libthe-seed: tests/test_DependencyLister.cpp File Reference
test_DependencyLister.cpp File Reference
#include <catch_amalgamated.hpp>
#include <libthe-seed/DependencyLister.hpp>
#include "../src/PeParser.hpp"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>
Functions
TEST_CASE ("DependencyLister extracts direct dependencies from ELF", "[DependencyLister][US1]")
TEST_CASE ("DependencyLister reports missing file errors", "[DependencyLister][US1]")
TEST_CASE ("DependencyLister reports non-binary file errors", "[DependencyLister][US1]")
TEST_CASE ("DependencyLister continues processing after per-file errors", "[DependencyLister][US1]")
TEST_CASE ("ELF file without PT_DYNAMIC produces empty dependencies", "[DependencyLister][US1]")
TEST_CASE ("DependencyLister resolves transitive dependencies", "[DependencyLister][US2]")
TEST_CASE ("DependencyLister uses canonical absolute keys when resolvable", "[DependencyLister][US2]")
TEST_CASE ("DependencyLister aggregates shared dependencies", "[DependencyLister][US2]")
TEST_CASE ("DependencyLister uses recorded name when unresolved", "[DependencyLister][US2]")
TEST_CASE ("PeParser reads DLL dependencies from fixture", "[DependencyLister][US3]")
TEST_CASE ("DependencyLister auto-detects PE format", "[DependencyLister][US3]")
TEST_CASE ("DependencyLister reports errors for truncated PE files", "[DependencyLister][US3]")
Function Documentation
TEST_CASE() [1/12]
TEST_CASE ("DependencyLister aggregates shared dependencies" , "" [DependencyLister][US2])
Definition at line 201 of file test_DependencyLister.cpp.
References DependencyLister::ListDependencies(), and REQUIRE.
TEST_CASE() [2/12]
TEST_CASE ("DependencyLister auto-detects PE format" , "" [DependencyLister][US3])
Definition at line 246 of file test_DependencyLister.cpp.
References DependencyLister::ListDependencies(), and REQUIRE.
TEST_CASE() [3/12]
TEST_CASE ("DependencyLister continues processing after per-file errors" , "" [DependencyLister][US1])
Definition at line 141 of file test_DependencyLister.cpp.
References DependencyLister::ListDependencies(), REQUIRE, and REQUIRE_FALSE.
TEST_CASE() [4/12]
TEST_CASE ("DependencyLister extracts direct dependencies from ELF" , "" [DependencyLister][US1])
Definition at line 104 of file test_DependencyLister.cpp.
References DependencyLister::ListDependencies(), REQUIRE, and REQUIRE_FALSE.
TEST_CASE() [5/12]
TEST_CASE ("DependencyLister reports errors for truncated PE files" , "" [DependencyLister][US3])
Definition at line 257 of file test_DependencyLister.cpp.
References DependencyLister::ListDependencies(), and REQUIRE.
TEST_CASE() [6/12]
TEST_CASE ("DependencyLister reports missing file errors" , "" [DependencyLister][US1])
Definition at line 114 of file test_DependencyLister.cpp.
References DependencyLister::ListDependencies(), and REQUIRE.
TEST_CASE() [7/12]
TEST_CASE ("DependencyLister reports non-binary file errors" , "" [DependencyLister][US1])
Definition at line 124 of file test_DependencyLister.cpp.
References DependencyLister::ListDependencies(), and REQUIRE.
TEST_CASE() [8/12]
TEST_CASE ("DependencyLister resolves transitive dependencies" , "" [DependencyLister][US2])
Definition at line 170 of file test_DependencyLister.cpp.
References DependencyLister::ListDependencies(), and REQUIRE.
TEST_CASE() [9/12]
TEST_CASE ("DependencyLister uses canonical absolute keys when resolvable" , "" [DependencyLister][US2])
Definition at line 180 of file test_DependencyLister.cpp.
References DependencyLister::ListDependencies(), and REQUIRE.
TEST_CASE() [10/12]
TEST_CASE ("DependencyLister uses recorded name when unresolved" , "" [DependencyLister][US2])
Definition at line 228 of file test_DependencyLister.cpp.
References DependencyLister::ListDependencies(), and REQUIRE.
TEST_CASE() [11/12]
TEST_CASE ("ELF file without PT_DYNAMIC produces empty dependencies" , "" [DependencyLister][US1])
Definition at line 157 of file test_DependencyLister.cpp.
References DependencyLister::ListDependencies(), and REQUIRE.
TEST_CASE() [12/12]
TEST_CASE ("PeParser reads DLL dependencies from fixture" , "" [DependencyLister][US3])
Definition at line 238 of file test_DependencyLister.cpp.
References PeParser::ListDependencies(), and REQUIRE.