libthe-seed: external/Catch2/tests/SelfTest/IntrospectiveTests/TextFlow.tests.cpp File Reference
TextFlow.tests.cpp File Reference
#include <catch2/catch_test_macros.hpp>
#include <catch2/internal/catch_textflow.hpp>
#include <sstream>
Classes
class Column
Functions
TEST_CASE ("TextFlow::Column one simple line", "[TextFlow][column][approvals]")
TEST_CASE ("TextFlow::Column respects already present newlines", "[TextFlow][column][approvals]")
TEST_CASE ("TextFlow::Column respects width setting", "[TextFlow][column][approvals]")
TEST_CASE ("TextFlow::Column respects indentation setting", "[TextFlow][column][approvals]")
TEST_CASE ("TextFlow::Column indentation respects whitespace", "[TextFlow][column][approvals]")
TEST_CASE ("TextFlow::Column linebreaking prefers boundary characters", "[TextFlow][column][approvals]")
TEST_CASE ("TextFlow::Column respects indentation for empty lines", "[TextFlow][column][approvals][!shouldfail]")
TEST_CASE ("TextFlow::Column leading/trailing whitespace", "[TextFlow][column][approvals]")
TEST_CASE ("TextFlow::Column can handle empty string", "[TextFlow][column][approvals]")
TEST_CASE ("#1400 - TextFlow::Column wrapping would sometimes duplicate words", "[TextFlow][column][regression][approvals]")
Function Documentation
TEST_CASE() [1/10]
TEST_CASE ("#1400 - TextFlow::Column wrapping would sometimes duplicate words" , "" [TextFlow][column][regression][approvals])
Definition at line 184 of file TextFlow.tests.cpp.
References Catch::TextFlow::Column::indent(), REQUIRE, and Catch::TextFlow::Column::width().
TEST_CASE() [2/10]
TEST_CASE ("TextFlow::Column can handle empty string" , "" [TextFlow][column][approvals])
Definition at line 178 of file TextFlow.tests.cpp.
References REQUIRE.
TEST_CASE() [3/10]
TEST_CASE ("TextFlow::Column indentation respects whitespace" , "" [TextFlow][column][approvals])
Definition at line 96 of file TextFlow.tests.cpp.
References Catch::TextFlow::Column::indent(), Catch::TextFlow::Column::initialIndent(), REQUIRE, and SECTION.
TEST_CASE() [4/10]
TEST_CASE ("TextFlow::Column leading/trailing whitespace" , "" [TextFlow][column][approvals])
Definition at line 158 of file TextFlow.tests.cpp.
References REQUIRE, and SECTION.
TEST_CASE() [5/10]
TEST_CASE ("TextFlow::Column linebreaking prefers boundary characters" , "" [TextFlow][column][approvals])
Definition at line 109 of file TextFlow.tests.cpp.
References REQUIRE, SECTION, and Catch::TextFlow::Column::width().
TEST_CASE() [6/10]
TEST_CASE ("TextFlow::Column one simple line" , "" [TextFlow][column][approvals])
Definition at line 24 of file TextFlow.tests.cpp.
References REQUIRE.
TEST_CASE() [7/10]
TEST_CASE ("TextFlow::Column respects already present newlines" , "" [TextFlow][column][approvals])
Definition at line 31 of file TextFlow.tests.cpp.
References REQUIRE.
TEST_CASE() [8/10]
TEST_CASE ("TextFlow::Column respects indentation for empty lines" , "" [TextFlow][column][approvals][!shouldfail])
Definition at line 135 of file TextFlow.tests.cpp.
References Catch::TextFlow::Column::indent(), and REQUIRE.
TEST_CASE() [9/10]
TEST_CASE ("TextFlow::Column respects indentation setting" , "" [TextFlow][column][approvals])
Definition at line 71 of file TextFlow.tests.cpp.
References Catch::TextFlow::Column::indent(), Catch::TextFlow::Column::initialIndent(), REQUIRE, and SECTION.
TEST_CASE() [10/10]
TEST_CASE ("TextFlow::Column respects width setting" , "" [TextFlow][column][approvals])
Definition at line 37 of file TextFlow.tests.cpp.
References REQUIRE, SECTION, and Catch::TextFlow::Column::width().