libthe-seed: external/Catch2/tests/SelfTest/IntrospectiveTests/ToString.tests.cpp File Reference
ToString.tests.cpp File Reference
#include <catch2/internal/catch_enum_values_registry.hpp>
#include <catch2/matchers/catch_matchers_vector.hpp>
#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_template_test_macros.hpp>
Enumerations
enum class EnumClass3 {
Value1 , Value2 , Value3 , Value4 ,
Value1 , Value2 , Value3 , Value4
}
Functions
TEST_CASE ("parseEnums", "[Strings][enums]")
TEST_CASE ("Directly creating an EnumInfo")
TEST_CASE ("Range type with sentinel")
TEST_CASE ("convertIntoString stringification helper", "[toString][approvals]")
TEMPLATE_TEST_CASE ("Stringifying char arrays with statically known sizes", "[toString]", char, signed char, unsigned char)
Enumeration Type Documentation
EnumClass3
enum class EnumClass3 strong
Enumerator
Value1
Value2
Value3
Value4
Value1
Value2
Value3
Value4
Definition at line 14 of file ToString.tests.cpp.
Function Documentation
TEMPLATE_TEST_CASE()
TEMPLATE_TEST_CASE ("Stringifying char arrays with statically known sizes" , "" [toString], char , signed char , unsigned char)
Definition at line 86 of file ToString.tests.cpp.
References CHECK, and Catch::Detail::stringify().
TEST_CASE() [1/4]
TEST_CASE ("convertIntoString stringification helper" , "" [toString][approvals])
Definition at line 64 of file ToString.tests.cpp.
References CHECK, Catch::Detail::convertIntoString(), and SECTION.
TEST_CASE() [2/4]
TEST_CASE ("Directly creating an EnumInfo")
Definition at line 50 of file ToString.tests.cpp.
References CHECK, and Catch::Detail::makeEnumInfo().
TEST_CASE() [3/4]
TEST_CASE ("parseEnums" , "" [Strings][enums])
Definition at line 24 of file ToString.tests.cpp.
References CHECK_THAT, Catch::Matchers::Equals(), Catch::Detail::parseEnums(), and SECTION.
TEST_CASE() [4/4]
TEST_CASE ("Range type with sentinel")
Definition at line 60 of file ToString.tests.cpp.
References CHECK, and Catch::Detail::stringify().