libthe-seed: external/Catch2/tests/SelfTest/UsageTests/ToStringVector.tests.cpp File Reference
ToStringVector.tests.cpp File Reference
#include <catch2/catch_test_macros.hpp>
#include <vector>
#include <array>
Functions
TEST_CASE ("vector<int> -> toString", "[toString][vector]")
TEST_CASE ("vector<string> -> toString", "[toString][vector]")
TEST_CASE ("vector<int,allocator> -> toString", "[toString][vector,allocator]")
TEST_CASE ("vec<vec<string,alloc>> -> toString", "[toString][vector,allocator]")
TEST_CASE ("vector<bool> -> toString", "[toString][containers][vector]")
TEST_CASE ("array<int, N> -> toString", "[toString][containers][array]")
Function Documentation
TEST_CASE() [1/6]
TEST_CASE ("array<int, N> -> toString" , "" [toString][containers][array])
Definition at line 87 of file ToStringVector.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [2/6]
TEST_CASE ("vec<vec<string,alloc>> -> toString" , "" [toString][vector, allocator])
Definition at line 68 of file ToStringVector.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [3/6]
TEST_CASE ("vector<bool> -> toString" , "" [toString][containers][vector])
Definition at line 79 of file ToStringVector.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [4/6]
TEST_CASE ("vector<int,allocator> -> toString" , "" [toString][vector, allocator])
Definition at line 59 of file ToStringVector.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [5/6]
TEST_CASE ("vector<int> -> toString" , "" [toString][vector])
Definition at line 14 of file ToStringVector.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [6/6]
TEST_CASE ("vector<string> -> toString" , "" [toString][vector])
Definition at line 24 of file ToStringVector.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().