libthe-seed: external/Catch2/tests/SelfTest/UsageTests/ToStringWhich.tests.cpp File Reference
ToStringWhich.tests.cpp File Reference
#include <catch2/catch_test_macros.hpp>
Namespaces
namespace Catch
Functions
TEST_CASE ("stringify(has_operator)", "[toString]")
TEST_CASE ("stringify(has_maker)", "[toString]")
TEST_CASE ("stringify(has_maker_and_operator)", "[toString]")
TEST_CASE ("stringify(has_neither)", "[toString]")
TEST_CASE ("stringify(has_template_operator)", "[toString]")
TEST_CASE ("stringify(vectors<has_operator>)", "[toString]")
TEST_CASE ("stringify(vectors<has_maker>)", "[toString]")
TEST_CASE ("stringify(vectors<has_maker_and_operator>)", "[toString]")
TEST_CASE ("stringify ranges", "[toString]")
Function Documentation
TEST_CASE() [1/9]
TEST_CASE ("stringify ranges" , "" [toString])
Definition at line 181 of file ToStringWhich.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [2/9]
TEST_CASE ("stringify(has_maker)" , "" [toString])
Definition at line 68 of file ToStringWhich.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [3/9]
TEST_CASE ("stringify(has_maker_and_operator)" , "" [toString])
Definition at line 74 of file ToStringWhich.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [4/9]
TEST_CASE ("stringify(has_neither)" , "" [toString])
Definition at line 79 of file ToStringWhich.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [5/9]
TEST_CASE ("stringify(has_operator)" , "" [toString])
Definition at line 62 of file ToStringWhich.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [6/9]
TEST_CASE ("stringify(has_template_operator)" , "" [toString])
Definition at line 85 of file ToStringWhich.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [7/9]
TEST_CASE ("stringify(vectors<has_maker>)" , "" [toString])
Definition at line 98 of file ToStringWhich.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [8/9]
TEST_CASE ("stringify(vectors<has_maker_and_operator>)" , "" [toString])
Definition at line 103 of file ToStringWhich.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().
TEST_CASE() [9/9]
TEST_CASE ("stringify(vectors<has_operator>)" , "" [toString])
Definition at line 93 of file ToStringWhich.tests.cpp.
References REQUIRE, and Catch::Detail::stringify().