libthe-seed: external/Catch2/tests/SelfTest/IntrospectiveTests/Xml.tests.cpp File Reference
Xml.tests.cpp File Reference
#include <catch2/catch_test_macros.hpp>
#include <catch2/internal/catch_xmlwriter.hpp>
#include <catch2/internal/catch_reusable_string_stream.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>
#include <sstream>
Functions
TEST_CASE ("XmlEncode", "[XML]")
TEST_CASE ("XmlEncode: UTF-8", "[XML][UTF-8][approvals]")
TEST_CASE ("XmlWriter writes boolean attributes as true/false", "[XML][XmlWriter]")
TEST_CASE ("XmlWriter does not escape comments", "[XML][XmlWriter][approvals]")
TEST_CASE ("XmlWriter errors out when writing text without enclosing element", "[XmlWriter][approvals]")
TEST_CASE ("XmlWriter escapes text properly", "[XML][XmlWriter][approvals]")
TEST_CASE ("XmlWriter escapes attributes properly", "[XML][XmlWriter][approvals]")
Function Documentation
TEST_CASE() [1/7]
TEST_CASE ("XmlEncode" , "" [XML])
Definition at line 23 of file Xml.tests.cpp.
References Catch::XmlEncode::ForAttributes, REQUIRE, and SECTION.
TEST_CASE() [2/7]
TEST_CASE ("XmlEncode: UTF-8" , "" [XML][UTF-8][approvals])
Definition at line 54 of file Xml.tests.cpp.
References CHECK, and SECTION.
TEST_CASE() [3/7]
TEST_CASE ("XmlWriter does not escape comments" , "" [XML][XmlWriter][approvals])
Definition at line 141 of file Xml.tests.cpp.
References Catch::Matchers::ContainsSubstring(), REQUIRE_THAT, and Catch::XmlWriter::writeComment().
TEST_CASE() [4/7]
TEST_CASE ("XmlWriter errors out when writing text without enclosing element" , "" [XmlWriter][approvals])
Definition at line 153 of file Xml.tests.cpp.
References REQUIRE_THROWS, and Catch::XmlWriter::writeText().
TEST_CASE() [5/7]
TEST_CASE ("XmlWriter escapes attributes properly" , "" [XML][XmlWriter][approvals])
Definition at line 172 of file Xml.tests.cpp.
References Catch::Matchers::ContainsSubstring(), REQUIRE_THAT, Catch::XmlWriter::scopedElement(), and Catch::XmlWriter::ScopedElement::writeAttribute().
TEST_CASE() [6/7]
TEST_CASE ("XmlWriter escapes text properly" , "" [XML][XmlWriter][approvals])
Definition at line 159 of file Xml.tests.cpp.
References Catch::Matchers::ContainsSubstring(), REQUIRE_THAT, Catch::XmlWriter::scopedElement(), and Catch::XmlWriter::ScopedElement::writeText().
TEST_CASE() [7/7]
TEST_CASE ("XmlWriter writes boolean attributes as true/false" , "" [XML][XmlWriter])
Definition at line 125 of file Xml.tests.cpp.
References Catch::Matchers::ContainsSubstring(), REQUIRE_THAT, Catch::XmlWriter::scopedElement(), and Catch::XmlWriter::ScopedElement::writeAttribute().